Dolibarr: BlockedLog Class Reference
BlockedLog Class Reference
Class to manage Blocked Log.
Public Member Functions
__construct (DoliDB $db)
Constructor.
getObjectLink ()
Try to retrieve source object (it it still exists)
getUser ()
try to retrieve user author
setObjectData (&$object, $action, $amounts, $fuser=null)
Populate properties of log from object data.
fetch ($id)
Get object from database.
dolDecodeBlockedData ($data, $mode=0)
Decode data.
setCertified ()
Set block certified by authority.
create ($user, $forcesignature= '')
Create blocked log in database.
checkSignature ($previoushash= '')
Check if current signature still correct compared to the value in chain.
getPreviousHash ($withlock=0, $beforeid=0)
Get previous signature/hash in chain.
getLog ($element, $fk_object, $limit=0, $sortfield= '', $sortorder= '', $search_fk_user=-1, $search_start=-1, $search_end=-1, $search_ref= '', $search_amount= '', $search_code= '')
Return array of log objects (with criterias)
getSignature ()
Return the signature (hash) of the "genesis-block" (Block 0).
alreadyUsed ($ignoresystem=0)
Check if module was already used or not for at least one recording.
Private Member Functions
buildKeyForSignature ()
Return a string for signature.
Detailed Description
Class to manage Blocked Log.
Definition at line 35 of file blockedlog.class.php.
Constructor & Destructor Documentation
__construct (DoliDB $db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 126 of file blockedlog.class.php.
References db.
Member Function Documentation
alreadyUsed ($ignoresystem = 0)
Check if module was already used or not for at least one recording.
Parameters
int $ignoresystem Ignore system events for the test
Returns
bool
Definition at line 1070 of file blockedlog.class.php.
References db, dol_print_error(), and dol_syslog().
buildKeyForSignature () private
Return a string for signature.
Note: rowid of line not included as it is not a business data and this allow to make backup of a year and restore it into another database with different id wihtout comprimising checksums
Returns
string Key for signature
Definition at line 907 of file blockedlog.class.php.
Referenced by checkSignature(), and create().
checkSignature ($previoushash = '')
Check if current signature still correct compared to the value in chain.
Parameters
string $previoushash If previous signature hash is known, we can provide it to avoid to make a search of it in database.
Returns
boolean True if OK, False if KO
Definition at line 878 of file blockedlog.class.php.
References buildKeyForSignature(), dol_hash(), and getPreviousHash().
create ($user, $forcesignature = '')
Create blocked log in database.
Parameters
User $user Object user that create
int $forcesignature Force signature (for example '0000000000' when we disabled the module)
Returns
int <0 if KO, >0 if OK
Definition at line 763 of file blockedlog.class.php.
References buildKeyForSignature(), db, dol_hash(), dol_now(), dol_syslog(), and getPreviousHash().
dolDecodeBlockedData ($data, $mode = 0)
Decode data.
Parameters
string $data Data to unserialize
string $mode 0=unserialize, 1=json_decode
Returns
string Value unserialized
Definition at line 728 of file blockedlog.class.php.
Referenced by fetch().
fetch ($id)
Get object from database.
Parameters
int $id Id of object to load
Returns
int >0 if OK, <0 if KO, 0 if not found
Definition at line 654 of file blockedlog.class.php.
References $resql, db, dol_syslog(), and dolDecodeBlockedData().
getLog ($element, $fk_object, $limit = 0, $sortfield = '', $sortorder = '', $search_fk_user = -1, $search_start = -1, $search_end = -1, $search_ref = '', $search_amount = '', $search_code = '')
Return array of log objects (with criterias)
Parameters
string $element element to search
int $fk_object id of object to search
int $limit max number of element, 0 for all
string $sortfield sort field
string $sortorder sort order
int $search_fk_user id of user(s)
int $search_start start time limit
int $search_end end time limit
string $search_ref search ref
string $search_amount search amount
string $search_code search code
Returns
array|int Array of object log or <0 if error
Definition at line 972 of file blockedlog.class.php.
References db, and natural_search().
getObjectLink ()
Try to retrieve source object (it it still exists)
Returns
string
Definition at line 185 of file blockedlog.class.php.
References db.
getPreviousHash ($withlock = 0, $beforeid = 0)
Get previous signature/hash in chain.
Parameters
int $withlock 1=With a lock
int $beforeid ID of a record
Returns
string Hash of previous record (if beforeid is defined) or hash of last record (if beforeid is 0)
Definition at line 921 of file blockedlog.class.php.
References $resql, db, dol_print_error(), and getSignature().
Referenced by checkSignature(), and create().
getSignature ()
Return the signature (hash) of the "genesis-block" (Block 0).
Returns
string Signature of genesis-block for current conf->entity
Definition at line 1044 of file blockedlog.class.php.
References dol_hash(), dolibarr_set_const(), and getRandomPassword().
Referenced by getPreviousHash().
getUser ()
try to retrieve user author
Returns
string
Definition at line 310 of file blockedlog.class.php.
References db.
setCertified ()
Set block certified by authority.
Returns
boolean
Definition at line 747 of file blockedlog.class.php.
References db.
setObjectData (& $object, $action, $amounts, $fuser = null)
Populate properties of log from object data.
Parameters
Object $object object to store
string $action action
string $amounts amounts
User $fuser User object (forced)
Returns
int >0 if OK, <0 if KO
Definition at line 339 of file blockedlog.class.php.
References db, dol_getIdFromCode(), and dol_syslog().
The documentation for this class was generated from the following file:
htdocs/blockedlog/class/blockedlog.class.php