Dolibarr: htdocs/core/lib/donation.lib.php File Reference
donation.lib.php File Reference
Library of donation functions.
Functions
donation_admin_prepare_head ()
Prepare array with list of admin tabs.
donation_prepare_head ($object)
Prepare array with list of tabs.
Detailed Description
Library of donation functions.
Definition in file donation.lib.php.
Function Documentation
donation_admin_prepare_head ()
Prepare array with list of admin tabs.
Returns
array Array of tabs to show
Definition at line 29 of file donation.lib.php.
References complete_head_from_modules().
donation_prepare_head ($object)
Prepare array with list of tabs.
Parameters
Don $object Donation
Returns
array Array of tabs to show
Definition at line 63 of file donation.lib.php.
References complete_head_from_modules(), Link\count(), dol_dir_list(), dol_sanitizeFileName(), and get_exdir().