Dolibarr: FormBank Class Reference
FormBank Class Reference
Class to manage generation of HTML components for bank module.
Public Member Functions
__construct ($db)
Constructor.
selectTypeOfBankAccount ($selected=Account::TYPE_CURRENT, $htmlname= 'type')
Retourne la liste des types de comptes financiers.
Static Public Member Functions
static getIBANLabel (Account $account)
Returns the name of the Iban label.
Detailed Description
Class to manage generation of HTML components for bank module.
Definition at line 30 of file html.formbank.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 48 of file html.formbank.class.php.
References db.
Member Function Documentation
static getIBANLabel (Account $account) static
Returns the name of the Iban label.
India uses 'IFSC' and the rest of the world 'IBAN' name.
Parameters
Account $account Account object
Returns
string
Definition at line 73 of file html.formbank.class.php.
References Account\getCountryCode().
Referenced by pdf_bank().
selectTypeOfBankAccount ($selected = Account::TYPE_CURRENT, $htmlname = 'type')
Retourne la liste des types de comptes financiers.
Parameters
integer $selected Type pre-selectionne
string $htmlname Nom champ formulaire
Returns
void
Definition at line 60 of file html.formbank.class.php.
References db, print, and Form\selectarray().
The documentation for this class was generated from the following file:
htdocs/core/class/html.formbank.class.php