Dolibarr: htdocs/core/modules/printsheet/modules_labels.php File Reference
modules_labels.php File Reference
Module foundation
File of parent class of document generator for members labels sheets.
Data Structures
class ModelePDFLabels
Parent class of document generator for address sheet.
Functions
doc_label_pdf_create ($db, $arrayofrecords, $modele, $outputlangs, $outputdir= '', $template= 'standardlabel', $filename= 'tmp_address_sheet.pdf')
Create a document onto disk according to template module.
Detailed Description
File of parent class of document generator for members labels sheets.
Definition in file modules_labels.php.
Function Documentation
doc_label_pdf_create ($db, $arrayofrecords, $modele, $outputlangs, $outputdir = '', $template = 'standardlabel', $filename = 'tmp_address_sheet.pdf')
Create a document onto disk according to template module.
Parameters
DoliDB $db Database handler
array $arrayofrecords Array of records
string $modele Force le modele a utiliser ('' to not force)
Translate $outputlangs Objet lang a utiliser pour traduction
string $outputdir Output directory
string $template pdf generenate document class to use default 'standardlabel'
string $filename Short file name of PDF output file
Returns
int <0 if KO, >0 if OK
Definition at line 80 of file modules_labels.php.
References dol_buildpath(), dol_print_error(), dol_strlen(), and dol_syslog().