Dolibarr: DolibarrApi Class Reference
DolibarrApi Class Reference
Class for API REST v1.
Public Member Functions
__construct ($db, $cachedir= '', $refreshCache=false)
Constructor.
Protected Member Functions
_cleanObjectDatas ($object)
Executed method when API is called without parameter.
_checkFilters ($sqlfilters)
Return if a $sqlfilters parameter is valid.
Static Protected Member Functions
static _checkAccessToResource ($resource, $resource_id=0, $dbtablename= '', $feature2= '', $dbt_keyfield= 'fk_soc', $dbt_select= 'rowid')
Check user access to a resource.
static _forge_criteria_callback ($matches)
Function to forge a SQL criteria.
Detailed Description
Class for API REST v1.
Definition at line 29 of file api.class.php.
Constructor & Destructor Documentation
__construct ($db, $cachedir = '', $refreshCache = false)
Constructor.
Parameters
DoliDb $db Database handler
string $cachedir Cache dir
boolean $refreshCache Update cache
Definition at line 49 of file api.class.php.
References db.
Member Function Documentation
static _checkAccessToResource ($resource, $resource_id = 0, $dbtablename = '', $feature2 = '', $dbt_keyfield = 'fk_soc', $dbt_select = 'rowid') static protected
Check user access to a resource.
Check access by user to a given resource
Parameters
string $resource element to check
int $resource_id Object ID if we want to check a particular record (optional) is linked to a owned thirdparty (optional).
string $dbtablename 'TableName&SharedElement' with Tablename is table where object is stored. SharedElement is an optional key to define where to check entity. Not used if objectid is null (optional)
string $feature2 Feature to check, second level of permission (optional). Can be or check with 'level1|level2'.
string $dbt_keyfield Field name for socid foreign key if not fk_soc. Not used if objectid is null (optional)
string $dbt_select Field name for select if not rowid. Not used if objectid is null (optional)
Returns
bool
Exceptions
RestException
Definition at line 223 of file api.class.php.
References checkUserAccessToObject().
Referenced by Contracts\activateLine(), Contacts\addCategory(), Thirdparties\addCategory(), Invoices\addContact(), SupplierInvoices\addPayment(), Invoices\addPayment(), Invoices\addPaymentDistributed(), Thirdparties\addSupplierCategory(), Tasks\addTimeSpent(), Contracts\close(), Proposals\close(), Orders\close(), Interventions\closeFichinter(), Contacts\createUser(), Warehouses\delete(), MembersTypes\delete(), Categories\delete(), Boms\delete(), Donations\delete(), Members\delete(), MyModuleApi\delete(), SupplierOrders\delete(), AgendaEvents\delete(), SupplierInvoices\delete(), Contacts\delete(), Interventions\delete(), Products\delete(), Users\delete(), Tickets\delete(), ExpenseReports\delete(), Shipments\delete(), Projects\delete(), Tasks\delete(), Thirdparties\delete(), Contracts\delete(), Orders\delete(), Proposals\delete(), Invoices\delete(), Contacts\deleteCategory(), Thirdparties\deleteCategory(), Invoices\deleteContact(), Orders\deleteContact(), Proposals\deleteContact(), Orders\deleteLine(), Shipments\deleteLine(), Proposals\deleteLine(), Contracts\deleteLine(), Invoices\deleteLine(), Thirdparties\deleteSupplierCategory(), MembersTypes\get(), Members\get(), Warehouses\get(), Donations\get(), Invoices\get(), SupplierOrders\get(), AgendaEvents\get(), Boms\get(), Proposals\get(), Supplierproposals\get(), ExpenseReports\get(), Orders\get(), Shipments\get(), SupplierInvoices\get(), Projects\get(), Tasks\get(), MyModuleApi\get(), Contracts\get(), Products\get(), Contacts\get(), Thirdparties\get(), Interventions\get(), Categories\get(), Users\get(), Tickets\getCommon(), Thirdparties\getCompanyBankAccount(), Thirdparties\getFixedAmountDiscounts(), Thirdparties\getInvoicesQualifiedForCreditNote(), Thirdparties\getInvoicesQualifiedForReplacement(), Projects\getLines(), Proposals\getLines(), Contracts\getLines(), Orders\getLines(), Invoices\getLines(), Categories\getObjects(), Thirdparties\getOutStandingInvoices(), Thirdparties\getOutStandingOrder(), Thirdparties\getOutStandingProposals(), SupplierInvoices\getPayments(), Invoices\getPayments(), Projects\getRoles(), Tasks\getRoles(), Thirdparties\getSocieteAccounts(), Invoices\markAsCreditAvailable(), Thirdparties\merge(), Invoices\postContact(), Orders\postContact(), Proposals\postContact(), Proposals\postLine(), Interventions\postLine(), Contracts\postLine(), Orders\postLine(), Invoices\postLine(), MembersTypes\put(), Warehouses\put(), Members\put(), Users\put(), Categories\put(), Boms\put(), Donations\put(), MyModuleApi\put(), Products\put(), SupplierOrders\put(), Thirdparties\put(), SupplierInvoices\put(), Contacts\put(), Tickets\put(), ExpenseReports\put(), Shipments\put(), Projects\put(), Tasks\put(), Contracts\put(), Orders\put(), Proposals\put(), Invoices\put(), Contracts\putLine(), Proposals\putLine(), Orders\putLine(), Invoices\putLine(), Users\setGroup(), Orders\setinvoiced(), Proposals\setinvoiced(), Proposals\settodraft(), Invoices\settodraft(), Orders\settodraft(), Invoices\settopaid(), Invoices\settounpaid(), Contracts\unactivateLine(), Invoices\useCreditNote(), Invoices\useDiscount(), Donations\validate(), SupplierOrders\validate(), SupplierInvoices\validate(), Interventions\validate(), Shipments\validate(), Projects\validate(), Contracts\validate(), Orders\validate(), Proposals\validate(), and Invoices\validate().
_checkFilters ($sqlfilters) protected
Return if a $sqlfilters parameter is valid.
Parameters
string $sqlfilters sqlfilter string
Returns
boolean True if valid, False if not valid
Definition at line 250 of file api.class.php.
References dol_syslog().
Referenced by Invoices\get(), Donations\get(), SupplierOrders\get(), Orders\get(), Supplierproposals\get(), Proposals\get(), Shipments\get(), SupplierInvoices\get(), Projects\get(), Contracts\get(), Contacts\get(), Interventions\get(), Setup\getAvailability(), Setup\getListOfCivilities(), Setup\getListOfCountries(), Setup\getListOfCurrencies(), Setup\getListOfEventTypes(), Setup\getListOfExtrafields(), Setup\getListOfMeasuringUnits(), Setup\getListOfTowns(), Setup\getPaymentTerms(), Setup\getPaymentTypes(), Setup\getShippingModes(), Setup\getTicketsCategories(), Setup\getTicketsSeverities(), Setup\getTicketsTypes(), BankAccounts\index(), Users\index(), Subscriptions\index(), MembersTypes\index(), Members\index(), Warehouses\index(), StockMovements\index(), ExpenseReports\index(), Boms\index(), AgendaEvents\index(), MyModuleApi\index(), Tasks\index(), Categories\index(), Products\index(), Thirdparties\index(), and Tickets\index().
_cleanObjectDatas ($object) protected
Executed method when API is called without parameter.
Display a short message an return a http code 200
Returns
array Clean sensible object datas
Parameters
object $object Object to clean
Returns
array Array of cleaned object properties
Definition at line 97 of file api.class.php.
Referenced by Subscriptions\get(), and Subscriptions\index().
static _forge_criteria_callback ($matches) static protected
Function to forge a SQL criteria.
Parameters
array $matches Array of found string by regex search. Example: "t.ref:like:'SO-%'" or "t.date_creation:<:'20160101'" or "t.nature:is:NULL"
Returns
string Forged criteria. Example: "t.field like 'abc%'"
Definition at line 282 of file api.class.php.
The documentation for this class was generated from the following file:
htdocs/api/class/api.class.php