Dolibarr: Menubase Class Reference
Menubase Class Reference
Class to manage menu entries.
Public Member Functions
__construct ($db, $menu_handler= '')
Constructor.
create ($user=null)
Create menu entry into database.
update ($user=null, $notrigger=0)
Update menu entry into database.
fetch ($id, $user=null)
Load object in memory from database.
delete ($user)
Delete object in database.
initAsSpecimen ()
Initialise an instance with random values.
menuTopCharger ($mymainmenu, $myleftmenu, $type_user, $menu_handler, &$tabMenu)
Load tabMenu array with top menu entries found into database.
menuLeftCharger ($newmenu, $mymainmenu, $myleftmenu, $type_user, $menu_handler, &$tabMenu)
Load entries found from database (and stored into $tabMenu) in $this->newmenu array.
menuLoad ($mymainmenu, $myleftmenu, $type_user, $menu_handler, &$tabMenu)
Load entries found in database into variable $tabMenu.
Private Member Functions
recur ($tab, $pere, $level)
Complete this->newmenu with menu entry found in $tab.
Detailed Description
Class to manage menu entries.
Definition at line 30 of file menubase.class.php.
Constructor & Destructor Documentation
__construct ($db, $menu_handler = '')
Constructor.
Parameters
DoliDB $db Database handler
string $menu_handler Menu handler
Definition at line 94 of file menubase.class.php.
References db.
Member Function Documentation
create ($user = null)
Create menu entry into database.
Parameters
User $user User that create
Returns
int <0 if KO, Id of record if OK
Definition at line 108 of file menubase.class.php.
References $resql, db, dol_print_error(), dol_syslog(), type, and user.
delete ($user)
Delete object in database.
Parameters
User $user User that delete
Returns
int <0 if KO, >0 if OK
Definition at line 387 of file menubase.class.php.
References $resql, db, and dol_syslog().
fetch ($id, $user = null)
Load object in memory from database.
Parameters
int $id Id object
User $user User that load
Returns
int <0 if KO, >0 if OK
Definition at line 313 of file menubase.class.php.
References $resql, db, dol_syslog(), type, and user.
initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
void
Definition at line 413 of file menubase.class.php.
References type, and user.
menuLeftCharger ($newmenu, $mymainmenu, $myleftmenu, $type_user, $menu_handler, & $tabMenu)
Load entries found from database (and stored into $tabMenu) in $this->newmenu array.
Warning: Entries in $tabMenu must have child after parent
Parameters
Menu $newmenu Menu array to complete (in most cases, it's empty, may be already initialized with some menu manager like eldy)
string $mymainmenu Value for mainmenu to filter menu to load (often $_SESSION["mainmenu"])
string $myleftmenu Value for leftmenu to filter menu to load (always '')
int $type_user 0=Menu for backoffice, 1=Menu for front office
string $menu_handler Filter on name of menu_handler used (auguria, eldy...)
array $tabMenu Array with menu entries already loaded
Returns
Menu Menu array for particular mainmenu value or full tabArray
Definition at line 476 of file menubase.class.php.
References dol_syslog(), and recur().
menuLoad ($mymainmenu, $myleftmenu, $type_user, $menu_handler, & $tabMenu)
Load entries found in database into variable $tabMenu.
Note that only "database menu entries" are loaded here, hardcoded will not be present into output.
Parameters
string $mymainmenu Value for mainmenu that defined mainmenu
string $myleftmenu Value for left that defined leftmenu
int $type_user Looks for menu entry for 0=Internal users, 1=External users
string $menu_handler Name of menu_handler used ('auguria', 'eldy'...)
array $tabMenu Array to store new entries found (in most cases, it's empty, but may be alreay filled)
Returns
int >0 if OK, <0 if KO
Definition at line 565 of file menubase.class.php.
References $resql, db, dol_print_error(), dol_syslog(), make_substitutions(), and verifCond().
menuTopCharger ($mymainmenu, $myleftmenu, $type_user, $menu_handler, & $tabMenu)
Load tabMenu array with top menu entries found into database.
Parameters
string $mymainmenu Value for mainmenu to filter menu to load (always '')
string $myleftmenu Value for leftmenu to filter menu to load (always '')
int $type_user 0=Menu for backoffice, 1=Menu for front office
string $menu_handler Filter on name of menu_handler used (auguria, eldy...)
array $tabMenu If array with menu entries already loaded, we put this array here (in most cases, it's empty)
Returns
array Return array with menu entries for top menu
Definition at line 447 of file menubase.class.php.
recur ($tab, $pere, $level) private
Complete this->newmenu with menu entry found in $tab.
Parameters
array $tab Tab array with all menu entries
int $pere Id of parent
int $level Level
Returns
void
Definition at line 704 of file menubase.class.php.
Referenced by menuLeftCharger().
update ($user = null, $notrigger = 0)
Update menu entry into database.
Parameters
User $user User that modify
int $notrigger 0=no, 1=yes (no update trigger)
Returns
int <0 if KO, >0 if OK
Definition at line 248 of file menubase.class.php.
References $resql, db, dol_syslog(), type, and user.
The documentation for this class was generated from the following file:
htdocs/core/class/menubase.class.php