Dolibarr: htdocs/admin/tools/eaccelerator.php File Reference
eaccelerator.php File Reference
Page administration de eaccelerator.
Functions
if(!is_array($info)) compare ($x, $y)
Compare revisions.
revcompare ($x, $y)
Compare revisions.
create_script_table ($list)
Output table.
create_key_table ($list)
Output table.
Detailed Description
Page administration de eaccelerator.
Definition in file eaccelerator.php.
Function Documentation
if (!is_array($info)) compare ($x, $y)
Compare revisions.
Parameters
array $x Parts of version 1
array $y Parts of version 2
Returns
int -1 if 1<2, 0 if 1=2, 1 if 1>2
Definition at line 78 of file eaccelerator.php.
create_key_table ($list)
Output table.
Parameters
array $list Array of records
Returns
void
Definition at line 191 of file eaccelerator.php.
References create_script_table(), dol_print_date(), llxFooter(), load_fiche_titre(), and print.
create_script_table ($list)
Output table.
Parameters
array $list Array of records
Returns
void
Definition at line 117 of file eaccelerator.php.
References GETPOST(), and print.
Referenced by create_key_table().
revcompare ($x, $y)
Compare revisions.
Parameters
array $x Parts of version 1
array $y Parts of version 2
Returns
int 1 if 1<2, 0 if 1=2, -1 if 1>2
Definition at line 98 of file eaccelerator.php.