Dolibarr: Documents Class Reference
Documents Class Reference
API class for receive files.
Public Member Functions
__construct ()
Constructor.
index ($modulepart, $original_file= '')
Download a document.
builddoc ($modulepart, $original_file= '', $doctemplate= '', $langcode= '')
Build a document.
getDocumentsListByElement ($modulepart, $id=0, $ref= '', $sortfield= '', $sortorder= '')
Return the list of documents of a dedicated element (from its ID or Ref)
Public Member Functions inherited from DolibarrApi
__construct ($db, $cachedir= '', $refreshCache=false)
Constructor.
Private Member Functions
_validate_file ($data)
Validate fields before create or update object.
Additional Inherited Members
Protected Member Functions inherited from DolibarrApi
_cleanObjectDatas ($object)
Executed method when API is called without parameter.
_checkFilters ($sqlfilters)
Return if a $sqlfilters parameter is valid.
Static Protected Member Functions inherited from DolibarrApi
static _checkAccessToResource ($resource, $resource_id=0, $dbtablename= '', $feature2= '', $dbt_keyfield= 'fk_soc', $dbt_select= 'rowid')
Check user access to a resource.
static _forge_criteria_callback ($matches)
Function to forge a SQL criteria.
Detailed Description
API class for receive files.
protected ,external}
Definition at line 33 of file api_documents.class.php.
Member Function Documentation
_validate_file ($data) private
Validate fields before create or update object.
Parameters
array $data Array with data to verify
Returns
array
Exceptions
RestException
Definition at line 604 of file api_documents.class.php.
builddoc ($modulepart, $original_file = '', $doctemplate = '', $langcode = '')
Build a document.
Test sample 1: { "module_part": "invoice", "original_file": "FA1701-001/FA1701-001.pdf", "doctemplate": "crabe", "langcode": "fr_FR" }.
Parameters
string $modulepart Name of module or area concerned by file download ('invoice', 'order', ...).
string $original_file Relative path with filename, relative to modulepart (for example: IN201701-999/IN201701-999.pdf).
string $doctemplate Set here the doc template to use for document generation (If not set, use the default template).
string $langcode Language code like 'en_US', 'fr_FR', 'es_ES', ... (If not set, use the default language).
Returns
array List of documents
Exceptions
500
501
400
401
404
200 PUT /builddoc
Definition at line 130 of file api_documents.class.php.
References db, dol_check_secure_access_document(), dol_mimetype(), and dol_osencode().
getDocumentsListByElement ($modulepart, $id = 0, $ref = '', $sortfield = '', $sortorder = '')
Return the list of documents of a dedicated element (from its ID or Ref)
Parameters
string $modulepart Name of module or area concerned ('thirdparty', 'member', 'proposal', 'order', 'invoice', 'shipment', 'project', ...)
int $id ID of element
string $ref Ref of element
string $sortfield Sort criteria ('','fullname','relativename','name','date','size')
string $sortorder Sort order ('asc' or 'desc')
Returns
array Array of documents with path
Exceptions
200
400
401
404
500 GET /
Definition at line 248 of file api_documents.class.php.
References db, dol_basename(), dol_check_secure_access_document(), dol_delete_file(), dol_dir_list(), dol_is_dir(), dol_is_file(), dol_move(), dol_sanitizeFileName(), dol_sanitizePathName(), and get_exdir().
index ($modulepart, $original_file = '')
Download a document.
Note that, this API is similar to using the wrapper link "documents.php" to download a file (used for internal HTML links of documents into application), but with no need to have a session cookie (the token is used instead).
Parameters
string $modulepart Name of module or area concerned by file download ('facture', ...)
string $original_file Relative path with filename, relative to modulepart (for example: IN201701-999/IN201701-999.pdf)
Returns
array List of documents
Exceptions
400
401
404
200 GET /download
Definition at line 70 of file api_documents.class.php.
References dol_check_secure_access_document(), dol_mimetype(), dol_osencode(), and dol_syslog().
The documentation for this class was generated from the following file:
htdocs/api/class/api_documents.class.php