Dolibarr: mod_facture_fournisseur_tulip Class Reference
mod_facture_fournisseur_tulip Class Reference
Tulip Class of numbering models of suppliers invoices references.
Public Member Functions
info ()
Returns the description of the model numbering.
getExample ()
Returns a numbering example.
getNextValue ($objsoc, $object, $mode= 'next')
Return next value.
getNumRef ($objsoc, $objforref, $mode= 'next')
Return next free value.
Public Member Functions inherited from ModeleNumRefSuppliersInvoices
isEnabled ()
Return if a model can be used or not.
info ()
Returns the default description of the model numbering.
getExample ()
Returns a numbering example.
canBeActivated ()
Tests if the numbers already in force in the database do not cause conflicts that would prevent this numbering.
getNextValue ($objsoc, $object, $mode)
Returns next value assigned.
getVersion ()
Returns version of the model numbering.
Detailed Description
Tulip Class of numbering models of suppliers invoices references.
Definition at line 37 of file mod_facture_fournisseur_tulip.php.
Member Function Documentation
getExample ()
Returns a numbering example.
Returns
string Example
Definition at line 132 of file mod_facture_fournisseur_tulip.php.
References getNextValue().
getNextValue ($objsoc, $object, $mode = 'next')
Return next value.
Parameters
Societe $objsoc Object third party
Object $object Object invoice
string $mode 'next' for next value or 'last' for last value
Returns
string Value if OK, 0 if KO
Definition at line 156 of file mod_facture_fournisseur_tulip.php.
References get_next_value().
Referenced by getExample(), and getNumRef().
getNumRef ($objsoc, $objforref, $mode = 'next')
Return next free value.
Parameters
Societe $objsoc Object third party
string $objforref Object for number to search
string $mode 'next' for next value or 'last' for last value
Returns
string Next free value
Definition at line 195 of file mod_facture_fournisseur_tulip.php.
References getNextValue().
info ()
Returns the description of the model numbering.
Returns
string Description Text
Definition at line 68 of file mod_facture_fournisseur_tulip.php.
References db.
The documentation for this class was generated from the following file:
htdocs/core/modules/supplier_invoice/mod_facture_fournisseur_tulip.php