Dolibarr: FormBarCode Class Reference
FormBarCode Class Reference
Class to manage barcode HTML.
Public Member Functions
__construct ($db)
Constructor.
setBarcodeEncoder ($selected, $barcodelist, $code_id, $idForm= 'formbarcode')
Return HTML select with list of bar code generators.
select_barcode_type ($selected= '', $htmlname= 'barcodetype_id', $useempty=0)
Print form to select type of barcode.
selectBarcodeType ($selected= '', $htmlname= 'barcodetype_id', $useempty=0)
Return html form to select type of barcode.
form_barcode_type ($page, $selected= '', $htmlname= 'barcodetype_id')
Show form to select type of barcode.
formBarcodeType ($page, $selected= '', $htmlname= 'barcodetype_id')
Return html form to select type of barcode.
Detailed Description
Class to manage barcode HTML.
Definition at line 30 of file html.formbarcode.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 48 of file html.formbarcode.class.php.
References db.
Member Function Documentation
form_barcode_type ($page, $selected = '', $htmlname = 'barcodetype_id')
Show form to select type of barcode.
Parameters
string $page Page
int $selected Id condition preselected
string $htmlname Nom du formulaire select
Returns
void
Deprecated:
Definition at line 196 of file html.formbarcode.class.php.
References formBarcodeType(), and print.
formBarcodeType ($page, $selected = '', $htmlname = 'barcodetype_id')
Return html form to select type of barcode.
Parameters
string $page Page
int $selected Id condition preselected
string $htmlname Nom du formulaire select
Returns
string
Definition at line 210 of file html.formbarcode.class.php.
References selectBarcodeType().
Referenced by form_barcode_type().
select_barcode_type ($selected = '', $htmlname = 'barcodetype_id', $useempty = 0)
Print form to select type of barcode.
Parameters
int $selected Id code pre-selected
string $htmlname Name of HTML select field
int $useempty Affiche valeur vide dans liste
Returns
void
Deprecated:
Definition at line 126 of file html.formbarcode.class.php.
References print, and selectBarcodeType().
selectBarcodeType ($selected = '', $htmlname = 'barcodetype_id', $useempty = 0)
Return html form to select type of barcode.
Parameters
int $selected Id code pre-selected
string $htmlname Name of HTML select field
int $useempty Display empty value in select
Returns
string
Definition at line 140 of file html.formbarcode.class.php.
References ajax_combobox(), db, and dol_print_error().
Referenced by formBarcodeType(), and select_barcode_type().
setBarcodeEncoder ($selected, $barcodelist, $code_id, $idForm = 'formbarcode')
Return HTML select with list of bar code generators.
Parameters
int $selected Id code pre-selected
array $barcodelist Array of barcodes generators
int $code_id Id du code barre
int $idForm Id du formulaire
Returns
string HTML select string
Definition at line 63 of file html.formbarcode.class.php.
References print.
The documentation for this class was generated from the following file:
htdocs/core/class/html.formbarcode.class.php