Dolibarr: htdocs/core/modules/member/modules_cards.php File Reference
modules_cards.php File Reference
Module foundation
File of parent class of document generator for members cards.
Data Structures
class ModelePDFCards
Parent class of document generator for members cards.
Functions
members_card_pdf_create ($db, $arrayofmembers, $modele, $outputlangs, $outputdir= '', $template= 'standard')
Cree un fichier de cartes de visites en fonction du modele de ADHERENT_CARDS_ADDON_PDF.
Detailed Description
File of parent class of document generator for members cards.
Definition in file modules_cards.php.
Function Documentation
members_card_pdf_create ($db, $arrayofmembers, $modele, $outputlangs, $outputdir = '', $template = 'standard')
Cree un fichier de cartes de visites en fonction du modele de ADHERENT_CARDS_ADDON_PDF.
Parameters
DoliDB $db Database handler
array $arrayofmembers Array of members
string $modele Force modele to use ('' to not force)
Translate $outputlangs Object langs to use for translation
string $outputdir Output directory
string $template pdf generenate document class to use default 'standard'
Returns
int <0 if KO, >0 if OK
Definition at line 79 of file modules_cards.php.
References dol_buildpath(), dol_print_error(), and dol_strlen().