Dolibarr: Thirdparties Class Reference
Thirdparties Class Reference
Public Member Functions
__construct ()
Constructor.
get ($id)
Get properties of a thirdparty object.
index ($sortfield="t.rowid", $sortorder= 'ASC', $limit=100, $page=0, $mode=0, $sqlfilters= '')
List thirdparties.
post ($request_data=null)
Create thirdparty object.
put ($id, $request_data=null)
Update thirdparty.
merge ($id, $idtodelete)
Merge a thirdparty into another one.
delete ($id)
Delete thirdparty.
getCategories ($id, $sortfield="s.rowid", $sortorder= 'ASC', $limit=0, $page=0)
Get customer categories for a thirdparty.
addCategory ($id, $category_id)
Add a customer category to a thirdparty.
deleteCategory ($id, $category_id)
Remove the link between a customer category and the thirdparty.
getSupplierCategories ($id, $sortfield="s.rowid", $sortorder= 'ASC', $limit=0, $page=0)
Get supplier categories for a thirdparty.
addSupplierCategory ($id, $category_id)
Add a supplier category to a thirdparty.
deleteSupplierCategory ($id, $category_id)
Remove the link between a category and the thirdparty.
getOutStandingProposals ($id, $mode= 'customer')
Get outstanding proposals of thirdparty.
getOutStandingOrder ($id, $mode= 'customer')
Get outstanding orders of thirdparty.
getOutStandingInvoices ($id, $mode= 'customer')
Get outstanding invoices of thirdparty.
getFixedAmountDiscounts ($id, $filter="none", $sortfield="f.type", $sortorder= 'ASC')
Get fixed amount discount of a thirdparty (all sources: deposit, credit note, commercial offers...)
getInvoicesQualifiedForReplacement ($id)
Return list of invoices qualified to be replaced by another invoice.
getInvoicesQualifiedForCreditNote ($id)
Return list of invoices qualified to be corrected by a credit note.
getCompanyBankAccount ($id)
Get CompanyBankAccount objects for thirdparty.
createCompanyBankAccount ($id, $request_data=null)
Create CompanyBankAccount object for thirdparty.
updateCompanyBankAccount ($id, $bankaccount_id, $request_data=null)
Update CompanyBankAccount object for thirdparty.
deleteCompanyBankAccount ($id, $bankaccount_id)
Delete a bank account attached to a thirdparty.
generateBankAccountDocument ($id, $companybankid=null, $model= 'sepamandate')
Generate a Document from a bank account record (like SEPA mandate)
getSocieteAccounts ($id, $site=null)
Get a specific gateway attached to a thirdparty (by specifying the site key)
createSocieteAccount ($id, $request_data=null)
Create and attach a new gateway to an existing thirdparty.
putSocieteAccount ($id, $site, $request_data=null)
Create and attach a new (or replace an existing) specific site gateway to a thirdparty.
patchSocieteAccount ($id, $site, $request_data=null)
Update specified values of a specific site gateway attached to a thirdparty.
Public Member Functions inherited from DolibarrApi
__construct ($db, $cachedir= '', $refreshCache=false)
Constructor.
Protected Member Functions
_cleanObjectDatas ($object)
Clean sensible object datas.
Protected Member Functions inherited from DolibarrApi
_cleanObjectDatas ($object)
Executed method when API is called without parameter.
_checkFilters ($sqlfilters)
Return if a $sqlfilters parameter is valid.
Private Member Functions
_validate ($data)
Validate fields before create or update object.
Additional Inherited Members
Static Protected Member Functions inherited from DolibarrApi
static _checkAccessToResource ($resource, $resource_id=0, $dbtablename= '', $feature2= '', $dbt_keyfield= 'fk_soc', $dbt_select= 'rowid')
Check user access to a resource.
static _forge_criteria_callback ($matches)
Function to forge a SQL criteria.
Detailed Description
Definition at line 29 of file api_thirdparties.class.php.
Member Function Documentation
_cleanObjectDatas ($object) protected
Clean sensible object datas.
Parameters
object $object Object to clean
Returns
array Array of cleaned object properties
Definition at line 1636 of file api_thirdparties.class.php.
Referenced by addCategory(), addSupplierCategory(), createSocieteAccount(), deleteCategory(), deleteSupplierCategory(), get(), index(), patchSocieteAccount(), and putSocieteAccount().
_validate ($data) private
Validate fields before create or update object.
Parameters
array $data Datas to validate
Returns
array
Exceptions
RestException
Definition at line 1663 of file api_thirdparties.class.php.
Referenced by post().
addCategory ($id, $category_id)
Add a customer category to a thirdparty.
Parameters
int $id Id of thirdparty
int $category_id Id of category
Returns
mixed
POST {id}/categories/{category_id}
Definition at line 543 of file api_thirdparties.class.php.
References DolibarrApi\_checkAccessToResource(), _cleanObjectDatas(), and db.
addSupplierCategory ($id, $category_id)
Add a supplier category to a thirdparty.
Parameters
int $id Id of thirdparty
int $category_id Id of category
Returns
mixed
POST {id}/supplier_categories/{category_id}
Definition at line 661 of file api_thirdparties.class.php.
References DolibarrApi\_checkAccessToResource(), _cleanObjectDatas(), and db.
createCompanyBankAccount ($id, $request_data = null)
Create CompanyBankAccount object for thirdparty.
Parameters
int $id ID of thirdparty
array $request_data Request data
Returns
object ID of thirdparty
POST {id}/bankaccounts
Definition at line 1089 of file api_thirdparties.class.php.
References db.
createSocieteAccount ($id, $request_data = null)
Create and attach a new gateway to an existing thirdparty.
Possible fields for request_data (request body) are specified in llx_societe_account table.
See Table llx_societe_account wiki page for more information<br>
<u>Example body payload :</u>
{"key_account": "cus_DAVkLSs1LYyYI", "site": "stripe"}
Parameters
int $id ID of thirdparty
array $request_data Request data
Returns
SocieteAccount
Exceptions
401 Unauthorized: User does not have permission to read thirdparties
409 Conflict: A SocieteAccount entity (gateway) already exists for this company and site.
422 Unprocessable Entity: You must pass the site attribute in your request data !
500 Internal Server Error: Error creating SocieteAccount account 201
POST {id}/gateways
Definition at line 1360 of file api_thirdparties.class.php.
References _cleanObjectDatas(), and db.
delete ($id)
Delete thirdparty.
Parameters
int $id Thirparty ID
Returns
integer
Definition at line 476 of file api_thirdparties.class.php.
References DolibarrApi\_checkAccessToResource().
deleteCategory ($id, $category_id)
Remove the link between a customer category and the thirdparty.
Parameters
int $id Id of thirdparty
int $category_id Id of category
Returns
mixed
DELETE {id}/categories/{category_id}
Definition at line 581 of file api_thirdparties.class.php.
References DolibarrApi\_checkAccessToResource(), _cleanObjectDatas(), and db.
deleteCompanyBankAccount ($id, $bankaccount_id)
Delete a bank account attached to a thirdparty.
Parameters
int $id ID of thirdparty
int $bankaccount_id ID of CompanyBankAccount
Returns
int -1 if error 1 if correct deletion
DELETE {id}/bankaccounts/{bankaccount_id}
Definition at line 1159 of file api_thirdparties.class.php.
References db.
deleteSupplierCategory ($id, $category_id)
Remove the link between a category and the thirdparty.
Parameters
int $id Id of thirdparty
int $category_id Id of category
Returns
mixed
DELETE {id}/supplier_categories/{category_id}
Definition at line 699 of file api_thirdparties.class.php.
References DolibarrApi\_checkAccessToResource(), _cleanObjectDatas(), and db.
generateBankAccountDocument ($id, $companybankid = null, $model = 'sepamandate')
Generate a Document from a bank account record (like SEPA mandate)
Parameters
int $id Thirdparty id
int $companybankid Companybank id
string $model Model of document to generate
Returns
void
GET {id}/generateBankAccountDocument/{companybankid}/{model}
Definition at line 1185 of file api_thirdparties.class.php.
References conf(), db, dol_sanitizeFileName(), and GETPOST().
get ($id)
Get properties of a thirdparty object.
Return an array with thirdparty informations
Parameters
int $id ID of thirdparty
Returns
array|mixed data without useless information
Exceptions
RestException
Definition at line 74 of file api_thirdparties.class.php.
References DolibarrApi\_checkAccessToResource(), _cleanObjectDatas(), and price2num().
getCategories ($id, $sortfield = "s.rowid", $sortorder = 'ASC', $limit = 0, $page = 0)
Get customer categories for a thirdparty.
Parameters
int $id ID of thirdparty
string $sortfield Sort field
string $sortorder Sort order
int $limit Limit for list
int $page Page number
Returns
mixed
GET {id}/categories
Definition at line 504 of file api_thirdparties.class.php.
References db.
getCompanyBankAccount ($id)
Get CompanyBankAccount objects for thirdparty.
Parameters
int $id ID of thirdparty
Returns
array
GET {id}/bankaccounts
We select all the records that match the socid
Definition at line 1011 of file api_thirdparties.class.php.
References DolibarrApi\_checkAccessToResource().
getFixedAmountDiscounts ($id, $filter = "none", $sortfield = "f.type", $sortorder = 'ASC')
Get fixed amount discount of a thirdparty (all sources: deposit, credit note, commercial offers...)
Parameters
int $id ID of the thirdparty
string $filter Filter exceptional discount. "none" will return every discount, "available" returns unapplied discounts, "used" returns applied discounts { none,available,used}
string $sortfield Sort field
string $sortorder Sort order
GET {id}/fixedamountdiscounts
Returns
array List of fixed discount of thirdparty
Exceptions
400
401
404
503
Definition at line 875 of file api_thirdparties.class.php.
References DolibarrApi\_checkAccessToResource(), and db.
getInvoicesQualifiedForCreditNote ($id)
Return list of invoices qualified to be corrected by a credit note.
Invoices matching the following rules are returned (validated + payment on process) or classified (payed completely or payed partialy) + not already replaced + not already a credit note
Parameters
int $id Id of thirdparty
GET {id}/getinvoicesqualifiedforcreditnote
Returns
array
Exceptions
400
401
404
405
Definition at line 975 of file api_thirdparties.class.php.
References DolibarrApi\_checkAccessToResource(), and db.
getInvoicesQualifiedForReplacement ($id)
Return list of invoices qualified to be replaced by another invoice.
Parameters
int $id Id of thirdparty
GET {id}/getinvoicesqualifiedforreplacement
Returns
array
Exceptions
400
401
404
405
Definition at line 933 of file api_thirdparties.class.php.
References DolibarrApi\_checkAccessToResource(), and db.
getOutStandingInvoices ($id, $mode = 'customer')
Get outstanding invoices of thirdparty.
Parameters
int $id ID of the thirdparty
string $mode 'customer' or 'supplier'
GET {id}/outstandinginvoices
Returns
array List of outstandings invoices of thirdparty
Exceptions
400
401
404
Definition at line 829 of file api_thirdparties.class.php.
References DolibarrApi\_checkAccessToResource().
getOutStandingOrder ($id, $mode = 'customer')
Get outstanding orders of thirdparty.
Parameters
int $id ID of the thirdparty
string $mode 'customer' or 'supplier'
GET {id}/outstandingorders
Returns
array List of outstandings orders of thirdparty
Exceptions
400
401
404
Definition at line 786 of file api_thirdparties.class.php.
References DolibarrApi\_checkAccessToResource().
getOutStandingProposals ($id, $mode = 'customer')
Get outstanding proposals of thirdparty.
Parameters
int $id ID of the thirdparty
string $mode 'customer' or 'supplier'
GET {id}/outstandingproposals
Returns
array List of outstandings proposals of thirdparty
Exceptions
400
401
404
Definition at line 742 of file api_thirdparties.class.php.
References DolibarrApi\_checkAccessToResource().
getSocieteAccounts ($id, $site = null)
Get a specific gateway attached to a thirdparty (by specifying the site key)
Parameters
int $id ID of thirdparty
string $site Site key
Returns
SocieteAccount[]
Exceptions
401 Unauthorized: User does not have permission to read thirdparties
404 Not Found: Specified thirdparty ID does not belongs to an existing thirdparty
GET {id}/gateways/
We select all the records that match the socid
Definition at line 1284 of file api_thirdparties.class.php.
References DolibarrApi\_checkAccessToResource().
getSupplierCategories ($id, $sortfield = "s.rowid", $sortorder = 'ASC', $limit = 0, $page = 0)
Get supplier categories for a thirdparty.
Parameters
int $id ID of thirdparty
string $sortfield Sort field
string $sortorder Sort order
int $limit Limit for list
int $page Page number
Returns
mixed
GET {id}/supplier_categories
Definition at line 622 of file api_thirdparties.class.php.
References db.
index ($sortfield = "t.rowid", $sortorder = 'ASC', $limit = 100, $page = 0, $mode = 0, $sqlfilters = '')
List thirdparties.
Get a list of thirdparties
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Limit for list
int $page Page number
int $mode Set to 1 to show only customers Set to 2 to show only prospects Set to 3 to show only those are not customer neither prospect
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.nom:like:'TheCompany%') and (t.date_creation:<:'20160101')"
Returns
array Array of thirdparty objects
Definition at line 120 of file api_thirdparties.class.php.
References DolibarrApi\_checkFilters(), and _cleanObjectDatas().
merge ($id, $idtodelete)
Merge a thirdparty into another one.
Merge content (properties, notes) and objects (like invoices, events, orders, proposals, ...) of a thirdparty into a target thirdparty, then delete the merged thirdparty. If a property has a defined value both in thirdparty to delete and thirdparty to keep, the value into the thirdparty to delete will be ignored, the value of target thirdparty will remain, except for notes (content is concatenated).
Parameters
int $id ID of thirdparty to keep (the target thirdparty)
int $idtodelete ID of thirdparty to remove (the thirdparty to delete), once data has been merged into the target thirdparty.
Returns
int
PUT {id}/merge/{idtodelete}
Definition at line 270 of file api_thirdparties.class.php.
References DolibarrApi\_checkAccessToResource(), dol_concatdesc(), and dol_syslog().
patchSocieteAccount ($id, $site, $request_data = null)
Update specified values of a specific site gateway attached to a thirdparty.
Parameters
int $id Id of thirdparty
string $site Site key
array $request_data Request data
Returns
SocieteAccount
Exceptions
401 Unauthorized: User does not have permission to read thirdparties
404 Not Found: Specified thirdparty ID does not belongs to an existing thirdparty
409 Conflict: Another SocieteAccount entity already exists for this thirdparty with this site key.
500 Internal Server Error: Error updating SocieteAccount entity
PATCH {id}/gateways/{site}
Definition at line 1500 of file api_thirdparties.class.php.
References _cleanObjectDatas(), and db.
post ($request_data = null)
Create thirdparty object.
Parameters
array $request_data Request datas
Returns
int ID of thirdparty
Definition at line 206 of file api_thirdparties.class.php.
References _validate().
put ($id, $request_data = null)
Update thirdparty.
Parameters
int $id Id of thirdparty to update
array $request_data Datas
Returns
int
Definition at line 230 of file api_thirdparties.class.php.
References DolibarrApi\_checkAccessToResource().
putSocieteAccount ($id, $site, $request_data = null)
Create and attach a new (or replace an existing) specific site gateway to a thirdparty.
You MUST pass all values to keep (otherwise, they will be deleted) !
If you just need to update specific fields prefer PATCH /thirdparties/{id}/gateways/{site} endpoint.
When a SocieteAccount entity does not exist for the id and site supplied, a new one will be created. In that case fk_soc and site members form request body payload will be ignored and id and site query strings parameters will be used instead.
Parameters
int $id ID of thirdparty
string $site Site key
array $request_data Request data
Returns
SocieteAccount
Exceptions
401 Unauthorized: User does not have permission to read thirdparties
422 Unprocessable Entity: You must pass the site attribute in your request data !
500 Internal Server Error: Error updating SocieteAccount entity
RestException PUT {id}/gateways/{site}
Definition at line 1419 of file api_thirdparties.class.php.
References _cleanObjectDatas(), and db.
updateCompanyBankAccount ($id, $bankaccount_id, $request_data = null)
Update CompanyBankAccount object for thirdparty.
Parameters
int $id ID of thirdparty
int $bankaccount_id ID of CompanyBankAccount
array $request_data Request data
Returns
object ID of thirdparty
PUT {id}/bankaccounts/{bankaccount_id}
Definition at line 1124 of file api_thirdparties.class.php.
References db.
The documentation for this class was generated from the following file:
htdocs/societe/class/api_thirdparties.class.php