Dolibarr: htdocs/webservices/server_invoice.php File Reference
server_invoice.php File Reference
File that is entry point to call Dolibarr WebServices.
Functions
getInvoice ($authentication, $id= '', $ref= '', $ref_ext= '')
Get invoice from id, ref or ref_ext.
getInvoicesForThirdParty ($authentication, $idthirdparty)
Get list of invoices for third party.
createInvoice ($authentication, $invoice)
Create an invoice.
createInvoiceFromOrder ($authentication, $id_order= '', $ref_order= '', $ref_ext_order= '')
Create an invoice from an order.
updateInvoice ($authentication, $invoice)
Uddate an invoice, only change the state of an invoice.
Detailed Description
File that is entry point to call Dolibarr WebServices.
Definition in file server_invoice.php.
Function Documentation
createInvoice ($authentication, $invoice)
Create an invoice.
Parameters
array $authentication Array of authentication information
Facture $invoice Invoice
Returns
array Array result
Definition at line 537 of file server_invoice.php.
References check_authentication(), dol_now(), dol_stringtotime(), dol_syslog(), Facture\STATUS_DRAFT, and Facture\STATUS_VALIDATED.
createInvoiceFromOrder ($authentication, $id_order = '', $ref_order = '', $ref_ext_order = '')
Create an invoice from an order.
Parameters
array $authentication Array of authentication information
string $id_order id of order to copy invoice from
string $ref_order ref of order to copy invoice from
string $ref_ext_order ref_ext of order to copy invoice from
Returns
array Array result
Definition at line 657 of file server_invoice.php.
References check_authentication(), dol_now(), and dol_syslog().
getInvoice ($authentication, $id = '', $ref = '', $ref_ext = '')
Get invoice from id, ref or ref_ext.
Parameters
array $authentication Array of authentication information
int $id Id
string $ref Ref
string $ref_ext Ref_ext
Returns
array Array result
Definition at line 289 of file server_invoice.php.
References check_authentication(), dol_htmlcleanlastbr(), dol_print_date(), and dol_syslog().
getInvoicesForThirdParty ($authentication, $idthirdparty)
Get list of invoices for third party.
Parameters
array $authentication Array of authentication information
int $idthirdparty Id thirdparty
Returns
array Array result
Definition at line 402 of file server_invoice.php.
References $resql, check_authentication(), dol_print_date(), and dol_syslog().
updateInvoice ($authentication, $invoice)
Uddate an invoice, only change the state of an invoice.
Parameters
array $authentication Array of authentication information
Facture $invoice Invoice
Returns
array Array result
Definition at line 743 of file server_invoice.php.
References check_authentication(), dol_syslog(), Facture\STATUS_ABANDONED, Facture\STATUS_CLOSED, Facture\STATUS_DRAFT, and Facture\STATUS_VALIDATED.