Dolibarr: htdocs/install/upgrade2.php File Reference
upgrade2.php File Reference
Upgrade some data.
Functions
migrate_paiements ($db, $langs, $conf)
Reporte liens vers une facture de paiements sur table de jointure (lien n-n paiements factures)
migrate_paiements_orphelins_1 ($db, $langs, $conf)
Corrige paiement orphelins (liens paumes suite a bugs) Pour verifier s'il reste des orphelins: select * from llx_paiement as p left join llx_paiement_facture as pf on pf.fk_paiement=p.rowid WHERE pf.rowid IS NULL AND (p.fk_facture = 0 OR p.fk_facture IS NULL)
migrate_paiements_orphelins_2 ($db, $langs, $conf)
Corrige paiement orphelins (liens paumes suite a bugs) Pour verifier s'il reste des orphelins: select * from llx_paiement as p left join llx_paiement_facture as pf on pf.fk_paiement=p.rowid WHERE pf.rowid IS NULL AND (p.fk_facture = 0 OR p.fk_facture IS NULL)
migrate_contracts_det ($db, $langs, $conf)
Mise a jour des contrats (gestion du contrat + detail de contrat)
migrate_links_transfert ($db, $langs, $conf)
Function to migrate links into llx_bank_url.
migrate_contracts_date1 ($db, $langs, $conf)
Mise a jour des date de contrats non renseignees.
migrate_contracts_date3 ($db, $langs, $conf)
Mise a jour des dates de creation de contrat.
migrate_contracts_open ($db, $langs, $conf)
Reouverture des contrats qui ont au moins une ligne non fermee.
migrate_paiementfourn_facturefourn ($db, $langs, $conf)
Factures fournisseurs.
migrate_price_facture ($db, $langs, $conf)
Update total of invoice lines.
migrate_price_propal ($db, $langs, $conf)
Update total of proposal lines.
migrate_price_contrat ($db, $langs, $conf)
Update total of contract lines.
migrate_price_commande ($db, $langs, $conf)
Update total of sales order lines.
migrate_price_commande_fournisseur ($db, $langs, $conf)
Update total of purchase order lines.
migrate_modeles ($db, $langs, $conf)
Mise a jour des modeles selectionnes.
migrate_commande_expedition ($db, $langs, $conf)
Correspondance des expeditions et des commandes clients dans la table llx_co_exp.
migrate_commande_livraison ($db, $langs, $conf)
Correspondance des livraisons et des commandes clients dans la table llx_co_liv.
migrate_detail_livraison ($db, $langs, $conf)
Migration des details commandes dans les details livraisons.
migrate_stocks ($db, $langs, $conf)
Migration du champ stock dans produits.
migrate_menus ($db, $langs, $conf)
Migration of menus (use only 1 table instead of 3) 2.6 -> 2.7.
migrate_commande_deliveryaddress ($db, $langs, $conf)
Migration du champ fk_adresse_livraison dans expedition 2.6 -> 2.7.
migrate_restore_missing_links ($db, $langs, $conf)
Migration du champ fk_remise_except dans llx_facturedet doit correspondre a lien dans llx_societe_remise_except vers llx_facturedet.
migrate_project_user_resp ($db, $langs, $conf)
Migration du champ fk_user_resp de llx_projet vers llx_element_contact.
migrate_project_task_actors ($db, $langs, $conf)
Migration de la table llx_projet_task_actors vers llx_element_contact.
migrate_relationship_tables ($db, $langs, $conf, $table, $fk_source, $sourcetype, $fk_target, $targettype)
Migration des tables de relation.
migrate_project_task_time ($db, $langs, $conf)
Migrate duration in seconds.
migrate_customerorder_shipping ($db, $langs, $conf)
Migrate order ref_customer and date_delivery fields to llx_expedition.
migrate_shipping_delivery ($db, $langs, $conf)
Migrate link stored into fk_expedition into llx_element_element.
migrate_shipping_delivery2 ($db, $langs, $conf)
We try to complete field ref_customer and date_delivery that are empty into llx_livraison.
migrate_actioncomm_element ($db, $langs, $conf)
Migrate link stored into fk_xxxx into fk_element and elementtype.
migrate_mode_reglement ($db, $langs, $conf)
Migrate link stored into fk_mode_reglement.
migrate_clean_association ($db, $langs, $conf, $versionto)
Delete duplicates in table categorie_association.
migrate_categorie_association ($db, $langs, $conf)
Migrate categorie association.
migrate_event_assignement ($db, $langs, $conf)
Migrate event assignement to owner.
migrate_event_assignement_contact ($db, $langs, $conf)
Migrate event assignement to owner.
migrate_reset_blocked_log ($db, $langs, $conf)
Migrate to reset the blocked log for V7+ algorithm.
migrate_remise_entity ($db, $langs, $conf)
Migrate to add entity value into llx_societe_remise.
migrate_remise_except_entity ($db, $langs, $conf)
Migrate to add entity value into llx_societe_remise_except.
migrate_user_rights_entity ($db, $langs, $conf)
Migrate to add entity value into llx_user_rights.
migrate_usergroup_rights_entity ($db, $langs, $conf)
Migrate to add entity value into llx_usergroup_rights.
migrate_rename_directories ($db, $langs, $conf, $oldname, $newname)
Migration directory.
migrate_delete_old_files ($db, $langs, $conf)
Delete deprecated files.
migrate_delete_old_dir ($db, $langs, $conf)
Remove deprecated directories.
migrate_reload_modules ($db, $langs, $conf, $listofmodule=array(), $force=0)
Disable/Reenable features modules.
migrate_reload_menu ($db, $langs, $conf, $versionto)
Reload menu if dynamic menus, if modified by version.
migrate_user_photospath ()
Migrate file from old path to new one for users.
Detailed Description
Upgrade some data.
Definition in file upgrade2.php.
Function Documentation
migrate_actioncomm_element ($db, $langs, $conf)
Migrate link stored into fk_xxxx into fk_element and elementtype.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 3445 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_categorie_association ($db, $langs, $conf)
Migrate categorie association.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 3698 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_clean_association ($db, $langs, $conf, $versionto)
Delete duplicates in table categorie_association.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
string $versionto Version target
Returns
void
Definition at line 3611 of file upgrade2.php.
References $resql, dolibarr_install_syslog(), and print.
migrate_commande_deliveryaddress ($db, $langs, $conf)
Migration du champ fk_adresse_livraison dans expedition 2.6 -> 2.7.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 2497 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_commande_expedition ($db, $langs, $conf)
Correspondance des expeditions et des commandes clients dans la table llx_co_exp.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 2050 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_commande_livraison ($db, $langs, $conf)
Correspondance des livraisons et des commandes clients dans la table llx_co_liv.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 2127 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_contracts_date1 ($db, $langs, $conf)
Mise a jour des date de contrats non renseignees.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 1139 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_contracts_date3 ($db, $langs, $conf)
Mise a jour des dates de creation de contrat.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 1239 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_contracts_det ($db, $langs, $conf)
Mise a jour des contrats (gestion du contrat + detail de contrat)
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 957 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_contracts_open ($db, $langs, $conf)
Reouverture des contrats qui ont au moins une ligne non fermee.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 1266 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_customerorder_shipping ($db, $langs, $conf)
Migrate order ref_customer and date_delivery fields to llx_expedition.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 3148 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_delete_old_dir ($db, $langs, $conf)
Remove deprecated directories.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 4501 of file upgrade2.php.
References dol_delete_dir_recursive(), dolibarr_install_syslog(), and print.
migrate_delete_old_files ($db, $langs, $conf)
Delete deprecated files.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 4427 of file upgrade2.php.
References dol_delete_file(), dolibarr_install_syslog(), and print.
migrate_detail_livraison ($db, $langs, $conf)
Migration des details commandes dans les details livraisons.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 2220 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_event_assignement ($db, $langs, $conf)
Migrate event assignement to owner.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 3791 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_event_assignement_contact ($db, $langs, $conf)
Migrate event assignement to owner.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 3868 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_links_transfert ($db, $langs, $conf)
Function to migrate links into llx_bank_url.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 1055 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_menus ($db, $langs, $conf)
Migration of menus (use only 1 table instead of 3) 2.6 -> 2.7.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 2415 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_mode_reglement ($db, $langs, $conf)
Migrate link stored into fk_mode_reglement.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 3511 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_modeles ($db, $langs, $conf)
Mise a jour des modeles selectionnes.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 1992 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), ModelePDFCommandes\liste_modeles(), and ModelePDFFactures\liste_modeles().
migrate_paiementfourn_facturefourn ($db, $langs, $conf)
Factures fournisseurs.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 1325 of file upgrade2.php.
References dolibarr_install_syslog(), and print.
migrate_paiements ($db, $langs, $conf) -> close()
Reporte liens vers une facture de paiements sur table de jointure (lien n-n paiements factures)
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 593 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_paiements_orphelins_1 ($db, $langs, $conf)
Corrige paiement orphelins (liens paumes suite a bugs) Pour verifier s'il reste des orphelins: select * from llx_paiement as p left join llx_paiement_facture as pf on pf.fk_paiement=p.rowid WHERE pf.rowid IS NULL AND (p.fk_facture = 0 OR p.fk_facture IS NULL)
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 687 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_paiements_orphelins_2 ($db, $langs, $conf)
Corrige paiement orphelins (liens paumes suite a bugs) Pour verifier s'il reste des orphelins: select * from llx_paiement as p left join llx_paiement_facture as pf on pf.fk_paiement=p.rowid WHERE pf.rowid IS NULL AND (p.fk_facture = 0 OR p.fk_facture IS NULL)
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 814 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_price_commande ($db, $langs, $conf)
Update total of sales order lines.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 1758 of file upgrade2.php.
References $resql, calcul_price_total(), dolibarr_install_syslog(), and print.
migrate_price_commande_fournisseur ($db, $langs, $conf)
Update total of purchase order lines.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 1875 of file upgrade2.php.
References $resql, calcul_price_total(), dolibarr_install_syslog(), and print.
migrate_price_contrat ($db, $langs, $conf)
Update total of contract lines.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 1669 of file upgrade2.php.
References $resql, calcul_price_total(), dolibarr_install_syslog(), and print.
migrate_price_facture ($db, $langs, $conf)
Update total of invoice lines.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 1442 of file upgrade2.php.
References $resql, calcul_price_total(), dolibarr_install_syslog(), and print.
migrate_price_propal ($db, $langs, $conf)
Update total of proposal lines.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 1561 of file upgrade2.php.
References $resql, calcul_price_total(), dolibarr_install_syslog(), and print.
migrate_project_task_actors ($db, $langs, $conf)
Migration de la table llx_projet_task_actors vers llx_element_contact.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 2834 of file upgrade2.php.
References $resql, dol_now(), dol_print_error(), dolibarr_install_syslog(), and print.
migrate_project_task_time ($db, $langs, $conf)
Migrate duration in seconds.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 3027 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_project_user_resp ($db, $langs, $conf)
Migration du champ fk_user_resp de llx_projet vers llx_element_contact.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 2737 of file upgrade2.php.
References $resql, dol_now(), dol_print_error(), dolibarr_install_syslog(), and print.
migrate_relationship_tables ($db, $langs, $conf, $table, $fk_source, $sourcetype, $fk_target, $targettype)
Migration des tables de relation.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
string $table Table name
int $fk_source Id of element source
string $sourcetype Type of element source
int $fk_target Id of element target
string $targettype Type of element target
Returns
void
Definition at line 2931 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_reload_menu ($db, $langs, $conf, $versionto)
Reload menu if dynamic menus, if modified by version.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
string $versionto Version target
Returns
void
Definition at line 4790 of file upgrade2.php.
References dolibarr_install_syslog(), print, and run_sql().
migrate_reload_modules ($db, $langs, $conf, $listofmodule = array(), $force = 0)
Disable/Reenable features modules.
We must do this when internal menu of module or permissions has changed or when triggers have moved.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
array $listofmodule List of modules
int $force 1=Reload module even if not already loaded
Returns
void
Definition at line 4540 of file upgrade2.php.
References dol_include_once(), dolibarr_install_syslog(), and print.
migrate_remise_entity ($db, $langs, $conf)
Migrate to add entity value into llx_societe_remise.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 4064 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_remise_except_entity ($db, $langs, $conf)
Migrate to add entity value into llx_societe_remise_except.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 4141 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_rename_directories ($db, $langs, $conf, $oldname, $newname)
Migration directory.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
string $oldname Old name (relative to DOL_DATA_ROOT)
string $newname New name (relative to DOL_DATA_ROOT)
Returns
void
Definition at line 4407 of file upgrade2.php.
References dolibarr_install_syslog().
migrate_reset_blocked_log ($db, $langs, $conf)
Migrate to reset the blocked log for V7+ algorithm.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 3946 of file upgrade2.php.
References $resql, dol_now(), dol_print_error(), dolibarr_install_syslog(), and print.
migrate_restore_missing_links ($db, $langs, $conf)
Migration du champ fk_remise_except dans llx_facturedet doit correspondre a lien dans llx_societe_remise_except vers llx_facturedet.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
integer|null
Definition at line 2581 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), print, and versioncompare().
migrate_shipping_delivery ($db, $langs, $conf)
Migrate link stored into fk_expedition into llx_element_element.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 3249 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_shipping_delivery2 ($db, $langs, $conf)
We try to complete field ref_customer and date_delivery that are empty into llx_livraison.
We set them with value from llx_expedition.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 3361 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_stocks ($db, $langs, $conf)
Migration du champ stock dans produits.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 2341 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_user_photospath ()
Migrate file from old path to new one for users.
Returns
void
Definition at line 4828 of file upgrade2.php.
References $resql, dol_copy(), dol_is_dir(), dol_is_file(), dol_mkdir(), dol_osencode(), get_exdir(), and print.
migrate_user_rights_entity ($db, $langs, $conf)
Migrate to add entity value into llx_user_rights.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 4253 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.
migrate_usergroup_rights_entity ($db, $langs, $conf)
Migrate to add entity value into llx_usergroup_rights.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
Returns
void
Definition at line 4329 of file upgrade2.php.
References $resql, dol_print_error(), dolibarr_install_syslog(), and print.