Dolibarr: htdocs/main.inc.php File Reference
main.inc.php File Reference
File that defines environment for Dolibarr GUI pages only (file not required by scripts)
Functions
if(!empty($_SERVER['MAIN_SHOW_TUNING_INFO'])) testSqlAndScriptInject ($val, $type)
Security: SQL Injection and XSS Injection (scripts) protection (Filters on GET, POST, PHP_SELF).
analyseVarsForSqlAndScriptsInjection (&$var, $type)
Return true if security check on parameters are OK, false otherwise.
if(!defined('NOREQUIREMENU')) if(!function_exists("llxHeader")) top_httphead ($contenttype= 'text/html', $forcenocache=0)
Show HTTP header.
top_htmlhead ($head, $title= '', $disablejs=0, $disablehead=0, $arrayofjs= '', $arrayofcss= '', $disablejmobile=0, $disablenofollow=0)
Ouput html header of a page.
top_menu ($head, $title= '', $target= '', $disablejs=0, $disablehead=0, $arrayofjs= '', $arrayofcss= '', $morequerystring= '', $helppagename= '')
Show an HTML header + a BODY + The top menu bar.
top_menu_user (User $user, Translate $langs)
Build the tooltip on user login.
left_menu ($menu_array_before, $helppagename= '', $notused= '', $menu_array_after= '', $leftmenuwithoutmainarea=0, $title= '', $acceptdelayedhtml=0)
Show left menu bar.
main_area ($title= '')
Begin main area.
getHelpParamFor ($helppagename, $langs)
Return helpbaseurl, helppage and mode.
printSearchForm ($urlaction, $urlobject, $title, $htmlmorecss, $htmlinputname, $accesskey= '', $prefhtmlinputname= '', $img= '', $showtitlebefore=0, $autofocus=0)
Show a search area.
Detailed Description
File that defines environment for Dolibarr GUI pages only (file not required by scripts)
Definition in file main.inc.php.
Function Documentation
analyseVarsForSqlAndScriptsInjection (& $var, $type)
Return true if security check on parameters are OK, false otherwise.
Parameters
string $var Variable name
string $type 1=GET, 0=POST, 2=PHP_SELF
Returns
boolean|null true if there is no injection. Stop code if injection found.
Show HTML header HTML + BODY + Top menu + left menu + DIV
Parameters
string $head Optionnal head lines
string $title HTML title
string $help_url Url links to help page Syntax is: For a wiki page: EN:EnglishPage|FR:FrenchPage|ES:SpanishPage For other external page: http://server/url
string $target Target to use on links
int $disablejs More content into html header
int $disablehead More content into html header
array $arrayofjs Array of complementary js files
array $arrayofcss Array of complementary css files
string $morequerystring Query string to add to the link "print" to get same parameters (use only if autodetect fails)
string $morecssonbody More CSS on body tag.
string $replacemainareaby Replace call to main_area() by a print of this string
Returns
void
Definition at line 120 of file main.inc.php.
References accessforbidden(), checkLoginPassEntity(), dol_buildpath(), dol_hash(), dol_include_once(), dol_now(), dol_print_error(), dol_stringtotime(), dol_syslog(), getBrowserInfo(), GETPOST(), GETPOSTISSET(), left_menu(), llxHeader(), MenuManager\loadMenu(), main_area(), print, setEventMessages(), testSqlAndScriptInject(), top_htmlhead(), top_menu(), and versioncompare().
getHelpParamFor ($helppagename, $langs)
Return helpbaseurl, helppage and mode.
Parameters
string $helppagename Page name ('EN:xxx,ES:eee,FR:fff...' or 'http://localpage')
Translate $langs Language
Returns
array Array of help urls
Definition at line 2116 of file main.inc.php.
Referenced by top_menu().
left_menu ($menu_array_before, $helppagename = '', $notused = '', $menu_array_after = '', $leftmenuwithoutmainarea = 0, $title = '', $acceptdelayedhtml = 0)
Show left menu bar.
Parameters
array $menu_array_before Table of menu entries to show before entries of menu handler. This param is deprectaed and must be provided to ''.
string $helppagename Name of wiki page for help ('' by default). Syntax is: For a wiki page: EN:EnglishPage|FR:FrenchPage|ES:SpanishPage For other external page: http://server/url
string $notused Deprecated. Used in past to add content into left menu. Hooks can be used now.
array $menu_array_after Table of menu entries to show after entries of menu handler
int $leftmenuwithoutmainarea Must be set to 1. 0 by default for backward compatibility with old modules.
string $title Title of web page
string $acceptdelayedhtml 1 if caller request to have html delayed content not returned but saved into global $delayedhtmlcontent (so caller can show it at end of page to avoid flash FOUC effect)
Returns
void
Definition at line 1906 of file main.inc.php.
References dol_escape_htmltag(), dol_syslog(), img_picto(), main_area(), print, printBookmarksList(), and printSearchForm().
Referenced by analyseVarsForSqlAndScriptsInjection().
main_area ($title = '')
Begin main area.
Parameters
string $title Title
Returns
void
Definition at line 2095 of file main.inc.php.
References info_admin(), and print.
Referenced by analyseVarsForSqlAndScriptsInjection(), and left_menu().
printSearchForm ($urlaction, $urlobject, $title, $htmlmorecss, $htmlinputname, $accesskey = '', $prefhtmlinputname = '', $img = '', $showtitlebefore = 0, $autofocus = 0)
Show a search area.
Used when the javascript quick search is not used.
Parameters
string $urlaction Url post
string $urlobject Url of the link under the search box
string $title Title search area
string $htmlmorecss Add more css
string $htmlinputname Field Name input form
string $accesskey Accesskey
string $prefhtmlinputname Complement for id to avoid multiple same id in the page
string $img Image to use
string $showtitlebefore Show title before input text instead of into placeholder. This can be set when output is dedicated for text browsers.
string $autofocus Set autofocus on field
Returns
string
Show HTML footer Close div /DIV class=fiche + /DIV id-right + /DIV id-container + /BODY + /HTML. If global var $delayedhtmlcontent was filled, we output it just before closing the body.
Parameters
string $comment A text to add as HTML comment into HTML generated page
string $zone 'private' (for private pages) or 'public' (for public pages)
int $disabledoutputofmessages Clear all messages stored into session without diplaying them
Returns
void
Definition at line 2169 of file main.inc.php.
References dol_now(), dol_print_date(), dolibarr_set_const(), llxFooter(), and print.
Referenced by left_menu().
if (!empty($_SERVER['MAIN_SHOW_TUNING_INFO'])) testSqlAndScriptInject ($val, $type)
Security: SQL Injection and XSS Injection (scripts) protection (Filters on GET, POST, PHP_SELF).
Parameters
string $val Value
string $type 1=GET, 0=POST, 2=PHP_SELF, 3=GET without sql reserved keywords (the less tolerant test)
Returns
int >0 if there is an injection, 0 if none
Definition at line 57 of file main.inc.php.
Referenced by analyseVarsForSqlAndScriptsInjection(), and Form\select_thirdparty_list().
top_htmlhead ($head, $title = '', $disablejs = 0, $disablehead = 0, $arrayofjs = '', $arrayofcss = '', $disablejmobile = 0, $disablenofollow = 0)
Ouput html header of a page.
This code is also duplicated into security2.lib.php::dol_loginfunction
Parameters
string $head Optionnal head lines
string $title HTML title
int $disablejs Disable js output
int $disablehead Disable head output
array $arrayofjs Array of complementary js files
array $arrayofcss Array of complementary css files
int $disablejmobile Disable jmobile (No more used)
int $disablenofollow Disable no follow tag
Returns
void
Definition at line 1195 of file main.inc.php.
References dol_buildpath(), dol_htmlentities(), dol_syslog(), GETPOST(), GETPOSTISSET(), if, print, and top_httphead().
Referenced by analyseVarsForSqlAndScriptsInjection(), llxHeaderSurvey(), llxHeaderTicket(), llxHeaderVierge(), and top_menu().
if (!defined('NOREQUIREMENU')) if (!function_exists("llxHeader")) top_httphead ($contenttype = 'text/html', $forcenocache = 0)
Show HTTP header.
Parameters
string $contenttype Content type. For example, 'text/html'
int $forcenocache Force disabling of cache for the page
Returns
void
Definition at line 1128 of file main.inc.php.
Referenced by llxFooter(), and top_htmlhead().
top_menu ($head, $title = '', $target = '', $disablejs = 0, $disablehead = 0, $arrayofjs = '', $arrayofcss = '', $morequerystring = '', $helppagename = '')
Show an HTML header + a BODY + The top menu bar.
Parameters
string $head Lines in the HEAD
string $title Title of web page
string $target Target to use in menu links (Example: '' or '_top')
int $disablejs Do not output links to js (Ex: qd fonction utilisee par sous formulaire Ajax)
int $disablehead Do not output head section
array $arrayofjs Array of js files to add in header
array $arrayofcss Array of css files to add in header
string $morequerystring Query string to add to the link "print" to get same parameters (use only if autodetect fails)
string $helppagename Name of wiki page for help ('' by default). Syntax is: For a wiki page: EN:EnglishPage|FR:FrenchPage|ES:SpanishPage For other external page: http://server/url
Returns
void
Definition at line 1529 of file main.inc.php.
References dol_escape_htmltag(), getHelpParamFor(), GETPOST(), img_picto(), print, Form\textwithtooltip(), top_htmlhead(), and top_menu_user().
Referenced by analyseVarsForSqlAndScriptsInjection().
top_menu_user (User $user, Translate $langs)
Build the tooltip on user login.
Parameters
user $user User object
Translate $langs Language object
Returns
string HTML content
Definition at line 1725 of file main.inc.php.
References dol_print_date(), dol_trunc(), picto_from_langcode(), Form\showphoto(), and yn().
Referenced by top_menu().