Dolibarr: FileUpload Class Reference
FileUpload Class Reference
This class is used to manage file upload using ajax.
Public Member Functions
__construct ($options=null, $fk_element=null, $element=null)
Constructor.
get ()
Output data.
post ()
Output data.
delete ()
Delete uploaded file.
Protected Member Functions
getFullUrl ()
Return full URL.
setFileDeleteUrl ($file)
Set delete url.
getFileObject ($file_name)
getFileObject
getFileObjects ()
getFileObjects
createScaledImage ($file_name, $options)
Create thumbs of a file uploaded.
validate ($uploaded_file, $file, $error, $index)
Enter description here ...
upcountNameCallback ($matches)
Enter description here ...
upcountName ($name)
Enter description here ...
trimFileName ($name, $type, $index)
trimFileName
handleFileUpload ($uploaded_file, $name, $size, $type, $error, $index)
handleFileUpload
Detailed Description
This class is used to manage file upload using ajax.
Definition at line 31 of file fileupload.class.php.
Constructor & Destructor Documentation
__construct ($options = null, $fk_element = null, $element = null)
Constructor.
Parameters
array $options Options array
int $fk_element fk_element
string $element element
Definition at line 44 of file fileupload.class.php.
References dol_include_once(), dol_sanitizeFileName(), and get_exdir().
Member Function Documentation
createScaledImage ($file_name, $options) protected
Create thumbs of a file uploaded.
Only the "mini" thumb is generated.
Parameters
string $file_name Filename
string $options is array('max_width', 'max_height')
Returns
boolean
Definition at line 283 of file fileupload.class.php.
References dol_mkdir(), and vignette().
Referenced by handleFileUpload().
delete ()
Delete uploaded file.
Returns
void
Definition at line 567 of file fileupload.class.php.
get ()
Output data.
Returns
void
Definition at line 489 of file fileupload.class.php.
References getFileObject(), and getFileObjects().
getFileObject ($file_name) protected
getFileObject
Parameters
string $file_name Filename
Returns
stdClass|null
Definition at line 244 of file fileupload.class.php.
References dol_mimetype(), and setFileDeleteUrl().
Referenced by get().
getFileObjects () protected
getFileObjects
Returns
void
Definition at line 271 of file fileupload.class.php.
Referenced by get(), and validate().
getFullUrl () protected
Return full URL.
Returns
string URL
Definition at line 210 of file fileupload.class.php.
handleFileUpload ($uploaded_file, $name, $size, $type, $error, $index) protected
handleFileUpload
Parameters
string $uploaded_file Uploade file
string $name Name
int $size Size
string $type Type
string $error Error
string $index Index
Returns
stdClass
Definition at line 434 of file fileupload.class.php.
References createScaledImage(), dol_mimetype(), dol_mkdir(), dol_move_uploaded_file(), setFileDeleteUrl(), trimFileName(), and validate().
Referenced by post().
post ()
Output data.
Returns
void
Definition at line 510 of file fileupload.class.php.
References handleFileUpload().
setFileDeleteUrl ($file) protected
Set delete url.
Parameters
string $file Filename
Returns
void
Definition at line 228 of file fileupload.class.php.
Referenced by getFileObject(), and handleFileUpload().
trimFileName ($name, $type, $index) protected
trimFileName
Parameters
string $name Filename
string $type ???
string $index ???
Returns
string
Definition at line 402 of file fileupload.class.php.
References upcountName().
Referenced by handleFileUpload().
upcountName ($name) protected
Enter description here ...
Parameters
string $name ???
Returns
string ???
Definition at line 389 of file fileupload.class.php.
Referenced by trimFileName().
upcountNameCallback ($matches) protected
Enter description here ...
Parameters
int $matches ???
Returns
string ???
Definition at line 376 of file fileupload.class.php.
validate ($uploaded_file, $file, $error, $index) protected
Enter description here ...
Parameters
string $uploaded_file Uploade file
string $file File
string $error Error
string $index Index
Returns
boolean True if OK, False if KO
Definition at line 317 of file fileupload.class.php.
References getFileObjects().
Referenced by handleFileUpload().
The documentation for this class was generated from the following file:
htdocs/core/class/fileupload.class.php