Dolibarr: ActionsAdherentCardDefault Class Reference
ActionsAdherentCardDefault Class Reference
Class allowing the management of the members by default.
Public Member Functions
__construct ($db, $dirmodule, $targetmodule, $canvas, $card)
Constructor.
assign_values (&$action, $id)
Assign custom values for canvas.
LoadListDatas ($limit, $offset, $sortfield, $sortorder)
Fetch datas list and save into ->list_datas.
Public Member Functions inherited from ActionsAdherentCardCommon
getObject ($id)
Get object.
assign_values (&$action, $id)
Set content of ->tpl array, to use into template.
Private Member Functions
getTitle ($action)
Return the title of card.
Additional Inherited Members
Data Fields inherited from ActionsAdherentCardCommon
$tpl = array()
Template container.
$object
Object container.
Detailed Description
Class allowing the management of the members by default.
Definition at line 31 of file actions_adherentcard_default.class.php.
Constructor & Destructor Documentation
__construct ($db, $dirmodule, $targetmodule, $canvas, $card)
Constructor.
Parameters
DoliDB $db Handler acces data base
string $dirmodule Name of directory of module
string $targetmodule Name of directory of module where canvas is stored
string $canvas Name of canvas
string $card Name of tab (sub-canvas)
Definition at line 42 of file actions_adherentcard_default.class.php.
References db.
Member Function Documentation
assign_values (& $action, $id)
Assign custom values for canvas.
Parameters
string $action Type of action
int $id Id
Returns
void
Definition at line 78 of file actions_adherentcard_default.class.php.
References dol_get_fiche_end(), dol_get_fiche_head(), ActionsAdherentCardCommon\getObject(), getTitle(), LoadListDatas(), member_prepare_head(), show_actions_done(), and show_actions_todo().
getTitle ($action) private
Return the title of card.
Parameters
string $action Action code
Returns
string Title
Definition at line 57 of file actions_adherentcard_default.class.php.
Referenced by assign_values().
LoadListDatas ($limit, $offset, $sortfield, $sortorder)
Fetch datas list and save into ->list_datas.
Parameters
int $limit Limit number of responses
int $offset Offset for first response
string $sortfield Sort field
string $sortorder Sort order ('ASC' or 'DESC')
Returns
void
Definition at line 135 of file actions_adherentcard_default.class.php.
Referenced by assign_values().
The documentation for this class was generated from the following file:
htdocs/adherents/canvas/default/actions_adherentcard_default.class.php