Dolibarr: ImportCsv Class Reference
ImportCsv Class Reference
Class to import CSV files.
Public Member Functions
__construct ($db, $datatoimport)
Constructor.
write_header_example ($outputlangs)
Output header of an example file for this format.
write_title_example ($outputlangs, $headerlinefields)
Output title line of an example file for this format.
write_record_example ($outputlangs, $contentlinevalues)
Output record of an example file for this format.
write_footer_example ($outputlangs)
Output footer of an example file for this format.
import_open_file ($file)
Open input file.
import_get_nb_of_lines ($file)
Return nb of records.
import_read_header ()
Input header line from file.
import_read_record ()
Return array of next record in input file.
import_close_file ()
Close file handle.
import_insert ($arrayrecord, $array_match_file_to_database, $objimport, $maxfields, $importid, $updatekeys)
Insert a record into database.
Public Member Functions inherited from ModeleImports
__construct ()
Constructor.
getDriverId ()
getDriverId
getDriverLabel ()
getDriverLabel
getDriverDesc ()
getDriverDesc
getDriverExtension ()
getDriverExtension
getDriverVersion ()
getDriverVersion
getLibLabel ()
getDriverLabel
getLibVersion ()
getLibVersion
liste_modeles ($db, $maxfilenamelength=0)
Charge en memoire et renvoie la liste des modeles actifs.
getPictoForKey ($key)
Return picto of import driver.
getDriverLabelForKey ($key)
Renvoi libelle d'un driver import.
getDriverDescForKey ($key)
Renvoi la description d'un driver import.
getDriverVersionForKey ($key)
Renvoi version d'un driver import.
getLibLabelForKey ($key)
Renvoi libelle de librairie externe du driver.
getLibVersionForKey ($key)
Renvoi version de librairie externe du driver.
Detailed Description
Class to import CSV files.
Definition at line 34 of file import_csv.modules.php.
Constructor & Destructor Documentation
__construct ($db, $datatoimport)
Constructor.
Parameters
DoliDB $db Database handler
string $datatoimport String code describing import set (ex: 'societe_1')
Definition at line 96 of file import_csv.modules.php.
References db, GETPOST(), and label.
Member Function Documentation
import_close_file ()
Close file handle.
Returns
integer
Definition at line 302 of file import_csv.modules.php.
import_get_nb_of_lines ($file)
Return nb of records.
File must be closed.
Parameters
string $file Path of filename
Returns
int <0 if KO, >=0 if OK
Definition at line 219 of file import_csv.modules.php.
References dol_count_nb_of_line().
import_insert ($arrayrecord, $array_match_file_to_database, $objimport, $maxfields, $importid, $updatekeys)
Insert a record into database.
Parameters
array $arrayrecord Array of read values: [fieldpos] => (['val']=>val, ['type']=>-1=null,0=blank,1=string), [fieldpos+1]...
array $array_match_file_to_database Array of target fields where to insert data: [fieldpos] => 's.fieldname', [fieldpos+1]...
Object $objimport Object import (contains objimport->array_import_tables, objimport->array_import_fields, objimport->array_import_convertvalue, ...)
int $maxfields Max number of fields to use
string $importid Import key
array $updatekeys Array of keys to use to try to do an update first before insert. This field are defined into the module descriptor.
Returns
int <0 if KO, >0 if OK
Definition at line 322 of file import_csv.modules.php.
References $resql, db, dol_include_once(), dol_print_error(), dol_syslog(), and price2num().
import_open_file ($file)
Open input file.
Parameters
string $file Path of filename
Returns
int <0 if KO, >=0 if OK
Definition at line 186 of file import_csv.modules.php.
References dol_osencode(), and dol_syslog().
import_read_header ()
Input header line from file.
Returns
int <0 if KO, >=0 if OK
Definition at line 232 of file import_csv.modules.php.
import_read_record ()
Return array of next record in input file.
Returns
Array Array of field values. Data are UTF8 encoded. [fieldpos] => (['val']=>val, ['type']=>-1=null,0=blank,1=not empty string)
Definition at line 245 of file import_csv.modules.php.
References dol_strlen(), and utf8_check().
write_footer_example ($outputlangs)
Output footer of an example file for this format.
Parameters
Translate $outputlangs Output language
Returns
string
Definition at line 171 of file import_csv.modules.php.
write_header_example ($outputlangs)
Output header of an example file for this format.
Parameters
Translate $outputlangs Output language
Returns
string
Definition at line 128 of file import_csv.modules.php.
write_record_example ($outputlangs, $contentlinevalues)
Output record of an example file for this format.
Parameters
Translate $outputlangs Output language
array $contentlinevalues Array of lines
Returns
string
Definition at line 157 of file import_csv.modules.php.
write_title_example ($outputlangs, $headerlinefields)
Output title line of an example file for this format.
Parameters
Translate $outputlangs Output language
array $headerlinefields Array of fields name
Returns
string$limittoachartaccount
Definition at line 142 of file import_csv.modules.php.
The documentation for this class was generated from the following file:
htdocs/core/modules/import/import_csv.modules.php