Dolibarr: CommActionRapport Class Reference
CommActionRapport Class Reference
Class to generate event report.
Public Member Functions
__construct ($db, $month, $year)
Constructor.
write_file ($socid=0, $catid=0, $outputlangs= '')
Write the object to document file to disk.
Private Member Functions
_pages (&$pdf, $outputlangs)
Write content of pages.
_pagehead (&$pdf, $outputlangs, $pagenb)
Show top header of page.
Detailed Description
Class to generate event report.
Definition at line 36 of file rapport.pdf.php.
Constructor & Destructor Documentation
__construct ($db, $month, $year)
Constructor.
Parameters
DoliDB $db Database handler
int $month Month
int $year Year
Definition at line 74 of file rapport.pdf.php.
References db, description, pdf_getFormat(), and type.
Member Function Documentation
_pagehead (& $pdf, $outputlangs, $pagenb) private
Show top header of page.
Parameters
PDF $pdf Object PDF
Translate $outputlangs Object lang for output
int $pagenb Page nb
Returns
integer
Definition at line 338 of file rapport.pdf.php.
References pdf_getPDFFont().
Referenced by _pages().
_pages (& $pdf, $outputlangs) private
Write content of pages.
Parameters
PDF $pdf Object pdf
Translate $outputlangs Object langs
Returns
int 1
Definition at line 213 of file rapport.pdf.php.
References $resql, _pagehead(), db, dol_get_first_day(), dol_get_last_day(), dol_htmlentitiesbr_decode(), dol_nboflines(), dol_print_date(), dol_syslog(), and dol_trunc().
Referenced by write_file().
write_file ($socid = 0, $catid = 0, $outputlangs = '')
Write the object to document file to disk.
Parameters
int $socid Thirdparty id
int $catid Cat id
Translate $outputlangs Lang object for output language
Returns
int 1=OK, 0=KO
Definition at line 111 of file rapport.pdf.php.
References _pages(), db, dol_mkdir(), pdf_getInstance(), and pdf_getPDFFont().
The documentation for this class was generated from the following file:
htdocs/core/modules/action/rapport.pdf.php