linters:
  phpcs:
    standard: PSR2
    exclude:
      - 'Generic.WhiteSpace.DisallowTabIndent'
    extensions: 'php'
    tab_width: 8
    fixer: true
files:
  ignore:
    - 'htdocs/includes/*'
fixers:
  enable: true
