branches:
  only:
  - develop

addons:
  apt:
    packages:
      - doxygen
      - graphviz

script:
  - cd build/doxygen
  - ( cat dolibarr-doxygen.doxyfile ; echo "PROJECT_NUMBER=develop" ) | doxygen -

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/build/html
  github_token: $GITHUB_API_KEY
  on:
    branch: develop
