# This script is used by Travis CI to run automatically Continuous test integration
# from Dolibarr GitHub repository.
# For syntax, see http://about.travis-ci.org/docs/user/languages/php/

language: php

dist: bionic

env:
  global:
  - DEBUG=true
  matrix:
  - DB=mariadb
  - DB=postgresql

php:
- '7.2'

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
  include:
  - php: '7.3'
    env: DB=mariadb
    addons:
        mariadb: '10.2'
        apt:
            packages:
            - apache2
  exclude:
  - php: 'nightly'
    env: DB=postgresql
  # PHP 7.2 is TravisCI default so we must explicitely exclude it
  - php: '7.2'
    env: DB=mariadb
  - php: '7.2'
    env: DB=postgresql

before_install:
- |
  echo "Disabling Xdebug for composer"
  export PHP_VERSION_NAME=$(phpenv version-name)
  cp ~/.phpenv/versions/$PHP_VERSION_NAME/etc/conf.d/xdebug.ini /tmp/xdebug.ini
  phpenv config-rm xdebug.ini
  echo

- |
  if [ "$DB" = 'postgresql' ]; then
    echo "Check pgloader version"
    pgloader --version
    echo
  fi

install:
- |
  echo "Updating Composer"
  rm $TRAVIS_BUILD_DIR/composer.json
  rm $TRAVIS_BUILD_DIR/composer.lock
  composer self-update
  composer global require hirak/prestissimo
  composer -n init
  composer -n config vendor-dir htdocs/includes
  echo

- |
  echo "Installing Composer requirements (Parallel Lint, PHP Unit and PHP CodeSniffer)"
  if [ "$TRAVIS_PHP_VERSION" = '5.4' ] || [ "$TRAVIS_PHP_VERSION" = '5.5' ]; then
    composer -n require jakub-onderka/php-parallel-lint ^0 jakub-onderka/php-console-highlighter ^0 phpunit/phpunit ^4 squizlabs/php_codesniffer ^3
  fi
  if [ "$TRAVIS_PHP_VERSION" = '5.6' ] || [ "$TRAVIS_PHP_VERSION" = '7.0' ] || [ "$TRAVIS_PHP_VERSION" = '7.1' ]; then
    composer -n require jakub-onderka/php-parallel-lint ^0 jakub-onderka/php-console-highlighter ^0 phpunit/phpunit ^5 squizlabs/php_codesniffer ^3
  fi
  if [ "$TRAVIS_PHP_VERSION" = '7.2' ] || [ "$TRAVIS_PHP_VERSION" = '7.3' ] || [ "$TRAVIS_PHP_VERSION" = 'nightly' ]; then
    composer -n require jakub-onderka/php-parallel-lint ^0 jakub-onderka/php-console-highlighter ^0 phpunit/phpunit ^5 squizlabs/php_codesniffer ^3
  fi
  echo

- |
  echo "Adding path of binaries tools installed by composer to the PATH"
  export PATH="$TRAVIS_BUILD_DIR/htdocs/includes/bin:$PATH"
  echo



before_script:
  - |
    echo "Setting up PHP"
    echo
    echo "Set timezone"
    echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$PHP_VERSION_NAME/etc/php.ini
    phpenv rehash
    echo

  - |
    echo "Versions information"
    # Check PHP
    echo "PHP version"
    php -i | head -
    # Check PHP CodeSniffer installation
    echo "PHPCS version"
    which phpcs
    phpcs --version | head -
    phpcs -i | head -
    # Check PHPUnit installation
    echo "PHPUnit version"
    which phpunit
    phpunit --version | head -
    # Check Apache version
    echo "Apache version"
    apache2 -v | head -
    # Check MariaDb
    echo "MariaDb version"
    mysql --version | head -
    mysql -e "SELECT VERSION();"  | head -
    echo

  - |
    echo "Setting up database"
    if [ "$DB" = 'mysql' ] || [ "$DB" = 'mariadb' ] || [ "$DB" = 'postgresql' ]; then
      echo "MySQL"
      mysql -e 'DROP DATABASE IF EXISTS travis;'
      mysql -e 'CREATE DATABASE IF NOT EXISTS travis;'
      mysql -e 'CREATE USER travis@127.0.0.1;'
      mysql -e 'GRANT ALL PRIVILEGES ON travis.* TO travis@127.0.0.1;'
      mysql -e 'FLUSH PRIVILEGES;'
      mysql -D travis < dev/initdemo/mysqldump_dolibarr_3.5.0.sql
    fi

  - |
    export CONF_FILE=htdocs/conf/conf.php
    echo "Setting up Dolibarr $CONF_FILE"
    echo '<?php' > $CONF_FILE
    echo '$'dolibarr_main_url_root=\'http://127.0.0.1\'';' >> $CONF_FILE
    echo '$'dolibarr_main_document_root=\'$TRAVIS_BUILD_DIR/htdocs\'';' >> $CONF_FILE
    echo '$'dolibarr_main_data_root=\'$TRAVIS_BUILD_DIR/documents\'';' >> $CONF_FILE
    echo '$'dolibarr_main_db_host=\'127.0.0.1\'';' >> $CONF_FILE
    echo '$'dolibarr_main_db_name=\'travis\'';' >> $CONF_FILE
    echo '$'dolibarr_main_db_user=\'travis\'';' >> $CONF_FILE
    if [ "$DB" = 'mysql' ] || [ "$DB" = 'mariadb' ]; then
      echo '$'dolibarr_main_db_type=\'mysqli\'';' >> $CONF_FILE
      echo '$'dolibarr_main_db_port=\'3306\'';' >> $CONF_FILE
    fi
    echo '$'dolibarr_main_authentication=\'dolibarr\'';' >> $CONF_FILE
    cat $CONF_FILE
    echo

  - |
    echo "Create documents directory and set permissions"
    # and admin/temp subdirectory needed for unit tests
    mkdir -p $TRAVIS_BUILD_DIR/documents/admin/temp
    sudo chmod -R a+rwx $TRAVIS_BUILD_DIR/documents
    echo "***** First line of dolibarr.log" > $TRAVIS_BUILD_DIR/documents/dolibarr.log
    echo


  - echo "Setting up Apache + FPM"
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - |
    if [ "$TRAVIS_PHP_VERSION" = '7.0' ] || [ "$TRAVIS_PHP_VERSION" = '7.1' ] || [ "$TRAVIS_PHP_VERSION" = '7.2' ] || [ "$TRAVIS_PHP_VERSION" = '7.3' ] || [ "$TRAVIS_PHP_VERSION" = 'nightly' ]; then
      # Copy the included pool
      sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
    fi
  - sudo a2enmod rewrite actions alias
  - |
    if [ "$TRAVIS_DIST" = 'trusty' ]; then
      sudo a2enmod fastcgi
      sudo chown -R travis:travis /var/lib/apache2/fastcgi
      sudo cp -f build/travis-ci/apache.conf /etc/apache2/sites-available/000-default.conf
    fi
    if [ "$TRAVIS_DIST" = 'bionic' ]; then
      wget http://mirrors.kernel.org/ubuntu/pool/multiverse/liba/libapache-mod-fastcgi/libapache2-mod-fastcgi_2.4.7~0910052141-1.2_amd64.deb
      export DEBIAN_FRONTEND=noninteractive && sudo dpkg -i libapache2-mod-fastcgi_2.4.7~0910052141-1.2_amd64.deb
      sudo cp -f build/travis-ci/apache-bionic.conf /etc/apache2/sites-available/000-default.conf
    fi
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo cat /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart
  - sudo systemctl status apache2.service
  - sudo journalctl -xe



script:
- |
  echo "Checking webserver availability by a wget -O - http://127.0.0.1"
  # Ensure we stop on error with set -e
  set +e
  # The wget should return a page with line '<meta name="generator" content="Dolibarr installer">
  wget -O - http://127.0.0.1 > test.html
  head test.html
  sudo cat /var/log/apache2/travis_error_log
  set +e
  echo

- |
  echo "Upgrading Dolibarr"
  # Ensure we catch errors. Set this to +e if you want to go to the end to see log files.
  set +e
  cd htdocs/install
  php upgrade.php 3.5.0 3.6.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade350360.log
  php upgrade2.php 3.5.0 3.6.0 > $TRAVIS_BUILD_DIR/upgrade350360-2.log
  php step5.php 3.5.0 3.6.0 > $TRAVIS_BUILD_DIR/upgrade350360-3.log
  php upgrade.php 3.6.0 3.7.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade360370.log
  php upgrade2.php 3.6.0 3.7.0 > $TRAVIS_BUILD_DIR/upgrade360370-2.log
  php step5.php 3.6.0 3.7.0 > $TRAVIS_BUILD_DIR/upgrade360370-3.log
  php upgrade.php 3.7.0 3.8.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade370380.log
  php upgrade2.php 3.7.0 3.8.0 > $TRAVIS_BUILD_DIR/upgrade370380-2.log
  php step5.php 3.7.0 3.8.0 > $TRAVIS_BUILD_DIR/upgrade370380-3.log
  php upgrade.php 3.8.0 3.9.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade380390.log
  php upgrade2.php 3.8.0 3.9.0 > $TRAVIS_BUILD_DIR/upgrade380390-2.log
  php step5.php 3.8.0 3.9.0 > $TRAVIS_BUILD_DIR/upgrade380390-3.log
  php upgrade.php 3.9.0 4.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade390400.log
  php upgrade2.php 3.9.0 4.0.0 > $TRAVIS_BUILD_DIR/upgrade390400-2.log
  php step5.php 3.9.0 4.0.0 > $TRAVIS_BUILD_DIR/upgrade390400-3.log
  php upgrade.php 4.0.0 5.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade400500.log
  php upgrade2.php 4.0.0 5.0.0 > $TRAVIS_BUILD_DIR/upgrade400500-2.log
  php step5.php 4.0.0 5.0.0 > $TRAVIS_BUILD_DIR/upgrade400500-3.log
  php upgrade.php 5.0.0 6.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade500600.log
  php upgrade2.php 5.0.0 6.0.0 > $TRAVIS_BUILD_DIR/upgrade500600-2.log
  php step5.php 5.0.0 6.0.0 > $TRAVIS_BUILD_DIR/upgrade500600-3.log
  php upgrade.php 6.0.0 7.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade600700.log
  php upgrade2.php 6.0.0 7.0.0 > $TRAVIS_BUILD_DIR/upgrade600700-2.log
  php step5.php 6.0.0 7.0.0 > $TRAVIS_BUILD_DIR/upgrade600700-3.log
  php upgrade.php 7.0.0 8.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade700800.log
  php upgrade2.php 7.0.0 8.0.0 > $TRAVIS_BUILD_DIR/upgrade700800-2.log
  php step5.php 7.0.0 8.0.0 > $TRAVIS_BUILD_DIR/upgrade700800-3.log
  php upgrade.php 8.0.0 9.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade800900.log
  php upgrade2.php 8.0.0 9.0.0 > $TRAVIS_BUILD_DIR/upgrade800900-2.log
  php step5.php 8.0.0 9.0.0 > $TRAVIS_BUILD_DIR/upgrade800900-3.log
  php upgrade.php 9.0.0 10.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade9001000.log
  php upgrade2.php 9.0.0 10.0.0 > $TRAVIS_BUILD_DIR/upgrade9001000-2.log
  php step5.php 9.0.0 10.0.0 > $TRAVIS_BUILD_DIR/upgrade9001000-3.log
  php upgrade.php 10.0.0 11.0.0 ignoredbversion > $TRAVIS_BUILD_DIR/upgrade9001000.log
  php upgrade2.php 10.0.0 11.0.0 > $TRAVIS_BUILD_DIR/upgrade9001000-2.log
  php step5.php 10.0.0 11.0.0 > $TRAVIS_BUILD_DIR/upgrade9001000-3.log
  # Enable modules not enabled into original dump
  php upgrade2.php 0.0.0 0.0.0 MAIN_MODULE_API,MAIN_MODULE_SUPPLIERPROPOSAL,MAIN_MODULE_WEBSITE,MAIN_MODULE_TICKETSUP,MAIN_MODULE_ACCOUNTING > $TRAVIS_BUILD_DIR/enablemodule.log
  echo $?
  cd -
  set +e
  echo
  #cat /tmp/dolibarr_install.log
  cat $TRAVIS_BUILD_DIR/enablemodule.log

- |
  echo "Unit testing"
  # Ensure we catch errors. Set this to +e if you want to go to the end to see dolibarr.log file.
  set -e
  phpunit -d memory_limit=-1 -c test/phpunit/phpunittest.xml test/phpunit/AllTests.php
  phpunitresult=$?
  echo "Phpunit return code = $phpunitresult"
  set +e

after_script:
- |
  echo "After script - Output lines of dolibarr.log"
  ls $TRAVIS_BUILD_DIR/documents
  #cat $TRAVIS_BUILD_DIR/documents/dolibarr.log
  sudo tail -n 50 $TRAVIS_BUILD_DIR/documents/dolibarr.log

after_success:
- |
  echo Success

after_failure:
- |
  echo Failure detected, so we show samples of log to help diagnose
  # This part of code is executed only if previous command that fails are enclosed with set +e
  # Upgrade log files
  for ficlog in `ls $TRAVIS_BUILD_DIR/*.log`
  do
    echo "Debugging informations for file $ficlog"
    #cat $ficlog
  done
  # Apache log file
  echo "Debugging informations for file apache error.log"
  sudo cat /var/log/apache2/travis_error_log
  if [ "$DEBUG" = true ]; then
    # Dolibarr log file
    echo "Debugging informations for file dolibarr.log (latest 50 lines)"
    tail -n 50 $TRAVIS_BUILD_DIR/documents/dolibarr.log
    # MariaDB log file
    echo "Debugging informations for file mysql error.log"
    sudo tail -n 50 /var/log/mysql/error.log
    # TODO: PostgreSQL log file
    echo
  fi
