branches:
  only:
    - doxygen

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - graphviz

# Build your code e.g. by calling make
script:
  - cd build/doxygen
  - doxygen dolibarr-doxygen.doxyfile

# Deploy using travis builtin GitHub Pages support
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/build/html
  github_token: $GITHUB_API_KEY
  on:
    branch: doxygen
