Dolibarr: FormOther Class Reference
FormOther Class Reference
Classe permettant la generation de composants html autre Only common components are here.
Public Member Functions
__construct ($db)
Constructor.
select_export_model ($selected= '', $htmlname= 'exportmodelid', $type= '', $useempty=0, $fk_user=null)
Return HTML select list of export models.
select_import_model ($selected= '', $htmlname= 'importmodelid', $type= '', $useempty=0)
Return list of export models.
select_ecotaxes ($selected= '', $htmlname= 'ecotaxe_id')
Return list of ecotaxes with label.
select_revenue_stamp ($selected= '', $htmlname= 'revenuestamp', $country_code= '')
Return list of revenue stamp for country.
select_percent ($selected=0, $htmlname= 'percent', $disabled=0, $increment=5, $start=0, $end=100, $showempty=0)
Return a HTML select list to select a percent.
select_categories ($type, $selected=0, $htmlname= 'search_categ', $nocateg=0, $showempty=1, $morecss= '')
Return select list for categories (to use in form search selectors)
select_salesrepresentatives ($selected, $htmlname, $user, $showstatus=0, $showempty=1, $morecss= '')
Return select list for categories (to use in form search selectors)
selectProjectTasks ($selectedtask= '', $projectid=0, $htmlname= 'task_parent', $modeproject=0, $modetask=0, $mode=0, $useempty=0, $disablechildoftaskid=0, $filteronprojstatus= '', $morecss= '')
Return list of project and tasks.
select_color ($set_color= '', $prefix= 'f_color', $form_name= '', $showcolorbox=1, $arrayofcolors= '')
Output a HTML code to select a color.
CreateColorIcon ($color, $module, $name, $x= '12', $y= '12')
Creation d'un icone de couleur.
select_dayofweek ($selected= '', $htmlname= 'weekid', $useempty=0)
Return HTML combo list of week.
select_month ($selected= '', $htmlname= 'monthid', $useempty=0, $longlabel=0, $morecss= 'maxwidth50imp valignmiddle')
Return HTML combo list of month.
select_year ($selected= '', $htmlname= 'yearid', $useempty=0, $min_year=10, $max_year=5, $offset=0, $invert=0, $option= '', $morecss= 'valignmiddle maxwidth75imp')
Return HTML combo list of years.
selectyear ($selected= '', $htmlname= 'yearid', $useempty=0, $min_year=10, $max_year=5, $offset=0, $invert=0, $option= '', $morecss= 'valignmiddle maxwidth75imp')
Return HTML combo list of years.
select_dictionary ($htmlname, $dictionarytable, $keyfield= 'code', $labelfield= 'label', $selected= '', $useempty=0, $moreattrib= '')
Return a HTML select list of a dictionary.
selectAutoManual ($htmlname, $value= '', $option=0, $disabled=false, $useempty=0)
Return an html string with a select combo box to choose yes or no.
Static Public Member Functions
static showColor ($color, $textifnotdefined= '')
Output a HTML thumb of color or a text if not defined.
static selectColor ($set_color= '', $prefix= 'f_color', $form_name= '', $showcolorbox=1, $arrayofcolors= '', $morecss= '')
Output a HTML code to select a color.
static getBoxesArea ($user, $areacode)
Get array with HTML tabs with boxes of a particular area including personalized choices of user.
Private Member Functions
_pLineSelect (&$inc, $parent, $lines, $level=0, $selectedtask=0, $selectedproject=0, $disablechildoftaskid=0)
Write lines of a project (all lines of a project if parent = 0)
Detailed Description
Classe permettant la generation de composants html autre Only common components are here.
Definition at line 39 of file html.formother.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 54 of file html.formother.class.php.
References db.
Member Function Documentation
_pLineSelect (& $inc, $parent, $lines, $level = 0, $selectedtask = 0, $selectedproject = 0, $disablechildoftaskid = 0) private
Write lines of a project (all lines of a project if parent = 0)
Parameters
int $inc Cursor counter
int $parent Id of parent task we want to see
array $lines Array of task lines
int $level Level
int $selectedtask Id selected task
int $selectedproject Id selected project
int $disablechildoftaskid 1=Disable task that are child of the provided task id
Returns
void
Definition at line 560 of file html.formother.class.php.
References print.
Referenced by selectProjectTasks().
CreateColorIcon ($color, $module, $name, $x = '12', $y = '12')
Creation d'un icone de couleur.
Parameters
string $color Couleur de l'image
string $module Nom du module
string $name Nom de l'image
int $x Largeur de l'image en pixels
int $y Hauteur de l'image en pixels
Returns
void
Definition at line 793 of file html.formother.class.php.
static getBoxesArea ($user, $areacode) static
Get array with HTML tabs with boxes of a particular area including personalized choices of user.
Class 'Form' must be known.
Parameters
User $user Object User
String $areacode Code of area for pages ('0'=value for Home page)
Returns
array array('selectboxlist'=>, 'boxactivated'=>, 'boxlista'=>, 'boxlistb'=>)
Definition at line 995 of file html.formother.class.php.
References ajax_combobox(), GETPOST(), InfoBox\listBoxes(), and Form\selectarray().
select_categories ($type, $selected = 0, $htmlname = 'search_categ', $nocateg = 0, $showempty = 1, $morecss = '')
Return select list for categories (to use in form search selectors)
Parameters
int $type Type of category ('customer', 'supplier', 'contact', 'product', 'member'). Old mode (0, 1, 2, ...) is deprecated.
integer $selected Preselected value
string $htmlname Name of combo list
int $nocateg Show also an entry "Not categorized"
int $showempty Add also an empty line
string $morecss More CSS
Returns
string Html combo list code
See also
select_all_categories()
Definition at line 332 of file html.formother.class.php.
References ajax_combobox(), db, dol_syslog(), and if.
select_color ($set_color = '', $prefix = 'f_color', $form_name = '', $showcolorbox = 1, $arrayofcolors = '')
Output a HTML code to select a color.
Parameters
string $set_color Pre-selected color
string $prefix Name of HTML field
string $form_name Deprecated. Not used.
int $showcolorbox 1=Show color code and color box, 0=Show only color code
array $arrayofcolors Array of colors. Example: array('29527A','5229A3','A32929','7A367A','B1365F','0D7813')
Returns
void
Deprecated:
Use instead selectColor
See also
selectColor()
Definition at line 676 of file html.formother.class.php.
References print, and selectColor().
select_dayofweek ($selected = '', $htmlname = 'weekid', $useempty = 0)
Return HTML combo list of week.
Parameters
string $selected Preselected value
string $htmlname Nom de la zone select
int $useempty Affiche valeur vide dans liste
Returns
string
Definition at line 832 of file html.formother.class.php.
select_dictionary ($htmlname, $dictionarytable, $keyfield = 'code', $labelfield = 'label', $selected = '', $useempty = 0, $moreattrib = '')
Return a HTML select list of a dictionary.
Parameters
string $htmlname Name of select zone
string $dictionarytable Dictionary table
string $keyfield Field for key
string $labelfield Label field
string $selected Selected value
int $useempty 1=Add an empty value in list, 2=Add an empty value in list only if there is more than 2 entries.
string $moreattrib More attributes on HTML select tag
Returns
void
Definition at line 1215 of file html.formother.class.php.
References db, dol_print_error(), dol_syslog(), and print.
select_ecotaxes ($selected = '', $htmlname = 'ecotaxe_id')
Return list of ecotaxes with label.
Parameters
string $selected Preselected ecotaxes
string $htmlname Name of combo list
Returns
integer
Definition at line 172 of file html.formother.class.php.
References $resql, db, dol_print_error(), dol_syslog(), price(), and print.
select_export_model ($selected = '', $htmlname = 'exportmodelid', $type = '', $useempty = 0, $fk_user = null)
Return HTML select list of export models.
Parameters
string $selected Id modele pre-selectionne
string $htmlname Nom de la zone select
string $type Type des modeles recherches
int $useempty Show an empty value in list
int $fk_user User that has created the template (this is set to null to get all export model when EXPORTS_SHARE_MODELS is on)
Returns
void
Definition at line 71 of file html.formother.class.php.
References db, dol_print_error(), and print.
select_import_model ($selected = '', $htmlname = 'importmodelid', $type = '', $useempty = 0)
Return list of export models.
Parameters
string $selected Id modele pre-selectionne
string $htmlname Nom de la zone select
string $type Type des modeles recherches
int $useempty Affiche valeur vide dans liste
Returns
void
Definition at line 123 of file html.formother.class.php.
References db, dol_print_error(), and print.
select_month ($selected = '', $htmlname = 'monthid', $useempty = 0, $longlabel = 0, $morecss = 'maxwidth50imp valignmiddle')
Return HTML combo list of month.
Parameters
string $selected Preselected value
string $htmlname Name of HTML select object
int $useempty Show empty in list
int $longlabel Show long label
string $morecss More Css
Returns
string
Definition at line 880 of file html.formother.class.php.
References if, and monthArray().
select_percent ($selected = 0, $htmlname = 'percent', $disabled = 0, $increment = 5, $start = 0, $end = 100, $showempty = 0)
Return a HTML select list to select a percent.
Parameters
integer $selected pourcentage pre-selectionne
string $htmlname nom de la liste deroulante
int $disabled Disabled or not
int $increment increment value
int $start start value
int $end end value
int $showempty Add also an empty line
Returns
string HTML select string
Definition at line 294 of file html.formother.class.php.
select_revenue_stamp ($selected = '', $htmlname = 'revenuestamp', $country_code = '')
Return list of revenue stamp for country.
Parameters
string $selected Value of preselected revenue stamp
string $htmlname Name of combo list
string $country_code Country Code
Returns
string HTML select list
Definition at line 231 of file html.formother.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
select_salesrepresentatives ($selected, $htmlname, $user, $showstatus = 0, $showempty = 1, $morecss = '')
Return select list for categories (to use in form search selectors)
Parameters
string $selected Preselected value
string $htmlname Name of combo list (example: 'search_sale')
User $user Object user
int $showstatus 0=show user status only if status is disabled, 1=always show user status into label, -1=never show user status
int $showempty 1=show also an empty value
string $morecss More CSS
Returns
string Html combo list code
Definition at line 393 of file html.formother.class.php.
References ajax_combobox(), db, dol_print_error(), dolGetFirstLastname(), getEntity(), and if.
select_year ($selected = '', $htmlname = 'yearid', $useempty = 0, $min_year = 10, $max_year = 5, $offset = 0, $invert = 0, $option = '', $morecss = 'valignmiddle maxwidth75imp')
Return HTML combo list of years.
Parameters
string $selected Preselected value (''=current year, -1=none, year otherwise)
string $htmlname Name of HTML select object
int $useempty Affiche valeur vide dans liste
int $min_year Offset of minimum year into list (by default current year -10)
int $max_year Offset of maximum year into list (by default current year + 5)
int $offset Offset
int $invert Invert
string $option Option
string $morecss More CSS
Returns
string
Definition at line 927 of file html.formother.class.php.
References print, and selectyear().
selectAutoManual ($htmlname, $value = '', $option = 0, $disabled = false, $useempty = 0)
Return an html string with a select combo box to choose yes or no.
Parameters
string $htmlname Name of html select field
string $value Pre-selected value
int $option 0 return automatic/manual, 1 return 1/0
bool $disabled true or false
int $useempty 1=Add empty line
Returns
string See option
Definition at line 1275 of file html.formother.class.php.
static selectColor ($set_color = '', $prefix = 'f_color', $form_name = '', $showcolorbox = 1, $arrayofcolors = '', $morecss = '') static
Output a HTML code to select a color.
Field will return an hexa color like '334455'.
Parameters
string $set_color Pre-selected color
string $prefix Name of HTML field
string $form_name Deprecated. Not used.
int $showcolorbox 1=Show color code and color box, 0=Show only color code
array $arrayofcolors Array of colors. Example: array('29527A','5229A3','A32929','7A367A','B1365F','0D7813')
string $morecss Add css style into input field
Returns
string
See also
showColor()
Definition at line 694 of file html.formother.class.php.
References dol_escape_js(), dol_syslog(), label, name, and type.
Referenced by select_color().
selectProjectTasks ($selectedtask = '', $projectid = 0, $htmlname = 'task_parent', $modeproject = 0, $modetask = 0, $mode = 0, $useempty = 0, $disablechildoftaskid = 0, $filteronprojstatus = '', $morecss = '')
Return list of project and tasks.
Parameters
int $selectedtask Pre-selected task
int $projectid Project id
string $htmlname Name of html select
int $modeproject 1 to restrict on projects owned by user
int $modetask 1 to restrict on tasks associated to user
int $mode 0=Return list of tasks and their projects, 1=Return projects and tasks if exists
int $useempty 0=Allow empty values
int $disablechildoftaskid 1=Disable task that are child of the provided task id
string $filteronprojstatus Filter on project status ('-1'=no filter, '0,1'=Draft+Validated status)
string $morecss More css
Returns
void
Definition at line 522 of file html.formother.class.php.
References _pLineSelect(), ajax_combobox(), db, if, and print.
selectyear ($selected = '', $htmlname = 'yearid', $useempty = 0, $min_year = 10, $max_year = 5, $offset = 0, $invert = 0, $option = '', $morecss = 'valignmiddle maxwidth75imp')
Return HTML combo list of years.
Parameters
string $selected Preselected value (''=current year, -1=none, year otherwise)
string $htmlname Name of HTML select object
int $useempty Affiche valeur vide dans liste
int $min_year Offset of minimum year into list (by default current year -10)
int $max_year Offset of maximum year into list (by default current year + 5)
int $offset Offset
int $invert Invert
string $option Option
string $morecss More css
Returns
string
Definition at line 947 of file html.formother.class.php.
Referenced by select_year().
static showColor ($color, $textifnotdefined = '') static
Output a HTML thumb of color or a text if not defined.
Parameters
string $color String with hex (FFFFFF) or comma RGB ('255,255,255')
string $textifnotdefined Text to show if color not defined
Returns
string HTML code for color thumb
See also
selectColor()
Definition at line 651 of file html.formother.class.php.
References colorArrayToHex(), colorIsLight(), colorStringToArray(), and print.
The documentation for this class was generated from the following file:
htdocs/core/class/html.formother.class.php