Dolibarr: ProductCombination Class Reference
ProductCombination Class Reference
Class ProductCombination Used to represent a product combination.
Public Member Functions
__construct (DoliDB $db)
Constructor.
fetch ($rowid)
Retrieves a combination by its rowid.
fetchByFkProductChild ($fk_child)
Retrieves a product combination by a child product row id.
fetchAllByFkProductParent ($fk_product_parent)
Retrieves all product combinations by the product parent row id.
countNbOfCombinationForFkProductParent ($fk_product_parent)
Retrieves all product combinations by the product parent row id.
create ($user)
Creates a product attribute combination.
update (User $user)
Updates a product combination.
delete (User $user)
Deletes a product combination.
deleteByFkProductParent ($user, $fk_product_parent)
Deletes all product combinations of a parent product.
updateProperties (Product $parent)
Updates the weight of the child product.
fetchByProductCombination2ValuePairs ($prodid, array $features)
Retrieves the combination that matches the given features.
getUniqueAttributesAndValuesByFkProductParent ($productid)
Retrieves all unique attributres for a parent product.
createProductCombination (Product $product, array $combinations, array $variations, $price_var_percent=false, $forced_pricevar=false, $forced_weightvar=false)
Creates a product combination.
copyAll ($origProductId, Product $destProduct)
Copies all product combinations from the origin product to the destination product.
getCombinationLabel ($prod_child)
Return label for combinations.
Detailed Description
Class ProductCombination Used to represent a product combination.
Definition at line 24 of file ProductCombination.class.php.
Constructor & Destructor Documentation
__construct (DoliDB $db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 79 of file ProductCombination.class.php.
References db.
Member Function Documentation
copyAll ($origProductId, Product $destProduct)
Copies all product combinations from the origin product to the destination product.
Parameters
int $origProductId Origin product id
Product $destProduct Destination product
Returns
int >0 OK <0 KO
Definition at line 671 of file ProductCombination.class.php.
References createProductCombination(), db, and fetchAllByFkProductParent().
countNbOfCombinationForFkProductParent ($fk_product_parent)
Retrieves all product combinations by the product parent row id.
Parameters
int $fk_product_parent Id of parent product
Returns
int Nb of record
Definition at line 191 of file ProductCombination.class.php.
References $resql, db, and getEntity().
create ($user)
Creates a product attribute combination.
Parameters
User $user Object user
Returns
int <0 if KO, >0 if OK
Definition at line 211 of file ProductCombination.class.php.
References db.
createProductCombination (Product $product, array $combinations, array $variations, $price_var_percent = false, $forced_pricevar = false, $forced_weightvar = false)
Creates a product combination.
Check usages to find more about its use
Format of $combinations array: array(0 => array(attr => value, attr2 => value [...]), [...])
Parameters
Product $product Parent product
array $combinations Attribute and value combinations.
array $variations Price and weight variations
bool $price_var_percent Is the price variation a relative variation?
bool | float $forced_pricevar If the price variation is forced
bool | float $forced_weightvar If the weight variation is forced
Returns
int <0 KO, >0 OK
If there is an existing combination, then we update the prices and weight Otherwise, we try adding a random number to the ref
Definition at line 509 of file ProductCombination.class.php.
References price2num().
Referenced by copyAll().
delete (User $user)
Deletes a product combination.
Parameters
User $user Object user
Returns
int <0 if KO, >0 if OK
Definition at line 263 of file ProductCombination.class.php.
References db.
deleteByFkProductParent ($user, $fk_product_parent)
Deletes all product combinations of a parent product.
Parameters
User $user Object user
int $fk_product_parent Rowid of parent product
Returns
int <0 KO >0 OK
Definition at line 288 of file ProductCombination.class.php.
References db, and fetchAllByFkProductParent().
fetch ($rowid)
Retrieves a combination by its rowid.
Parameters
int $rowid Row id
Returns
int <0 KO, >0 OK
Definition at line 93 of file ProductCombination.class.php.
References db, and getEntity().
fetchAllByFkProductParent ($fk_product_parent)
Retrieves all product combinations by the product parent row id.
Parameters
int $fk_product_parent Rowid of parent product
Returns
int|ProductCombination[] <0 KO
Definition at line 157 of file ProductCombination.class.php.
References db, and getEntity().
Referenced by copyAll(), and deleteByFkProductParent().
fetchByFkProductChild ($fk_child)
Retrieves a product combination by a child product row id.
Parameters
int $fk_child Product row id
Returns
int <0 KO, >0 OK
Definition at line 125 of file ProductCombination.class.php.
References db, and getEntity().
fetchByProductCombination2ValuePairs ($prodid, array $features)
Retrieves the combination that matches the given features.
Parameters
int $prodid Id of parent product
array $features Format: [$attr] => $attr_val
Returns
false|ProductCombination False if not found
Definition at line 409 of file ProductCombination.class.php.
References db.
getCombinationLabel ($prod_child)
Return label for combinations.
Parameters
int $prod_child id of child
Returns
string combination label
Definition at line 714 of file ProductCombination.class.php.
References $resql, and db.
Referenced by updateProperties().
getUniqueAttributesAndValuesByFkProductParent ($productid)
Retrieves all unique attributres for a parent product.
Parameters
int $productid Product rowid
Returns
ProductAttribute[]
Definition at line 447 of file ProductCombination.class.php.
References db.
update (User $user)
Updates a product combination.
Parameters
User $user Object user
Returns
int <0 KO, >0 OK
Definition at line 236 of file ProductCombination.class.php.
References db, and updateProperties().
updateProperties (Product $parent)
Updates the weight of the child product.
The price must be updated using Product::updatePrices
Parameters
Product $parent Parent product
Returns
int >0 OK <0 KO
Definition at line 322 of file ProductCombination.class.php.
References db, getCombinationLabel(), and Product\updatePrice().
Referenced by update().
The documentation for this class was generated from the following file:
htdocs/variants/class/ProductCombination.class.php