Dolibarr: DataPolicy Class Reference
DataPolicy Class Reference
Class DataPolicy.
Public Member Functions
getAllContactNotInformed ()
getAllContactNotInformed
getAllCompaniesNotInformed ()
getAllCompaniesNotInformed
getAllAdherentsNotInformed ()
getAllAdherentsNotInformed
sendMailDataPolicyContact ($contact)
sendMailDataPolicyContact
sendMailDataPolicyCompany ($societe)
sendMailDataPolicyCompany
sendMailDataPolicyAdherent ($adherent)
sendMailDataPolicyAdherent
Detailed Description
Class DataPolicy.
Definition at line 31 of file datapolicy.class.php.
Member Function Documentation
getAllAdherentsNotInformed ()
getAllAdherentsNotInformed
Returns
number
Definition at line 109 of file datapolicy.class.php.
References $resql, db, and sendMailDataPolicyAdherent().
getAllCompaniesNotInformed ()
getAllCompaniesNotInformed
Returns
number
Definition at line 74 of file datapolicy.class.php.
References $resql, db, and sendMailDataPolicyCompany().
getAllContactNotInformed ()
getAllContactNotInformed
Returns
number
Definition at line 38 of file datapolicy.class.php.
References $resql, db, and sendMailDataPolicyContact().
sendMailDataPolicyAdherent ($adherent)
sendMailDataPolicyAdherent
Parameters
Adherent $adherent Member
Returns
void
Definition at line 294 of file datapolicy.class.php.
References dol_buildpath(), dol_concatdesc(), dol_print_error(), make_substitutions(), and setEventMessage().
Referenced by ActionsDatapolicy\doActions(), and getAllAdherentsNotInformed().
sendMailDataPolicyCompany ($societe)
sendMailDataPolicyCompany
Parameters
Societe $societe Object societe
Returns
void
Definition at line 220 of file datapolicy.class.php.
References dol_buildpath(), dol_concatdesc(), dol_print_error(), make_substitutions(), and setEventMessage().
Referenced by ActionsDatapolicy\doActions(), and getAllCompaniesNotInformed().
sendMailDataPolicyContact ($contact)
sendMailDataPolicyContact
Parameters
mixed $contact Contact
Returns
void
Definition at line 145 of file datapolicy.class.php.
References dol_buildpath(), dol_concatdesc(), dol_print_error(), make_substitutions(), and setEventMessage().
Referenced by ActionsDatapolicy\doActions(), and getAllContactNotInformed().
The documentation for this class was generated from the following file:
htdocs/datapolicy/class/datapolicy.class.php