Dolibarr: ActionsContactCardCommon Class Reference
ActionsContactCardCommon Class Reference
Classe permettant la gestion des contacts par defaut.
Public Member Functions
getObject ($id)
Get object.
assign_values (&$action, $id)
Set content of ->tpl array, to use into template.
Data Fields
$tpl = array()
Template container.
$object
Object container.
Private Member Functions
assign_post ()
Assign POST values into object.
Detailed Description
Classe permettant la gestion des contacts par defaut.
Definition at line 28 of file actions_contactcard_common.class.php.
Member Function Documentation
assign_post () private
Assign POST values into object.
Returns
string HTML output
Definition at line 276 of file actions_contactcard_common.class.php.
References $resql, db, and dol_print_error().
Referenced by assign_values().
assign_values (& $action, $id)
Set content of ->tpl array, to use into template.
Parameters
string $action Type of action
int $id Id
Returns
string HTML output
Definition at line 87 of file actions_contactcard_common.class.php.
References assign_post(), db, dol_buildlogin(), dol_nl2br(), dol_print_email(), dol_print_phone(), dol_strlen(), getRandomPassword(), info_admin(), and picto_from_langcode().
getObject ($id)
Get object.
Parameters
int $id Object id
Returns
object Object loaded
Definition at line 63 of file actions_contactcard_common.class.php.
References $object, and db.
Referenced by ActionsContactCardDefault\assign_values().
The documentation for this class was generated from the following file:
htdocs/contact/canvas/actions_contactcard_common.class.php