Dolibarr: Cpaiement Class Reference
Cpaiement Class Reference
Class Cpaiement.
Public Member Functions
__construct (DoliDB $db)
Constructor.
create (User $user, $notrigger=false)
Create object into database.
fetch ($id, $ref=null)
Load object in memory from the database.
update (User $user, $notrigger=false)
Update object into database.
delete (User $user, $notrigger=false)
Delete object in database.
initAsSpecimen ()
Initialise object with example values Id must be 0 if object instance is a specimen.
Detailed Description
Class Cpaiement.
Definition at line 31 of file cpaiement.class.php.
Constructor & Destructor Documentation
__construct (DoliDB $db)
Constructor.
Parameters
DoliDb $db Database handler
Definition at line 56 of file cpaiement.class.php.
References db.
Member Function Documentation
create (User $user, $notrigger = false)
Create object into database.
Parameters
User $user User that creates
bool $notrigger false=launch triggers after, true=disable triggers
Returns
int <0 if KO, Id of created object if OK
Definition at line 69 of file cpaiement.class.php.
References $resql, db, dol_syslog(), getEntity(), and type.
delete (User $user, $notrigger = false)
Delete object in database.
Parameters
User $user User that deletes
bool $notrigger false=launch triggers after, true=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 309 of file cpaiement.class.php.
References $resql, db, and dol_syslog().
fetch ($id, $ref = null)
Load object in memory from the database.
Parameters
int $id Id object
string $ref Ref
Returns
int <0 if KO, 0 if not found, >0 if OK
Definition at line 169 of file cpaiement.class.php.
References $resql, db, dol_syslog(), and type.
initAsSpecimen ()
Initialise object with example values Id must be 0 if object instance is a specimen.
Returns
void
Definition at line 358 of file cpaiement.class.php.
References type.
update (User $user, $notrigger = false)
Update object into database.
Parameters
User $user User that modifies
bool $notrigger false=launch triggers after, true=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 227 of file cpaiement.class.php.
References $resql, db, dol_syslog(), and type.
The documentation for this class was generated from the following file:
htdocs/compta/paiement/class/cpaiement.class.php