Dolibarr: htdocs/core/lib/json.lib.php File Reference
json.lib.php File Reference
Functions to emulate json function when there were not activated.
Functions
if(!function_exists('json_encode')) dol_json_encode ($elements)
Implement json_encode for PHP that does not support it.
_val ($val)
Return text according to type.
if(!function_exists('json_decode')) dol_json_decode ($json, $assoc=false)
Implement json_decode for PHP that does not support it Use json_encode and json_decode in your code !
_unval ($val)
Return text according to type.
utf162utf8 ($utf16)
Convert a string from one UTF-16 char to one UTF-8 char.
utf82utf16 ($utf8)
Convert a string from one UTF-8 char to one UTF-16 char.
Detailed Description
Functions to emulate json function when there were not activated.
Definition in file json.lib.php.
Function Documentation
_unval ($val)
Return text according to type.
Parameters
string $val Value to decode
Returns
string Formated value
Definition at line 288 of file json.lib.php.
References utf162utf8().
Referenced by dol_json_decode().
_val ($val)
Return text according to type.
Parameters
mixed $val Value to show
Returns
string Formated value
Implement json_decode for PHP that does not support it
Parameters
string $json Json encoded to PHP Object or Array
bool $assoc False return an object, true return an array
Returns
mixed Object or Array
Definition at line 108 of file json.lib.php.
References dol_json_decode(), and utf82utf16().
Referenced by dol_json_encode().
if (!function_exists('json_decode')) dol_json_decode ($json, $assoc = false)
Implement json_decode for PHP that does not support it Use json_encode and json_decode in your code !
Parameters
string $json Json encoded to PHP Object or Array
bool $assoc False return an object, true return an array. Try to always use it with true !
Returns
mixed Object or Array or false on error
See also
json_decode()
Definition at line 232 of file json.lib.php.
References _unval(), and dol_syslog().
Referenced by _val(), and Stripe\getStripeAccount().
if (!function_exists('json_encode')) dol_json_encode ($elements)
Implement json_encode for PHP that does not support it.
Use json_encode and json_decode in your code !
Parameters
mixed $elements PHP Object to json encode
Returns
string Json encoded string
See also
json_encode()
Definition at line 48 of file json.lib.php.
References _val(), and dol_syslog().
utf162utf8 ($utf16)
Convert a string from one UTF-16 char to one UTF-8 char.
Normally should be handled by mb_convert_encoding, but provides a slower PHP-only method for installations that lack the multibye string extension.
Parameters
string $utf16 UTF-16 character
Returns
string UTF-8 character
Definition at line 310 of file json.lib.php.
Referenced by _unval().
utf82utf16 ($utf8)
Convert a string from one UTF-8 char to one UTF-16 char.
Normally should be handled by mb_convert_encoding, but provides a slower PHP-only method for installations that lack the multibye string extension.
Parameters
string $utf8 UTF-8 character
Returns
string UTF-16 character
Definition at line 353 of file json.lib.php.
Referenced by _val().