Dolibarr: DoliDB Class Reference
DoliDB Class Reference
Class to manage Dolibarr database access.
Public Member Functions
ifsql ($test, $resok, $resko)
Format a SQL IF.
idate ($param)
Convert (by PHP) a GM Timestamp date into a string date with PHP server TZ to insert into a date field.
lasterrno ()
Return last error code.
begin ()
Start transaction.
commit ($log= '')
Validate a database transaction.
rollback ($log= '')
Cancel a transaction and go back to initial data values.
plimit ($limit=0, $offset=0)
Define limits and offset of request.
getVersionArray ()
Return version of database server into an array.
lastquery ()
Return last request executed with query()
order ($sortfield=null, $sortorder=null)
Define sort criteria of request.
lasterror ()
Return last error label.
jdate ($string, $gm=false)
Convert (by PHP) a PHP server TZ string date into a Timestamps date (GMT if gm=true) 19700101020000 -> 3600 with TZ+1 and gmt=0 19700101020000 -> 7200 whaterver is TZ if gmt=1.
lastqueryerror ()
Return last query in error.
Public Member Functions inherited from Database
fetch_row ($resultset)
Return datas as an array.
DDLCreateDb ($database, $charset= '', $collation= '', $owner= '')
Create a new database Do not use function xxx_create_db (xxx=mysql, ...) as they are deprecated We force to create database with charset this->forcecharset and collate this->forcecollate.
affected_rows ($resultset)
Return the number of lines in the result of a request INSERT, DELETE or UPDATE.
error ()
Return description of last error.
DDLListTables ($database, $table= '')
List tables into a database.
decrypt ($value)
Decrypt sensitive data in database.
fetch_array ($resultset)
Return datas as an array.
escape ($stringtoencode)
Escape a string to insert data.
last_insert_id ($tab, $fieldid= 'rowid')
Get last ID after an insert INSERT.
getPathOfRestore ()
Return full path of restore program.
query ($query, $usesavepoint=0, $type= 'auto')
Execute a SQL request and return the resultset.
connect ($host, $login, $passwd, $name, $port=0)
Connexion to server.
getServerParametersValues ($filter= '')
Return value of server parameters.
getServerStatusValues ($filter= '')
Return value of server status.
getDefaultCollationDatabase ()
Return collation used in database.
num_rows ($resultset)
Return number of lines for result of a SELECT.
getPathOfDump ()
Return full path of dump program.
getDriverInfo ()
Return version of database client driver.
errno ()
Return generic error code of last operation.
DDLCreateTable ($table, $fields, $primary_key, $type, $unique_keys=null, $fulltext_keys=null, $keys=null)
Create a table into database.
DDLDropTable ($table)
Drop a table into database.
getListOfCharacterSet ()
Return list of available charset that can be used to store data in database.
DDLAddField ($table, $field_name, $field_desc, $field_position="")
Create a new field into table.
DDLDropField ($table, $field_name)
Drop a field from table.
DDLUpdateField ($table, $field_name, $field_desc)
Update format of a field into a table.
getListOfCollation ()
Return list of available collation that can be used for database.
DDLDescTable ($table, $field="")
Return a pointer of line with description of a table or field.
getVersion ()
Return version of database server.
getDefaultCharacterSetDatabase ()
Return charset used to store data in database.
DDLCreateUser ($dolibarr_main_db_host, $dolibarr_main_db_user, $dolibarr_main_db_pass, $dolibarr_main_db_name)
Create a user and privileges to connect to database (even if database does not exists yet)
encrypt ($fieldorvalue, $withQuotes=0)
Encrypt sensitive data in database Warning: This function includes the escape, so it must use direct value.
DDLInfoTable ($table)
List information of columns into a table.
free ($resultset=null)
Free last resultset used.
close ()
Close database connexion.
DDLGetConnectId ()
Return connexion ID.
fetch_object ($resultset)
Renvoie la ligne courante (comme un objet) pour le curseur resultset.
select_db ($database)
Select a database.
Additional Inherited Members
Static Public Member Functions inherited from Database
static convertSQLFromMysql ($line, $type= 'ddl')
Convert a SQL request in Mysql syntax to native syntax.
Detailed Description
Class to manage Dolibarr database access.
Definition at line 30 of file DoliDB.class.php.
Member Function Documentation
begin ()
Start transaction.
Returns
int 1 if transaction successfuly opened or already opened, 0 if error
Implements Database.
Definition at line 111 of file DoliDB.class.php.
References dol_syslog(), and Database\query().
commit ($log = '')
Validate a database transaction.
Parameters
string $log Add more log to default log line
Returns
int 1 if validation is OK or transaction level no started, 0 if ERROR
Implements Database.
Definition at line 138 of file DoliDB.class.php.
References dol_syslog(), and Database\query().
getVersionArray ()
Return version of database server into an array.
Returns
array Version array
Implements Database.
Definition at line 206 of file DoliDB.class.php.
References Database\getVersion().
idate ($param)
Convert (by PHP) a GM Timestamp date into a string date with PHP server TZ to insert into a date field.
Function to use to build INSERT, UPDATE or WHERE predica
Parameters
int $param Date TMS to convert
Returns
string Date in a string YYYY-MM-DD HH:MM:SS
Implements Database.
Definition at line 90 of file DoliDB.class.php.
References dol_print_date().
ifsql ($test, $resok, $resko)
Format a SQL IF.
Parameters
string $test Test string (example: 'cd.statut=0', 'field IS NULL')
string $resok resultat si test egal
string $resko resultat si test non egal
Returns
string SQL string
Implements Database.
Definition at line 78 of file DoliDB.class.php.
jdate ($string, $gm = false)
Convert (by PHP) a PHP server TZ string date into a Timestamps date (GMT if gm=true) 19700101020000 -> 3600 with TZ+1 and gmt=0 19700101020000 -> 7200 whaterver is TZ if gmt=1.
Parameters
string $string Date in a string (YYYYMMDDHHMMSS, YYYYMMDD, YYYY-MM-DD HH:MM:SS)
bool $gm 1=Input informations are GMT values, otherwise local to server TZ
Returns
int|string Date TMS or ''
Implements Database.
Definition at line 281 of file DoliDB.class.php.
References dol_mktime().
lasterrno ()
Return last error code.
Returns
string lasterrno
Implements Database.
Definition at line 101 of file DoliDB.class.php.
Referenced by DoliDBMssql\DDLCreateUser(), DoliDBMssql\errno(), DoliDBMysqli\query(), DoliDBMssql\query(), DoliDBSqlite3\query(), and DoliDBPgsql\query().
lasterror ()
Return last error label.
Returns
string Last error
Implements Database.
Definition at line 267 of file DoliDB.class.php.
Referenced by DoliDBMssql\DDLDropField(), DoliDBPgsql\DDLDropField(), DoliDBMysqli\query(), DoliDBMssql\query(), DoliDBSqlite3\query(), and DoliDBPgsql\query().
lastquery ()
Return last request executed with query()
Returns
string Last query
Implements Database.
Definition at line 216 of file DoliDB.class.php.
Referenced by DoliDBMysqli\query(), DoliDBMssql\query(), DoliDBSqlite3\query(), and DoliDBPgsql\query().
lastqueryerror ()
Return last query in error.
Returns
string lastqueryerror
Implements Database.
Definition at line 296 of file DoliDB.class.php.
Referenced by DoliDBMysqli\query(), DoliDBMssql\query(), DoliDBSqlite3\query(), and DoliDBPgsql\query().
order ($sortfield = null, $sortorder = null)
Define sort criteria of request.
Parameters
string $sortfield List of sort fields, separated by comma. Example: 't1.fielda,t2.fieldb'
string $sortorder Sort order, separated by comma. Example: 'ASC,DESC';
Returns
string String to provide syntax of a sort sql string
Implements Database.
Definition at line 228 of file DoliDB.class.php.
plimit ($limit = 0, $offset = 0)
Define limits and offset of request.
Parameters
int $limit Maximum number of lines returned (-1=conf->liste_limit, 0=no limit)
int $offset Numero of line from where starting fetch
Returns
string String with SQL syntax to add a limit and offset
Implements Database.
Definition at line 192 of file DoliDB.class.php.
rollback ($log = '')
Cancel a transaction and go back to initial data values.
Parameters
string $log Add more log to default log line
Returns
resource|int 1 if cancelation is ok or transaction not open, 0 if error
Implements Database.
Definition at line 168 of file DoliDB.class.php.
References dol_syslog(), and Database\query().
The documentation for this class was generated from the following file:
htdocs/core/db/DoliDB.class.php