Dolibarr: mod_codeclient_elephant Class Reference
mod_codeclient_elephant Class Reference
Class to manage third party code with elephant rule.
Public Member Functions
__construct ()
Constructor.
info ($langs)
Return description of module.
getExample ($langs, $objsoc=0, $type=-1)
Return an example of result returned by getNextValue.
getNextValue ($objsoc=0, $type=-1)
Return next value.
verif_prefixIsUsed ()
Check if mask/numbering use prefix.
verif ($db, &$code, $soc, $type)
Check validity of code according to its rules.
verif_dispo ($db, $code, $soc, $type=0)
Renvoi si un code est pris ou non (par autre tiers)
Public Member Functions inherited from ModeleThirdPartyCode
info ($langs)
Renvoi la description par defaut du modele de numerotation.
getNom ($langs)
Renvoi nom module.
getExample ($langs)
Renvoi un exemple de numerotation.
canBeActivated ()
Test si les numeros deja en vigueur dans la base ne provoquent pas de de conflits qui empechera cette numerotation de fonctionner.
getNextValue ($objsoc=0, $type=-1)
Return next value available.
getVersion ()
Return version of module.
getToolTip ($langs, $soc, $type)
Return description of module parameters.
verif_prefixIsUsed ()
Check if mask/numbering use prefix.
Additional Inherited Members
Static Public Member Functions inherited from ModeleThirdPartyCode
static liste_modeles ($db, $maxfilenamelength=0)
Renvoie la liste des modeles de numérotation.
Detailed Description
Class to manage third party code with elephant rule.
Definition at line 35 of file mod_codeclient_elephant.php.
Member Function Documentation
getExample ($langs, $objsoc = 0, $type = -1)
Return an example of result returned by getNextValue.
Parameters
Translate $langs Object langs
societe $objsoc Object thirdparty
int $type Type of third party (1:customer, 2:supplier, -1:autodetect)
Returns
string Return string example
Definition at line 143 of file mod_codeclient_elephant.php.
References getNextValue().
getNextValue ($objsoc = 0, $type = -1)
Return next value.
Parameters
Societe $objsoc Object third party
int $type Client ou fournisseur (0:customer, 1:supplier)
Returns
string Value if OK, '' if module not configured, <0 if KO
Definition at line 204 of file mod_codeclient_elephant.php.
References dol_now(), and get_next_value().
Referenced by getExample().
info ($langs)
Return description of module.
Parameters
Translate $langs Object langs
Returns
string Description of module
Definition at line 92 of file mod_codeclient_elephant.php.
verif ($db, & $code, $soc, $type)
Check validity of code according to its rules.
Parameters
DoliDB $db Database handler
string $code Code to check/correct
Societe $soc Object third party
int $type 0 = customer/prospect , 1 = supplier
Returns
int 0 if OK -1 ErrorBadCustomerCodeSyntax -2 ErrorCustomerCodeRequired -3 ErrorCustomerCodeAlreadyUsed -4 ErrorPrefixRequired -5 Other (see this->error)
Definition at line 276 of file mod_codeclient_elephant.php.
References check_value(), and dol_syslog().
verif_dispo ($db, $code, $soc, $type = 0)
Renvoi si un code est pris ou non (par autre tiers)
Parameters
DoliDB $db Handler acces base
string $code Code a verifier
Societe $soc Objet societe
int $type 0 = customer/prospect , 1 = supplier
Returns
int 0 if available, <0 if KO
Definition at line 328 of file mod_codeclient_elephant.php.
References $resql.
verif_prefixIsUsed ()
Check if mask/numbering use prefix.
Returns
int 0 or 1
Definition at line 247 of file mod_codeclient_elephant.php.
The documentation for this class was generated from the following file:
htdocs/core/modules/societe/mod_codeclient_elephant.php