Dolibarr: Expedition Class Reference
Expedition Class Reference
Class to manage shipments.
Public Member Functions
__construct ($db)
Constructor.
getNextNumRef ($soc)
Return next contract ref.
create ($user, $notrigger=0)
Create expedition en base.
create_line ($entrepot_id, $origin_line_id, $qty, $rang, $array_options=0)
Create a expedition line.
create_line_batch ($line_ext, $array_options=0)
Create the detail (eat-by date) of the expedition line.
fetch ($id, $ref= '', $ref_ext= '', $ref_int= '')
Get object and lines from database.
valid ($user, $notrigger=0)
Validate object and update stock if option enabled.
create_delivery ($user)
Create a delivery receipt from a shipment.
addline ($entrepot_id, $id, $qty, $array_options=0)
Add an expedition line.
addline_batch ($dbatch, $array_options=0)
Add a shipment line with batch record.
update ($user=null, $notrigger=0)
Update database.
delete ($notrigger=0, $also_update_stock=false)
Delete shipment.
fetch_lines ()
Load lines.
deleteline ($user, $lineid)
Delete detail line.
getNomUrl ($withpicto=0, $option= '', $max=0, $short=0, $notooltip=0, $save_lastsearch_value=-1)
Return clicable link of object (with eventually picto)
getLibStatut ($mode=0)
Return status label.
LibStatut ($statut, $mode)
Return label of a status.
initAsSpecimen ()
Initialise an instance with random values.
set_date_livraison ($user, $date_livraison)
Set the planned delivery date.
fetch_delivery_methods ()
Fetch deliveries method and return an array.
list_delivery_methods ($id= '')
Fetch all deliveries method and return an array.
update_delivery_method ($id= '')
Update/create delivery method.
activ_delivery_method ($id)
Activate delivery method.
disable_delivery_method ($id)
DesActivate delivery method.
getUrlTrackingStatus ($value= '')
Forge an set tracking url.
setClosed ()
Classify the shipping as closed.
set_billed ()
Classify the shipping as invoiced (used when WORKFLOW_BILL_ON_SHIPMENT is on)
reOpen ()
Classify the shipping as validated/opened.
generateDocument ($modele, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0, $moreparams=null)
Create a document onto disk according to template module.
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0)
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source= 'external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source= 'internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source= '', $code= '')
Delete all links between an object $this and all its contacts.
liste_contact ($statut=-1, $source= 'external', $list=0, $code= '')
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source= 'internal', $order= 'position', $option=0, $activeonly=0, $code= '')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contactid into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table= '', $id=null, $format= '', $id_field= '', $fuser=null, $trigkey= '', $fk_user_field= 'fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source= 'external')
Return list of id of contacts of object.
setProject ($projectid)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id)
Change the payments terms.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder= 'ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix= '')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust= 'none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null)
Add objects linked in llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $clause= 'OR', $alsosametype=1, $orderby= 'sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
updateObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '')
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $rowid= '')
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType= '', $trigkey= '')
Set status of an object.
getCanvas ($id=0, $ref= '')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
display_incoterms ()
Return incoterms informations TODO Use a cache for label get.
getIncotermsForPDF ()
Return incoterms informations for pdf display.
setIncoterms ($id_incoterm, $location)
Define incoterms values of current object.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir= '/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir= '/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafieldsline=0, $defaulttpldir= '/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist= '', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist= '', $defaulttpldir= '/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
addThumbs ($file)
Build thumb Move this into files.lib.php.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($trigger_name, $user)
Call trigger based on this instance.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger= '', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update an extra field value for the current object.
showInputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
showOutputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss= '')
Return HTML string to show a field into a page Code very similar with showOutputField of extra fields.
showOptionals ($extrafields, $mode= 'view', $params=null, $keysuffix= '', $keyprefix= '', $onetrtd=0)
Function to show lines of extrafields with output datas.
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere= '')
Load object in memory from the database.
fetchLinesCommon ($morewhere= '')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
Static Public Member Functions
static replaceThirdparty (DoliDB $db, $origin_id, $dest_id)
Function used to replace a thirdparty id with another one.
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref= '', $ref_ext= '')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static commonReplaceThirdparty (DoliDB $db, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
Data Fields
$date
$date_expedition
const STATUS_DRAFT = 0
Draft status.
const STATUS_VALIDATED = 1
Validated status.
const STATUS_CLOSED = 2
Closed status.
Data Fields inherited from CommonObject
$projet
$note
Additional Inherited Members
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
isNull ($info)
Function test if type is null.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare the values to insert.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ()
Function to concat keys of fields.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage shipments.
Definition at line 46 of file expedition.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 174 of file expedition.class.php.
References db.
Member Function Documentation
activ_delivery_method ($id)
Activate delivery method.
Parameters
int $id id method to activate
Returns
void
Definition at line 1928 of file expedition.class.php.
References $resql, and db.
addline ($entrepot_id, $id, $qty, $array_options = 0)
Add an expedition line.
If STOCK_WAREHOUSE_NOT_REQUIRED_FOR_SHIPMENTS is set, you can add a shipment line, with no stock source defined If STOCK_MUST_BE_ENOUGH_FOR_SHIPMENT is not set, you can add a shipment line, even if not enough into stock
Parameters
int $entrepot_id Id of warehouse
int $id Id of source line (order line)
int $qty Quantity
array $array_options extrafields array
Returns
int <0 if KO, >0 if OK
Definition at line 917 of file expedition.class.php.
References db.
addline_batch ($dbatch, $array_options = 0)
Add a shipment line with batch record.
Parameters
array $dbatch Array of value (key 'detail' -> Array, key 'qty' total quantity for line, key ix_l : original line index)
array $array_options extrafields array
Returns
int <0 if KO, >0 if OK
Definition at line 991 of file expedition.class.php.
References db, and dol_syslog().
create ($user, $notrigger = 0)
Create expedition en base.
Parameters
User $user Objet du user qui cree
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 si erreur, id expedition creee si ok
Definition at line 267 of file expedition.class.php.
References $resql, CommonObject\add_object_linked(), CommonObject\call_trigger(), create_line(), create_line_batch(), db, dol_now(), dol_sanitizeFileName(), dol_syslog(), CommonObject\insertExtraFields(), and user.
create_delivery ($user)
Create a delivery receipt from a shipment.
Parameters
User $user User
Returns
int <0 if KO, >=0 if OK
Definition at line 878 of file expedition.class.php.
References db.
create_line ($entrepot_id, $origin_line_id, $qty, $rang, $array_options = 0)
Create a expedition line.
Parameters
int $entrepot_id Id of warehouse
int $origin_line_id Id of source line
int $qty Quantity
int $rang Rang
array $array_options extrafields array
Returns
int <0 if KO, line_id if OK
Definition at line 448 of file expedition.class.php.
References db.
Referenced by create(), and create_line_batch().
create_line_batch ($line_ext, $array_options = 0)
Create the detail (eat-by date) of the expedition line.
Parameters
object $line_ext full line informations
array $array_options extrafields array
Returns
int <0 if KO, >0 if OK
Definition at line 477 of file expedition.class.php.
References create_line().
Referenced by create().
delete ($notrigger = 0, $also_update_stock = false)
Delete shipment.
Warning, do not delete a shipment if a delivery is linked to (with table llx_element_element)
Parameters
int $notrigger Disable triggers
bool $also_update_stock true if the stock should be increased back (false by default)
Returns
int >0 if OK, 0 if deletion done but failed to delete files, <0 if KO
Definition at line 1166 of file expedition.class.php.
References $resql, CommonObject\call_trigger(), db, ExpeditionLineBatch\deletefromexp(), CommonObject\deleteObjectLinked(), dol_delete_dir_recursive(), dol_delete_file(), dol_sanitizeFileName(), dol_syslog(), CommonObject\fetch_origin(), ExpeditionLineBatch\fetchAll(), CommonObject\fetchObjectLinked(), Commande\STATUS_SHIPMENTONPROCESS, and Commande\STATUS_VALIDATED.
deleteline ($user, $lineid)
Delete detail line.
Parameters
User $user User making deletion
int $lineid Id of line to delete
Returns
int >0 if OK, <0 if KO
Definition at line 1567 of file expedition.class.php.
References db.
disable_delivery_method ($id)
DesActivate delivery method.
Parameters
int $id id method to desactivate
Returns
void
Definition at line 1945 of file expedition.class.php.
References $resql, and db.
fetch ($id, $ref = '', $ref_ext = '', $ref_int = '')
Get object and lines from database.
Parameters
int $id Id of object to load
string $ref Ref of object
string $ref_ext External reference of object
string $ref_int Internal reference of other object
Returns
int >0 if OK, 0 if not found, <0 if KO
Definition at line 527 of file expedition.class.php.
References db, dol_syslog(), fetch_lines(), CommonObject\fetch_optionals(), CommonObject\fetch_thirdparty(), and getUrlTrackingStatus().
fetch_delivery_methods ()
Fetch deliveries method and return an array.
Load array this->meths(rowid=>label).
Returns
void
Definition at line 1833 of file expedition.class.php.
References $resql, and db.
fetch_lines ()
Load lines.
Returns
int >0 if OK, Otherwise if KO
Definition at line 1382 of file expedition.class.php.
References $resql, calcul_price_total(), db, dol_syslog(), ExpeditionLineBatch\fetchAll(), and get_localtax().
Referenced by fetch().
generateDocument ($modele, $outputlangs, $hidedetails = 0, $hidedesc = 0, $hideref = 0, $moreparams = null)
Create a document onto disk according to template module.
Parameters
string $modele Force the model to using ('' to not force)
Translate $outputlangs object lang to use for translations
int $hidedetails Hide details of lines
int $hidedesc Hide description
int $hideref Hide ref
null | array $moreparams Array to provide more information
Returns
int 0 if KO, 1 if OK
Definition at line 2328 of file expedition.class.php.
References CommonObject\commonGenerateDocument(), dol_strlen(), and CommonObject\fetch_origin().
getLibStatut ($mode = 0)
Return status label.
Parameters
int $mode 0=Long label, 1=Short label, 2=Picto + Short label, 3=Picto, 4=Picto + Long label, 5=Short label + Picto
Returns
string Libelle
Definition at line 1662 of file expedition.class.php.
References LibStatut().
getNextNumRef ($soc)
Return next contract ref.
Parameters
Societe $soc Thirdparty object
Returns
string Free reference for contract
Definition at line 210 of file expedition.class.php.
References db, dol_buildpath(), dol_print_error(), and print.
Referenced by valid().
getNomUrl ($withpicto = 0, $option = '', $max = 0, $short = 0, $notooltip = 0, $save_lastsearch_value = -1)
Return clicable link of object (with eventually picto)
Parameters
int $withpicto Add picto into link
string $option Where the link point to
int $max Max length to show
int $short Use short labels
int $notooltip 1=No tooltip
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
Returns
string String with URL
Definition at line 1612 of file expedition.class.php.
References dol_escape_htmltag(), and img_object().
getUrlTrackingStatus ($value = '')
Forge an set tracking url.
Parameters
string $value Value
Returns
void
Definition at line 1961 of file expedition.class.php.
References $resql, and db.
Referenced by fetch().
initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
void
Definition at line 1719 of file expedition.class.php.
References $resql, db, dol_now(), and dol_syslog().
LibStatut ($statut, $mode)
Return label of a status.
Parameters
int $statut Id statut
int $mode 0=Long label, 1=Short label, 2=Picto + Short label, 3=Picto, 4=Picto + Long label, 5=Short label + Picto
Returns
string Label of status
Definition at line 1675 of file expedition.class.php.
References img_picto().
Referenced by getLibStatut().
list_delivery_methods ($id = '')
Fetch all deliveries method and return an array.
Load array this->listmeths.
Parameters
int $id only this carrier, all if none
Returns
void
Definition at line 1862 of file expedition.class.php.
References $resql, and db.
reOpen ()
Classify the shipping as validated/opened.
Returns
int <0 if KO, 0 if already open, >0 if OK
Definition at line 2192 of file expedition.class.php.
References $resql, CommonObject\call_trigger(), db, and dol_syslog().
static replaceThirdparty (DoliDB $db, $origin_id, $dest_id) static
Function used to replace a thirdparty id with another one.
Parameters
DoliDB $db Database handler
int $origin_id Old thirdparty id
int $dest_id New thirdparty id
Returns
bool
Definition at line 2360 of file expedition.class.php.
References CommonObject\commonReplaceThirdparty().
set_billed ()
Classify the shipping as invoiced (used when WORKFLOW_BILL_ON_SHIPMENT is on)
Returns
int <0 if ko, >0 if ok
Definition at line 2147 of file expedition.class.php.
References $resql, CommonObject\call_trigger(), and db.
set_date_livraison ($user, $date_livraison)
Set the planned delivery date.
Parameters
User $user Objet user that modify
integer $date_livraison Date of delivery
Returns
int <0 if KO, >0 if OK
Definition at line 1799 of file expedition.class.php.
References $resql, db, and dol_syslog().
setClosed ()
Classify the shipping as closed.
Returns
int <0 if KO, >0 if OK
Definition at line 1995 of file expedition.class.php.
References $resql, CommonObject\call_trigger(), db, dol_print_error(), and dol_syslog().
update ($user = null, $notrigger = 0)
Update database.
Parameters
User $user User that modify
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 1060 of file expedition.class.php.
References $resql, CommonObject\call_trigger(), db, dol_syslog(), and note.
Referenced by update_delivery_method().
update_delivery_method ($id = '')
Update/create delivery method.
Parameters
string $id id method to activate
Returns
void
Definition at line 1899 of file expedition.class.php.
References $resql, db, dol_print_error(), and update().
valid ($user, $notrigger = 0)
Validate object and update stock if option enabled.
Parameters
User $user Object user that validate
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if OK, >0 if KO
Definition at line 655 of file expedition.class.php.
References $resql, CommonObject\call_trigger(), db, dol_dir_list(), dol_now(), dol_sanitizeFileName(), dol_syslog(), getNextNumRef(), CommonObject\setStatut(), and Commande\STATUS_SHIPMENTONPROCESS.
Field Documentation
$date
Deprecated:
See also
$date_shipping
Definition at line 132 of file expedition.class.php.
$date_expedition
Deprecated:
See also
$date_shipping
Definition at line 138 of file expedition.class.php.
The documentation for this class was generated from the following file:
htdocs/expedition/class/expedition.class.php