Dolibarr: PriceParser Class Reference
PriceParser Class Reference
Class to parse product price expressions.
Public Member Functions
__construct ($db)
Constructor.
translatedError ()
Returns translated error.
parseExpression ($product, $expression, $values)
Calculates price based on expression.
parseProduct ($product, $extra_values=array())
Calculates product price based on product id and associated expression.
parseProductSupplier ($product_supplier, $extra_values=array())
Calculates supplier product price based on product supplier price and associated expression.
testExpression ($product_id, $expression, $extra_values=array())
Tests string expression for validity.
Detailed Description
Class to parse product price expressions.
Definition at line 33 of file price_parser.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 52 of file price_parser.class.php.
References db.
Member Function Documentation
parseExpression ($product, $expression, $values)
Calculates price based on expression.
Parameters
Product $product The Product object to get information
String $expression The expression to parse
array $values Strings to replaces
Returns
int > 0 if OK, < 1 if KO
Definition at line 133 of file price_parser.class.php.
References db, and dol_now().
Referenced by parseProduct(), parseProductSupplier(), and testExpression().
parseProduct ($product, $extra_values = array())
Calculates product price based on product id and associated expression.
Parameters
Product $product The Product object to get information
array $extra_values Any aditional values for expression
Returns
int > 0 if OK, < 1 if KO
Definition at line 255 of file price_parser.class.php.
References db, and parseExpression().
parseProductSupplier ($product_supplier, $extra_values = array())
Calculates supplier product price based on product supplier price and associated expression.
Parameters
ProductFournisseur $product_supplier The Product supplier object to get information
array $extra_values Any aditional values for expression
Returns
int > 0 if OK, < 1 if KO
Definition at line 296 of file price_parser.class.php.
References db, and parseExpression().
testExpression ($product_id, $expression, $extra_values = array())
Tests string expression for validity.
Parameters
int $product_id The Product id to get information
string $expression The expression to parse
array $extra_values Any aditional values for expression
Returns
int > 0 if OK, < 1 if KO
Definition at line 328 of file price_parser.class.php.
References db, and parseExpression().
translatedError ()
Returns translated error.
Returns
string Translated error
Definition at line 62 of file price_parser.class.php.
The documentation for this class was generated from the following file:
htdocs/product/dynamic_price/class/price_parser.class.php