Dolibarr: Interfaces Class Reference
Interfaces Class Reference
Class to manage triggers.
Public Member Functions
__construct ($db)
Constructor.
run_triggers ($action, $object, $user, $langs, $conf)
Function called when a Dolibarr business event occurs This function call all qualified triggers.
getTriggersList ($forcedirtriggers=null)
Return list of triggers.
Detailed Description
Class to manage triggers.
Definition at line 32 of file interfaces.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 51 of file interfaces.class.php.
References db.
Member Function Documentation
getTriggersList ($forcedirtriggers = null)
Return list of triggers.
Function used by admin page htdoc/admin/triggers. List is sorted by trigger filename so by priority to run.
Parameters
array $forcedirtriggers null=All default directories. This parameter is used by modulebuilder module only.
Returns
array Array list of triggers
Definition at line 244 of file interfaces.class.php.
References dol_buildpath(), dol_osencode(), img_object(), img_picto(), and print.
run_triggers ($action, $object, $user, $langs, $conf)
Function called when a Dolibarr business event occurs This function call all qualified triggers.
Parameters
string $action Trigger event code
object $object Objet concerned. Some context information may also be provided into array property object->context.
User $user Objet user
Translate $langs Objet lang
Conf $conf Objet conf
Returns
int Nb of triggers ran if no error, -Nb of triggers with errors otherwise.
Definition at line 68 of file interfaces.class.php.
References db, dol_buildpath(), dol_osencode(), and dol_syslog().
The documentation for this class was generated from the following file:
htdocs/core/class/interfaces.class.php