Dolibarr: PriceGlobalVariable Class Reference
PriceGlobalVariable Class Reference
Class for accesing price global variables table.
Public Member Functions
__construct ($db)
Constructor.
create ($user, $notrigger=0)
Create object into database.
fetch ($id)
Load object in memory from the database.
update ($user=0, $notrigger=0)
Update object into database.
delete ($rowid, $user, $notrigger=0)
Delete object in database.
initAsSpecimen ()
Initialise object with example values Id must be 0 if object instance is a specimen.
checkParameters ()
Checks if all parameters are in order.
listGlobalVariables ()
List all price global variables.
Detailed Description
Class for accesing price global variables table.
Definition at line 30 of file price_global_variable.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDb $db Database handler
Definition at line 71 of file price_global_variable.class.php.
References db.
Member Function Documentation
checkParameters ()
Checks if all parameters are in order.
Returns
void
Definition at line 312 of file price_global_variable.class.php.
References description.
Referenced by create(), fetch(), and update().
create ($user, $notrigger = 0)
Create object into database.
Parameters
User $user User that creates
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, Id of created object if OK
Definition at line 84 of file price_global_variable.class.php.
References $resql, checkParameters(), db, description, and dol_syslog().
delete ($rowid, $user, $notrigger = 0)
Delete object in database.
Parameters
int $rowid Row id of global variable
User $user User that deletes
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 245 of file price_global_variable.class.php.
References $resql, db, and dol_syslog().
fetch ($id)
Load object in memory from the database.
Parameters
int $id Id object
Returns
int < 0 if KO, 0 if OK but not found, > 0 if OK
Definition at line 146 of file price_global_variable.class.php.
References $resql, checkParameters(), db, description, and dol_syslog().
initAsSpecimen ()
Initialise object with example values Id must be 0 if object instance is a specimen.
Returns
void
Definition at line 299 of file price_global_variable.class.php.
References description.
listGlobalVariables ()
List all price global variables.
Returns
array Array of price global variables
Definition at line 327 of file price_global_variable.class.php.
References $resql, db, and dol_syslog().
update ($user = 0, $notrigger = 0)
Update object into database.
Parameters
User $user User that modifies
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 185 of file price_global_variable.class.php.
References $resql, checkParameters(), db, description, and dol_syslog().
The documentation for this class was generated from the following file:
htdocs/product/dynamic_price/class/price_global_variable.class.php