Dolibarr: modPhpbarcode Class Reference
modPhpbarcode Class Reference
Class to generate barcode images using php barcode generator.
Public Member Functions
isEnabled ()
Return if a module can be used or not.
info ()
Return description.
canBeActivated ()
Test si les numeros deja en vigueur dans la base ne provoquent pas de de conflits qui empechera cette numerotation de fonctionner.
encodingIsSupported ($encoding)
Return true if encoding is supported.
buildBarCode ($code, $encoding, $readable= 'Y', $scale=1, $nooutputiferror=0)
Return an image file on the fly (no need to write on disk)
writeBarCode ($code, $encoding, $readable= 'Y', $scale=1, $nooutputiferror=0)
Save an image file on disk (with no output)
Public Member Functions inherited from ModeleBarCode
isEnabled ()
Return if a model can be used or not.
Detailed Description
Class to generate barcode images using php barcode generator.
Definition at line 33 of file phpbarcode.modules.php.
Member Function Documentation
buildBarCode ($code, $encoding, $readable = 'Y', $scale = 1, $nooutputiferror = 0)
Return an image file on the fly (no need to write on disk)
Parameters
string $code Value to encode
string $encoding Mode of encoding
string $readable Code can be read
integer $scale Scale
integer $nooutputiferror No output if error
Returns
int <0 if KO, >0 if OK
Definition at line 122 of file phpbarcode.modules.php.
References barcode_print(), dol_syslog(), encodingIsSupported(), and print.
Referenced by writeBarCode().
canBeActivated ()
Test si les numeros deja en vigueur dans la base ne provoquent pas de de conflits qui empechera cette numerotation de fonctionner.
Returns
boolean false si conflit, true si ok
Definition at line 79 of file phpbarcode.modules.php.
encodingIsSupported ($encoding)
Return true if encoding is supported.
Parameters
string $encoding Encoding norm
Returns
int >0 if supported, 0 if not
Definition at line 93 of file phpbarcode.modules.php.
Referenced by buildBarCode().
info ()
Return description.
Returns
string Texte descripif
Definition at line 63 of file phpbarcode.modules.php.
isEnabled ()
Return if a module can be used or not.
Returns
boolean true if module can be used
Definition at line 52 of file phpbarcode.modules.php.
writeBarCode ($code, $encoding, $readable = 'Y', $scale = 1, $nooutputiferror = 0)
Save an image file on disk (with no output)
Parameters
string $code Value to encode
string $encoding Mode of encoding
string $readable Code can be read
integer $scale Scale
integer $nooutputiferror No output if error
Returns
int <0 if KO, >0 if OK
Definition at line 163 of file phpbarcode.modules.php.
References buildBarCode(), and dol_mkdir().
The documentation for this class was generated from the following file:
htdocs/core/modules/barcode/doc/phpbarcode.modules.php