Dolibarr: FormTicket Class Reference
FormTicket Class Reference
Public Member Functions
__construct ($db)
Constructor.
showForm ($withdolfichehead=0)
Show the form to input ticket.
selectTypesTickets ($selected= '', $htmlname= 'tickettype', $filtertype= '', $format=0, $empty=0, $noadmininfo=0, $maxlength=0, $morecss= '')
Return html list of tickets type.
selectGroupTickets ($selected= '', $htmlname= 'ticketcategory', $filtertype= '', $format=0, $empty=0, $noadmininfo=0, $maxlength=0, $morecss= '')
Return html list of ticket anaytic codes.
selectSeveritiesTickets ($selected= '', $htmlname= 'ticketseverity', $filtertype= '', $format=0, $empty=0, $noadmininfo=0, $maxlength=0, $morecss= '')
Return html list of ticket severitys.
clear_attached_files ()
Clear list of attached files in send mail form (also stored in session)
showMessageForm ($width= '40%')
Show the form to add message on ticket.
Detailed Description
Definition at line 42 of file html.formticket.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 103 of file html.formticket.class.php.
References db.
Member Function Documentation
clear_attached_files ()
Clear list of attached files in send mail form (also stored in session)
Returns
void
Definition at line 742 of file html.formticket.class.php.
References dol_delete_dir_recursive().
Referenced by showMessageForm().
selectGroupTickets ($selected = '', $htmlname = 'ticketcategory', $filtertype = '', $format = 0, $empty = 0, $noadmininfo = 0, $maxlength = 0, $morecss = '')
Return html list of ticket anaytic codes.
Parameters
string $selected Id categorie pre-selectionnée
string $htmlname Nom de la zone select
string $filtertype To filter on field type in llx_c_ticket_category (array('code'=>xx,'label'=>zz))
int $format 0=id+libelle, 1=code+code, 2=code+libelle, 3=id+code
int $empty 1=peut etre vide, 0 sinon
int $noadmininfo 0=Add admin info, 1=Disable admin info
int $maxlength Max length of label
string $morecss More CSS
Returns
void
Definition at line 548 of file html.formticket.class.php.
References ajax_combobox(), db, dol_syslog(), dol_trunc(), info_admin(), and print.
Referenced by showForm().
selectSeveritiesTickets ($selected = '', $htmlname = 'ticketseverity', $filtertype = '', $format = 0, $empty = 0, $noadmininfo = 0, $maxlength = 0, $morecss = '')
Return html list of ticket severitys.
Parameters
string $selected Id severity pre-selectionnée
string $htmlname Nom de la zone select
string $filtertype To filter on field type in llx_c_ticket_severity (array('code'=>xx,'label'=>zz))
int $format 0=id+libelle, 1=code+code, 2=code+libelle, 3=id+code
int $empty 1=peut etre vide, 0 sinon
int $noadmininfo 0=Add admin info, 1=Disable admin info
int $maxlength Max length of label
string $morecss More CSS
Returns
void
Definition at line 649 of file html.formticket.class.php.
References ajax_combobox(), db, dol_syslog(), dol_trunc(), info_admin(), and print.
Referenced by showForm().
selectTypesTickets ($selected = '', $htmlname = 'tickettype', $filtertype = '', $format = 0, $empty = 0, $noadmininfo = 0, $maxlength = 0, $morecss = '')
Return html list of tickets type.
Parameters
string $selected Id du type pre-selectionne
string $htmlname Nom de la zone select
string $filtertype To filter on field type in llx_c_ticket_type (array('code'=>xx,'label'=>zz))
int $format 0=id+libelle, 1=code+code, 2=code+libelle, 3=id+code
int $empty 1=peut etre vide, 0 sinon
int $noadmininfo 0=Add admin info, 1=Disable admin info
int $maxlength Max length of label
string $morecss More CSS
Returns
void
Definition at line 448 of file html.formticket.class.php.
References ajax_combobox(), db, dol_syslog(), dol_trunc(), info_admin(), and print.
Referenced by showForm().
showForm ($withdolfichehead = 0)
Show the form to input ticket.
Parameters
int $withdolfichehead With dol_fiche_head
Returns
void
Definition at line 129 of file html.formticket.class.php.
References db, dol_buildpath(), dol_fiche_end(), dol_fiche_head(), dol_include_once(), GETPOST(), GETPOSTISSET(), img_mime(), print, selectGroupTickets(), selectSeveritiesTickets(), and selectTypesTickets().
showMessageForm ($width = '40%')
Show the form to add message on ticket.
Parameters
string $width Width of form
Returns
void
Definition at line 765 of file html.formticket.class.php.
References clear_attached_files(), db, dol_escape_htmltag(), dol_mimetype(), dol_nl2br(), dol_textishtml(), GETPOST(), img_mime(), info_admin(), make_substitutions(), print, and setEventMessages().
The documentation for this class was generated from the following file:
htdocs/core/class/html.formticket.class.php