Dolibarr: CommandeFournisseur Class Reference
CommandeFournisseur Class Reference
Class to manage predefined suppliers products.
Public Member Functions
__construct ($db)
Constructor.
fetch ($id, $ref= '')
Get object and lines from database.
fetch_lines ($only_product=0)
Load array lines.
valid ($user, $idwarehouse=0, $notrigger=0)
Validate an order.
getLibStatut ($mode=0)
Return label of the status of object.
LibStatut ($statut, $mode=0, $billed=0)
Return label of a status.
getNomUrl ($withpicto=0, $option= '', $notooltip=0, $save_lastsearch_value=-1)
Return clicable name (with picto eventually)
getNextNumRef ($soc)
Returns the following order reference not used depending on the numbering model activated defined within COMMANDE_SUPPLIER_ADDON_NUMBER.
classifyBilled (User $user)
Class invoiced the supplier order.
approve ($user, $idwarehouse=0, $secondlevel=0)
Approve a supplier order.
refuse ($user)
Refuse an order.
Cancel ($user, $idwarehouse=-1)
Cancel an approved order.
commande ($user, $date, $methode, $comment= '')
Submit a supplier order to supplier.
create ($user, $notrigger=0)
Create order with draft status.
createFromClone (User $user)
Load an object from its id and create a new one in database.
addline ($desc, $pu_ht, $qty, $txtva, $txlocaltax1=0.0, $txlocaltax2=0.0, $fk_product=0, $fk_prod_fourn_price=0, $ref_supplier= '', $remise_percent=0.0, $price_base_type= 'HT', $pu_ttc=0.0, $type=0, $info_bits=0, $notrigger=false, $date_start=null, $date_end=null, $array_options=0, $fk_unit=null, $pu_ht_devise=0, $origin= '', $origin_id=0)
Add order line.
dispatchProduct ($user, $product, $qty, $entrepot, $price=0, $comment= '', $eatby= '', $sellby= '', $batch= '', $fk_commandefourndet=0, $notrigger=0)
Save a receiving into the tracking table of receiving (commande_fournisseur_dispatch) and add product into stock warehouse.
deleteline ($idline, $notrigger=0)
Delete line.
delete (User $user, $notrigger=0)
Delete an order.
get_methodes_commande ()
Get list of order methods.
getDispachedLines ($status=-1)
Return array of dispatched lines waiting to be approved for this order.
Livraison ($user, $date, $type, $comment)
Set a delivery in database for this supplier order.
set_date_livraison ($user, $date_livraison, $notrigger=0)
Set the planned delivery date.
set_id_projet ($user, $id_projet, $notrigger=0)
Set the id projet.
updateFromCommandeClient ($user, $idc, $comclientid)
Update a supplier order from a customer order.
setStatus ($user, $status)
Tag order with a particular status.
updateline ($rowid, $desc, $pu, $qty, $remise_percent, $txtva, $txlocaltax1=0, $txlocaltax2=0, $price_base_type= 'HT', $info_bits=0, $type=0, $notrigger=0, $date_start= '', $date_end= '', $array_options=0, $fk_unit=null, $pu_ht_devise=0, $ref_supplier= '')
Update line.
initAsSpecimen ()
Initialise an instance with random values.
info ($id)
Charge les informations d'ordre info dans l'objet facture.
load_state_board ()
Charge indicateurs this->nb de tableau de bord.
load_board ($user)
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
getInputMethod ()
Returns the translated input method of object (defined if $this->methode_commande_id > 0).
generateDocument ($modele, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0, $moreparams=null)
Create a document onto disk according to template model.
getMaxDeliveryTimeDay ($langs)
Return the max number delivery delay in day.
getRights ()
Returns the rights used for this class.
hasDelay ()
Is the supplier order delayed?
showDelay ()
Show the customer delayed info.
calcAndSetStatusDispatch (User $user, $closeopenorder=1, $comment= '')
Calc status regarding to dispatched stock.
loadReceptions ($filtre_statut=-1)
Load array this->receptions of lines of shipments with nb of products sent for each order line Note: For a dedicated shipment, the fetch_lines can be used to load the qty_asked and qty_shipped.
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0)
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source= 'external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source= 'internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source= '', $code= '')
Delete all links between an object $this and all its contacts.
liste_contact ($statut=-1, $source= 'external', $list=0, $code= '')
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source= 'internal', $order= 'position', $option=0, $activeonly=0, $code= '')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contactid into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table= '', $id=null, $format= '', $id_field= '', $fuser=null, $trigkey= '', $fk_user_field= 'fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source= 'external')
Return list of id of contacts of object.
setProject ($projectid)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id)
Change the payments terms.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder= 'ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix= '')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust= 'none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null)
Add objects linked in llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $clause= 'OR', $alsosametype=1, $orderby= 'sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
updateObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '')
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $rowid= '')
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType= '', $trigkey= '')
Set status of an object.
getCanvas ($id=0, $ref= '')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
display_incoterms ()
Return incoterms informations TODO Use a cache for label get.
getIncotermsForPDF ()
Return incoterms informations for pdf display.
setIncoterms ($id_incoterm, $location)
Define incoterms values of current object.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir= '/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir= '/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafieldsline=0, $defaulttpldir= '/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist= '', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist= '', $defaulttpldir= '/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
addThumbs ($file)
Build thumb Move this into files.lib.php.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($trigger_name, $user)
Call trigger based on this instance.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger= '', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update an extra field value for the current object.
showInputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
showOutputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss= '')
Return HTML string to show a field into a page Code very similar with showOutputField of extra fields.
showOptionals ($extrafields, $mode= 'view', $params=null, $keysuffix= '', $keyprefix= '', $onetrtd=0)
Function to show lines of extrafields with output datas.
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere= '')
Load object in memory from the database.
fetchLinesCommon ($morewhere= '')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
Static Public Member Functions
static replaceThirdparty (DoliDB $db, $origin_id, $dest_id)
Function used to replace a thirdparty id with another one.
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref= '', $ref_ext= '')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static commonReplaceThirdparty (DoliDB $db, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
Data Fields
$date_livraison
Delivery date.
$note
const STATUS_DRAFT = 0
Draft status.
const STATUS_VALIDATED = 1
Validated status.
const STATUS_ACCEPTED = 2
Accepted.
const STATUS_ORDERSENT = 3
Order sent, shipment on process.
const STATUS_RECEIVED_PARTIALLY = 4
Received partially.
const STATUS_RECEIVED_COMPLETELY = 5
Received completely.
const STATUS_CANCELED = 6
Order canceled.
const STATUS_CANCELED_AFTER_ORDER = 7
Order canceled/never received.
const STATUS_REFUSED = 9
Refused.
Data Fields inherited from CommonObject
$projet
$note
Protected Attributes
$table_ref_field = 'ref'
{}
Additional Inherited Members
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
isNull ($info)
Function test if type is null.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare the values to insert.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ()
Function to concat keys of fields.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage predefined suppliers products.
Definition at line 43 of file fournisseur.commande.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 236 of file fournisseur.commande.class.php.
References db.
Member Function Documentation
addline ($desc, $pu_ht, $qty, $txtva, $txlocaltax1 = 0.0, $txlocaltax2 = 0.0, $fk_product = 0, $fk_prod_fourn_price = 0, $ref_supplier = '', $remise_percent = 0.0, $price_base_type = 'HT', $pu_ttc = 0.0, $type = 0, $info_bits = 0, $notrigger = false, $date_start = null, $date_end = null, $array_options = 0, $fk_unit = null, $pu_ht_devise = 0, $origin = '', $origin_id = 0)
Add order line.
Parameters
string $desc Description
float $pu_ht Unit price
float $qty Quantity
float $txtva Taux tva
float $txlocaltax1 Localtax1 tax
float $txlocaltax2 Localtax2 tax
int $fk_product Id product
int $fk_prod_fourn_price Id supplier price
string $ref_supplier Supplier reference price
float $remise_percent Remise
string $price_base_type HT or TTC
float $pu_ttc Unit price TTC
int $type Type of line (0=product, 1=service)
int $info_bits More information
bool $notrigger Disable triggers
int $date_start Date start of service
int $date_end Date end of service
array $array_options extrafields array
string $fk_unit Code of the unit to use. Null to use the default one
string $pu_ht_devise Amount in currency
string $origin 'order', ...
int $origin_id Id of origin object
Returns
int <=0 if KO, >0 if OK
Definition at line 1504 of file fournisseur.commande.class.php.
References calcul_price_total(), db, dol_syslog(), getLocalTaxesFromRate(), CommonObject\line_max(), CommonObject\line_order(), price2num(), and CommonObject\update_price().
Referenced by create().
approve ($user, $idwarehouse = 0, $secondlevel = 0)
Approve a supplier order.
Parameters
User $user Object user
int $idwarehouse Id of warhouse for stock change
int $secondlevel 0=Standard approval, 1=Second level approval (used when option SUPPLIER_ORDER_3_STEPS_TO_BE_APPROVED is set)
Returns
int <0 if KO, >0 if OK
Definition at line 887 of file fournisseur.commande.class.php.
References CommonObject\add_contact(), CommonObject\call_trigger(), db, dol_now(), dol_syslog(), getNextNumRef(), and price2num().
calcAndSetStatusDispatch (User $user, $closeopenorder = 1, $comment = '')
Calc status regarding to dispatched stock.
Parameters
User $user User action
int $closeopenorder Close if received
string $comment Comment
Returns
int <0 if KO, 0 if not applicable, >0 if OK
Definition at line 3037 of file fournisseur.commande.class.php.
References db, dol_now(), and Livraison().
Cancel ($user, $idwarehouse = -1)
Cancel an approved order.
The cancellation is done after approval
Parameters
User $user User making action
int $idwarehouse Id warehouse to use for stock change (not used for supplier orders).
Returns
int >0 if Ok, <0 if Ko
Definition at line 1096 of file fournisseur.commande.class.php.
References CommonObject\call_trigger(), db, and dol_syslog().
classifyBilled (User $user)
Class invoiced the supplier order.
Parameters
User $user Object user making the change
Returns
int <0 if KO, >0 if KO
Definition at line 840 of file fournisseur.commande.class.php.
References CommonObject\call_trigger(), db, and dol_print_error().
commande ($user, $date, $methode, $comment = '')
Submit a supplier order to supplier.
Parameters
User $user User making change
integer $date Date
int $methode Method
string $comment Comment
Returns
int <0 if KO, >0 if OK
Definition at line 1158 of file fournisseur.commande.class.php.
References CommonObject\call_trigger(), db, and dol_syslog().
create ($user, $notrigger = 0)
Create order with draft status.
Parameters
User $user User making creation
int $notrigger Disable all triggers
Returns
int <0 if KO, Id of supplier order if OK
Definition at line 1216 of file fournisseur.commande.class.php.
References CommonObject\add_object_linked(), addline(), CommonObject\call_trigger(), db, dol_now(), dol_print_error(), dol_syslog(), MultiCurrency\getIdAndTxFromCode(), MultiCurrency\getIdFromCode(), and CommonObject\insertExtraFields().
Referenced by createFromClone().
createFromClone (User $user)
Load an object from its id and create a new one in database.
Parameters
User $user User making the clone
Returns
int New id of clone
Definition at line 1420 of file fournisseur.commande.class.php.
References create(), and db.
delete (User $user, $notrigger = 0)
Delete an order.
Parameters
User $user Object user
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 1906 of file fournisseur.commande.class.php.
References $resql, CommonObject\call_trigger(), db, CommonObject\deleteExtraFields(), CommonObject\deleteObjectLinked(), dol_delete_dir_recursive(), dol_delete_file(), dol_sanitizeFileName(), and dol_syslog().
deleteline ($idline, $notrigger = 0)
Delete line.
Parameters
int $idline Id of line to delete
int $notrigger 1=Disable call to triggers
Returns
int <0 if KO, >0 if OK
Definition at line 1870 of file fournisseur.commande.class.php.
References db, and CommonObject\update_price().
dispatchProduct ($user, $product, $qty, $entrepot, $price = 0, $comment = '', $eatby = '', $sellby = '', $batch = '', $fk_commandefourndet = 0, $notrigger = 0)
Save a receiving into the tracking table of receiving (commande_fournisseur_dispatch) and add product into stock warehouse.
Parameters
User $user User object making change
int $product Id of product to dispatch
double $qty Qty to dispatch
int $entrepot Id of warehouse to add product
double $price Unit Price for PMP value calculation (Unit price without Tax and taking into account discount)
string $comment Comment for stock movement
integer $eatby eat-by date
integer $sellby sell-by date
string $batch Lot number
int $fk_commandefourndet Id of supplier order line
int $notrigger 1 = notrigger
Returns
int <0 if KO, >0 if OK
Definition at line 1768 of file fournisseur.commande.class.php.
References $resql, CommonObject\call_trigger(), db, dol_now(), and dol_syslog().
fetch ($id, $ref = '')
Get object and lines from database.
Parameters
int $id Id of order to load
string $ref Ref of object
Returns
int >0 if OK, <0 if KO, 0 if not found
Definition at line 251 of file fournisseur.commande.class.php.
References $resql, db, dol_syslog(), fetch_lines(), CommonObject\fetch_optionals(), and note.
fetch_lines ($only_product = 0)
Load array lines.
Parameters
int $only_product Return only physical products
Returns
int <0 if KO, >0 if OK
Definition at line 385 of file fournisseur.commande.class.php.
References db, and dol_syslog().
Referenced by fetch().
generateDocument ($modele, $outputlangs, $hidedetails = 0, $hidedesc = 0, $hideref = 0, $moreparams = null)
Create a document onto disk according to template model.
Parameters
string $modele Force template to use ('' to not force)
Translate $outputlangs Object lang to use for traduction
int $hidedetails Hide details of lines
int $hidedesc Hide description
int $hideref Hide ref
null | array $moreparams Array to provide more information
Returns
int 0 if KO, 1 if OK
Definition at line 2912 of file fournisseur.commande.class.php.
References CommonObject\commonGenerateDocument(), and dol_strlen().
get_methodes_commande ()
Get list of order methods.
Returns
int 0 if OK, <0 if KO
Definition at line 2026 of file fournisseur.commande.class.php.
References $resql, and db.
getDispachedLines ($status = -1)
Return array of dispatched lines waiting to be approved for this order.
Since
8.0 Return dispatched quantity (qty).
Parameters
int $status Filter on stats (-1 = no filter, 0 = lines draft to be approved, 1 = approved lines)
Returns
array Array of lines
Definition at line 2063 of file fournisseur.commande.class.php.
References $resql, db, and dol_print_error().
Referenced by Livraison().
getInputMethod ()
Returns the translated input method of object (defined if $this->methode_commande_id > 0).
This function make a sql request to get translation. No cache yet, try to not use it inside a loop.
Returns
string
Definition at line 2870 of file fournisseur.commande.class.php.
References $resql, and dol_print_error().
getLibStatut ($mode = 0)
Return label of the status of object.
Parameters
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=short label + picto
Returns
string Label
Definition at line 619 of file fournisseur.commande.class.php.
References LibStatut().
getMaxDeliveryTimeDay ($langs)
Return the max number delivery delay in day.
Parameters
Translate $langs Language object
Returns
string Translated string
Definition at line 2940 of file fournisseur.commande.class.php.
References db.
getNextNumRef ($soc)
Returns the following order reference not used depending on the numbering model activated defined within COMMANDE_SUPPLIER_ADDON_NUMBER.
Parameters
Societe $soc company object
Returns
string free reference for the invoice
Definition at line 787 of file fournisseur.commande.class.php.
References dol_buildpath(), and dol_print_error().
Referenced by approve(), and valid().
getNomUrl ($withpicto = 0, $option = '', $notooltip = 0, $save_lastsearch_value = -1)
Return clicable name (with picto eventually)
Parameters
int $withpicto 0=No picto, 1=Include picto into link, 2=Only picto
string $option On what the link points
int $notooltip 1=Disable tooltip
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
Returns
string Chain with URL
Definition at line 727 of file fournisseur.commande.class.php.
References img_object(), and price().
getRights ()
Returns the rights used for this class.
Returns
stdClass
Definition at line 2968 of file fournisseur.commande.class.php.
hasDelay ()
Is the supplier order delayed?
Returns
bool
Definition at line 2998 of file fournisseur.commande.class.php.
References $date_livraison, and dol_now().
info ($id)
Charge les informations d'ordre info dans l'objet facture.
Parameters
int $id Id de la facture a charger
Returns
void
Definition at line 2727 of file fournisseur.commande.class.php.
References db, and dol_print_error().
initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
void
Definition at line 2643 of file fournisseur.commande.class.php.
References $resql, db, dol_now(), and dol_syslog().
LibStatut ($statut, $mode = 0, $billed = 0)
Return label of a status.
Parameters
int $statut Id statut
int $mode 0=Long label, 1=Short label, 2=Picto + Short label, 3=Picto, 4=Picto + Long label, 5=Short label + Picto
int $billed 1=Billed
Returns
string Label of status
Definition at line 633 of file fournisseur.commande.class.php.
References img_picto().
Referenced by getLibStatut().
Livraison ($user, $date, $type, $comment)
Set a delivery in database for this supplier order.
Parameters
User $user User that input data
integer $date Date of reception
string $type Type of receipt ('tot' = total/done, 'par' = partial, 'nev' = never, 'can' = cancel)
string $comment Comment
Returns
int <0 if KO, >0 if OK
Definition at line 2117 of file fournisseur.commande.class.php.
References $resql, CommonObject\call_trigger(), db, dol_syslog(), and getDispachedLines().
Referenced by calcAndSetStatusDispatch().
load_board ($user)
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
Parameters
User $user Objet user
Returns
WorkboardResponse|int <0 if KO, WorkboardResponse if OK
Definition at line 2811 of file fournisseur.commande.class.php.
References $resql, db, and img_object().
load_state_board ()
Charge indicateurs this->nb de tableau de bord.
Returns
int <0 si ko, >0 si ok
Definition at line 2767 of file fournisseur.commande.class.php.
References $resql, db, and dol_print_error().
loadReceptions ($filtre_statut = -1)
Load array this->receptions of lines of shipments with nb of products sent for each order line Note: For a dedicated shipment, the fetch_lines can be used to load the qty_asked and qty_shipped.
This function is use to return qty_shipped cumulated for the order
Parameters
int $filtre_statut Filter on shipment status
Returns
int <0 if KO, Nb of lines found if OK
Definition at line 3178 of file fournisseur.commande.class.php.
References db, and dol_syslog().
refuse ($user)
Refuse an order.
Parameters
User $user User making action
Returns
int 0 if Ok, <0 if Ko
Definition at line 1039 of file fournisseur.commande.class.php.
References CommonObject\call_trigger(), db, and dol_syslog().
static replaceThirdparty (DoliDB $db, $origin_id, $dest_id) static
Function used to replace a thirdparty id with another one.
Parameters
DoliDB $db Database handler
int $origin_id Old thirdparty id
int $dest_id New thirdparty id
Returns
bool
Definition at line 2984 of file fournisseur.commande.class.php.
References CommonObject\commonReplaceThirdparty().
set_date_livraison ($user, $date_livraison, $notrigger = 0)
Set the planned delivery date.
Parameters
User $user Objet user making change
integer $date_livraison Planned delivery date
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 2233 of file fournisseur.commande.class.php.
References $date_livraison, $resql, CommonObject\call_trigger(), db, and dol_syslog().
set_id_projet ($user, $id_projet, $notrigger = 0)
Set the id projet.
Parameters
User $user Objet utilisateur qui modifie
int $id_projet Date de livraison
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 si ko, >0 si ok
Definition at line 2299 of file fournisseur.commande.class.php.
References $resql, CommonObject\call_trigger(), db, and dol_syslog().
setStatus ($user, $status)
Tag order with a particular status.
Parameters
User $user Object user that change status
int $status New status
Returns
int <0 if KO, >0 if OK
Definition at line 2408 of file fournisseur.commande.class.php.
References $resql, CommonObject\call_trigger(), db, and dol_syslog().
showDelay ()
Show the customer delayed info.
Returns
string Show delayed information
Definition at line 3015 of file fournisseur.commande.class.php.
References $date_livraison, and dol_print_date().
updateFromCommandeClient ($user, $idc, $comclientid)
Update a supplier order from a customer order.
Parameters
User $user User that create
int $idc Id of supplier order to update
int $comclientid Id of customer order to use as template
Returns
int <0 if KO, >0 if OK
Definition at line 2365 of file fournisseur.commande.class.php.
References db, price2num(), and CommonObject\update_price().
updateline ($rowid, $desc, $pu, $qty, $remise_percent, $txtva, $txlocaltax1 = 0, $txlocaltax2 = 0, $price_base_type = 'HT', $info_bits = 0, $type = 0, $notrigger = 0, $date_start = '', $date_end = '', $array_options = 0, $fk_unit = null, $pu_ht_devise = 0, $ref_supplier = '')
Update line.
Parameters
int $rowid Id de la ligne de facture
string $desc Description de la ligne
double $pu Prix unitaire
double $qty Quantity
double $remise_percent Percent discount on line
double $txtva VAT rate
double $txlocaltax1 Localtax1 tax
double $txlocaltax2 Localtax2 tax
double $price_base_type Type of price base
int $info_bits Miscellaneous informations
int $type Type of line (0=product, 1=service)
int $notrigger Disable triggers
integer $date_start Date start of service
integer $date_end Date end of service
array $array_options Extrafields array
string $fk_unit Code of the unit to use. Null to use the default one
double $pu_ht_devise Unit price in currency
string $ref_supplier Supplier ref
Returns
int < 0 if error, > 0 if ok
Definition at line 2482 of file fournisseur.commande.class.php.
References calcul_price_total(), db, dol_syslog(), getLocalTaxesFromRate(), price2num(), and CommonObject\update_price().
valid ($user, $idwarehouse = 0, $notrigger = 0)
Validate an order.
Parameters
User $user Validator User
int $idwarehouse Id of warehouse to use for stock decrease
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 495 of file fournisseur.commande.class.php.
References $resql, CommonObject\call_trigger(), db, dol_dir_list(), dol_now(), dol_print_error(), dol_sanitizeFileName(), dol_syslog(), and getNextNumRef().
Field Documentation
$note
Deprecated:
See also
$note_private, $note_public
Definition at line 128 of file fournisseur.commande.class.php.
The documentation for this class was generated from the following file:
htdocs/fourn/class/fournisseur.commande.class.php