Dolibarr: ModeleBoxes Class Reference
ModeleBoxes Class Reference
Class ModeleBoxes.
Public Member Functions
__construct ($db, $param= '')
Constructor.
error ()
Return last error message.
fetch ($rowid)
Load a box line from its rowid.
outputBox ($head=null, $contents=null)
Standard method to get content of a box.
showBox ($head=null, $contents=null, $nooutput=0)
Standard method to show a box (usage by boxes not mandatory, a box can still use its own showBox function)
Static Public Member Functions
static getWidgetsList ($forcedirwidget=null)
Return list of widget.
Detailed Description
Class ModeleBoxes.
Boxes parent class
Definition at line 34 of file modules_boxes.php.
Constructor & Destructor Documentation
__construct ($db, $param = '')
Constructor.
Parameters
DoliDB $db Database handler
string $param More parameters
Definition at line 118 of file modules_boxes.php.
References db.
Member Function Documentation
error ()
Return last error message.
Returns
string Error message
Definition at line 128 of file modules_boxes.php.
fetch ($rowid)
Load a box line from its rowid.
Parameters
int $rowid Row id to load
Returns
int <0 if KO, >0 if OK
Definition at line 141 of file modules_boxes.php.
References $resql, db, and dol_syslog().
static getWidgetsList ($forcedirwidget = null) static
Return list of widget.
Function used by admin page htdoc/admin/widget. List is sorted by widget filename so by priority to run.
Parameters
array $forcedirwidget null=All default directories. This parameter is used by modulebuilder module only.
Returns
array Array list of widget
Definition at line 388 of file modules_boxes.php.
References dol_buildpath(), dol_osencode(), img_object(), img_picto(), and print.
outputBox ($head = null, $contents = null)
Standard method to get content of a box.
Parameters
array $head Array with properties of box title
array $contents Array with properties of box lines
Returns
string
Definition at line 185 of file modules_boxes.php.
References showBox().
showBox ($head = null, $contents = null, $nooutput = 0)
Standard method to show a box (usage by boxes not mandatory, a box can still use its own showBox function)
Parameters
array $head Array with properties of box title
array $contents Array with properties of box lines
int $nooutput No print, only return string
Returns
string
Definition at line 207 of file modules_boxes.php.
References dol_cache_refresh(), dol_escape_htmltag(), dol_filecache(), dol_readcachefile(), dol_syslog(), dol_trunc(), img_object(), img_picto(), and print.
Referenced by outputBox().
The documentation for this class was generated from the following file:
htdocs/core/boxes/modules_boxes.php