Dolibarr: printing_printgcp Class Reference
printing_printgcp Class Reference
Class to provide printing with Google Cloud Print.
Public Member Functions
__construct ($db)
Constructor.
listAvailablePrinters ()
Return list of available printers.
getlistAvailablePrinters ()
Return list of available printers.
printFile ($file, $module, $subdir= '')
Print selected file.
sendPrintToPrinter ($printerid, $printjobtitle, $filepath, $contenttype)
Sends document to the printer.
listJobs ()
List jobs print.
Public Member Functions inherited from PrintingDriver
__construct ($db)
Constructor.
getDesc ()
Return description of Printing Module.
Additional Inherited Members
Static Public Member Functions inherited from PrintingDriver
static listDrivers ($db, $maxfilenamelength=0)
Return list of printing driver.
Detailed Description
Class to provide printing with Google Cloud Print.
Definition at line 36 of file printgcp.modules.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 73 of file printgcp.modules.php.
References conf(), db, and dol_print_date().
Member Function Documentation
getlistAvailablePrinters ()
Return list of available printers.
Returns
array list of printers
Definition at line 235 of file printgcp.modules.php.
References conf(), db, and print.
Referenced by listAvailablePrinters().
listAvailablePrinters ()
Return list of available printers.
Returns
int 0 if OK, >0 if KO
Definition at line 186 of file printgcp.modules.php.
References getlistAvailablePrinters(), and img_picto().
listJobs ()
List jobs print.
Returns
int 0 if OK, >0 if KO
Definition at line 425 of file printgcp.modules.php.
References conf(), db, and dol_print_date().
printFile ($file, $module, $subdir = '')
Print selected file.
Parameters
string $file file
string $module module
string $subdir subdir for file
Returns
int 0 if OK, >0 if KO
Definition at line 303 of file printgcp.modules.php.
References db, dol_mimetype(), dol_print_error(), and sendPrintToPrinter().
sendPrintToPrinter ($printerid, $printjobtitle, $filepath, $contenttype)
Sends document to the printer.
Parameters
string $printerid Printer id returned by Google Cloud Print
string $printjobtitle Job Title
string $filepath File Path to be send to Google Cloud Print
string $contenttype File content type by example application/pdf, image/png
Returns
array status array
Definition at line 360 of file printgcp.modules.php.
References conf(), and db.
Referenced by printFile().
The documentation for this class was generated from the following file:
htdocs/core/modules/printing/printgcp.modules.php