Dolibarr: SupplierInvoices Class Reference
SupplierInvoices Class Reference
Public Member Functions
__construct ()
Constructor.
get ($id)
Get properties of a supplier invoice object.
post ($request_data=null)
Create supplier invoice object.
put ($id, $request_data=null)
Update supplier invoice.
delete ($id)
Delete supplier invoice.
validate ($id, $idwarehouse=0, $notrigger=0)
Validate an order.
getPayments ($id)
Get list of payments of a given supplier invoice.
addPayment ($id, $datepaye, $paiementid, $closepaidinvoices, $accountid, $num_paiement= '', $comment= '', $chqemetteur= '', $chqbank= '')
Add payment line to a specific supplier invoice with the remain to pay as amount.
Public Member Functions inherited from DolibarrApi
__construct ($db, $cachedir= '', $refreshCache=false)
Constructor.
Protected Member Functions
_cleanObjectDatas ($object)
Clean sensible object datas.
Protected Member Functions inherited from DolibarrApi
_cleanObjectDatas ($object)
Executed method when API is called without parameter.
_checkFilters ($sqlfilters)
Return if a $sqlfilters parameter is valid.
Private Member Functions
_validate ($data)
Validate fields before create or update object.
Additional Inherited Members
Static Protected Member Functions inherited from DolibarrApi
static _checkAccessToResource ($resource, $resource_id=0, $dbtablename= '', $feature2= '', $dbt_keyfield= 'fk_soc', $dbt_select= 'rowid')
Check user access to a resource.
static _forge_criteria_callback ($matches)
Function to forge a SQL criteria.
Detailed Description
Definition at line 31 of file api_supplier_invoices.class.php.
Member Function Documentation
_cleanObjectDatas ($object) protected
Clean sensible object datas.
Parameters
Object $object Object to clean
Returns
array Array of cleaned object properties
Definition at line 489 of file api_supplier_invoices.class.php.
Referenced by get().
_validate ($data) private
Validate fields before create or update object.
Parameters
array $data Datas to validate
Returns
array
Exceptions
RestException
Definition at line 511 of file api_supplier_invoices.class.php.
Referenced by post().
addPayment ($id, $datepaye, $paiementid, $closepaidinvoices, $accountid, $num_paiement = '', $comment = '', $chqemetteur = '', $chqbank = '')
Add payment line to a specific supplier invoice with the remain to pay as amount.
Parameters
int $id Id of invoice
string $datepaye { body} Payment date { timestamp}
int $paiementid { body} Payment mode Id { 1}
string $closepaidinvoices { body} Close paid invoices { yes,no}
int $accountid { body} Account Id { 1}
string $num_paiement { body} Payment number (optional)
string $comment { body} Note (optional)
string $chqemetteur { body} Payment issuer (mandatory if paiementcode = 'CHQ')
string $chqbank { body} Issuer bank name (optional)
POST {id}/payments
Returns
int Payment ID
Exceptions
400
401
404
Definition at line 403 of file api_supplier_invoices.class.php.
References DolibarrApi\_checkAccessToResource(), db, dol_getIdFromCode(), and price2num().
delete ($id)
Delete supplier invoice.
Parameters
int $id Supplier invoice ID
Returns
array
Exceptions
401
404
500
Definition at line 269 of file api_supplier_invoices.class.php.
References DolibarrApi\_checkAccessToResource().
get ($id)
Get properties of a supplier invoice object.
Return an array with supplier invoice information
Parameters
int $id ID of supplier invoice
Returns
array|mixed data without useless information
Exceptions
RestException
Definition at line 66 of file api_supplier_invoices.class.php.
References DolibarrApi\_checkAccessToResource(), DolibarrApi\_checkFilters(), and _cleanObjectDatas().
getPayments ($id)
Get list of payments of a given supplier invoice.
Parameters
int $id Id of SupplierInvoice
GET {id}/payments
Returns
array
Exceptions
400
401
404
405
Definition at line 356 of file api_supplier_invoices.class.php.
References DolibarrApi\_checkAccessToResource().
post ($request_data = null)
Create supplier invoice object.
Parameters
array $request_data Request datas
Returns
int ID of supplier invoice
Exceptions
401
500
Definition at line 200 of file api_supplier_invoices.class.php.
References _validate(), and dol_now().
put ($id, $request_data = null)
Update supplier invoice.
Parameters
int $id Id of supplier invoice to update
array $request_data Datas
Returns
int
Exceptions
401
404
Definition at line 232 of file api_supplier_invoices.class.php.
References DolibarrApi\_checkAccessToResource().
validate ($id, $idwarehouse = 0, $notrigger = 0)
Validate an order.
Parameters
int $id Order ID
int $idwarehouse Warehouse ID
int $notrigger 1=Does not execute triggers, 0= execute triggers
POST {id}/validate
Returns
array
Exceptions
304
401
404
405
500
Definition at line 313 of file api_supplier_invoices.class.php.
References DolibarrApi\_checkAccessToResource().
The documentation for this class was generated from the following file:
htdocs/fourn/class/api_supplier_invoices.class.php