Dolibarr: AssetType Class Reference
AssetType Class Reference
Class to manage asset type.
Public Member Functions
__construct ($db)
Constructor.
create ($user, $notrigger=0)
Fonction qui permet de creer le type d'immobilisation.
update ($user, $notrigger=0)
Met a jour en base donnees du type.
delete ()
Fonction qui permet de supprimer le status de l'adherent.
fetch ($rowid)
Fonction qui permet de recuperer le status de l'immobilisation.
liste_array ()
Return list of asset's type.
listAssetForAssetType ($excludefilter= '', $mode=0)
Return array of Asset objects for asset type this->id (or all if this->id not defined)
getNomUrl ($withpicto=0, $maxlen=0, $notooltip=0)
Return clicable name (with picto eventually)
initAsSpecimen ()
Initialise an instance with random values.
getLibStatut ()
getLibStatut
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0)
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source= 'external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source= 'internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source= '', $code= '')
Delete all links between an object $this and all its contacts.
liste_contact ($statut=-1, $source= 'external', $list=0, $code= '')
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source= 'internal', $order= 'position', $option=0, $activeonly=0, $code= '')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contactid into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table= '', $id=null, $format= '', $id_field= '', $fuser=null, $trigkey= '', $fk_user_field= 'fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source= 'external')
Return list of id of contacts of object.
setProject ($projectid)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id)
Change the payments terms.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder= 'ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix= '')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust= 'none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null)
Add objects linked in llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $clause= 'OR', $alsosametype=1, $orderby= 'sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
updateObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '')
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $rowid= '')
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType= '', $trigkey= '')
Set status of an object.
getCanvas ($id=0, $ref= '')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
display_incoterms ()
Return incoterms informations TODO Use a cache for label get.
getIncotermsForPDF ()
Return incoterms informations for pdf display.
setIncoterms ($id_incoterm, $location)
Define incoterms values of current object.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir= '/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir= '/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafieldsline=0, $defaulttpldir= '/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist= '', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist= '', $defaulttpldir= '/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
addThumbs ($file)
Build thumb Move this into files.lib.php.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($trigger_name, $user)
Call trigger based on this instance.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger= '', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update an extra field value for the current object.
showInputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
showOutputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss= '')
Return HTML string to show a field into a page Code very similar with showOutputField of extra fields.
showOptionals ($extrafields, $mode= 'view', $params=null, $keysuffix= '', $keyprefix= '', $onetrtd=0)
Function to show lines of extrafields with output datas.
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere= '')
Load object in memory from the database.
fetchLinesCommon ($morewhere= '')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
Additional Inherited Members
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref= '', $ref_ext= '')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static commonReplaceThirdparty (DoliDB $db, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
Data Fields inherited from CommonObject
$projet
$note
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
isNull ($info)
Function test if type is null.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare the values to insert.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ()
Function to concat keys of fields.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage asset type.
Definition at line 30 of file asset_type.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 79 of file asset_type.class.php.
References db.
Member Function Documentation
create ($user, $notrigger = 0)
Fonction qui permet de creer le type d'immobilisation.
Parameters
User $user User making creation
int $notrigger 1=do not execute triggers, 0 otherwise
Returns
int >0 if OK, < 0 if KO
Definition at line 92 of file asset_type.class.php.
References CommonObject\call_trigger(), db, dol_syslog(), label, note, and update().
delete ()
Fonction qui permet de supprimer le status de l'adherent.
Returns
int >0 if OK, 0 if not found, < 0 if KO
Definition at line 236 of file asset_type.class.php.
References $resql, CommonObject\call_trigger(), and db.
fetch ($rowid)
Fonction qui permet de recuperer le status de l'immobilisation.
Parameters
int $rowid Id of member type to load
Returns
int <0 if KO, >0 if OK
Definition at line 270 of file asset_type.class.php.
References $resql, db, dol_syslog(), label, and note.
getLibStatut ()
getLibStatut
Returns
string Return status of a type of asset
Definition at line 456 of file asset_type.class.php.
getNomUrl ($withpicto = 0, $maxlen = 0, $notooltip = 0)
Return clicable name (with picto eventually)
Parameters
int $withpicto 0=No picto, 1=Include picto into link, 2=Only picto
int $maxlen length max label
int $notooltip 1=Disable tooltip
Returns
string String with URL
Definition at line 408 of file asset_type.class.php.
References dol_escape_htmltag(), dol_trunc(), img_object(), and label.
initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
void
Definition at line 433 of file asset_type.class.php.
References label, and note.
listAssetForAssetType ($excludefilter = '', $mode = 0)
Return array of Asset objects for asset type this->id (or all if this->id not defined)
Parameters
string $excludefilter Filter to exclude
int $mode 0=Return array of asset instance 1=Return array of asset instance without extra data 2=Return array of asset id only
Returns
mixed Array of asset or -1 on error
Definition at line 353 of file asset_type.class.php.
References $resql, db, and dol_syslog().
liste_array ()
Return list of asset's type.
Returns
array List of types of members
Definition at line 309 of file asset_type.class.php.
References $resql, db, and print.
update ($user, $notrigger = 0)
Met a jour en base donnees du type.
Parameters
User $user Object user making change
int $notrigger 1=do not execute triggers, 0 otherwise
Returns
int >0 if OK, < 0 if KO
Definition at line 169 of file asset_type.class.php.
References CommonObject\call_trigger(), db, dol_syslog(), CommonObject\insertExtraFields(), label, and note.
Referenced by create().
The documentation for this class was generated from the following file:
htdocs/asset/class/asset_type.class.php