Dolibarr: ICal Class Reference
ICal Class Reference
Class to read/parse ICal calendars.
Public Member Functions
__construct ()
Constructor.
read_file ($file)
Read text file, icalender text file.
get_event_count ()
Returns the number of calendar events.
get_todo_count ()
Returns the number of to do.
parse ($uri)
Translate Calendar.
add_to_array ($type, $key, $value)
Add to $this->ical array one value and key.
retun_key_value ($text)
Parse text "XXXX:value text some with : " and return array($key = "XXXX", $value="value");.
ical_rrule ($value)
Parse RRULE return array.
ical_date_to_unix ($ical_date)
Return Unix time from ical date time fomrat (YYYYMMDD[T]HHMMSS[Z] or YYYYMMDD[T]HHMMSS)
ical_dt_date ($key, $value)
Return unix date from iCal date format.
get_sort_event_list ()
Return sorted eventlist as array or false if calendar is empty.
ical_dtstart_compare ($a, $b)
Compare two unix timestamp.
get_event_list ()
Return eventlist array (not sorted eventlist array)
get_freebusy_list ()
Return eventlist array (not sort eventlist array)
get_todo_list ()
Return to do array (not sorted todo array)
get_calender_data ()
Return base calendar data.
get_all_data ()
Return array with all data.
Detailed Description
Class to read/parse ICal calendars.
Definition at line 33 of file ical.class.php.
Member Function Documentation
add_to_array ($type, $key, $value)
Add to $this->ical array one value and key.
Parameters
string $type Type ('VTODO', 'VEVENT', 'VFREEBUSY', 'VCALENDAR'...)
string $key Key ('DTSTART', ...). Note: Field is never 'DTSTART;TZID=...' because ';...' was before removed and added as another property
string $value Value
Returns
void
Definition at line 214 of file ical.class.php.
References ical_date_to_unix(), and ical_dt_date().
Referenced by parse().
get_all_data ()
Return array with all data.
Returns
array
Definition at line 455 of file ical.class.php.
get_calender_data ()
Return base calendar data.
Returns
array
Definition at line 443 of file ical.class.php.
get_event_count ()
Returns the number of calendar events.
Returns
int
Definition at line 79 of file ical.class.php.
get_event_list ()
Return eventlist array (not sorted eventlist array)
Returns
array
Definition at line 407 of file ical.class.php.
Referenced by get_sort_event_list().
get_freebusy_list ()
Return eventlist array (not sort eventlist array)
Returns
array
Definition at line 419 of file ical.class.php.
get_sort_event_list ()
Return sorted eventlist as array or false if calendar is empty.
Returns
array|false
Definition at line 372 of file ical.class.php.
References get_event_list().
get_todo_count ()
Returns the number of to do.
Returns
int
Definition at line 91 of file ical.class.php.
get_todo_list ()
Return to do array (not sorted todo array)
Returns
array
Definition at line 431 of file ical.class.php.
ical_date_to_unix ($ical_date)
Return Unix time from ical date time fomrat (YYYYMMDD[T]HHMMSS[Z] or YYYYMMDD[T]HHMMSS)
Parameters
string $ical_date String date
Returns
int
Definition at line 319 of file ical.class.php.
References dol_mktime().
Referenced by add_to_array(), and ical_dt_date().
ical_dt_date ($key, $value)
Return unix date from iCal date format.
Parameters
string $key Key
string $value Value
Returns
array
Definition at line 343 of file ical.class.php.
References ical_date_to_unix().
Referenced by add_to_array().
ical_dtstart_compare ($a, $b)
Compare two unix timestamp.
Parameters
array $a Operand a
array $b Operand b
Returns
integer
Definition at line 395 of file ical.class.php.
ical_rrule ($value)
Parse RRULE return array.
Parameters
string $value string
Returns
array
Definition at line 299 of file ical.class.php.
parse ($uri)
Translate Calendar.
Parameters
string $uri Url
Returns
array|string
Definition at line 103 of file ical.class.php.
References add_to_array(), quotedPrintDecode(), read_file(), and retun_key_value().
read_file ($file)
Read text file, icalender text file.
Parameters
string $file File
Returns
string
Definition at line 58 of file ical.class.php.
Referenced by parse().
retun_key_value ($text)
Parse text "XXXX:value text some with : " and return array($key = "XXXX", $value="value");.
Parameters
string $text Text
Returns
array
Definition at line 274 of file ical.class.php.
Referenced by parse().
The documentation for this class was generated from the following file:
htdocs/comm/action/class/ical.class.php