Dolibarr: BlockedLogAuthority Class Reference
BlockedLogAuthority Class Reference
Class to manage certif authority.
Public Member Functions
__construct ($db)
Constructor.
getLocalBlockChain ()
Get the blockchain.
getBlockchainHash ()
Get hash of the block chain to check.
checkBlockchain ($hash)
Get hash of the block chain to check.
addBlock ($block)
Add a new block to the chain.
checkBlock ($block)
hash already exist into chain ?
fetch ($id, $signature= '')
Get object from database.
create ($user)
Create authority in database.
update ($user)
Create authority in database.
syncSignatureWithAuthority ()
For cron to sync to authority.
Detailed Description
Class to manage certif authority.
Definition at line 21 of file authority.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 53 of file authority.class.php.
References db.
Member Function Documentation
addBlock ($block)
Add a new block to the chain.
Parameters
string $block new block to chain
Returns
void
Definition at line 110 of file authority.class.php.
checkBlock ($block)
hash already exist into chain ?
Parameters
string $block new block to chain
Returns
boolean
Definition at line 122 of file authority.class.php.
checkBlockchain ($hash)
Get hash of the block chain to check.
Parameters
string $hash hash md5 of blockchain to test
Returns
boolean
Definition at line 98 of file authority.class.php.
References getBlockchainHash().
create ($user)
Create authority in database.
Parameters
User $user Object user that create
Returns
int <0 if KO, >0 if OK
Definition at line 202 of file authority.class.php.
References db, and dol_syslog().
fetch ($id, $signature = '')
Get object from database.
Parameters
int $id Id of object to load
string $signature Signature of object to load
Returns
int >0 if OK, <0 if KO, 0 if not found
Definition at line 145 of file authority.class.php.
References $resql, db, and dol_syslog().
getBlockchainHash ()
Get hash of the block chain to check.
Returns
string hash md5 of blockchain
Definition at line 86 of file authority.class.php.
Referenced by checkBlockchain().
getLocalBlockChain ()
Get the blockchain.
Returns
string blockchain
Definition at line 63 of file authority.class.php.
References db.
syncSignatureWithAuthority ()
For cron to sync to authority.
Returns
int <0 if KO, >0 if OK
Definition at line 293 of file authority.class.php.
References db.
update ($user)
Create authority in database.
Parameters
User $user Object user that create
Returns
int <0 if KO, >0 if OK
Definition at line 256 of file authority.class.php.
References db, and dol_syslog().
The documentation for this class was generated from the following file:
htdocs/blockedlog/class/authority.class.php