Dolibarr: CSMSFile Class Reference
CSMSFile Class Reference
Class to send SMS Usage: $smsfile = new CSMSFile($subject,$sendto,$replyto,$message,$filepath,$mimetype,$filename,$cc,$ccc,$deliveryreceipt,$msgishtml,$errors_to); $smsfile->sendfile();.
Public Member Functions
__construct ($to, $from, $msg, $deliveryreceipt=0, $deferred=0, $priority=3, $class=1)
CSMSFile.
sendfile ()
Send sms that was prepared by constructor.
dump_sms ()
Write content of a SendSms request into a dump file (mode = all) Used for debugging.
dump_sms_result ($result)
Write content of a SendSms result into a dump file (mode = all) Used for debugging.
Detailed Description
Class to send SMS Usage: $smsfile = new CSMSFile($subject,$sendto,$replyto,$message,$filepath,$mimetype,$filename,$cc,$ccc,$deliveryreceipt,$msgishtml,$errors_to); $smsfile->sendfile();.
Definition at line 35 of file CSMSFile.class.php.
Constructor & Destructor Documentation
__construct ($to, $from, $msg, $deliveryreceipt = 0, $deferred = 0, $priority = 3, $class = 1)
CSMSFile.
Parameters
string $to Recipients SMS
string $from Sender SMS
string $msg Message
int $deliveryreceipt Not used
int $deferred Deferred or not
int $priority Priority
int $class Class
Definition at line 62 of file CSMSFile.class.php.
References dol_syslog().
Member Function Documentation
dump_sms ()
Write content of a SendSms request into a dump file (mode = all) Used for debugging.
Returns
void
Definition at line 205 of file CSMSFile.class.php.
Referenced by sendfile().
dump_sms_result ($result)
Write content of a SendSms result into a dump file (mode = all) Used for debugging.
Parameters
int $result Result of sms sending
Returns
void
Definition at line 237 of file CSMSFile.class.php.
Referenced by sendfile().
sendfile ()
Send sms that was prepared by constructor.
Returns
boolean True if sms sent, false otherwise
Definition at line 97 of file CSMSFile.class.php.
References db, dol_include_once(), dol_print_error(), dol_syslog(), dump_sms(), and dump_sms_result().
The documentation for this class was generated from the following file:
htdocs/core/class/CSMSFile.class.php