Dolibarr: htdocs/compta/index.php File Reference
index.php File Reference
Main page of accountancy area.
Variables
print
Draft customers invoices.
if(!empty($conf->facture->enabled)&&$user->rights->facture->lire) if(!empty($conf->fournisseur->enabled)&&$user->rights->fournisseur->facture->lire) if(!empty($conf->don->enabled)&&$user->rights->societe->lire) if(!empty($conf->tax->enabled)&&$user->rights->tax->charges->lire) if(!empty($conf->facture->enabled)&&!empty($conf->commande->enabled)&&$user->rights->commande->lire &&empty($conf->global->WORKFLOW_DISABLE_CREATE_INVOICE_FROM_ORDER)) if(!empty($conf->facture->enabled)&&$user->rights->facture->lire) if(!empty($conf->fournisseur->enabled)&&$user->rights->fournisseur->facture->lire) $resql = 0
Social contributions to pay.
Detailed Description
Main page of accountancy area.
Definition in file index.php.
Variable Documentation
if ($resql) print
Draft customers invoices.
Draft suppliers invoices
Definition at line 93 of file index.php.
Referenced by DolGeoIP\__construct(), FormOther\_pLineSelect(), accessforbidden(), ActionsStripeconnect\addMoreActionsButtons(), ajax_constantonoff(), analyseVarsForSqlAndScriptsInjection(), barcode_encode(), barcode_outimage(), modPhpbarcode\buildBarCode(), check_user_password_ldap(), clean_data_ecm_directories(), cleanCorruptedTree(), complete_dictionary_with_modules(), UserBankAccount\create(), CompanyBankAccount\create(), DolEditor\Create(), BonPrelevement\Create(), create_key_table(), create_script_table(), Categorie\debug_cats(), ExtraFields\delete_label(), FormMargin\displayMarginInfos(), dol_banner_tab(), dol_fiche_end(), dol_fiche_head(), dol_htmloutput_mesg(), dol_print_address(), dol_print_cron_urls(), dol_print_error(), dol_print_error_email(), dol_print_file(), dol_print_object_info(), dol_setshmop(), dol_syslog(), dolWebsiteOutput(), DolGraph\draw_jflot(), envoi_mail(), mod_syslog_file\export(), AccountancyExport\exportAgiris(), AccountancyExport\exportBob50(), AccountancyExport\exportCegid(), AccountancyExport\exportCharlemagne(), AccountancyExport\exportCiel(), AccountancyExport\exportCoala(), AccountancyExport\exportCogilog(), AccountancyExport\exportConfigurable(), AccountancyExport\exportEbp(), AccountancyExport\exportFEC(), AccountancyExport\exportLDCompta(), AccountancyExport\exportOpenConcerto(), AccountancyExport\exportQuadratus(), AccountancyExport\exportSAGE50SWISS(), ExpenseReport\fetch_line_by_project(), fichinter_create(), fieldList(), fieldListAccountingCategories(), fieldListAccountModel(), fieldListJournal(), fieldListWebsites(), FormFile\form_attach_new_file(), Form\form_availability(), FormBarCode\form_barcode_type(), Form\form_conditions_reglement(), Form\form_confirm(), form_constantes(), Form\form_contacts(), Form\form_date(), Form\form_modes_reglement(), Form\form_multicurrency_code(), Form\form_multicurrency_rate(), Form\form_project(), FormCompany\form_prospect_level(), Form\form_remise_dispo(), FormActions\form_select_status_action(), Form\form_thirdparty(), Form\form_users(), Form\formInputReason(), Form\formSelectAccount(), FormContract\formSelectContract(), Form\formSelectShippingMethod(), FormProduct\formSelectWarehouses(), Don\generateDocument(), Societe\generateDocument(), printing_printgcp\getlistAvailablePrinters(), Reception\getNextNumRef(), Holiday\getNextNumRef(), Contrat\getNextNumRef(), Expedition\getNextNumRef(), Commande\getNextNumRef(), RemiseCheque\getNextNumRef(), BOM\getNextNumRef(), PaiementFourn\getNextNumRef(), Fichinter\getNextNumRef(), Paiement\getNextNumRef(), SupplierProposal\getNextNumRef(), Facture\getNextNumRef(), Propal\getNextNumRef(), Dolistore\getRemoteCategories(), Dolistore\getRemoteProducts(), Interfaces\getTriggersList(), ModeleBoxes\getWidgetsList(), Societe\has_projects(), html_print_stripe_footer(), Societe\id_prof_exists(), includeContainer(), Contact\info(), inventorySelectProducts(), journalHead(), DoliDBPgsql\last_insert_id(), left_menu(), Export\list_export_model(), FormFile\list_of_autoecmfiles(), FormFile\list_of_documents(), AssetType\liste_array(), AdherentType\liste_array(), ModeleAction\liste_modeles(), FormFile\listOfLinks(), llxFooter(), llxFooterSurvey(), llxFooterVierge(), llxHeader(), llxHeaderSurvey(), llxHeaderTicket(), llxHeaderVierge(), ActionsCardService\LoadListDatas(), Localtax\localtax_sum_collectee(), Localtax\localtax_sum_payee(), Localtax\localtax_sum_reglee(), main_area(), migrate_actioncomm_element(), migrate_categorie_association(), migrate_clean_association(), migrate_commande_deliveryaddress(), migrate_commande_expedition(), migrate_commande_livraison(), migrate_contracts_date1(), migrate_contracts_date3(), migrate_contracts_det(), migrate_contracts_open(), migrate_customerorder_shipping(), migrate_delete_old_dir(), migrate_delete_old_files(), migrate_detail_livraison(), migrate_event_assignement(), migrate_event_assignement_contact(), migrate_links_transfert(), migrate_menus(), migrate_mode_reglement(), migrate_paiementfourn_facturefourn(), migrate_paiements(), migrate_paiements_orphelins_1(), migrate_paiements_orphelins_2(), migrate_price_commande(), migrate_price_commande_fournisseur(), migrate_price_contrat(), migrate_price_facture(), migrate_price_propal(), migrate_project_task_actors(), migrate_project_task_time(), migrate_project_user_resp(), migrate_relationship_tables(), migrate_reload_menu(), migrate_reload_modules(), migrate_remise_entity(), migrate_remise_except_entity(), migrate_reset_blocked_log(), migrate_restore_missing_links(), migrate_shipping_delivery(), migrate_shipping_delivery2(), migrate_stocks(), migrate_user_photospath(), migrate_user_rights_entity(), migrate_usergroup_rights_entity(), RssParser\parser(), pFooter(), pHeader(), price2numjs(), print_actions_filter(), print_auguria_menu(), print_barre_liste(), print_date_range(), print_end_menu_array(), print_end_menu_array_auguria(), print_end_menu_array_empty(), print_end_menu_entry(), print_end_menu_entry_auguria(), print_end_menu_entry_empty(), print_fiche_titre(), print_fleche_navigation(), print_left_auguria_menu(), print_left_eldy_menu(), print_liste_field_titre(), print_paybox_redirect(), print_projecttasks_array(), print_start_menu_array(), print_start_menu_array_auguria(), print_start_menu_array_empty(), print_start_menu_entry(), print_start_menu_entry_auguria(), print_start_menu_entry_empty(), print_text_menu_entry(), print_text_menu_entry_auguria(), print_text_menu_entry_empty(), print_titre(), printCommonFooter(), printSearchForm(), Ticket\printSelectStatus(), projectLinesa(), projectLinesPerAction(), projectLinesPerDay(), projectLinesPerWeek(), pt(), rebuild_merge_pdf(), redirectToContainer(), report_header(), run_sql(), FormAccounting\select_accounting_category(), Form\select_address(), FormBarCode\select_barcode_type(), FormOther\select_color(), Form\select_company(), Form\select_comptes(), Form\select_conditions_paiements(), Form\select_contacts(), FormContract\select_contract(), Form\select_currency(), Form\select_date(), FormCompany\select_departement(), FormOther\select_dictionary(), FormOther\select_ecotaxes(), select_expensereport_statut(), FormOther\select_export_model(), Form\select_export_model(), FormCompany\select_forme_juridique(), FormOther\select_import_model(), FormCompany\select_localtax(), FormProduct\select_measuring_units(), FormAdmin\select_menu(), FormAdmin\select_menu_families(), Form\select_produits(), Form\select_produits_fournisseurs(), FormProjets\select_projects(), FormProjets\select_projects_list(), FormCompany\select_region(), Form\select_remises(), FormAdmin\select_timezone(), FormActions\select_type_actions(), Form\select_type_fees(), select_type_fees_id(), Form\select_type_of_lines(), FormSocialContrib\select_type_socialcontrib(), Form\select_types_paiements(), FormResource\select_types_resource(), Form\select_users(), FormOther\select_year(), Form\selectAvailabilityDelay(), FormCompany\selectCompaniesForNewContact(), Form\selectEstablishments(), FormTicket\selectGroupTickets(), FormOrder\selectInputMethod(), Form\selectInputReason(), FormOther\selectProjectTasks(), FormPropal\selectProposalStatus(), FormTicket\selectSeveritiesTickets(), Form\selectShippingMethod(), Holiday\selectStatutCP(), FormOrder\selectSupplierOrderStatus(), FormProjets\selectTasks(), FormCompany\selectTypeContact(), FormBank\selectTypeOfBankAccount(), FormWebsite\selectTypeOfContainer(), FormTicket\selectTypesTickets(), dolReceiptPrinter\sendToPrinter(), FormBarCode\setBarcodeEncoder(), show_actions_done(), show_actions_todo(), show_array_actions_to_do(), show_array_last_actions_done(), show_contacts(), FormFile\show_documents(), FormSms\show_form(), FormMail\show_form(), show_ldap_content(), show_ldap_test_button(), show_list_sending_receive(), show_projects(), show_skin(), show_stats_for_company(), show_subsidiaries(), FormActions\showactions(), box_actions\showBox(), ModeleBoxes\showBox(), FormOther\showColor(), FormTicket\showForm(), ExtraFields\showInputField(), Form\showLinkedObjectBlock(), Form\showLinkToObjectBlock(), MenuManager\showmenu(), FormTicket\showMessageForm(), showSkins(), showWebsiteTemplates(), ChargeSociales\solde(), top_htmlhead(), top_menu(), tree_recur(), tree_showpad(), treeOutputForAbsoluteDir(), Tva\tva_sum_collectee(), Tva\tva_sum_payee(), Tva\tva_sum_reglee(), ExtraFields\update_label(), usage(), valeur(), ActionsTicket\viewStatusActions(), ActionsTicket\viewTicketMessages(), ActionsTicket\viewTicketOriginalMessage(), ActionsTicket\viewTicketTimelineMessages(), and doc_generic_task_odt\write_file().