Dolibarr: Database Interface Reference
Database Interface Reference
Class to manage Dolibarr database access for an SQL database.
Public Member Functions
ifsql ($test, $resok, $resko)
Format a SQL IF.
fetch_row ($resultset)
Return datas as an array.
idate ($param)
Convert (by PHP) a GM Timestamp date into a string date with PHP server TZ to insert into a date field.
lasterrno ()
Return last error code.
begin ()
Start transaction.
DDLCreateDb ($database, $charset= '', $collation= '', $owner= '')
Create a new database Do not use function xxx_create_db (xxx=mysql, ...) as they are deprecated We force to create database with charset this->forcecharset and collate this->forcecollate.
getVersionArray ()
Return version of database server into an array.
affected_rows ($resultset)
Return the number of lines in the result of a request INSERT, DELETE or UPDATE.
error ()
Return description of last error.
DDLListTables ($database, $table= '')
List tables into a database.
lastquery ()
Return last request executed with query()
order ($sortfield=null, $sortorder=null)
Define sort criteria of request.
decrypt ($value)
Decrypt sensitive data in database.
fetch_array ($resultset)
Return datas as an array.
lasterror ()
Return last error label.
escape ($stringtoencode)
Escape a string to insert data.
last_insert_id ($tab, $fieldid= 'rowid')
Get last ID after an insert INSERT.
getPathOfRestore ()
Return full path of restore program.
rollback ($log= '')
Annulation d'une transaction et retour aux anciennes valeurs.
query ($query, $usesavepoint=0, $type= 'auto')
Execute a SQL request and return the resultset.
connect ($host, $login, $passwd, $name, $port=0)
Connexion to server.
plimit ($limit=0, $offset=0)
Define limits and offset of request.
getServerParametersValues ($filter= '')
Return value of server parameters.
getServerStatusValues ($filter= '')
Return value of server status.
getDefaultCollationDatabase ()
Return collation used in database.
num_rows ($resultset)
Return number of lines for result of a SELECT.
getPathOfDump ()
Return full path of dump program.
getDriverInfo ()
Return version of database client driver.
errno ()
Return generic error code of last operation.
DDLCreateTable ($table, $fields, $primary_key, $type, $unique_keys=null, $fulltext_keys=null, $keys=null)
Create a table into database.
DDLDropTable ($table)
Drop a table into database.
getListOfCharacterSet ()
Return list of available charset that can be used to store data in database.
DDLAddField ($table, $field_name, $field_desc, $field_position="")
Create a new field into table.
DDLDropField ($table, $field_name)
Drop a field from table.
DDLUpdateField ($table, $field_name, $field_desc)
Update format of a field into a table.
getListOfCollation ()
Return list of available collation that can be used for database.
DDLDescTable ($table, $field="")
Return a pointer of line with description of a table or field.
getVersion ()
Return version of database server.
getDefaultCharacterSetDatabase ()
Return charset used to store data in database.
DDLCreateUser ($dolibarr_main_db_host, $dolibarr_main_db_user, $dolibarr_main_db_pass, $dolibarr_main_db_name)
Create a user and privileges to connect to database (even if database does not exists yet)
jdate ($string, $gm=false)
Convert (by PHP) a PHP server TZ string date into a Timestamps date (GMT if gm=true) 19700101020000 -> 3600 with TZ+1 and gmt=0 19700101020000 -> 7200 whaterver is TZ if gmt=1.
encrypt ($fieldorvalue, $withQuotes=0)
Encrypt sensitive data in database Warning: This function includes the escape, so it must use direct value.
commit ($log= '')
Validate a database transaction.
DDLInfoTable ($table)
List information of columns into a table.
free ($resultset=null)
Free last resultset used.
close ()
Close database connexion.
lastqueryerror ()
Return last query in error.
DDLGetConnectId ()
Return connexion ID.
fetch_object ($resultset)
Renvoie la ligne courante (comme un objet) pour le curseur resultset.
select_db ($database)
Select a database.
Static Public Member Functions
static convertSQLFromMysql ($line, $type= 'ddl')
Convert a SQL request in Mysql syntax to native syntax.
Detailed Description
Class to manage Dolibarr database access for an SQL database.
Definition at line 26 of file Database.interface.php.
Member Function Documentation
affected_rows ($resultset)
Return the number of lines in the result of a request INSERT, DELETE or UPDATE.
Parameters
resource $resultset Curseur de la requete voulue
Returns
int Number of lines
See also
num_rows()
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
begin ()
Start transaction.
Returns
int 1 if transaction successfuly opened or already opened, 0 if error
Implemented in DoliDBMssql, DoliDB, and TraceableDB.
close ()
Close database connexion.
Returns
boolean True if disconnect successfull, false otherwise
See also
connect
Implemented in TraceableDB, DoliDBPgsql, DoliDBSqlite3, DoliDBMysqli, and DoliDBMssql.
commit ($log = '')
Validate a database transaction.
Parameters
string $log Add more log to default log line
Returns
int 1 if validation is OK or transaction level no started, 0 if ERROR
Implemented in TraceableDB, DoliDBMssql, and DoliDB.
connect ($host, $login, $passwd, $name, $port = 0)
Connexion to server.
Parameters
string $host database server host
string $login login
string $passwd password
string $name name of database (not used for mysql, used for pgsql)
int $port Port of database server
Returns
resource Database access handler
See also
close
Implemented in DoliDBPgsql, TraceableDB, DoliDBSqlite3, DoliDBMysqli, and DoliDBMssql.
static convertSQLFromMysql ($line, $type = 'ddl') static
Convert a SQL request in Mysql syntax to native syntax.
Parameters
string $line SQL request line to convert
string $type Type of SQL order ('ddl' for insert, update, select, delete or 'dml' for create, alter...)
Returns
string SQL request line converted
Implemented in DoliDBMysqli, TraceableDB, DoliDBMssql, and DoliDBSqlite3.
DDLAddField ($table, $field_name, $field_desc, $field_position = "")
Create a new field into table.
Parameters
string $table Name of table
string $field_name Name of field to add
string $field_desc Tableau associatif de description du champ a inserer[nom du parametre][valeur du parametre]
string $field_position Optionnel ex.: "after champtruc"
Returns
int <0 if KO, >0 if OK
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
DDLCreateDb ($database, $charset = '', $collation = '', $owner = '')
Create a new database Do not use function xxx_create_db (xxx=mysql, ...) as they are deprecated We force to create database with charset this->forcecharset and collate this->forcecollate.
Parameters
string $database Database name to create
string $charset Charset used to store data
string $collation Charset used to sort data
string $owner Username of database owner
Returns
resource resource defined if OK, null if KO
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
DDLCreateTable ($table, $fields, $primary_key, $type, $unique_keys = null, $fulltext_keys = null, $keys = null)
Create a table into database.
Parameters
string $table Name of table
array $fields Tableau associatif [nom champ][tableau des descriptions]
string $primary_key Nom du champ qui sera la clef primaire
string $type Type de la table
array $unique_keys Tableau associatifs Nom de champs qui seront clef unique => valeur
array $fulltext_keys Tableau des Nom de champs qui seront indexes en fulltext
array $keys Tableau des champs cles noms => valeur
Returns
int <0 if KO, >=0 if OK
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
DDLCreateUser ($dolibarr_main_db_host, $dolibarr_main_db_user, $dolibarr_main_db_pass, $dolibarr_main_db_name)
Create a user and privileges to connect to database (even if database does not exists yet)
Parameters
string $dolibarr_main_db_host Ip serveur
string $dolibarr_main_db_user Nom user a creer
string $dolibarr_main_db_pass Mot de passe user a creer
string $dolibarr_main_db_name Database name where user must be granted
Returns
int <0 if KO, >=0 if OK
Implemented in DoliDBSqlite3, DoliDBPgsql, DoliDBMssql, DoliDBMysqli, and TraceableDB.
DDLDescTable ($table, $field = "")
Return a pointer of line with description of a table or field.
Parameters
string $table Name of table
string $field Optionnel : Name of field if we want description of field
Returns
resource Resource
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
DDLDropField ($table, $field_name)
Drop a field from table.
Parameters
string $table Name of table
string $field_name Name of field to drop
Returns
int <0 if KO, >0 if OK
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
DDLDropTable ($table)
Drop a table into database.
Parameters
string $table Name of table
Returns
int <0 if KO, >=0 if OK
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
DDLGetConnectId ()
Return connexion ID.
Returns
string Id connexion
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, TraceableDB, and DoliDBMysqli.
DDLInfoTable ($table)
List information of columns into a table.
Parameters
string $table Name of table
Returns
array Array with inforation on table
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
DDLListTables ($database, $table = '')
List tables into a database.
Parameters
string $database Name of database
string $table Nmae of table filter ('xxx')
Returns
array List of tables in an array
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
DDLUpdateField ($table, $field_name, $field_desc)
Update format of a field into a table.
Parameters
string $table Name of table
string $field_name Name of field to modify
string $field_desc Array with description of field format
Returns
int <0 if KO, >0 if OK
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
decrypt ($value)
Decrypt sensitive data in database.
Parameters
string $value Value to decrypt
Returns
string Decrypted value if used
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
encrypt ($fieldorvalue, $withQuotes = 0)
Encrypt sensitive data in database Warning: This function includes the escape, so it must use direct value.
Parameters
string $fieldorvalue Field name or value to encrypt
int $withQuotes Return string with quotes
Returns
string XXX(field) or XXX('value') or field or 'value'
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, TraceableDB, and DoliDBMysqli.
errno ()
Return generic error code of last operation.
Returns
string Error code (Exemples: DB_ERROR_TABLE_ALREADY_EXISTS, DB_ERROR_RECORD_ALREADY_EXISTS...)
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, TraceableDB, and DoliDBMysqli.
error ()
Return description of last error.
Returns
string Error text
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
escape ($stringtoencode)
Escape a string to insert data.
Parameters
string $stringtoencode String to escape
Returns
string String escaped
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
fetch_array ($resultset)
Return datas as an array.
Parameters
resource $resultset Resultset of request
Returns
array Array
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
fetch_object ($resultset)
Renvoie la ligne courante (comme un objet) pour le curseur resultset.
Parameters
resource $resultset Curseur de la requete voulue
Returns
Object Object result line or false if KO or end of cursor
Implemented in TraceableDB, DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, and DoliDBMysqli.
Referenced by Societe\replaceThirdparty().
fetch_row ($resultset)
Return datas as an array.
Parameters
resource $resultset Resultset of request
Returns
array Array
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
free ($resultset = null)
Free last resultset used.
Parameters
resource $resultset Fre cursor
Returns
void
Implemented in DoliDBPgsql, TraceableDB, DoliDBSqlite3, DoliDBMssql, and DoliDBMysqli.
getDefaultCharacterSetDatabase ()
Return charset used to store data in database.
Returns
string Charset
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
getDefaultCollationDatabase ()
Return collation used in database.
Returns
string Collation value
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
getDriverInfo ()
Return version of database client driver.
Returns
string Version string
Implemented in DoliDBPgsql, TraceableDB, DoliDBSqlite3, DoliDBMysqli, and DoliDBMssql.
getListOfCharacterSet ()
Return list of available charset that can be used to store data in database.
Returns
array List of Charset
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
getListOfCollation ()
Return list of available collation that can be used for database.
Returns
array List of Collation
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
getPathOfDump ()
Return full path of dump program.
Returns
string Full path of dump program
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
getPathOfRestore ()
Return full path of restore program.
Returns
string Full path of restore program
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
getServerParametersValues ($filter = '')
Return value of server parameters.
Parameters
string $filter Filter list on a particular value
Returns
array Array of key-values (key=>value)
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
getServerStatusValues ($filter = '')
Return value of server status.
Parameters
string $filter Filter list on a particular value
Returns
array Array of key-values (key=>value)
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
getVersion ()
Return version of database server.
Returns
string Version string
Implemented in TraceableDB, DoliDBPgsql, DoliDBSqlite3, DoliDBMysqli, and DoliDBMssql.
Referenced by DoliDB\getVersionArray().
getVersionArray ()
Return version of database server into an array.
Returns
array Version array
Implemented in DoliDB, and TraceableDB.
idate ($param)
Convert (by PHP) a GM Timestamp date into a string date with PHP server TZ to insert into a date field.
Function to use to build INSERT, UPDATE or WHERE predica
Parameters
int $param Date TMS to convert
Returns
string Date in a string YYYYMMDDHHMMSS
Implemented in DoliDBPgsql, DoliDBMssql, DoliDB, and TraceableDB.
ifsql ($test, $resok, $resko)
Format a SQL IF.
Parameters
string $test Test string (example: 'cd.statut=0', 'field IS NULL')
string $resok resultat si test egal
string $resko resultat si test non egal
Returns
string SQL string
Implemented in DoliDBPgsql, DoliDB, and TraceableDB.
jdate ($string, $gm = false)
Convert (by PHP) a PHP server TZ string date into a Timestamps date (GMT if gm=true) 19700101020000 -> 3600 with TZ+1 and gmt=0 19700101020000 -> 7200 whaterver is TZ if gmt=1.
Parameters
string $string Date in a string (YYYYMMDDHHMMSS, YYYYMMDD, YYYY-MM-DD HH:MM:SS)
bool $gm 1=Input informations are GMT values, otherwise local to server TZ
Returns
int|string Date TMS or ''
Implemented in TraceableDB, and DoliDB.
last_insert_id ($tab, $fieldid = 'rowid')
Get last ID after an insert INSERT.
Parameters
string $tab Table name concerned by insert. Ne sert pas sous MySql mais requis pour compatibilite avec Postgresql
string $fieldid Field name
Returns
int Id of row
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, DoliDBMysqli, and TraceableDB.
lasterrno ()
Return last error code.
Returns
string lasterrno
Implemented in DoliDB, and TraceableDB.
lasterror ()
Return last error label.
Returns
string lasterror
Implemented in DoliDB, and TraceableDB.
lastquery ()
Return last request executed with query()
Returns
string Last query
Implemented in DoliDB, and TraceableDB.
lastqueryerror ()
Return last query in error.
Returns
string lastqueryerror
Implemented in TraceableDB, and DoliDB.
num_rows ($resultset)
Return number of lines for result of a SELECT.
Parameters
resource $resultset Resulset of requests
Returns
int Nb of lines
See also
affected_rows
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, TraceableDB, and DoliDBMysqli.
order ($sortfield = null, $sortorder = null)
Define sort criteria of request.
Parameters
string $sortfield List of sort fields
string $sortorder Sort order
Returns
string String to provide syntax of a sort sql string
Implemented in DoliDB, and TraceableDB.
plimit ($limit = 0, $offset = 0)
Define limits and offset of request.
Parameters
int $limit Maximum number of lines returned (-1=conf->liste_limit, 0=no limit)
int $offset Numero of line from where starting fetch
Returns
string String with SQL syntax to add a limit and offset
Implemented in DoliDBPgsql, TraceableDB, and DoliDB.
query ($query, $usesavepoint = 0, $type = 'auto')
Execute a SQL request and return the resultset.
Parameters
string $query SQL query string
int $usesavepoint 0=Default mode, 1=Run a savepoint before and a rollback to savepoint if error (this allow to have some request with errors inside global transactions). Note that with Mysql, this parameter is not used as Myssql can already commit a transaction even if one request is in error, without using savepoints.
string $type Type of SQL order ('ddl' for insert, update, select, delete or 'dml' for create, alter...)
Returns
resource Resultset of answer
Implemented in DoliDBPgsql, DoliDBSqlite3, DoliDBMssql, TraceableDB, and DoliDBMysqli.
Referenced by DoliDB\begin(), DoliDB\commit(), Societe\replaceThirdparty(), and DoliDB\rollback().
rollback ($log = '')
Annulation d'une transaction et retour aux anciennes valeurs.
Parameters
string $log Add more log to default log line
Returns
int 1 si annulation ok ou transaction non ouverte, 0 en cas d'erreur
Implemented in DoliDBMssql, TraceableDB, and DoliDB.
select_db ($database)
Select a database.
Parameters
string $database Name of database
Returns
boolean true if OK, false if KO
Implemented in TraceableDB, DoliDBPgsql, DoliDBSqlite3, DoliDBMysqli, and DoliDBMssql.
The documentation for this interface was generated from the following file:
htdocs/core/db/Database.interface.php