Dolibarr: Tickets Class Reference
Tickets Class Reference
Public Member Functions
__construct ()
Constructor.
get ($id)
Get properties of a Ticket object.
getByTrackId ($track_id)
Get properties of a Ticket object from track id.
getByRef ($ref)
Get properties of a Ticket object from ref.
index ($socid=0, $sortfield="t.rowid", $sortorder="ASC", $limit=100, $page=0, $sqlfilters= '')
List tickets.
post ($request_data=null)
Create ticket object.
postNewMessage ($request_data=null)
Create ticket object.
put ($id, $request_data=null)
Update ticket.
delete ($id)
Delete ticket.
Public Member Functions inherited from DolibarrApi
__construct ($db, $cachedir= '', $refreshCache=false)
Constructor.
Protected Member Functions
_cleanObjectDatas ($object)
Clean sensible object datas.
Protected Member Functions inherited from DolibarrApi
_cleanObjectDatas ($object)
Executed method when API is called without parameter.
_checkFilters ($sqlfilters)
Return if a $sqlfilters parameter is valid.
Private Member Functions
getCommon ($id=0, $track_id= '', $ref= '')
Get properties of a Ticket object Return an array with ticket informations.
_validate ($data)
Validate fields before create or update object.
_validateMessage ($data)
Validate fields before create or update object message.
Additional Inherited Members
Static Protected Member Functions inherited from DolibarrApi
static _checkAccessToResource ($resource, $resource_id=0, $dbtablename= '', $feature2= '', $dbt_keyfield= 'fk_soc', $dbt_select= 'rowid')
Check user access to a resource.
static _forge_criteria_callback ($matches)
Function to forge a SQL criteria.
Detailed Description
Definition at line 30 of file api_tickets.class.php.
Member Function Documentation
_cleanObjectDatas ($object) protected
Clean sensible object datas.
Parameters
object $object Object to clean
Returns
array Array of cleaned object properties
Definition at line 496 of file api_tickets.class.php.
Referenced by getCommon(), and index().
_validate ($data) private
Validate fields before create or update object.
Parameters
array $data Data to validate
Returns
array
Exceptions
RestException
Definition at line 454 of file api_tickets.class.php.
Referenced by post().
_validateMessage ($data) private
Validate fields before create or update object message.
Parameters
array $data Data to validate
Returns
array
Exceptions
RestException
Definition at line 474 of file api_tickets.class.php.
Referenced by postNewMessage().
delete ($id)
Delete ticket.
Parameters
int $id Ticket ID
Returns
array
Definition at line 420 of file api_tickets.class.php.
References DolibarrApi\_checkAccessToResource().
get ($id)
Get properties of a Ticket object.
Return an array with ticket informations
Parameters
int $id ID of ticket
Returns
array|mixed Data without useless information
Exceptions
401
403
404
Definition at line 75 of file api_tickets.class.php.
References getCommon().
getByRef ($ref)
Get properties of a Ticket object from ref.
Return an array with ticket informations
Parameters
string $ref Reference for ticket
Returns
array|mixed Data without useless information
GET ref/{ref}
Exceptions
401
403
404
Definition at line 113 of file api_tickets.class.php.
References getCommon().
getByTrackId ($track_id)
Get properties of a Ticket object from track id.
Return an array with ticket informations
Parameters
string $track_id Tracking ID of ticket
Returns
array|mixed Data without useless information
GET track_id/{track_id}
Exceptions
401
403
404
Definition at line 94 of file api_tickets.class.php.
References getCommon().
getCommon ($id = 0, $track_id = '', $ref = '') private
Get properties of a Ticket object Return an array with ticket informations.
Parameters
int $id ID of ticket
string $track_id Tracking ID of ticket
string $ref Reference for ticket
Returns
array|mixed Data without useless information
Definition at line 133 of file api_tickets.class.php.
References DolibarrApi\_checkAccessToResource(), _cleanObjectDatas(), db, and dolGetFirstLastname().
Referenced by get(), getByRef(), and getByTrackId().
index ($socid = 0, $sortfield = "t.rowid", $sortorder = "ASC", $limit = 100, $page = 0, $sqlfilters = '')
List tickets.
Get a list of tickets
Parameters
int $socid Filter list with thirdparty ID
string $sortfield Sort field
string $sortorder Sort order
int $limit Limit for list
int $page Page number
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.ref:like:'SO-%') and (t.date_creation:<:'20160101') and (t.fk_statut:=:1)"
Returns
array Array of ticket objects
Definition at line 231 of file api_tickets.class.php.
References DolibarrApi\_checkFilters(), _cleanObjectDatas(), and db.
post ($request_data = null)
Create ticket object.
Parameters
array $request_data Request datas
Returns
int ID of ticket
Definition at line 322 of file api_tickets.class.php.
References _validate(), db, and generate_random_id().
postNewMessage ($request_data = null)
Create ticket object.
Parameters
array $request_data Request datas
Returns
int ID of ticket
Definition at line 355 of file api_tickets.class.php.
References _validateMessage(), and db.
put ($id, $request_data = null)
Update ticket.
Parameters
int $id Id of ticket to update
array $request_data Datas
Returns
int
Definition at line 387 of file api_tickets.class.php.
References DolibarrApi\_checkAccessToResource().
The documentation for this class was generated from the following file:
htdocs/ticket/class/api_tickets.class.php