Dolibarr: Cchargesociales Class Reference
Cchargesociales Class Reference
Class Cchargesociales.
Public Member Functions
__construct (DoliDB $db)
Constructor.
create (User $user, $notrigger=false)
Create object into database.
fetch ($id, $ref=null)
Load object in memory from the database.
update (User $user, $notrigger=false)
Update object into database.
delete (User $user, $notrigger=false)
Delete object in database.
createFromClone (User $user, $fromid)
Load an object from its id and create a new one in database.
getNomUrl ($withpicto=0, $option= '', $notooltip=0, $maxlen=24, $morecss= '')
Return a link to the user card (with optionaly the picto) Use this->id,this->lastname, this->firstname.
getLibStatut ($mode=0)
Retourne le libelle du status d'un user (actif, inactif)
LibStatut ($status, $mode=0)
Renvoi le libelle d'un status donne.
initAsSpecimen ()
Initialise object with example values Id must be 0 if object instance is a specimen.
Private Member Functions
trimParameters ($parameters)
Trim object parameters.
Detailed Description
Class Cchargesociales.
Definition at line 35 of file cchargesociales.class.php.
Constructor & Destructor Documentation
__construct (DoliDB $db)
Constructor.
Parameters
DoliDb $db Database handler
Definition at line 66 of file cchargesociales.class.php.
References db.
Member Function Documentation
create (User $user, $notrigger = false)
Create object into database.
Parameters
User $user User that creates
bool $notrigger false=launch triggers after, true=disable triggers
Returns
int <0 if KO, Id of created object if OK
Definition at line 79 of file cchargesociales.class.php.
References $resql, db, dol_syslog(), and trimParameters().
createFromClone (User $user, $fromid)
Load an object from its id and create a new one in database.
Parameters
User $user User making the clone
int $fromid Id of object to clone
Returns
int New id of clone
Definition at line 353 of file cchargesociales.class.php.
References db, and dol_syslog().
delete (User $user, $notrigger = false)
Delete object in database.
Parameters
User $user User that deletes
bool $notrigger false=launch triggers after, true=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 302 of file cchargesociales.class.php.
References $resql, db, and dol_syslog().
fetch ($id, $ref = null)
Load object in memory from the database.
Parameters
int $id Id object
string $ref Ref
Returns
int <0 if KO, 0 if not found, >0 if OK
Definition at line 169 of file cchargesociales.class.php.
References $resql, db, and dol_syslog().
getLibStatut ($mode = 0)
Retourne le libelle du status d'un user (actif, inactif)
Parameters
int $mode 0=libelle long, 1=libelle court, 2=Picto + Libelle court, 3=Picto, 4=Picto + Libelle long, 5=Libelle court + Picto
Returns
string Label of status
Definition at line 440 of file cchargesociales.class.php.
References LibStatut().
getNomUrl ($withpicto = 0, $option = '', $notooltip = 0, $maxlen = 24, $morecss = '')
Return a link to the user card (with optionaly the picto) Use this->id,this->lastname, this->firstname.
Parameters
int $withpicto Include picto in link (0=No picto, 1=Include picto into link, 2=Only picto)
string $option On what the link point to
integer $notooltip 1=Disable tooltip
int $maxlen Max length of visible user name
string $morecss Add more css on link
Returns
string String with URL
Definition at line 406 of file cchargesociales.class.php.
initAsSpecimen ()
Initialise object with example values Id must be 0 if object instance is a specimen.
Returns
void
Definition at line 497 of file cchargesociales.class.php.
LibStatut ($status, $mode = 0)
Renvoi le libelle d'un status donne.
Parameters
int $status Id status
int $mode 0=libelle long, 1=libelle court, 2=Picto + Libelle court, 3=Picto, 4=Picto + Libelle long, 5=Libelle court + Picto
Returns
string Label of status
Definition at line 453 of file cchargesociales.class.php.
References img_picto().
Referenced by getLibStatut().
trimParameters ($parameters) private
Trim object parameters.
Parameters
string[] $parameters array of parameters to trim
Returns
void
Definition at line 516 of file cchargesociales.class.php.
Referenced by create(), and update().
update (User $user, $notrigger = false)
Update object into database.
Parameters
User $user User that modifies
bool $notrigger false=launch triggers after, true=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 228 of file cchargesociales.class.php.
References $resql, db, dol_syslog(), and trimParameters().
The documentation for this class was generated from the following file:
htdocs/compta/sociales/class/cchargesociales.class.php