Dolibarr: Notify Class Reference
Notify Class Reference
Class to manage notifications.
Public Member Functions
__construct ($db)
Constructor.
confirmMessage ($action, $socid, $object)
Return message that say how many notification (and to which email) will occurs on requested event.
getNotificationsArray ($notifcode, $socid=0, $object=null, $userid=0, $scope=array('thirdparty', 'user', 'global'))
Return number of notifications activated for action code (and third party)
send ($notifcode, $object, $filename_list=array(), $mimetype_list=array(), $mimefilename_list=array())
Check if notification are active for couple action/company.
Detailed Description
Class to manage notifications.
Definition at line 32 of file notify.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 93 of file notify.class.php.
References db.
Member Function Documentation
confirmMessage ($action, $socid, $object)
Return message that say how many notification (and to which email) will occurs on requested event.
This is to show confirmation messages before event is recorded.
Parameters
string $action Id of action in llx_c_action_trigger
int $socid Id of third party
Object $object Object the notification is about
Returns
string Message
Definition at line 108 of file notify.class.php.
References getNotificationsArray(), and img_object().
getNotificationsArray ($notifcode, $socid = 0, $object = null, $userid = 0, $scope = array('thirdparty', 'user', 'global'))
Return number of notifications activated for action code (and third party)
Parameters
string $notifcode Code of action in llx_c_action_trigger (new usage) or Id of action in llx_c_action_trigger (old usage)
int $socid Id of third party or 0 for all thirdparties or -1 for no thirdparties
Object $object Object the notification is about (need it to check threshold value of some notifications)
int $userid Id of user or 0 for all users or -1 for no users
array $scope Scope where to search
Returns
array|int <0 if KO, array of notifications to send if OK
Definition at line 149 of file notify.class.php.
References $resql, db, dol_syslog(), and isValidEmail().
Referenced by confirmMessage().
send ($notifcode, $object, $filename_list = array(), $mimetype_list = array(), $mimefilename_list = array())
Check if notification are active for couple action/company.
If yes, send mail and save trace into llx_notify.
Parameters
string $notifcode Code of action in llx_c_action_trigger (new usage) or Id of action in llx_c_action_trigger (old usage)
Object $object Object the notification deals on
array $filename_list List of files to attach (full path of filename on file system)
array $mimetype_list List of MIME type of attached files
array $mimefilename_list List of attached file name in message
Returns
int <0 if KO, or number of changes if OK
Definition at line 312 of file notify.class.php.
References db, dol_getIdFromCode(), dol_is_file(), dol_now(), dol_print_error(), dol_sanitizeFileName(), dol_strlen(), dol_syslog(), and dolGetFirstLastname().
The documentation for this class was generated from the following file:
htdocs/core/class/notify.class.php