Dolibarr: Products Class Reference
Products Class Reference
Public Member Functions
__construct ()
Constructor.
get ($id, $ref= '', $ref_ext= '', $barcode= '', $includestockdata=0)
Get properties of a product object (from its ID, Ref, Ref_ext or Barcode)
index ($sortfield="t.ref", $sortorder= 'ASC', $limit=100, $page=0, $mode=0, $category=0, $sqlfilters= '')
List products.
post ($request_data=null)
Create product object.
put ($id, $request_data=null)
Update product.
delete ($id)
Delete product.
getCategories ($id, $sortfield="s.rowid", $sortorder= 'ASC', $limit=0, $page=0)
Get categories for a product.
getCustomerPricesPerSegment ($id)
Get prices per segment for a product.
getCustomerPricesPerCustomer ($id)
Get prices per customer for a product.
getCustomerPricesPerQuantity ($id)
Get prices per quantity for a product.
Public Member Functions inherited from DolibarrApi
__construct ($db, $cachedir= '', $refreshCache=false)
Constructor.
Protected Member Functions
_cleanObjectDatas ($object)
Clean sensible object datas.
Protected Member Functions inherited from DolibarrApi
_cleanObjectDatas ($object)
Executed method when API is called without parameter.
_checkFilters ($sqlfilters)
Return if a $sqlfilters parameter is valid.
Private Member Functions
_validate ($data)
Validate fields before create or update object.
Additional Inherited Members
Static Protected Member Functions inherited from DolibarrApi
static _checkAccessToResource ($resource, $resource_id=0, $dbtablename= '', $feature2= '', $dbt_keyfield= 'fk_soc', $dbt_select= 'rowid')
Check user access to a resource.
static _forge_criteria_callback ($matches)
Function to forge a SQL criteria.
Detailed Description
Definition at line 29 of file api_products.class.php.
Member Function Documentation
_cleanObjectDatas ($object) protected
Clean sensible object datas.
Parameters
object $object Object to clean
Returns
array Array of cleaned object properties
Definition at line 478 of file api_products.class.php.
Referenced by get(), and index().
_validate ($data) private
Validate fields before create or update object.
Parameters
array $data Datas to validate
Returns
array
Exceptions
RestException
Definition at line 506 of file api_products.class.php.
Referenced by post().
delete ($id)
Delete product.
Parameters
int $id Product ID
Returns
array
Definition at line 303 of file api_products.class.php.
References DolibarrApi\_checkAccessToResource().
get ($id, $ref = '', $ref_ext = '', $barcode = '', $includestockdata = 0)
Get properties of a product object (from its ID, Ref, Ref_ext or Barcode)
Return an array with product information. TODO implement getting a product by ref or by $ref_ext
Parameters
int $id ID of product
string $ref Ref of element
string $ref_ext Ref ext of element
string $barcode Barcode of element
int $includestockdata Load also information about stock (slower)
Returns
array|mixed Data without useless information
Exceptions
401
403
404
Definition at line 71 of file api_products.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
getCategories ($id, $sortfield = "s.rowid", $sortorder = 'ASC', $limit = 0, $page = 0)
Get categories for a product.
Parameters
int $id ID of product
string $sortfield Sort field
string $sortorder Sort order
int $limit Limit for list
int $page Page number
Returns
mixed
GET {id}/categories
Definition at line 338 of file api_products.class.php.
References db.
getCustomerPricesPerCustomer ($id)
Get prices per customer for a product.
Parameters
int $id ID of product
Returns
mixed
GET {id}/selling_multiprices/per_customer
Definition at line 409 of file api_products.class.php.
getCustomerPricesPerQuantity ($id)
Get prices per quantity for a product.
Parameters
int $id ID of product
Returns
mixed
GET {id}/selling_multiprices/per_quantity
Definition at line 443 of file api_products.class.php.
getCustomerPricesPerSegment ($id)
Get prices per segment for a product.
Parameters
int $id ID of product
Returns
mixed
GET {id}/selling_multiprices/per_segment
Definition at line 368 of file api_products.class.php.
index ($sortfield = "t.ref", $sortorder = 'ASC', $limit = 100, $page = 0, $mode = 0, $category = 0, $sqlfilters = '')
List products.
Get a list of products
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Limit for list
int $page Page number
int $mode Use this param to filter list (0 for all, 1 for only product, 2 for only service)
int $category Use this param to filter list by category
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.tobuy:=:0) and (t.tosell:=:1)"
Returns
array Array of product objects
Definition at line 113 of file api_products.class.php.
References DolibarrApi\_checkFilters(), and _cleanObjectDatas().
post ($request_data = null)
Create product object.
Parameters
array $request_data Request data
Returns
int ID of product
Definition at line 188 of file api_products.class.php.
References _validate().
put ($id, $request_data = null)
Update product.
Price will be updated by this API only if option is set on "One price per product". See other APIs for other price modes.
Parameters
int $id Id of product to update
array $request_data Datas
Returns
int
Exceptions
RestException
401
404
Definition at line 218 of file api_products.class.php.
References DolibarrApi\_checkAccessToResource(), and dol_clone().
The documentation for this class was generated from the following file:
htdocs/product/class/api_products.class.php