Dolibarr: htdocs/compta/tva/index.php File Reference
index.php File Reference
Module Loans
Index page of VAT reports.
Functions
pt ($db, $sql, $date)
print function
Detailed Description
Index page of VAT reports.
Definition in file index.php.
Function Documentation
pt ($db, $sql, $date)
print function
Parameters
DoliDB $db Database handler
string $sql SQL Request
string $date Date
Returns
void
Definition at line 91 of file index.php.
References dol_getdate(), dol_mktime(), dol_now(), dol_print_date(), dol_print_error(), llxFooter(), llxHeader(), load_fiche_titre(), price(), price2num(), print, pt(), report_header(), and tax_by_rate().