Dolibarr: htdocs/webservices/server_project.php File Reference
server_project.php File Reference
File that is entry point to call Dolibarr WebServices.
Functions
createProject ($authentication, $project)
Create project.
getProject ($authentication, $id= '', $ref= '')
Get a project.
Detailed Description
File that is entry point to call Dolibarr WebServices.
Definition in file server_project.php.
Function Documentation
createProject ($authentication, $project)
Create project.
Parameters
array $authentication Array of authentication information
array $project Project info
Returns
int Id of new order
Definition at line 232 of file server_project.php.
References check_authentication(), dol_stringtotime(), and dol_syslog().
getProject ($authentication, $id = '', $ref = '')
Get a project.
Parameters
array $authentication Array of authentication information
string $id internal id
string $ref internal reference
Returns
array Array result
Definition at line 332 of file server_project.php.
References check_authentication(), dol_print_date(), and dol_syslog().