Dolibarr: TaskStats Class Reference
TaskStats Class Reference
Class to manage statistics on project tasks.
Public Member Functions
__construct ($db)
Constructor of the class.
getAllTaskByStatus ($limit=5)
Return all tasks grouped by status.
getAllByYear ()
Return count, and sum of products.
buildWhere ()
Build the where part.
getNbByMonth ($year, $format=0)
Return Task number by month for a year.
Public Member Functions inherited from Stats
getNbByMonthWithPrevYear ($endyear, $startyear, $cachedelay=0, $format=0, $startmonth=1)
Return nb of elements by month for several years.
getAmountByMonthWithPrevYear ($endyear, $startyear, $cachedelay=0, $format=0, $startmonth=1)
Return amount of elements by month for several years.
getAverageByMonthWithPrevYear ($endyear, $startyear)
Return average of entity by month for several years.
getAllByProductEntry ($year, $cachedelay=0)
Return count, and sum of products.
Additional Inherited Members
Protected Member Functions inherited from Stats
_getNbByYear ($sql)
Return nb of elements by year.
_getAllByYear ($sql)
Return nb of elements, total amount and avg amount each year.
_getNbByMonth ($year, $sql, $format=0)
Renvoie le nombre de documents par mois pour une annee donnee Return number of documents per month for a given year.
_getAmountByMonth ($year, $sql, $format=0)
Renvoie le montant totalise par mois pour une annee donnee Return the amount per month for a given year.
_getAverageByMonth ($year, $sql, $format=0)
Renvoie le montant moyen par mois pour une annee donnee Return the amount average par month for a given year.
_getAllByProduct ($sql, $limit=10)
Return number or total of product refs.
Detailed Description
Class to manage statistics on project tasks.
Definition at line 25 of file taskstats.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor of the class.
Parameters
DoliDb $db Database handler
Definition at line 37 of file taskstats.class.php.
References db.
Member Function Documentation
buildWhere ()
Build the where part.
Returns
string
Definition at line 135 of file taskstats.class.php.
References db, dol_get_first_day(), dol_get_last_day(), and getEntity().
Referenced by getAllByYear(), getAllTaskByStatus(), and getNbByMonth().
getAllByYear ()
Return count, and sum of products.
Returns
array of values
Definition at line 110 of file taskstats.class.php.
References Stats\_getAllByYear(), buildWhere(), and db.
getAllTaskByStatus ($limit = 5)
Return all tasks grouped by status.
Parameters
int $limit Limit results
Returns
array|int Array with value or -1 if error
Exceptions
Exception
Definition at line 53 of file taskstats.class.php.
References $resql, buildWhere(), db, and dol_syslog().
getNbByMonth ($year, $format = 0)
Return Task number by month for a year.
Parameters
int $year Year to scan
int $format 0=Label of absiss is a translated text, 1=Label of absiss is month number, 2=Label of absiss is first letter of month
Returns
array Array of values
Definition at line 169 of file taskstats.class.php.
References Stats\_getNbByMonth(), buildWhere(), and db.
The documentation for this class was generated from the following file:
htdocs/projet/class/taskstats.class.php