Dolibarr: htdocs/admin/emailcollector_list.php File Reference
emailcollector_list.php File Reference
List page for emailcollector.
Variables
foreach($object->fields as $key=> $val) if(is_array($extrafields->attributes[$object->table_element]['label'])&&count($extrafields->attributes[$object->table_element]['label']) > 0) $object fields = dol_sort_array($object->fields, 'position')
Detailed Description
List page for emailcollector.
Definition in file emailcollector_list.php.
Variable Documentation
array Array to store compute formula for computed fields = dol_sort_array($object->fields, 'position')
Deprecated:
Deprecated:
Definition at line 117 of file emailcollector_list.php.
Referenced by ActionCommReminder\__construct(), EmailCollectorFilter\__construct(), EmailCollectorAction\__construct(), EmailSenderProfile\__construct(), BOM\__construct(), Asset\__construct(), SocieteAccount\__construct(), EmailCollector\__construct(), Inventory\__construct(), MyObject\__construct(), CompanyPaymentMode\__construct(), BOMLine\__construct(), CoreObject\checkFieldType(), CommonObject\createCommon(), CommonObject\fetchCommon(), CommonObject\getFieldList(), SimpleOpenID\GetRedirectURL(), CoreObject\init(), CommonObject\initAsSpecimenCommon(), SimpleOpenID\SetOptionalFields(), SimpleOpenID\SetRequiredFields(), CommonObject\setSaveQuery(), CommonObject\setVarsFromFetchObj(), and CommonObject\updateCommon().