Dolibarr: Stats Class Reference
Stats Class Reference
Parent class of statistics class.
Public Member Functions
getNbByMonthWithPrevYear ($endyear, $startyear, $cachedelay=0, $format=0, $startmonth=1)
Return nb of elements by month for several years.
getAmountByMonthWithPrevYear ($endyear, $startyear, $cachedelay=0, $format=0, $startmonth=1)
Return amount of elements by month for several years.
getAverageByMonthWithPrevYear ($endyear, $startyear)
Return average of entity by month for several years.
getAllByProductEntry ($year, $cachedelay=0)
Return count, and sum of products.
Protected Member Functions
_getNbByYear ($sql)
Return nb of elements by year.
_getAllByYear ($sql)
Return nb of elements, total amount and avg amount each year.
_getNbByMonth ($year, $sql, $format=0)
Renvoie le nombre de documents par mois pour une annee donnee Return number of documents per month for a given year.
_getAmountByMonth ($year, $sql, $format=0)
Renvoie le montant totalise par mois pour une annee donnee Return the amount per month for a given year.
_getAverageByMonth ($year, $sql, $format=0)
Renvoie le montant moyen par mois pour une annee donnee Return the amount average par month for a given year.
_getAllByProduct ($sql, $limit=10)
Return number or total of product refs.
Detailed Description
Parent class of statistics class.
Definition at line 30 of file stats.class.php.
Member Function Documentation
_getAllByProduct ($sql, $limit = 10) protected
Return number or total of product refs.
Parameters
string $sql SQL
int $limit Limit
Returns
array
Definition at line 601 of file stats.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
Referenced by FichinterStats\getAllByProduct(), CommandeStats\getAllByProduct(), FactureStats\getAllByProduct(), and PropaleStats\getAllByProduct().
_getAllByYear ($sql) protected
Return nb of elements, total amount and avg amount each year.
Parameters
string $sql SQL request
Returns
array Array with nb, total amount, average for each year
Definition at line 382 of file stats.class.php.
References $resql, db, dol_print_error(), dol_syslog(), and if.
Referenced by TaskStats\getAllByYear(), ProjectStats\getAllByYear(), DonationStats\getAllByYear(), ReceptionStats\getAllByYear(), ExpeditionStats\getAllByYear(), TicketStats\getAllByYear(), SalariesStats\getAllByYear(), DeplacementStats\getAllByYear(), ExpenseReportStats\getAllByYear(), AdherentStats\getAllByYear(), FichinterStats\getAllByYear(), CommandeStats\getAllByYear(), FactureStats\getAllByYear(), and PropaleStats\getAllByYear().
_getAmountByMonth ($year, $sql, $format = 0) protected
Renvoie le montant totalise par mois pour une annee donnee Return the amount per month for a given year.
Parameters
int $year Year
string $sql SQL
int $format 0=Label of absiss is a translated text, 1=Label of absiss is month number, 2=Label of absiss is first letter of month
Returns
array
Definition at line 489 of file stats.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
Referenced by TicketStats\getAmountByMonth(), SalariesStats\getAmountByMonth(), DeplacementStats\getAmountByMonth(), AdherentStats\getAmountByMonth(), ExpenseReportStats\getAmountByMonth(), FichinterStats\getAmountByMonth(), CommandeStats\getAmountByMonth(), FactureStats\getAmountByMonth(), PropaleStats\getAmountByMonth(), ProjectStats\getAmountByMonth(), and ProjectStats\getWeightedAmountByMonth().
_getAverageByMonth ($year, $sql, $format = 0) protected
Renvoie le montant moyen par mois pour une annee donnee Return the amount average par month for a given year.
Parameters
int $year Year
string $sql SQL
int $format 0=Label of absiss is a translated text, 1=Label of absiss is month number, 2=Label of absiss is first letter of month
Returns
array
Definition at line 546 of file stats.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
Referenced by TicketStats\getAverageByMonth(), SalariesStats\getAverageByMonth(), DeplacementStats\getAverageByMonth(), AdherentStats\getAverageByMonth(), ExpenseReportStats\getAverageByMonth(), FichinterStats\getAverageByMonth(), CommandeStats\getAverageByMonth(), FactureStats\getAverageByMonth(), and PropaleStats\getAverageByMonth().
_getNbByMonth ($year, $sql, $format = 0) protected
Renvoie le nombre de documents par mois pour une annee donnee Return number of documents per month for a given year.
Parameters
int $year Year
string $sql SQL
int $format 0=Label of absiss is a translated text, 1=Label of absiss is month number, 2=Label of absiss is first letter of month
Returns
array Array of nb each month
Definition at line 429 of file stats.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
Referenced by DonationStats\getNbByMonth(), ReceptionStats\getNbByMonth(), AdherentStats\getNbByMonth(), ExpeditionStats\getNbByMonth(), FichinterStats\getNbByMonth(), SalariesStats\getNbByMonth(), TicketStats\getNbByMonth(), DeplacementStats\getNbByMonth(), FactureStats\getNbByMonth(), CommandeStats\getNbByMonth(), PropaleStats\getNbByMonth(), ExpenseReportStats\getNbByMonth(), TaskStats\getNbByMonth(), ProjectStats\getNbByMonth(), and ProjectStats\getTransformRateByMonth().
_getNbByYear ($sql) protected
Return nb of elements by year.
Parameters
string $sql SQL request
Returns
array
Definition at line 350 of file stats.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
Referenced by SalariesStats\getNbByYear(), DeplacementStats\getNbByYear(), TicketStats\getNbByYear(), ExpenseReportStats\getNbByYear(), DonationStats\getNbByYear(), AdherentStats\getNbByYear(), ReceptionStats\getNbByYear(), ExpeditionStats\getNbByYear(), FichinterStats\getNbByYear(), FactureStats\getNbByYear(), CommandeStats\getNbByYear(), and PropaleStats\getNbByYear().
getAllByProductEntry ($year, $cachedelay = 0)
Return count, and sum of products.
Parameters
int $year Year
int $cachedelay Delay we accept for cache file (0=No read, no save of cache, -1=No read but save)
Returns
array Array of values
Definition at line 274 of file stats.class.php.
References dol_filemtime(), dol_is_dir(), dol_mkdir(), dol_now(), and dol_syslog().
getAmountByMonthWithPrevYear ($endyear, $startyear, $cachedelay = 0, $format = 0, $startmonth = 1)
Return amount of elements by month for several years.
Criterias used to build request are defined into the constructor of parent class into xxx/class/xxxstats.class.php The caller of class can add more filters into sql request by adding criteris into the $stats->where property just after calling constructor.
Parameters
int $endyear Start year
int $startyear End year
int $cachedelay Delay we accept for cache file (0=No read, no save of cache, -1=No read but save)
int $format 0=Label of absiss is a translated text, 1=Label of absiss is month number, 2=Label of absiss is first letter of month
int $startmonth month of the fiscal year start min 1 max 12 ; if 1 = january
Returns
array Array of values
Definition at line 144 of file stats.class.php.
References dol_filemtime(), dol_is_dir(), dol_mkdir(), dol_now(), and dol_syslog().
getAverageByMonthWithPrevYear ($endyear, $startyear)
Return average of entity by month for several years.
Parameters
int $endyear Start year
int $startyear End year
Returns
array Array of values
Definition at line 238 of file stats.class.php.
getNbByMonthWithPrevYear ($endyear, $startyear, $cachedelay = 0, $format = 0, $startmonth = 1)
Return nb of elements by month for several years.
Parameters
int $endyear Start year
int $startyear End year
int $cachedelay Delay we accept for cache file (0=No read, no save of cache, -1=No read but save)
int $format 0=Label of absiss is a translated text, 1=Label of absiss is month number, 2=Label of absiss is first letter of month
int $startmonth month of the fiscal year start min 1 max 12 ; if 1 = january
Returns
array Array of values
Definition at line 47 of file stats.class.php.
References dol_filemtime(), dol_is_dir(), dol_mkdir(), dol_now(), and dol_syslog().
The documentation for this class was generated from the following file:
htdocs/core/class/stats.class.php