Dolibarr: ExportCsv Class Reference
ExportCsv Class Reference
Class to build export files with format CSV.
Public Member Functions
__construct ($db)
Constructor.
getDriverId ()
getDriverId
getDriverLabel ()
getDriverLabel
getDriverDesc ()
getDriverDesc
getDriverExtension ()
getDriverExtension
getDriverVersion ()
getDriverVersion
getLibLabel ()
getLabelLabel
getLibVersion ()
getLibVersion
open_file ($file, $outputlangs)
Open output file.
write_header ($outputlangs)
Output header into file.
write_title ($array_export_fields_label, $array_selected_sorted, $outputlangs, $array_types)
Output title line into file.
write_record ($array_selected_sorted, $objp, $outputlangs, $array_types)
Output record line into file.
write_footer ($outputlangs)
Output footer into file.
close_file ()
Close file handle.
csvClean ($newvalue, $charset)
Clean a cell to respect rules of CSV file cells Note: It uses $this->separator Note: We keep this function public to be able to test.
Public Member Functions inherited from ModeleExports
liste_modeles ($db, $maxfilenamelength=0)
Load into memory list of available export format.
getPictoForKey ($key)
Return picto of export driver.
getDriverLabelForKey ($key)
Renvoi libelle d'un driver export.
getDriverDescForKey ($key)
Renvoi le descriptif d'un driver export.
getDriverVersionForKey ($key)
Renvoi version d'un driver export.
getLibLabelForKey ($key)
Renvoi libelle de librairie externe du driver.
getLibVersionForKey ($key)
Renvoi version de librairie externe du driver.
Public Member Functions inherited from CommonDocGenerator
__construct ($db)
Constructor.
get_substitutionarray_user ($user, $outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_mysoc ($mysoc, $outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_thirdparty ($object, $outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_contact ($object, $outputlangs, $array_key= 'object')
Define array with couple subtitution key => subtitution value.
get_substitutionarray_other ($outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_object ($object, $outputlangs, $array_key= 'object')
Define array with couple substitution key => substitution value.
get_substitutionarray_lines ($line, $outputlangs)
Define array with couple substitution key => substitution value.
get_substitutionarray_shipment ($object, $outputlangs, $array_key= 'object')
Define array with couple substitution key => substitution value.
get_substitutionarray_shipment_lines ($line, $outputlangs)
Define array with couple substitution key => substitution value.
get_substitutionarray_each_var_object (&$object, $outputlangs, $recursive=true)
Define array with couple subtitution key => subtitution value.
fill_substitutionarray_with_extrafields ($object, $array_to_fill, $extrafields, $array_key, $outputlangs)
Fill array with couple extrafield key => extrafield value.
printRect ($pdf, $x, $y, $l, $h, $hidetop=0, $hidebottom=0)
Rect pdf.
columnSort ($a, $b)
uasort callback function to Sort colums fields
prepareArrayColumnField ($object, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0)
Prepare Array Column Field.
getColumnContentWidth ($colKey)
get column content width from column key
getColumnContentXStart ($colKey)
get column content X (abscissa) left position from column key
getColumnRank ($colKey)
get column position rank from column key
insertNewColumnDef ($newColKey, $defArray, $targetCol=false, $insertAfterTarget=false)
get column position rank from column key
printStdColumnContent ($pdf, &$curY, $colKey, $columnText= '')
print standard column content
getColumnStatus ($colKey)
get column status from column key
pdfTabTitles (&$pdf, $tab_top, $tab_height, $outputlangs, $hidetop=0)
Print standard column content.
Detailed Description
Class to build export files with format CSV.
Definition at line 33 of file export_csv.modules.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 67 of file export_csv.modules.php.
References db, and label.
Member Function Documentation
close_file ()
Close file handle.
Returns
int <0 if KO, >0 if OK
Definition at line 315 of file export_csv.modules.php.
csvClean ($newvalue, $charset)
Clean a cell to respect rules of CSV file cells Note: It uses $this->separator Note: We keep this function public to be able to test.
Parameters
string $newvalue String to clean
string $charset Input AND Output character set
Returns
string Value cleaned
Definition at line 332 of file export_csv.modules.php.
References dol_htmlcleanlastbr().
Referenced by write_record(), and write_title().
getDriverDesc ()
getDriverDesc
Returns
string
Definition at line 114 of file export_csv.modules.php.
getDriverExtension ()
getDriverExtension
Returns
string
Definition at line 124 of file export_csv.modules.php.
getDriverId ()
getDriverId
Returns
string
Definition at line 94 of file export_csv.modules.php.
getDriverLabel ()
getDriverLabel
Returns
string Return driver label
Definition at line 104 of file export_csv.modules.php.
getDriverVersion ()
getDriverVersion
Returns
string
Definition at line 134 of file export_csv.modules.php.
getLibLabel ()
getLabelLabel
Returns
string
Definition at line 144 of file export_csv.modules.php.
getLibVersion ()
getLibVersion
Returns
string
Definition at line 154 of file export_csv.modules.php.
open_file ($file, $outputlangs)
Open output file.
Parameters
string $file Path of filename to generate
Translate $outputlangs Output language object
Returns
int <0 if KO, >=0 if OK
Definition at line 168 of file export_csv.modules.php.
References dol_syslog().
write_footer ($outputlangs)
Output footer into file.
Parameters
Translate $outputlangs Output language object
Returns
int <0 if KO, >0 if OK
Definition at line 303 of file export_csv.modules.php.
write_header ($outputlangs)
Output header into file.
Parameters
Translate $outputlangs Output language object
Returns
int <0 if KO, >0 if OK
Definition at line 196 of file export_csv.modules.php.
write_record ($array_selected_sorted, $objp, $outputlangs, $array_types)
Output record line into file.
Parameters
array $array_selected_sorted Array with list of field to export
resource $objp A record from a fetch with all fields from select
Translate $outputlangs Object lang to translate values
array $array_types Array with types of fields
Returns
int <0 if KO, >0 if OK
Definition at line 249 of file export_csv.modules.php.
References csvClean(), and dol_print_error().
write_title ($array_export_fields_label, $array_selected_sorted, $outputlangs, $array_types)
Output title line into file.
Parameters
array $array_export_fields_label Array with list of label of fields
array $array_selected_sorted Array with list of field to export
Translate $outputlangs Object lang to translate values
array $array_types Array with types of fields
Returns
int <0 if KO, >0 if OK
Definition at line 213 of file export_csv.modules.php.
References csvClean().
The documentation for this class was generated from the following file:
htdocs/core/modules/export/export_csv.modules.php