Dolibarr: Contacts Class Reference
Contacts Class Reference
Public Member Functions
__construct ()
Constructor.
get ($id, $includecount=0)
Get properties of a contact object.
post ($request_data=null)
Create contact object.
put ($id, $request_data=null)
Update contact.
delete ($id)
Delete contact.
createUser ($id, $request_data=null)
Create an user account object from contact (external user)
getCategories ($id, $sortfield="s.rowid", $sortorder= 'ASC', $limit=0, $page=0)
Get categories for a contact.
addCategory ($id, $category_id)
Add a category to a contact.
deleteCategory ($id, $category_id)
Remove the link between a category and a contact.
Public Member Functions inherited from DolibarrApi
__construct ($db, $cachedir= '', $refreshCache=false)
Constructor.
Protected Member Functions
_cleanObjectDatas ($object)
Clean sensible object datas.
Protected Member Functions inherited from DolibarrApi
_cleanObjectDatas ($object)
Executed method when API is called without parameter.
_checkFilters ($sqlfilters)
Return if a $sqlfilters parameter is valid.
Private Member Functions
_validate ($data)
Validate fields before create or update object.
Additional Inherited Members
Static Protected Member Functions inherited from DolibarrApi
static _checkAccessToResource ($resource, $resource_id=0, $dbtablename= '', $feature2= '', $dbt_keyfield= 'fk_soc', $dbt_select= 'rowid')
Check user access to a resource.
static _forge_criteria_callback ($matches)
Function to forge a SQL criteria.
Detailed Description
Definition at line 31 of file api_contacts.class.php.
Member Function Documentation
_cleanObjectDatas ($object) protected
Clean sensible object datas.
Parameters
Object $object Object to clean
Returns
array Array of cleaned object properties
Definition at line 473 of file api_contacts.class.php.
Referenced by addCategory(), deleteCategory(), and get().
_validate ($data) private
Validate fields before create or update object.
Parameters
array | null $data Data to validate
Returns
array
Exceptions
RestException
Definition at line 498 of file api_contacts.class.php.
Referenced by post().
addCategory ($id, $category_id)
Add a category to a contact.
POST {id}/categories/{category_id}
Parameters
int $id Id of contact
int $category_id Id of category
Returns
mixed
Exceptions
401 RestException Insufficient rights
401 RestException Access not allowed for login
404 RestException Category not found
404 RestException Contact not found
Definition at line 396 of file api_contacts.class.php.
References DolibarrApi\_checkAccessToResource(), _cleanObjectDatas(), and db.
createUser ($id, $request_data = null)
Create an user account object from contact (external user)
Parameters
int $id Id of contact
array $request_data Request datas
Returns
int ID of user
POST {id}/createUser
Definition at line 305 of file api_contacts.class.php.
References DolibarrApi\_checkAccessToResource(), and db.
delete ($id)
Delete contact.
Parameters
int $id Contact ID
Returns
integer
Definition at line 276 of file api_contacts.class.php.
References DolibarrApi\_checkAccessToResource().
deleteCategory ($id, $category_id)
Remove the link between a category and a contact.
DELETE {id}/categories/{category_id}
Parameters
int $id Id of contact
int $category_id Id of category
Returns
mixed
Exceptions
401 RestException Insufficient rights
401 RestException Access not allowed for login
404 RestException Category not found
404 RestException Contact not found
Definition at line 438 of file api_contacts.class.php.
References DolibarrApi\_checkAccessToResource(), _cleanObjectDatas(), and db.
get ($id, $includecount = 0)
Get properties of a contact object.
Return an array with contact informations
Parameters
int $id ID of contact
int $includecount Count and return also number of elements the contact is used as a link for
Returns
array|mixed data without useless information
Exceptions
RestException
Definition at line 71 of file api_contacts.class.php.
References DolibarrApi\_checkAccessToResource(), DolibarrApi\_checkFilters(), _cleanObjectDatas(), and getEntity().
getCategories ($id, $sortfield = "s.rowid", $sortorder = 'ASC', $limit = 0, $page = 0)
Get categories for a contact.
Parameters
int $id ID of contact
string $sortfield Sort field
string $sortorder Sort order
int $limit Limit for list
int $page Page number
Returns
mixed
GET {id}/categories
Definition at line 360 of file api_contacts.class.php.
References db.
post ($request_data = null)
Create contact object.
Parameters
array $request_data Request datas
Returns
int ID of contact
Definition at line 214 of file api_contacts.class.php.
References _validate().
put ($id, $request_data = null)
Update contact.
Parameters
int $id Id of contact to update
array $request_data Datas
Returns
int
Definition at line 240 of file api_contacts.class.php.
References DolibarrApi\_checkAccessToResource().
The documentation for this class was generated from the following file:
htdocs/societe/class/api_contacts.class.php