Dolibarr: mod_project_simple Class Reference
mod_project_simple Class Reference
Class to manage the numbering module Simple for project references.
Public Member Functions
info ()
Return description of numbering module.
getExample ()
Return an example of numbering module values.
canBeActivated ()
Test si les numeros deja en vigueur dans la base ne provoquent pas de de conflits qui empechera cette numerotation de fonctionner.
getNextValue ($objsoc, $project)
Return next value.
project_get_num ($objsoc=0, $project= '')
Return next reference not yet used as a reference.
Public Member Functions inherited from ModeleNumRefProjects
isEnabled ()
Return if a module can be used or not.
info ()
Renvoi la description par defaut du modele de numerotation.
getExample ()
Renvoi un exemple de numerotation.
canBeActivated ()
Test si les numeros deja en vigueur dans la base ne provoquent pas de de conflits qui empechera cette numerotation de fonctionner.
getNextValue ($objsoc, $project)
Renvoi prochaine valeur attribuee.
getVersion ()
Renvoi version du module numerotation.
Detailed Description
Class to manage the numbering module Simple for project references.
Definition at line 32 of file mod_project_simple.php.
Member Function Documentation
canBeActivated ()
Test si les numeros deja en vigueur dans la base ne provoquent pas de de conflits qui empechera cette numerotation de fonctionner.
Returns
boolean false si conflit, true si ok
Definition at line 88 of file mod_project_simple.php.
References $resql.
getExample ()
Return an example of numbering module values.
Returns
string Example
Definition at line 77 of file mod_project_simple.php.
getNextValue ($objsoc, $project)
Return next value.
Parameters
Societe $objsoc Object third party
Project $project Object project
Returns
string Value if OK, 0 if KO
Definition at line 125 of file mod_project_simple.php.
References $resql, dol_now(), and dol_syslog().
Referenced by project_get_num().
info ()
Return description of numbering module.
Returns
string Text with description
Definition at line 65 of file mod_project_simple.php.
project_get_num ($objsoc = 0, $project = '')
Return next reference not yet used as a reference.
Parameters
Societe $objsoc Object third party
Project $project Object project
Returns
string Next not used reference
Definition at line 170 of file mod_project_simple.php.
References getNextValue().
The documentation for this class was generated from the following file:
htdocs/core/modules/project/mod_project_simple.php