Dolibarr: Export Class Reference
Export Class Reference
Class to manage exports.
Public Member Functions
__construct ($db)
Constructor.
load_arrays ($user, $filter= '')
Load an exportable dataset.
build_sql ($indice, $array_selected, $array_filterValue)
Build the sql export request.
build_filterQuery ($TypeField, $NameField, $ValueField)
Build the conditionnal string from filter the query.
conditionDate ($Field, $Value, $Sens)
conditionDate
build_filterField ($TypeField, $NameField, $ValueField)
Build an input field used to filter the query.
genDocFilter ($TypeField)
Build an input field used to filter the query.
build_file ($user, $model, $datatoexport, $array_selected, $array_filterValue, $sqlquery= '')
Build export file.
create ($user)
Save an export model in database.
fetch ($id)
Load an export profil from database.
delete ($user, $notrigger=0)
Delete object in database.
list_export_model ()
Output list all export models TODO Move this into a class htmlxxx.class.php.
Detailed Description
Class to manage exports.
Definition at line 31 of file export.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 67 of file export.class.php.
References db.
Member Function Documentation
build_file ($user, $model, $datatoexport, $array_selected, $array_filterValue, $sqlquery = '')
Build export file.
File is built into directory $conf->export->dir_temp.'/'.$user->id Arrays this->array_export_xxx are already loaded for required datatoexport
Parameters
User $user User that export
string $model Export format
string $datatoexport Name of dataset to export
array $array_selected Filter on array of fields to export
array $array_filterValue Filter on array of fields with a filter
string $sqlquery If set, transmit the sql request for select (otherwise, sql request is generated from arrays)
Returns
int <0 if KO, >0 if OK
Definition at line 540 of file export.class.php.
References $resql, build_sql(), db, dol_eval(), dol_mkdir(), and dol_syslog().
build_filterField ($TypeField, $NameField, $ValueField)
Build an input field used to filter the query.
Parameters
string $TypeField Type of Field to filter. Example: Text, Date, List:c_country:label:rowid, List:c_stcom:label:code, Numeric or Number, Boolean
string $NameField Name of the field to filter
string $ValueField Initial value of the field to filter
Returns
string html string of the input field ex : "<input type=text name=... value=...>"
Definition at line 380 of file export.class.php.
References $resql, db, dol_print_error(), and dol_trunc().
build_filterQuery ($TypeField, $NameField, $ValueField)
Build the conditionnal string from filter the query.
Parameters
string $TypeField Type of Field to filter
string $NameField Name of the field to filter
string $ValueField Value of the field for filter. Must not be ''
Returns
string sql string of then field ex : "field='xxx'>"
Definition at line 285 of file export.class.php.
References conditionDate(), dol_syslog(), and if.
build_sql ($indice, $array_selected, $array_filterValue)
Build the sql export request.
Arrays this->array_export_xxx are already loaded for required datatoexport
Parameters
int $indice Indice of export
array $array_selected Filter fields on array of fields to export
array $array_filterValue Filter records on array of value for fields
Returns
string SQL String. Example "select s.rowid as r_rowid, s.status as s_status from ..."
Definition at line 222 of file export.class.php.
Referenced by build_file().
conditionDate ($Field, $Value, $Sens)
conditionDate
Parameters
string $Field Field operand 1
string $Value Value operand 2
string $Sens Comparison operator
Returns
string
Definition at line 362 of file export.class.php.
Referenced by build_filterQuery().
create ($user)
Save an export model in database.
Parameters
User $user Object user that save
Returns
int <0 if KO, >0 if OK
Definition at line 701 of file export.class.php.
References $resql, db, and dol_syslog().
delete ($user, $notrigger = 0)
Delete object in database.
Parameters
User $user User that delete
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 790 of file export.class.php.
References $resql, db, and dol_syslog().
fetch ($id)
Load an export profil from database.
Parameters
int $id Id of profil to load
Returns
int <0 if KO, >0 if OK
Definition at line 747 of file export.class.php.
References db, dol_print_error(), and dol_syslog().
genDocFilter ($TypeField)
Build an input field used to filter the query.
Parameters
string $TypeField Type of Field to filter
Returns
string html string of the input field ex : "<input type=text name=... value=...>"
Definition at line 499 of file export.class.php.
list_export_model ()
Output list all export models TODO Move this into a class htmlxxx.class.php.
Returns
void
Definition at line 845 of file export.class.php.
References db, dol_print_error(), img_delete(), img_object(), and print.
load_arrays ($user, $filter = '')
Load an exportable dataset.
Parameters
User $user Object user making export
string $filter Load a particular dataset only
Returns
int <0 if KO, >0 if OK
Definition at line 81 of file export.class.php.
References db, dol_osencode(), dol_syslog(), dolGetModulesDirs(), and verifCond().
The documentation for this class was generated from the following file:
htdocs/exports/class/export.class.php