Dolibarr: Ticket Class Reference
Ticket Class Reference
Class to manage ticket.
Public Member Functions
__construct ($db)
Constructor.
create ($user, $notrigger=0)
Create object into database.
fetch ($id= '', $ref= '', $track_id= '')
Load object in memory from the database.
fetchAll ($user, $sortorder= 'ASC', $sortfield= 't.datec', $limit= '', $offset=0, $arch= '', $filter= '')
Load all objects in memory from database.
update ($user=0, $notrigger=0)
Update object into database.
delete ($user, $notrigger=0)
Delete object in database.
createFromClone (User $user, $fromid)
Load an object from its id and create a new one in database.
initAsSpecimen ()
Initialise object with example values Id must be 0 if object instance is a specimen.
printSelectStatus ($selected="")
print selected status
loadCacheTypesTickets ()
Charge dans cache la liste des types de tickets (paramétrable dans dictionnaire)
loadCacheCategoriesTickets ()
Charge dans cache la liste des catégories de tickets (paramétrable dans dictionnaire)
loadCacheSeveritiesTickets ()
Charge dans cache la liste des sévérité de tickets (paramétrable dans dictionnaire)
getLibStatut ($mode=0)
Return status label of object.
LibStatut ($statut, $mode=0)
Return status label of object.
getNomUrl ($withpicto=0, $option= '', $notooltip=0, $morecss= '', $save_lastsearch_value=-1)
Return a link to the object card (with optionaly the picto)
markAsRead ($user, $notrigger=0)
Mark a message as read.
assignUser ($user, $id_assign_user, $notrigger=0)
Mark a message as read.
loadCacheLogsTicket ()
Charge la liste des actions sur le ticket.
createTicketMessage ($user, $notrigger=0)
Add message into database.
loadCacheMsgsTicket ()
Load the list of event on ticket into ->cache_msgs_ticket.
close (User $user)
Close a ticket.
searchSocidByEmail ($email, $type= '0', $filters=array(), $clause= 'AND')
Search and fetch thirparties by email.
searchContactByEmail ($email, $socid= '', $case= '')
Search and fetch contacts by email.
setCustomer ($id)
Define parent commany of current ticket.
setProgression ($percent)
Define progression of current ticket.
setProject ($projectid)
Link element with a project Override core function because of key name 'fk_project' used for this module.
setContract ($contractid)
Link element with a contract.
getIdTicketInternalContact ()
Return id des contacts interne de suivi.
getInfosTicketInternalContact ()
Retrieve informations about internal contacts.
getIdTicketCustomerContact ()
Return id des contacts clients pour le suivi ticket.
getInfosTicketExternalContact ()
Retrieve informations about external contacts.
getIdTicketInternalInvolvedContact ()
Return id des contacts clients des intervenants.
getIdTicketCustomerInvolvedContact ()
Return id des contacts clients des intervenants.
getTicketAllContacts ()
Return id of all contacts for ticket.
getTicketAllCustomerContacts ()
Return id of all contacts for ticket.
messageSend ($subject, $texte)
Send message.
listeContact ($statut=-1, $source= 'external', $list=0, $code= '')
Get array of all contacts for a ticket Override method of file commonobject.class.php to add phone number.
getDefaultRef ($thirdparty= '')
Get a default reference.
is_photo_available ($sdir)
Return if at least one photo is available.
copyFilesForTicket ()
Copy files into ticket directory Used for files linked into messages.
newMessage ($user, &$action, $private=1)
Add new message on a ticket (private area)
sendTicketMessageByEmail ($subject, $message, $send_internal_cc=0, $array_receiver=array())
Send ticket by email to linked contacts.
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0)
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source= 'external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source= 'internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source= '', $code= '')
Delete all links between an object $this and all its contacts.
liste_contact ($statut=-1, $source= 'external', $list=0, $code= '')
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source= 'internal', $order= 'position', $option=0, $activeonly=0, $code= '')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contactid into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table= '', $id=null, $format= '', $id_field= '', $fuser=null, $trigkey= '', $fk_user_field= 'fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source= 'external')
Return list of id of contacts of object.
setProject ($projectid)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id)
Change the payments terms.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder= 'ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix= '')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust= 'none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null)
Add objects linked in llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $clause= 'OR', $alsosametype=1, $orderby= 'sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
updateObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '')
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $rowid= '')
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType= '', $trigkey= '')
Set status of an object.
getCanvas ($id=0, $ref= '')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
display_incoterms ()
Return incoterms informations TODO Use a cache for label get.
getIncotermsForPDF ()
Return incoterms informations for pdf display.
setIncoterms ($id_incoterm, $location)
Define incoterms values of current object.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir= '/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir= '/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafieldsline=0, $defaulttpldir= '/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist= '', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist= '', $defaulttpldir= '/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
addThumbs ($file)
Build thumb Move this into files.lib.php.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($trigger_name, $user)
Call trigger based on this instance.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger= '', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update an extra field value for the current object.
showInputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
showOutputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss= '')
Return HTML string to show a field into a page Code very similar with showOutputField of extra fields.
showOptionals ($extrafields, $mode= 'view', $params=null, $keysuffix= '', $keyprefix= '', $onetrtd=0)
Function to show lines of extrafields with output datas.
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere= '')
Load object in memory from the database.
fetchLinesCommon ($morewhere= '')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
Data Fields
$subject
var string Ticket subject
const STATUS_NOT_READ = 0
Status.
Data Fields inherited from CommonObject
$projet
$note
Private Member Functions
verify ()
Check properties of ticket are ok (like ref, track_id, ...).
sendLogByEmail ($user, $message)
Send notification of changes by email.
Additional Inherited Members
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref= '', $ref_ext= '')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static commonReplaceThirdparty (DoliDB $db, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
isNull ($info)
Function test if type is null.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare the values to insert.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ()
Function to concat keys of fields.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage ticket.
Definition at line 34 of file ticket.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDb $db Database handler
Definition at line 223 of file ticket.class.php.
References db.
Member Function Documentation
assignUser ($user, $id_assign_user, $notrigger = 0)
Mark a message as read.
Parameters
User $user Object user
int $id_assign_user ID of user assigned
int $notrigger Disable trigger
Returns
int <0 if KO, 0=Nothing done, >0 if OK
Definition at line 1417 of file ticket.class.php.
References $resql, CommonObject\call_trigger(), db, dol_clone(), and dol_syslog().
close (User $user)
Close a ticket.
Parameters
User $user User that close
Returns
int <0 if KO, >0 if OK
Definition at line 1710 of file ticket.class.php.
References $resql, CommonObject\call_trigger(), db, dol_now(), dol_syslog(), and CommonObject\fetchObjectLinked().
copyFilesForTicket ()
Copy files into ticket directory Used for files linked into messages.
Returns
void
Definition at line 2397 of file ticket.class.php.
References db, dol_is_dir(), dol_mkdir(), dol_move(), image_format_supported(), and vignette().
int Notify tiers at create ($user, $notrigger = 0)
Create object into database.
Parameters
User $user User that creates
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, Id of created object if OK
Definition at line 324 of file ticket.class.php.
References $resql, CommonObject\call_trigger(), db, dol_now(), dol_strlen(), dol_syslog(), generate_random_id(), CommonObject\insertExtraFields(), and verify().
createFromClone (User $user, $fromid)
Load an object from its id and create a new one in database.
Parameters
User $user User that clone
int $fromid Id of object to clone
Returns
int New id of clone
Definition at line 951 of file ticket.class.php.
References db.
createTicketMessage ($user, $notrigger = 0)
Add message into database.
Parameters
User $user User that creates
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, Id of created object if OK
Definition at line 1611 of file ticket.class.php.
References $subject, db, and dol_now().
delete ($user, $notrigger = 0)
Delete object in database.
Parameters
User $user User that deletes
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 876 of file ticket.class.php.
References $resql, CommonObject\call_trigger(), db, CommonObject\delete_linked_contact(), CommonObject\deleteExtraFields(), CommonObject\deleteObjectLinked(), and dol_syslog().
fetch ($id = '', $ref = '', $track_id = '')
Load object in memory from the database.
Parameters
int $id Id object
string $ref Ref
string $track_id Track id, a hash like ref
Returns
int <0 if KO, >0 if OK
Definition at line 444 of file ticket.class.php.
References $resql, db, dol_print_error(), dol_syslog(), CommonObject\fetch_optionals(), and getEntity().
fetchAll ($user, $sortorder = 'ASC', $sortfield = 't.datec', $limit = '', $offset = 0, $arch = '', $filter = '')
Load all objects in memory from database.
Parameters
User $user User for action
string $sortorder Sort order
string $sortfield Sort field
int $limit page number
int $offset Offset for query
int $arch archive or not (not used)
array $filter Filter for query output
Returns
int <0 if KO, >0 if OK
Definition at line 569 of file ticket.class.php.
References $resql, db, dol_syslog(), and getEntity().
getDefaultRef ($thirdparty = '')
Get a default reference.
Parameters
Societe $thirdparty Thirdparty
Returns
string Reference
Definition at line 2319 of file ticket.class.php.
References dol_buildpath(), and dol_include_once().
getIdTicketCustomerContact ()
Return id des contacts clients pour le suivi ticket.
Returns
array Liste des id contacts suivi ticket
Definition at line 2019 of file ticket.class.php.
References CommonObject\getIdContact().
Referenced by getTicketAllContacts(), and getTicketAllCustomerContacts().
getIdTicketCustomerInvolvedContact ()
Return id des contacts clients des intervenants.
Returns
array Liste des id contacts intervenants
Definition at line 2049 of file ticket.class.php.
References CommonObject\getIdContact().
Referenced by getTicketAllContacts(), and getTicketAllCustomerContacts().
getIdTicketInternalContact ()
Return id des contacts interne de suivi.
Returns
array Liste des id contacts suivi ticket
Definition at line 1999 of file ticket.class.php.
References CommonObject\getIdContact().
Referenced by getTicketAllContacts().
getIdTicketInternalInvolvedContact ()
Return id des contacts clients des intervenants.
Returns
array Liste des id contacts intervenants
Definition at line 2039 of file ticket.class.php.
References CommonObject\getIdContact().
Referenced by getTicketAllContacts().
getInfosTicketExternalContact ()
Retrieve informations about external contacts.
Returns
array Array with datas : firstname, lastname, socid (-1 for internal users), email, code, libelle, status
Definition at line 2029 of file ticket.class.php.
References listeContact().
Referenced by sendTicketMessageByEmail().
getInfosTicketInternalContact ()
Retrieve informations about internal contacts.
Returns
array Array with datas : firstname, lastname, socid (-1 for internal users), email, code, libelle, status
Definition at line 2009 of file ticket.class.php.
References listeContact().
Referenced by sendTicketMessageByEmail().
getLibStatut ($mode = 0)
Return status label of object.
Parameters
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto
Returns
string Label
Definition at line 1162 of file ticket.class.php.
getNomUrl ($withpicto = 0, $option = '', $notooltip = 0, $morecss = '', $save_lastsearch_value = -1)
Return a link to the object card (with optionaly the picto)
Parameters
int $withpicto Include picto in link (0=No picto, 1=Include picto into link, 2=Only picto)
string $option On what the link point to ('nolink', ...)
int $notooltip 1=Disable tooltip
string $morecss Add more css on link
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
Returns
string String with URL
Definition at line 1304 of file ticket.class.php.
References $subject, dol_buildpath(), and img_object().
getTicketAllContacts ()
Return id of all contacts for ticket.
Returns
array Array of contacts for tickets
Definition at line 2059 of file ticket.class.php.
References getIdTicketCustomerContact(), getIdTicketCustomerInvolvedContact(), getIdTicketInternalContact(), and getIdTicketInternalInvolvedContact().
getTicketAllCustomerContacts ()
Return id of all contacts for ticket.
Returns
array Array of contacts
Definition at line 2078 of file ticket.class.php.
References getIdTicketCustomerContact(), and getIdTicketCustomerInvolvedContact().
initAsSpecimen ()
Initialise object with example values Id must be 0 if object instance is a specimen.
Returns
void
Definition at line 997 of file ticket.class.php.
is_photo_available ($sdir)
Return if at least one photo is available.
Parameters
string $sdir Directory to scan
Returns
boolean True if at least one photo is available, False if not
Definition at line 2362 of file ticket.class.php.
References dol_is_file(), dol_osencode(), and utf8_check().
LibStatut ($statut, $mode = 0)
Return status label of object.
Parameters
string $statut id statut
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto, 6=Long label + Picto
Returns
string Label
Definition at line 1176 of file ticket.class.php.
References img_picto().
listeContact ($statut = -1, $source = 'external', $list = 0, $code = '')
Get array of all contacts for a ticket Override method of file commonobject.class.php to add phone number.
Parameters
int $statut Status of lines to get (-1=all)
string $source Source of contact: external or thirdparty (llx_socpeople) or internal (llx_user)
int $list 0:Return array contains all properties, 1:Return array contains just id
string $code Filter on this code of contact type ('SHIPPING', 'BILLING', ...)
Returns
array Array of contacts
Definition at line 2218 of file ticket.class.php.
References $resql, db, and dol_print_error().
Referenced by getInfosTicketExternalContact(), getInfosTicketInternalContact(), and sendLogByEmail().
loadCacheCategoriesTickets ()
Charge dans cache la liste des catégories de tickets (paramétrable dans dictionnaire)
Returns
int Number of lines loaded, 0 if already loaded, <0 if KO
Definition at line 1079 of file ticket.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
loadCacheLogsTicket ()
Charge la liste des actions sur le ticket.
Returns
int Number of lines loaded, 0 if already loaded, <0 if KO
Definition at line 1566 of file ticket.class.php.
loadCacheMsgsTicket ()
Load the list of event on ticket into ->cache_msgs_ticket.
Returns
int Number of lines loaded, 0 if already loaded, <0 if KO
Definition at line 1667 of file ticket.class.php.
References $resql, db, and dol_syslog().
Referenced by ActionsTicket\viewTicketTimelineMessages().
loadCacheSeveritiesTickets ()
Charge dans cache la liste des sévérité de tickets (paramétrable dans dictionnaire)
Returns
int Number of lines loaded, 0 if already loaded, <0 if KO
Definition at line 1119 of file ticket.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
loadCacheTypesTickets ()
Charge dans cache la liste des types de tickets (paramétrable dans dictionnaire)
Returns
int Number of lines loaded, 0 if already loaded, <0 if KO
Definition at line 1039 of file ticket.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
markAsRead ($user, $notrigger = 0)
Mark a message as read.
Parameters
User $user Object user
int $notrigger No trigger
Returns
int <0 if KO, >0 if OK
Definition at line 1365 of file ticket.class.php.
References $resql, CommonObject\call_trigger(), db, dol_now(), and dol_syslog().
messageSend ($subject, $texte)
Send message.
Parameters
string $subject Subject
string $texte Message to send
Returns
int <0 if KO, or number of changes if OK
Definition at line 2095 of file ticket.class.php.
References $subject, db, dol_mimetype(), dol_nl2br(), dol_now(), dol_print_error(), dol_strlen(), dol_syslog(), and CommonObject\getIdContact().
newMessage ($user, & $action, $private = 1)
Add new message on a ticket (private area)
Parameters
User $user User for action
string $action Action string
int $private 1=Message is private. TODO Implement this. What does this means ?
Returns
int
Definition at line 2448 of file ticket.class.php.
References $subject, db, dol_buildpath(), dolGetFirstLastname(), GETPOST(), sendTicketMessageByEmail(), and setEventMessages().
printSelectStatus ($selected = "")
print selected status
Parameters
string $selected selected status
Returns
void
Definition at line 1028 of file ticket.class.php.
References print, and Form\selectarray().
searchContactByEmail ($email, $socid = '', $case = '')
Search and fetch contacts by email.
Parameters
string $email Email
array $socid Limit to a thirdparty
string $case Respect case
Returns
array Array of contacts object
Definition at line 1850 of file ticket.class.php.
References db, dol_syslog(), and getEntity().
searchSocidByEmail ($email, $type = '0', $filters = array(), $clause = 'AND')
Search and fetch thirparties by email.
Parameters
string $email Email
int $type Type of thirdparties (0=any, 1=customer, 2=prospect, 3=supplier)
array $filters Array of couple field name/value to filter the companies with the same name
string $clause Clause for filters
Returns
array Array of thirdparties object
Definition at line 1784 of file ticket.class.php.
References db, dol_syslog(), and getEntity().
sendLogByEmail ($user, $message) private
Send notification of changes by email.
Parameters
User $user User that create
string $message Log message
Returns
int <0 if KO, >0 if OK (number of emails sent)
Definition at line 1476 of file ticket.class.php.
References $subject, dol_buildpath(), dol_html_entity_decode(), dol_nl2br(), dolGetFirstLastname(), CommonObject\fetch_thirdparty(), listeContact(), and setEventMessages().
sendTicketMessageByEmail ($subject, $message, $send_internal_cc = 0, $array_receiver = array())
Send ticket by email to linked contacts.
Parameters
string $subject Email subject
string $message Email message
int $send_internal_cc Receive a copy on internal email ($conf->global->TICKET_NOTIFICATION_EMAIL_FROM)
array $array_receiver Array of receiver. exemple array('name' => 'John Doe', 'email' => 'john@.nosp@m.doe..nosp@m.com', etc...)
Returns
void
Definition at line 2667 of file ticket.class.php.
References $subject, db, dol_nl2br(), dol_syslog(), getInfosTicketExternalContact(), getInfosTicketInternalContact(), and setEventMessages().
Referenced by newMessage().
setContract ($contractid)
Link element with a contract.
Parameters
int $contractid Contract id to link element to
Returns
int <0 if KO, >0 if OK
Definition at line 1975 of file ticket.class.php.
References CommonObject\add_object_linked(), db, dol_print_error(), and dol_syslog().
setCustomer ($id)
Define parent commany of current ticket.
Parameters
int $id Id of thirdparty to set or '' to remove
Returns
int <0 if KO, >0 if OK
Definition at line 1894 of file ticket.class.php.
References $resql, db, and dol_syslog().
setProgression ($percent)
Define progression of current ticket.
Parameters
int $percent Progression percent
Returns
int <0 if KO, >0 if OK
Definition at line 1918 of file ticket.class.php.
References $resql, db, and dol_syslog().
setProject ($projectid)
Link element with a project Override core function because of key name 'fk_project' used for this module.
Parameters
int $projectid Project id to link element to
Returns
int <0 if KO, >0 if OK
Definition at line 1943 of file ticket.class.php.
References db, dol_print_error(), and dol_syslog().
update ($user = 0, $notrigger = 0)
Update object into database.
Parameters
User $user User that modifies
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 733 of file ticket.class.php.
References $resql, CommonObject\call_trigger(), db, dol_strlen(), dol_syslog(), and CommonObject\insertExtraFields().
verify () private
Check properties of ticket are ok (like ref, track_id, ...).
All properties must be already loaded on object (this->ref, this->track_id, ...).
Returns
int 0 if OK, <0 if KO
Definition at line 237 of file ticket.class.php.
References dol_syslog().
Referenced by create().
The documentation for this class was generated from the following file:
htdocs/ticket/class/ticket.class.php