Dolibarr: MailingTargets Class Reference
MailingTargets Class Reference
Parent class of emailing target selectors modules.
Public Member Functions
__construct ($db)
Constructor.
getDesc ()
Return description of email selector.
getNbOfRecords ()
Return number of records for email selector.
getNbOfRecipients ($sql)
Retourne nombre de destinataires.
formFilter ()
Affiche formulaire de filtre qui apparait dans page de selection des destinataires de mailings.
update_nb ($mailing_id)
Met a jour nombre de destinataires.
add_to_target ($mailing_id, $cibles)
Ajoute destinataires dans table des cibles.
clear_target ($mailing_id)
Supprime tous les destinataires de la table des cibles.
Detailed Description
Parent class of emailing target selectors modules.
Definition at line 32 of file modules_mailings.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 52 of file modules_mailings.php.
References db.
Member Function Documentation
add_to_target ($mailing_id, $cibles)
Ajoute destinataires dans table des cibles.
Parameters
int $mailing_id Id of emailing
array $cibles Array with targets
Returns
int < 0 si erreur, nb ajout si ok
Definition at line 162 of file modules_mailings.php.
References db, dol_hash(), dol_print_error(), dol_syslog(), getEntity(), and update_nb().
clear_target ($mailing_id)
Supprime tous les destinataires de la table des cibles.
Parameters
int $mailing_id Id of emailing
Returns
void
Definition at line 257 of file modules_mailings.php.
References db, dol_syslog(), and update_nb().
formFilter ()
Affiche formulaire de filtre qui apparait dans page de selection des destinataires de mailings.
Returns
string Retourne zone select
Definition at line 115 of file modules_mailings.php.
getDesc ()
Return description of email selector.
Returns
string Return translation of module label. Try translation of $this->name then translation of 'MailingModuleDesc'.$this->name, or $this->desc if not found
Definition at line 62 of file modules_mailings.php.
getNbOfRecipients ($sql)
Retourne nombre de destinataires.
Parameters
string $sql Sql request to count
Returns
int Nb of recipient, or <0 if error
Definition at line 94 of file modules_mailings.php.
References db.
getNbOfRecords ()
Return number of records for email selector.
Returns
integer Example
Definition at line 83 of file modules_mailings.php.
update_nb ($mailing_id)
Met a jour nombre de destinataires.
Parameters
int $mailing_id Id of emailing
Returns
int < 0 si erreur, nb destinataires si ok
Definition at line 127 of file modules_mailings.php.
References db, and dol_syslog().
Referenced by add_to_target(), and clear_target().
The documentation for this class was generated from the following file:
htdocs/core/modules/mailings/modules_mailings.php