Dolibarr: htdocs/modulebuilder/template/core/tpl/mytemplate.tpl.php File Reference
mytemplate.tpl.php File Reference
Module MyModule
Example template.
Variables
if (empty($conf)||!is_object($conf))
Your code here.
Detailed Description
Example template.
Put detailed description here.
Definition in file mytemplate.tpl.php.
Variable Documentation
if(empty($conf)||!is_object($conf))
Your code here.
Definition at line 27 of file mytemplate.tpl.php.
Referenced by CMailFile\__construct(), Stats\_getAllByYear(), pdf_einstein\_tableau_tot(), pdf_azur\_tableau_tot(), pdf_crabe\_tableau_tot(), Propal\addline(), Export\build_filterQuery(), commande_prepare_head(), Form\constructProductListOption(), Facture\create(), WebsitePage\createFromClone(), Stripe\createPaymentStripe(), dol_banner_tab(), dol_format_address(), DolGraph\draw_jflot(), pdf_eratosthene\drawTotalTable(), pdf_cyan\drawTotalTable(), pdf_sponge\drawTotalTable(), Form\editfieldkey(), Form\editfieldval(), Form\formconfirm(), ActionComm\getActions(), Setup\getCheckIntegrity(), ActionComm\getNomUrl(), Stripe\getPaymentIntent(), CommonObject\initAsSpecimenCommon(), DolibarrModules\insert_const(), Form\load_cache_vatrates(), RssParser\parser(), project_timesheet_prepare_head(), projectLinesa(), FormOther\select_categories(), Form\select_conditions_paiements(), FormOther\select_month(), Form\select_produits_fournisseurs_list(), Form\select_produits_list(), FormOther\select_salesrepresentatives(), FormCompany\select_state(), FormSocialContrib\select_type_socialcontrib(), Form\select_types_paiements(), FormCompany\selectCompaniesForNewContact(), FormProjets\selectOpportunityStatus(), FormOther\selectProjectTasks(), FormCompany\selectTypeContact(), FormProduct\selectWarehouses(), Conf\setValues(), show_list_sending_receive(), Form\textwithtooltip(), top_htmlhead(), pdf_cornas\write_file(), pdf_cyan\write_file(), pdf_eratosthene\write_file(), pdf_canelle\write_file(), pdf_aurore\write_file(), pdf_sponge\write_file(), pdf_muscadet\write_file(), pdf_azur\write_file(), pdf_einstein\write_file(), and pdf_crabe\write_file().