Dolibarr: htdocs/core/lib/ticket.lib.php File Reference
ticket.lib.php File Reference
Module Ticket
This file is a library for Ticket module.
Functions
ticketAdminPrepareHead ()
Build tabs for admin page.
ticket_prepare_head ($object)
Build tabs for a Ticket object.
generate_random_id ($car=16)
Generate a random id.
llxHeaderTicket ($title, $head="", $disablejs=0, $disablehead=0, $arrayofjs= '', $arrayofcss= '')
Show header for public pages.
Detailed Description
This file is a library for Ticket module.
Definition in file ticket.lib.php.
Function Documentation
generate_random_id ($car = 16)
Generate a random id.
Parameters
string $car Char to generate key
Returns
void
Definition at line 134 of file ticket.lib.php.
Referenced by Ticket\create(), and Tickets\post().
llxHeaderTicket ($title, $head = "", $disablejs = 0, $disablehead = 0, $arrayofjs = '', $arrayofcss = '')
Show header for public pages.
Parameters
string $title Title
string $head Head array
int $disablejs More content into html header
int $disablehead More content into html header
array $arrayofjs Array of complementary js files
array $arrayofcss Array of complementary css files
Returns
void
Definition at line 156 of file ticket.lib.php.
References dol_buildpath(), print, and top_htmlhead().
ticket_prepare_head ($object)
Build tabs for a Ticket object.
Parameters
Ticket $object Object Ticket
Returns
array Array of tabs
Definition at line 73 of file ticket.lib.php.
References complete_head_from_modules(), dol_buildpath(), and dol_dir_list().
ticketAdminPrepareHead ()
Build tabs for admin page.
Returns
array
Definition at line 30 of file ticket.lib.php.
References complete_head_from_modules().