Dolibarr: EcmDirectory Class Reference
EcmDirectory Class Reference
Class to manage ECM directories.
Public Member Functions
__construct ($db)
Constructor.
create ($user)
Create record into database.
update ($user=null, $notrigger=0)
Update database.
changeNbOfFiles ($value)
Update cache of nb of documents into database.
fetch ($id)
Load object in memory from database.
delete ($user, $mode= 'all', $deletedirrecursive=0)
Delete object on database and/or on disk.
initAsSpecimen ()
Initialise an instance with random values.
getNomUrl ($withpicto=0, $option= '', $max=0, $more= '', $notooltip=0)
Return directory name you can click (and picto)
getRelativePath ($force=0)
Return relative path of a directory on disk.
load_motherof ()
Load this->motherof that is array(id_son=>id_parent, ...)
getLibStatut ($mode=0)
Retourne le libelle du status d'un user (actif, inactif)
get_full_arbo ($force=0)
Reconstruit l'arborescence des categories sous la forme d'un tableau à partir de la base de donnée Renvoi un tableau de tableau('id','id_mere',...) trie selon arbre et avec: id Id de la categorie id_mere Id de la categorie mere id_children Tableau des id enfant label Name of directory cachenbofdoc Nb of documents date_c Date creation fk_user_c User creation login_c Login creation fullpath Full path of id (Added by build_path_from_id_categ call) fullrelativename Full path name (Added by build_path_from_id_categ call) fulllabel Full label (Added by build_path_from_id_categ call) level Level of line (Added by build_path_from_id_categ call)
build_path_from_id_categ ($id_categ, $protection=0)
Define properties fullpath, fullrelativename, fulllabel of a directory of array this->cats and all its childs.
refreshcachenboffile ($all=0)
Refresh value for cachenboffile.
call_trigger ($trigger_name, $user)
Call trigger based on this instance.
Static Public Member Functions
static LibStatut ($status, $mode=0)
Return the status.
Detailed Description
Class to manage ECM directories.
Definition at line 28 of file ecmdirectory.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 108 of file ecmdirectory.class.php.
References db.
Member Function Documentation
build_path_from_id_categ ($id_categ, $protection = 0)
Define properties fullpath, fullrelativename, fulllabel of a directory of array this->cats and all its childs.
Separator between directories is always '/', whatever is OS.
Parameters
int $id_categ id_categ entry to update
int $protection Deep counter to avoid infinite loop
Returns
void
Definition at line 713 of file ecmdirectory.class.php.
Referenced by get_full_arbo().
call_trigger ($trigger_name, $user)
Call trigger based on this instance.
NB: Error from trigger are stacked in errors NB2: if trigger fail, action should be canceled. NB3: Should be deleted if EcmDirectory extend CommonObject
Parameters
string $trigger_name trigger's name to execute
User $user Object user
Returns
int Result of run_triggers
Definition at line 802 of file ecmdirectory.class.php.
References db.
Referenced by create(), delete(), and update().
changeNbOfFiles ($value)
Update cache of nb of documents into database.
Parameters
string $value '+' or '-' or new number
Returns
int <0 if KO, >0 if OK
Definition at line 291 of file ecmdirectory.class.php.
References $resql, db, and dol_syslog().
create ($user)
Create record into database.
Parameters
User $user User that create
Returns
int <0 if KO, >0 if OK
Definition at line 121 of file ecmdirectory.class.php.
References $resql, call_trigger(), db, description, dol_mkdir(), dol_now(), dol_sanitizeFileName(), dol_syslog(), getRelativePath(), and label.
delete ($user, $mode = 'all', $deletedirrecursive = 0)
Delete object on database and/or on disk.
Parameters
User $user User that delete
string $mode 'all'=delete all, 'databaseonly'=only database entry, 'fileonly' (not implemented)
int $deletedirrecursive 1=Agree to delete content recursiveley (otherwise an error will be returned when trying to delete)
Returns
int <0 if KO, >0 if OK
Definition at line 378 of file ecmdirectory.class.php.
References $resql, call_trigger(), db, dol_delete_dir(), dol_delete_dir_recursive(), dol_osencode(), dol_syslog(), and getRelativePath().
fetch ($id)
Load object in memory from database.
Parameters
int $id Id of object
Returns
int <0 if KO, 0 if not found, >0 if OK
Definition at line 323 of file ecmdirectory.class.php.
References $resql, db, description, dol_syslog(), and label.
get_full_arbo ($force = 0)
Reconstruit l'arborescence des categories sous la forme d'un tableau à partir de la base de donnée Renvoi un tableau de tableau('id','id_mere',...) trie selon arbre et avec: id Id de la categorie id_mere Id de la categorie mere id_children Tableau des id enfant label Name of directory cachenbofdoc Nb of documents date_c Date creation fk_user_c User creation login_c Login creation fullpath Full path of id (Added by build_path_from_id_categ call) fullrelativename Full path name (Added by build_path_from_id_categ call) fulllabel Full label (Added by build_path_from_id_categ call) level Level of line (Added by build_path_from_id_categ call)
Parameters
int $force Force reload of full arbo even if already loaded in cache $this->cats
Returns
array Tableau de array
Definition at line 623 of file ecmdirectory.class.php.
References $resql, build_path_from_id_categ(), db, dol_print_error(), dol_sort_array(), dol_syslog(), and load_motherof().
Referenced by getRelativePath().
getLibStatut ($mode = 0)
Retourne le libelle du status d'un user (actif, inactif)
Parameters
int $mode 0=libelle long, 1=libelle court, 2=Picto + Libelle court, 3=Picto, 4=Picto + Libelle long, 5=Libelle court + Picto
Returns
string Label of status
Definition at line 582 of file ecmdirectory.class.php.
References LibStatut().
getNomUrl ($withpicto = 0, $option = '', $max = 0, $more = '', $notooltip = 0)
Return directory name you can click (and picto)
Parameters
int $withpicto 0=Pas de picto, 1=Include picto into link, 2=Only picto
string $option Sur quoi pointe le lien
int $max Max length
string $more Add more param on a link
int $notooltip 1=Disable tooltip
Returns
string Chaine avec URL
Definition at line 471 of file ecmdirectory.class.php.
References dol_escape_htmltag(), dol_trunc(), and img_object().
getRelativePath ($force = 0)
Return relative path of a directory on disk.
Parameters
int $force Force reload of full arbo even if already loaded
Returns
string Relative physical path
Definition at line 504 of file ecmdirectory.class.php.
References dol_sanitizeFileName(), and get_full_arbo().
Referenced by create(), delete(), and refreshcachenboffile().
initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
void
Definition at line 451 of file ecmdirectory.class.php.
References description, and label.
static LibStatut ($status, $mode = 0) static
Return the status.
Parameters
int $status Id status
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto, 5=Long label + Picto
Returns
string Label of status
Definition at line 595 of file ecmdirectory.class.php.
Referenced by getLibStatut().
load_motherof ()
Load this->motherof that is array(id_son=>id_parent, ...)
Returns
int <0 if KO, >0 if OK
Definition at line 544 of file ecmdirectory.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
Referenced by get_full_arbo().
refreshcachenboffile ($all = 0)
Refresh value for cachenboffile.
This scan and count files into directory.
Parameters
int $all 0=refresh record using this->id , 1=refresh record using this->entity
Returns
int -1 if KO, Nb of files in directory if OK
Definition at line 753 of file ecmdirectory.class.php.
References $resql, db, dol_dir_list(), dol_syslog(), and getRelativePath().
update ($user = null, $notrigger = 0)
Update database.
Parameters
User $user User that modify
int $notrigger 0=no, 1=yes (no update trigger)
Returns
int <0 if KO, >0 if OK
Definition at line 233 of file ecmdirectory.class.php.
References $resql, call_trigger(), db, description, dol_syslog(), and label.
The documentation for this class was generated from the following file:
htdocs/ecm/class/ecmdirectory.class.php