Dolibarr: DolGraph Class Reference
DolGraph Class Reference
Class to build graphs.
Public Member Functions
__construct ($library= 'jflot')
Constructor.
SetPrecisionY ($which_prec)
Set Y precision.
SetHorizTickIncrement ($xi)
Utiliser SetNumTicks ou SetHorizTickIncrement mais pas les 2.
SetNumXTicks ($xt)
Utiliser SetNumTicks ou SetHorizTickIncrement mais pas les 2.
SetLabelInterval ($x)
Set label interval to reduce number of labels.
SetHideXGrid ($bool)
Hide X grid.
SetHideYGrid ($bool)
Hide Y grid.
SetYLabel ($label)
Set y label.
SetWidth ($w)
Set width.
SetTitle ($title)
Set title.
SetData ($data)
Set data.
SetDataColor ($datacolor)
Set data.
SetType ($type)
Set type.
SetLegend ($legend)
Set legend.
SetLegendWidthMin ($legendwidthmin)
Set min width.
SetMaxValue ($max)
Set max value.
GetMaxValue ()
Get max value.
SetMinValue ($min)
Set min value.
GetMinValue ()
Get min value.
SetHeight ($h)
Set height.
SetShading ($s)
Set shading.
SetCssPrefix ($s)
Set shading.
ResetBgColor ()
Reset bg color.
ResetBgColorGrid ()
Reset bgcolorgrid.
isGraphKo ()
Is graph ko.
setShowLegend ($showlegend)
Show legend or not.
setShowPointValue ($showpointvalue)
Show pointvalue or not.
setShowPercent ($showpercent)
Show percent or not.
SetBgColor ($bg_color=array(255, 255, 255))
Define background color of complete image.
SetBgColorGrid ($bg_colorgrid=array(255, 255, 255))
Define background color of grid.
ResetDataColor ()
Reset data color.
GetMaxValueInData ()
Get max value.
GetMinValueInData ()
Return min value of all data.
GetCeilMaxValue ()
Return max value of all data.
GetFloorMinValue ()
Return min value of all data.
draw ($file, $fileurl= '')
Build a graph into memory using correct library (may also be wrote on disk, depending on library used)
show ($shownographyet=0)
Output HTML string to show graph.
Static Public Member Functions
static getDefaultGraphSizeForStats ($direction, $defaultsize= '')
getDefaultGraphSizeForStats
Data Fields
$data
Array of data.
Private Member Functions
draw_artichow ($file, $fileurl)
Build a graph onto disk using Artichow library and return img string to it.
draw_jflot ($file, $fileurl)
Build a graph using JFlot library.
Detailed Description
Class to build graphs.
Usage is: $dolgraph=new DolGraph(); $dolgraph->SetTitle($langs->transnoentities('MyTitle').'
'.$langs->transnoentities('MyTitlePercent').''); $dolgraph->SetMaxValue(50); $dolgraph->SetData($data); $dolgraph->setShowLegend(1); $dolgraph->setShowPercent(1); $dolgraph->SetType(array('pie')); $dolgraph->setWidth('100'); $dolgraph->draw('idofgraph'); print $dolgraph->show($total?0:1);
Definition at line 40 of file dolgraph.class.php.
Constructor & Destructor Documentation
__construct ($library = 'jflot')
Constructor.
Parameters
string $library 'jflot' (default) or 'artichow' (no more supported)
Definition at line 97 of file dolgraph.class.php.
Member Function Documentation
draw ($file, $fileurl = '')
Build a graph into memory using correct library (may also be wrote on disk, depending on library used)
Parameters
string $file Image file name to use to save onto disk (also used as javascript unique id)
string $fileurl Url path to show image if saved onto disk
Returns
integer|null
Definition at line 666 of file dolgraph.class.php.
References dol_syslog().
draw_artichow ($file, $fileurl) private
Build a graph onto disk using Artichow library and return img string to it.
Parameters
string $file Image file name to use if we save onto disk
string $fileurl Url path to show image if saved onto disk
Returns
void
Definition at line 698 of file dolgraph.class.php.
References dol_escape_htmltag(), dol_strlen(), dol_syslog(), SetShading(), and type.
draw_jflot ($file, $fileurl) private
Build a graph using JFlot library.
Input when calling this method should be: $this->data = array(array(0=>'labelxA',1=>yA), array('labelxB',yB)); $this->data = array(array(0=>'labelxA',1=>yA1,...,n=>yAn), array('labelxB',yB1,...yBn)); // or when there is n series to show for each x $this->data = array(array('label'=>'labelxA','data'=>yA), array('labelxB',yB)); // Syntax deprecated $this->legend= array("Val1",...,"Valn"); // list of n series name $this->type = array('bars',...'lines'); or array('pie') $this->mode = 'depth' ??? $this->bgcolorgrid $this->datacolor $this->shownodatagraph
Parameters
string $file Image file name to use to save onto disk (also used as javascript unique id)
string $fileurl Url path to show image if saved onto disk. Never used here.
Returns
void
Definition at line 888 of file dolgraph.class.php.
References $data, dol_escape_htmltag(), dol_escape_js(), dol_string_nospecial(), dol_string_unaccent(), dol_syslog(), if, label, print, and type.
GetCeilMaxValue ()
Return max value of all data.
Returns
int Max value of all data
Definition at line 615 of file dolgraph.class.php.
References dol_strlen(), and GetMaxValueInData().
static getDefaultGraphSizeForStats ($direction, $defaultsize = '') static
getDefaultGraphSizeForStats
Parameters
string $direction 'width' or 'height'
string $defaultsize Value we want as default size
Returns
int Value of width or height to use by default
Definition at line 1157 of file dolgraph.class.php.
GetFloorMinValue ()
Return min value of all data.
Returns
double Max value of all data
Definition at line 640 of file dolgraph.class.php.
References dol_strlen(), and GetMinValueInData().
GetMaxValue ()
Get max value.
Returns
int Max value
Definition at line 344 of file dolgraph.class.php.
GetMaxValueInData ()
Get max value.
Returns
int Max value
Definition at line 561 of file dolgraph.class.php.
Referenced by GetCeilMaxValue().
GetMinValue ()
Get min value.
Returns
int Max value
Definition at line 369 of file dolgraph.class.php.
GetMinValueInData ()
Return min value of all data.
Returns
int Min value of all data
Definition at line 588 of file dolgraph.class.php.
Referenced by GetFloorMinValue().
isGraphKo ()
Is graph ko.
Returns
string Error
Definition at line 443 of file dolgraph.class.php.
ResetBgColor ()
Reset bg color.
Returns
void
Definition at line 420 of file dolgraph.class.php.
ResetBgColorGrid ()
Reset bgcolorgrid.
Returns
void
Definition at line 432 of file dolgraph.class.php.
ResetDataColor ()
Reset data color.
Returns
void
Definition at line 549 of file dolgraph.class.php.
SetBgColor ($bg_color = array(255,255,255))
Define background color of complete image.
Parameters
array $bg_color array(R,G,B) ou 'onglet' ou 'default'
Returns
void
Definition at line 490 of file dolgraph.class.php.
SetBgColorGrid ($bg_colorgrid = array(255,255,255))
Define background color of grid.
Parameters
array $bg_colorgrid array(R,G,B) ou 'onglet' ou 'default'
Returns
void
Definition at line 520 of file dolgraph.class.php.
SetCssPrefix ($s)
Set shading.
Parameters
string $s Shading
Returns
void
Definition at line 408 of file dolgraph.class.php.
SetData ($data)
Set data.
Parameters
array $data Data
Returns
void
See also
draw_jflot() for syntax of data array
Definition at line 267 of file dolgraph.class.php.
References $data.
SetDataColor ($datacolor)
Set data.
Parameters
array $datacolor Data color array(array(R,G,B),array(R,G,B)...)
Returns
void
Definition at line 280 of file dolgraph.class.php.
SetHeight ($h)
Set height.
Parameters
int $h Height
Returns
void
Definition at line 382 of file dolgraph.class.php.
SetHideXGrid ($bool)
Hide X grid.
Parameters
boolean $bool XGrid or not
Returns
boolean true
Definition at line 199 of file dolgraph.class.php.
SetHideYGrid ($bool)
Hide Y grid.
Parameters
boolean $bool YGrid or not
Returns
boolean true
Definition at line 213 of file dolgraph.class.php.
SetHorizTickIncrement ($xi)
Utiliser SetNumTicks ou SetHorizTickIncrement mais pas les 2.
Parameters
float $xi Xi
Returns
boolean True
Definition at line 157 of file dolgraph.class.php.
SetLabelInterval ($x)
Set label interval to reduce number of labels.
Parameters
float $x Label interval
Returns
boolean True
Definition at line 185 of file dolgraph.class.php.
SetLegend ($legend)
Set legend.
Parameters
array $legend Legend. Example: array('seriename1','seriname2',...)
Returns
void
Definition at line 306 of file dolgraph.class.php.
SetLegendWidthMin ($legendwidthmin)
Set min width.
Parameters
int $legendwidthmin Min width
Returns
void
Definition at line 319 of file dolgraph.class.php.
SetMaxValue ($max)
Set max value.
Parameters
int $max Max value
Returns
void
Definition at line 332 of file dolgraph.class.php.
SetMinValue ($min)
Set min value.
Parameters
int $min Min value
Returns
void
Definition at line 357 of file dolgraph.class.php.
SetNumXTicks ($xt)
Utiliser SetNumTicks ou SetHorizTickIncrement mais pas les 2.
Parameters
float $xt Xt
Returns
boolean True
Definition at line 171 of file dolgraph.class.php.
SetPrecisionY ($which_prec)
Set Y precision.
Parameters
float $which_prec Precision
Returns
boolean
Deprecated:
Definition at line 144 of file dolgraph.class.php.
SetShading ($s)
Set shading.
Parameters
string $s Shading
Returns
void
Definition at line 395 of file dolgraph.class.php.
Referenced by draw_artichow().
setShowLegend ($showlegend)
Show legend or not.
Parameters
int $showlegend 1=Show legend (default), 0=Hide legend
Returns
void
Definition at line 454 of file dolgraph.class.php.
setShowPercent ($showpercent)
Show percent or not.
Parameters
int $showpercent 1=Show percent for each point, as tooltip or inline, 0=Hide percent (default)
Returns
void
Definition at line 476 of file dolgraph.class.php.
setShowPointValue ($showpointvalue)
Show pointvalue or not.
Parameters
int $showpointvalue 1=Show value for each point, as tooltip or inline (default), 0=Hide value
Returns
void
Definition at line 465 of file dolgraph.class.php.
SetTitle ($title)
Set title.
Parameters
string $title Title
Returns
void
Definition at line 253 of file dolgraph.class.php.
SetType ($type)
Set type.
Parameters
array $type Array with type for each serie. Example: array('pie'), array('lines',...,'bars')
Returns
void
Definition at line 293 of file dolgraph.class.php.
References type.
SetWidth ($w)
Set width.
Parameters
int | string $w Width (Example: 320 or '100')
Returns
boolean|null True
Definition at line 240 of file dolgraph.class.php.
SetYLabel ($label)
Set y label.
Parameters
string $label Y label
Returns
boolean|null True
Definition at line 227 of file dolgraph.class.php.
show ($shownographyet = 0)
Output HTML string to show graph.
Parameters
int $shownographyet Show graph to say there is not enough data
Returns
string HTML string to show graph
Definition at line 1135 of file dolgraph.class.php.
The documentation for this class was generated from the following file:
htdocs/core/class/dolgraph.class.php