Dolibarr: ExtraFields Class Reference
ExtraFields Class Reference
Class to manage standard extra fields.
Public Member Functions
__construct ($db)
Constructor.
addExtraField ($attrname, $label, $type, $pos, $size, $elementtype, $unique=0, $required=0, $default_value= '', $param= '', $alwayseditable=0, $perms= '', $list= '-1', $help= '', $computed= '', $entity= '', $langfile= '', $enabled= '1')
Add a new extra field parameter.
delete ($attrname, $elementtype= 'member')
Delete an optional attribute.
update ($attrname, $label, $type, $length, $elementtype, $unique=0, $required=0, $pos=0, $param= '', $alwayseditable=0, $perms= '', $list= '', $help= '', $default= '', $computed= '', $entity= '', $langfile= '', $enabled= '1', $totalizable=0)
Modify type of a personalized attribute.
fetch_name_optionals_label ($elementtype, $forceload=false)
Load array this->attributes, or old this->attribute_xxx like attribute_label, attribute_type, ...
showInputField ($key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss= '', $objectid=0, $extrafieldsobjectkey= '')
Return HTML string to put an input field into a page Code very similar with showInputField of common object.
showOutputField ($key, $value, $moreparam= '', $extrafieldsobjectkey= '')
Return HTML string to put an output field into a page.
getAlignFlag ($key, $extrafieldsobjectkey= '')
Return tag to describe alignement to use for this extrafield.
showSeparator ($key, $object)
Return HTML string to print separator extrafield.
setOptionalsFromPost ($extralabels, &$object, $onlykey= '')
Fill array_options property of object by extrafields value (using for data sent by forms)
getOptionalsFromPost ($extrafieldsobjectkey, $keyprefix= '', $keysuffix= '')
return array_options array of data of extrafields value of object sent by a search form
Private Member Functions
create ($attrname, $type= 'varchar', $length=255, $elementtype= 'member', $unique=0, $required=0, $default_value= '', $param= '', $perms= '', $list= '0', $computed= '')
Add a new optional attribute.
create_label ($attrname, $label= '', $type= '', $pos=0, $size=0, $elementtype= 'member', $unique=0, $required=0, $param= '', $alwayseditable=0, $perms= '', $list= '-1', $help= '', $default= '', $computed= '', $entity= '', $langfile= '', $enabled= '1')
Add description of a new optional attribute.
delete_label ($attrname, $elementtype= 'member')
Delete description of an optional attribute.
update_label ($attrname, $label, $type, $size, $elementtype, $unique=0, $required=0, $pos=0, $param= '', $alwayseditable=0, $perms= '', $list= '0', $help= '', $default= '', $computed= '', $entity= '', $langfile= '', $enabled= '1', $totalizable=0)
Modify description of personalized attribute.
Detailed Description
Class to manage standard extra fields.
Definition at line 38 of file extrafields.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 185 of file extrafields.class.php.
References db.
Member Function Documentation
addExtraField ($attrname, $label, $type, $pos, $size, $elementtype, $unique = 0, $required = 0, $default_value = '', $param = '', $alwayseditable = 0, $perms = '', $list = '-1', $help = '', $computed = '', $entity = '', $langfile = '', $enabled = '1')
Add a new extra field parameter.
Parameters
string $attrname Code of attribute
string $label label of attribute
int $type Type of attribute ('boolean','int','varchar','text','html','date','datehour','price','phone','mail','password','url','select','checkbox','separate',...)
int $pos Position of attribute
string $size Size/length definition of attribute ('5', '24,8', ...). For float, it contains 2 numeric separated with a comma.
string $elementtype Element type. Same value than object->table_element (Example 'member', 'product', 'thirdparty', ...)
int $unique Is field unique or not
int $required Is field required or not
string $default_value Defaulted value (In database. use the default_value feature for default value on screen. Example: '', '0', 'null', 'avalue')
array | string $param Params for field (ex for select list : array('options' => array(value'=>'label of option')))
int $alwayseditable Is attribute always editable regardless of the document status
string $perms Permission to check
string $list Visibilty ('0'=never visible, '1'=visible on list+forms, '2'=list only, '3'=form only or 'eval string')
string $help Text with help tooltip
string $computed Computed value
string $entity Entity of extrafields (for multicompany modules)
string $langfile Language file
string $enabled Condition to have the field enabled or not
Returns
int <=0 if KO, >0 if OK
Definition at line 229 of file extrafields.class.php.
References create(), and create_label().
create ($attrname, $type = 'varchar', $length = 255, $elementtype = 'member', $unique = 0, $required = 0, $default_value = '', $param = '', $perms = '', $list = '0', $computed = '') private
Add a new optional attribute.
This is a private method. For public method, use addExtraField.
Parameters
string $attrname code of attribute
int $type Type of attribute ('boolean', 'int', 'varchar', 'text', 'html', 'date', 'datehour','price','phone','mail','password','url','select','checkbox', ...)
string $length Size/length of attribute ('5', '24,8', ...)
string $elementtype Element type ('member', 'product', 'thirdparty', 'contact', ...)
int $unique Is field unique or not
int $required Is field required or not
string $default_value Default value for field (in database)
array $param Params for field (ex for select list : array('options'=>array('value'=>'label of option'))
string $perms Permission
string $list Into list view by default
string $computed Computed value
Returns
int <=0 if KO, >0 if OK
Definition at line 279 of file extrafields.class.php.
References $resql, and db.
Referenced by addExtraField().
create_label ($attrname, $label = '', $type = '', $pos = 0, $size = 0, $elementtype = 'member', $unique = 0, $required = 0, $param = '', $alwayseditable = 0, $perms = '', $list = '-1', $help = '', $default = '', $computed = '', $entity = '', $langfile = '', $enabled = '1') private
Add description of a new optional attribute.
Parameters
string $attrname code of attribute
string $label label of attribute
int $type Type of attribute ('int', 'varchar', 'text', 'html', 'date', 'datehour', 'float')
int $pos Position of attribute
string $size Size/length of attribute ('5', '24,8', ...)
string $elementtype Element type ('member', 'product', 'thirdparty', ...)
int $unique Is field unique or not
int $required Is field required or not
array | string $param Params for field (ex for select list : array('options' => array(value'=>'label of option')))
int $alwayseditable Is attribute always editable regardless of the document status
string $perms Permission to check
string $list Visibily
string $help Help on tooltip
string $default Default value (in database. use the default_value feature for default value on screen).
string $computed Computed value
string $entity Entity of extrafields
string $langfile Language file
string $enabled Condition to have the field enabled or not
Returns
int <=0 if KO, >0 if OK
Definition at line 375 of file extrafields.class.php.
References db, dol_now(), and dol_syslog().
Referenced by addExtraField().
delete ($attrname, $elementtype = 'member')
Delete an optional attribute.
Parameters
string $attrname Code of attribute to delete
string $elementtype Element type ('member', 'product', 'thirdparty', 'contact', ...)
Returns
int < 0 if KO, 0 if nothing is done, 1 if OK
Definition at line 472 of file extrafields.class.php.
References $resql, db, and delete_label().
delete_label ($attrname, $elementtype = 'member') private
Delete description of an optional attribute.
Parameters
string $attrname Code of attribute to delete
string $elementtype Element type ('member', 'product', 'thirdparty', ...)
Returns
int < 0 if KO, 0 if nothing is done, 1 if OK
Definition at line 532 of file extrafields.class.php.
References $resql, db, dol_print_error(), dol_syslog(), and print.
Referenced by delete().
fetch_name_optionals_label ($elementtype, $forceload = false)
Load array this->attributes, or old this->attribute_xxx like attribute_label, attribute_type, ...
Parameters
string $elementtype Type of element ('adherent', 'commande', 'thirdparty', 'facture', 'propal', 'product', ...).
boolean $forceload Force load of extra fields whatever is option MAIN_EXTRAFIELDS_DISABLED. Deprecated. Should not be required.
Returns
array Array of attributes keys+label for all extra fields.
Definition at line 830 of file extrafields.class.php.
References $resql, db, and dol_syslog().
getAlignFlag ($key, $extrafieldsobjectkey = '')
Return tag to describe alignement to use for this extrafield.
Parameters
string $key Key of attribute
string $extrafieldsobjectkey If defined, use the new method to get extrafields data
Returns
string Formated value
Definition at line 1908 of file extrafields.class.php.
getOptionalsFromPost ($extrafieldsobjectkey, $keyprefix = '', $keysuffix = '')
return array_options array of data of extrafields value of object sent by a search form
Parameters
array | string $extrafieldsobjectkey array of extrafields (old usage) or value of object->table_element (new usage)
string $keyprefix Prefix string to add into name and id of field (can be used to avoid duplicate names)
string $keysuffix Suffix string to add into name and id of field (can be used to avoid duplicate names)
Returns
array|int array_options set or 0 if no value
Definition at line 2117 of file extrafields.class.php.
References dol_mktime(), GETPOST(), and price2num().
setOptionalsFromPost ($extralabels, & $object, $onlykey = '')
Fill array_options property of object by extrafields value (using for data sent by forms)
Parameters
array $extralabels Deprecated $array of extrafields
object $object Object
string $onlykey Only following key is filled. When we make update of only one extrafield ($action = 'update_extras'), calling page must must set this to avoid to have other extrafields being reset.
Returns
int 1 if array_options set, 0 if no value, -1 if error (field required missing for example)
Definition at line 2017 of file extrafields.class.php.
References dol_eval(), dol_mktime(), GETPOST(), price2num(), and setEventMessages().
showInputField ($key, $value, $moreparam = '', $keysuffix = '', $keyprefix = '', $morecss = '', $objectid = 0, $extrafieldsobjectkey = '')
Return HTML string to put an input field into a page Code very similar with showInputField of common object.
Parameters
string $key Key of attribute
string $value Preselected value to show (for date type it must be in timestamp format, for amount or price it must be a php numeric value)
string $moreparam To add more parametes on html input tag
string $keysuffix Prefix string to add after name and id of field (can be used to avoid duplicate names)
string $keyprefix Suffix string to add before name and id of field (can be used to avoid duplicate names)
string $morecss More css (to defined size of field. Old behaviour: may also be a numeric)
int $objectid Current object id
string $extrafieldsobjectkey If defined (for example $object->table_element), use the new method to get extrafields data
Returns
string
Definition at line 963 of file extrafields.class.php.
References $resql, ajax_combobox(), db, dol_escape_htmltag(), dol_eval(), dol_syslog(), dol_trunc(), price(), and print.
showOutputField ($key, $value, $moreparam = '', $extrafieldsobjectkey = '')
Return HTML string to put an output field into a page.
Parameters
string $key Key of attribute
string $value Value to show
string $moreparam To add more parameters on html input tag (only checkbox use html input for output rendering)
string $extrafieldsobjectkey If defined (for example $object->table_element), use the new method to get extrafields data
Returns
string Formated value
Definition at line 1591 of file extrafields.class.php.
References $resql, db, dol_eval(), dol_htmlentitiesbr(), dol_include_once(), dol_print_date(), dol_print_email(), dol_print_phone(), dol_print_url(), dol_syslog(), dol_trunc(), and price().
showSeparator ($key, $object)
Return HTML string to print separator extrafield.
Parameters
string $key Key of attribute
string $object Object
Returns
string HTML code with line for separator
Definition at line 1960 of file extrafields.class.php.
References GETPOST().
update ($attrname, $label, $type, $length, $elementtype, $unique = 0, $required = 0, $pos = 0, $param = '', $alwayseditable = 0, $perms = '', $list = '', $help = '', $default = '', $computed = '', $entity = '', $langfile = '', $enabled = '1', $totalizable = 0)
Modify type of a personalized attribute.
Parameters
string $attrname Name of attribute
string $label Label of attribute
string $type Type of attribute ('boolean', 'int', 'varchar', 'text', 'html', 'date', 'datehour','price','phone','mail','password','url','select','checkbox', ...)
int $length Length of attribute
string $elementtype Element type ('member', 'product', 'thirdparty', 'contact', ...)
int $unique Is field unique or not
int $required Is field required or not
int $pos Position of attribute
array $param Params for field (ex for select list : array('options' => array(value'=>'label of option')))
int $alwayseditable Is attribute always editable regardless of the document status
string $perms Permission to check
string $list Visibility
string $help Help on tooltip
string $default Default value (in database. use the default_value feature for default value on screen).
string $computed Computed value
string $entity Entity of extrafields
string $langfile Language file
string $enabled Condition to have the field enabled or not
int $totalizable Is extrafield totalizable on list
Returns
int >0 if OK, <=0 if KO
Definition at line 589 of file extrafields.class.php.
References $resql, db, dol_syslog(), and update_label().
update_label ($attrname, $label, $type, $size, $elementtype, $unique = 0, $required = 0, $pos = 0, $param = '', $alwayseditable = 0, $perms = '', $list = '0', $help = '', $default = '', $computed = '', $entity = '', $langfile = '', $enabled = '1', $totalizable = 0) private
Modify description of personalized attribute.
Parameters
string $attrname Name of attribute
string $label Label of attribute
string $type Type of attribute
int $size Length of attribute
string $elementtype Element type ('member', 'product', 'thirdparty', ...)
int $unique Is field unique or not
int $required Is field required or not
int $pos Position of attribute
array $param Params for field (ex for select list : array('options' => array(value'=>'label of option')))
int $alwayseditable Is attribute always editable regardless of the document status
string $perms Permission to check
string $list Visiblity
string $help Help on tooltip.
string $default Default value (in database. use the default_value feature for default value on screen).
string $computed Computed value
string $entity Entity of extrafields
string $langfile Language file
string $enabled Condition to have the field enabled or not
int $totalizable Is extrafield totalizable on list
Returns
int <=0 if KO, >0 if OK
Definition at line 699 of file extrafields.class.php.
References db, dol_now(), dol_print_error(), dol_syslog(), and print.
Referenced by update().
The documentation for this class was generated from the following file:
htdocs/core/class/extrafields.class.php