Dolibarr: Holiday Class Reference
Holiday Class Reference
Class of the module paid holiday.
Public Member Functions
__construct ($db)
Constructor.
getNextNumRef ($objsoc)
Returns the reference to the following non used Order depending on the active numbering module defined into HOLIDAY_ADDON.
updateBalance ()
Update balance of vacations and check table of users for holidays is complete.
create ($user, $notrigger=0)
Créer un congés payés dans la base de données.
fetch ($id, $ref= '')
Load object in memory from database.
fetchByUser ($user_id, $order= '', $filter= '')
List holidays for a particular user or list of users.
fetchAll ($order, $filter)
List all holidays of all users.
validate ($user=null, $notrigger=0)
Validate leave request.
approve ($user=null, $notrigger=0)
Approve leave request.
update ($user=null, $notrigger=0)
Update database.
delete ($user, $notrigger=0)
Delete object in database.
verifDateHolidayCP ($fk_user, $dateStart, $dateEnd, $halfday=0)
Check if a user is on holiday (partially or completely) into a period.
verifDateHolidayForTimestamp ($fk_user, $timestamp, $status= '-1')
Check that a user is not on holiday for a particular timestamp.
getNomUrl ($withpicto=0, $save_lastsearch_value=-1)
Return clicable name (with picto eventually)
getLibStatut ($mode=0)
Returns the label status.
LibStatut ($statut, $mode=0, $startdate= '')
Returns the label of a statut.
selectStatutCP ($selected= '', $htmlname= 'select_statut')
Affiche un select HTML des statuts de congés payés.
updateConfCP ($name, $value)
Met à jour une option du module Holiday Payés.
getConfCP ($name, $createifnotfound= '')
Return value of a conf parameterfor leave module TODO Move this into llx_const table.
updateSoldeCP ($userID= '', $nbHoliday= '', $fk_type= '')
Met à jour le timestamp de la dernière mise à jour du solde des CP.
getCheckOption ($name)
Retourne un checked si vrai.
createCPusers ($single=false, $userid= '')
Créer les entrées pour chaque utilisateur au moment de la configuration.
deleteCPuser ($user_id)
Supprime un utilisateur du module Congés Payés.
getCPforUser ($user_id, $fk_type=0)
Retourne le solde de congés payés pour un utilisateur.
fetchUsers ($stringlist=true, $type=true, $filters= '')
Get list of Users or list of vacation balance.
fetch_users_approver_holiday ()
Return list of people with permission to validate leave requests.
countActiveUsers ()
Compte le nombre d'utilisateur actifs dans Dolibarr.
countActiveUsersWithoutCP ()
Compte le nombre d'utilisateur actifs dans Dolibarr sans CP.
verifNbUsers ($userDolibarrWithoutCP, $userCP)
Compare le nombre d'utilisateur actif de Dolibarr à celui des utilisateurs des congés payés.
addLogCP ($fk_user_action, $fk_user_update, $label, $new_solde, $fk_type)
addLogCP
fetchLog ($order, $filter)
Liste le log des congés payés.
getTypes ($active=-1, $affect=-1)
Return array with list of types.
initAsSpecimen ()
Initialise an instance with random values.
load_state_board ()
Load this->nb for dashboard.
load_board ($user)
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0)
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source= 'external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source= 'internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source= '', $code= '')
Delete all links between an object $this and all its contacts.
liste_contact ($statut=-1, $source= 'external', $list=0, $code= '')
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source= 'internal', $order= 'position', $option=0, $activeonly=0, $code= '')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contactid into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table= '', $id=null, $format= '', $id_field= '', $fuser=null, $trigkey= '', $fk_user_field= 'fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source= 'external')
Return list of id of contacts of object.
setProject ($projectid)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id)
Change the payments terms.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder= 'ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix= '')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust= 'none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null)
Add objects linked in llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $clause= 'OR', $alsosametype=1, $orderby= 'sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
updateObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '')
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $rowid= '')
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType= '', $trigkey= '')
Set status of an object.
getCanvas ($id=0, $ref= '')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
display_incoterms ()
Return incoterms informations TODO Use a cache for label get.
getIncotermsForPDF ()
Return incoterms informations for pdf display.
setIncoterms ($id_incoterm, $location)
Define incoterms values of current object.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir= '/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir= '/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafieldsline=0, $defaulttpldir= '/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist= '', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist= '', $defaulttpldir= '/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
addThumbs ($file)
Build thumb Move this into files.lib.php.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($trigger_name, $user)
Call trigger based on this instance.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger= '', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update an extra field value for the current object.
showInputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
showOutputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss= '')
Return HTML string to show a field into a page Code very similar with showOutputField of extra fields.
showOptionals ($extrafields, $mode= 'view', $params=null, $keysuffix= '', $keyprefix= '', $onetrtd=0)
Function to show lines of extrafields with output datas.
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere= '')
Load object in memory from the database.
fetchLinesCommon ($morewhere= '')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
Data Fields
$rowid
const STATUS_DRAFT = 1
Draft status.
const STATUS_VALIDATED = 2
Validated status.
const STATUS_APPROVED = 3
Approved.
const STATUS_CANCELED = 4
Canceled.
const STATUS_REFUSED = 5
Refused.
Data Fields inherited from CommonObject
$projet
$note
Additional Inherited Members
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref= '', $ref_ext= '')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static commonReplaceThirdparty (DoliDB $db, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
isNull ($info)
Function test if type is null.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare the values to insert.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ()
Function to concat keys of fields.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class of the module paid holiday.
Developed by Teclib (http://www.teclib.com/)
Definition at line 34 of file holiday.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 152 of file holiday.class.php.
References db.
Member Function Documentation
addLogCP ($fk_user_action, $fk_user_update, $label, $new_solde, $fk_type)
addLogCP
Parameters
int $fk_user_action Id user creation
int $fk_user_update Id user update
string $label Label
int $new_solde New value
int $fk_type Type of vacation
Returns
int Id of record added, 0 if nothing done, < 0 if KO
Definition at line 1964 of file holiday.class.php.
References $resql, db, dol_now(), dol_syslog(), getCPforUser(), and price2num().
Referenced by updateSoldeCP().
approve ($user = null, $notrigger = 0)
Approve leave request.
Parameters
User $user User that approve
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 748 of file holiday.class.php.
References $resql, CommonObject\call_trigger(), db, description, and dol_syslog().
countActiveUsers ()
Compte le nombre d'utilisateur actifs dans Dolibarr.
Returns
int retourne le nombre d'utilisateur
Definition at line 1910 of file holiday.class.php.
References db.
countActiveUsersWithoutCP ()
Compte le nombre d'utilisateur actifs dans Dolibarr sans CP.
Returns
int retourne le nombre d'utilisateur
Definition at line 1926 of file holiday.class.php.
References db.
create ($user, $notrigger = 0)
Créer un congés payés dans la base de données.
Parameters
User $user User that create
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, Id of created object if OK
Definition at line 253 of file holiday.class.php.
References $resql, CommonObject\call_trigger(), db, description, dol_now(), and dol_syslog().
createCPusers ($single = false, $userid = '')
Créer les entrées pour chaque utilisateur au moment de la configuration.
Parameters
boolean $single Single
int $userid Id user
Returns
void
Definition at line 1567 of file holiday.class.php.
References $resql, db, dol_print_error(), dol_syslog(), and fetchUsers().
delete ($user, $notrigger = 0)
Delete object in database.
Parameters
User $user User that delete
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 975 of file holiday.class.php.
References $resql, CommonObject\call_trigger(), db, and dol_syslog().
deleteCPuser ($user_id)
Supprime un utilisateur du module Congés Payés.
Parameters
int $user_id ID de l'utilisateur à supprimer
Returns
boolean Vrai si pas d'erreur, faut si Erreur
Definition at line 1602 of file holiday.class.php.
References db.
fetch ($id, $ref = '')
Load object in memory from database.
Parameters
int $id Id object
string $ref Ref object
Returns
int <0 if KO, >0 if OK
Definition at line 339 of file holiday.class.php.
References $resql, db, description, and dol_syslog().
fetch_users_approver_holiday ()
Return list of people with permission to validate leave requests.
Search for permission "approve leave requests"
Returns
array Array of user ids
Definition at line 1869 of file holiday.class.php.
References db, and dol_syslog().
fetchAll ($order, $filter)
List all holidays of all users.
Parameters
string $order Sort order
string $filter SQL Filter
Returns
int -1 if KO, 1 if OK, 2 if no result
Definition at line 551 of file holiday.class.php.
References $resql, db, and dol_syslog().
fetchByUser ($user_id, $order = '', $filter = '')
List holidays for a particular user or list of users.
Parameters
int | string $user_id ID of user to list, or comma separated list of IDs of users to list
string $order Sort order
string $filter SQL Filter
Returns
int -1 if KO, 1 if OK, 2 if no result
Definition at line 423 of file holiday.class.php.
References $resql, db, and dol_syslog().
Referenced by verifDateHolidayCP().
fetchLog ($order, $filter)
Liste le log des congés payés.
Parameters
string $order Filtrage par ordre
string $filter Filtre de séléction
Returns
int -1 si erreur, 1 si OK et 2 si pas de résultat
Definition at line 2033 of file holiday.class.php.
References $resql, db, and dol_syslog().
fetchUsers ($stringlist = true, $type = true, $filters = '')
Get list of Users or list of vacation balance.
Parameters
boolean $stringlist If true return a string list of id. If false, return an array with detail.
boolean $type If true, read Dolibarr user list, if false, return vacation balance list.
string $filters Filters
Returns
array|string|int Return an array
Definition at line 1649 of file holiday.class.php.
References $resql, db, and dol_syslog().
Referenced by createCPusers(), and updateSoldeCP().
getCheckOption ($name)
Retourne un checked si vrai.
Parameters
string $name name du paramètre de configuration
Returns
string retourne checked si > 0
Definition at line 1540 of file holiday.class.php.
References db.
getConfCP ($name, $createifnotfound = '')
Return value of a conf parameterfor leave module TODO Move this into llx_const table.
Parameters
string $name Name of parameter
string $createifnotfound 'stringvalue'=Create entry with string value if not found. For example 'YYYYMMDDHHMMSS'.
Returns
string Value of parameter. Example: 'YYYYMMDDHHMMSS' or < 0 if error
Definition at line 1351 of file holiday.class.php.
References db, and dol_syslog().
Referenced by updateSoldeCP().
getCPforUser ($user_id, $fk_type = 0)
Retourne le solde de congés payés pour un utilisateur.
Parameters
int $user_id ID de l'utilisateur
int $fk_type Filter on type
Returns
float Retourne le solde de congés payés de l'utilisateur
Definition at line 1619 of file holiday.class.php.
References db, and dol_syslog().
Referenced by addLogCP().
getLibStatut ($mode = 0)
Returns the label status.
Parameters
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto
Returns
string Label
Definition at line 1214 of file holiday.class.php.
References LibStatut().
getNextNumRef ($objsoc)
Returns the reference to the following non used Order depending on the active numbering module defined into HOLIDAY_ADDON.
Parameters
Societe $objsoc third party object
Returns
string Holiday free reference
Definition at line 165 of file holiday.class.php.
References dol_buildpath(), dol_print_error(), and print.
Referenced by validate().
getNomUrl ($withpicto = 0, $save_lastsearch_value = -1)
Return clicable name (with picto eventually)
Parameters
int $withpicto 0=_No picto, 1=Includes the picto in the linkn, 2=Picto only
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
Returns
string String with URL
Definition at line 1178 of file holiday.class.php.
References dol_escape_htmltag(), and img_object().
getTypes ($active = -1, $affect = -1)
Return array with list of types.
Parameters
int $active Status of type. -1 = Both
int $affect Filter on affect (a request will change sold or not). -1 = Both
Returns
array Return array with list of types
Definition at line 2110 of file holiday.class.php.
References db, and dol_print_error().
Referenced by updateSoldeCP().
initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
void
Definition at line 2147 of file holiday.class.php.
References description, dol_now(), and STATUS_VALIDATED.
LibStatut ($statut, $mode = 0, $startdate = '')
Returns the label of a statut.
Parameters
int $statut id statut
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto
integer $startdate Date holiday should start
Returns
string Label
Definition at line 1228 of file holiday.class.php.
References dol_now(), and img_picto().
Referenced by getLibStatut().
load_board ($user)
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
Parameters
User $user Objet user
Returns
WorkboardResponse|int <0 if KO, WorkboardResponse if OK
Definition at line 2205 of file holiday.class.php.
References $resql, db, dol_now(), dol_print_error(), and img_object().
load_state_board ()
Load this->nb for dashboard.
Returns
int <0 if KO, >0 if OK
Definition at line 2172 of file holiday.class.php.
References $resql, db, and dol_print_error().
selectStatutCP ($selected = '', $htmlname = 'select_statut')
Affiche un select HTML des statuts de congés payés.
Parameters
int $selected Id of preselected status
string $htmlname Name of HTML select field
Returns
string Show select of status
Definition at line 1293 of file holiday.class.php.
References print.
update ($user = null, $notrigger = 0)
Update database.
Parameters
User $user User that modify
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 861 of file holiday.class.php.
References $resql, CommonObject\call_trigger(), db, description, and dol_syslog().
updateBalance ()
Update balance of vacations and check table of users for holidays is complete.
If not complete.
Returns
int <0 if KO, >0 if OK
Definition at line 224 of file holiday.class.php.
References db, and updateSoldeCP().
updateConfCP ($name, $value)
Met à jour une option du module Holiday Payés.
Parameters
string $name name du paramètre de configuration
string $value vrai si mise à jour OK sinon faux
Returns
boolean ok or ko
Definition at line 1327 of file holiday.class.php.
References db, and dol_syslog().
updateSoldeCP ($userID = '', $nbHoliday = '', $fk_type = '')
Met à jour le timestamp de la dernière mise à jour du solde des CP.
Parameters
int $userID Id of user
int $nbHoliday Nb of days
int $fk_type Type of vacation
Returns
int 0=Nothing done, 1=OK, -1=KO
Definition at line 1406 of file holiday.class.php.
References $resql, addLogCP(), db, dol_now(), dol_print_date(), dol_syslog(), fetchUsers(), getConfCP(), getTypes(), and price2num().
Referenced by updateBalance().
validate ($user = null, $notrigger = 0)
Validate leave request.
Parameters
User $user User that validate
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 677 of file holiday.class.php.
References $resql, CommonObject\call_trigger(), db, dol_syslog(), and getNextNumRef().
verifDateHolidayCP ($fk_user, $dateStart, $dateEnd, $halfday = 0)
Check if a user is on holiday (partially or completely) into a period.
This function can be used to avoid to have 2 leave requests on same period for example. Warning: It consumes a lot of memory because it load in ->holiday all holiday of a dedicated user at each call.
Parameters
int $fk_user Id user
integer $dateStart Start date of period to check
integer $dateEnd End date of period to check
int $halfday Tag to define how start and end the period to check: 0:Full days, 2:Start afternoon end morning, -1:Start afternoon end afternoon, 1:Start morning end morning
Returns
boolean False = New range overlap an existing holiday, True = no overlapping (is never on holiday during checked period).
See also
verifDateHolidayForTimestamp()
Definition at line 1033 of file holiday.class.php.
References dol_print_error(), and fetchByUser().
verifDateHolidayForTimestamp ($fk_user, $timestamp, $status = '-1')
Check that a user is not on holiday for a particular timestamp.
Parameters
int $fk_user Id user
integer $timestamp Time stamp date for a day (YYYY-MM-DD) without hours (= 12:00AM in english and not 12:00PM that is 12:00)
string $status Filter on holiday status. '-1' = no filter.
Returns
array array('morning'=> ,'afternoon'=>), Boolean is true if user is available for day timestamp.
See also
verifDateHolidayCP()
Definition at line 1115 of file holiday.class.php.
References $resql, db, and dol_print_error().
verifNbUsers ($userDolibarrWithoutCP, $userCP)
Compare le nombre d'utilisateur actif de Dolibarr à celui des utilisateurs des congés payés.
Parameters
int $userDolibarrWithoutCP Number of active users in Dolibarr without holidays
int $userCP Number of active users into table of holidays
Returns
int <0 if KO, >0 if OK
Definition at line 1946 of file holiday.class.php.
References dol_syslog().
Field Documentation
$rowid
Deprecated:
See also
$id
Definition at line 63 of file holiday.class.php.
The documentation for this class was generated from the following file:
htdocs/holiday/class/holiday.class.php