Dolibarr: htdocs/core/lib/functions2.lib.php File Reference
functions2.lib.php File Reference
A set of functions for Dolibarr This file contains all rare functions.
Functions
jsUnEscape ($source)
Same function than javascript unescape() function but in PHP.
dolGetModulesDirs ($subdir= '')
Return list of modules directories.
dol_getDefaultFormat (Translate $outputlangs=null)
Try to guess default paper format according to language into $langs.
dol_print_file ($langs, $filename, $searchalt=0)
Output content of a file $filename in version of current language (otherwise may use an alternate language)
dol_print_object_info ($object, $usetable=0)
Show informations on an object TODO Move this into html.formother.
dolAddEmailTrackId ($email, $trackingid)
Return an email formatted to include a tracking id For example myema.nosp@m.il@e.nosp@m.xampl.nosp@m.e.co.nosp@m.m becom myema.nosp@m.il+t.nosp@m.racki.nosp@m.ngid.nosp@m.@exam.nosp@m.ple..nosp@m.com.
isValidMailDomain ($mail)
Return true if email has a domain name that can't be resolved.
isValidUrl ($url, $http=0, $pass=0, $port=0, $path=0, $query=0, $anchor=0)
Url string validation <http[s]> :// [user[:pass]@] hostname [port] [/path] [?getquery] [anchor].
isValidVATID ($company)
Check if VAT numero is valid (check done on syntax only, no database or remote access)
clean_url ($url, $http=1)
Clean an url string.
dolObfuscateEmail ($mail, $replace="*", $nbreplace=8, $nbdisplaymail=4, $nbdisplaydomain=3, $displaytld=true)
Returns an email value with obfuscated parts.
array2tr ($data, $troptions= '', $tdoptions= '')
Return lines of an html table from an array Used by array2table function only.
array2table ($data, $tableMarkup=1, $tableoptions= '', $troptions= '', $tdoptions= '')
Return an html table from an array.
get_next_value ($db, $mask, $table, $field, $where= '', $objsoc= '', $date= '', $mode= 'next', $bentityon=true, $objuser=null, $forceentity=null)
Return last or next value for a mask (according to area we should not reset)
get_string_between ($string, $start, $end)
Get string between.
check_value ($mask, $value)
Check value.
binhex ($bin, $pad=false, $upper=false)
Convert a binary data to string that represent hexadecimal value.
hexbin ($hexa)
Convert an hexadecimal string into a binary string.
numero_semaine ($time)
Retourne le numero de la semaine par rapport a une date.
weight_convert ($weight, &$from_unit, $to_unit)
Convertit une masse d'une unite vers une autre unite.
dol_set_user_param ($db, $conf, &$user, $tab)
Save personnal parameter.
dol_print_reduction ($reduction, $langs)
Returns formated reduction.
version_os ()
Return OS version.
version_php ()
Return PHP version.
version_dolibarr ()
Return Dolibarr version.
version_webserver ()
Return web server version.
getListOfModels ($db, $type, $maxfilenamelength=0)
Return list of activated modules usable for document generation.
is_ip ($ip)
This function evaluates a string that should be a valid IPv4 Note: For ip 169.254.0.0, it returns 0 with some PHP (5.6.24) and 2 with some minor patchs of PHP (5.6.25).
dol_buildlogin ($lastname, $firstname)
Build a login from lastname, firstname.
getSoapParams ()
Return array to use for SoapClient constructor.
dolGetElementUrl ($objectid, $objecttype, $withpicto=0, $option= '')
Return link url to an object.
cleanCorruptedTree ($db, $tabletocleantree, $fieldfkparent)
Clean corrupted tree (orphelins linked to a not existing parent), record linked to themself and child-parent loop.
getElementProperties ($element_type)
Get an array with properties of an element.
fetchObjectByElement ($element_id, $element_type, $element_ref= '')
Fetch an object from its id and element_type Inclusion of classes is automatic.
colorArrayToHex ($arraycolor, $colorifnotfound= '888888')
Convert an array with RGB value into hex RGB value.
colorStringToArray ($stringcolor, $colorifnotfound=array(88, 88, 88))
Convert a string RGB value ('FFFFFF', '255,255,255') into an array RGB array(255,255,255).
colorValidateHex ($color, $allow_white=true)
colorAgressivity ($hex, $ratio=-50)
Change color to make it less aggressive (ratio is negative) or more aggressive (ratio is positive)
colorAdjustBrightness ($hex, $steps)
colorDarker ($hex, $percent)
colorLighten ($hex, $percent)
colorHexToRgb ($hex, $alpha=false, $returnArray=false)
cartesianArray (array $input)
Applies the Cartesian product algorithm to an array Source: http://stackoverflow.com/a/15973172.
getModuleDirForApiClass ($module)
Get name of directory where the api_...class.php file is stored.
randomColorPart ($min=0, $max=255)
Return 2 hexa code randomly.
randomColor ($min=0, $max=255)
Return hexadecimal color randomly.
if(!function_exists('dolEscapeXML')) autoOrManual ($automaticmanual, $case=1, $color=0)
Return automatic or manual in current language.
convertBackOfficeMediasLinksToPublicLinks ($notetoshow)
Convert links to local wrapper to medias files into a string into a public external URL readable on internet.
Detailed Description
A set of functions for Dolibarr This file contains all rare functions.
Definition in file functions2.lib.php.
Function Documentation
array2table ($data, $tableMarkup = 1, $tableoptions = '', $troptions = '', $tdoptions = '')
Return an html table from an array.
Parameters
array $data Array of data
int $tableMarkup Table markup
string $tableoptions Options for table
string $troptions Options for tr
string $tdoptions Options for td
Returns
string
Definition at line 704 of file functions2.lib.php.
References array2tr().
array2tr ($data, $troptions = '', $tdoptions = '')
Return lines of an html table from an array Used by array2table function only.
Parameters
array $data Array of data
string $troptions Options for tr
string $tdoptions Options for td
Returns
string
Definition at line 684 of file functions2.lib.php.
Referenced by array2table().
if (!function_exists('dolEscapeXML')) autoOrManual ($automaticmanual, $case = 1, $color = 0)
Return automatic or manual in current language.
Parameters
string $automaticmanual Value to test (1, 'automatic', 'true' or 0, 'manual', 'false')
integer $case 1=Yes/No, 0=yes/no, 2=Disabled checkbox, 3=Disabled checkbox + Automatic/Manual
int $color 0=texte only, 1=Text is formated with a color font style ('ok' or 'error'), 2=Text is formated with 'ok' color.
Returns
string HTML string
Definition at line 2542 of file functions2.lib.php.
binhex ($bin, $pad = false, $upper = false)
Convert a binary data to string that represent hexadecimal value.
Parameters
string $bin Value to convert
boolean $pad Add 0
boolean $upper Convert to tupper
Returns
string x
Definition at line 1333 of file functions2.lib.php.
References dol_strlen().
cartesianArray (array $input)
Applies the Cartesian product algorithm to an array Source: http://stackoverflow.com/a/15973172.
Parameters
array $input Array of products
Returns
array Array of combinations
Definition at line 2386 of file functions2.lib.php.
check_value ($mask, $value)
Check value.
Parameters
string $mask Mask to use
string $value Value
Returns
int|string <0 or error string if KO, 0 if OK
Definition at line 1220 of file functions2.lib.php.
References dol_string_nospecial(), dol_strlen(), and dol_syslog().
Referenced by mod_codeproduct_elephant\verif(), mod_codeclient_elephant\verif(), and mod_barcode_product_standard\verif_syntax().
clean_url ($url, $http = 1)
Clean an url string.
Parameters
string $url Url
integer $http 1 = keep both http:// and https://, 0: remove http:// but not https://
Returns
string Cleaned url
Definition at line 597 of file functions2.lib.php.
Referenced by Link\update(), and Societe\update().
cleanCorruptedTree ($db, $tabletocleantree, $fieldfkparent)
Clean corrupted tree (orphelins linked to a not existing parent), record linked to themself and child-parent loop.
Parameters
DoliDB $db Database handler
string $tabletocleantree Table to clean
string $fieldfkparent Field name that contains id of parent
Returns
int Nb of records fixed/deleted
Definition at line 1934 of file functions2.lib.php.
References $resql, dol_print_error(), and print.
colorAdjustBrightness ($hex, $steps)
Parameters
string $hex Color in hex ('#AA1122' or 'AA1122' or '#a12' or 'a12')
integer $steps Step/offset added to each color component. It should be between -255 and 255. Negative = darker, positive = lighter
Returns
string New color with format '#AA1122'
See also
colorAgressivity()
Definition at line 2300 of file functions2.lib.php.
Referenced by colorDarker(), and colorLighten().
colorAgressivity ($hex, $ratio = -50)
Change color to make it less aggressive (ratio is negative) or more aggressive (ratio is positive)
Parameters
string $hex Color in hex ('#AA1122' or 'AA1122' or '#a12' or 'a12')
integer $ratio Default=-50. Note: 0=Component color is unchanged, -100=Component color become 88, +100=Component color become 00 or FF
Returns
string New string of color
See also
colorAdjustBrightness()
Definition at line 2259 of file functions2.lib.php.
colorArrayToHex ($arraycolor, $colorifnotfound = '888888')
Convert an array with RGB value into hex RGB value.
This is the opposite function of colorStringToArray
Parameters
array $arraycolor Array
string $colorifnotfound Color code to return if entry not defined or not a RGB format
Returns
string RGB hex value (without # before). For example: 'FF00FF', '01FF02'
See also
colorStringToArray(), colorHexToRgb()
Definition at line 2204 of file functions2.lib.php.
Referenced by FormOther\showColor(), and showSkins().
colorDarker ($hex, $percent)
Parameters
string $hex color in hex
integer $percent 0 to 100
Returns
string
Definition at line 2329 of file functions2.lib.php.
References colorAdjustBrightness().
colorHexToRgb ($hex, $alpha = false, $returnArray = false)
Parameters
string $hex color in hex
float $alpha 0 to 1 to add alpha channel
bool $returnArray Array set to 1 to return an array instead of string
Returns
string|array String or array
Definition at line 2353 of file functions2.lib.php.
colorLighten ($hex, $percent)
Parameters
string $hex color in hex
integer $percent 0 to 100
Returns
string
Definition at line 2340 of file functions2.lib.php.
References colorAdjustBrightness().
colorStringToArray ($stringcolor, $colorifnotfound = array(88,88,88))
Convert a string RGB value ('FFFFFF', '255,255,255') into an array RGB array(255,255,255).
This is the opposite function of colorArrayToHex. If entry is already an array, return it.
Parameters
string $stringcolor String with hex (FFFFFF) or comma RGB ('255,255,255')
array $colorifnotfound Color code array to return if entry not defined
Returns
array RGB hex value (without # before). For example: FF00FF
See also
colorArrayToHex(), colorHexToRgb()
Definition at line 2221 of file functions2.lib.php.
Referenced by FormOther\showColor(), and showSkins().
colorValidateHex ($color, $allow_white = true)
Parameters
string $color the color you need to valid
boolean $allow_white in case of white isn't valid
Returns
boolean
Definition at line 2240 of file functions2.lib.php.
convertBackOfficeMediasLinksToPublicLinks ($notetoshow)
Convert links to local wrapper to medias files into a string into a public external URL readable on internet.
Parameters
string $notetoshow Text to convert
Returns
string String
Definition at line 2576 of file functions2.lib.php.
Referenced by pdf_timespent\write_file(), pdf_beluga\write_file(), pdf_soleil\write_file(), pdf_baleine\write_file(), pdf_cornas\write_file(), pdf_cyan\write_file(), pdf_stdmovement\write_file(), pdf_eratosthene\write_file(), pdf_sponge\write_file(), pdf_aurore\write_file(), pdf_standard\write_file(), pdf_azur\write_file(), pdf_einstein\write_file(), and pdf_crabe\write_file().
dol_buildlogin ($lastname, $firstname)
Build a login from lastname, firstname.
Parameters
string $lastname Lastname
string $firstname Firstname
Returns
string Login
Definition at line 1745 of file functions2.lib.php.
References dol_string_nospecial(), and dol_string_unaccent().
Referenced by ActionsAdherentCardCommon\assign_values(), and ActionsContactCardCommon\assign_values().
dol_getDefaultFormat (Translate $outputlangs = null)
Try to guess default paper format according to language into $langs.
Parameters
Translate $outputlangs Output lang to use to autodetect output format if setup not done
Returns
string Default paper format code
Definition at line 123 of file functions2.lib.php.
Referenced by pdf_getFormat().
dol_print_file ($langs, $filename, $searchalt = 0)
Output content of a file $filename in version of current language (otherwise may use an alternate language)
Parameters
Translate $langs Object language to use for output
string $filename Relative filename to output
int $searchalt 1=Search also in alternative languages
Returns
boolean true if OK, false if KO
Definition at line 145 of file functions2.lib.php.
References dol_syslog(), print, and utf8_check().
dol_print_object_info ($object, $usetable = 0)
Show informations on an object TODO Move this into html.formother.
Parameters
object $object Objet to show
int $usetable Output into a table
Returns
void
Definition at line 195 of file functions2.lib.php.
References dol_print_date(), getServerTimeZoneInt(), and print.
dol_print_reduction ($reduction, $langs)
Returns formated reduction.
Parameters
int $reduction Reduction percentage
Translate $langs Output language
Returns
string Formated reduction
Definition at line 1553 of file functions2.lib.php.
References vatrate().
Referenced by pdf_getlineremisepercent().
dol_set_user_param ($db, $conf, & $user, $tab)
Save personnal parameter.
Parameters
DoliDB $db Handler database
Conf $conf Object conf
User $user Object user
array $tab Array (key=>value) with all parameters to save
Returns
int <0 if KO, >0 if OK
See also
dolibarr_get_const(), dolibarr_set_const(), dolibarr_del_const()
Definition at line 1486 of file functions2.lib.php.
References $resql, dol_print_error(), and dol_syslog().
Referenced by InfoBox\saveboxorder().
dolAddEmailTrackId ($email, $trackingid)
Return an email formatted to include a tracking id For example myema.nosp@m.il@e.nosp@m.xampl.nosp@m.e.co.nosp@m.m becom myema.nosp@m.il+t.nosp@m.racki.nosp@m.ngid.nosp@m.@exam.nosp@m.ple..nosp@m.com.
Parameters
string $email Email address (Ex: "toto@example.com", "John Do <johndo@example.com>")
string $trackingid Tracking id (Ex: thi123 for thirdparty with id 123)
Returns
string Return email tracker string
Definition at line 493 of file functions2.lib.php.
dolGetElementUrl ($objectid, $objecttype, $withpicto = 0, $option = '')
Return link url to an object.
Parameters
int $objectid Id of record
string $objecttype Type of object ('invoice', 'order', 'expedition_bon', ...)
int $withpicto Picto to show
string $option More options
Returns
string URL of link to object id/type
Definition at line 1809 of file functions2.lib.php.
References dol_include_once(), and dol_syslog().
Referenced by show_actions_done().
dolGetModulesDirs ($subdir = '')
Return list of modules directories.
We detect directories that contains a subdirectory /core/modules We discard directory modules that contains 'disabled' into their name.
Parameters
string $subdir Sub directory (Example: '/mailings')
Returns
array Array of directories that can contains module descriptors
Definition at line 81 of file functions2.lib.php.
Referenced by activateModule(), activateModulesRequiredByCountry(), complete_dictionary_with_modules(), complete_elementList_with_modules(), Import\load_arrays(), Export\load_arrays(), and unActivateModule().
dolObfuscateEmail ($mail, $replace = "*", $nbreplace = 8, $nbdisplaymail = 4, $nbdisplaydomain = 3, $displaytld = true)
Returns an email value with obfuscated parts.
Parameters
string $mail Email
string $replace Replacement character (defaul: *)
int $nbreplace Number of replacement character (default: 8)
int $nbdisplaymail Number of character unchanged (default: 4)
int $nbdisplaydomain Number of character unchanged of domain (default: 3)
bool $displaytld Display tld (default: true)
Returns
string Return email with hidden parts or '';
Definition at line 643 of file functions2.lib.php.
References isValidEmail().
fetchObjectByElement ($element_id, $element_type, $element_ref = '')
Fetch an object from its id and element_type Inclusion of classes is automatic.
Parameters
int $element_id Element id
string $element_type Element type
string $element_ref Element ref (Use this or element_id but not both)
Returns
int|object object || 0 || -1 if error
Definition at line 2175 of file functions2.lib.php.
References getElementProperties().
Referenced by Dolresource\fetch_all_resources(), Dolresource\fetch_all_used(), Dolresource\fetch_element_resource(), and Dolresource\getElementResources().
get_next_value ($db, $mask, $table, $field, $where = '', $objsoc = '', $date = '', $mode = 'next', $bentityon = true, $objuser = null, $forceentity = null)
Return last or next value for a mask (according to area we should not reset)
Parameters
DoliDB $db Database handler
string $mask Mask to use
string $table Table containing field with counter
string $field Field containing already used values of counter
string $where To add a filter on selection (for exemple to filter on invoice types)
Societe $objsoc The company that own the object we need a counter for
string $date Date to use for the {y},{m},{d} tags.
string $mode 'next' for next value or 'last' for last value
bool $bentityon Activate the entity filter. Default is true (for modules not compatible with multicompany)
User $objuser Object user we need data from.
int $forceentity Entity id to force
Returns
string New value (numeric) or error message
Definition at line 738 of file functions2.lib.php.
References $resql, dol_mktime(), dol_now(), dol_print_error(), dol_string_nospecial(), dol_string_unaccent(), dol_strlen(), dol_syslog(), and get_string_between().
Referenced by mod_reception_moonstone\getNextValue(), mod_chequereceipt_thyme\getNextValue(), mod_contract_magre\getNextValue(), mod_holiday_immaculate\getNextValue(), mod_ticket_universal\getNextValue(), mod_expedition_ribera\getNextValue(), mod_supplier_payment_brodator\getNextValue(), mod_commande_saphir\getNextValue(), mod_bom_advanced\getNextValue(), mod_payment_ant\getNextValue(), mod_expensereport_sand\getNextValue(), mod_project_universal\getNextValue(), mod_task_universal\getNextValue(), mod_livraison_saphir\getNextValue(), mod_arctic\getNextValue(), mod_supplier_proposal_saphir\getNextValue(), mod_commande_fournisseur_orchidee\getNextValue(), mod_propale_saphir\getNextValue(), mod_facture_mercure\getNextValue(), mod_barcode_product_standard\getNextValue(), mod_facture_fournisseur_tulip\getNextValue(), mod_codeproduct_elephant\getNextValue(), and mod_codeclient_elephant\getNextValue().
get_string_between ($string, $start, $end)
Get string between.
Parameters
string $string String to test
int $start Value for start
int $end Value for end
Returns
string Return part of string
Definition at line 1203 of file functions2.lib.php.
Referenced by get_next_value().
getElementProperties ($element_type)
Get an array with properties of an element.
Parameters
string $element_type Element type: 'action', 'facture', 'project_task' or 'object'...
Returns
array (module, classpath, element, subelement, classfile, classname)
Definition at line 2051 of file functions2.lib.php.
Referenced by fetchObjectByElement().
getListOfModels ($db, $type, $maxfilenamelength = 0)
Return list of activated modules usable for document generation.
Parameters
DoliDB $db Database handler
string $type Type of models (company, invoice, ...)
int $maxfilenamelength Max length of value to show
Returns
mixed 0 if no module is activated, or array(key=>label). For modules that need directory scan, key is completed with ":filename".
Definition at line 1620 of file functions2.lib.php.
References $resql, dol_dir_list(), dol_print_error(), dol_syslog(), and dol_trunc().
Referenced by ModelePDFSuppliersPayments\liste_modeles(), ModeleExpenseReport\liste_modeles(), ModelePDFStock\liste_modeles(), ModelePdfReception\liste_modeles(), ModeleAction\liste_modeles(), ModelePDFMovement\liste_modeles(), ModeleBankAccountDoc\liste_modeles(), ModelePDFProjects\liste_modeles(), ModelePDFTask\liste_modeles(), ModeleThirdPartyDoc\liste_modeles(), ModelePDFProduct\liste_modeles(), ModelePDFBoms\liste_modeles(), ModeleDon\liste_modeles(), ModelePDFCommandes\liste_modeles(), ModelePDFFicheinter\liste_modeles(), ModelePDFSuppliersInvoices\liste_modeles(), ModelePDFCards\liste_modeles(), ModelePDFLabels\liste_modeles(), ModelePDFDeliveryOrder\liste_modeles(), ModelePdfExpedition\liste_modeles(), ModelePDFSupplierProposal\liste_modeles(), ModelePDFFactures\liste_modeles(), ModelePDFPropales\liste_modeles(), ModelePDFContract\liste_modeles(), ModelePDFSuppliersOrders\liste_modeles(), ModelePDFHoliday\liste_modeles(), ModelePDFUserGroup\liste_modeles(), ModelePDFUser\liste_modeles(), ModelePDFProductBatch\liste_modeles(), and ModeleChequeReceipts\liste_modeles().
getModuleDirForApiClass ($module)
Get name of directory where the api_...class.php file is stored.
Parameters
string $module Module name
Returns
string Directory name
Definition at line 2416 of file functions2.lib.php.
getSoapParams ()
Return array to use for SoapClient constructor.
Returns
array
Definition at line 1759 of file functions2.lib.php.
hexbin ($hexa)
Convert an hexadecimal string into a binary string.
Parameters
string $hexa Hexadecimal string to convert (example: 'FF')
Returns
string bin
Definition at line 1349 of file functions2.lib.php.
References dol_strlen().
is_ip ($ip)
This function evaluates a string that should be a valid IPv4 Note: For ip 169.254.0.0, it returns 0 with some PHP (5.6.24) and 2 with some minor patchs of PHP (5.6.25).
See https://github.com/php/php-src/pull/1954.
Parameters
string $ip IP Address
Returns
int 0 if not valid or reserved range, 1 if valid and public IP, 2 if valid and private range IP
Definition at line 1721 of file functions2.lib.php.
Referenced by SMTPs\_server_connect().
isValidMailDomain ($mail)
Return true if email has a domain name that can't be resolved.
Parameters
string $mail Email address (Ex: "toto@example.com", "John Do <johndo@example.com>")
Returns
boolean True if domain email is OK, False if KO
Definition at line 505 of file functions2.lib.php.
isValidUrl ($url, $http = 0, $pass = 0, $port = 0, $path = 0, $query = 0, $anchor = 0)
Url string validation <http[s]> :// [user[:pass]@] hostname [port] [/path] [?getquery] [anchor].
Parameters
string $url Url
int $http 1: verify http is provided, 0: not verify http
int $pass 1: verify user and pass is provided, 0: not verify user and pass
int $port 1: verify port is provided, 0: not verify port
int $path 1: verify a path is provided "/" or "/..." or "/.../", 0: not verify path
int $query 1: verify query is provided, 0: not verify query
int $anchor 1: verify anchor is provided, 0: not verify anchor
Returns
int 1=Check is OK, 0=Check is KO
Definition at line 531 of file functions2.lib.php.
isValidVATID ($company)
Check if VAT numero is valid (check done on syntax only, no database or remote access)
Parameters
Societe $company VAT number
Returns
int 1=Check is OK, 0=Check is KO
Definition at line 573 of file functions2.lib.php.
jsUnEscape ($source)
Same function than javascript unescape() function but in PHP.
Parameters
string $source String to decode
Returns
string Unescaped string
Definition at line 40 of file functions2.lib.php.
References dol_html_entity_decode().
numero_semaine ($time)
Retourne le numero de la semaine par rapport a une date.
Parameters
string $time Date au format 'timestamp'
Returns
string Number of week
Definition at line 1366 of file functions2.lib.php.
randomColor ($min = 0, $max = 255)
Return hexadecimal color randomly.
Parameters
int $min Between 0 and 255
int $max Between 0 and 255
Returns
string A color string '123456'
Encode string for xml usage
Parameters
string $string String to encode
Returns
string String encoded
Definition at line 2513 of file functions2.lib.php.
References randomColorPart().
randomColorPart ($min = 0, $max = 255)
Return 2 hexa code randomly.
Parameters
int $min Between 0 and 255
int $max Between 0 and 255
Returns
string A color string '12'
Definition at line 2501 of file functions2.lib.php.
Referenced by randomColor().
version_dolibarr ()
Return Dolibarr version.
Returns
string Dolibarr version
See also
versiondolibarrarray()
Definition at line 1597 of file functions2.lib.php.
version_os ()
Return OS version.
Note that PHP_OS returns only OS (not version) and OS PHP was built on, not necessarly OS PHP runs on.
Returns
string OS version
Definition at line 1574 of file functions2.lib.php.
version_php ()
Return PHP version.
Returns
string PHP version
See also
versionphparray()
Definition at line 1586 of file functions2.lib.php.
version_webserver ()
Return web server version.
Returns
string Web server version
Definition at line 1607 of file functions2.lib.php.
weight_convert ($weight, & $from_unit, $to_unit)
Convertit une masse d'une unite vers une autre unite.
Parameters
float $weight Masse a convertir
int $from_unit Unite originale en puissance de 10
int $to_unit Nouvelle unite en puissance de 10
Returns
float Masse convertie
Definition at line 1449 of file functions2.lib.php.