Dolibarr: htdocs/stripe/lib/stripe.lib.php File Reference
stripe.lib.php File Reference
Module stripe
Library for common stripe functions.
Functions
stripeadmin_prepare_head ()
Define head array for tabs of stripe tools setup pages.
showStripePaymentUrl ($type, $ref)
Return string with full Url.
getStripePaymentUrl ($mode, $type, $ref= '', $amount= '9.99', $freetag= 'your_tag')
Return string with full Url.
html_print_stripe_footer ($fromcompany, $langs)
Show footer of company in HTML pages.
Detailed Description
Library for common stripe functions.
Definition in file stripe.lib.php.
Function Documentation
getStripePaymentUrl ($mode, $type, $ref = '', $amount = '9.99', $freetag = 'your_tag')
Return string with full Url.
Parameters
int $mode 0=True url, 1=Url formated with colors
string $type Type of URL ('free', 'order', 'invoice', 'contractline', 'membersubscription' ...)
string $ref Ref of object
int $amount Amount
string $freetag Free tag
Returns
string Url string
Definition at line 90 of file stripe.lib.php.
Referenced by showStripePaymentUrl().
html_print_stripe_footer ($fromcompany, $langs)
Show footer of company in HTML pages.
Parameters
Societe $fromcompany Third party
Translate $langs Output language
Returns
void
Definition at line 143 of file stripe.lib.php.
References getFormeJuridiqueLabel(), and print.
showStripePaymentUrl ($type, $ref)
Return string with full Url.
Parameters
string $type Type of URL ('free', 'order', 'invoice', 'contractline', 'membersubscription' ...)
string $ref Ref of object
Returns
string Url string
Definition at line 63 of file stripe.lib.php.
References ajax_autoselect(), getStripePaymentUrl(), and img_picto().
stripeadmin_prepare_head ()
Define head array for tabs of stripe tools setup pages.
Returns
Array of head
Definition at line 29 of file stripe.lib.php.
References complete_head_from_modules().