Dolibarr: Tasks Class Reference
Tasks Class Reference
Public Member Functions
__construct ()
Constructor.
get ($id, $includetimespent=0)
Get properties of a task object.
index ($sortfield="t.rowid", $sortorder= 'ASC', $limit=100, $page=0, $sqlfilters= '')
List tasks.
post ($request_data=null)
Create task object.
getRoles ($id, $userid=0)
Get time spent of a task.
put ($id, $request_data=null)
Add a task to given project.
delete ($id)
Delete task.
addTimeSpent ($id, $date, $duration, $user_id=0, $note= '')
Add time spent to a task of a project.
Public Member Functions inherited from DolibarrApi
__construct ($db, $cachedir= '', $refreshCache=false)
Constructor.
Protected Member Functions
_cleanObjectDatas ($object)
Clean sensible object datas.
Protected Member Functions inherited from DolibarrApi
_cleanObjectDatas ($object)
Executed method when API is called without parameter.
_checkFilters ($sqlfilters)
Return if a $sqlfilters parameter is valid.
Private Member Functions
_validate ($data)
Validate fields before create or update object.
Additional Inherited Members
Static Protected Member Functions inherited from DolibarrApi
static _checkAccessToResource ($resource, $resource_id=0, $dbtablename= '', $feature2= '', $dbt_keyfield= 'fk_soc', $dbt_select= 'rowid')
Check user access to a resource.
static _forge_criteria_callback ($matches)
Function to forge a SQL criteria.
Detailed Description
Definition at line 30 of file api_tasks.class.php.
Member Function Documentation
_cleanObjectDatas ($object) protected
Clean sensible object datas.
Parameters
object $object Object to clean
Returns
array Array of cleaned object properties
Definition at line 557 of file api_tasks.class.php.
Referenced by get(), getRoles(), and index().
_validate ($data) private
Validate fields before create or update object.
Parameters
array $data Array with data to verify
Returns
array
Exceptions
RestException
Definition at line 607 of file api_tasks.class.php.
Referenced by post().
addTimeSpent ($id, $date, $duration, $user_id = 0, $note = '')
Add time spent to a task of a project.
You can test this API with the following input message { "date": "2016-12-31 23:15:00", "duration": 1800, "user_id": 1, "note": "My time test" }
Parameters
int $id Task ID
datetime $date Date (YYYY-MM-DD HH:MI:SS in GMT)
int $duration Duration in seconds (3600 = 1h)
int $user_id User (Use 0 for connected user)
string $note Note
POST {id}/addtimespent
Returns
array
Definition at line 508 of file api_tasks.class.php.
References DolibarrApi\_checkAccessToResource(), and dol_stringtotime().
delete ($id)
Delete task.
Parameters
int $id Task ID
Returns
array
Definition at line 466 of file api_tasks.class.php.
References DolibarrApi\_checkAccessToResource().
get ($id, $includetimespent = 0)
Get properties of a task object.
Return an array with task informations
Parameters
int $id ID of task
int $includetimespent 0=Return only task. 1=Include a summary of time spent, 2=Include details of time spent lines (2 is no implemented yet)
Returns
array|mixed data without useless information
Exceptions
RestException
Definition at line 67 of file api_tasks.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
getRoles ($id, $userid = 0)
Get time spent of a task.
Parameters
int $id Id of task
Returns
int
GET {id}/tasks Get roles a user is assigned to a task with
Parameters
int $id Id of task
int $userid Id of user (0 = connected user)
GET {id}/roles
Returns
int
Definition at line 268 of file api_tasks.class.php.
References DolibarrApi\_checkAccessToResource(), _cleanObjectDatas(), and db.
index ($sortfield = "t.rowid", $sortorder = 'ASC', $limit = 100, $page = 0, $sqlfilters = '')
List tasks.
Get a list of tasks
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Limit for list
int $page Page number
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.ref:like:'SO-%') and (t.date_creation:<:'20160101')"
Returns
array Array of project objects
Definition at line 109 of file api_tasks.class.php.
References DolibarrApi\_checkFilters(), _cleanObjectDatas(), and dol_syslog().
post ($request_data = null)
Create task object.
Parameters
array $request_data Request data
Returns
int ID of project
Definition at line 191 of file api_tasks.class.php.
References _validate().
put ($id, $request_data = null)
Add a task to given project.
Parameters
int $id Id of project to update
array $request_data Projectline data
POST {id}/tasks
Returns
int Update a task to given project
Parameters
int $id Id of project to update
int $taskid Id of task to update
array $request_data Projectline data
PUT {id}/tasks/{taskid}
Returns
object Update task general fields (won't touch time spent of task)
Parameters
int $id Id of task to update
array $request_data Datas
Returns
int
Definition at line 430 of file api_tasks.class.php.
References DolibarrApi\_checkAccessToResource().
The documentation for this class was generated from the following file:
htdocs/projet/class/api_tasks.class.php