Dolibarr: BonPrelevement Class Reference
BonPrelevement Class Reference
Class to manage withdrawal receipts.
Public Member Functions
__construct ($db, $filename= '')
Constructor.
AddFacture ($facture_id, $client_id, $client_nom, $amount, $code_banque, $code_guichet, $number, $number_key)
Add invoice to withdrawal.
addline (&$line_id, $client_id, $client_nom, $amount, $code_banque, $code_guichet, $number, $number_key)
Add line to withdrawal.
getErrorString ($error)
Return error string.
fetch ($rowid, $ref= '')
Get object and lines from database.
set_credite ()
Set credite and set status of linked invoices.
set_infocredit ($user, $date)
Set direct debit order to "credited" status.
set_infotrans ($user, $date, $method)
Set withdrawal to transmited status.
SommeAPrelever ()
Returns amount of withdrawal.
NbFactureAPrelever ($banque=0, $agence=0)
Get number of invoices to withdrawal TODO delete params banque and agence when not necesary.
Create ($banque=0, $agence=0, $mode= 'real', $format= 'ALL', $executiondate= '')
Create a withdraw TODO delete params banque and agence when not necesary.
delete ($user=null, $notrigger=0)
Get object and lines from database.
getNomUrl ($withpicto=0, $option= '', $notooltip=0, $morecss= '', $save_lastsearch_value=-1)
Returns clickable name (with picto)
DeleteNotificationById ($rowid)
Delete a notification def by id.
DeleteNotification ($user, $action)
Delete a notification.
AddNotification ($db, $user, $action)
Add a notification.
generate ($format= 'ALL', $executiondate= '')
Generate a withdrawal file.
EnregDestinataire ($rowid, $client_nom, $rib_banque, $rib_guichet, $rib_number, $amount, $ref, $facid, $rib_dom= '')
Write recipient of request (customer)
EnregDestinataireSEPA ($row_code_client, $row_nom, $row_address, $row_zip, $row_town, $row_country_code, $row_cb, $row_cg, $row_cc, $row_somme, $row_ref, $row_idfac, $row_iban, $row_bic, $row_datec, $row_drum, $row_rum)
Write recipient of request (customer)
EnregEmetteur ()
Write sender of request (me)
EnregEmetteurSEPA ($configuration, $ladate, $nombre, $total, $CrLf= '\n', $format= 'FRST')
Write sender of request (me).
EnregTotal ($total)
Write end.
getLibStatut ($mode=0)
Return status label of object.
LibStatut ($statut, $mode=0)
Return status label for a status.
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0)
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source= 'external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source= 'internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source= '', $code= '')
Delete all links between an object $this and all its contacts.
liste_contact ($statut=-1, $source= 'external', $list=0, $code= '')
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source= 'internal', $order= 'position', $option=0, $activeonly=0, $code= '')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contactid into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table= '', $id=null, $format= '', $id_field= '', $fuser=null, $trigkey= '', $fk_user_field= 'fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source= 'external')
Return list of id of contacts of object.
setProject ($projectid)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id)
Change the payments terms.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder= 'ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix= '')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust= 'none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null)
Add objects linked in llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $clause= 'OR', $alsosametype=1, $orderby= 'sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
updateObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '')
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $rowid= '')
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType= '', $trigkey= '')
Set status of an object.
getCanvas ($id=0, $ref= '')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
display_incoterms ()
Return incoterms informations TODO Use a cache for label get.
getIncotermsForPDF ()
Return incoterms informations for pdf display.
setIncoterms ($id_incoterm, $location)
Define incoterms values of current object.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir= '/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir= '/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafieldsline=0, $defaulttpldir= '/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist= '', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist= '', $defaulttpldir= '/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
addThumbs ($file)
Build thumb Move this into files.lib.php.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($trigger_name, $user)
Call trigger based on this instance.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger= '', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update an extra field value for the current object.
showInputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
showOutputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss= '')
Return HTML string to show a field into a page Code very similar with showOutputField of extra fields.
showOptionals ($extrafields, $mode= 'view', $params=null, $keysuffix= '', $keyprefix= '', $onetrtd=0)
Function to show lines of extrafields with output datas.
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere= '')
Load object in memory from the database.
fetchLinesCommon ($morewhere= '')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
Static Public Member Functions
static buildRumNumber ($row_code_client, $row_datec, $row_drum)
Build RUM number for a customer bank account.
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref= '', $ref_ext= '')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static commonReplaceThirdparty (DoliDB $db, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
Private Member Functions
getListInvoices ($amounts=0)
Get invoice list.
Additional Inherited Members
Data Fields inherited from CommonObject
$projet
$note
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
isNull ($info)
Function test if type is null.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare the values to insert.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ()
Function to concat keys of fields.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage withdrawal receipts.
Definition at line 40 of file bonprelevement.class.php.
Constructor & Destructor Documentation
__construct ($db, $filename = '')
Constructor.
Parameters
DoliDB $db Database handler
string $filename Filename of withdraw receipt
Definition at line 84 of file bonprelevement.class.php.
References db.
Member Function Documentation
AddFacture ($facture_id, $client_id, $client_nom, $amount, $code_banque, $code_guichet, $number, $number_key)
Add invoice to withdrawal.
Parameters
int $facture_id id invoice to add
int $client_id id invoice customer
string $client_nom customer name
int $amount amount of invoice
string $code_banque code of bank withdrawal
string $code_guichet code of bank's office
string $number bank account number
string $number_key number key of account number
Returns
int >0 if OK, <0 if KO
Definition at line 129 of file bonprelevement.class.php.
References addline(), db, and dol_syslog().
Referenced by Create().
addline (& $line_id, $client_id, $client_nom, $amount, $code_banque, $code_guichet, $number, $number_key)
Add line to withdrawal.
Parameters
int $line_id id line to add
int $client_id id invoice customer
string $client_nom customer name
int $amount amount of invoice
string $code_banque code of bank withdrawal
string $code_guichet code of bank's office
string $number bank account number
string $number_key number key of account number
Returns
int >0 if OK, <0 if KO
Definition at line 187 of file bonprelevement.class.php.
References $resql, db, and dol_syslog().
Referenced by AddFacture().
AddNotification ($db, $user, $action)
Add a notification.
Parameters
DoliDB $db database handler
int $user notification user
string $action notification action
Returns
int 0 if OK, <0 if KO
Definition at line 1331 of file bonprelevement.class.php.
References db, DeleteNotification(), dol_now(), and dol_syslog().
static buildRumNumber ($row_code_client, $row_datec, $row_drum) static
Build RUM number for a customer bank account.
Parameters
string $row_code_client Customer code (soc.code_client)
int $row_datec Creation date of bank account (rib.datec)
string $row_drum Id of customer bank account (rib.rowid)
Returns
string RUM number
Definition at line 1631 of file bonprelevement.class.php.
Referenced by EnregDestinataireSEPA().
Create ($banque = 0, $agence = 0, $mode = 'real', $format = 'ALL', $executiondate = '')
Create a withdraw TODO delete params banque and agence when not necesary.
Parameters
int $banque dolibarr mysoc bank
int $agence dolibarr mysoc bank office (guichet)
string $mode real=do action, simu=test only
string $format FRST, RCUR or ALL
string $executiondate Date to execute the transfer
Returns
int <0 if KO, nbre of invoice withdrawed if OK
Definition at line 780 of file bonprelevement.class.php.
References $resql, AddFacture(), db, dol_mkdir(), dol_now(), dol_substr(), dol_syslog(), generate(), and print.
delete ($user = null, $notrigger = 0)
Get object and lines from database.
Parameters
User $user Object user that delete
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int >0 if OK, <0 if KO
Definition at line 1142 of file bonprelevement.class.php.
References CommonObject\call_trigger(), db, and dol_print_error().
DeleteNotification ($user, $action)
Delete a notification.
Parameters
int $user notification user
string $action notification action
Returns
int >0 if OK, <0 if KO
Definition at line 1304 of file bonprelevement.class.php.
References db.
Referenced by AddNotification().
DeleteNotificationById ($rowid)
Delete a notification def by id.
Parameters
int $rowid id of notification
Returns
int 0 if OK, <0 if KO
Definition at line 1278 of file bonprelevement.class.php.
References db.
EnregDestinataire ($rowid, $client_nom, $rib_banque, $rib_guichet, $rib_number, $amount, $ref, $facid, $rib_dom = '')
Write recipient of request (customer)
Parameters
int $rowid id of line
string $client_nom name of customer
string $rib_banque code of bank
string $rib_guichet code of bank office
string $rib_number bank account
float $amount amount
string $ref ref of invoice
int $facid id of invoice
string $rib_dom rib domiciliation
Returns
void
Definition at line 1565 of file bonprelevement.class.php.
EnregDestinataireSEPA ($row_code_client, $row_nom, $row_address, $row_zip, $row_town, $row_country_code, $row_cb, $row_cg, $row_cc, $row_somme, $row_ref, $row_idfac, $row_iban, $row_bic, $row_datec, $row_drum, $row_rum)
Write recipient of request (customer)
Parameters
string $row_code_client soc.code_client as code,
string $row_nom pl.client_nom AS name,
string $row_address soc.address AS adr,
string $row_zip soc.zip
string $row_town soc.town
string $row_country_code c.code AS country,
string $row_cb pl.code_banque AS cb, Not used for SEPA
string $row_cg pl.code_guichet AS cg, Not used for SEPA
string $row_cc pl.number AS cc, Not used for SEPA
string $row_somme pl.amount AS somme,
string $row_ref f.ref
string $row_idfac pf.fk_facture AS idfac,
string $row_iban rib.iban_prefix AS iban,
string $row_bic rib.bic AS bic,
string $row_datec rib.datec,
string $row_drum rib.rowid used to generate rum
string $row_rum rib.rum Rum defined on company bank account
Returns
string Return string with SEPA part DrctDbtTxInf
Definition at line 1661 of file bonprelevement.class.php.
References buildRumNumber(), dol_print_date(), dol_string_unaccent(), and dol_trunc().
Referenced by generate().
EnregEmetteur ()
Write sender of request (me)
Returns
void
Definition at line 1728 of file bonprelevement.class.php.
EnregEmetteurSEPA ($configuration, $ladate, $nombre, $total, $CrLf = '\n', $format = 'FRST')
Write sender of request (me).
Note: The tag PmtInf is opened here but closed into caller
Parameters
string $configuration conf
int $ladate Date
int $nombre 0 or 1
float $total Total
string $CrLf End of line character
string $format FRST or RCUR or ALL
Returns
string String with SEPA Sender
Definition at line 1802 of file bonprelevement.class.php.
References $resql, db, dol_print_date(), and dol_string_unaccent().
Referenced by generate().
EnregTotal ($total)
Write end.
Parameters
int $total total amount
Returns
void
Definition at line 1919 of file bonprelevement.class.php.
fetch ($rowid, $ref = '')
Get object and lines from database.
Parameters
int $rowid Id of object to load
string $ref Ref of direct debit
Returns
int >0 if OK, <0 if KO
Definition at line 279 of file bonprelevement.class.php.
References db, dol_syslog(), and note.
generate ($format = 'ALL', $executiondate = '')
Generate a withdrawal file.
Generation Formats:
Europe: SEPA (France: CFONB no more supported, Spain: AEB19 if external module EsAEB is enabled)
Others countries: Warning message File is generated with name this->filename
Parameters
string $format FRST, RCUR or ALL
string $executiondate Date to execute transfer
Returns
int 0 if OK, <0 if KO
SECTION CREATION FICHIER SEPA
SECTION CREATION SEPA FILE
Definition at line 1370 of file bonprelevement.class.php.
References $resql, db, dol_now(), dol_print_date(), dol_string_unaccent(), dol_syslog(), EnregDestinataireSEPA(), and EnregEmetteurSEPA().
Referenced by Create().
getErrorString ($error)
Return error string.
Parameters
int $error Id of error
Returns
string Error string
Definition at line 261 of file bonprelevement.class.php.
getLibStatut ($mode = 0)
Return status label of object.
Parameters
int $mode 0=Label, 1=Picto + label, 2=Picto, 3=Label + Picto
Returns
string Label
Definition at line 1981 of file bonprelevement.class.php.
References LibStatut().
getListInvoices ($amounts = 0) private
Get invoice list.
Parameters
int $amounts If you want to get the amount of the order for each invoice
Returns
array Id of invoices
Definition at line 633 of file bonprelevement.class.php.
References $resql, db, and dol_syslog().
Referenced by set_credite(), and set_infocredit().
getNomUrl ($withpicto = 0, $option = '', $notooltip = 0, $morecss = '', $save_lastsearch_value = -1)
Returns clickable name (with picto)
Parameters
int $withpicto Include picto in link (0=No picto, 1=Include picto into link, 2=Only picto)
string $option On what the link point to ('nolink', ...)
int $notooltip 1=Disable tooltip
string $morecss Add more css on link
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
Returns
string URL of target
Definition at line 1208 of file bonprelevement.class.php.
References img_object().
LibStatut ($statut, $mode = 0)
Return status label for a status.
Parameters
int $statut id statut
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto, 6=Long label + Picto
Returns
string Label
Definition at line 1994 of file bonprelevement.class.php.
References img_picto().
Referenced by getLibStatut().
NbFactureAPrelever ($banque = 0, $agence = 0)
Get number of invoices to withdrawal TODO delete params banque and agence when not necesary.
Parameters
int $banque dolibarr mysoc bank
int $agence dolibarr mysoc agence
Returns
int <O if KO, number of invoices if OK
Definition at line 734 of file bonprelevement.class.php.
References $resql, db, and dol_syslog().
set_credite ()
Set credite and set status of linked invoices.
Still used ??
Returns
int <0 if KO, >=0 if OK
Definition at line 340 of file bonprelevement.class.php.
References db, dol_syslog(), and getListInvoices().
set_infocredit ($user, $date)
Set direct debit order to "credited" status.
Parameters
User $user Id of user
int $date date of action
Returns
int >0 if OK, <0 if KO
Definition at line 421 of file bonprelevement.class.php.
References db, dol_print_date(), dol_syslog(), getListInvoices(), and price2num().
set_infotrans ($user, $date, $method)
Set withdrawal to transmited status.
Parameters
User $user id of user
int $date date of action
string $method method of transmision to bank
Returns
int >0 if OK, <0 if KO
Definition at line 569 of file bonprelevement.class.php.
References db, dol_print_date(), dol_syslog(), dolGetFirstLastname(), and price().
SommeAPrelever ()
Returns amount of withdrawal.
Returns
double Total amount
Definition at line 692 of file bonprelevement.class.php.
References $resql, db, and dol_syslog().
The documentation for this class was generated from the following file:
htdocs/compta/prelevement/class/bonprelevement.class.php