Dolibarr: htdocs/install/inc.php File Reference
inc.php File Reference
File that define environment for support pages.
Functions
conf ($dolibarr_main_document_root)
Load conf file (file must exists)
pHeader ($subtitle, $next, $action= 'set', $param= '', $forcejqueryurl= '', $csstable= 'main-inside')
Show HTML header of install pages.
pFooter ($nonext=0, $setuplang= '', $jscheckfunction= '', $withpleasewait=0)
Print HTML footer of install pages.
dolibarr_install_syslog ($message, $level=LOG_DEBUG)
Log function for install pages.
detect_dolibarr_main_document_root ()
Automatically detect Dolibarr's main document root.
detect_dolibarr_main_data_root ($dolibarr_main_document_root)
Automatically detect Dolibarr's main data root.
detect_dolibarr_main_url_root ()
Automatically detect Dolibarr's main URL root.
parse_database_login ($force_install_databaserootlogin)
Replaces automatic database login by actual value.
parse_database_pass ($force_install_databaserootpass)
Replaces automatic database password by actual value.
Variables
$conf db = new stdClass()
API class for accounts.
Detailed Description
File that define environment for support pages.
Definition in file inc.php.
Function Documentation
conf ($dolibarr_main_document_root) -> setDefaultLang(GETPOST('lang', 'aZ09'))
Load conf file (file must exists)
Parameters
string $dolibarr_main_document_root Root directory of Dolibarr bin files
Returns
int <0 if KO, >0 if OK
Definition at line 268 of file inc.php.
Referenced by modGeneratePassNone\__construct(), modGeneratePassStandard\__construct(), printing_printipp\__construct(), modGeneratePassPerso\__construct(), printing_printgcp\__construct(), User\__construct(), encodedecode_dbpassconf(), User\fetch(), Thirdparties\generateBankAccountDocument(), printing_printgcp\getlistAvailablePrinters(), printing_printgcp\listJobs(), User\send_password(), and printing_printgcp\sendPrintToPrinter().
detect_dolibarr_main_data_root ($dolibarr_main_document_root)
Automatically detect Dolibarr's main data root.
Parameters
string $dolibarr_main_document_root Current main document root
Returns
string
Definition at line 525 of file inc.php.
detect_dolibarr_main_document_root ()
Automatically detect Dolibarr's main document root.
Returns
string
Definition at line 500 of file inc.php.
detect_dolibarr_main_url_root ()
Automatically detect Dolibarr's main URL root.
Returns
string
Definition at line 537 of file inc.php.
dolibarr_install_syslog ($message, $level = LOG_DEBUG)
Log function for install pages.
Parameters
string $message Message
int $level Level of log
Returns
void
Definition at line 489 of file inc.php.
References dol_syslog().
Referenced by migrate_actioncomm_element(), migrate_categorie_association(), migrate_clean_association(), migrate_commande_deliveryaddress(), migrate_commande_expedition(), migrate_commande_livraison(), migrate_contracts_date1(), migrate_contracts_date3(), migrate_contracts_det(), migrate_contracts_open(), migrate_customerorder_shipping(), migrate_delete_old_dir(), migrate_delete_old_files(), migrate_detail_livraison(), migrate_event_assignement(), migrate_event_assignement_contact(), migrate_links_transfert(), migrate_menus(), migrate_mode_reglement(), migrate_modeles(), migrate_paiementfourn_facturefourn(), migrate_paiements(), migrate_paiements_orphelins_1(), migrate_paiements_orphelins_2(), migrate_price_commande(), migrate_price_commande_fournisseur(), migrate_price_contrat(), migrate_price_facture(), migrate_price_propal(), migrate_project_task_actors(), migrate_project_task_time(), migrate_project_user_resp(), migrate_relationship_tables(), migrate_reload_menu(), migrate_reload_modules(), migrate_remise_entity(), migrate_remise_except_entity(), migrate_rename_directories(), migrate_reset_blocked_log(), migrate_restore_missing_links(), migrate_shipping_delivery(), migrate_shipping_delivery2(), migrate_stocks(), migrate_user_rights_entity(), and migrate_usergroup_rights_entity().
parse_database_login ($force_install_databaserootlogin)
Replaces automatic database login by actual value.
Parameters
string $force_install_databaserootlogin Login
Returns
string
Definition at line 568 of file inc.php.
parse_database_pass ($force_install_databaserootpass)
Replaces automatic database password by actual value.
Parameters
string $force_install_databaserootpass Password
Returns
string
Definition at line 579 of file inc.php.
pFooter ($nonext = 0, $setuplang = '', $jscheckfunction = '', $withpleasewait = 0)
Print HTML footer of install pages.
Parameters
integer $nonext 1=No button "Next step", 2=Show button but disabled with a link to enable
string $setuplang Language code
string $jscheckfunction Add a javascript check function
integer $withpleasewait Add also please wait tags
Returns
void
Definition at line 432 of file inc.php.
References print.
pHeader ($subtitle, $next, $action = 'set', $param = '', $forcejqueryurl = '', $csstable = 'main-inside')
Show HTML header of install pages.
Parameters
string $subtitle Title
string $next Next
string $action Action code ('set' or 'upgrade')
string $param Param
string $forcejqueryurl Set jquery relative URL (must end with / if defined)
string $csstable Css for table
Returns
void
Definition at line 353 of file inc.php.
References print.
Variable Documentation
DoliDB db = new stdClass()
API class for accounts.
API class for supplier invoices.
protected
Definition at line 54 of file inc.php.
Referenced by DolQueryCollector\__construct(), Login\__construct(), modHRM\__construct(), modBlockedLog\__construct(), GenericObject\__construct(), ProjectStats\__construct(), TaskStats\__construct(), modCashDesk\__construct(), modMargin\__construct(), modModuleBuilder\__construct(), modWebServices\__construct(), modWebServicesClient\__construct(), modCollab\__construct(), modDav\__construct(), modEmailCollector\__construct(), modExpenseReport\__construct(), modGravatar\__construct(), modDynamicPrices\__construct(), modNotification\__construct(), modPayBox\__construct(), modReception\__construct(), modSocialNetworks\__construct(), modStripe\__construct(), modTicket\__construct(), modWebsite\__construct(), MembersTypes\__construct(), modAccounting\__construct(), modCategorie\__construct(), modAsset\__construct(), modCron\__construct(), modDebugBar\__construct(), modDeplacement\__construct(), modECM\__construct(), modGeoIPMaxmind\__construct(), modLdap\__construct(), modLoan\__construct(), modOpenSurvey\__construct(), modPaypal\__construct(), modTakePos\__construct(), modSyslog\__construct(), modWorkflow\__construct(), pdf_paiement\__construct(), Auth\__construct(), modApi\__construct(), modBom\__construct(), modBookmark\__construct(), modClickToDial\__construct(), ActionsContactCardDefault\__construct(), modExport\__construct(), modExternalRss\__construct(), modFTP\__construct(), modImport\__construct(), modLabel\__construct(), modIncoterm\__construct(), modMailmanSpip\__construct(), modMultiCurrency\__construct(), modProductBatch\__construct(), modResource\__construct(), modUser\__construct(), modVariants\__construct(), FormAdmin\__construct(), modMyModule\__construct(), ActionsCardIndividual\__construct(), Client\__construct(), modBarcode\__construct(), modContrat\__construct(), Setup\__construct(), modDocumentGeneration\__construct(), modExternalSite\__construct(), modFckeditor\__construct(), modFournisseur\__construct(), modMailing\__construct(), ActionsAdherentCardDefault\__construct(), mailing_mailinglist_mymodule_myobject\__construct(), ActionsCardCompany\__construct(), html_cerfafr\__construct(), modComptabilite\__construct(), modDon\__construct(), modFacture\__construct(), modOauth\__construct(), modPrelevement\__construct(), modPrinting\__construct(), modReceiptPrinter\__construct(), modService\__construct(), modStock\__construct(), pdf_squille\__construct(), InterfaceTicketEmail\__construct(), InterfaceIFTTT\__construct(), FormWebsite\__construct(), Utils\__construct(), Subscriptions\__construct(), modBanque\__construct(), modExpedition\__construct(), modHoliday\__construct(), modPropale\__construct(), modProjet\__construct(), modSociete\__construct(), modTax\__construct(), CdavLib\__construct(), Members\__construct(), Fournisseur\__construct(), modAdherent\__construct(), modFicheinter\__construct(), modProduct\__construct(), modSupplierProposal\__construct(), FormAdvTargetEmailing\__construct(), mailing_thirdparties_services_expired\__construct(), mailing_thirdparties\__construct(), modAgenda\__construct(), modCommande\__construct(), modDataPolicy\__construct(), modSalaries\__construct(), TraceableDB\__construct(), Boms\__construct(), FormEcm\__construct(), CoreObject\__construct(), Invoices\__construct(), FormContract\__construct(), FormCron\__construct(), FormIntervention\__construct(), FormPropal\__construct(), FormSocialContrib\__construct(), Warehouses\__construct(), Documents\__construct(), Proposals\__construct(), Thirdparties\__construct(), mailing_advthirdparties\__construct(), Users\__construct(), mailing_xinputfile\__construct(), mailing_xinputuser\__construct(), Orders\__construct(), Donations\__construct(), BankAccounts\__construct(), SupplierOrders\__construct(), FormMargin\__construct(), Products\__construct(), AgendaEvents\__construct(), Supplierproposals\__construct(), InterfaceStripe\__construct(), ExpenseReports\__construct(), FormActions\__construct(), FormBank\__construct(), FormBarCode\__construct(), FormProjets\__construct(), StockMovements\__construct(), BordereauChequeBlochet\__construct(), Contacts\__construct(), Shipments\__construct(), SupplierInvoices\__construct(), FormCompany\__construct(), Tasks\__construct(), Projects\__construct(), DolibarrApi\__construct(), RejetPrelevement\__construct(), PrintingDriver\__construct(), MyModuleApi\__construct(), mailing_pomme\__construct(), Contracts\__construct(), box_graph_invoices_permonth\__construct(), box_graph_invoices_supplier_permonth\__construct(), box_graph_orders_permonth\__construct(), box_graph_orders_supplier_permonth\__construct(), box_graph_propales_permonth\__construct(), ActionsCardService\__construct(), Interfaces\__construct(), SalariesStats\__construct(), TicketStats\__construct(), MailingTargets\__construct(), pdf_timespent\__construct(), ExpeditionLineBatch\__construct(), ActionsCardProduct\__construct(), FormProduct\__construct(), PriceParser\__construct(), MenuManager\__construct(), mailing_contacts1\__construct(), mailing_example\__construct(), LignePrelevement\__construct(), BlockedLogAuthority\__construct(), box_bookmarks\__construct(), ExpenseReportStats\__construct(), DeplacementStats\__construct(), FormAccounting\__construct(), InterfaceMyModuleTriggers\__construct(), pdf_ban\__construct(), box_graph_product_distribution\__construct(), box_project\__construct(), BankCateg\__construct(), FormFile\__construct(), FormOther\__construct(), AdherentStats\__construct(), mailing_fraise\__construct(), box_factures\__construct(), box_factures_fourn_imp\__construct(), box_services_expired\__construct(), box_supplier_orders\__construct(), pdf_sepamandate\__construct(), ReceptionStats\__construct(), ActionsStripeconnect\__construct(), Cpaiement\__construct(), Tickets\__construct(), box_activity\__construct(), box_contracts\__construct(), box_factures_fourn\__construct(), box_ficheinter\__construct(), box_fournisseurs\__construct(), box_lastlogin\__construct(), FactureStats\__construct(), doc_generic_odt\__construct(), box_birthdays_members\__construct(), box_clients\__construct(), box_commandes\__construct(), box_birthdays\__construct(), box_actions\__construct(), box_propales\__construct(), box_services_contracts\__construct(), box_task\__construct(), FichinterStats\__construct(), DoliDBMysqli\__construct(), FormResource\__construct(), CommandeStats\__construct(), box_factures_imp\__construct(), box_goodcustomers\__construct(), box_produits\__construct(), box_members\__construct(), CommonDocGenerator\__construct(), DonationStats\__construct(), AntiVir\__construct(), ExpeditionStats\__construct(), Interventions\__construct(), DoliDBMssql\__construct(), UserBankAccount\__construct(), PropaleStats\__construct(), modGeneratePassNone\__construct(), modGeneratePassStandard\__construct(), box_comptes\__construct(), box_contacts\__construct(), box_external_rss\__construct(), box_prospect\__construct(), ProductAttributeValue\__construct(), ProductCombination2ValuePair\__construct(), ActionsDatapolicy\__construct(), box_produits_alerte_stock\__construct(), Productbatch\__construct(), DoliDBSqlite3\__construct(), ProductAttribute\__construct(), doc_generic_reception_odt\__construct(), Categories\__construct(), doc_generic_user_odt\__construct(), Import\__construct(), Propalmergepdfproduct\__construct(), RssParser\__construct(), CompanyBankAccount\__construct(), doc_generic_proposal_odt\__construct(), Canvas\__construct(), ActionsMyModule\__construct(), Link\__construct(), doc_generic_product_odt\__construct(), doc_generic_stock_odt\__construct(), printing_printipp\__construct(), doc_generic_supplier_proposal_odt\__construct(), doc_generic_usergroup_odt\__construct(), Ctyperesource\__construct(), HookManager\__construct(), PriceExpression\__construct(), DoliDBPgsql\__construct(), doc_generic_contract_odt\__construct(), ExportTsv\__construct(), doc_generic_invoice_odt\__construct(), Cchargesociales\__construct(), Ctypent\__construct(), doc_generic_order_odt\__construct(), doc_generic_shipment_odt\__construct(), ExportCsv\__construct(), Export\__construct(), AccountancySystem\__construct(), MailmanSpip\__construct(), Dolresource\__construct(), CUnits\__construct(), Stripe\__construct(), CActionComm\__construct(), PriceGlobalVariable\__construct(), PaiementFourn\__construct(), PaymentTerm\__construct(), RemiseCheque\__construct(), ExportExcel\__construct(), ExportExcel2007\__construct(), printing_printgcp\__construct(), modGeneratePassPerso\__construct(), CommActionRapport\__construct(), ExportExcel2007new\__construct(), pdf_beluga\__construct(), ProductStockEntrepot\__construct(), Cstate\__construct(), Livraison\__construct(), AccountingJournal\__construct(), Ccountry\__construct(), Localtax\__construct(), ProductCombination\__construct(), AssetType\__construct(), FormSms\__construct(), AccountancyExport\__construct(), doc_generic_project_odt\__construct(), doc_generic_task_odt\__construct(), Comment\__construct(), AdvanceTargetingMailing\__construct(), DolibarrTriggers\__construct(), PriceGlobalVariableUpdater\__construct(), BonPrelevement\__construct(), ChargeSociales\__construct(), Tva\__construct(), Productcustomerprice\__construct(), Mailing\__construct(), Form\__construct(), MouvementStock\__construct(), ActionsTicket\__construct(), Bookmark\__construct(), Productlot\__construct(), PaymentDonation\__construct(), Notify\__construct(), PaymentSocialContribution\__construct(), Menubase\__construct(), PaymentExpenseReport\__construct(), ImportCsv\__construct(), Deplacement\__construct(), Subscription\__construct(), PaymentSalary\__construct(), ImportXlsx\__construct(), AdherentType\__construct(), Loan\__construct(), PaymentLoan\__construct(), MultiCurrency\__construct(), Website\__construct(), Reception\__construct(), CashControl\__construct(), LoanSchedule\__construct(), Conf\__construct(), PaymentVarious\__construct(), Fiscalyear\__construct(), FormTicket\__construct(), Entrepot\__construct(), UserGroup\__construct(), Establishment\__construct(), FactureRec\__construct(), Don\__construct(), EcmFiles\__construct(), DiscountAbsolute\__construct(), EcmDirectory\__construct(), CommonStickerGenerator\__construct(), ProductFournisseur\__construct(), Opensurveysondage\__construct(), EmailCollectorFilter\__construct(), CommandeFournisseurDispatch\__construct(), ActionCommReminder\__construct(), Cronjob\__construct(), pdf_espadon\__construct(), pdf_stdmovement\__construct(), ModeleBoxes\__construct(), pdf_rouget\__construct(), pdf_merou\__construct(), pdf_soleil\__construct(), pdf_typhon\__construct(), pdf_baleine\__construct(), pdf_canelle\__construct(), pdf_aurore\__construct(), pdf_cornas\__construct(), pdf_muscadet\__construct(), FormMail\__construct(), pdf_standard\__construct(), BlockedLog\__construct(), Task\__construct(), pdf_strato\__construct(), WebsitePage\__construct(), pdf_azur\__construct(), pdf_cyan\__construct(), pdf_einstein\__construct(), pdf_eratosthene\__construct(), AccountancyCategory\__construct(), dolReceiptPrinter\__construct(), Events\__construct(), Fichinter\__construct(), pdf_crabe\__construct(), pdf_sponge\__construct(), BookKeeping\__construct(), AccountingAccount\__construct(), ExpenseReport\__construct(), EmailCollectorAction\__construct(), Paiement\__construct(), Contact\__construct(), EmailSenderProfile\__construct(), Holiday\__construct(), Project\__construct(), BOM\__construct(), Expedition\__construct(), Asset\__construct(), SocieteAccount\__construct(), ExtraFields\__construct(), EmailCollector\__construct(), Inventory\__construct(), Contrat\__construct(), User\__construct(), MyObject\__construct(), SupplierProposal\__construct(), CompanyPaymentMode\__construct(), Ticket\__construct(), Categorie\__construct(), CommandeFournisseur\__construct(), Account\__construct(), Adherent\__construct(), Propal\__construct(), Commande\__construct(), ActionComm\__construct(), FactureFournisseur\__construct(), Facture\__construct(), DolibarrModules\__construct(), Product\__construct(), Societe\__construct(), CurrencyRate\__construct(), CommonInvoiceLine\__construct(), BOMLine\__construct(), LivraisonLigne\__construct(), FichinterLigne\__construct(), AccountLine\__construct(), ExpenseReportLine\__construct(), ExpeditionLigne\__construct(), ContratLigne\__construct(), SupplierInvoiceLine\__construct(), SupplierProposalLine\__construct(), CommandeFournisseurLigne\__construct(), PropaleLigne\__construct(), OrderLine\__construct(), ProductCombination2ValuePair\__toString(), DolibarrModules\_active(), MouvementStock\_create(), MouvementStock\_createSubProduct(), Product\_get_stats(), Stats\_getAllByProduct(), Stats\_getAllByYear(), Stats\_getAmountByMonth(), Stats\_getAverageByMonth(), Stats\_getNbByMonth(), Stats\_getNbByYear(), DolibarrModules\_init(), AdherentType\_load_ldap_info(), Contact\_load_ldap_info(), UserGroup\_load_ldap_info(), User\_load_ldap_info(), Product\_log_price(), pdf_merou\_pagehead(), pdf_standard\_pagehead(), pdf_squille\_pagehead(), pdf_espadon\_pagehead(), pdf_rouget\_pagehead(), pdf_muscadet\_pagehead(), pdf_cornas\_pagehead(), pdf_einstein\_pagehead(), pdf_aurore\_pagehead(), pdf_eratosthene\_pagehead(), pdf_azur\_pagehead(), pdf_cyan\_pagehead(), pdf_crabe\_pagehead(), pdf_sponge\_pagehead(), CommActionRapport\_pages(), DolibarrModules\_remove(), RejetPrelevement\_send_email(), pdf_einstein\_tableau_info(), pdf_aurore\_tableau_info(), pdf_azur\_tableau_info(), pdf_crabe\_tableau_info(), pdf_crabe\_tableau_versements(), pdf_canelle\_tableau_versements(), DolibarrModules\_unactive(), AccountingAccount\account_activate(), AccountingAccount\account_desactivate(), Reception\activ_delivery_method(), Expedition\activ_delivery_method(), Contrat\activateAll(), ContratLigne\active_line(), Societe\add_commercial(), Product\add_fournisseur(), SupplierProposal\add_product(), Propal\add_product(), Commande\add_product(), Product\add_sousproduit(), Adherent\add_to_abo(), MailmanSpip\add_to_mailman(), mailing_thirdparties\add_to_target(), mailing_thirdparties_services_expired\add_to_target(), mailing_mailinglist_mymodule_myobject\add_to_target(), mailing_pomme\add_to_target(), MailingTargets\add_to_target(), mailing_fraise\add_to_target(), mailing_contacts1\add_to_target(), mailing_advthirdparties\add_to_target_spec(), Categorie\add_type(), Account\add_url_line(), Contacts\addCategory(), Thirdparties\addCategory(), CoreObject\addChild(), Opensurveysondage\addComment(), DoliDBSqlite3\addCustomFunction(), BonPrelevement\AddFacture(), Societe\AddFournisseurInCategory(), BonPrelevement\addline(), SupplierProposal\addline(), Account\addline(), Propal\addline(), BankAccounts\addLine(), Livraison\addline(), FactureRec\addline(), Reception\addline(), Expedition\addline(), Fichinter\addline(), Commande\addline(), Contrat\addline(), CommandeFournisseur\addline(), FactureFournisseur\addline(), ExpenseReport\addline(), Facture\addline(), Expedition\addline_batch(), BankAccounts\addLink(), Holiday\addLogCP(), BonPrelevement\AddNotification(), SupplierInvoices\addPayment(), Localtax\addPayment(), Tva\addPayment(), Invoices\addPayment(), Invoices\addPaymentDistributed(), PaymentLoan\addPaymentToBank(), PaymentDonation\addPaymentToBank(), PaymentExpenseReport\addPaymentToBank(), PaymentSocialContribution\addPaymentToBank(), Paiement\addPaymentToBank(), dolReceiptPrinter\addPrinter(), MultiCurrency\addRate(), UserGroup\addrights(), User\addrights(), Thirdparties\addSupplierCategory(), Task\addTimeSpent(), FormAdvTargetEmailing\advMultiselectarray(), FormAdvTargetEmailing\advMultiselectarraySelllist(), TraceableDB\affected_rows(), DoliDBMysqli\affected_rows(), DoliDBMssql\affected_rows(), DoliDBSqlite3\affected_rows(), Categorie\already_exists(), modBlockedLog\alreadyUsed(), BlockedLog\alreadyUsed(), ExpenseReport\applyOffset(), Holiday\approve(), CommandeFournisseur\approve(), Contrat\array_detail(), ActionsAdherentCardCommon\assign_post(), ActionsContactCardCommon\assign_post(), ActionsCardService\assign_values(), ActionsCardProduct\assign_values(), ActionsCardCompany\assign_values(), ActionsCardCommon\assign_values(), ActionsAdherentCardCommon\assign_values(), ActionsContactCardCommon\assign_values(), Ticket\assignUser(), Commande\availability(), Propal\availability(), TraceableDB\begin(), DoliDBMssql\begin(), Import\build_example_file(), ActionComm\build_exportfile(), Export\build_file(), Export\build_filterField(), Documents\builddoc(), TaskStats\buildWhere(), ProjectStats\buildWhere(), CommandeFournisseur\calcAndSetStatusDispatch(), CommonInvoice\calculate_date_lim_reglement(), MouvementStock\calculateBalanceForProductBefore(), EcmDirectory\call_trigger(), Account\can_be_deleted(), Commande\cancel(), CommandeFournisseur\Cancel(), Stripe\cardStripe(), EcmDirectory\changeNbOfFiles(), Product\check_barcode(), Societe\check_codeclient(), Societe\check_codefournisseur(), Facture\checkProgressLine(), AccountingAccount\checkUsage(), CommandeFournisseur\classifyBilled(), Propal\classifyBilled(), Commande\classifyBilled(), Commande\classifyUnBilled(), MailingTargets\clear_target(), Product\clone_associations(), Product\clone_fournisseurs(), Product\clone_price(), DoliDBMssql\close(), DoliDBMysqli\close(), DoliDBSqlite3\close(), DoliDBPgsql\close(), TraceableDB\close(), Ticket\close(), ContratLigne\close_line(), Contrat\closeAll(), Commande\cloture(), SupplierProposal\cloture(), Propal\cloture(), DolQueryCollector\collect(), CommandeFournisseur\commande(), DoliDBMssql\commit(), TraceableDB\commit(), Website\componentSelectLang(), DoliDBMssql\connect(), DoliDBSqlite3\connect(), TraceableDB\connect(), DoliDBPgsql\connect(), Form\constructProductListOption(), Societe\contact_array(), Societe\contact_array_objects(), Societe\contact_get_property(), Societe\contact_property_array(), Categorie\containing(), Categorie\containsObject(), ProductCombination\copyAll(), Ticket\copyFilesForTicket(), Product\correct_stock(), Product\correct_stock_batch(), Holiday\countActiveUsers(), Holiday\countActiveUsersWithoutCP(), ProductAttribute\countChildProducts(), ProductAttribute\countChildValues(), ProductCombination\countNbOfCombinationForFkProductParent(), Mailing\countNbOfTargets(), BankCateg\create(), Cpaiement\create(), Productbatch\create(), Link\create(), Propalmergepdfproduct\create(), UserBankAccount\create(), Ctyperesource\create(), PriceExpression\create(), Cchargesociales\create(), Ctypent\create(), Dolresource\create(), CompanyBankAccount\create(), CUnits\create(), PriceGlobalVariable\create(), RejetPrelevement\create(), PaymentTerm\create(), ProductCombination2ValuePair\create(), ProductStockEntrepot\create(), Cstate\create(), Localtax\create(), Ccountry\create(), AssetType\create(), Livraison\create(), Comment\create(), Tva\create(), PriceGlobalVariableUpdater\create(), Productcustomerprice\create(), Productlot\create(), PaymentDonation\create(), PaymentSocialContribution\create(), ExpeditionLineBatch\create(), PaymentExpenseReport\create(), Mailing\create(), Menubase\create(), PaymentLoan\create(), Subscription\create(), AdvanceTargetingMailing\create(), AdherentType\create(), Deplacement\create(), LoanSchedule\create(), Website\create(), CashControl\create(), MultiCurrency\create(), FactureRec\create(), EcmFiles\create(), Fiscalyear\create(), Establishment\create(), EcmDirectory\create(), Opensurveysondage\create(), Entrepot\create(), AccountancySystem\create(), Cronjob\create(), ProductAttribute\create(), CommandeFournisseurDispatch\create(), Task\create(), Bookmark\create(), RemiseCheque\create(), AccountancyCategory\create(), Events\create(), PaiementFourn\create(), ProductAttributeValue\create(), BookKeeping\create(), Loan\create(), ExpenseReport\create(), Project\create(), ChargeSociales\create(), Reception\create(), Fichinter\create(), BlockedLogAuthority\create(), DiscountAbsolute\create(), Contact\create(), ProductCombination\create(), AccountingAccount\create(), Paiement\create(), Import\create(), Holiday\create(), Expedition\create(), ActionComm\create(), ExtraFields\create(), CoreObject\create(), FactureFournisseur\create(), Facture\create(), Categorie\create(), PaymentVarious\create(), Ticket\create(), PaymentSalary\create(), Don\create(), Adherent\create(), Product\create(), Societe\create(), Account\create(), UserGroup\create(), Export\create(), CurrencyRate\create(), BlockedLog\create(), Commande\create(), BonPrelevement\Create(), SupplierProposal\create(), Propal\create(), Contrat\create(), User\create(), CommandeFournisseur\create(), Expedition\create_delivery(), User\create_from_contact(), User\create_from_member(), Societe\create_from_member(), Livraison\create_from_sending(), Societe\create_individual(), ExtraFields\create_label(), Livraison\create_line(), Expedition\create_line(), MouvementStock\createBatch(), Fournisseur\CreateCategory(), CommonObject\createCommon(), Thirdparties\createCompanyBankAccount(), Holiday\createCPusers(), modMultiCurrency\createFirstCurrency(), EmailSenderProfile\createFromClone(), EmailCollectorFilter\createFromClone(), EmailCollectorAction\createFromClone(), Asset\createFromClone(), SocieteAccount\createFromClone(), BOM\createFromClone(), Inventory\createFromClone(), EmailCollector\createFromClone(), CompanyPaymentMode\createFromClone(), MyObject\createFromClone(), Mailing\createFromClone(), BankCateg\createFromClone(), ExpenseReport\createFromClone(), Productbatch\createFromClone(), Cchargesociales\createFromClone(), PaymentTerm\createFromClone(), WebsitePage\createFromClone(), Ctyperesource\createFromClone(), PaymentDonation\createFromClone(), PaymentExpenseReport\createFromClone(), ProductStockEntrepot\createFromClone(), Productlot\createFromClone(), PaymentSocialContribution\createFromClone(), CommandeFournisseurDispatch\createFromClone(), Website\createFromClone(), ActionComm\createFromClone(), Propalmergepdfproduct\createFromClone(), EcmFiles\createFromClone(), Cronjob\createFromClone(), Productcustomerprice\createFromClone(), Ticket\createFromClone(), Facture\createFromClone(), Commande\createFromClone(), SupplierProposal\createFromClone(), Fichinter\createFromClone(), Propal\createFromClone(), Project\createFromClone(), BookKeeping\createFromClone(), CommandeFournisseur\createFromClone(), Task\createFromClone(), Contrat\createFromClone(), FactureFournisseur\createFromClone(), Facture\createFromCurrent(), Facture\createFromOrder(), Commande\createFromProposal(), Invoices\createInvoiceFromOrder(), Orders\createOrderFromProposal(), Stripe\createPaymentStripe(), SupplierProposal\createPriceFournisseur(), createProductOrService(), Thirdparties\createSocieteAccount(), BookKeeping\createStd(), Members\createSubscription(), Ticket\createTicketMessage(), Contacts\createUser(), Stripe\customerStripe(), AccountLine\dateo_change(), AccountLine\datev_change(), TraceableDB\DDLAddField(), TraceableDB\DDLCreateDb(), DoliDBMssql\DDLCreateDb(), TraceableDB\DDLCreateTable(), TraceableDB\DDLCreateUser(), TraceableDB\DDLDescTable(), TraceableDB\DDLDropField(), TraceableDB\DDLDropTable(), TraceableDB\DDLGetConnectId(), TraceableDB\DDLInfoTable(), TraceableDB\DDLListTables(), DoliDBMssql\DDLListTables(), DoliDBPgsql\DDLListTables(), TraceableDB\DDLUpdateField(), TraceableDB\decrypt(), Societe\del_commercial(), Product\del_sousproduit(), Adherent\del_to_abo(), MailmanSpip\del_to_mailman(), Categorie\del_type(), ProductAttribute\delete(), ProductAttributeValue\delete(), BankCateg\delete(), Subscriptions\delete(), MembersTypes\delete(), AssetType\delete(), ChargeSociales\delete(), PriceGlobalVariable\delete(), Members\delete(), AdherentType\delete(), Fiscalyear\delete(), Loan\delete(), PaymentVarious\delete(), ProductCombination\delete(), PriceGlobalVariableUpdater\delete(), Cstate\delete(), DiscountAbsolute\delete(), Establishment\delete(), Productbatch\delete(), CompanyBankAccount\delete(), PaymentSalary\delete(), Ctypent\delete(), Events\delete(), Localtax\delete(), Ccountry\delete(), Comment\delete(), Entrepot\delete(), Subscription\delete(), RemiseCheque\delete(), Deplacement\delete(), Cchargesociales\delete(), Cpaiement\delete(), Tva\delete(), Import\delete(), PriceExpression\delete(), CoreObject\delete(), MultiCurrency\delete(), BankAccounts\delete(), PaymentDonation\delete(), PaymentExpenseReport\delete(), PaymentTerm\delete(), LoanSchedule\delete(), PaymentLoan\delete(), Opensurveysondage\delete(), Ctyperesource\delete(), Link\delete(), WebsitePage\delete(), EcmDirectory\delete(), ProductStockEntrepot\delete(), PaymentSocialContribution\delete(), AccountancyCategory\delete(), Propalmergepdfproduct\delete(), Productlot\delete(), CUnits\delete(), Menubase\delete(), AccountingAccount\delete(), Dolresource\delete(), CommandeFournisseurDispatch\delete(), Mailing\delete(), Task\delete(), Website\delete(), AdvanceTargetingMailing\delete(), ExtraFields\delete(), Paiement\delete(), Categorie\delete(), Don\delete(), Project\delete(), UserGroup\delete(), Livraison\delete(), FactureRec\delete(), EcmFiles\delete(), Cronjob\delete(), ActionComm\delete(), Export\delete(), Productcustomerprice\delete(), Adherent\delete(), Reception\delete(), Ticket\delete(), CurrencyRate\delete(), Fichinter\delete(), Contact\delete(), Holiday\delete(), Account\delete(), User\delete(), ExpenseReport\delete(), FactureFournisseur\delete(), Product\delete(), Contrat\delete(), BonPrelevement\delete(), Expedition\delete(), BookKeeping\delete(), Societe\delete(), FactureLigneRec\delete(), AccountLine\delete(), CommandeFournisseur\delete(), Facture\delete(), SupplierProposal\delete(), ExpeditionLigne\delete(), Propal\delete(), SupplierInvoiceLine\delete(), SupplierProposalLine\delete(), Commande\delete(), CommandeFournisseurLigne\delete(), PropaleLigne\delete(), OrderLine\delete(), FactureLigne\delete(), DolibarrModules\delete_boxes(), Propalmergepdfproduct\delete_by_file(), Propalmergepdfproduct\delete_by_product(), DolibarrModules\delete_const(), DolibarrModules\delete_cronjobs(), DolibarrModules\delete_dirs(), ExtraFields\delete_label(), DolibarrModules\delete_menus(), DolibarrModules\delete_module_parts(), DolibarrModules\delete_permissions(), DolibarrModules\delete_tabs(), Mailing\delete_targets(), AccountLine\delete_urls(), ProductAttributeValue\deleteByFkAttribute(), ProductCombination2ValuePair\deleteByFkCombination(), ProductCombination\deleteByFkProductParent(), BookKeeping\deleteByImportkey(), BookKeeping\deleteByYearAndJournal(), Contacts\deleteCategory(), Thirdparties\deleteCategory(), Opensurveysondage\deleteComment(), CommonObject\deleteCommon(), Thirdparties\deleteCompanyBankAccount(), AccountancyCategory\deleteCptCat(), Holiday\deleteCPuser(), Livraison\deleteline(), SupplierProposal\deleteline(), Propal\deleteline(), Expedition\deleteline(), FichinterLigne\deleteline(), Contrat\deleteline(), CommandeFournisseur\deleteline(), FactureFournisseur\deleteline(), ExpenseReport\deleteline(), Commande\deleteline(), Facture\deleteline(), CommonObject\deleteLineCommon(), BookKeeping\deleteMvtNum(), BonPrelevement\DeleteNotification(), BonPrelevement\DeleteNotificationById(), dolReceiptPrinter\deletePrinter(), Thirdparties\deleteSupplierCategory(), Project\deleteTasks(), Product\delMultiLangs(), UserGroup\delrights(), User\delrights(), Task\delTimeSpent(), Commande\demand_reason(), Propal\demand_reason(), Facture\demande_prelevement(), Facture\demande_prelevement_delete(), Reception\disable_delivery_method(), Expedition\disable_delivery_method(), CommandeFournisseur\dispatchProduct(), AccountancyCategory\display(), Societe\display_rib(), ActionsDatapolicy\doActions(), EmailCollector\doCollectOneCollector(), MyObject\doScheduledJob(), BOM\doScheduledJob(), pdf_eratosthene\drawInfoTable(), pdf_cyan\drawInfoTable(), pdf_sponge\drawInfoTable(), pdf_sponge\drawPaymentsTable(), FormCompany\effectif_array(), TraceableDB\encrypt(), TraceableDB\endTracing(), BonPrelevement\EnregEmetteurSEPA(), DoliDBMysqli\errno(), TraceableDB\errno(), DoliDBSqlite3\errno(), DoliDBPgsql\errno(), TraceableDB\error(), DoliDBMysqli\error(), DoliDBPgsql\error(), TraceableDB\escape(), DoliDBMysqli\escape(), BookKeeping\export_bookkeping(), Website\exportWebSite(), LignePrelevement\fetch(), ProductAttributeValue\fetch(), ProductAttribute\fetch(), AccountancySystem\fetch(), CActionComm\fetch(), PaiementFourn\fetch(), RemiseCheque\fetch(), AccountingJournal\fetch(), ProductCombination\fetch(), ChargeSociales\fetch(), Bookmark\fetch(), Loan\fetch(), UserGroup\fetch(), DiscountAbsolute\fetch(), BankCateg\fetch(), ModeleBoxes\fetch(), PriceExpression\fetch(), BlockedLogAuthority\fetch(), Productbatch\fetch(), PriceGlobalVariable\fetch(), UserBankAccount\fetch(), AccountingAccount\fetch(), Paiement\fetch(), WebsitePage\fetch(), Ctyperesource\fetch(), PriceGlobalVariableUpdater\fetch(), Cstate\fetch(), Comment\fetch(), Cchargesociales\fetch(), Cpaiement\fetch(), Ctypent\fetch(), CUnits\fetch(), ProductStockEntrepot\fetch(), Ccountry\fetch(), Propalmergepdfproduct\fetch(), PaymentTerm\fetch(), Subscription\fetch(), Dolresource\fetch(), PaymentVarious\fetch(), PaymentExpenseReport\fetch(), PaymentLoan\fetch(), AdvanceTargetingMailing\fetch(), PaymentDonation\fetch(), LoanSchedule\fetch(), Mailing\fetch(), PaymentSalary\fetch(), Opensurveysondage\fetch(), Productlot\fetch(), Website\fetch(), CompanyBankAccount\fetch(), Fiscalyear\fetch(), PaymentSocialContribution\fetch(), Localtax\fetch(), Establishment\fetch(), Categorie\fetch(), Events\fetch(), Task\fetch(), User\fetch(), AccountancyCategory\fetch(), Tva\fetch(), CommandeFournisseur\fetch(), CommandeFournisseurDispatch\fetch(), Deplacement\fetch(), Productcustomerprice\fetch(), AssetType\fetch(), Livraison\fetch(), BonPrelevement\fetch(), Import\fetch(), AdherentType\fetch(), Cronjob\fetch(), Menubase\fetch(), Link\fetch(), EcmFiles\fetch(), EcmDirectory\fetch(), RejetPrelevement\fetch(), Holiday\fetch(), Reception\fetch(), FactureRec\fetch(), Entrepot\fetch(), Fichinter\fetch(), Project\fetch(), Ticket\fetch(), Expedition\fetch(), FactureFournisseur\fetch(), MouvementStock\fetch(), ActionComm\fetch(), Contrat\fetch(), BookKeeping\fetch(), Don\fetch(), BlockedLog\fetch(), Contact\fetch(), Export\fetch(), CurrencyRate\fetch(), Account\fetch(), SupplierProposal\fetch(), Adherent\fetch(), Societe\fetch(), Facture\fetch(), Propal\fetch(), FichinterLigne\fetch(), Commande\fetch(), AccountLine\fetch(), FactureLigneRec\fetch(), Product\fetch(), ExpenseReportLine\fetch(), ExpeditionLigne\fetch(), ContratLigne\fetch(), SupplierInvoiceLine\fetch(), SupplierProposalLine\fetch(), CommandeFournisseurLigne\fetch(), PropaleLigne\fetch(), OrderLine\fetch(), FactureLigne\fetch(), Productcustomerprice\fetch_all(), Cronjob\fetch_all(), Dolresource\fetch_all(), Productcustomerprice\fetch_all_log(), Dolresource\fetch_all_resources(), Dolresource\fetch_all_used(), TraceableDB\fetch_array(), AdvanceTargetingMailing\fetch_by_element(), AdvanceTargetingMailing\fetch_by_mailing(), Propalmergepdfproduct\fetch_by_product(), User\fetch_clicktodial(), Reception\fetch_delivery_methods(), Expedition\fetch_delivery_methods(), Dolresource\fetch_element_resource(), CommandeFournisseur\fetch_lines(), Opensurveysondage\fetch_lines(), FactureRec\fetch_lines(), FactureFournisseur\fetch_lines(), Contrat\fetch_lines(), Livraison\fetch_lines(), ExpenseReport\fetch_lines(), Fichinter\fetch_lines(), Expedition\fetch_lines(), Facture\fetch_lines(), Propal\fetch_lines(), Commande\fetch_lines(), Adherent\fetch_login(), Adherent\fetch_name(), ExtraFields\fetch_name_optionals_label(), TraceableDB\fetch_object(), Product\fetch_prod_arbo(), ProductFournisseur\fetch_product_fournisseur_price(), TraceableDB\fetch_row(), Adherent\fetch_subscriptions(), PaiementFourn\fetch_thirdparty(), Paiement\fetch_thirdparty(), ActionComm\fetch_userassigned(), ExpenseReport\fetch_users_approver_expensereport(), Holiday\fetch_users_approver_holiday(), EmailCollector\fetchActions(), ProductAttribute\fetchAll(), AccountingJournal\fetchAll(), Ctyperesource\fetchAll(), CUnits\fetchAll(), ProductStockEntrepot\fetchAll(), Link\fetchAll(), WebsitePage\fetchAll(), Website\fetchAll(), BankCateg\fetchAll(), EmailCollector\fetchAll(), BOM\fetchAll(), MyObject\fetchAll(), LoanSchedule\fetchAll(), EcmFiles\fetchAll(), Holiday\fetchAll(), Ticket\fetchAll(), CommandeFournisseurDispatch\fetchAll(), BookKeeping\fetchAll(), BOMLine\fetchAll(), User\fetchAll(), BookKeeping\fetchAllBalance(), BookKeeping\fetchAllByAccount(), ProductCombination\fetchAllByFkProductParent(), ProductAttributeValue\fetchAllByProductAttribute(), BookKeeping\fetchAllPerMvt(), Task\fetchAllTimeSpent(), ProductCombination2ValuePair\fetchByFkCombination(), ProductCombination\fetchByFkProductChild(), ProductCombination\fetchByProductCombination2ValuePairs(), Holiday\fetchByUser(), CoreObject\fetchChild(), CommonObject\fetchComments(), CommonObject\fetchCommon(), EmailCollector\fetchFilters(), ExpeditionLineBatch\fetchFromStock(), CommonObject\fetchLinesCommon(), Holiday\fetchLog(), BookKeeping\fetchPerMvt(), Facture\fetchPreviousNextSituationInvoice(), ActionComm\fetchResources(), Task\fetchTimeSpent(), Holiday\fetchUsers(), CommonDocGenerator\fill_substitutionarray_with_extrafields(), Productbatch\find(), ProductFournisseur\find_min_price_product_fournisseur(), PriceExpression\find_title(), Form\form_contacts(), Form\form_project(), FormCompany\form_prospect_level(), Form\form_thirdparty(), Form\form_users(), mailing_mailinglist_mymodule_myobject\formFilter(), mailing_fraise\formFilter(), mailing_contacts1\formFilter(), mailing_advthirdparties\formFilter(), mailing_thirdparties\formFilter(), Form\formSelectAccount(), FormProduct\formSelectWarehouses(), TraceableDB\free(), BonPrelevement\generate(), Thirdparties\generateBankAccountDocument(), Utils\generateDoc(), Don\generateDocument(), Societe\generateDocument(), RemiseCheque\generatePdf(), MembersTypes\get(), Subscriptions\get(), Members\get(), BankAccounts\get(), Categorie\get_all_categories(), Societe\get_all_rib(), Product\get_buyprice(), User\get_children(), Entrepot\get_children_warehouses(), mod_codecompta_aquarium\get_code(), Societe\get_codecompta(), BookKeeping\get_compte_desc(), BookKeeping\get_compte_racine(), Project\get_element_list(), Categorie\get_filles(), FormMail\get_form(), EcmDirectory\get_full_arbo(), Entrepot\get_full_arbo(), Categorie\get_full_arbo(), User\get_full_tree(), Categorie\get_meres(), CommandeFournisseur\get_methodes_commande(), MouvementStock\get_origin(), Societe\get_OutstandingBill(), FactureLigne\get_prev_progress(), Facture\get_prev_sits(), CommonDocGenerator\get_substitutionarray_contact(), CommonDocGenerator\get_substitutionarray_lines(), doc_generic_project_odt\get_substitutionarray_object(), doc_generic_task_odt\get_substitutionarray_object(), CommonDocGenerator\get_substitutionarray_object(), doc_generic_project_odt\get_substitutionarray_project_contacts(), CommonDocGenerator\get_substitutionarray_shipment(), CommonDocGenerator\get_substitutionarray_shipment_lines(), doc_generic_project_odt\get_substitutionarray_tasks(), CommonDocGenerator\get_substitutionarray_thirdparty(), Account\get_url(), Fiscalyear\getAccountancyEntriesByFiscalYear(), Fiscalyear\getAccountancyMovementsByFiscalYear(), AccountancyCategory\getAccountsWithNoCategory(), DataPolicy\getAllAdherentsNotInformed(), FichinterStats\getAllByProduct(), CommandeStats\getAllByProduct(), FactureStats\getAllByProduct(), PropaleStats\getAllByProduct(), TaskStats\getAllByYear(), ProjectStats\getAllByYear(), DonationStats\getAllByYear(), ReceptionStats\getAllByYear(), ExpeditionStats\getAllByYear(), TicketStats\getAllByYear(), SalariesStats\getAllByYear(), DeplacementStats\getAllByYear(), ExpenseReportStats\getAllByYear(), AdherentStats\getAllByYear(), FichinterStats\getAllByYear(), CommandeStats\getAllByYear(), FactureStats\getAllByYear(), PropaleStats\getAllByYear(), DataPolicy\getAllCompaniesNotInformed(), DataPolicy\getAllContactNotInformed(), ProjectStats\getAllProjectByStatus(), TaskStats\getAllTaskByStatus(), TicketStats\getAmountByMonth(), SalariesStats\getAmountByMonth(), DeplacementStats\getAmountByMonth(), AdherentStats\getAmountByMonth(), ExpenseReportStats\getAmountByMonth(), FichinterStats\getAmountByMonth(), CommandeStats\getAmountByMonth(), FactureStats\getAmountByMonth(), PropaleStats\getAmountByMonth(), ProjectStats\getAmountByMonth(), Paiement\getAmountsArray(), Setup\getAvailability(), DiscountAbsolute\getAvailableDiscounts(), Societe\getAvailableDiscounts(), TicketStats\getAverageByMonth(), SalariesStats\getAverageByMonth(), DeplacementStats\getAverageByMonth(), AdherentStats\getAverageByMonth(), ExpenseReportStats\getAverageByMonth(), FichinterStats\getAverageByMonth(), CommandeStats\getAverageByMonth(), FactureStats\getAverageByMonth(), PropaleStats\getAverageByMonth(), PaiementFourn\getBillsArray(), Paiement\getBillsArray(), Canvas\getCanvas(), Products\getCategories(), Contacts\getCategories(), Members\getCategories(), Thirdparties\getCategories(), AccountancyCategory\getCats(), AccountancyCategory\getCatsCpts(), Holiday\getCheckOption(), Product\getChildsArbo(), Contact\getCivilityLabel(), Adherent\getCivilityLabel(), ProductCombination\getCombinationLabel(), Opensurveysondage\getComments(), Tickets\getCommon(), Holiday\getConfCP(), Setup\getCountryByID(), Account\getCountryCode(), Holiday\getCPforUser(), AccountancyCategory\getCptBK(), AccountancyCategory\getCptsCat(), SocieteAccount\getCustomerAccount(), TraceableDB\getDefaultCharacterSetDatabase(), TraceableDB\getDefaultCollationDatabase(), PaymentTerm\getDefaultId(), CommandeFournisseur\getDispachedLines(), Documents\getDocumentsListByElement(), DoliDBMysqli\getDriverInfo(), TraceableDB\getDriverInfo(), Dolresource\getElementResources(), Establishment\getEstablishment(), ExpenseReportLine\getExpAmount(), Product\getFather(), ActionsCardService\getFieldList(), ActionsCardProduct\getFieldList(), Thirdparties\getFixedAmountDiscounts(), ExpenseReportRule\getGroupLabel(), Users\getGroups(), CommonInvoice\getIdReplacingInvoice(), ActionsTicket\getInstanceDao(), Thirdparties\getInvoicesQualifiedForCreditNote(), Thirdparties\getInvoicesQualifiedForReplacement(), CommonObjectLine\getLabelOfUnit(), Product\getLabelOfUnit(), DolibarrModules\getLastActivationDate(), DolibarrModules\getLastActivationInfo(), BankAccounts\getLines(), MyObject\getLinesArray(), BOM\getLinesArray(), Project\getLinesArray(), SupplierProposal\getLinesArray(), printing_printgcp\getlistAvailablePrinters(), Categorie\getListForItem(), CommonInvoice\getListIdAvoirFromInvoice(), RejetPrelevement\getListInvoices(), BonPrelevement\getListInvoices(), TraceableDB\getListOfCharacterSet(), Setup\getListOfCivilities(), TraceableDB\getListOfCollation(), Contrat\getListOfContracts(), Setup\getListOfCountries(), Setup\getListOfCurrencies(), Setup\getListOfEventTypes(), Setup\getListOfExtrafields(), InterfaceNotification\getListOfManagedEvents(), Setup\getListOfMeasuringUnits(), CommonInvoice\getListOfPayments(), Setup\getListOfTowns(), BlockedLogAuthority\getLocalBlockChain(), BlockedLog\getLog(), CommandeFournisseur\getMaxDeliveryTimeDay(), Product\getMultiLangs(), Categorie\getMultiLangs(), DonationStats\getNbByMonth(), ReceptionStats\getNbByMonth(), AdherentStats\getNbByMonth(), ExpeditionStats\getNbByMonth(), FichinterStats\getNbByMonth(), SalariesStats\getNbByMonth(), TicketStats\getNbByMonth(), DeplacementStats\getNbByMonth(), FactureStats\getNbByMonth(), CommandeStats\getNbByMonth(), PropaleStats\getNbByMonth(), ExpenseReportStats\getNbByMonth(), TaskStats\getNbByMonth(), ProjectStats\getNbByMonth(), DonationStats\getNbByYear(), AdherentStats\getNbByYear(), ReceptionStats\getNbByYear(), ExpeditionStats\getNbByYear(), FichinterStats\getNbByYear(), CommandeStats\getNbByYear(), FactureStats\getNbByYear(), PropaleStats\getNbByYear(), Contact\getNbOfEMailings(), Adherent\getNbOfEMailings(), User\getNbOfEMailings(), Fournisseur\getNbOfOrders(), MailingTargets\getNbOfRecipients(), Commande\getNbOfShipments(), User\getNbOfUsers(), BookKeeping\getNextNumMvt(), Reception\getNextNumRef(), Expedition\getNextNumRef(), Paiement\getNomUrl(), AccountLine\getNomUrl(), Notify\getNotificationsArray(), ActionsAdherentCardCommon\getObject(), ActionsContactCardCommon\getObject(), ActionsCardCommon\getObject(), BlockedLog\getObjectLink(), Categorie\getObjectsInCateg(), Societe\getOutstandingBills(), Societe\getOutstandingOrders(), Societe\getOutstandingProposals(), TraceableDB\getPathOfDump(), TraceableDB\getPathOfRestore(), Stripe\getPaymentIntent(), Setup\getPaymentTerms(), Setup\getPaymentTypes(), BlockedLog\getPreviousHash(), Project\getProjectsAuthorizedForUser(), MultiCurrency\getRate(), Livraison\getRemainingDelivered(), UserGroup\getrights(), User\getrights(), Projects\getRoles(), Tasks\getRoles(), Societe\getSalesRepresentatives(), TraceableDB\getServerParametersValues(), TraceableDB\getServerStatusValues(), Setup\getShippingModes(), ProductFournisseur\getSocNomUrl(), CommonInvoice\getSommePaiement(), ChargeSociales\getSommePaiement(), Tva\getSommePaiement(), CdavLib\getSqlCalEvents(), Stripe\getStripeAccount(), Stripe\getStripeCustomerAccount(), Members\getSubscriptions(), CommonInvoice\getSumCreditNotesUsed(), DiscountAbsolute\getSumCreditNotesUsed(), AccountancyCategory\getSumDebitCredit(), CommonInvoice\getSumDepositsUsed(), DiscountAbsolute\getSumDepositsUsed(), CommonInvoice\getSumFromThisCreditNotesNotUsed(), DiscountAbsolute\getSumFromThisCreditNotesNotUsed(), Task\getSummaryOfTimeSpent(), Task\getSumOfAmount(), Loan\getSumPayment(), ExpenseReport\getSumPayments(), Thirdparties\getSupplierCategories(), Task\getTasksArray(), SocieteAccount\getThirdPartyID(), Setup\getTicketsCategories(), Setup\getTicketsSeverities(), Setup\getTicketsTypes(), ProjectStats\getTransformRateByMonth(), Holiday\getTypes(), ProductCombination\getUniqueAttributesAndValuesByFkProductParent(), Reception\getUrlTrackingStatus(), Expedition\getUrlTrackingStatus(), BlockedLog\getUser(), ExpenseReportRule\getUserName(), Task\getUserRolesForProjectsOrTasks(), CommonInvoice\getVentilExportCompta(), AccountLine\getVentilExportCompta(), ExpenseReport\getVentilExportCompta(), DoliDBMysqli\getVersion(), DoliDBSqlite3\getVersion(), TraceableDB\getVersion(), TraceableDB\getVersionArray(), ProjectStats\getWeightedAmountByMonth(), Societe\has_projects(), Task\hasChildren(), Product\hasFatherOrChild(), Task\hasTimeSpent(), Product\hasVariants(), Societe\id_prof_exists(), TraceableDB\idate(), TraceableDB\ifsql(), ImportCsv\import_insert(), ImportXlsx\import_insert(), Website\importWebSite(), Login\index(), BankAccounts\index(), Subscriptions\index(), MembersTypes\index(), Members\index(), Tickets\index(), mod_reception_moonstone\info(), mod_project_universal\info(), mod_task_universal\info(), mod_supplier_payment_brodator\info(), mod_livraison_saphir\info(), mod_arctic\info(), mod_propale_saphir\info(), mod_supplier_proposal_saphir\info(), mod_facture_fournisseur_tulip\info(), doc_generic_odt\info(), doc_generic_reception_odt\info(), doc_generic_user_odt\info(), doc_generic_proposal_odt\info(), doc_generic_product_odt\info(), doc_generic_stock_odt\info(), doc_generic_supplier_proposal_odt\info(), doc_generic_usergroup_odt\info(), doc_generic_contract_odt\info(), doc_generic_order_odt\info(), doc_generic_invoice_odt\info(), doc_generic_shipment_odt\info(), Fiscalyear\info(), doc_generic_task_odt\info(), Establishment\info(), EmailSenderProfile\info(), doc_generic_project_odt\info(), PaiementFourn\info(), Asset\info(), EmailCollectorFilter\info(), Inventory\info(), Subscription\info(), Deplacement\info(), EmailCollectorAction\info(), Entrepot\info(), SocieteAccount\info(), AccountingAccount\info(), CompanyPaymentMode\info(), Loan\info(), EmailCollector\info(), ChargeSociales\info(), MyObject\info(), PaymentVarious\info(), PaymentSalary\info(), ExpenseReport\info(), PaymentExpenseReport\info(), Tva\info(), BOM\info(), Fichinter\info(), Cronjob\info(), Don\info(), Paiement\info(), Contact\info(), ActionComm\info(), BOMLine\info(), Project\info(), Contrat\info(), FactureFournisseur\info(), SupplierProposal\info(), AccountLine\info(), Adherent\info(), User\info(), CommandeFournisseur\info(), Propal\info(), Societe\info(), Facture\info(), Commande\info(), Product\info(), modExternalRss\init(), modPrelevement\init(), modDon\init(), modBlockedLog\init(), modSupplierProposal\init(), modDataPolicy\init(), modFicheinter\init(), modContrat\init(), modReception\init(), modPropale\init(), modCommande\init(), modEmailCollector\init(), modDav\init(), modProjet\init(), modBom\init(), modExpedition\init(), modStock\init(), modFacture\init(), modAdherent\init(), modFournisseur\init(), Don\initAsSpecimen(), ExpenseReport\initAsSpecimen(), Livraison\initAsSpecimen(), Reception\initAsSpecimen(), Fichinter\initAsSpecimen(), Contact\initAsSpecimen(), FactureRec\initAsSpecimen(), Expedition\initAsSpecimen(), Contrat\initAsSpecimen(), SupplierProposal\initAsSpecimen(), FactureFournisseur\initAsSpecimen(), CommandeFournisseur\initAsSpecimen(), Propal\initAsSpecimen(), Commande\initAsSpecimen(), Facture\initAsSpecimen(), HookManager\initHooks(), dolReceiptPrinter\initPrinter(), FichinterLigne\insert(), AccountLine\insert(), ExpeditionLigne\insert(), ExpenseReportLine\insert(), SupplierProposalLine\insert(), SupplierInvoiceLine\insert(), ContratLigne\insert(), CommandeFournisseurLigne\insert(), PropaleLigne\insert(), OrderLine\insert(), FactureLigne\insert(), DolibarrModules\insert_boxes(), DolibarrModules\insert_const(), DolibarrModules\insert_cronjobs(), DolibarrModules\insert_dirs(), SupplierProposal\insert_discount(), Propal\insert_discount(), FactureFournisseur\insert_discount(), Facture\insert_discount(), Commande\insert_discount(), DolibarrModules\insert_menus(), DolibarrModules\insert_module_parts(), DolibarrModules\insert_permissions(), DolibarrModules\insert_tabs(), Propal\InvoiceArrayList(), Facture\is_last_in_cycle(), Product\is_sousproduit(), Product\isVariant(), TraceableDB\jdate(), TraceableDB\last_insert_id(), DoliDBMysqli\last_insert_id(), DoliDBSqlite3\last_insert_id(), DoliDBPgsql\last_insert_id(), TraceableDB\lasterrno(), TraceableDB\lasterror(), LoanSchedule\lastPayment(), TraceableDB\lastquery(), TraceableDB\lastqueryerror(), Lettering\letteringThirdparty(), Societe\LibProspLevel(), DiscountAbsolute\link_to_invoice(), Entrepot\list_array(), Reception\list_delivery_methods(), Expedition\list_delivery_methods(), Export\list_export_model(), FormFile\list_of_autoecmfiles(), FormFile\list_of_documents(), PriceExpression\list_price_expression(), ProductFournisseur\list_product_fournisseur_price(), Facture\list_qualified_avoir_invoices(), FactureFournisseur\list_qualified_avoir_supplier_invoices(), Facture\list_replacable_invoices(), FactureFournisseur\list_replacable_supplier_invoices(), Product\list_suppliers(), Fournisseur\ListArray(), AssetType\listAssetForAssetType(), CActionComm\liste_array(), AssetType\liste_array(), AdherentType\liste_array(), SupplierProposal\liste_array(), Commande\liste_array(), Propal\liste_array(), Facture\liste_array(), Ticket\listeContact(), PriceGlobalVariable\listGlobalVariables(), UserGroup\listGroupsForUser(), printing_printipp\listJobs(), printing_printgcp\listJobs(), AdherentType\listMembersForMemberType(), FormFile\listOfLinks(), Deplacement\listOfTypes(), ExpenseReport\listOfTypes(), PriceGlobalVariableUpdater\listPendingUpdaters(), dolReceiptPrinter\listPrinters(), dolReceiptPrinter\listPrintersTemplates(), ProductFournisseur\listProductFournisseurPriceLog(), PriceGlobalVariableUpdater\listUpdaters(), UserGroup\listUsersForGroup(), CommandeFournisseur\Livraison(), Import\load_arrays(), Export\load_arrays(), RemiseCheque\load_board(), ActionComm\load_board(), Account\load_board(), Project\load_board(), Task\load_board(), Contrat\load_board(), FactureFournisseur\load_board(), Holiday\load_board(), SupplierProposal\load_board(), Adherent\load_board(), ExpenseReport\load_board(), CommandeFournisseur\load_board(), Propal\load_board(), Commande\load_board(), Facture\load_board(), Form\load_cache_availability(), Dolresource\load_cache_code_type_resource(), Form\load_cache_conditions_paiements(), Form\load_cache_types_fees(), Form\load_cache_types_paiements(), Form\load_cache_vatrates(), EcmDirectory\load_motherof(), Categorie\load_motherof(), RemiseCheque\load_previous_next_id(), Contact\load_ref_elements(), Client\load_state_board(), Fournisseur\load_state_board(), Fichinter\load_state_board(), Contact\load_state_board(), RemiseCheque\load_state_board(), Don\load_state_board(), Account\load_state_board(), Project\load_state_board(), Task\load_state_board(), Holiday\load_state_board(), Contrat\load_state_board(), Adherent\load_state_board(), ExpenseReport\load_state_board(), SupplierProposal\load_state_board(), FactureFournisseur\load_state_board(), CommandeFournisseur\load_state_board(), User\load_state_board(), Propal\load_state_board(), Commande\load_state_board(), Facture\load_state_board(), Product\load_state_board(), Product\load_stats_commande(), Product\load_stats_commande_fournisseur(), Product\load_stats_contrat(), Product\load_stats_facture(), Product\load_stats_facture_fournisseur(), Product\load_stats_propale(), Product\load_stats_proposal_supplier(), Product\load_stats_reception(), Product\load_stats_sending(), Product\load_stock(), Form\load_tva(), Product\load_virtual_stock(), Product\loadBatchInfo(), box_last_ticket\loadBox(), box_last_modified_ticket\loadBox(), box_graph_invoices_permonth\loadBox(), box_graph_invoices_supplier_permonth\loadBox(), box_graph_orders_permonth\loadBox(), box_graph_propales_permonth\loadBox(), box_graph_orders_supplier_permonth\loadBox(), box_services_expired\loadBox(), box_external_rss\loadBox(), box_graph_product_distribution\loadBox(), box_project\loadBox(), box_produits\loadBox(), box_task\loadBox(), box_produits_alerte_stock\loadBox(), Ticket\loadCacheCategoriesTickets(), Form\loadCacheInputReason(), Ticket\loadCacheMsgsTicket(), Client\loadCacheOfProspStatus(), Ticket\loadCacheSeveritiesTickets(), Ticket\loadCacheTypesTickets(), User\loadDefaultValues(), Commande\loadExpeditions(), ActionsCardService\LoadListDatas(), ActionsCardProduct\LoadListDatas(), FormProduct\loadLotStock(), MenuManager\loadMenu(), User\loadParentOf(), CommandeFournisseur\loadReceptions(), Societe\LoadSupplierCateg(), dolReceiptPrinter\loadTemplate(), Project\loadTimeSpent(), FormProduct\loadWarehouses(), Localtax\localtax_sum_collectee(), Localtax\localtax_sum_payee(), Localtax\localtax_sum_reglee(), Product\log_price_delete(), ProductFournisseur\logPrice(), Invoices\markAsCreditAvailable(), Ticket\markAsRead(), Menubase\menuLoad(), Ticket\messageSend(), Product\min_recommended_price(), ProductAttribute\moveLine(), FormAdvTargetEmailing\multiselectCategories(), FormAdvTargetEmailing\multiselectCivility(), FormAdvTargetEmailing\multiselectCountry(), FormAdvTargetEmailing\multiselectProspectionStatus(), FormAdvTargetEmailing\multiselectselectSalesRepresentatives(), Entrepot\nb_different_products(), Commande\nb_expedition(), Entrepot\nb_products(), BonPrelevement\NbFactureAPrelever(), Fournisseur\nbOfProductRefs(), Facture\newCycle(), Ticket\newMessage(), TraceableDB\num_rows(), DoliDBSqlite3\num_rows(), ExpenseReport\offsetAlreadyGiven(), TraceableDB\order(), LoanSchedule\paimenttorecord(), PriceParser\parseExpression(), PriceParser\parseProduct(), PriceParser\parseProductSupplier(), Thirdparties\patchSocieteAccount(), ExpenseReport\periode_existe(), TraceableDB\plimit(), BankAccounts\post(), Subscriptions\post(), MembersTypes\post(), Members\post(), Tickets\post(), Tickets\postNewMessage(), ActionsDatapolicy\printCommonFooter(), printing_printipp\printFile(), printing_printgcp\printFile(), PriceGlobalVariableUpdater\process(), Utils\purgeFiles(), Subscriptions\put(), MembersTypes\put(), Members\put(), BankAccounts\put(), Proposals\putLine(), Thirdparties\putSocieteAccount(), DoliDBMysqli\query(), TraceableDB\query(), DoliDBMssql\query(), DoliDBSqlite3\query(), DoliDBPgsql\query(), AdvanceTargetingMailing\query_contact(), AdvanceTargetingMailing\query_thirdparty(), CommonObject\quote(), ExpenseReport\recalculer(), Categorie\rechercher(), EcmDirectory\refreshcachenboffile(), CommandeFournisseur\refuse(), Paiement\reject(), RemiseCheque\rejectCheck(), modBlockedLog\remove(), Bookmark\remove(), modApi\remove(), Project\remove_element(), ProductFournisseur\remove_fournisseur(), ProductFournisseur\remove_product_fournisseur_price(), RemiseCheque\removeCheck(), User\RemoveFromGroup(), Contrat\reopen(), SupplierProposal\reopen(), Reception\reOpen(), Expedition\reOpen(), Propal\reopen(), ProductAttribute\reorderLines(), Cronjob\reprogram_jobs(), Mailing\reset_targets_status(), Adherent\resiliate(), TraceableDB\rollback(), DoliDBMssql\rollback(), Cronjob\run_jobs(), Interfaces\run_triggers(), InterfaceActionsBlockedLog\runTrigger(), InterfaceLdapsynchro\runTrigger(), InterfaceLogevents\runTrigger(), InterfaceWorkflowManager\runTrigger(), InterfaceActionsAuto\runTrigger(), InterfaceNotification\runTrigger(), InterfaceTicketEmail\runTrigger(), InterfaceStripe\runTrigger(), Ticket\searchContactByEmail(), Ticket\searchSocidByEmail(), FormAccounting\select_account(), BookKeeping\select_account(), Form\select_address(), Form\select_all_categories(), FormAccounting\select_auxaccount(), FormAccounting\select_bookkeeping_importkey(), FormOther\select_categories(), FormCompany\select_civility(), Form\select_company(), Form\select_comptes(), Form\select_country(), DoliDBMssql\select_db(), DoliDBMysqli\select_db(), TraceableDB\select_db(), FormOther\select_dictionary(), Form\select_dolgroups(), Form\select_dolusers(), Form\select_dolusers_forevent(), FormOther\select_ecotaxes(), FormProjets\select_element(), FormOther\select_export_model(), Form\select_export_model(), FormOther\select_import_model(), Form\select_incoterms(), FormAccounting\select_journal(), FormCompany\select_juridicalstatus(), FormCompany\select_localtax(), FormAdmin\select_paper_format(), Form\select_product_fourn_price(), Form\select_produits(), Form\select_produits_fournisseurs(), Form\select_produits_fournisseurs_list(), Form\select_produits_list(), FormProjets\select_projects(), FormProjets\select_projects_list(), FormCompany\select_region(), Form\select_remises(), FormResource\select_resource_list(), FormOther\select_revenue_stamp(), FormOther\select_salesrepresentatives(), FormCompany\select_state(), Form\select_thirdparty_list(), FormActions\select_type_actions(), FormResource\select_types_resource(), FormAdvTargetEmailing\selectAdvtargetemailingTemplate(), FormEcm\selectAllSections(), FormBarCode\selectBarcodeType(), FormCompany\selectCompaniesForNewContact(), Form\selectcontacts(), FormMailing\selectDestinariesStatus(), Form\selectEstablishments(), FormTicket\selectGroupTickets(), FormOrder\selectInputMethod(), FormProjets\selectOpportunityStatus(), FormOther\selectProjectTasks(), FormPropal\selectProposalStatus(), FormTicket\selectSeveritiesTickets(), Form\selectShippingMethod(), Form\selectSituationInvoices(), FormOrder\selectSupplierOrderStatus(), FormProjets\selectTasks(), FormBank\selectTypeOfBankAccount(), FormWebsite\selectTypeOfContainer(), FormTicket\selectTypesTickets(), Form\selectUnits(), FormWebsite\selectWebsite(), FormAccounting\selectyear_accountancy_bookkepping(), Notify\send(), ActionComm\sendEmailsReminder(), CSMSFile\sendfile(), printing_printgcp\sendPrintToPrinter(), Adherent\sendReminderForExpiredSubscription(), Ticket\sendTicketMessageByEmail(), Societe\set_as_client(), Propal\set_availability(), Reception\set_billed(), Expedition\set_billed(), Don\set_cancel(), ExpenseReport\set_cancel(), Facture\set_canceled(), Fichinter\set_contrat(), BonPrelevement\set_credite(), RemiseCheque\set_date(), Propal\set_date(), Commande\set_date(), Fichinter\set_date_delivery(), Livraison\set_date_livraison(), Reception\set_date_livraison(), SupplierProposal\set_date_livraison(), Expedition\set_date_livraison(), Propal\set_date_livraison(), CommandeFournisseur\set_date_livraison(), Commande\set_date_livraison(), User\set_default_rights(), Propal\set_demand_reason(), Fichinter\set_description(), Propal\set_echeance(), CommandeFournisseur\set_id_projet(), BonPrelevement\set_infocredit(), BonPrelevement\set_infotrans(), RemiseCheque\set_number(), Loan\set_paid(), ChargeSociales\set_paid(), ExpenseReport\set_paid(), Don\set_paid(), FactureFournisseur\set_paid(), Facture\set_paid(), Societe\set_parent(), Societe\set_price_level(), Facture\set_ref_client(), Propal\set_ref_client(), Commande\set_ref_client(), Commande\set_remise(), Facture\set_remise(), SupplierProposal\set_remise_absolue(), Propal\set_remise_absolue(), Commande\set_remise_absolue(), Facture\set_remise_absolue(), Societe\set_remise_client(), Societe\set_remise_except(), SupplierProposal\set_remise_percent(), Propal\set_remise_percent(), Societe\set_remise_supplier(), Commande\set_reopen(), ExpenseReport\set_save_from_refuse(), ChargeSociales\set_unpaid(), FactureFournisseur\set_unpaid(), ExpenseReport\set_unpaid(), Facture\set_unpaid(), ExpenseReport\setApproved(), CompanyBankAccount\setAsDefault(), CompanyPaymentMode\setAsDefault(), FactureRec\setAutoValidate(), Account\setCategories(), User\setCategories(), Contact\setCategories(), Project\setCategories(), Adherent\setCategories(), Societe\setCategories(), Product\setCategories(), BlockedLog\setCertified(), Project\setClose(), Reception\setClosed(), Expedition\setClosed(), Ticket\setContract(), Ticket\setCustomer(), ExpenseReport\setDeny(), Fichinter\setDraft(), Commande\setDraft(), BOM\setDraft(), FactureFournisseur\setDraft(), Reception\setDraft(), SupplierProposal\setDraft(), Facture\setDraft(), Propal\setDraft(), Facture\setFinal(), FactureRec\setFrequencyAndUnit(), FactureRec\setGeneratePdf(), User\SetInGroup(), FactureRec\setMaxPeriod(), FactureRec\setModelPdf(), Product\setMultiLangs(), Categorie\setMultiLangs(), Societe\setMysoc(), FactureRec\setNextDate(), BlockedLog\setObjectData(), MouvementStock\setOrigin(), Adherent\setPassword(), User\setPassword(), Productcustomerprice\setPriceOnAffiliateThirdparty(), Ticket\setProgression(), Ticket\setProject(), Facture\setRetainedWarranty(), Facture\setRetainedWarrantyDateLimit(), CommonObject\setSaveQuery(), User\setstatus(), Contact\setstatus(), CommandeFournisseur\setStatus(), ProductFournisseur\setSupplierPriceExpression(), Adherent\setThirdPartyId(), Adherent\setUserId(), Fichinter\setValid(), Project\setValid(), ExpenseReport\setValidate(), Project\shiftTaskDate(), FormSms\show_form(), FormActions\showactions(), FormFile\showdocuments(), FormTicket\showForm(), ExtraFields\showInputField(), Form\showLinkToObjectBlock(), MenuManager\showmenu(), FormTicket\showMessageForm(), ExtraFields\showOutputField(), ChargeSociales\solde(), Account\solde(), BonPrelevement\SommeAPrelever(), Commande\stock_array(), Adherent\subscription(), Adherent\subscriptionComplementaryActions(), Don\sum_donations(), BlockedLogAuthority\syncSignatureWithAuthority(), pdf_standard\tablePayments(), PriceParser\testExpression(), BankAccounts\transfer(), BookKeeping\transformTransaction(), LoanSchedule\transPayment(), Tva\tva_sum_collectee(), Tva\tva_sum_payee(), Tva\tva_sum_reglee(), FormCompany\typent_array(), DiscountAbsolute\unlink_invoice(), UserBankAccount\update(), PaymentSalary\update(), PaymentVarious\update(), CompanyBankAccount\update(), BankCateg\update(), Link\update(), ProductAttribute\update(), Localtax\update(), Mailing\update(), AssetType\update(), Tva\update(), ProductAttributeValue\update(), Fiscalyear\update(), AdherentType\update(), PriceGlobalVariable\update(), Establishment\update(), Deplacement\update(), Bookmark\update(), Events\update(), Productbatch\update(), PriceGlobalVariableUpdater\update(), Cstate\update(), Entrepot\update(), Ctypent\update(), Ccountry\update(), Comment\update(), Cpaiement\update(), Cchargesociales\update(), EcmDirectory\update(), Subscription\update(), ProductCombination\update(), Dolresource\update(), CoreObject\update(), Menubase\update(), BlockedLogAuthority\update(), PriceExpression\update(), PaymentExpenseReport\update(), PaymentDonation\update(), PaymentLoan\update(), PaymentTerm\update(), LoanSchedule\update(), Productlot\update(), Opensurveysondage\update(), Ctyperesource\update(), PaymentSocialContribution\update(), Project\update(), AccountancyCategory\update(), Propalmergepdfproduct\update(), ProductStockEntrepot\update(), ChargeSociales\update(), CUnits\update(), Contact\update(), FactureRec\update(), AccountingAccount\update(), CommandeFournisseurDispatch\update(), Loan\update(), Fichinter\update(), Task\update(), Website\update(), AdvanceTargetingMailing\update(), ExpenseReport\update(), Categorie\update(), Don\update(), Adherent\update(), EcmFiles\update(), Cronjob\update(), Productcustomerprice\update(), ExtraFields\update(), Account\update(), Ticket\update(), UserGroup\update(), Reception\update(), Product\update(), FactureFournisseur\update(), Societe\update(), Holiday\update(), CurrencyRate\update(), ActionComm\update(), Expedition\update(), BookKeeping\update(), Contrat\update(), User\update(), Propal\update(), FichinterLigne\update(), Facture\update(), FactureLigneRec\update(), AccountLine\update(), ExpenseReportLine\update(), ExpeditionLigne\update(), ContratLigne\update(), SupplierInvoiceLine\update(), Commande\update(), SupplierProposalLine\update(), CommandeFournisseurLigne\update(), PropaleLigne\update(), OrderLine\update(), FactureLigne\update(), Account\update_bban(), ProductFournisseur\update_buyprice(), User\update_clicktodial(), AccountLine\update_conciliation(), Paiement\update_date(), Reception\update_delivery_method(), Expedition\update_delivery_method(), Project\update_element(), Dolresource\update_element_resource(), Adherent\update_end_date(), PaymentVarious\update_fk_bank(), PaymentLoan\update_fk_bank(), PaymentSalary\update_fk_bank(), Localtax\update_fk_bank(), PaymentDonation\update_fk_bank(), PaymentSocialContribution\update_fk_bank(), PaymentExpenseReport\update_fk_bank(), Tva\update_fk_bank(), Paiement\update_fk_bank(), ExtraFields\update_label(), User\update_last_login_date(), Livraison\update_line(), MailingTargets\update_nb(), PriceGlobalVariableUpdater\update_next_update(), Paiement\update_num(), Contact\update_perso(), Product\update_sousproduit(), PriceGlobalVariableUpdater\update_status(), FichinterLigne\update_total(), ContratLigne\update_total(), SupplierInvoiceLine\update_total(), SupplierProposalLine\update_total(), PropaleLigne\update_total(), OrderLine\update_total(), FactureLigne\update_total(), ExpenseReport\update_totaux_add(), ExpenseReport\update_totaux_del(), AccountancyCategory\updateAccAcc(), RemiseCheque\updateAmount(), Holiday\updateBalance(), BookKeeping\updateByMvt(), CommonObject\updateCommon(), Thirdparties\updateCompanyBankAccount(), Holiday\updateConfCP(), CommandeFournisseur\updateFromCommandeClient(), Lettering\updateLettering(), SupplierProposal\updateline(), Propal\updateline(), FactureRec\updateline(), Contrat\updateline(), FactureFournisseur\updateline(), ExpenseReport\updateline(), CommandeFournisseur\updateline(), Facture\updateline(), Commande\updateline(), SupplierProposal\updateOrCreatePriceFournisseur(), Product\updatePrice(), SupplierProposal\updatePriceFournisseur(), dolReceiptPrinter\updatePrinter(), updateProductOrService(), ProductCombination\updateProperties(), Holiday\updateSoldeCP(), dolReceiptPrinter\updateTemplate(), Task\updateTimeSpent(), mailing_advthirdparties\url(), Invoices\useCreditNote(), Societe\useLocalTax(), Societe\useNPR(), User\user_get_property(), Societe\useRevenueStamp(), CashControl\valid(), Commande\valid(), Livraison\valid(), Mailing\valid(), Reception\valid(), CommandeFournisseur\valid(), BOM\valid(), Expedition\valid(), SupplierProposal\valid(), Propal\valid(), Don\valid_promesse(), RemiseCheque\validate(), Contrat\validate(), Holiday\validate(), FactureFournisseur\validate(), Adherent\validate(), Facture\validate(), Paiement\valide(), Holiday\verifDateHolidayForTimestamp(), ActionsTicket\viewTicketMessages(), ActionsTicket\viewTicketTimelineMessages(), html_cerfafr\write_file(), BordereauChequeBlochet\write_file(), pdf_paiement\write_file(), pdf_ban\write_file(), pdf_sepamandate\write_file(), pdf_timespent\write_file(), CommActionRapport\write_file(), pdf_squille\write_file(), pdf_beluga\write_file(), pdf_merou\write_file(), pdf_espadon\write_file(), pdf_soleil\write_file(), pdf_strato\write_file(), pdf_baleine\write_file(), pdf_cornas\write_file(), pdf_rouget\write_file(), pdf_typhon\write_file(), doc_generic_odt\write_file(), pdf_cyan\write_file(), pdf_eratosthene\write_file(), pdf_stdmovement\write_file(), doc_generic_contract_odt\write_file(), pdf_canelle\write_file(), doc_generic_reception_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_shipment_odt\write_file(), doc_generic_order_odt\write_file(), pdf_aurore\write_file(), pdf_sponge\write_file(), pdf_standard\write_file(), pdf_muscadet\write_file(), pdf_azur\write_file(), doc_generic_user_odt\write_file(), pdf_einstein\write_file(), doc_generic_stock_odt\write_file(), doc_generic_product_odt\write_file(), doc_generic_usergroup_odt\write_file(), doc_generic_proposal_odt\write_file(), pdf_crabe\write_file(), doc_generic_supplier_proposal_odt\write_file(), doc_generic_task_odt\write_file(), and doc_generic_project_odt\write_file().