Dolibarr: mod_arctic Class Reference
mod_arctic Class Reference
Class to manage numbering of intervention cards with rule Artic.
Public Member Functions
info ()
Returns the description of the numbering model.
getExample ()
Renvoi un exemple de numerotation.
getNextValue ($objsoc=0, $object= '')
Return next free value.
getNumRef ($objsoc, $objforref)
Return next free value.
Public Member Functions inherited from ModeleNumRefFicheinter
isEnabled ()
Return if a module can be used or not.
info ()
Returns the default description of the numbering template.
getExample ()
Return a numbering example.
canBeActivated ()
Tests if the numbers already in force in the database do not cause conflicts that would prevent this numbering from working.
getNextValue ()
Return the next assigned value.
getVersion ()
Return the version of the numbering module.
Detailed Description
Class to manage numbering of intervention cards with rule Artic.
Definition at line 33 of file mod_arctic.php.
Member Function Documentation
getExample ()
Renvoi un exemple de numerotation.
Returns
string Example
Definition at line 104 of file mod_arctic.php.
References ModeleNumRefFicheinter\getNextValue().
getNextValue ($objsoc = 0, $object = '')
Return next free value.
Parameters
Societe $objsoc Object thirdparty
Object $object Object we need next value for
Returns
string Value if KO, <0 if KO
Definition at line 127 of file mod_arctic.php.
References get_next_value().
getNumRef ($objsoc, $objforref)
Return next free value.
Parameters
Societe $objsoc Object third party
Object $objforref Object for number to search
Returns
string Next free value
Definition at line 155 of file mod_arctic.php.
References ModeleNumRefFicheinter\getNextValue().
info ()
Returns the description of the numbering model.
Returns
string Texte descripif
Definition at line 64 of file mod_arctic.php.
References db.
The documentation for this class was generated from the following file:
htdocs/core/modules/fichinter/mod_arctic.php