Dolibarr: ActionsCardCompany Class Reference
ActionsCardCompany Class Reference
ActionsCardCompany.
Public Member Functions
__construct ($db, $dirmodule, $targetmodule, $canvas, $card)
Constructor.
assign_values (&$action, $id=0, $ref= '')
Assign custom values for canvas (for example into this->tpl to be used by templates)
restrictedArea ($user, $features= 'societe', $objectid=0, $dbtablename= '', $feature2= '', $dbt_keyfield= 'fk_soc', $dbt_select= 'rowid')
Check permissions of a user to show a page and an object.
Public Member Functions inherited from ActionsCardCommon
assign_values (&$action, $id=0, $ref= '')
Assign custom values for canvas (for example into this->tpl to be used by templates)
Private Member Functions
getTitle ($action)
Return the title of card.
Additional Inherited Members
Data Fields inherited from ActionsCardCommon
$tpl = array()
Template container.
$object
Object container.
Protected Member Functions inherited from ActionsCardCommon
getObject ($id, $ref= '')
Get object from id or ref and save it into this->object.
Detailed Description
ActionsCardCompany.
Class with controller methods for thirdparty canvas
Definition at line 32 of file actions_card_company.class.php.
Constructor & Destructor Documentation
__construct ($db, $dirmodule, $targetmodule, $canvas, $card)
Constructor.
Parameters
DoliDB $db Handler acces base de donnees
string $dirmodule Name of directory of module
string $targetmodule Name of directory of module where canvas is stored
string $canvas Name of canvas
string $card Name of tab (sub-canvas)
Definition at line 43 of file actions_card_company.class.php.
References db.
Member Function Documentation
assign_values (& $action, $id = 0, $ref = '')
Assign custom values for canvas (for example into this->tpl to be used by templates)
Parameters
string $action Type of action
integer $id Id of object
string $ref Ref of object
Returns
void
Definition at line 81 of file actions_card_company.class.php.
References db, dol_escape_js(), ActionsCardCommon\getObject(), getTitle(), img_picto(), and load_fiche_titre().
getTitle ($action) private
Return the title of card.
Parameters
string $action Action code
Returns
string Title
Definition at line 58 of file actions_card_company.class.php.
Referenced by assign_values().
restrictedArea ($user, $features = 'societe', $objectid = 0, $dbtablename = '', $feature2 = '', $dbt_keyfield = 'fk_soc', $dbt_select = 'rowid')
Check permissions of a user to show a page and an object.
Check read permission If $_REQUEST['action'] defined, we also check write permission.
Parameters
User $user User to check
string $features Features to check (in most cases, it's module name)
int $objectid Object ID if we want to check permission on a particular record (optional)
string $dbtablename Table name where object is stored. Not used if objectid is null (optional)
string $feature2 Feature to check (second level of permission)
string $dbt_keyfield Field name for socid foreign key if not fk_soc. (optional)
string $dbt_select Field name for select if not rowid. (optional)
Returns
int 1
Definition at line 220 of file actions_card_company.class.php.
The documentation for this class was generated from the following file:
htdocs/societe/canvas/company/actions_card_company.class.php