Dolibarr: htdocs/install/lib/repair.lib.php File Reference
repair.lib.php File Reference
Library of repair functions.
Functions
checkElementExist ($id, $table)
Check if an element exist.
checkLinkedElements ($sourcetype, $targettype)
Check linked elements and delete if invalid.
clean_data_ecm_directories ()
Clean data into ecm_directories table.
Detailed Description
Library of repair functions.
Definition in file repair.lib.php.
Function Documentation
checkElementExist ($id, $table)
Check if an element exist.
Parameters
int $id Element id
string $table Table of Element
Returns
boolean True if child exists
Definition at line 31 of file repair.lib.php.
References $resql.
Referenced by checkLinkedElements().
checkLinkedElements ($sourcetype, $targettype)
Check linked elements and delete if invalid.
Parameters
string $sourcetype Source element type
string $targettype Target element type
Returns
string
Definition at line 54 of file repair.lib.php.
References $resql, and checkElementExist().
clean_data_ecm_directories ()
Clean data into ecm_directories table.
Returns
void
Definition at line 118 of file repair.lib.php.
References $resql, dol_print_error(), dol_sanitizeFileName(), and print.