Dolibarr: StockMovements Class Reference
StockMovements Class Reference
Public Member Functions
__construct ()
Constructor.
index ($sortfield="t.rowid", $sortorder= 'ASC', $limit=100, $page=0, $sqlfilters= '')
Get properties of a stock movement object.
post ($request_data=null)
Create stock movement object.
Public Member Functions inherited from DolibarrApi
__construct ($db, $cachedir= '', $refreshCache=false)
Constructor.
Protected Member Functions
_cleanObjectDatas ($object)
Update stock movement.
Protected Member Functions inherited from DolibarrApi
_cleanObjectDatas ($object)
Executed method when API is called without parameter.
_checkFilters ($sqlfilters)
Return if a $sqlfilters parameter is valid.
Private Member Functions
_validate ($data)
Validate fields before create or update object.
Additional Inherited Members
Static Protected Member Functions inherited from DolibarrApi
static _checkAccessToResource ($resource, $resource_id=0, $dbtablename= '', $feature2= '', $dbt_keyfield= 'fk_soc', $dbt_select= 'rowid')
Check user access to a resource.
static _forge_criteria_callback ($matches)
Function to forge a SQL criteria.
Detailed Description
Definition at line 29 of file api_stockmovements.class.php.
Member Function Documentation
_cleanObjectDatas ($object) protected
Update stock movement.
Parameters
int $id Id of warehouse to update
array $request_data Datas
Returns
int Delete stock movement
Parameters
int $id Stock movement ID
Returns
array Clean sensible object datas
Parameters
MouvementStock $object Object to clean
Returns
array Array of cleaned object properties
Definition at line 284 of file api_stockmovements.class.php.
Referenced by index().
_validate ($data) private
Validate fields before create or update object.
Parameters
array | null $data Data to validate
Returns
array
Exceptions
RestException
Definition at line 342 of file api_stockmovements.class.php.
index ($sortfield = "t.rowid", $sortorder = 'ASC', $limit = 100, $page = 0, $sqlfilters = '')
Get properties of a stock movement object.
Return an array with stock movement informations
Parameters
int $id ID of movement
Returns
array|mixed data without useless information
Exceptions
RestException Get a list of stock movement
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Limit for list
int $page Page number
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.product_id:=:1) and (t.date_creation:<:'20160101')"
Returns
array Array of warehouse objects
Exceptions
RestException
Definition at line 96 of file api_stockmovements.class.php.
References DolibarrApi\_checkFilters(), and _cleanObjectDatas().
post ($request_data = null)
Create stock movement object.
You can use the following message to test this RES API: { "product_id": 1, "warehouse_id": 1, "qty": 1, "lot": "", "movementcode": "INV123", "movementlabel": "Inventory 123", "price": 0 }
Parameters
array $request_data Request data
Returns
int ID of stock movement
Definition at line 177 of file api_stockmovements.class.php.
The documentation for this class was generated from the following file:
htdocs/product/stock/class/api_stockmovements.class.php