Dolibarr: htdocs/core/lib/images.lib.php File Reference
images.lib.php File Reference
Set of function for manipulating images.
Functions
image_format_supported ($file)
Return if a filename is file name of a supported image format.
dol_getImageSize ($file, $url=false)
Return size of image file on disk (Supported extensions are gif, jpg, png and bmp)
dol_imageResizeOrCrop ($file, $mode, $newWidth, $newHeight, $src_x=0, $src_y=0)
Resize or crop an image file (Supported extensions are gif, jpg, png and bmp)
dolRotateImage ($file_path)
dolRotateImage if image is a jpg file.
vignette ($file, $maxWidth=160, $maxHeight=120, $extName= '_small', $quality=50, $outdir= 'thumbs', $targetformat=0)
Create a thumbnail from an image file (Supported extensions are gif, jpg, png and bmp).
Detailed Description
Set of function for manipulating images.
Definition in file images.lib.php.
Function Documentation
dol_getImageSize ($file, $url = false)
Return size of image file on disk (Supported extensions are gif, jpg, png and bmp)
Parameters
string $file Full path name of file
bool $url Image with url (true or false)
Returns
array array('width'=>width, 'height'=>height)
Definition at line 75 of file images.lib.php.
References dol_osencode(), and image_format_supported().
Referenced by pdf_standard\Add_PDF_card(), pdf_standardlabel\Add_PDF_label(), pdf_getHeightForLogo(), and pdf_getSizeForImage().
dol_imageResizeOrCrop ($file, $mode, $newWidth, $newHeight, $src_x = 0, $src_y = 0)
Resize or crop an image file (Supported extensions are gif, jpg, png and bmp)
Parameters
string $file Path of file to resize/crop
int $mode 0=Resize, 1=Crop
int $newWidth Largeur maximum que dois faire l'image destination (0=keep ratio)
int $newHeight Hauteur maximum que dois faire l'image destination (0=keep ratio)
int $src_x Position of croping image in source image (not use if mode=0)
int $src_y Position of croping image in source image (not use if mode=0)
Returns
string File name if OK, error message if KO
Definition at line 109 of file images.lib.php.
References dol_osencode(), dol_syslog(), and image_format_supported().
dolRotateImage ($file_path)
dolRotateImage if image is a jpg file.
Currently use an autodetection to know if we can rotate. TODO Introduce a new parameter to force rotate.
Parameters
string $file_path Full path to image to rotate
Returns
boolean Success or not
Definition at line 307 of file images.lib.php.
image_format_supported ($file)
Return if a filename is file name of a supported image format.
Parameters
string $file Filename
Returns
int -1=Not image filename, 0=Image filename but format not supported by PHP, 1=Image filename with format supported by this PHP
Definition at line 38 of file images.lib.php.
Referenced by Ticket\copyFilesForTicket(), dol_add_file_process(), dol_getImageSize(), dol_imageResizeOrCrop(), Product\is_photo_available(), FormFile\list_of_documents(), Product\liste_photos(), CommonObject\show_photos(), and vignette().
vignette ($file, $maxWidth = 160, $maxHeight = 120, $extName = '_small', $quality = 50, $outdir = 'thumbs', $targetformat = 0)
Create a thumbnail from an image file (Supported extensions are gif, jpg, png and bmp).
If file is myfile.jpg, new file may be myfile_small.jpg
Parameters
string $file Path of source file to resize
int $maxWidth Largeur maximum que dois faire la miniature (-1=unchanged, 160 by default)
int $maxHeight Hauteur maximum que dois faire l'image (-1=unchanged, 120 by default)
string $extName Extension to differenciate thumb file name ('_small', '_mini')
int $quality Quality of compression (0=worst, 100=best)
string $outdir Directory where to store thumb
int $targetformat New format of target (IMAGETYPE_GIF, IMAGETYPE_JPG, IMAGETYPE_PNG, IMAGETYPE_BMP, IMAGETYPE_WBMP ... or 0 to keep old format)
Returns
string Full path of thumb or '' if it fails or 'Error...' if it fails
Definition at line 352 of file images.lib.php.
References dol_mkdir(), dol_osencode(), dol_syslog(), getImageFileNameForSize(), and image_format_supported().
Referenced by Ticket\copyFilesForTicket(), FileUpload\createScaledImage(), and dol_add_file_process().