Dolibarr: htdocs/core/menus/standard/empty.php File Reference
empty.php File Reference
This is an example of an empty top menu handler.
Data Structures
class MenuManager
Class to manage menu Auguria.
Functions
print_start_menu_array_empty ()
Output menu entry.
print_start_menu_entry_empty ($idsel, $classname, $showmode)
Output start menu entry.
print_text_menu_entry_empty ($text, $showmode, $url, $id, $idsel, $classname, $atarget)
Output menu entry.
print_end_menu_entry_empty ($showmode)
Output end menu entry.
print_end_menu_array_empty ()
Output menu array.
Detailed Description
This is an example of an empty top menu handler.
Definition in file empty.php.
Function Documentation
print_end_menu_array_empty ()
Output menu array.
Returns
void
Definition at line 599 of file empty.php.
References print.
Referenced by MenuManager\showmenu().
print_end_menu_entry_empty ($showmode)
Output end menu entry.
Parameters
int $showmode 0 = hide, 1 = allowed or 2 = not allowed
Returns
void
Definition at line 585 of file empty.php.
References print.
Referenced by MenuManager\showmenu().
print_start_menu_array_empty ()
Output menu entry.
Returns
void
Definition at line 519 of file empty.php.
References print.
Referenced by MenuManager\showmenu().
print_start_menu_entry_empty ($idsel, $classname, $showmode)
Output start menu entry.
Parameters
string $idsel Text
string $classname String to add a css class
int $showmode 0 = hide, 1 = allowed or 2 = not allowed
Returns
void
Definition at line 535 of file empty.php.
References print.
Referenced by MenuManager\showmenu().
print_text_menu_entry_empty ($text, $showmode, $url, $id, $idsel, $classname, $atarget)
Output menu entry.
Parameters
string $text Text
int $showmode 1 or 2
string $url Url
string $id Id
string $idsel Id sel
string $classname Class name
string $atarget Target
Returns
void
Definition at line 557 of file empty.php.
References dol_escape_htmltag(), and print.
Referenced by MenuManager\showmenu().