Dolibarr: Invoices Class Reference
Invoices Class Reference
Public Member Functions
__construct ()
Constructor.
get ($id, $contact_list=1)
Get properties of a invoice object.
post ($request_data=null)
Create invoice object.
createInvoiceFromOrder ($orderid)
Create an invoice using an existing order.
getLines ($id)
Get lines of an invoice.
putLine ($id, $lineid, $request_data=null)
Update a line to a given invoice.
postContact ($id, $contactid, $type)
Add a contact type of given invoice.
deleteContact ($id, $rowid)
Delete a contact type of given invoice.
deleteLine ($id, $lineid)
Deletes a line of a given invoice.
put ($id, $request_data=null)
Update invoice.
delete ($id)
Delete invoice.
postLine ($id, $request_data=null)
Add a line to a given invoice.
addContact ($id, $fk_socpeople, $type_contact, $source, $notrigger=0)
Adds a contact to an invoice.
settodraft ($id, $idwarehouse=-1)
Sets an invoice as draft.
validate ($id, $idwarehouse=0, $notrigger=0)
Validate an invoice.
settopaid ($id, $close_code= '', $close_note= '')
Sets an invoice as paid.
settounpaid ($id)
Sets an invoice as unpaid.
markAsCreditAvailable ($id)
Create a discount (credit available) for a credit note or a deposit.
useDiscount ($id, $discountid)
Add a discount line into an invoice (as an invoice line) using an existing absolute discount.
useCreditNote ($id, $discountid)
Add an available credit note discount to payments of an existing invoice.
getPayments ($id)
Get list of payments of a given invoice.
addPayment ($id, $datepaye, $paiementid, $closepaidinvoices, $accountid, $num_paiement= '', $comment= '', $chqemetteur= '', $chqbank= '')
Add payment line to a specific invoice with the remain to pay as amount.
addPaymentDistributed ($arrayofamounts, $datepaye, $paiementid, $closepaidinvoices, $accountid, $num_paiement= '', $comment= '', $chqemetteur= '', $chqbank= '')
Add a payment to pay partially or completely one or several invoices.
Public Member Functions inherited from DolibarrApi
__construct ($db, $cachedir= '', $refreshCache=false)
Constructor.
Protected Member Functions
_cleanObjectDatas ($object)
Clean sensible object datas.
Protected Member Functions inherited from DolibarrApi
_cleanObjectDatas ($object)
Executed method when API is called without parameter.
_checkFilters ($sqlfilters)
Return if a $sqlfilters parameter is valid.
Private Member Functions
_validate ($data)
Validate fields before create or update object.
Additional Inherited Members
Static Protected Member Functions inherited from DolibarrApi
static _checkAccessToResource ($resource, $resource_id=0, $dbtablename= '', $feature2= '', $dbt_keyfield= 'fk_soc', $dbt_select= 'rowid')
Check user access to a resource.
static _forge_criteria_callback ($matches)
Function to forge a SQL criteria.
Detailed Description
Definition at line 28 of file api_invoices.class.php.
Member Function Documentation
_cleanObjectDatas ($object) protected
Clean sensible object datas.
Parameters
object $object Object to clean
Returns
array Array of cleaned object properties
Definition at line 1483 of file api_invoices.class.php.
Referenced by addContact(), createInvoiceFromOrder(), deleteContact(), get(), getLines(), markAsCreditAvailable(), postContact(), putLine(), settodraft(), settopaid(), settounpaid(), and validate().
_validate ($data) private
Validate fields before create or update object.
Parameters
array | null $data Datas to validate
Returns
array
Exceptions
RestException
Definition at line 1506 of file api_invoices.class.php.
Referenced by post().
addContact ($id, $fk_socpeople, $type_contact, $source, $notrigger = 0)
Adds a contact to an invoice.
Parameters
int $id Order ID
int $fk_socpeople Id of thirdparty contact (if source = 'external') or id of user (if souce = 'internal') to link
string $type_contact Type of contact (code). Must a code found into table llx_c_type_contact. For example: BILLING
string $source external=Contact extern (llx_socpeople), internal=Contact intern (llx_user)
int $notrigger Disable all triggers
POST {id}/contacts
Returns
array
Exceptions
200
304
401
404
500
Definition at line 684 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
addPayment ($id, $datepaye, $paiementid, $closepaidinvoices, $accountid, $num_paiement = '', $comment = '', $chqemetteur = '', $chqbank = '')
Add payment line to a specific invoice with the remain to pay as amount.
Parameters
int $id Id of invoice
string $datepaye { body} Payment date { timestamp}
int $paiementid { body} Payment mode Id { 1}
string $closepaidinvoices { body} Close paid invoices { yes,no}
int $accountid { body} Account Id { 1}
string $num_paiement { body} Payment number (optional)
string $comment { body} Note (optional)
string $chqemetteur { body} Payment issuer (mandatory if paiementcode = 'CHQ')
string $chqbank { body} Issuer bank name (optional)
POST {id}/payments
Returns
int Payment ID
Exceptions
400
401
404
Definition at line 1251 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource(), db, dol_getIdFromCode(), price2num(), and Facture\TYPE_CREDIT_NOTE.
addPaymentDistributed ($arrayofamounts, $datepaye, $paiementid, $closepaidinvoices, $accountid, $num_paiement = '', $comment = '', $chqemetteur = '', $chqbank = '')
Add a payment to pay partially or completely one or several invoices.
Warning: Take care that all invoices are owned by the same customer. Example of value for parameter arrayofamounts: {"1": "99.99", "2": "10"}
Parameters
array $arrayofamounts { body} Array with id of invoices with amount to pay for each invoice
string $datepaye { body} Payment date { timestamp}
int $paiementid { body} Payment mode Id { 1}
string $closepaidinvoices { body} Close paid invoices { yes,no}
int $accountid { body} Account Id { 1}
string $num_paiement { body} Payment number (optional)
string $comment { body} Note (optional)
string $chqemetteur { body} Payment issuer (mandatory if paiementcode = 'CHQ')
string $chqbank { body} Issuer bank name (optional)
POST /paymentsdistributed
Returns
int Payment ID
Exceptions
400
401
403
404
Definition at line 1371 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource(), db, dol_getIdFromCode(), price2num(), and Facture\TYPE_CREDIT_NOTE.
createInvoiceFromOrder ($orderid)
Create an invoice using an existing order.
Parameters
int $orderid Id of the order
POST /createfromorder/{orderid}
Returns
int
Exceptions
400
401
404
405
Definition at line 250 of file api_invoices.class.php.
References _cleanObjectDatas(), and db.
delete ($id)
Delete invoice.
Parameters
int $id Invoice ID
Returns
array
Definition at line 550 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource().
deleteContact ($id, $rowid)
Delete a contact type of given invoice.
Parameters
int $id Id of invoice to update
int $rowid Row key of the contact in the array contact_ids.
DELETE {id}/contact/{rowid}
Returns
int
Exceptions
401
404
500
Definition at line 431 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
deleteLine ($id, $lineid)
Deletes a line of a given invoice.
Parameters
int $id Id of invoice
int $lineid Id of the line to delete
DELETE {id}/lines/{lineid}
Returns
array
Exceptions
400
401
404
405
Definition at line 471 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource().
get ($id, $contact_list = 1)
Get properties of a invoice object.
Return an array with invoice informations
Parameters
int $id ID of invoice
int $contact_list 0:Return array contains all properties, 1:Return array contains just id
Returns
array|mixed data without useless information
Exceptions
RestException
Definition at line 64 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource(), DolibarrApi\_checkFilters(), _cleanObjectDatas(), and price2num().
getLines ($id)
Get lines of an invoice.
Parameters
int $id Id of invoice
GET {id}/lines
Returns
int
Definition at line 288 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
getPayments ($id)
Get list of payments of a given invoice.
Parameters
int $id Id of invoice
GET {id}/payments
Returns
array
Exceptions
400
401
404
405
Definition at line 1203 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource().
markAsCreditAvailable ($id)
Create a discount (credit available) for a credit note or a deposit.
Parameters
int $id Invoice ID POST {id}/markAsCreditAvailable
Returns
array An invoice object
Exceptions
200
304
401
404
500
Definition at line 937 of file api_invoices.class.php.
References $resql, DolibarrApi\_checkAccessToResource(), _cleanObjectDatas(), db, dol_print_error(), Facture\TYPE_CREDIT_NOTE, Facture\TYPE_DEPOSIT, Facture\TYPE_REPLACEMENT, Facture\TYPE_SITUATION, and Facture\TYPE_STANDARD.
post ($request_data = null)
Create invoice object.
Parameters
array $request_data Request datas
Returns
int ID of invoice
Definition at line 207 of file api_invoices.class.php.
References _validate(), and dol_now().
postContact ($id, $contactid, $type)
Add a contact type of given invoice.
Parameters
int $id Id of invoice to update
int $contactid Id of contact to add
string $type Type of the contact (BILLING, SHIPPING, CUSTOMER)
POST {id}/contact/{contactid}/{type}
Returns
int
Exceptions
401
404
Definition at line 389 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
postLine ($id, $request_data = null)
Add a line to a given invoice.
Exemple of POST query : { "desc": "Desc", "subprice": "1.00000000", "qty": "1", "tva_tx": "20.000", "localtax1_tx": "0.000", "localtax2_tx": "0.000", "fk_product": "1", "remise_percent": "0", "date_start": "", "date_end": "", "fk_code_ventilation": 0, "info_bits": "0", "fk_remise_except": null, "product_type": "1", "rang": "-1", "special_code": "0", "fk_parent_line": null, "fk_fournprice": null, "pa_ht": "0.00000000", "label": "", "array_options": [], "situation_percent": "100", "fk_prev_id": null, "fk_unit": null }
Parameters
int $id Id of invoice
array $request_data InvoiceLine data
POST {id}/lines
Returns
int
Exceptions
200
401
404
400
Definition at line 600 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource(), and getMarginInfos().
put ($id, $request_data = null)
Update invoice.
Parameters
int $id Id of invoice to update
array $request_data Datas
Returns
int
Definition at line 509 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource().
putLine ($id, $lineid, $request_data = null)
Update a line to a given invoice.
Parameters
int $id Id of invoice to update
int $lineid Id of line to update
array $request_data InvoiceLine data
PUT {id}/lines/{lineid}
Returns
object
Exceptions
200
304
401
404
Definition at line 326 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
settodraft ($id, $idwarehouse = -1)
Sets an invoice as draft.
Parameters
int $id Order ID
int $idwarehouse Warehouse ID
POST {id}/settodraft
Returns
array
Exceptions
200
304
401
404
500
Definition at line 734 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
settopaid ($id, $close_code = '', $close_note = '')
Sets an invoice as paid.
Parameters
int $id Order ID
string $close_code Code renseigne si on classe a payee completement alors que paiement incomplet (cas escompte par exemple)
string $close_note Commentaire renseigne si on classe a payee alors que paiement incomplet (cas escompte par exemple)
POST {id}/settopaid
Returns
array An invoice object
Exceptions
200
304
401
404
500
Definition at line 837 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
settounpaid ($id)
Sets an invoice as unpaid.
Parameters
int $id Order ID
POST {id}/settounpaid
Returns
array An invoice object
Exceptions
200
304
401
404
500
Definition at line 888 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
useCreditNote ($id, $discountid)
Add an available credit note discount to payments of an existing invoice.
Note that this consume the credit note.
Parameters
int $id Id of invoice
int $discountid Id of a discount coming from a credit note
POST {id}/usecreditnote/{discountid}
Returns
int
Exceptions
400
401
404
405
Definition at line 1158 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource(), and db.
useDiscount ($id, $discountid)
Add a discount line into an invoice (as an invoice line) using an existing absolute discount.
Note that this consume the discount.
Parameters
int $id Id of invoice
int $discountid Id of discount
POST {id}/usediscount/{discountid}
Returns
int
Exceptions
400
401
404
405
Definition at line 1112 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource().
validate ($id, $idwarehouse = 0, $notrigger = 0)
Validate an invoice.
If you get a bad value for param notrigger check that ou provide this in body { "idwarehouse": 0, "notrigger": 0 }
Parameters
int $id Invoice ID
int $idwarehouse Warehouse ID
int $notrigger 1=Does not execute triggers, 0= execute triggers
POST {id}/validate
Returns
array
Definition at line 786 of file api_invoices.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
The documentation for this class was generated from the following file:
htdocs/compta/facture/class/api_invoices.class.php