Dolibarr: PriceGlobalVariableUpdater Class Reference
PriceGlobalVariableUpdater Class Reference
Class for price global variable updaters table.
Public Member Functions
__construct ($db)
Constructor.
create ($user, $notrigger=0)
Create object into database.
fetch ($id)
Load object in memory from the database.
update ($user=0, $notrigger=0)
Update object into database.
delete ($rowid, $user, $notrigger=0)
Delete object in database.
initAsSpecimen ()
Initialise object with example values Id must be 0 if object instance is a specimen.
getLastUpdated ()
Returns the last updated time in string html format, returns "never" if its less than 1.
checkParameters ()
Checks if all parameters are in order.
listUpdaters ()
List all price global variables.
listPendingUpdaters ()
List all updaters which need to be processed.
process ()
Handles the processing of this updater.
update_next_update ($next_update, $user=0, $notrigger=0)
Update next_update into database.
update_status ($last_status, $user=0, $notrigger=0)
Update last_status into database.
Data Fields
$types =array(0, 1)
Updater types.
$update_min = 5
Minimal update rate.
$update_interval
Interval in mins.
$next_update
Next update timestamp.
Detailed Description
Class for price global variable updaters table.
Definition at line 30 of file price_global_variable_updater.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDb $db Database handler
Definition at line 83 of file price_global_variable_updater.class.php.
References db.
Member Function Documentation
checkParameters ()
Checks if all parameters are in order.
Returns
void
Definition at line 355 of file price_global_variable_updater.class.php.
References $update_min, description, and type.
Referenced by create(), fetch(), process(), update(), update_next_update(), and update_status().
create ($user, $notrigger = 0)
Create object into database.
Parameters
User $user User that creates
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, Id of created object if OK
Definition at line 96 of file price_global_variable_updater.class.php.
References $resql, checkParameters(), db, description, and dol_syslog().
delete ($rowid, $user, $notrigger = 0)
Delete object in database.
Parameters
int $rowid Row id of global variable
User $user User that deletes
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 268 of file price_global_variable_updater.class.php.
References $resql, db, and dol_syslog().
fetch ($id)
Load object in memory from the database.
Parameters
int $id Id object
Returns
int < 0 if KO, 0 if OK but not found, > 0 if OK
Definition at line 162 of file price_global_variable_updater.class.php.
References $resql, checkParameters(), db, description, dol_syslog(), and type.
getLastUpdated ()
Returns the last updated time in string html format, returns "never" if its less than 1.
Returns
string
Definition at line 339 of file price_global_variable_updater.class.php.
References dol_print_date().
initAsSpecimen ()
Initialise object with example values Id must be 0 if object instance is a specimen.
Returns
void
Definition at line 322 of file price_global_variable_updater.class.php.
References description, and type.
listPendingUpdaters ()
List all updaters which need to be processed.
Returns
array Array of price global variable updaters
Definition at line 415 of file price_global_variable_updater.class.php.
References $resql, db, and dol_syslog().
listUpdaters ()
List all price global variables.
Returns
array Array of price global variable updaters
Definition at line 374 of file price_global_variable_updater.class.php.
References $resql, db, and dol_syslog().
process ()
Handles the processing of this updater.
Returns
int <0 if KO, 0 if OK but no global variable found, >0 if OK
Definition at line 457 of file price_global_variable_updater.class.php.
References checkParameters(), db, dol_syslog(), getURLContent(), and type.
update ($user = 0, $notrigger = 0)
Update object into database.
Parameters
User $user User that modifies
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 205 of file price_global_variable_updater.class.php.
References $resql, checkParameters(), db, description, and dol_syslog().
update_next_update ($next_update, $user = 0, $notrigger = 0)
Update next_update into database.
Parameters
string $next_update Next update to write
User $user User that modifies
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 572 of file price_global_variable_updater.class.php.
References $next_update, $resql, checkParameters(), db, and dol_syslog().
update_status ($last_status, $user = 0, $notrigger = 0)
Update last_status into database.
Parameters
string $last_status Status to write
User $user User that modifies
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 618 of file price_global_variable_updater.class.php.
References $resql, checkParameters(), db, and dol_syslog().
The documentation for this class was generated from the following file:
htdocs/product/dynamic_price/class/price_global_variable_updater.class.php