Dolibarr: mod_facture_terre Class Reference
mod_facture_terre Class Reference
Classe du modele de numerotation de reference de facture Terre.
Public Member Functions
__construct ()
Constructor.
info ()
Returns the description of the numbering model.
getExample ()
Renvoi un exemple de numerotation.
canBeActivated ()
Test si les numeros deja en vigueur dans la base ne provoquent pas de de conflits qui empechera cette numerotation de fonctionner.
getNextValue ($objsoc, $invoice, $mode= 'next')
Return next value not used or last value used.
getNumRef ($objsoc, $objforref, $mode= 'next')
Return next free value.
Public Member Functions inherited from ModeleNumRefFactures
isEnabled ()
Return if a module can be used or not.
info ()
Renvoi la description par defaut du modele de numerotation.
getExample ()
Renvoi un exemple de numerotation.
canBeActivated ()
Test si les numeros deja en vigueur dans la base ne provoquent pas de conflits qui empecheraient cette numerotation de fonctionner.
getNextValue ($objsoc, $facture)
Renvoi prochaine valeur attribuee.
getVersion ()
Renvoi version du modele de numerotation.
Detailed Description
Classe du modele de numerotation de reference de facture Terre.
Definition at line 31 of file mod_facture_terre.php.
Member Function Documentation
canBeActivated ()
Test si les numeros deja en vigueur dans la base ne provoquent pas de de conflits qui empechera cette numerotation de fonctionner.
Returns
boolean false si conflit, true si ok
Definition at line 102 of file mod_facture_terre.php.
References $resql.
getExample ()
Renvoi un exemple de numerotation.
Returns
string Example
Definition at line 91 of file mod_facture_terre.php.
getNextValue ($objsoc, $invoice, $mode = 'next')
Return next value not used or last value used.
Parameters
Societe $objsoc Object third party
Facture $invoice Object invoice
string $mode 'next' for next value or 'last' for last value
Returns
string Value
Definition at line 183 of file mod_facture_terre.php.
References $resql, dol_print_error(), and dol_syslog().
Referenced by getNumRef().
getNumRef ($objsoc, $objforref, $mode = 'next')
Return next free value.
Parameters
Societe $objsoc Object third party
string $objforref Object for number to search
string $mode 'next' for next value or 'last' for last value
Returns
string Next free value
Definition at line 255 of file mod_facture_terre.php.
References getNextValue().
info ()
Returns the description of the numbering model.
Returns
string Texte descripif
Definition at line 79 of file mod_facture_terre.php.
The documentation for this class was generated from the following file:
htdocs/core/modules/facture/mod_facture_terre.php