Dolibarr: htdocs/core/lib/product.lib.php File Reference
product.lib.php File Reference
Ensemble de fonctions de base pour le module produit et service.
Functions
product_prepare_head ($object)
Prepare array with list of tabs.
productlot_prepare_head ($object)
Prepare array with list of tabs.
product_admin_prepare_head ()
Return array head with list of tabs to view object informations.
product_lot_admin_prepare_head ()
Return array head with list of tabs to view object informations.
show_stats_for_company ($product, $socid)
Show stats for company.
measuring_units_string ($unit, $measuring_style= '')
Return translation label of a unit key.
measuring_units_squared ($unit)
Transform a given unit into the square of that unit, if known.
measuring_units_cubed ($unit)
Transform a given unit into the cube of that unit, if known.
Detailed Description
Ensemble de fonctions de base pour le module produit et service.
Definition in file product.lib.php.
Function Documentation
measuring_units_cubed ($unit)
Transform a given unit into the cube of that unit, if known.
Parameters
int $unit Unit key (-3,-2,-1,0,98,99...)
Returns
int Cubed unit key (-9,-6,-3,0,88,89...)
See also
formproduct->selectMeasuringUnits
Definition at line 540 of file product.lib.php.
Referenced by Product\update().
measuring_units_squared ($unit)
Transform a given unit into the square of that unit, if known.
Parameters
int $unit Unit key (-3,-2,-1,0,98,99...)
Returns
int Squared unit key (-6,-4,-2,0,98,99...)
See also
formproduct->selectMeasuringUnits
Definition at line 520 of file product.lib.php.
Referenced by Product\update().
measuring_units_string ($unit, $measuring_style = '')
Return translation label of a unit key.
Parameters
int $unit ID of unit (rowid in llx_c_units table)
string $measuring_style Style of unit: weight, volume,...
Returns
string Unit string
See also
formproduct->selectMeasuringUnits
Definition at line 491 of file product.lib.php.
Referenced by ActionsCardProduct\assign_values(), CommonDocGenerator\get_substitutionarray_shipment(), CommonDocGenerator\get_substitutionarray_shipment_lines(), Product\getNomUrl(), showDimensionInBestUnit(), pdf_squille\write_file(), pdf_espadon\write_file(), and pdf_rouget\write_file().
product_admin_prepare_head ()
Return array head with list of tabs to view object informations.
Returns
array head array with tabs
Definition at line 262 of file product.lib.php.
References complete_head_from_modules().
product_lot_admin_prepare_head ()
Return array head with list of tabs to view object informations.
Returns
array head array with tabs
Definition at line 307 of file product.lib.php.
References complete_head_from_modules().
product_prepare_head ($object)
Prepare array with list of tabs.
Parameters
Product $object Object related to tabs
Returns
array Array of tabs to show
Definition at line 35 of file product.lib.php.
References complete_head_from_modules(), Link\count(), dol_dir_list(), dol_sanitizeFileName(), get_exdir(), Product\TYPE_PRODUCT, and Product\TYPE_SERVICE.
Referenced by ActionsCardService\assign_values(), and ActionsCardProduct\assign_values().
productlot_prepare_head ($object)
Prepare array with list of tabs.
Parameters
ProductLot $object Object related to tabs
Returns
array Array of tabs to show
Definition at line 209 of file product.lib.php.
References complete_head_from_modules(), Link\count(), dol_dir_list(), and dol_sanitizeFileName().
show_stats_for_company ($product, $socid)
Show stats for company.
Parameters
Product $product Product object
int $socid Thirdparty id
Returns
integer NB of lines shown into array
Definition at line 339 of file product.lib.php.
References dol_print_error(), img_object(), and print.