Dolibarr: htdocs/opensurvey/fonctions.php File Reference
fonctions.php File Reference
Module opensurvey
Functions for module.
Functions
opensurvey_prepare_head (Opensurveysondage $object)
Returns an array with the tabs for the "Opensurvey poll" section It loads tabs from modules looking for the entity Opensurveyso.
llxHeaderSurvey ($title, $head="", $disablejs=0, $disablehead=0, $arrayofjs= '', $arrayofcss= '')
Show header for new member.
llxFooterSurvey ()
Show footer for new member.
get_server_name ()
get_server_name
issetAndNoEmpty ($name, $tableau=null)
Fonction vérifiant l'existance et la valeur non vide d'une clé d'un tableau.
getUrlSondage ($id, $admin=false)
Fonction permettant de générer les URL pour les sondage.
dol_survey_random ($car)
Generate a random id.
ajouter_sondage ()
Add a poll.
Detailed Description
Functions for module.
Definition in file fonctions.php.
Function Documentation
ajouter_sondage ()
Add a poll.
Returns
void
Definition at line 195 of file fonctions.php.
References dol_buildpath(), dol_print_error(), and dol_survey_random().
dol_survey_random ($car)
Generate a random id.
Parameters
string $car Char to generate key
Returns
string
Definition at line 179 of file fonctions.php.
Referenced by ajouter_sondage().
get_server_name ()
get_server_name
Returns
string URL to use
Definition at line 120 of file fonctions.php.
Referenced by getUrlSondage().
getUrlSondage ($id, $admin = false)
Fonction permettant de générer les URL pour les sondage.
Parameters
string $id L'identifiant du sondage
bool $admin True pour générer une URL pour l'administration d'un sondage, False pour un URL publique
Returns
string L'url pour le sondage
Definition at line 161 of file fonctions.php.
References get_server_name().
issetAndNoEmpty ($name, $tableau = null)
Fonction vérifiant l'existance et la valeur non vide d'une clé d'un tableau.
Parameters
string $name La clé à tester
array $tableau Le tableau où rechercher la clé ($_POST par défaut)
Returns
bool Vrai si la clé existe et renvoie une valeur non vide
Definition at line 144 of file fonctions.php.
llxFooterSurvey ()
Show footer for new member.
Returns
void
Definition at line 102 of file fonctions.php.
References dol_htmloutput_events(), print, and printCommonFooter().
llxHeaderSurvey ($title, $head = "", $disablejs = 0, $disablehead = 0, $arrayofjs = '', $arrayofcss = '')
Show header for new member.
Parameters
string $title Title
string $head Head array
int $disablejs More content into html header
int $disablehead More content into html header
array $arrayofjs Array of complementary js files
array $arrayofcss Array of complementary css files
Returns
void
Definition at line 72 of file fonctions.php.
References print, and top_htmlhead().
opensurvey_prepare_head (Opensurveysondage $object)
Returns an array with the tabs for the "Opensurvey poll" section It loads tabs from modules looking for the entity Opensurveyso.
Parameters
Opensurveysondage $object Current viewing poll
Returns
array Tabs for the opensurvey section
Definition at line 32 of file fonctions.php.
References complete_head_from_modules().