Dolibarr: RssParser Class Reference
RssParser Class Reference
Class to parse RSS files.
Public Member Functions
__construct ($db)
Constructor.
getFormat ()
getFormat
getUrlRss ()
getUrlRss
getLanguage ()
getLanguage
getGenerator ()
getGenerator
getCopyright ()
getCopyright
getLastBuildDate ()
getLastBuildDate
getImageUrl ()
getImageUrl
getLink ()
getLink
getTitle ()
getTitle
getDescription ()
getDescription
getLastFetchDate ()
getLastFetchDate
getItems ()
getItems
parser ($urlRSS, $maxNb=0, $cachedelay=60, $cachedir= '')
Parse rss URL.
feed_start_element ($p, $element, &$attrs)
Triggered when opened tag is found.
feed_cdata ($p, $text)
Triggered when CDATA is found.
feed_end_element ($p, $el)
Triggered when closed tag is found.
concat (&$str1, $str2="")
To concat 2 string with no warning if an operand is not defined.
append_content ($text)
Enter description here ...
append ($el, $text)
smart append - field and namespace aware
Detailed Description
Class to parse RSS files.
Definition at line 27 of file rssparser.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 62 of file rssparser.class.php.
References db.
Member Function Documentation
append ($el, $text)
smart append - field and namespace aware
Parameters
string $el El
string $text Text
Returns
void
Definition at line 702 of file rssparser.class.php.
References concat().
Referenced by feed_cdata(), and feed_start_element().
append_content ($text)
Enter description here ...
Parameters
string $text Text
Returns
void
Definition at line 684 of file rssparser.class.php.
References concat().
Referenced by feed_cdata(), feed_end_element(), and feed_start_element().
concat (& $str1, $str2 = "")
To concat 2 string with no warning if an operand is not defined.
Parameters
string $str1 Str1
string $str2 Str2
Returns
string String cancatenated
Definition at line 669 of file rssparser.class.php.
Referenced by append(), and append_content().
feed_cdata ($p, $text)
Triggered when CDATA is found.
Parameters
string $p P
string $text Tag
Returns
void
Definition at line 592 of file rssparser.class.php.
References append(), and append_content().
feed_end_element ($p, $el)
Triggered when closed tag is found.
Parameters
string $p P
string $el Tag
Returns
void
Definition at line 614 of file rssparser.class.php.
References append_content().
feed_start_element ($p, $element, & $attrs)
Triggered when opened tag is found.
Parameters
string $p Start
string $element Tag
array $attrs Attributes of tags
Returns
void
Definition at line 473 of file rssparser.class.php.
References append(), and append_content().
getCopyright ()
getCopyright
Returns
string
Definition at line 109 of file rssparser.class.php.
getDescription ()
getDescription
Returns
string
Definition at line 154 of file rssparser.class.php.
getFormat ()
getFormat
Returns
string
Definition at line 72 of file rssparser.class.php.
getGenerator ()
getGenerator
Returns
string
Definition at line 100 of file rssparser.class.php.
getImageUrl ()
getImageUrl
Returns
string
Definition at line 127 of file rssparser.class.php.
getItems ()
getItems
Returns
string
Definition at line 172 of file rssparser.class.php.
getLanguage ()
getLanguage
Returns
string
Definition at line 91 of file rssparser.class.php.
getLastBuildDate ()
getLastBuildDate
Returns
string
Definition at line 118 of file rssparser.class.php.
getLastFetchDate ()
getLastFetchDate
Returns
string
Definition at line 163 of file rssparser.class.php.
getLink ()
getLink
Returns
string
Definition at line 136 of file rssparser.class.php.
getTitle ()
getTitle
Returns
string
Definition at line 145 of file rssparser.class.php.
getUrlRss ()
getUrlRss
Returns
string
Definition at line 82 of file rssparser.class.php.
parser ($urlRSS, $maxNb = 0, $cachedelay = 60, $cachedir = '')
Parse rss URL.
Parameters
string $urlRSS Url to parse
int $maxNb Max nb of records to get (0 for no limit)
int $cachedelay 0=No cache, nb of seconds we accept cache files (cachedir must also be defined)
string $cachedir Directory where to save cache file
Returns
int <0 if KO, >0 if OK
Definition at line 187 of file rssparser.class.php.
References dol_filemtime(), dol_hash(), dol_is_dir(), dol_is_url(), dol_mkdir(), dol_now(), dol_syslog(), if, print, and xml2php().
The documentation for this class was generated from the following file:
htdocs/core/class/rssparser.class.php