Dolibarr: htdocs/core/lib/security2.lib.php File Reference
security2.lib.php File Reference
Set of function used for dolibarr security (not common functions).
Functions
dol_getwebuser ($mode)
Return user/group account of web server.
checkLoginPassEntity ($usertotest, $passwordtotest, $entitytotest, $authmode, $context= '')
Return a login if login/pass was successfull.
if(!function_exists('dol_loginfunction')) makesalt ($type=CRYPT_SALT_LENGTH)
Fonction pour initialiser un salt pour la fonction crypt.
encodedecode_dbpassconf ($level=0)
Encode or decode database password in config file.
getRandomPassword ($generic=false, $replaceambiguouschars=null, $length=32)
Return a generated password using default module.
Detailed Description
Set of function used for dolibarr security (not common functions).
Warning, this file must not depends on other library files, except function.lib.php because it is used at low code level.
Definition in file security2.lib.php.
Function Documentation
checkLoginPassEntity ($usertotest, $passwordtotest, $entitytotest, $authmode, $context = '')
Return a login if login/pass was successfull.
Parameters
string $usertotest Login value to test
string $passwordtotest Password value to test
string $entitytotest Instance of data we must check
array $authmode Array list of selected authentication mode array('http', 'dolibarr', 'xxx'...)
string $context Context checkLoginPassEntity was created for ('api', 'dav', '')
Returns
string Login or ''
Show Dolibarr default login page. Part of this code is also duplicated into main.inc.php::top_htmlhead
Parameters
Translate $langs Lang object (must be initialized by a new).
Conf $conf Conf object
Societe $mysoc Company object
Returns
void
Definition at line 53 of file security2.lib.php.
References $dol_url_root, complete_substitutions_array(), dol_buildpath(), dol_htmlcleanlastbr(), dol_osencode(), dol_syslog(), getCommonSubstitutionArray(), GETPOST(), img_picto(), and make_substitutions().
Referenced by analyseVarsForSqlAndScriptsInjection(), check_authentication(), Login\index(), and Auth\verif().
dol_getwebuser ($mode)
Return user/group account of web server.
Parameters
string $mode 'user' or 'group'
Returns
string Return user or group of web server
Definition at line 35 of file security2.lib.php.
encodedecode_dbpassconf ($level = 0)
Encode or decode database password in config file.
Parameters
int $level Encode level: 0 no encoding, 1 encoding
Returns
int <0 if KO, >0 if OK
Definition at line 340 of file security2.lib.php.
References conf(), dol_decode(), dol_encode(), and dol_syslog().
getRandomPassword ($generic = false, $replaceambiguouschars = null, $length = 32)
Return a generated password using default module.
Parameters
boolean $generic true=Create generic password (32 chars/numbers), false=Use the configured password generation module
array $replaceambiguouschars Discard ambigous characters. For example array('I').
int $length Length of random string (Used only if $generic is true)
Returns
string New value for password
See also
dol_hash()
Definition at line 449 of file security2.lib.php.
Referenced by addFileIntoDatabaseIndex(), ActionsAdherentCardCommon\assign_values(), ActionsContactCardCommon\assign_values(), BlockedLog\getSignature(), InterfaceIFTTT\runTrigger(), Adherent\setPassword(), and User\setPassword().
if (!function_exists('dol_loginfunction')) makesalt ($type = CRYPT_SALT_LENGTH)
Fonction pour initialiser un salt pour la fonction crypt.
Parameters
int $type 2=>renvoi un salt pour cryptage DES 12=>renvoi un salt pour cryptage MD5 non defini=>renvoi un salt pour cryptage par defaut
Returns
string Salt string
Definition at line 313 of file security2.lib.php.
References dol_strlen(), and dol_syslog().
Referenced by MailmanSpip\add_to_spip().