Dolibarr: AccountancyCategory Class Reference
AccountancyCategory Class Reference
Class to manage categories of an accounting account.
Public Member Functions
__construct ($db)
Constructor.
create ($user, $notrigger=0)
Create object into database.
fetch ($id, $code= '', $label= '')
Load object in memory from database.
update ($user=null, $notrigger=0)
Update object into database.
delete ($user, $notrigger=0)
Delete object in database.
display ($id)
Function to select all accounting accounts from an accounting category.
getCptBK ($id)
Function to select accounting category of an accounting account present in chart of accounts.
getAccountsWithNoCategory ($id)
Function to select accounting category of an accounting account present in chart of accounts.
updateAccAcc ($id_cat, $cpts=array())
Function to add an accounting account in an accounting category.
deleteCptCat ($cpt_id)
Function to delete an accounting account from an accounting category.
getCatsCpts ()
Function to know all category from accounting account.
getSumDebitCredit ($cpt, $date_start, $date_end, $sens, $thirdparty_code= 'nofilter', $month=0, $year=0)
Function to show result of an accounting account from the ledger with a direction and a period.
getCats ($categorytype=-1)
Return list of personalized groups that are active.
getCptsCat ($cat_id, $predefinedgroupwhere= '')
Get all accounting account of a group.
Detailed Description
Class to manage categories of an accounting account.
Definition at line 32 of file accountancycategory.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDb $db Database handler
Definition at line 132 of file accountancycategory.class.php.
References db.
Member Function Documentation
create ($user, $notrigger = 0)
Create object into database.
Parameters
User $user User that create
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, Id of created object if OK
Definition at line 145 of file accountancycategory.class.php.
References $resql, db, dol_syslog(), and label.
delete ($user, $notrigger = 0)
Delete object in database.
Parameters
User $user User that delete
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 382 of file accountancycategory.class.php.
References $resql, db, and dol_syslog().
deleteCptCat ($cpt_id)
Function to delete an accounting account from an accounting category.
Parameters
int $cpt_id Id of accounting account
Returns
int <0 if KO, >0 if OK
Definition at line 636 of file accountancycategory.class.php.
References $resql, db, and dol_syslog().
array Lines display ($id)
Function to select all accounting accounts from an accounting category.
Parameters
int $id Id
Returns
int <0 if KO, 0 if not found, >0 if OK
Definition at line 436 of file accountancycategory.class.php.
References $resql, db, and dol_syslog().
fetch ($id, $code = '', $label = '')
Load object in memory from database.
Parameters
int $id Id object
string $code Code
string $label Label
Returns
int <0 if KO, >0 if OK
Definition at line 242 of file accountancycategory.class.php.
References $resql, db, dol_syslog(), and label.
getAccountsWithNoCategory ($id)
Function to select accounting category of an accounting account present in chart of accounts.
Parameters
int $id Id of category to know which account to exclude
Returns
int <0 if KO, 0 if not found, >0 if OK
Definition at line 521 of file accountancycategory.class.php.
References $resql, db, and dol_syslog().
getCats ($categorytype = -1)
Return list of personalized groups that are active.
Parameters
int $categorytype -1=All, 0=Only non computed groups, 1=Only computed groups
Returns
array|int Array of groups or -1 if error
Definition at line 804 of file accountancycategory.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
getCatsCpts ()
Function to know all category from accounting account.
Returns
array|integer Result in table (array), -1 if KO
Definition at line 673 of file accountancycategory.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
getCptBK ($id)
Function to select accounting category of an accounting account present in chart of accounts.
Parameters
int $id Id category
Returns
int <0 if KO, 0 if not found, >0 if OK
Definition at line 472 of file accountancycategory.class.php.
References $resql, db, and dol_syslog().
getCptsCat ($cat_id, $predefinedgroupwhere = '')
Get all accounting account of a group.
You must choose between first parameter (personalized group) or the second (free criteria filter)
Parameters
int $cat_id Id if personalized accounting group/category
string $predefinedgroupwhere Sql criteria filter to select accounting accounts
Returns
array|int Array of accounting accounts or -1 if error
Definition at line 862 of file accountancycategory.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
getSumDebitCredit ($cpt, $date_start, $date_end, $sens, $thirdparty_code = 'nofilter', $month = 0, $year = 0)
Function to show result of an accounting account from the ledger with a direction and a period.
Parameters
int | array $cpt Accounting account or array of accounting account
string $date_start Date start
string $date_end Date end
int $sens Sens of the account: 0: credit - debit (use this by default), 1: debit - credit
string $thirdparty_code Thirdparty code
int $month Specifig month - Can be empty
int $year Specifig year - Can be empty
Returns
integer <0 if KO, >= 0 if OK
Definition at line 734 of file accountancycategory.class.php.
References $resql, db, dol_get_first_day(), dol_get_last_day(), and dol_syslog().
update ($user = null, $notrigger = 0)
Update object into database.
Parameters
User $user User that modify
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 302 of file accountancycategory.class.php.
References $resql, db, dol_syslog(), and label.
updateAccAcc ($id_cat, $cpts = array())
Function to add an accounting account in an accounting category.
Parameters
int $id_cat Id category
array $cpts list of accounts array
Returns
int <0 if KO, >0 if OK
Definition at line 565 of file accountancycategory.class.php.
References $resql, db, dol_syslog(), and length_accountg().
The documentation for this class was generated from the following file:
htdocs/accountancy/class/accountancycategory.class.php