Dolibarr: mod_barcode_product_standard Class Reference
mod_barcode_product_standard Class Reference
Class to manage barcode with standard rule.
Public Member Functions
__construct ()
Constructor.
info ($langs)
Return description of module.
getExample ($langs, $objproduct=0)
Return an example of result returned by getNextValue.
getNextValue ($objproduct=null, $type= '')
Return next value.
verif ($db, &$code, $product, $thirdparty_type, $type)
Check validity of code according to its rules.
verif_dispo ($db, $code, $product)
Return if a code is used (by other element)
verif_syntax ($codefortest, $typefortest)
Return if a barcode value match syntax.
Public Member Functions inherited from ModeleNumRefBarCode
info ($langs)
Return default description of numbering model.
getNom ($langs)
Return model name.
getExample ($langs)
Return a numbering example.
getNextValue ($objproduct, $type= '')
Return next value available.
getVersion ()
Return version of module.
getToolTip ($langs, $soc, $type)
Return description of module parameters.
Detailed Description
Class to manage barcode with standard rule.
Definition at line 34 of file mod_barcode_product_standard.php.
Member Function Documentation
getExample ($langs, $objproduct = 0)
Return an example of result returned by getNextValue.
Parameters
Translate $langs Object langs
Product $objproduct Object product
Returns
string Return string example
Definition at line 125 of file mod_barcode_product_standard.php.
References getNextValue().
getNextValue ($objproduct = null, $type = '')
Return next value.
Parameters
Product $objproduct Object product
string $type Type of barcode (EAN, ISBN, ...)
Returns
string Value if OK, '' if module not configured, <0 if KO
Definition at line 148 of file mod_barcode_product_standard.php.
References dol_now(), and get_next_value().
Referenced by getExample().
info ($langs)
Return description of module.
Parameters
Translate $langs Object langs
Returns
string Description of module
Definition at line 80 of file mod_barcode_product_standard.php.
verif ($db, & $code, $product, $thirdparty_type, $type)
Check validity of code according to its rules.
Parameters
DoliDB $db Database handler
string $code Code to check/correct
Product $product Object product
int $thirdparty_type 0 = customer/prospect , 1 = supplier
string $type type of barcode (EAN, ISBN, ...)
Returns
int 0 if OK -1 ErrorBadCustomerCodeSyntax -2 ErrorCustomerCodeRequired -3 ErrorCustomerCodeAlreadyUsed -4 ErrorPrefixRequired
Definition at line 190 of file mod_barcode_product_standard.php.
References dol_strlen(), dol_syslog(), verif_dispo(), and verif_syntax().
verif_dispo ($db, $code, $product)
Return if a code is used (by other element)
Parameters
DoliDB $db Handler acces base
string $code Code to check
Product $product Objet product
Returns
int 0 if available, <0 if KO
Definition at line 250 of file mod_barcode_product_standard.php.
References $resql.
Referenced by verif().
verif_syntax ($codefortest, $typefortest)
Return if a barcode value match syntax.
Parameters
string $codefortest Code to check syntax
string $typefortest Type of barcode (ISBN, EAN, ...)
Returns
int 0 if OK, <0 if KO
Definition at line 283 of file mod_barcode_product_standard.php.
References check_value(), and dol_syslog().
Referenced by verif().
The documentation for this class was generated from the following file:
htdocs/core/modules/barcode/mod_barcode_product_standard.php