Dolibarr: ExpenseReport Class Reference
ExpenseReport Class Reference
Class to manage Trips and Expenses.
Public Member Functions
__construct ($db)
Constructor.
create ($user, $notrigger=0)
Create object in database.
createFromClone (User $user, $fk_user_author)
Load an object from its id and create a new one in database.
update ($user, $notrigger=0, $userofexpensereport=null)
update
ref}
Load an object from database
Parameters
int $id Id { 1}
string $ref Ref {
Returns
int <0 if KO, >0 if OK
fetch ($id, $ref= '')
set_paid ($id, $fuser, $notrigger=0)
Classify the expense report as paid.
getLibStatut ($mode=0)
Returns the label status.
LibStatut ($status, $mode=0)
Returns the label of a statut.
info ($id)
Load information on object.
initAsSpecimen ()
Initialise an instance with random values.
fetch_line_by_project ($projectid, $user= '')
fetch_line_by_project
recalculer ($id)
recalculer TODO Replace this with call to update_price if not already done
fetch_lines ()
fetch_lines
delete (User $fuser=null)
delete
setValidate ($fuser, $notrigger=0)
Set to status validate.
set_save_from_refuse ($fuser)
set_save_from_refuse
setApproved ($fuser, $notrigger=0)
Set status to approved.
setDeny ($fuser, $details, $notrigger=0)
setDeny
set_unpaid ($fuser, $notrigger=0)
set_unpaid
set_cancel ($fuser, $detail, $notrigger=0)
set_cancel
getNextNumRef ()
Return next reference of expense report not already used.
getNomUrl ($withpicto=0, $max=0, $short=0, $moretitle= '', $notooltip=0, $save_lastsearch_value=-1)
Return clicable name (with picto eventually)
update_totaux_add ($ligne_total_ht, $ligne_total_tva)
Update total of an expense report when you add a line.
update_totaux_del ($ligne_total_ht, $ligne_total_tva)
Update total of an expense report when you delete a line.
addline ($qty=0, $up=0, $fk_c_type_fees=0, $vatrate=0, $date= '', $comments= '', $fk_project=0, $fk_c_exp_tax_cat=0, $type=0, $fk_ecm_files=0)
addline
checkRules ($type=0, $seller= '')
Check constraint of rules and update price if needed.
applyOffset ()
Method to apply the offset if needed.
offsetAlreadyGiven ()
If the sql find any rows then the ikoffset is already given (ikoffset is applied at the first expense report line)
updateline ($rowid, $type_fees_id, $projet_id, $vatrate, $comments, $qty, $value_unit, $date, $expensereport_id, $fk_c_exp_tax_cat=0, $fk_ecm_files=0)
Update an expense report line.
deleteline ($rowid, $fuser= '')
deleteline
periode_existe ($fuser, $date_debut, $date_fin)
periode_existe
fetch_users_approver_expensereport ()
Return list of people with permission to validate expense reports.
generateDocument ($modele, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0, $moreparams=null)
Create a document onto disk accordign to template module.
listOfTypes ($active=1)
List of types.
load_state_board ()
Charge indicateurs this->nb pour le tableau de bord.
load_board ($user, $option= 'topay')
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
hasDelay ($option)
Return if an expense report is late or not.
getVentilExportCompta ()
Return if an expensereport was dispatched into bookkeeping.
getSumPayments ()
Return amount of payments already done.
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0)
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source= 'external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source= 'internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source= '', $code= '')
Delete all links between an object $this and all its contacts.
liste_contact ($statut=-1, $source= 'external', $list=0, $code= '')
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source= 'internal', $order= 'position', $option=0, $activeonly=0, $code= '')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contactid into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table= '', $id=null, $format= '', $id_field= '', $fuser=null, $trigkey= '', $fk_user_field= 'fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source= 'external')
Return list of id of contacts of object.
setProject ($projectid)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id)
Change the payments terms.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder= 'ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix= '')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust= 'none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null)
Add objects linked in llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $clause= 'OR', $alsosametype=1, $orderby= 'sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
updateObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '')
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $rowid= '')
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType= '', $trigkey= '')
Set status of an object.
getCanvas ($id=0, $ref= '')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
display_incoterms ()
Return incoterms informations TODO Use a cache for label get.
getIncotermsForPDF ()
Return incoterms informations for pdf display.
setIncoterms ($id_incoterm, $location)
Define incoterms values of current object.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir= '/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir= '/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafieldsline=0, $defaulttpldir= '/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist= '', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist= '', $defaulttpldir= '/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
addThumbs ($file)
Build thumb Move this into files.lib.php.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($trigger_name, $user)
Call trigger based on this instance.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger= '', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update an extra field value for the current object.
showInputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
showOutputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss= '')
Return HTML string to show a field into a page Code very similar with showOutputField of extra fields.
showOptionals ($extrafields, $mode= 'view', $params=null, $keysuffix= '', $keyprefix= '', $onetrtd=0)
Function to show lines of extrafields with output datas.
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere= '')
Load object in memory from the database.
fetchLinesCommon ($morewhere= '')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
Data Fields
const STATUS_DRAFT = 0
Draft status.
const STATUS_VALIDATED = 2
Validated (need to be paid)
const STATUS_CANCELED = 4
Classified canceled.
const STATUS_APPROVED = 5
Classified approved.
const STATUS_REFUSED = 99
Classified refused.
const STATUS_CLOSED = 6
Classified paid.
Data Fields inherited from CommonObject
$projet
$note
Additional Inherited Members
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref= '', $ref_ext= '')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static commonReplaceThirdparty (DoliDB $db, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
isNull ($info)
Function test if type is null.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare the values to insert.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ()
Function to concat keys of fields.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage Trips and Expenses.
Definition at line 35 of file expensereport.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Handler acces base de donnees
Definition at line 145 of file expensereport.class.php.
References db.
Member Function Documentation
addline ($qty = 0, $up = 0, $fk_c_type_fees = 0, $vatrate = 0, $date = '', $comments = '', $fk_project = 0, $fk_c_exp_tax_cat = 0, $type = 0, $fk_ecm_files = 0)
addline
Parameters
float $qty Qty
double $up Value init
int $fk_c_type_fees Type payment
string $vatrate Vat rate (Can be '10' or '10 (ABC)')
string $date Date
string $comments Description
int $fk_project Project id
int $fk_c_exp_tax_cat Car category id
int $type Type line
int $fk_ecm_files Id of ECM file to link to this expensereport line
Returns
int <0 if KO, >0 if OK
Definition at line 1708 of file expensereport.class.php.
References applyOffset(), calcul_price_total(), checkRules(), db, dol_syslog(), getLocalTaxesFromRate(), price2num(), and CommonObject\update_price().
applyOffset ()
Method to apply the offset if needed.
Returns
boolean true=applied, false=not applied
Definition at line 1875 of file expensereport.class.php.
References calcul_price_total(), db, ExpenseReportIk\getRangeByUser(), and offsetAlreadyGiven().
Referenced by addline(), and updateline().
checkRules ($type = 0, $seller = '')
Check constraint of rules and update price if needed.
Parameters
int $type type of line
string $seller seller, but actually he is unknown
Returns
true or false
Definition at line 1806 of file expensereport.class.php.
References calcul_price_total(), ExpenseReportRule\getAllRule(), and price().
Referenced by addline(), and updateline().
create ($user, $notrigger = 0)
Create object in database.
Parameters
User $user User that create
int $notrigger Disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 166 of file expensereport.class.php.
References $resql, CommonObject\call_trigger(), db, dol_now(), dol_syslog(), CommonObject\insertExtraFields(), and CommonObject\update_price().
Referenced by createFromClone().
createFromClone (User $user, $fk_user_author)
Load an object from its id and create a new one in database.
Parameters
User $user User making the clone
int $fk_user_author Id of new user
Returns
int New id of clone
Definition at line 321 of file expensereport.class.php.
References create(), and db.
delete (User $fuser = null)
delete
Parameters
User $fuser User that delete
Returns
int <0 if KO, >0 if OK
Definition at line 1053 of file expensereport.class.php.
References $resql, db, and dol_syslog().
deleteline ($rowid, $fuser = '')
deleteline
Parameters
int $rowid Row id
User $fuser User
Returns
int <0 if KO, >0 if OK
Definition at line 2078 of file expensereport.class.php.
References db, and dol_syslog().
fetch_line_by_project ($projectid, $user = '')
fetch_line_by_project
Parameters
int $projectid Project id
User $user User
Returns
int <0 if KO, >0 if OK
Definition at line 814 of file expensereport.class.php.
References dol_syslog(), img_picto(), price(), and print.
fetch_lines ()
fetch_lines
Returns
int <0 if OK, >0 if KO
Definition at line 969 of file expensereport.class.php.
References $resql, db, and dol_syslog().
Referenced by update().
fetch_users_approver_expensereport ()
Return list of people with permission to validate expense reports.
Search for permission "approve expense report"
Returns
array Array of user ids
Definition at line 2164 of file expensereport.class.php.
References db, and dol_syslog().
generateDocument ($modele, $outputlangs, $hidedetails = 0, $hidedesc = 0, $hideref = 0, $moreparams = null)
Create a document onto disk accordign to template module.
Parameters
string $modele Force le mnodele a utiliser ('' to not force)
Translate $outputlangs objet lang a utiliser pour traduction
int $hidedetails Hide details of lines
int $hidedesc Hide description
int $hideref Hide ref
null | array $moreparams Array to provide more information
Returns
int 0 if KO, 1 if OK
Definition at line 2210 of file expensereport.class.php.
References CommonObject\commonGenerateDocument(), and dol_strlen().
Referenced by ModeleExpenseReport\liste_modeles().
getLibStatut ($mode = 0)
Returns the label status.
Parameters
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto
Returns
string Label
Definition at line 627 of file expensereport.class.php.
References LibStatut().
getNextNumRef ()
Return next reference of expense report not already used.
Returns
string free ref
Definition at line 1517 of file expensereport.class.php.
References dol_buildpath(), and dol_print_error().
Referenced by setValidate().
getNomUrl ($withpicto = 0, $max = 0, $short = 0, $moretitle = '', $notooltip = 0, $save_lastsearch_value = -1)
Return clicable name (with picto eventually)
Parameters
int $withpicto 0=No picto, 1=Include picto into link, 2=Only picto
int $max Max length of shown ref
int $short 1=Return just URL
string $moretitle Add more text to title tooltip
int $notooltip 1=Disable tooltip
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
Returns
string String with URL
Definition at line 1577 of file expensereport.class.php.
References dol_trunc(), img_object(), and price().
getSumPayments ()
Return amount of payments already done.
Returns
int Amount of payment already done, <0 if KO
Definition at line 2438 of file expensereport.class.php.
References $resql, db, and dol_syslog().
getVentilExportCompta ()
Return if an expensereport was dispatched into bookkeeping.
Returns
int <0 if KO, 0=no, 1=yes
Definition at line 2404 of file expensereport.class.php.
References $resql, and db.
hasDelay ($option)
Return if an expense report is late or not.
Parameters
string $option 'topay' or 'toapprove'
Returns
boolean True if late, False if not late
Definition at line 2382 of file expensereport.class.php.
References dol_now().
info ($id)
Load information on object.
Parameters
int $id Id of object
Returns
void
Definition at line 674 of file expensereport.class.php.
References $resql, db, and dol_print_error().
initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
void
Definition at line 751 of file expensereport.class.php.
References db, and dol_now().
LibStatut ($status, $mode = 0)
Returns the label of a statut.
Parameters
int $status id statut
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto, 6=Long label + Picto
Returns
string Label
Definition at line 640 of file expensereport.class.php.
References img_picto().
Referenced by getLibStatut().
listOfTypes ($active = 1)
List of types.
Parameters
int $active Active or not
Returns
array
Definition at line 2238 of file expensereport.class.php.
References db, dol_print_error(), and dol_syslog().
load_board ($user, $option = 'topay')
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
Parameters
User $user Objet user
string $option 'topay' or 'toapprove'
Returns
WorkboardResponse|int <0 if KO, WorkboardResponse if OK
Definition at line 2307 of file expensereport.class.php.
References $resql, db, dol_now(), dol_print_error(), and img_object().
load_state_board ()
Charge indicateurs this->nb pour le tableau de bord.
Returns
int <0 if KO, >0 if OK
Definition at line 2271 of file expensereport.class.php.
References $resql, db, and dol_print_error().
offsetAlreadyGiven ()
If the sql find any rows then the ikoffset is already given (ikoffset is applied at the first expense report line)
Returns
bool
Definition at line 1923 of file expensereport.class.php.
References $resql, db, dol_print_date(), dol_print_error(), and dol_syslog().
Referenced by applyOffset().
periode_existe ($fuser, $date_debut, $date_fin)
periode_existe
Parameters
User $fuser User
integer $date_debut Start date
integer $date_fin End date
Returns
int <0 if KO, >0 if OK
Definition at line 2109 of file expensereport.class.php.
References db, and dol_syslog().
recalculer ($id)
recalculer TODO Replace this with call to update_price if not already done
Parameters
int $id Id of expense report
Returns
int <0 if KO, >0 if OK
Definition at line 919 of file expensereport.class.php.
References db, and dol_syslog().
set_cancel ($fuser, $detail, $notrigger = 0)
set_cancel
Parameters
User $fuser User
string $detail Detail
int $notrigger Disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 1457 of file expensereport.class.php.
References CommonObject\call_trigger(), db, dol_syslog(), and STATUS_CANCELED.
set_paid ($id, $fuser, $notrigger = 0)
Classify the expense report as paid.
Parameters
int $id Id of expense report
user $fuser User making change
int $notrigger Disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 568 of file expensereport.class.php.
References $resql, CommonObject\call_trigger(), db, dol_print_error(), and dol_syslog().
set_save_from_refuse ($fuser)
set_save_from_refuse
Parameters
User $fuser User
Returns
int <0 if KO, >0 if OK
Definition at line 1221 of file expensereport.class.php.
References db, and dol_syslog().
set_unpaid ($fuser, $notrigger = 0)
set_unpaid
Parameters
User $fuser User
int $notrigger Disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 1395 of file expensereport.class.php.
References CommonObject\call_trigger(), db, and dol_syslog().
setApproved ($fuser, $notrigger = 0)
Set status to approved.
Parameters
User $fuser User
int $notrigger Disable triggers
Returns
int <0 if KO, 0 if nothing done, >0 if OK
Definition at line 1268 of file expensereport.class.php.
References CommonObject\call_trigger(), db, dol_now(), and dol_syslog().
setDeny ($fuser, $details, $notrigger = 0)
setDeny
Parameters
User $fuser User
string $details Details
int $notrigger Disable triggers
Returns
int
Definition at line 1330 of file expensereport.class.php.
References CommonObject\call_trigger(), db, dol_now(), and dol_syslog().
setValidate ($fuser, $notrigger = 0)
Set to status validate.
Parameters
User $fuser User
int $notrigger Disable triggers
Returns
int <0 if KO, 0 if nothing done, >0 if OK
Definition at line 1093 of file expensereport.class.php.
References $resql, CommonObject\call_trigger(), db, dol_dir_list(), dol_now(), dol_sanitizeFileName(), dol_syslog(), and getNextNumRef().
update ($user, $notrigger = 0, $userofexpensereport = null)
update
Parameters
User $user User making change
int $notrigger Disable triggers
User $userofexpensereport New user we want to have the expense report on.
Returns
int <0 if KO, >0 if OK
Definition at line 391 of file expensereport.class.php.
References $resql, CommonObject\call_trigger(), db, dol_syslog(), dolGetFirstLastname(), and fetch_lines().
update_totaux_add ($ligne_total_ht, $ligne_total_tva)
Update total of an expense report when you add a line.
Parameters
string $ligne_total_ht Amount without taxes
string $ligne_total_tva Amount of all taxes
Returns
void
Definition at line 1641 of file expensereport.class.php.
References db.
update_totaux_del ($ligne_total_ht, $ligne_total_tva)
Update total of an expense report when you delete a line.
Parameters
string $ligne_total_ht Amount without taxes
string $ligne_total_tva Amount of all taxes
Returns
void
Definition at line 1671 of file expensereport.class.php.
References db.
updateline ($rowid, $type_fees_id, $projet_id, $vatrate, $comments, $qty, $value_unit, $date, $expensereport_id, $fk_c_exp_tax_cat = 0, $fk_ecm_files = 0)
Update an expense report line.
Parameters
int $rowid Line to edit
int $type_fees_id Type payment
int $projet_id Project id
double $vatrate Vat rate. Can be '8.5' or '8.5* (8.5NPROM...)'
string $comments Description
float $qty Qty
double $value_unit Value init
int $date Date
int $expensereport_id Expense report id
int $fk_c_exp_tax_cat Id of category of car
int $fk_ecm_files Id of ECM file to link to this expensereport line
Returns
int <0 if KO, >0 if OK
Definition at line 1963 of file expensereport.class.php.
References $resql, applyOffset(), calcul_price_total(), checkRules(), db, getLocalTaxesFromRate(), and price2num().
The documentation for this class was generated from the following file:
htdocs/expensereport/class/expensereport.class.php