Dolibarr: RejetPrelevement Class Reference
RejetPrelevement Class Reference
Class to manage standing orders rejects.
Public Member Functions
__construct ($db, $user)
Constructor.
create ($user, $id, $motif, $date_rejet, $bonid, $facturation=0)
Create.
fetch ($rowid)
Retrieve withdrawal object.
Private Member Functions
_send_email ($fac)
Send email to all users that has asked the withdraw request.
getListInvoices ($amounts=0)
Retrieve the list of invoices.
Detailed Description
Class to manage standing orders rejects.
Definition at line 31 of file rejetprelevement.class.php.
Constructor & Destructor Documentation
__construct ($db, $user)
Constructor.
Parameters
DoliDb $db Database handler
User $user Objet user
Definition at line 50 of file rejetprelevement.class.php.
References db, and user.
Member Function Documentation
_send_email ($fac) private
Send email to all users that has asked the withdraw request.
Parameters
Facture $fac Invoice object
Returns
void
Definition at line 208 of file rejetprelevement.class.php.
References $resql, db, dol_syslog(), price(), and user.
Referenced by create().
create ($user, $id, $motif, $date_rejet, $bonid, $facturation = 0)
Create.
Parameters
User $user User object
int $id Id
string $motif Motif
int $date_rejet Date rejet
int $bonid Bon id
int $facturation Facturation
Returns
void
Definition at line 85 of file rejetprelevement.class.php.
References _send_email(), db, dol_now(), dol_syslog(), getListInvoices(), and price2num().
fetch ($rowid)
Retrieve withdrawal object.
Parameters
int $rowid id of invoice to retrieve
Returns
int
Definition at line 337 of file rejetprelevement.class.php.
References $resql, db, and dol_syslog().
getListInvoices ($amounts = 0) private
Retrieve the list of invoices.
Parameters
int $amounts If you want to get the amount of the order for each invoice
Returns
array Array List of invoices related to the withdrawal line A withdrawal line is today linked to one and only one invoice. So the function should return only one object ?
Definition at line 285 of file rejetprelevement.class.php.
References $resql, db, and dol_syslog().
Referenced by create().
The documentation for this class was generated from the following file:
htdocs/compta/prelevement/class/rejetprelevement.class.php