Dolibarr: MailmanSpip Class Reference
MailmanSpip Class Reference
Class to manage mailman and spip.
Public Member Functions
__construct ($db)
Constructor.
isSpipEnabled ()
Function used to check if SPIP is enabled on the system.
checkSpipConfig ()
Function used to check if the SPIP config is correct.
connectSpip ()
Function used to connect to SPIP.
add_to_spip ($object)
Fonction qui donne les droits redacteurs dans spip.
del_to_spip ($object)
Fonction qui enleve les droits redacteurs dans spip.
is_in_spip ($object)
Fonction qui dit si cet utilisateur est un redacteur existant dans spip.
add_to_mailman ($object, $listes= '')
Subscribe an email to all mailing-lists.
del_to_mailman ($object, $listes= '')
Unsubscribe an email from all mailing-lists Used when a user is resiliated.
Private Member Functions
callMailman ($object, $url, $list)
Function used to connect to Mailman.
Detailed Description
Class to manage mailman and spip.
Definition at line 40 of file mailmanspip.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 68 of file mailmanspip.class.php.
References db.
Member Function Documentation
add_to_mailman ($object, $listes = '')
Subscribe an email to all mailing-lists.
Parameters
Adherent $object Object with data (->email, ->pass, ->element, ->type)
array $listes To force mailing-list (string separated with ,)
Returns
int <0 if KO, >=0 if OK
Definition at line 324 of file mailmanspip.class.php.
References callMailman(), db, and dol_syslog().
add_to_spip ($object)
Fonction qui donne les droits redacteurs dans spip.
Parameters
Adherent $object Object with data (->firstname, ->lastname, ->email and ->login)
Returns
int =0 if KO, >0 if OK
Definition at line 186 of file mailmanspip.class.php.
References checkSpipConfig(), connectSpip(), dol_hash(), dol_syslog(), isSpipEnabled(), and makesalt().
callMailman ($object, $url, $list) private
Function used to connect to Mailman.
Parameters
Adherent $object Object with the data
string $url Mailman URL to be called with patterns
string $list Name of mailing-list
Returns
mixed Boolean or string
Definition at line 133 of file mailmanspip.class.php.
References dol_syslog().
Referenced by add_to_mailman(), and del_to_mailman().
checkSpipConfig ()
Function used to check if the SPIP config is correct.
Returns
boolean
Definition at line 93 of file mailmanspip.class.php.
Referenced by add_to_spip(), del_to_spip(), and is_in_spip().
connectSpip ()
Function used to connect to SPIP.
Returns
boolean|DoliDB Boolean of DoliDB
Definition at line 111 of file mailmanspip.class.php.
References dol_syslog(), and getDoliDBInstance().
Referenced by add_to_spip(), del_to_spip(), and is_in_spip().
del_to_mailman ($object, $listes = '')
Unsubscribe an email from all mailing-lists Used when a user is resiliated.
Parameters
Adherent $object Object with data (->email, ->pass, ->element, ->type)
array $listes To force mailing-list (string separated with ,)
Returns
int <0 if KO, >=0 if OK
Definition at line 398 of file mailmanspip.class.php.
References callMailman(), db, and dol_syslog().
del_to_spip ($object)
Fonction qui enleve les droits redacteurs dans spip.
Parameters
Adherent $object Object with data (->login)
Returns
int =0 if KO, >0 if OK
Definition at line 230 of file mailmanspip.class.php.
References checkSpipConfig(), connectSpip(), dol_syslog(), and isSpipEnabled().
is_in_spip ($object)
Fonction qui dit si cet utilisateur est un redacteur existant dans spip.
Parameters
object $object Object with data (->login)
Returns
int 1=exists, 0=does not exists, -1=error
Definition at line 271 of file mailmanspip.class.php.
References checkSpipConfig(), connectSpip(), and isSpipEnabled().
isSpipEnabled ()
Function used to check if SPIP is enabled on the system.
Returns
boolean
Definition at line 78 of file mailmanspip.class.php.
Referenced by add_to_spip(), del_to_spip(), and is_in_spip().
The documentation for this class was generated from the following file:
htdocs/mailmanspip/class/mailmanspip.class.php