Dolibarr: pdf_standardlabel Class Reference
pdf_standardlabel Class Reference
Class to generate stick sheet with format Avery or other personalised.
Public Member Functions
addSticker (&$pdf, $outputlangs, $param)
Output a sticker on page at position _COUNTX, _COUNTY (_COUNTX and _COUNTY start from 0)
Add_PDF_label (&$pdf, $textleft, $header, $footer, $outputlangs, $textright= '', $photo= '')
Output a sticker on page at position _COUNTX, _COUNTY (_COUNTX and _COUNTY start from 0)
write_file ($arrayofrecords, $outputlangs, $srctemplatepath, $outputdir= '', $filename= 'tmp_address_sheet.pdf')
Function to build PDF on disk, then output on HTTP strem.
Public Member Functions inherited from CommonStickerGenerator
__construct ($db)
Constructor.
write_file ($arrayofrecords, $outputlangs, $srctemplatepath, $outputdir= '')
Function to build PDF on disk, then output on HTTP strem.
addSticker (&$pdf, $outputlangs, $param)
Output a sticker on page at position _COUNTX, _COUNTY (_COUNTX and _COUNTY start from 0)
Set_Char_Size (&$pdf, $pt)
Methode qui permet de modifier la taille des caracteres Cela modiera aussi l'espace entre chaque ligne.
Additional Inherited Members
Protected Member Functions inherited from CommonStickerGenerator
_Pointille (&$pdf, $x1=0, $y1=0, $x2=210, $y2=297, $epaisseur=1, $nbPointilles=15)
protected Print dot line
_Croix (&$pdf, $x1=0, $y1=0, $x2=210, $y2=297, $epaisseur=1, $taille=4)
protected Function realisant une croix aux 4 coins des cartes
_Get_Height_Chars ($pt)
protected Give the height for a char size given.
_Set_Format (&$pdf, $format)
protected Set format
Detailed Description
Class to generate stick sheet with format Avery or other personalised.
Definition at line 34 of file pdf_standardlabel.class.php.
Member Function Documentation
Add_PDF_label (& $pdf, $textleft, $header, $footer, $outputlangs, $textright = '', $photo = '')
Output a sticker on page at position _COUNTX, _COUNTY (_COUNTX and _COUNTY start from 0)
LOGO% is replace with company logo
PHOTO% is replace with photo provided as parameter
Parameters
PDF $pdf PDF reference
string $textleft Text left
string $header Header
string $footer Footer
Translate $outputlangs Output langs
string $textright Text right
string $photo Photo (full path to image file used as replacement for key PHOTOS% into left, right, header or footer text)
Returns
void
Definition at line 64 of file pdf_standardlabel.class.php.
References CommonStickerGenerator\_Croix(), and dol_getImageSize().
Referenced by write_file().
addSticker (& $pdf, $outputlangs, $param)
Output a sticker on page at position _COUNTX, _COUNTY (_COUNTX and _COUNTY start from 0)
Parameters
PDF $pdf PDF reference
Translate $outputlangs Output langs
array $param Associative array containing label content and optional parameters
Returns
void
Definition at line 44 of file pdf_standardlabel.class.php.
write_file ($arrayofrecords, $outputlangs, $srctemplatepath, $outputdir = '', $filename = 'tmp_address_sheet.pdf')
Function to build PDF on disk, then output on HTTP strem.
Parameters
array $arrayofrecords Array of record informations (array('textleft'=>,'textheader'=>, ..., 'id'=>,'photo'=>)
Translate $outputlangs Lang object for output language
string $srctemplatepath Full path of source filename for generator using a template file
string $outputdir Output directory for pdf file
string $filename Short file name of PDF output file
Returns
int 1=OK, 0=KO
Definition at line 241 of file pdf_standardlabel.class.php.
References CommonStickerGenerator\_Set_Format(), Add_PDF_label(), dol_mimetype(), dol_mkdir(), dol_print_error(), pdf_getInstance(), pdf_getPDFFont(), and type.
The documentation for this class was generated from the following file:
htdocs/core/modules/printsheet/doc/pdf_standardlabel.class.php