Dolibarr: htdocs/bookmarks/bookmarks.lib.php File Reference
bookmarks.lib.php File Reference
File with library for bookmark module.
Functions
printBookmarksList ($aDb, $aLangs)
Add area with bookmarks in menu.
Detailed Description
File with library for bookmark module.
Definition in file bookmarks.lib.php.
Function Documentation
printBookmarksList ($aDb, $aLangs)
Add area with bookmarks in menu.
Parameters
DoliDb $aDb Database handler
Translate $aLangs Object lang
Returns
string
Definition at line 31 of file bookmarks.lib.php.
References $resql, ajax_combobox(), dol_escape_htmltag(), and dol_print_error().
Referenced by left_menu().