Dolibarr: DiscountAbsolute Class Reference
DiscountAbsolute Class Reference
Class to manage absolute discounts.
Public Member Functions
__construct ($db)
Constructor.
fetch ($rowid, $fk_facture_source=0, $fk_invoice_supplier_source=0)
Load object from database into memory.
create ($user)
Create a discount into database.
delete ($user)
Delete object in database.
link_to_invoice ($rowidline, $rowidinvoice)
Link the discount to a particular invoice line or a particular invoice.
unlink_invoice ()
Link the discount to a particular invoice line or a particular invoice.
getAvailableDiscounts ($company= '', $user= '', $filter= '', $maxvalue=0, $discount_type=0)
Return amount (with tax) of discounts currently available for a company, user or other criteria.
getSumDepositsUsed ($invoice, $multicurrency=0)
Return amount (with tax) of all deposits invoices used by invoice as a payment.
getSumCreditNotesUsed ($invoice, $multicurrency=0)
Return amount (with tax) of all credit notes invoices + excess received used by invoice as a payment.
getSumFromThisCreditNotesNotUsed ($invoice, $multicurrency=0)
Return amount (with tax) of all converted amount for this credit note.
getNomUrl ($withpicto, $option= 'invoice')
Return clickable ref of object (with picto or not)
initAsSpecimen ()
Initialise an instance with random values.
Detailed Description
Class to manage absolute discounts.
Definition at line 29 of file discount.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 107 of file discount.class.php.
References db.
Member Function Documentation
create ($user)
Create a discount into database.
Parameters
User $user User that create
Returns
int <0 if KO, >0 if OK
Definition at line 203 of file discount.class.php.
References $resql, db, description, dol_now(), dol_syslog(), and price2num().
delete ($user)
Delete object in database.
If fk_facture_source is defined, we delete all familiy with same fk_facture_source. If not, only with id is removed
Parameters
User $user Object of user asking to delete
Returns
int <0 if KO, >0 if OK
Definition at line 274 of file discount.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
fetch ($rowid, $fk_facture_source = 0, $fk_invoice_supplier_source = 0)
Load object from database into memory.
Parameters
int $rowid id discount to load
int $fk_facture_source fk_facture_source
int $fk_invoice_supplier_source fk_invoice_supplier_source
Returns
int <0 if KO, =0 if not found, >0 if OK
Definition at line 121 of file discount.class.php.
References $resql, db, description, and dol_syslog().
getAvailableDiscounts ($company = '', $user = '', $filter = '', $maxvalue = 0, $discount_type = 0)
Return amount (with tax) of discounts currently available for a company, user or other criteria.
Parameters
Societe $company Object third party for filter
User $user Filtre sur un user auteur des remises
string $filter Filtre autre
int $maxvalue Filter on max value for discount
int $discount_type 0 => customer discount, 1 => supplier discount
Returns
int <0 if KO, amount otherwise
Definition at line 505 of file discount.class.php.
References $resql, db, and dol_syslog().
getNomUrl ($withpicto, $option = 'invoice')
Return clickable ref of object (with picto or not)
Parameters
int $withpicto 0=No picto, 1=Include picto into link, 2=Picto only
string $option Where to link to ('invoice' or 'discount')
Returns
string String with URL
Definition at line 683 of file discount.class.php.
References dol_escape_htmltag().
getSumCreditNotesUsed ($invoice, $multicurrency = 0)
Return amount (with tax) of all credit notes invoices + excess received used by invoice as a payment.
Parameters
CommonInvoice $invoice Object invoice
int $multicurrency Return multicurrency_amount instead of amount
Returns
int <0 if KO, Sum of credit notes and excess received amount otherwise
Definition at line 594 of file discount.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
getSumDepositsUsed ($invoice, $multicurrency = 0)
Return amount (with tax) of all deposits invoices used by invoice as a payment.
Should always be empty, except if option FACTURE_DEPOSITS_ARE_JUST_PAYMENTS is on (not recommended).
Parameters
CommonInvoice $invoice Object invoice (customer of supplier)
int $multicurrency Return multicurrency_amount instead of amount
Returns
int <0 if KO, Sum of credit notes and deposits amount otherwise
Definition at line 548 of file discount.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
getSumFromThisCreditNotesNotUsed ($invoice, $multicurrency = 0)
Return amount (with tax) of all converted amount for this credit note.
Parameters
CommonInvoice $invoice Object invoice
int $multicurrency Return multicurrency_amount instead of amount
Returns
int <0 if KO, Sum of credit notes and deposits amount otherwise
Definition at line 639 of file discount.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
void
Definition at line 721 of file discount.class.php.
References description.
link_to_invoice ($rowidline, $rowidinvoice)
Link the discount to a particular invoice line or a particular invoice.
When discount is a global discount used as an invoice line, we link using rowidline. When discount is from a credit note used to reduce payment of an invoice, we link using rowidinvoice
Parameters
int $rowidline Invoice line id (To use discount into invoice lines)
int $rowidinvoice Invoice id (To use discount as a credit note to reduc payment of invoice)
Returns
int <0 if KO, >0 if OK
Definition at line 417 of file discount.class.php.
References $resql, db, and dol_syslog().
unlink_invoice ()
Link the discount to a particular invoice line or a particular invoice.
Do not call this if discount is linked to a reconcialiated invoice
Returns
int <0 if KO, >0 if OK
Definition at line 470 of file discount.class.php.
References $resql, db, and dol_syslog().
The documentation for this class was generated from the following file:
htdocs/core/class/discount.class.php