Dolibarr: htdocs/webservices/server_thirdparty.php File Reference
server_thirdparty.php File Reference
File that is entry point to call Dolibarr WebServices.
Functions
getThirdParty ($authentication, $id= '', $ref= '', $ref_ext= '')
Get a thirdparty.
createThirdParty ($authentication, $thirdparty)
Create a thirdparty.
updateThirdParty ($authentication, $thirdparty)
Update a thirdparty.
getListOfThirdParties ($authentication, $filterthirdparty)
getListOfThirdParties
deleteThirdParty ($authentication, $id= '', $ref= '', $ref_ext= '')
Delete a thirdparty.
Detailed Description
File that is entry point to call Dolibarr WebServices.
Definition in file server_thirdparty.php.
Function Documentation
createThirdParty ($authentication, $thirdparty)
Create a thirdparty.
Parameters
array $authentication Array of authentication information
Societe $thirdparty Thirdparty
Returns
array Array result
Definition at line 402 of file server_thirdparty.php.
References check_authentication(), dol_now(), dol_syslog(), and getCountry().
deleteThirdParty ($authentication, $id = '', $ref = '', $ref_ext = '')
Delete a thirdparty.
Parameters
array $authentication Array of authentication information
string $id internal id
string $ref internal reference
string $ref_ext external reference
Returns
array Array result
Definition at line 763 of file server_thirdparty.php.
References check_authentication(), and dol_syslog().
getListOfThirdParties ($authentication, $filterthirdparty)
getListOfThirdParties
Parameters
array $authentication Array of authentication information
array $filterthirdparty Filter fields (key=>value to filer on. For example 'client'=>2, 'supplier'=>1, 'category'=>idcateg, 'name'=>'searchstring', ...)
Returns
array Array result
Definition at line 658 of file server_thirdparty.php.
References $resql, check_authentication(), dol_now(), and dol_syslog().
getThirdParty ($authentication, $id = '', $ref = '', $ref_ext = '')
Get a thirdparty.
Parameters
array $authentication Array of authentication information
string $id internal id
string $ref internal reference
string $ref_ext external reference
Returns
array Array result
Definition at line 286 of file server_thirdparty.php.
References check_authentication(), dol_print_date(), and dol_syslog().
updateThirdParty ($authentication, $thirdparty)
Update a thirdparty.
Parameters
array $authentication Array of authentication information
Societe $thirdparty Thirdparty
Returns
array Array result
Definition at line 528 of file server_thirdparty.php.
References check_authentication(), dol_now(), dol_syslog(), and getCountry().