Dolibarr: htdocs/core/lib/website.lib.php File Reference
website.lib.php File Reference
Module website
Library for website module.
Functions
dolStripPhpCode ($str, $replacewith= '')
Remove PHP code part from a string.
dolKeepOnlyPhpCode ($str)
Keep only PHP code part from a HTML string page.
dolWebsiteReplacementOfLinks ($website, $content, $removephppart=0, $contenttype= 'html', $containerid= '')
Convert a page content to have correct links (based on DOL_URL_ROOT) into an html content.
dolWebsiteOutput ($content, $contenttype= 'html', $containerid= '')
Render a string of an HTML content and output it.
redirectToContainer ($containerref, $containeraliasalt= '', $containerid=0)
Format img tags to introduce viewimage on img src.
includeContainer ($containerref)
Clean an HTML page to report only content, so we can include it into another page.
getStructuredData ($type, $data=array())
Return HTML content to add structured data for an article, news or Blog Post.
getPagesFromSearchCriterias ($type, $algo, $searchstring, $max=25)
Return list of containers object that match a criteria.
getAllImages ($object, $objectpage, $urltograb, &$tmp, &$action, $modifylinks=0, $grabimages=1, $grabimagesinto= 'subpage')
Download all images found into page content $tmp.
Detailed Description
Library for website module.
Definition in file website.lib.php.
Function Documentation
dolKeepOnlyPhpCode ($str)
Keep only PHP code part from a HTML string page.
Parameters
string $str String to clean
Returns
string Result string with php code only
See also
dolStripPhpCode()
Definition at line 72 of file website.lib.php.
dolStripPhpCode ($str, $replacewith = '')
Remove PHP code part from a string.
Parameters
string $str String to clean
string $replacewith String to use as replacement
Returns
string Result string without php code
See also
dolKeepOnlyPhpCode()
Definition at line 33 of file website.lib.php.
Referenced by dolWebsiteReplacementOfLinks().
dolWebsiteOutput ($content, $contenttype = 'html', $containerid = '')
Render a string of an HTML content and output it.
Used to ouput the page when viewed from server (Dolibarr or Apache).
Parameters
string $content Content string
string $contenttype Content type
int $containerid Contenair id
Returns
void
See also
dolWebsiteReplacementOfLinks() for function used to replace content in the backoffice context.
Definition at line 216 of file website.lib.php.
References dol_syslog(), and print.
dolWebsiteReplacementOfLinks ($website, $content, $removephppart = 0, $contenttype = 'html', $containerid = '')
Convert a page content to have correct links (based on DOL_URL_ROOT) into an html content.
It replaces also dynamic content with '...php...' Used to ouput the page on the Preview from backoffice.
Parameters
Website $website Web site object
string $content Content to replace
int $removephppart 0=Replace PHP sections with a PHP badge. 1=Remove completely PHP sections.
string $contenttype Content type
int $containerid Contenair id
Returns
boolean True if OK
See also
dolWebsiteOutput() for function used to replace content in a web server context
Definition at line 116 of file website.lib.php.
References dol_syslog(), and dolStripPhpCode().
getAllImages ($object, $objectpage, $urltograb, & $tmp, & $action, $modifylinks = 0, $grabimages = 1, $grabimagesinto = 'subpage')
Download all images found into page content $tmp.
If $modifylinks is set, links to images will be replace with a link to viewimage wrapper.
Parameters
Website $object Object website
WebsitePage $objectpage Object website page
string $urltograb URL to grab (exemple: http://www.nltechno.com/ or http://www.nltechno.com/dir1/ or http://www.nltechno.com/dir1/mapage1)
string $tmp Content to parse
string $action Var $action
string $modifylinks 0=Do not modify content, 1=Replace links with a link to viewimage
int $grabimages 0=Do not grab images, 1=Grab images
string $grabimagesinto 'root' or 'subpage'
Returns
void
Definition at line 754 of file website.lib.php.
References dol_mkdir(), dol_syslog(), getRootURLFromURL(), getURLContent(), and setEventMessages().
getPagesFromSearchCriterias ($type, $algo, $searchstring, $max = 25)
Return list of containers object that match a criteria.
Parameters
string $type Type of container to search into (Example: 'page')
string $algo Algorithm used for search (Example: 'meta' is searching into meta information like title and description, 'metacontent')
string $searchstring Search string
int $max Max number of answers
Returns
string HTML content
Definition at line 647 of file website.lib.php.
References $resql, and dol_strlen().
getStructuredData ($type, $data = array())
Return HTML content to add structured data for an article, news or Blog Post.
Parameters
string $type 'blogpost', 'product', 'software'...
array $data Array of data parameters for structured data
Returns
string HTML content
Definition at line 528 of file website.lib.php.
References dol_print_date().
includeContainer ($containerref)
Clean an HTML page to report only content, so we can include it into another page.
It outputs content of file sanitized from html and body part.
Parameters
string $containerref Path to file to include (must be a page from website root. Example: 'mypage.php' means 'mywebsite/mypage.php')
Returns
void
Definition at line 482 of file website.lib.php.
References print.
redirectToContainer ($containerref, $containeraliasalt = '', $containerid = 0)
Format img tags to introduce viewimage on img src.
Parameters
string $content Content string
Returns
void
See also
dolWebsiteOutput() Make a redirect to another container.
Parameters
string $containerref Ref of container to redirect to (must be a page from website root. Example: 'mypage.php' means 'mywebsite/mypage.php').
string $containeraliasalt Ref of alternative aliases to redirect to.
int $containerid Id of container.
Returns
void
Definition at line 392 of file website.lib.php.
References print, and setEventMessages().