Dolibarr: AccountancySystem Class Reference
AccountancySystem Class Reference
Class to manage accountancy systems.
Public Member Functions
__construct ($db)
Constructor.
fetch ($rowid=0, $ref= '')
Load record in memory.
create ($user)
Insert accountancy system name into database.
Detailed Description
Class to manage accountancy systems.
Definition at line 29 of file accountancysystem.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db handler
Definition at line 67 of file accountancysystem.class.php.
References db.
Member Function Documentation
create ($user)
Insert accountancy system name into database.
Parameters
User $user making insert
Returns
int if KO, Id of line if OK
Definition at line 127 of file accountancysystem.class.php.
References $resql, db, dol_now(), dol_syslog(), and label.
fetch ($rowid = 0, $ref = '')
Load record in memory.
Parameters
int $rowid Id
string $ref ref
Returns
int <0 if KO, Id of record if OK and found
Definition at line 80 of file accountancysystem.class.php.
References db, dol_syslog(), and label.
The documentation for this class was generated from the following file:
htdocs/accountancy/class/accountancysystem.class.php