Dolibarr: FormWebsite Class Reference
FormWebsite Class Reference
Class to manage component html for module website.
Public Member Functions
__construct ($db)
Constructor.
selectWebsite ($selected= '', $htmlname= 'exportmodelid', $useempty=0)
Return HTML select list of export models.
selectTypeOfContainer ($htmlname, $selected= '', $useempty=0, $moreattrib= '')
Return a HTML select list of a dictionary.
selectSampleOfContainer ($htmlname, $selected= '', $useempty=0, $moreattrib= '')
Return a HTML select list of a dictionary.
Detailed Description
Class to manage component html for module website.
Definition at line 28 of file html.formwebsite.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 43 of file html.formwebsite.class.php.
References db.
Member Function Documentation
selectSampleOfContainer ($htmlname, $selected = '', $useempty = 0, $moreattrib = '')
Return a HTML select list of a dictionary.
Parameters
string $htmlname Name of select zone
string $selected Selected value
int $useempty 1=Add an empty value in list
string $moreattrib More attributes on HTML select tag
Returns
void
Definition at line 173 of file html.formwebsite.class.php.
References dol_dir_list().
selectTypeOfContainer ($htmlname, $selected = '', $useempty = 0, $moreattrib = '')
Return a HTML select list of a dictionary.
Parameters
string $htmlname Name of select zone
string $selected Selected value
int $useempty 1=Add an empty value in list, 2=Add an empty value in list only if there is more than 2 entries.
string $moreattrib More attributes on HTML select tag
Returns
void
Definition at line 110 of file html.formwebsite.class.php.
References db, dol_print_error(), dol_syslog(), info_admin(), and print.
selectWebsite ($selected = '', $htmlname = 'exportmodelid', $useempty = 0)
Return HTML select list of export models.
Parameters
string $selected Id modele pre-selectionne
string $htmlname Name of HTML select
int $useempty Show empty value or not
Returns
string Html component
Definition at line 57 of file html.formwebsite.class.php.
References db, and dol_print_error().
The documentation for this class was generated from the following file:
htdocs/core/class/html.formwebsite.class.php