Dolibarr: pdf_strato Class Reference
pdf_strato Class Reference
Class to build contracts documents with model Strato.
Public Member Functions
__construct ($db)
Constructor.
write_file ($object, $outputlangs, $srctemplatepath= '', $hidedetails=0, $hidedesc=0, $hideref=0)
Function to build pdf onto disk.
Public Member Functions inherited from CommonDocGenerator
__construct ($db)
Constructor.
get_substitutionarray_user ($user, $outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_mysoc ($mysoc, $outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_thirdparty ($object, $outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_contact ($object, $outputlangs, $array_key= 'object')
Define array with couple subtitution key => subtitution value.
get_substitutionarray_other ($outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_object ($object, $outputlangs, $array_key= 'object')
Define array with couple substitution key => substitution value.
get_substitutionarray_lines ($line, $outputlangs)
Define array with couple substitution key => substitution value.
get_substitutionarray_shipment ($object, $outputlangs, $array_key= 'object')
Define array with couple substitution key => substitution value.
get_substitutionarray_shipment_lines ($line, $outputlangs)
Define array with couple substitution key => substitution value.
get_substitutionarray_each_var_object (&$object, $outputlangs, $recursive=true)
Define array with couple subtitution key => subtitution value.
fill_substitutionarray_with_extrafields ($object, $array_to_fill, $extrafields, $array_key, $outputlangs)
Fill array with couple extrafield key => extrafield value.
printRect ($pdf, $x, $y, $l, $h, $hidetop=0, $hidebottom=0)
Rect pdf.
columnSort ($a, $b)
uasort callback function to Sort colums fields
prepareArrayColumnField ($object, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0)
Prepare Array Column Field.
getColumnContentWidth ($colKey)
get column content width from column key
getColumnContentXStart ($colKey)
get column content X (abscissa) left position from column key
getColumnRank ($colKey)
get column position rank from column key
insertNewColumnDef ($newColKey, $defArray, $targetCol=false, $insertAfterTarget=false)
get column position rank from column key
printStdColumnContent ($pdf, &$curY, $colKey, $columnText= '')
print standard column content
getColumnStatus ($colKey)
get column status from column key
pdfTabTitles (&$pdf, $tab_top, $tab_height, $outputlangs, $hidetop=0)
Print standard column content.
Protected Member Functions
_tableau (&$pdf, $tab_top, $tab_height, $nexY, $outputlangs, $hidetop=0, $hidebottom=0)
Show table for lines.
tabSignature (&$pdf, $tab_top, $tab_height, $outputlangs)
Show footer signature of page.
_pagehead (&$pdf, $object, $showaddress, $outputlangs)
Show top header of page.
_pagefoot (&$pdf, $object, $outputlangs, $hidefreetext=0)
Show footer of page.
Additional Inherited Members
Static Public Member Functions inherited from ModelePDFContract
static liste_modeles ($db, $maxfilenamelength=0)
Return list of active generation modules.
Detailed Description
Class to build contracts documents with model Strato.
Definition at line 41 of file pdf_strato.modules.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 127 of file pdf_strato.modules.php.
References db, description, name, pdf_getFormat(), and type.
Member Function Documentation
_pagefoot (& $pdf, $object, $outputlangs, $hidefreetext = 0) protected
Show footer of page.
Need this->emetteur object
Parameters
PDF $pdf PDF
CommonObject $object Object to show
Translate $outputlangs Object lang for output
int $hidefreetext 1=Hide free text
Returns
integer
Definition at line 779 of file pdf_strato.modules.php.
References pdf_pagefoot().
Referenced by write_file().
_pagehead (& $pdf, $object, $showaddress, $outputlangs) protected
Show top header of page.
Parameters
PDF $pdf Object PDF
CommonObject $object Object to show
int $showaddress 0=no, 1=yes
Translate $outputlangs Object lang for output
Returns
void
Definition at line 599 of file pdf_strato.modules.php.
References dol_print_date(), pdf_build_address(), pdf_getHeightForLogo(), pdf_getPDFFontSize(), pdf_pagehead(), pdf_watermark(), and pdfBuildThirdpartyName().
Referenced by write_file().
_tableau (& $pdf, $tab_top, $tab_height, $nexY, $outputlangs, $hidetop = 0, $hidebottom = 0) protected
Show table for lines.
Parameters
PDF $pdf Object PDF
string $tab_top Top position of table
string $tab_height Height of table (rectangle)
int $nexY Y
Translate $outputlangs Langs object
int $hidetop Hide top bar of array
int $hidebottom Hide bottom bar of array
Returns
void
Definition at line 523 of file pdf_strato.modules.php.
References pdf_getPDFFontSize(), and CommonDocGenerator\printRect().
Referenced by write_file().
tabSignature (& $pdf, $tab_top, $tab_height, $outputlangs) protected
Show footer signature of page.
Parameters
PDF $pdf Object PDF
int $tab_top tab height position
int $tab_height tab height
Translate $outputlangs Object language for output
Returns
void
Definition at line 570 of file pdf_strato.modules.php.
Referenced by write_file().
write_file ($object, $outputlangs, $srctemplatepath = '', $hidedetails = 0, $hidedesc = 0, $hideref = 0)
Function to build pdf onto disk.
Parameters
CommonObject $object Id of object to generate
object $outputlangs Lang output object
string $srctemplatepath Full path of source filename for generator using a template file
int $hidedetails Do not show line details
int $hidedesc Do not show desc
int $hideref Do not show ref
Returns
int 1=OK, 0=KO
Definition at line 175 of file pdf_strato.modules.php.
References _pagefoot(), _pagehead(), _tableau(), convertSecondToTime(), db, dol_concatdesc(), dol_htmlentitiesbr(), dol_mkdir(), dol_print_date(), dol_sanitizeFileName(), pdf_getInstance(), pdf_getPDFFont(), pdf_getPDFFontSize(), price(), and tabSignature().
The documentation for this class was generated from the following file:
htdocs/core/modules/contract/doc/pdf_strato.modules.php