Dolibarr: htdocs/core/menus/standard/eldy.lib.php File Reference
eldy.lib.php File Reference
Library for file eldy menus.
Functions
print_eldy_menu ($db, $atarget, $type_user, &$tabMenu, &$menu, $noout=0, $mode= '')
Core function to output top menu eldy.
print_start_menu_array ()
Output start menu array.
print_start_menu_entry ($idsel, $classname, $showmode)
Output start menu entry.
print_text_menu_entry ($text, $showmode, $url, $id, $idsel, $classname, $atarget)
Output menu entry.
print_end_menu_entry ($showmode)
Output end menu entry.
print_end_menu_array ()
Output menu array.
print_left_eldy_menu ($db, $menu_array_before, $menu_array_after, &$tabMenu, &$menu, $noout=0, $forcemainmenu= '', $forceleftmenu= '', $moredata=null)
Core function to output left menu eldy Fill &$menu (example with $forcemainmenu='home' $forceleftmenu='all', return left menu tree of Home)
Detailed Description
Library for file eldy menus.
Definition in file eldy.lib.php.
Function Documentation
print_eldy_menu ($db, $atarget, $type_user, & $tabMenu, & $menu, $noout = 0, $mode = '')
Core function to output top menu eldy.
Parameters
DoliDB $db Database handler
string $atarget Target (Example: '' or '_top')
int $type_user 0=Menu for backoffice, 1=Menu for front office
array $tabMenu If array with menu entries already loaded, we put this array here (in most cases, it's empty)
Menu $menu Object Menu to return back list of menu entries
int $noout 1=Disable output (Initialise &$menu only).
string $mode 'top', 'topnb', 'left', 'jmobile'
Returns
int 0
Definition at line 44 of file eldy.lib.php.
References dol_buildpath(), dol_sort_array(), isVisibleToUserType(), make_substitutions(), print_end_menu_array(), print_end_menu_entry(), print_start_menu_array(), print_start_menu_entry(), and print_text_menu_entry().
Referenced by MenuManager\showmenu().
print_end_menu_array ()
Output menu array.
Returns
void
Definition at line 581 of file eldy.lib.php.
References print.
Referenced by print_eldy_menu().
print_end_menu_entry ($showmode)
Output end menu entry.
Parameters
int $showmode 0 = hide, 1 = allowed or 2 = not allowed
Returns
void
Definition at line 567 of file eldy.lib.php.
References print.
Referenced by print_eldy_menu().
print_left_eldy_menu ($db, $menu_array_before, $menu_array_after, & $tabMenu, & $menu, $noout = 0, $forcemainmenu = '', $forceleftmenu = '', $moredata = null)
Core function to output left menu eldy Fill &$menu (example with $forcemainmenu='home' $forceleftmenu='all', return left menu tree of Home)
Parameters
DoliDB $db Database handler
array $menu_array_before Table of menu entries to show before entries of menu handler (menu->liste filled with menu->add)
array $menu_array_after Table of menu entries to show after entries of menu handler (menu->liste filled with menu->add)
array $tabMenu If array with menu entries already loaded, we put this array here (in most cases, it's empty)
Menu $menu Object Menu to return back list of menu entries
int $noout Disable output (Initialise &$menu only).
string $forcemainmenu 'x'=Force mainmenu to mainmenu='x'
string $forceleftmenu 'all'=Force leftmenu to '' (= all). If value come being '', we change it to value in session and 'none' if not defined in session.
array $moredata An array with more data to output
Returns
int nb of menu entries
We update newmenu with entries found into database
Definition at line 605 of file eldy.lib.php.
References $resql, dol_buildpath(), dol_print_error(), dol_trunc(), GETPOST(), isVisibleToUserType(), make_substitutions(), print, and Account\TYPE_CASH.
Referenced by MenuManager\showmenu().
print_start_menu_array ()
Output start menu array.
Returns
void
Definition at line 500 of file eldy.lib.php.
References print.
Referenced by print_eldy_menu().
print_start_menu_entry ($idsel, $classname, $showmode)
Output start menu entry.
Parameters
string $idsel Text
string $classname String to add a css class
int $showmode 0 = hide, 1 = allowed or 2 = not allowed
Returns
void
Definition at line 516 of file eldy.lib.php.
References print.
Referenced by print_eldy_menu().
print_text_menu_entry ($text, $showmode, $url, $id, $idsel, $classname, $atarget)
Output menu entry.
Parameters
string $text Text
int $showmode 0 = hide, 1 = allowed or 2 = not allowed
string $url Url
string $id Id
string $idsel Id sel
string $classname Class name
string $atarget Target
Returns
void
Definition at line 538 of file eldy.lib.php.
References dol_escape_htmltag(), and print.
Referenced by print_eldy_menu().