Dolibarr: CMailFile Class Reference
CMailFile Class Reference
Class to send emails (with attachments or not) Usage: $mailfile = new CMailFile($subject,$sendto,$replyto,$message,$filepath,$mimetype,$filename,$cc,$ccc,$deliveryreceipt,$msgishtml,$errors_to,$css,$trackid,$moreinheader,$sendcontext); $mailfile->sendfile();.
Public Member Functions
__construct ($subject, $to, $from, $msg, $filename_list=array(), $mimetype_list=array(), $mimefilename_list=array(), $addr_cc="", $addr_bcc="", $deliveryreceipt=0, $msgishtml=0, $errors_to= '', $css= '', $trackid= '', $moreinheader= '', $sendcontext= 'standard', $replyto= '')
CMailFile.
sendfile ()
Send mail that was prepared by constructor.
dump_mail ()
Write content of a SMTP request into a dump file (mode = all) Used for debugging.
checkIfHTML ($msg)
Correct an uncomplete html string.
buildCSS ()
Build a css style (mode = all) into this->styleCSS and this->bodyCSS.
write_smtpheaders ()
Create SMTP headers (mode = 'mail')
write_mimeheaders ($filename_list, $mimefilename_list)
Create header MIME (mode = 'mail')
write_body ($msgtext)
Return email content (mode = 'mail')
write_files ($filename_list, $mimetype_list, $mimefilename_list)
Attach file to email (mode = 'mail')
write_images ($images_list)
Attach an image to email (mode = 'mail')
check_server_port ($host, $port)
Try to create a socket connection.
server_parse ($socket, $response)
This function has been modified as provided by SirSir to allow multiline responses when using SMTP Extensions.
findHtmlImages ($images_dir)
Seearch images into html message and init array this->images_encoded if found.
getArrayAddress ($address)
Return a formatted array of address string for SMTP protocol.
Static Public Member Functions
static encodetorfc2822 ($stringtoencode)
Encode subject according to RFC 2822 - http://en.wikipedia.org/wiki/MIME#Encoded-Word.
static getValidAddress ($address, $format, $encode=0, $maxnumberofemail=0)
Return a formatted address string for SMTP protocol.
Data Fields
$styleCSS
Defined css style for body background.
$bodyCSS
Defined background directly in body tag.
Private Member Functions
_encode_file ($sourcefile)
Read a file on disk and return encoded content for emails (mode = 'mail')
Detailed Description
Class to send emails (with attachments or not) Usage: $mailfile = new CMailFile($subject,$sendto,$replyto,$message,$filepath,$mimetype,$filename,$cc,$ccc,$deliveryreceipt,$msgishtml,$errors_to,$css,$trackid,$moreinheader,$sendcontext); $mailfile->sendfile();.
Definition at line 38 of file CMailFile.class.php.
Constructor & Destructor Documentation
__construct ($subject, $to, $from, $msg, $filename_list = array(), $mimetype_list = array(), $mimefilename_list = array(), $addr_cc = "", $addr_bcc = "", $deliveryreceipt = 0, $msgishtml = 0, $errors_to = '', $css = '', $trackid = '', $moreinheader = '', $sendcontext = 'standard', $replyto = '')
CMailFile.
Parameters
string $subject Topic/Subject of mail
string $to Recipients emails (RFC 2822: "Name firstname <email>[, ...]" or "email[, ...]" or "<email>[, ...]"). Note: the keyword 'SUPERVISOREMAIL' is not allowed here and must be replaced by caller.
string $from Sender email (RFC 2822: "Name firstname <email>[, ...]" or "email[, ...]" or "<email>[, ...]")
string $msg Message
array $filename_list List of files to attach (full path of filename on file system)
array $mimetype_list List of MIME type of attached files
array $mimefilename_list List of attached file name in message
string $addr_cc Email cc
string $addr_bcc Email bcc (Note: This is autocompleted with MAIN_MAIL_AUTOCOPY_TO if defined)
int $deliveryreceipt Ask a delivery receipt
int $msgishtml 1=String IS already html, 0=String IS NOT html, -1=Unknown make autodetection (with fast mode, not reliable)
string $errors_to Email for errors-to
string $css Css option
string $trackid Tracking string (contains type and id of related element)
string $moreinheader More in header. $moreinheader must contains the "\r\n" (TODO not supported for other MAIL_SEND_MODE different than 'phpmail' and 'smtps' for the moment)
string $sendcontext 'standard', 'emailing', ... (used to define with sending mode and parameters to use)
string $replyto Reply-to email (will be set to same value than From by default if not provided)
Definition at line 123 of file CMailFile.class.php.
References buildCSS(), checkIfHTML(), dol_syslog(), dol_textishtml(), encodetorfc2822(), findHtmlImages(), getArrayAddress(), getValidAddress(), if, write_body(), write_files(), write_mimeheaders(), and write_smtpheaders().
Member Function Documentation
_encode_file ($sourcefile) private
Read a file on disk and return encoded content for emails (mode = 'mail')
Parameters
string $sourcefile Path to file to encode
Returns
int <0 if KO, encoded string if OK
Definition at line 867 of file CMailFile.class.php.
References dol_osencode(), and dol_syslog().
Referenced by write_files().
buildCSS ()
Build a css style (mode = all) into this->styleCSS and this->bodyCSS.
Returns
string
Definition at line 958 of file CMailFile.class.php.
Referenced by __construct().
check_server_port ($host, $port)
Try to create a socket connection.
Parameters
string $host Add ssl:// for SSL/TLS.
int $port Example: 25, 465
Returns
int Socket id if ok, 0 if KO
Definition at line 1269 of file CMailFile.class.php.
References dol_syslog(), server_parse(), and utf8_check().
checkIfHTML ($msg)
Correct an uncomplete html string.
Parameters
string $msg String
Returns
string Completed string
Definition at line 933 of file CMailFile.class.php.
References $bodyCSS, and $styleCSS.
Referenced by __construct(), and write_body().
dump_mail ()
Write content of a SMTP request into a dump file (mode = all) Used for debugging.
Note that to see full SMTP protocol, you can use tcpdump -w /tmp/smtp -s 2000 port 25"
Returns
void
Definition at line 895 of file CMailFile.class.php.
Referenced by sendfile().
static encodetorfc2822 ($stringtoencode) static
Encode subject according to RFC 2822 - http://en.wikipedia.org/wiki/MIME#Encoded-Word.
Parameters
string $stringtoencode String to encode
Returns
string string encoded
Definition at line 854 of file CMailFile.class.php.
Referenced by __construct(), and sendfile().
findHtmlImages ($images_dir)
Seearch images into html message and init array this->images_encoded if found.
Parameters
string $images_dir Location of physical images files
Returns
int >0 if OK, <0 if KO
Definition at line 1364 of file CMailFile.class.php.
References dol_hash().
Referenced by __construct().
getArrayAddress ($address)
Return a formatted array of address string for SMTP protocol.
Parameters
string $address Example: 'John Doe john@.nosp@m.doe..nosp@m.com, Alan Smith alan@.nosp@m.smit.nosp@m.h.com' or 'john@.nosp@m.doe..nosp@m.com, alan@.nosp@m.smit.nosp@m.h.com'
Returns
array array of email => name
Definition at line 1538 of file CMailFile.class.php.
Referenced by __construct().
static getValidAddress ($address, $format, $encode = 0, $maxnumberofemail = 0) static
Return a formatted address string for SMTP protocol.
Parameters
string $address Example: 'John Doe john@.nosp@m.doe..nosp@m.com, Alan Smith alan@.nosp@m.smit.nosp@m.h.com' or 'john@.nosp@m.doe..nosp@m.com, alan@.nosp@m.smit.nosp@m.h.com'
int $format 0=auto, 1=emails with <>, 2=emails without <>, 3=auto + label between ", 4 label or email, 5 mailto link
int $encode 0=No encode name, 1=Encode name to RFC2822
int $maxnumberofemail 0=No limit. Otherwise, maximum number of emails returned ($address may contains several email separated with ','). Add '...' if there is more.
Returns
string If format 0: 'john@.nosp@m.doe..nosp@m.com' or 'John Doe john@.nosp@m.doe..nosp@m.com' or '=?UTF-8?B?Sm9obiBEb2U=?= john@.nosp@m.doe..nosp@m.com' If format 1: 'john@.nosp@m.doe..nosp@m.com' If format 2: 'john@.nosp@m.doe..nosp@m.com' If format 3: 'john@.nosp@m.doe..nosp@m.com' or '"John Doe" john@.nosp@m.doe..nosp@m.com' or '"=?UTF-8?B?Sm9obiBEb2U=?=" john@.nosp@m.doe..nosp@m.com' If format 4: 'John Doe' or 'john@.nosp@m.doe..nosp@m.com' if no label exists If format 5: John Doe or john@doe.com if no label exists
Definition at line 1467 of file CMailFile.class.php.
Referenced by __construct(), sendfile(), and Adherent\sendReminderForExpiredSubscription().
sendfile ()
Send mail that was prepared by constructor.
Returns
boolean True if mail sent, false otherwise
Definition at line 478 of file CMailFile.class.php.
References dol_syslog(), dump_mail(), encodetorfc2822(), and getValidAddress().
server_parse ($socket, $response)
This function has been modified as provided by SirSir to allow multiline responses when using SMTP Extensions.
Parameters
resource $socket Socket
string $response Response string
Returns
boolean true if success
Definition at line 1334 of file CMailFile.class.php.
Referenced by check_server_port().
write_body ($msgtext)
Return email content (mode = 'mail')
Parameters
string $msgtext Message string
Returns
string String content
Definition at line 1084 of file CMailFile.class.php.
References checkIfHTML(), and write_images().
Referenced by __construct().
write_files ($filename_list, $mimetype_list, $mimefilename_list)
Attach file to email (mode = 'mail')
Parameters
array $filename_list Tableau
array $mimetype_list Tableau
array $mimefilename_list Tableau
Returns
string Chaine fichiers encodes
Definition at line 1188 of file CMailFile.class.php.
References _encode_file(), and dol_syslog().
Referenced by __construct().
write_images ($images_list)
Attach an image to email (mode = 'mail')
Parameters
array $images_list Array of array image
Returns
string Chaine images encodees
Definition at line 1235 of file CMailFile.class.php.
References dol_syslog().
Referenced by write_body().
write_mimeheaders ($filename_list, $mimefilename_list)
Create header MIME (mode = 'mail')
Parameters
array $filename_list Array of filenames
array $mimefilename_list Array of mime types
Returns
string mime headers
Definition at line 1054 of file CMailFile.class.php.
References dol_syslog().
Referenced by __construct().
write_smtpheaders ()
Create SMTP headers (mode = 'mail')
Returns
string headers
Definition at line 988 of file CMailFile.class.php.
References dol_syslog().
Referenced by __construct().
The documentation for this class was generated from the following file:
htdocs/core/class/CMailFile.class.php