Dolibarr: FormResource Class Reference
FormResource Class Reference
Classe permettant la gestion des formulaire du module resource.
Public Member Functions
__construct ($db)
Constructor.
select_resource_list ($selected= '', $htmlname= 'fk_resource', $filter= '', $showempty=0, $showtype=0, $forcecombo=0, $event=array(), $filterkey= '', $outputmode=0, $limit=20)
Output html form to select a resource.
select_types_resource ($selected= '', $htmlname= 'type_resource', $filtertype= '', $format=0, $empty=0, $noadmininfo=0, $maxlength=0)
Return html list of tickets type.
Detailed Description
Classe permettant la gestion des formulaire du module resource.
Remarks
Utilisation: $formresource = new FormResource($db)
$formplace->proprietes=1 ou chaine ou tableau de valeurs
Definition at line 35 of file html.formresource.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 57 of file html.formresource.class.php.
References db.
Member Function Documentation
select_resource_list ($selected = '', $htmlname = 'fk_resource', $filter = '', $showempty = 0, $showtype = 0, $forcecombo = 0, $event = array(), $filterkey = '', $outputmode = 0, $limit = 20)
Output html form to select a resource.
Parameters
int $selected Preselected resource id
string $htmlname Name of field in form
string $filter Optionnal filters criteras (example: 's.rowid <> x')
int $showempty Add an empty field
int $showtype Show third party type in combolist (customer, prospect or supplier)
int $forcecombo Force to use combo box
array $event Event options. Example: array(array('method'=>'getContacts', 'url'=>dol_buildpath('/core/ajax/contacts.php',1), 'htmlname'=>'contactid', 'params'=>array('add-customer-contact'=>'disabled')))
string $filterkey Filter on key value
int $outputmode 0=HTML select string, 1=Array, 2=without form tag
int $limit Limit number of answers
Returns
string HTML string with
Definition at line 79 of file html.formresource.class.php.
References ajax_combobox(), db, and dol_print_error().
select_types_resource ($selected = '', $htmlname = 'type_resource', $filtertype = '', $format = 0, $empty = 0, $noadmininfo = 0, $maxlength = 0)
Return html list of tickets type.
Parameters
string $selected Id du type pre-selectionne
string $htmlname Nom de la zone select
string $filtertype To filter on field type in llx_c_ticket_type (array('code'=>xx,'label'=>zz))
int $format 0=id+libelle, 1=code+code, 2=code+libelle, 3=id+code
int $empty 1=peut etre vide, 0 sinon
int $noadmininfo 0=Add admin info, 1=Disable admin info
int $maxlength Max length of label
Returns
void
Definition at line 171 of file html.formresource.class.php.
References db, dol_syslog(), dol_trunc(), info_admin(), and print.
The documentation for this class was generated from the following file:
htdocs/resource/class/html.formresource.class.php