Dolibarr: DolLogsCollector Class Reference
DolLogsCollector Class Reference
DolLogsCollector class.
Public Member Functions
__construct ($path=null, $name= 'logs')
Constructor.
getWidgets ()
Return widget settings.
collect ()
Return collected data.
getLogsFile ()
Get the path to the logs file.
getStorageLogs ($path)
Get logs.
getLogs ($file)
Search a string for log entries.
getLevels ()
Get the log levels from psr/log.
Protected Member Functions
tailFile ($file, $lines)
Get latest file lines.
Detailed Description
DolLogsCollector class.
Definition at line 11 of file DolLogsCollector.php.
Constructor & Destructor Documentation
__construct ($path = null, $name = 'logs')
Constructor.
Parameters
string $path Path
string $name Name
Definition at line 28 of file DolLogsCollector.php.
References getLogsFile().
Member Function Documentation
collect ()
Return collected data.
Returns
array Array
Definition at line 71 of file DolLogsCollector.php.
References getLevels(), and getStorageLogs().
getLevels ()
Get the log levels from psr/log.
Returns
array Array of log level
Definition at line 201 of file DolLogsCollector.php.
Referenced by collect(), and getLogs().
getLogs ($file)
Search a string for log entries.
Parameters
string $file File
Returns
array Lines of logs
Definition at line 177 of file DolLogsCollector.php.
References getLevels().
Referenced by getStorageLogs().
getLogsFile ()
Get the path to the logs file.
Returns
string
Definition at line 107 of file DolLogsCollector.php.
Referenced by __construct().
getStorageLogs ($path)
Get logs.
Parameters
string $path Path
Returns
array
Definition at line 120 of file DolLogsCollector.php.
References getLogs(), and tailFile().
Referenced by collect().
getWidgets ()
Return widget settings.
Returns
array Array
Definition at line 45 of file DolLogsCollector.php.
tailFile ($file, $lines) protected
Get latest file lines.
Parameters
string $file File
int $lines Lines
Returns
array Array
Definition at line 141 of file DolLogsCollector.php.
Referenced by getStorageLogs().
The documentation for this class was generated from the following file:
htdocs/debugbar/class/DataCollector/DolLogsCollector.php