Dolibarr: ProductAttribute Class Reference
ProductAttribute Class Reference
Class ProductAttribute Used to represent a product attribute.
Public Member Functions
__construct (DoliDB $db)
Constructor.
fetch ($id)
Fetches the properties of a product attribute.
fetchAll ()
Returns an array of all product variants.
create (User $user)
Creates a product attribute.
update (User $user)
Updates a product attribute.
delete ()
Deletes a product attribute.
countChildValues ()
Returns the number of values for this attribute.
countChildProducts ()
Returns the number of products that are using this attribute.
moveUp ()
Shows this attribute before others.
moveDown ()
Shows this attribute after others.
Static Public Member Functions
static bulkUpdateOrder (DoliDB $db, array $order)
Updates the order of all variants.
Protected Member Functions
reorderLines ()
Reorders the order of the variants.
Private Member Functions
moveLine ($type)
Internal function to handle moveUp and moveDown functions.
Detailed Description
Class ProductAttribute Used to represent a product attribute.
Definition at line 23 of file ProductAttribute.class.php.
Constructor & Destructor Documentation
__construct (DoliDB $db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 61 of file ProductAttribute.class.php.
References db.
Member Function Documentation
static bulkUpdateOrder (DoliDB $db, array $order) static
Updates the order of all variants.
Used by AJAX page for drag&drop
Parameters
DoliDB $db Database handler
array $order Array with row id ordered in ascendent mode
Returns
int <0 KO >0 OK
Definition at line 329 of file ProductAttribute.class.php.
countChildProducts ()
Returns the number of products that are using this attribute.
Returns
int
Definition at line 211 of file ProductAttribute.class.php.
References db, and getEntity().
countChildValues ()
Returns the number of values for this attribute.
Returns
int
Definition at line 196 of file ProductAttribute.class.php.
References db.
create (User $user)
Creates a product attribute.
Parameters
User $user Object user that create
Returns
int <0 KO, Id of new variant if OK
Definition at line 135 of file ProductAttribute.class.php.
References db, and label.
delete ()
Deletes a product attribute.
Returns
int <0 KO, >0 OK
Definition at line 180 of file ProductAttribute.class.php.
References db.
fetch ($id)
Fetches the properties of a product attribute.
Parameters
int $id Attribute id
Returns
int <1 KO, >1 OK
Definition at line 75 of file ProductAttribute.class.php.
References db, getEntity(), and label.
fetchAll ()
Returns an array of all product variants.
Returns
ProductAttribute[]
Definition at line 104 of file ProductAttribute.class.php.
References db, dol_print_error(), and getEntity().
moveDown ()
Shows this attribute after others.
Returns
int <0 KO >0 OK
Definition at line 317 of file ProductAttribute.class.php.
References moveLine().
moveLine ($type) private
Internal function to handle moveUp and moveDown functions.
Parameters
string $type up/down
Returns
int <0 KO >0 OK
Definition at line 268 of file ProductAttribute.class.php.
References db, reorderLines(), and update().
Referenced by moveDown(), and moveUp().
moveUp ()
Shows this attribute before others.
Returns
int <0 KO >0 OK
Definition at line 307 of file ProductAttribute.class.php.
References moveLine().
reorderLines () protected
Reorders the order of the variants.
This is an internal function used by moveLine function
Returns
int <0 KO >0 OK
Definition at line 230 of file ProductAttribute.class.php.
References db.
Referenced by moveLine().
update (User $user)
Updates a product attribute.
Parameters
User $user Object user
Returns
int <0 KO, >0 OK
Definition at line 160 of file ProductAttribute.class.php.
References db, and label.
Referenced by moveLine().
The documentation for this class was generated from the following file:
htdocs/variants/class/ProductAttribute.class.php