Dolibarr: Conf Class Reference
Conf Class Reference
Class to stock current configuration.
Public Member Functions
__construct ()
Constructor.
setValues ($db)
Load setup values into conf object (read llx_const) Note that this->db->xxx, this->file->xxx and this->multicompany have been already loaded when setValues is called.
Data Fields
$file
To store properties found in conf file.
$global
To store properties found into database.
$browser
To store browser info.
$use_javascript_ajax
To store if javascript/ajax is enabked.
$currency
Used to store current currency (ISO code like 'USD', 'EUR', ...)
$theme
Used to store current css (from theme)
$standard_menu
Used to store current menu handler.
$multicompany
To store properties of multi-company.
$entity = 1
Used to store running instance for multi-company (default 1)
$entities = array()
Used to store list of entities to use for each element.
Detailed Description
Class to stock current configuration.
Definition at line 33 of file conf.class.php.
Constructor & Destructor Documentation
__construct ()
Constructor.
Charset for HTML output and for storing data in memory
Definition at line 103 of file conf.class.php.
References db, and user.
Member Function Documentation
setValues ($db)
Load setup values into conf object (read llx_const) Note that this->db->xxx, this->file->xxx and this->multicompany have been already loaded when setValues is called.
Parameters
DoliDB $db Database handler
Returns
int < 0 if KO, >= 0 if OK
Definition at line 150 of file conf.class.php.
References $file, $resql, dol_buildpath(), dol_include_once(), dol_osencode(), dol_sanitizeFileName(), dol_syslog(), if, and user.
The documentation for this class was generated from the following file:
htdocs/core/class/conf.class.php