Dolibarr: PropaleStats Class Reference
PropaleStats Class Reference
Class to manage proposals statistics.
Public Member Functions
__construct ($db, $socid=0, $userid=0, $mode= 'customer')
Constructor.
getNbByMonth ($year, $format=0)
Return propals number by month for a year.
getNbByYear ()
Return propals number per year.
getAmountByMonth ($year, $format)
Return the propals amount by month for a year.
getAverageByMonth ($year)
Return the propals amount average by month for a year.
getAllByYear ()
Return nb, total and average.
getAllByProduct ($year)
Return nb, amount of predefined product for year.
Public Member Functions inherited from Stats
getNbByMonthWithPrevYear ($endyear, $startyear, $cachedelay=0, $format=0, $startmonth=1)
Return nb of elements by month for several years.
getAmountByMonthWithPrevYear ($endyear, $startyear, $cachedelay=0, $format=0, $startmonth=1)
Return amount of elements by month for several years.
getAverageByMonthWithPrevYear ($endyear, $startyear)
Return average of entity by month for several years.
getAllByProductEntry ($year, $cachedelay=0)
Return count, and sum of products.
Additional Inherited Members
Protected Member Functions inherited from Stats
_getNbByYear ($sql)
Return nb of elements by year.
_getAllByYear ($sql)
Return nb of elements, total amount and avg amount each year.
_getNbByMonth ($year, $sql, $format=0)
Renvoie le nombre de documents par mois pour une annee donnee Return number of documents per month for a given year.
_getAmountByMonth ($year, $sql, $format=0)
Renvoie le montant totalise par mois pour une annee donnee Return the amount per month for a given year.
_getAverageByMonth ($year, $sql, $format=0)
Renvoie le montant moyen par mois pour une annee donnee Return the amount average par month for a given year.
_getAllByProduct ($sql, $limit=10)
Return number or total of product refs.
Detailed Description
Class to manage proposals statistics.
Definition at line 36 of file propalestats.class.php.
Constructor & Destructor Documentation
__construct ($db, $socid = 0, $userid = 0, $mode = 'customer')
Constructor.
Parameters
DoliDB $db Database handler
int $socid Id third party for filter. This value must be forced during the new to external user company if user is an external user.
int $userid Id user for filter (creation user)
string $mode Option ('customer', 'supplier')
Definition at line 59 of file propalestats.class.php.
References db.
Member Function Documentation
getAllByProduct ($year)
Return nb, amount of predefined product for year.
Parameters
int $year Year to scan
Returns
array Array of values
Definition at line 216 of file propalestats.class.php.
References Stats\_getAllByProduct(), db, dol_get_first_day(), and dol_get_last_day().
getAllByYear ()
Return nb, total and average.
Returns
array Array of values
Definition at line 194 of file propalestats.class.php.
References Stats\_getAllByYear(), and db.
getAmountByMonth ($year, $format)
Return the propals amount by month for a year.
Parameters
int $year Year to scan
int $format 0=Label of absiss is a translated text, 1=Label of absiss is month number, 2=Label of absiss is first letter of month
Returns
array Array with amount by month
Definition at line 152 of file propalestats.class.php.
References Stats\_getAmountByMonth(), db, dol_get_first_day(), and dol_get_last_day().
getAverageByMonth ($year)
Return the propals amount average by month for a year.
Parameters
int $year year for stats
Returns
array array with number by month
Definition at line 174 of file propalestats.class.php.
References Stats\_getAverageByMonth(), db, dol_get_first_day(), and dol_get_last_day().
getNbByMonth ($year, $format = 0)
Return propals number by month for a year.
Parameters
int $year Year to scan
int $format 0=Label of absiss is a translated text, 1=Label of absiss is month number, 2=Label of absiss is first letter of month
Returns
array Array with number by month
Definition at line 109 of file propalestats.class.php.
References Stats\_getNbByMonth(), db, dol_get_first_day(), and dol_get_last_day().
getNbByYear ()
Return propals number per year.
Returns
array Array with number by year
Definition at line 131 of file propalestats.class.php.
References Stats\_getNbByYear(), and db.
The documentation for this class was generated from the following file:
htdocs/comm/propal/class/propalestats.class.php