Dolibarr: FactureFournisseur Class Reference
FactureFournisseur Class Reference
Class to manage suppliers invoices.
Public Member Functions
__construct ($db)
Constructor.
create ($user)
Create supplier invoice into database.
fetch ($id= '', $ref= '')
Load object in memory from database.
fetch_lines ()
Load this->lines.
update ($user=null, $notrigger=0)
Update database.
insert_discount ($idremise)
Add a discount line into an invoice (as an invoice line) using an existing absolute discount (Consume the discount)
delete (User $user, $notrigger=0)
Delete invoice from database.
set_paid ($user, $close_code= '', $close_note= '')
Tag invoice as a payed invoice.
set_unpaid ($user)
Tag la facture comme non payee completement + appel trigger BILL_UNPAYED Fonction utilisee quand un paiement prelevement est refuse, ou quand une facture annulee et reouverte.
validate ($user, $force_number= '', $idwarehouse=0, $notrigger=0)
Tag invoice as validated + call trigger BILL_VALIDATE.
setDraft ($user, $idwarehouse=-1)
Set draft status.
addline ($desc, $pu, $txtva, $txlocaltax1, $txlocaltax2, $qty, $fk_product=0, $remise_percent=0, $date_start= '', $date_end= '', $ventil=0, $info_bits= '', $price_base_type= 'HT', $type=0, $rang=-1, $notrigger=false, $array_options=0, $fk_unit=null, $origin_id=0, $pu_ht_devise=0, $ref_supplier= '', $special_code= '')
Ajoute une ligne de facture (associe a aucun produit/service predefini) Les parametres sont deja cense etre juste et avec valeurs finales a l'appel de cette methode.
updateline ($id, $desc, $pu, $vatrate, $txlocaltax1=0, $txlocaltax2=0, $qty=1, $idproduct=0, $price_base_type= 'HT', $info_bits=0, $type=0, $remise_percent=0, $notrigger=false, $date_start= '', $date_end= '', $array_options=0, $fk_unit=null, $pu_ht_devise=0, $ref_supplier= '')
Update a line detail into database.
deleteline ($rowid, $notrigger=0)
Delete a detail line from database.
info ($id)
Charge les informations d'ordre info dans l'objet facture.
list_replacable_supplier_invoices ($socid=0)
Renvoi liste des factures remplacables Statut validee ou abandonnee pour raison autre + non payee + aucun paiement + pas deja remplacee.
list_qualified_avoir_supplier_invoices ($socid=0)
Renvoi liste des factures qualifiables pour correction par avoir Les factures qui respectent les regles suivantes sont retournees: (validee + paiement en cours) ou classee (payee completement ou payee partiellement) + pas deja remplacee + pas deja avoir.
load_board ($user)
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
getNomUrl ($withpicto=0, $option= '', $max=0, $short=0, $moretitle= '', $notooltip=0, $save_lastsearch_value=-1)
Return clicable name (with picto eventually)
getNextNumRef ($soc, $mode= 'next')
Return next reference of supplier invoice not already used (or last reference) according to numbering module defined into constant INVOICE_SUPPLIER_ADDON_NUMBER.
initAsSpecimen ($option= '')
Initialise an instance with random values.
load_state_board ()
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
createFromClone (User $user, $fromid, $invertdetail=0)
Load an object from its id and create a new one in database.
generateDocument ($modele, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0, $moreparams=null)
Create a document onto disk according to template model.
getRights ()
Returns the rights used for this class.
hasDelay ()
Is the payment of the supplier invoice having a delay?
isCreditNoteUsed ()
Is credit note used.
Public Member Functions inherited from CommonInvoice
getRemainToPay ($multicurrency=0)
Return remain amount to pay.
getSommePaiement ($multicurrency=0)
Return amount of payments already done.
getSumDepositsUsed ($multicurrency=0)
Return amount (with tax) of all deposits invoices used by invoice.
getSumCreditNotesUsed ($multicurrency=0)
Return amount (with tax) of all credit notes invoices + excess received used by invoice.
getSumFromThisCreditNotesNotUsed ($multicurrency=0)
Return amount (with tax) of all converted amount for this credit note.
getListIdAvoirFromInvoice ()
Renvoie tableau des ids de facture avoir issus de la facture.
getIdReplacingInvoice ($option= '')
Renvoie l'id de la facture qui la remplace.
getListOfPayments ($filtertype= '')
Return list of payments.
is_erasable ()
Return if an invoice can be deleted Rule is: If invoice is draft and has a temporary ref -> yes (1) If hidden option INVOICE_CAN_NEVER_BE_REMOVED is on -> no (0) If invoice is dispatched in bookkeeping -> no (-1) If invoice has a definitive ref, is not last and INVOICE_CAN_ALWAYS_BE_REMOVED off -> no (-2) If invoice not last in a cycle -> no (-3) If there is payment -> no (-4) Otherwise -> yes (2)
getVentilExportCompta ()
Return if an invoice was dispatched into bookkeeping.
getLibType ()
Return label of type of invoice.
getLibStatut ($mode=0, $alreadypaid=-1)
Return label of object status.
LibStatut ($paye, $status, $mode=0, $alreadypaid=-1, $type=0)
Return label of a status.
calculate_date_lim_reglement ($cond_reglement=0)
Renvoi une date limite de reglement de facture en fonction des conditions de reglements de la facture et date de facturation.
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0)
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source= 'external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source= 'internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source= '', $code= '')
Delete all links between an object $this and all its contacts.
liste_contact ($statut=-1, $source= 'external', $list=0, $code= '')
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source= 'internal', $order= 'position', $option=0, $activeonly=0, $code= '')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contactid into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table= '', $id=null, $format= '', $id_field= '', $fuser=null, $trigkey= '', $fk_user_field= 'fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source= 'external')
Return list of id of contacts of object.
setProject ($projectid)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id)
Change the payments terms.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder= 'ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix= '')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust= 'none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null)
Add objects linked in llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $clause= 'OR', $alsosametype=1, $orderby= 'sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
updateObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '')
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $rowid= '')
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType= '', $trigkey= '')
Set status of an object.
getCanvas ($id=0, $ref= '')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
display_incoterms ()
Return incoterms informations TODO Use a cache for label get.
getIncotermsForPDF ()
Return incoterms informations for pdf display.
setIncoterms ($id_incoterm, $location)
Define incoterms values of current object.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir= '/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir= '/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafieldsline=0, $defaulttpldir= '/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist= '', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist= '', $defaulttpldir= '/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
addThumbs ($file)
Build thumb Move this into files.lib.php.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($trigger_name, $user)
Call trigger based on this instance.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger= '', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update an extra field value for the current object.
showInputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
showOutputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss= '')
Return HTML string to show a field into a page Code very similar with showOutputField of extra fields.
showOptionals ($extrafields, $mode= 'view', $params=null, $keysuffix= '', $keyprefix= '', $onetrtd=0)
Function to show lines of extrafields with output datas.
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere= '')
Load object in memory from the database.
fetchLinesCommon ($morewhere= '')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
Static Public Member Functions
static replaceThirdparty (DoliDB $db, $origin_id, $dest_id)
Function used to replace a thirdparty id with another one.
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref= '', $ref_ext= '')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static commonReplaceThirdparty (DoliDB $db, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
Data Fields
$note
$fournisseur
const TYPE_STANDARD = 0
Standard invoice.
const TYPE_REPLACEMENT = 1
Replacement invoice.
const TYPE_CREDIT_NOTE = 2
Credit note invoice.
const TYPE_DEPOSIT = 3
Deposit invoice.
const STATUS_DRAFT = 0
Draft.
const STATUS_VALIDATED = 1
Validated (need to be paid)
const STATUS_CLOSED = 2
Classified paid.
const STATUS_ABANDONED = 3
Classified abandoned and no payment done.
Data Fields inherited from CommonInvoice
const TYPE_STANDARD = 0
Standard invoice.
const TYPE_REPLACEMENT = 1
Replacement invoice.
const TYPE_CREDIT_NOTE = 2
Credit note invoice.
const TYPE_DEPOSIT = 3
Deposit invoice.
const TYPE_PROFORMA = 4
Proforma invoice.
const TYPE_SITUATION = 5
Situation invoice.
const STATUS_DRAFT = 0
Draft status.
const STATUS_VALIDATED = 1
Validated (need to be paid)
const STATUS_CLOSED = 2
Classified paid.
const STATUS_ABANDONED = 3
Classified abandoned and no payment done.
Data Fields inherited from CommonObject
$projet
$note
Protected Attributes
$table_ref_field = 'ref'
{}
Additional Inherited Members
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
isNull ($info)
Function test if type is null.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare the values to insert.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ()
Function to concat keys of fields.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage suppliers invoices.
Definition at line 44 of file fournisseur.facture.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 275 of file fournisseur.facture.class.php.
References db.
Member Function Documentation
addline ($desc, $pu, $txtva, $txlocaltax1, $txlocaltax2, $qty, $fk_product = 0, $remise_percent = 0, $date_start = '', $date_end = '', $ventil = 0, $info_bits = '', $price_base_type = 'HT', $type = 0, $rang = -1, $notrigger = false, $array_options = 0, $fk_unit = null, $origin_id = 0, $pu_ht_devise = 0, $ref_supplier = '', $special_code = '')
Ajoute une ligne de facture (associe a aucun produit/service predefini) Les parametres sont deja cense etre juste et avec valeurs finales a l'appel de cette methode.
Aussi, pour le taux tva, il doit deja avoir ete defini par l'appelant par la methode get_default_tva(societe_vendeuse,societe_acheteuse,idprod) et le desc doit deja avoir la bonne valeur (a l'appelant de gerer le multilangue).
Parameters
string $desc Description de la ligne
double $pu Prix unitaire (HT ou TTC selon price_base_type, > 0 even for credit note)
double $txtva Force Vat rate to use, -1 for auto.
double $txlocaltax1 LocalTax1 Rate
double $txlocaltax2 LocalTax2 Rate
double $qty Quantite
int $fk_product Product/Service ID predefined
double $remise_percent Percentage discount of the line
integer $date_start Date de debut de validite du service
integer $date_end Date de fin de validite du service
string $ventil Code de ventilation comptable
int $info_bits Bits de type de lines
string $price_base_type HT ou TTC
int $type Type of line (0=product, 1=service)
int $rang Position of line
int $notrigger Disable triggers
array $array_options extrafields array
string $fk_unit Code of the unit to use. Null to use the default one
int $origin_id id origin document
double $pu_ht_devise Amount in currency
string $ref_supplier Supplier ref
string $special_code Special code
Returns
int >0 if OK, <0 if KO
Definition at line 1584 of file fournisseur.facture.class.php.
References calcul_price_total(), db, dol_syslog(), getLocalTaxesFromRate(), CommonObject\line_max(), CommonObject\line_order(), price2num(), type, and CommonObject\update_price().
create ($user)
Create supplier invoice into database.
Parameters
User $user object utilisateur qui cree
Returns
int Id invoice created if OK, < 0 if KO
Definition at line 288 of file fournisseur.facture.class.php.
References $resql, CommonObject\add_object_linked(), CommonObject\call_trigger(), db, description, dol_now(), dol_print_error(), dol_syslog(), MultiCurrency\getIdAndTxFromCode(), MultiCurrency\getIdFromCode(), CommonObject\insertExtraFields(), label, type, CommonObject\update_price(), and updateline().
createFromClone (User $user, $fromid, $invertdetail = 0)
Load an object from its id and create a new one in database.
Parameters
User $user User that clone
int $fromid Id of object to clone
int $invertdetail Reverse sign of amounts for lines
Returns
int New id of clone
Definition at line 2528 of file fournisseur.facture.class.php.
References db.
delete (User $user, $notrigger = 0)
Delete invoice from database.
Parameters
User $user User object
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 1060 of file fournisseur.facture.class.php.
References $resql, CommonObject\call_trigger(), db, CommonObject\deleteExtraFields(), CommonObject\deleteObjectLinked(), dol_delete_dir_recursive(), dol_delete_file(), dol_sanitizeFileName(), dol_syslog(), fetch_lines(), and get_exdir().
deleteline ($rowid, $notrigger = 0)
Delete a detail line from database.
Parameters
int $rowid Id of line to delete
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 1970 of file fournisseur.facture.class.php.
References db, dol_syslog(), and CommonObject\update_price().
fetch ($id = '', $ref = '')
Load object in memory from database.
Parameters
int $id Id supplier invoice
string $ref Ref supplier invoice
Returns
int <0 if KO, >0 if OK, 0 if not found
Definition at line 564 of file fournisseur.facture.class.php.
References $resql, db, dol_syslog(), fetch_lines(), CommonObject\fetch_optionals(), getEntity(), label, note, and type.
fetch_lines ()
Load this->lines.
Returns
int 1 si ok, < 0 si erreur
Definition at line 728 of file fournisseur.facture.class.php.
References db, and dol_syslog().
Referenced by delete(), fetch(), and validate().
generateDocument ($modele, $outputlangs, $hidedetails = 0, $hidedesc = 0, $hideref = 0, $moreparams = null)
Create a document onto disk according to template model.
Parameters
string $modele Force template to use ('' to not force)
Translate $outputlangs Object lang a utiliser pour traduction
int $hidedetails Hide details of lines
int $hidedesc Hide description
int $hideref Hide ref
null | array $moreparams Array to provide more information
Returns
int <0 if KO, 0 if nothing done, >0 if OK
Definition at line 2607 of file fournisseur.facture.class.php.
References CommonObject\commonGenerateDocument().
getNextNumRef ($soc, $mode = 'next')
Return next reference of supplier invoice not already used (or last reference) according to numbering module defined into constant INVOICE_SUPPLIER_ADDON_NUMBER.
Parameters
Societe $soc Thirdparty object
string $mode 'next' for next value or 'last' for last value
Returns
string free ref or last ref
Definition at line 2327 of file fournisseur.facture.class.php.
References dol_buildpath(), and dol_print_error().
Referenced by validate().
getNomUrl ($withpicto = 0, $option = '', $max = 0, $short = 0, $moretitle = '', $notooltip = 0, $save_lastsearch_value = -1)
Return clicable name (with picto eventually)
Parameters
int $withpicto 0=No picto, 1=Include picto into link, 2=Only picto
string $option Where point the link
int $max Max length of shown ref
int $short 1=Return just URL
string $moretitle Add more text to title tooltip
int $notooltip 1=Disable tooltip
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
Returns
string String with URL
Definition at line 2248 of file fournisseur.facture.class.php.
References dol_print_date(), dol_trunc(), img_object(), label, price(), and type.
getRights ()
Returns the rights used for this class.
Returns
stdClass
Definition at line 2642 of file fournisseur.facture.class.php.
hasDelay ()
Is the payment of the supplier invoice having a delay?
Returns
bool
Definition at line 2671 of file fournisseur.facture.class.php.
References dol_now().
info ($id)
Charge les informations d'ordre info dans l'objet facture.
Parameters
int $id Id de la facture a charger
Returns
void
Definition at line 2028 of file fournisseur.facture.class.php.
References db, and dol_print_error().
initAsSpecimen ($option = '')
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Parameters
string $option ''=Create a specimen invoice with lines, 'nolines'=No lines
Returns
void
Definition at line 2381 of file fournisseur.facture.class.php.
References $resql, db, and dol_now().
insert_discount ($idremise)
Add a discount line into an invoice (as an invoice line) using an existing absolute discount (Consume the discount)
Parameters
int $idremise Id of absolute discount
Returns
int >0 if OK, <0 if KO
Definition at line 956 of file fournisseur.facture.class.php.
References db, and CommonObject\update_price().
isCreditNoteUsed ()
Is credit note used.
Returns
bool
Definition at line 2689 of file fournisseur.facture.class.php.
References $resql.
list_qualified_avoir_supplier_invoices ($socid = 0)
Renvoi liste des factures qualifiables pour correction par avoir Les factures qui respectent les regles suivantes sont retournees: (validee + paiement en cours) ou classee (payee completement ou payee partiellement) + pas deja remplacee + pas deja avoir.
Parameters
int $socid Id societe
Returns
array|int Tableau des factures ($id => array('ref'=>,'paymentornot'=>,'status'=>,'paye'=>) <0 if error
Definition at line 2133 of file fournisseur.facture.class.php.
References $resql, db, and dol_syslog().
list_replacable_supplier_invoices ($socid = 0)
Renvoi liste des factures remplacables Statut validee ou abandonnee pour raison autre + non payee + aucun paiement + pas deja remplacee.
Parameters
int $socid Id societe
Returns
array|int Tableau des factures ('id'=>id, 'ref'=>ref, 'status'=>status, 'paymentornot'=>0/1) <0 if error
Definition at line 2081 of file fournisseur.facture.class.php.
References $resql, db, and dol_syslog().
load_board ($user)
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
Parameters
User $user Object user
Returns
WorkboardResponse|int <0 if KO, WorkboardResponse if OK
Definition at line 2183 of file fournisseur.facture.class.php.
References $resql, db, dol_now(), dol_print_error(), and img_object().
load_state_board ()
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
Returns
int <0 if KO, >0 if OK
Definition at line 2482 of file fournisseur.facture.class.php.
References $resql, db, and dol_print_error().
static replaceThirdparty (DoliDB $db, $origin_id, $dest_id) static
Function used to replace a thirdparty id with another one.
Parameters
DoliDB $db Database handler
int $origin_id Old thirdparty id
int $dest_id New thirdparty id
Returns
bool
Definition at line 2657 of file fournisseur.facture.class.php.
References CommonObject\commonReplaceThirdparty().
set_paid ($user, $close_code = '', $close_note = '')
Tag invoice as a payed invoice.
Parameters
User $user Object user
string $close_code Code renseigne si on classe a payee completement alors que paiement incomplet. Not implementd yet.
string $close_note Commentaire renseigne si on classe a payee alors que paiement incomplet. Not implementd yet.
Returns
int <0 si ko, >0 si ok
Definition at line 1211 of file fournisseur.facture.class.php.
References $resql, CommonObject\call_trigger(), db, dol_print_error(), and dol_syslog().
set_unpaid ($user)
Tag la facture comme non payee completement + appel trigger BILL_UNPAYED Fonction utilisee quand un paiement prelevement est refuse, ou quand une facture annulee et reouverte.
Parameters
User $user Object user that change status
Returns
int <0 si ok, >0 si ok
Definition at line 1261 of file fournisseur.facture.class.php.
References $resql, CommonObject\call_trigger(), db, and dol_syslog().
setDraft ($user, $idwarehouse = -1)
Set draft status.
Parameters
User $user Object user that modify
int $idwarehouse Id warehouse to use for stock change.
Returns
int <0 if KO, >0 if OK
Definition at line 1477 of file fournisseur.facture.class.php.
References CommonObject\call_trigger(), db, dol_syslog(), type, and TYPE_CREDIT_NOTE.
update ($user = null, $notrigger = 0)
Update database.
Parameters
User $user User that modify
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 828 of file fournisseur.facture.class.php.
References $resql, CommonObject\call_trigger(), db, dol_strlen(), dol_syslog(), label, note, and type.
updateline ($id, $desc, $pu, $vatrate, $txlocaltax1 = 0, $txlocaltax2 = 0, $qty = 1, $idproduct = 0, $price_base_type = 'HT', $info_bits = 0, $type = 0, $remise_percent = 0, $notrigger = false, $date_start = '', $date_end = '', $array_options = 0, $fk_unit = null, $pu_ht_devise = 0, $ref_supplier = '')
Update a line detail into database.
Parameters
int $id Id of line invoice
string $desc Description of line
double $pu Prix unitaire (HT ou TTC selon price_base_type)
double $vatrate VAT Rate (Can be '8.5', '8.5 (ABC)')
double $txlocaltax1 LocalTax1 Rate
double $txlocaltax2 LocalTax2 Rate
double $qty Quantity
int $idproduct Id produit
double $price_base_type HT or TTC
int $info_bits Miscellaneous informations of line
int $type Type of line (0=product, 1=service)
double $remise_percent Percentage discount of the line
int $notrigger Disable triggers
integer $date_start Date start of service
integer $date_end Date end of service
array $array_options extrafields array
string $fk_unit Code of the unit to use. Null to use the default one
double $pu_ht_devise Amount in currency
string $ref_supplier Supplier ref
Returns
int <0 if KO, >0 if OK
Definition at line 1836 of file fournisseur.facture.class.php.
References calcul_price_total(), db, dol_syslog(), getLocalTaxesFromRate(), price2num(), type, and CommonObject\update_price().
Referenced by create().
validate ($user, $force_number = '', $idwarehouse = 0, $notrigger = 0)
Tag invoice as validated + call trigger BILL_VALIDATE.
Parameters
User $user Object user that validate
string $force_number Reference to force on invoice
int $idwarehouse Id of warehouse for stock change
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, =0 if nothing to do, >0 if OK
Definition at line 1310 of file fournisseur.facture.class.php.
References $resql, CommonObject\call_trigger(), db, dol_dir_list(), dol_now(), dol_sanitizeFileName(), dol_syslog(), fetch_lines(), CommonObject\fetch_thirdparty(), get_exdir(), getNextNumRef(), price2num(), type, and TYPE_CREDIT_NOTE.
Field Documentation
$fournisseur
Deprecated:
Definition at line 188 of file fournisseur.facture.class.php.
$note
Deprecated:
See also
$note_private, $note_public
Definition at line 163 of file fournisseur.facture.class.php.
const STATUS_ABANDONED = 3
Classified abandoned and no payment done.
$this->close_code can be:
CLOSECODE_BADDEBT
CLOSECODE_ABANDONED
CLOSECODE_REPLACED
Definition at line 263 of file fournisseur.facture.class.php.
const STATUS_CLOSED = 2
Classified paid.
If paid partially, $this->close_code can be:
CLOSECODE_DISCOUNTVAT
CLOSECODE_BADDEBT If paid completelly, this->close_code will be null
Definition at line 254 of file fournisseur.facture.class.php.
The documentation for this class was generated from the following file:
htdocs/fourn/class/fournisseur.facture.class.php