Dolibarr: ExpenseReportLine Class Reference
ExpenseReportLine Class Reference
Class of expense report details lines.
Public Member Functions
__construct ($db)
Constructor.
fetch ($rowid)
Fetch record for expense report detailed line.
insert ($notrigger=0, $fromaddline=false)
insert
getExpAmount (ExpenseReportRule $rule, $fk_user, $mode= 'day')
Function to get total amount in expense reports for a same rule.
update (User $user)
Update line.
Detailed Description
Class of expense report details lines.
Definition at line 2467 of file expensereport.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Handlet database
Definition at line 2531 of file expensereport.class.php.
References db.
Member Function Documentation
fetch ($rowid)
Fetch record for expense report detailed line.
Parameters
int $rowid Id of object to load
Returns
int <0 if KO, >0 if OK
Definition at line 2542 of file expensereport.class.php.
References db, dol_print_error(), and vatrate().
getExpAmount (ExpenseReportRule $rule, $fk_user, $mode = 'day')
Function to get total amount in expense reports for a same rule.
Parameters
ExpenseReportRule $rule object rule to check
int $fk_user user author id
string $mode day|EX_DAY / month|EX_MON / year|EX_YEA to get amount
Returns
float Amount
Definition at line 2678 of file expensereport.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
insert ($notrigger = 0, $fromaddline = false)
insert
Parameters
int $notrigger 1=No trigger
bool $fromaddline false=keep default behavior, true=exclude the update_price() of parent object
Returns
int <0 if KO, >0 if OK
Definition at line 2596 of file expensereport.class.php.
References $resql, db, dol_syslog(), price2num(), and vatrate().
update (User $user)
Update line.
Parameters
User $user User
Returns
int <0 if KO, >0 if OK
Definition at line 2718 of file expensereport.class.php.
References $resql, db, dol_print_error(), dol_syslog(), price2num(), and vatrate().
The documentation for this class was generated from the following file:
htdocs/expensereport/class/expensereport.class.php