Dolibarr: htdocs/core/lib/invoice2.lib.php File Reference
invoice2.lib.php File Reference
Module invoices
Function to rebuild PDF and merge PDF files into one.
Functions
rebuild_merge_pdf ($db, $langs, $conf, $diroutputpdf, $newlangid, $filter, $dateafterdate, $datebeforedate, $paymentdateafter, $paymentdatebefore, $usestdout, $regenerate=0, $filesuffix= '', $paymentbankid= '', $thirdpartiesid= '', $fileprefix= 'mergedpdf')
Function to build a compiled PDF.
Detailed Description
Function to rebuild PDF and merge PDF files into one.
Definition in file invoice2.lib.php.
Function Documentation
rebuild_merge_pdf ($db, $langs, $conf, $diroutputpdf, $newlangid, $filter, $dateafterdate, $datebeforedate, $paymentdateafter, $paymentdatebefore, $usestdout, $regenerate = 0, $filesuffix = '', $paymentbankid = '', $thirdpartiesid = '', $fileprefix = 'mergedpdf')
Function to build a compiled PDF.
Parameters
DoliDB $db Database handler
Translate $langs Object langs
Conf $conf Object conf
string $diroutputpdf Dir to output file
string $newlangid Lang id
array $filter Array with filters
integer $dateafterdate Invoice after date
integer $datebeforedate Invoice before date
integer $paymentdateafter Payment after date (must includes hour)
integer $paymentdatebefore Payment before date (must includes hour)
int $usestdout Add information onto standard output
int $regenerate ''=Use existing PDF files, 'nameofpdf'=Regenerate all PDF files using the template
string $filesuffix Suffix to add into file name of generated PDF
string $paymentbankid Only if payment on this bank account id
array $thirdpartiesid List of thirdparties id when using filter excludethirdpartiesid or onlythirdpartiesid
string $fileprefix Prefix to add into filename of generated PDF
Returns
int Error code
Definition at line 50 of file invoice2.lib.php.
References $resql, dol_is_file(), dol_mkdir(), dol_print_error(), dol_syslog(), pdf_getFormat(), pdf_getInstance(), pdf_getPDFFont(), and print.