Dolibarr: PrestaShopWebservice Class Reference
PrestaShopWebservice Class Reference
Public Member Functions
__construct ($url, $key, $debug=true)
PrestaShopWebservice constructor.
executeRequest ($url, $curl_params=array())
Handles a CURL request to PrestaShop Webservice.
printDebug ($title, $content)
Output debug info.
getVersion ()
Return version.
add ($options)
Add (POST) a resource.
get ($options)
Retrieve (GET) a resource.
head ($options)
Head method (HEAD) a resource.
edit ($options)
Edit (PUT) a resource.
delete ($options)
Delete (DELETE) a resource.
Protected Member Functions
checkStatusCode ($status_code)
Take the status code and throw an exception if the server didn't return 200 or 201 code.
parseXML ($response)
Load XML from string.
Detailed Description
Definition at line 32 of file PSWebServiceLibrary.class.php.
Constructor & Destructor Documentation
__construct ($url, $key, $debug = true)
PrestaShopWebservice constructor.
Throw an exception when CURL is not installed/activated <?php require_once './PrestaShopWebservice.php'; try { $ws = new PrestaShopWebservice('http://mystore.com/', 'ZQ88PRJX5VWQHCWE4EE7SQ7HPNX00RAJ', false); // Now we have a webservice object to play with } catch (PrestaShopWebserviceException $ex) { echo 'Error : '.$ex->getMessage(); } ?>
Parameters
string $url Root URL for the shop
string $key Authentification key
mixed $debug Debug mode Activated (true) or deactivated (false)
Definition at line 72 of file PSWebServiceLibrary.class.php.
Member Function Documentation
add ($options)
Add (POST) a resource.
Unique parameter must take :
'resource' => Resource name
'postXml' => Full XML string to add resource<br>
Examples are given in the tutorial
Parameters
array $options Options
Returns
SimpleXMLElement status_code, response
Definition at line 254 of file PSWebServiceLibrary.class.php.
checkStatusCode ($status_code) protected
Take the status code and throw an exception if the server didn't return 200 or 201 code.
Parameters
int $status_code Status code of an HTTP return
Returns
void
Definition at line 88 of file PSWebServiceLibrary.class.php.
delete ($options)
Delete (DELETE) a resource.
Unique parameter must take :
'resource' => Resource name
'id' => ID or array which contains IDs of a resource(s) you want to delete<br>
<?php require_once('./PrestaShopWebservice.php'); try { $ws = new PrestaShopWebservice('http://mystore.com/', 'ZQ88PRJX5VWQHCWE4EE7SQ7HPNX00RAJ', false); $xml = $ws->delete(array('resource' => 'orders', 'id' => 1)); // Following code will not be executed if an exception is thrown. echo 'Successfully deleted.'; } catch (PrestaShopWebserviceException $ex) { echo 'Error : '.$ex->getMessage(); } ?>
Parameters
array $options Array representing resource to delete.
Returns
boolean True
Definition at line 421 of file PSWebServiceLibrary.class.php.
edit ($options)
Edit (PUT) a resource.
Unique parameter must take :
'resource' => Resource name ,
'id' => ID of a resource you want to edit,
'putXml' => Modified XML string of a resource<br>
Examples are given in the tutorial
Parameters
array $options Array representing resource to edit.
Returns
SimpleXMLElement status_code, response
Definition at line 374 of file PSWebServiceLibrary.class.php.
executeRequest ($url, $curl_params = array())
Handles a CURL request to PrestaShop Webservice.
Can throw exception.
Parameters
string $url Resource name
mixed $curl_params CURL parameters (sent to curl_set_opt)
Returns
array status_code, response
Definition at line 120 of file PSWebServiceLibrary.class.php.
References dol_syslog(), and printDebug().
get ($options)
Retrieve (GET) a resource.
Unique parameter must take :
'url' => Full URL for a GET request of Webservice (ex: http://mystore.com/api/customers/1/)
OR
'resource' => Resource name,
'id' => ID of a resource you want to get<br>
<?php require_once './PrestaShopWebservice.php'; try { $ws = new PrestaShopWebservice('http://mystore.com/', 'ZQ88PRJX5VWQHCWE4EE7SQ7HPNX00RAJ', false); $xml = $ws->get(array('resource' => 'orders', 'id' => 1)); // Here in $xml, a SimpleXMLElement object you can parse foreach ($xml->children()->children() as $attName => $attValue) echo $attName.' = '.$attValue.'
'; } catch (PrestaShopWebserviceException $ex) { echo 'Error : '.$ex->getMessage(); } ?>
Parameters
array $options Array representing resource to get.
Returns
SimpleXMLElement status_code, response
Definition at line 303 of file PSWebServiceLibrary.class.php.
getVersion ()
Return version.
Returns
string Version
Definition at line 214 of file PSWebServiceLibrary.class.php.
head ($options)
Head method (HEAD) a resource.
Parameters
array $options Array representing resource for head request.
Returns
SimpleXMLElement status_code, response
Definition at line 338 of file PSWebServiceLibrary.class.php.
parseXML ($response) protected
Load XML from string.
Can throw exception
Parameters
string $response String from a CURL response
Returns
SimpleXMLElement status_code, response
Definition at line 225 of file PSWebServiceLibrary.class.php.
printDebug ($title, $content)
Output debug info.
Parameters
string $title Title
string $content Content
Returns
void
Definition at line 204 of file PSWebServiceLibrary.class.php.
Referenced by executeRequest().
The documentation for this class was generated from the following file:
htdocs/admin/dolistore/class/PSWebServiceLibrary.class.php