Dolibarr: mod_supplier_payment_brodator Class Reference
mod_supplier_payment_brodator Class Reference
Class to manage customer payment numbering rules Ant.
Public Member Functions
info ()
Returns the description of the numbering model.
getExample ()
Renvoi un exemple de numerotation.
getNextValue ($objsoc, $object)
Return next free value.
commande_get_num ($objsoc, $objforref)
Return next free value.
Public Member Functions inherited from ModeleNumRefSupplierPayments
isEnabled ()
Return if a module can be used or not.
info ()
Return the default description of numbering module.
getExample ()
Return numbering example.
canBeActivated ()
Test if the existing numbers in the database do not cause conflicts that would prevent this numbering run.
getNextValue ($objsoc, $object)
Returns the next value.
getVersion ()
Returns the module numbering version.
Detailed Description
Class to manage customer payment numbering rules Ant.
Definition at line 31 of file mod_supplier_payment_brodator.php.
Member Function Documentation
commande_get_num ($objsoc, $objforref)
Return next free value.
Parameters
Societe $objsoc Object third party
string $objforref Object for number to search
Returns
string Next free value
Definition at line 154 of file mod_supplier_payment_brodator.php.
References getNextValue().
getExample ()
Renvoi un exemple de numerotation.
Returns
string Example
Definition at line 102 of file mod_supplier_payment_brodator.php.
References getNextValue().
getNextValue ($objsoc, $object)
Return next free value.
Parameters
Societe $objsoc Object thirdparty
Object $object Object we need next value for
Returns
string Value if KO, <0 if KO
Definition at line 125 of file mod_supplier_payment_brodator.php.
References get_next_value().
Referenced by commande_get_num(), and getExample().
info ()
Returns the description of the numbering model.
Returns
string Texte descripif
Definition at line 62 of file mod_supplier_payment_brodator.php.
References db.
The documentation for this class was generated from the following file:
htdocs/core/modules/supplier_payment/mod_supplier_payment_brodator.php