Dolibarr: FormSms Class Reference
FormSms Class Reference
Classe permettant la generation du formulaire d'envoi de Sms Usage: $formsms = new FormSms($db) $formsms->proprietes=1 ou chaine ou tableau de valeurs $formsms->show_form() affiche le formulaire.
Public Member Functions
__construct ($db)
Constructor.
show_form ($morecss= 'titlefield', $showform=1)
Show the form to input an sms.
Detailed Description
Classe permettant la generation du formulaire d'envoi de Sms Usage: $formsms = new FormSms($db) $formsms->proprietes=1 ou chaine ou tableau de valeurs $formsms->show_form() affiche le formulaire.
Definition at line 34 of file html.formsms.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 79 of file html.formsms.class.php.
References db.
Member Function Documentation
show_form ($morecss = 'titlefield', $showform = 1)
Show the form to input an sms.
Parameters
string $morecss Class on first column td
int $showform Show form tags and submit button (recommanded is to use with value 0)
Returns
void
Definition at line 103 of file html.formsms.class.php.
References db, dol_include_once(), dol_print_error(), dol_strlen(), dol_syslog(), GETPOST(), make_substitutions(), and print.
The documentation for this class was generated from the following file:
htdocs/core/class/html.formsms.class.php