Dolibarr: AgendaEvents Class Reference
AgendaEvents Class Reference
Public Member Functions
__construct ()
Constructor.
get ($id)
Get properties of a Agenda Events object.
index ($sortfield="t.id", $sortorder= 'ASC', $limit=100, $page=0, $user_ids=0, $sqlfilters= '')
List Agenda Events.
post ($request_data=null)
Create Agenda Event object.
delete ($id)
Update Agenda Event general fields.
Public Member Functions inherited from DolibarrApi
__construct ($db, $cachedir= '', $refreshCache=false)
Constructor.
Protected Member Functions
_cleanObjectDatas ($object)
Clean sensible object datas.
Protected Member Functions inherited from DolibarrApi
_cleanObjectDatas ($object)
Executed method when API is called without parameter.
_checkFilters ($sqlfilters)
Return if a $sqlfilters parameter is valid.
Private Member Functions
_validate ($data)
Validate fields before create or update object.
Additional Inherited Members
Static Protected Member Functions inherited from DolibarrApi
static _checkAccessToResource ($resource, $resource_id=0, $dbtablename= '', $feature2= '', $dbt_keyfield= 'fk_soc', $dbt_select= 'rowid')
Check user access to a resource.
static _forge_criteria_callback ($matches)
Function to forge a SQL criteria.
Detailed Description
Definition at line 29 of file api_agendaevents.class.php.
Member Function Documentation
_cleanObjectDatas ($object) protected
Clean sensible object datas.
Parameters
object $object Object to clean
Returns
array Array of cleaned object properties
Definition at line 323 of file api_agendaevents.class.php.
Referenced by get(), and index().
_validate ($data) private
Validate fields before create or update object.
Parameters
array $data Array with data to verify
Returns
array
Exceptions
RestException
Definition at line 305 of file api_agendaevents.class.php.
Referenced by post().
delete ($id)
Update Agenda Event general fields.
Parameters
int $id Id of Agenda Event to update
array $request_data Datas
Returns
int Delete Agenda Event
Parameters
int $id Agenda Event ID
Returns
array
Definition at line 266 of file api_agendaevents.class.php.
References DolibarrApi\_checkAccessToResource().
get ($id)
Get properties of a Agenda Events object.
Return an array with Agenda Events informations
Parameters
int $id ID of Agenda Events
Returns
array|mixed Data without useless information
Exceptions
RestException
Definition at line 64 of file api_agendaevents.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
index ($sortfield = "t.id", $sortorder = 'ASC', $limit = 100, $page = 0, $user_ids = 0, $sqlfilters = '')
List Agenda Events.
Get a list of Agenda Events
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Limit for list
int $page Page number
string $user_ids User ids filter field (owners of event). Example: '1' or '1,2,3' { /^[0-9,]*$/i}
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.label:like:'%dol%') and (t.datec:<:'20160101')"
Returns
array Array of Agenda Events objects
Definition at line 102 of file api_agendaevents.class.php.
References DolibarrApi\_checkFilters(), and _cleanObjectDatas().
post ($request_data = null)
Create Agenda Event object.
Parameters
array $request_data Request data
Returns
int ID of Agenda Event
Definition at line 191 of file api_agendaevents.class.php.
References _validate().
The documentation for this class was generated from the following file:
htdocs/comm/action/class/api_agendaevents.class.php