Dolibarr: htdocs/core/lib/functions.lib.php File Reference
functions.lib.php File Reference
A set of functions for Dolibarr This file contains all frequently used functions.
Functions
getDoliDBInstance ($type, $host, $user, $pass, $name, $port)
Return a DoliDB instance (database handler).
getEntity ($element, $shared=1, $currentobject=null)
Get list of entity id to use.
setEntity ($currentobject)
Set entity id to use when to create an object.
getBrowserInfo ($user_agent)
Return information about user browser.
dol_shutdown ()
Function called at end of web php process.
GETPOSTISSET ($paramname)
Return true if we are in a context of submitting a parameter.
GETPOST ($paramname, $check= 'none', $method=0, $filter=null, $options=null, $noreplace=0)
Return value of a param into GET or POST supervariable.
if(!function_exists('dol_getprefix')) dol_include_once ($relpath, $classname= '')
Make an include_once using default root and alternate root if it fails.
dol_buildpath ($path, $type=0, $returnemptyifnotfound=0)
Return path of url or filesystem.
dol_clone ($object, $native=0)
Create a clone of instance of object (new instance with same value for properties) With native = 0: Property that are reference are also new object (full isolation clone).
dol_size ($size, $type= '')
Optimize a size for some browsers (phone, smarphone, ...)
dol_sanitizeFileName ($str, $newstr= '_', $unaccent=1)
Clean a string to use it as a file name.
dol_sanitizePathName ($str, $newstr= '_', $unaccent=1)
Clean a string to use it as a path name.
dol_string_unaccent ($str)
Clean a string from all accent characters to be used as ref, login or by dol_sanitizeFileName.
dol_string_nospecial ($str, $newstr= '_', $badcharstoreplace= '')
Clean a string from all punctuation characters to use it as a ref or login.
dol_escape_js ($stringtoescape, $mode=0, $noescapebackslashn=0)
Returns text escaped for inclusion into javascript code.
dol_escape_htmltag ($stringtoescape, $keepb=0, $keepn=0)
Returns text escaped for inclusion in HTML alt or title tags, or into values of HTML input fields.
dol_strtolower ($utf8_string)
Convert a string to lower.
dol_strtoupper ($utf8_string)
Convert a string to upper.
dol_syslog ($message, $level=LOG_INFO, $ident=0, $suffixinfilename= '', $restricttologhandler= '', $logcontext=null)
Write log message into outputs.
dol_fiche_head ($links=array(), $active= '0', $title= '', $notab=0, $picto= '', $pictoisfullpath=0, $morehtmlright= '', $morecss= '')
Show tab header of a card.
dol_get_fiche_head ($links=array(), $active= '', $title= '', $notab=0, $picto= '', $pictoisfullpath=0, $morehtmlright= '', $morecss= '')
Show tab header of a card.
dol_fiche_end ($notab=0)
Show tab footer of a card.
dol_get_fiche_end ($notab=0)
Return tab footer of a card.
dol_banner_tab ($object, $paramid, $morehtml= '', $shownav=1, $fieldid= 'rowid', $fieldref= 'ref', $morehtmlref= '', $moreparam= '', $nodbprefix=0, $morehtmlleft= '', $morehtmlstatus= '', $onlybanner=0, $morehtmlright= '')
Show tab footer of a card.
fieldLabel ($langkey, $fieldkey, $fieldrequired=0)
Show a string with the label tag dedicated to the HTML edit field.
dol_bc ($var, $moreclass= '')
Return string to add class property on html element with pair/impair.
dol_format_address ($object, $withcountry=0, $sep="\n", $outputlangs= '', $mode=0)
Return a formated address (part address/zip/town/state) according to country rules.
dol_strftime ($fmt, $ts=false, $is_gmt=false)
Format a string.
dol_print_date ($time, $format= '', $tzoutput= 'tzserver', $outputlangs= '', $encodetooutput=false)
Output date in a string format according to outputlangs (or langs if not defined).
dol_getdate ($timestamp, $fast=false)
Return an array with locale date info.
dol_mktime ($hour, $minute, $second, $month, $day, $year, $gm=false, $check=1)
Return a timestamp date built from detailed informations (by default a local PHP server timestamp) Replace function mktime not available under Windows if year < 1970 PHP mktime is restricted to the years 1901-2038 on Unix and 1970-2038 on Windows.
dol_now ($mode= 'gmt')
Return date for now.
dol_print_size ($size, $shortvalue=0, $shortunit=0)
Return string with formated size.
dol_print_url ($url, $target= '_blank', $max=32, $withpicto=0)
Show Url link.
dol_print_email ($email, $cid=0, $socid=0, $addlink=0, $max=64, $showinvalid=1, $withpicto=0)
Show EMail link.
dol_print_socialnetworks ($value, $cid, $socid, $type)
Show social network link.
dol_print_phone ($phone, $countrycode= '', $cid=0, $socid=0, $addlink= '', $separ="&nbsp;", $withpicto= '', $titlealt= '', $adddivfloat=0)
Format phone numbers according to country.
dol_print_ip ($ip, $mode=0)
Return an IP formated to be shown on screen.
getUserRemoteIP ()
Return the IP of remote user.
dolGetCountryCodeFromIp ($ip)
Return a country code from IP.
dol_user_country ()
Return country code for current user.
dol_print_address ($address, $htmlid, $mode, $id, $noprint=0, $charfornl= '')
Format address string.
isValidEmail ($address, $acceptsupervisorkey=0)
Return true if email syntax is ok.
isValidMXRecord ($domain)
Return if the domain name has a valid MX record.
isValidPhone ($phone)
Return true if phone number syntax is ok TODO Decide what to do with this.
dol_strlen ($string, $stringencoding= 'UTF-8')
Make a strlen call.
dol_substr ($string, $start, $length, $stringencoding= '', $trunconbytes=0)
Make a substring.
dol_trunc ($string, $size=40, $trunc= 'right', $stringencoding= 'UTF-8', $nodot=0, $display=0)
Truncate a string to a particular length adding '...' if string larger than length.
img_picto ($titlealt, $picto, $moreatt= '', $pictoisfullpath=false, $srconly=0, $notitle=0, $alt= '', $morecss= '', $marginleftonlyshort=2)
Show picto whatever it's its name (generic function)
img_object ($titlealt, $picto, $moreatt= '', $pictoisfullpath=false, $srconly=0, $notitle=0)
Show a picto called object_picto (generic function)
img_weather ($titlealt, $picto, $moreatt= '', $pictoisfullpath=0, $morecss= '')
Show weather picto.
img_picto_common ($titlealt, $picto, $moreatt= '', $pictoisfullpath=0)
Show picto (generic function)
img_action ($titlealt, $numaction)
Show logo action.
img_pdf ($titlealt= 'default', $size=3)
Show pdf logo.
img_edit_add ($titlealt= 'default', $other= '')
Show logo +.
img_edit_remove ($titlealt= 'default', $other= '')
Show logo -.
img_edit ($titlealt= 'default', $float=0, $other= '')
Show logo editer/modifier fiche.
img_view ($titlealt= 'default', $float=0, $other= '')
Show logo view card.
img_delete ($titlealt= 'default', $other= 'class="pictodelete"')
Show delete logo.
img_printer ($titlealt="default", $other= '')
Show printer logo.
img_split ($titlealt= 'default', $other= 'class="pictosplit"')
Show split logo.
img_help ($usehelpcursor=1, $usealttitle=1)
Show help logo with cursor "?".
img_info ($titlealt= 'default')
Show info logo.
img_warning ($titlealt= 'default', $moreatt= '', $morecss= 'pictowarning')
Show warning logo.
img_error ($titlealt= 'default')
Show error logo.
img_next ($titlealt= 'default', $moreatt= '')
Show next logo.
img_previous ($titlealt= 'default', $moreatt= '')
Show previous logo.
img_down ($titlealt= 'default', $selected=0, $moreclass= '')
Show down arrow logo.
img_up ($titlealt= 'default', $selected=0, $moreclass= '')
Show top arrow logo.
img_left ($titlealt= 'default', $selected=0, $moreatt= '')
Show left arrow logo.
img_right ($titlealt= 'default', $selected=0, $moreatt= '')
Show right arrow logo.
img_allow ($allow, $titlealt= 'default')
Show tick logo if allowed.
img_credit_card ($brand)
Return image of a credit card according to its brand name.
img_mime ($file, $titlealt= '', $morecss= '')
Show MIME img of a file.
img_search ($titlealt= 'default', $other= '')
Show search logo.
img_searchclear ($titlealt= 'default', $other= '')
Show search logo.
info_admin ($text, $infoonimgalt=0, $nodiv=0, $admin= '1', $morecss= '')
Show information for admin users or standard users.
dol_print_error ($db= '', $error= '', $errors=null)
Affiche message erreur system avec toutes les informations pour faciliter le diagnostic et la remontee des bugs.
dol_print_error_email ($prefixcode, $errormessage= '', $errormessages=array(), $morecss= 'error', $email= '')
Show a public email and error code to contact if technical error.
print_liste_field_titre ($name, $file="", $field="", $begin="", $moreparam="", $moreattrib="", $sortfield="", $sortorder="", $prefix="", $tooltip="")
Show title line of an array.
getTitleFieldOfList ($name, $thead=0, $file="", $field="", $begin="", $moreparam="", $moreattrib="", $sortfield="", $sortorder="", $prefix="", $disablesortlink=0, $tooltip= '')
Get title line of an array.
print_titre ($title)
Show a title.
print_fiche_titre ($title, $mesg= '', $picto= 'title_generic.png', $pictoisfullpath=0, $id= '')
Show a title with picto.
load_fiche_titre ($titre, $morehtmlright= '', $picto= 'title_generic.png', $pictoisfullpath=0, $id= '', $morecssontable= '', $morehtmlcenter= '')
Load a title with picto.
print_barre_liste ($titre, $page, $file, $options= '', $sortfield= '', $sortorder= '', $morehtmlcenter= '', $num=-1, $totalnboflines= '', $picto= 'title_generic.png', $pictoisfullpath=0, $morehtmlright= '', $morecss= '', $limit=-1, $hideselectlimit=0, $hidenavigation=0)
Print a title with navigation controls for pagination.
print_fleche_navigation ($page, $file, $options= '', $nextpage=0, $betweenarrows= '', $afterarrows= '', $limit=-1, $totalnboflines=0, $hideselectlimit=0)
Function to show navigation arrows into lists.
vatrate ($rate, $addpercent=false, $info_bits=0, $usestarfornpr=0)
Return a string with VAT rate label formated for view output Used into pdf and HTML pages.
price ($amount, $form=0, $outlangs= '', $trunc=1, $rounding=-1, $forcerounding=-1, $currency_code= '')
Function to format a value into an amount for visual output Function used into PDF and HTML pages.
price2num ($amount, $rounding= '', $alreadysqlnb=0)
Function that return a number with universal decimal format (decimal separator is '.
showDimensionInBestUnit ($dimension, $unit, $type, $outputlangs, $round=-1, $forceunitoutput= 'no')
Output a dimension with best unit.
get_localtax ($vatrate, $local, $thirdparty_buyer="", $thirdparty_seller="", $vatnpr=0)
Return localtax rate for a particular vat, when selling a product with vat $vatrate, from a $thirdparty_buyer to a $thirdparty_seller Note: This function applies same rules than get_default_tva.
isOnlyOneLocalTax ($local)
Return true if LocalTax (1 or 2) is unique.
get_localtax_by_third ($local)
Get values of localtaxes (1 or 2) for company country for the common vat with the highest value.
getTaxesFromId ($vatrate, $buyer=null, $seller=null, $firstparamisid=1)
Get vat main information from Id.
getLocalTaxesFromRate ($vatrate, $local, $buyer, $seller, $firstparamisid=0)
Get type and rate of localtaxes for a particular vat rate/country of a thirdparty.
get_product_vat_for_country ($idprod, $thirdparty_seller, $idprodfournprice=0)
Return vat rate of a product in a particular selling country or default country vat if product is unknown Function called by get_default_tva.
get_product_localtax_for_country ($idprod, $local, $thirdparty_seller)
Return localtax vat rate of a product in a particular selling country or default country vat if product is unknown.
get_default_tva (Societe $thirdparty_seller, Societe $thirdparty_buyer, $idprod=0, $idprodfournprice=0)
Function that return vat rate of a product line (according to seller, buyer and product vat rate) Si vendeur non assujeti a TVA, TVA par defaut=0.
get_default_npr (Societe $thirdparty_seller, Societe $thirdparty_buyer, $idprod=0, $idprodfournprice=0)
Fonction qui renvoie si tva doit etre tva percue recuperable.
get_default_localtax ($thirdparty_seller, $thirdparty_buyer, $local, $idprod=0)
Function that return localtax of a product line (according to seller, buyer and product vat rate) Si vendeur non assujeti a TVA, TVA par defaut=0.
yn ($yesno, $case=1, $color=0)
Return yes or no in current language.
get_exdir ($num, $level, $alpha, $withoutslash, $object, $modulepart)
Return a path to have a the directory according to object where files are stored.
dol_mkdir ($dir, $dataroot= '', $newmask=null)
Creation of a directory (this can create recursive subdir)
picto_required ()
Return picto saying a field is required.
dol_string_nohtmltag ($stringtoclean, $removelinefeed=1, $pagecodeto= 'UTF-8', $strip_tags=0)
Clean a string from all HTML tags and entities.
dol_string_onlythesehtmltags ($stringtoclean)
Clean a string to keep only desirable HTML tags.
dol_string_neverthesehtmltags ($stringtoclean, $disallowed_tags=array('textarea'))
Clean a string from some undesirable HTML tags.
dolGetFirstLineOfText ($text, $nboflines=1, $charset= 'UTF-8')
Return first line of text.
dol_nl2br ($stringtoencode, $nl2brmode=0, $forxml=false)
Replace CRLF in string with a HTML BR tag.
dol_htmlentitiesbr ($stringtoencode, $nl2brmode=0, $pagecodefrom= 'UTF-8', $removelasteolbr=1)
This function is called to encode a string into a HTML string but differs from htmlentities because a detection is done before to see if text is already HTML or not.
dol_htmlentitiesbr_decode ($stringtodecode, $pagecodeto= 'UTF-8')
This function is called to decode a HTML string (it decodes entities and br tags)
dol_htmlcleanlastbr ($stringtodecode)
This function remove all ending
and br at end.
dol_html_entity_decode ($a, $b, $c= 'UTF-8')
Replace html_entity_decode functions to manage errors.
dol_htmlentities ($string, $flags=null, $encoding= 'UTF-8', $double_encode=false)
Replace htmlentities functions.
dol_string_is_good_iso ($s)
Check if a string is a correct iso string If not, it will we considered not HTML encoded even if it is by FPDF.
dol_nboflines ($s, $maxchar=0)
Return nb of lines of a clear text.
dol_nboflines_bis ($text, $maxlinesize=0, $charset= 'UTF-8')
Return nb of lines of a formated text with
and
(WARNING: string must not have mixed
and br separators)
dol_microtime_float ()
Same function than microtime in PHP 5 but compatible with PHP4.
dol_textishtml ($msg, $option=0)
Return if a text is a html content.
dol_concatdesc ($text1, $text2, $forxml=false, $invert=false)
Concat 2 descriptions with a new line between them (second operand after first one with appropriate new line separator) text1 html + text2 html => text1 + '
' + text2 text1 html + text2 txt => text1 + '
' + dol_nl2br(text2) text1 txt + text2 html => dol_nl2br(text1) + '
' + text2 text1 txt + text2 txt => text1 + '
' + text2.
getCommonSubstitutionArray ($outputlangs, $onlykey=0, $exclude=null, $object=null)
Return array of possible common substitutions.
make_substitutions ($text, $substitutionarray, $outputlangs=null)
Make substitution into a text string, replacing keys with vals from $substitutionarray (oldval=>newval), and texts like __(TranslationKey|langfile)__ and [ConstantKey] are also replaced.
complete_substitutions_array (&$substitutionarray, $outputlangs, $object=null, $parameters=null, $callfunc="completesubstitutionarray")
Complete the $substitutionarray with more entries coming from external module that had set the "substitutions=1" into module_part array.
print_date_range ($date_start, $date_end, $format= '', $outputlangs= '')
Format output for start and end date.
get_date_range ($date_start, $date_end, $format= '', $outputlangs= '', $withparenthesis=1)
Format output for start and end date.
dolGetFirstLastname ($firstname, $lastname, $nameorder=-1)
Return firstname and lastname in correct order.
setEventMessage ($mesgs, $style= 'mesgs')
Set event message in dol_events session object.
setEventMessages ($mesg, $mesgs, $style= 'mesgs', $messagekey= '')
Set event messages in dol_events session object.
dol_htmloutput_events ($disabledoutputofmessages=0)
Print formated messages to output (Used to show messages on html output).
get_htmloutput_mesg ($mesgstring= '', $mesgarray= '', $style= 'ok', $keepembedded=0)
Get formated messages to output (Used to show messages on html output).
get_htmloutput_errors ($mesgstring= '', $mesgarray=array(), $keepembedded=0)
Get formated error messages to output (Used to show messages on html output).
dol_htmloutput_mesg ($mesgstring= '', $mesgarray=array(), $style= 'ok', $keepembedded=0)
Print formated messages to output (Used to show messages on html output).
dol_htmloutput_errors ($mesgstring= '', $mesgarray=array(), $keepembedded=0)
Print formated error messages to output (Used to show messages on html output).
dol_sort_array (&$array, $index, $order= 'asc', $natsort=0, $case_sensitive=0, $keepindex=0)
Advanced sort array by second index function, which produces ascending (default) or descending output and uses optionally natural case insensitive sorting (which can be optionally case sensitive as well).
utf8_check ($str)
Check if a string is in UTF8.
dol_osencode ($str)
Return a string encoded into OS filesystem encoding.
dol_getIdFromCode ($db, $key, $tablename, $fieldkey= 'code', $fieldid= 'id', $entityfilter=0)
Return an id or code from a code or id.
verifCond ($strRights)
Verify if condition in string is ok or not.
dol_eval ($s, $returnvalue=0, $hideerrors=1)
Replace eval function to add more security.
dol_validElement ($element)
Return if var element is ok.
picto_from_langcode ($codelang, $moreatt= '')
Return img flag of country for a language code or country code.
getLanguageCodeFromCountryCode ($countrycode)
Return default language from country code.
complete_head_from_modules ($conf, $langs, $object, &$head, &$h, $type, $mode= 'add')
Complete or removed entries into a head array (used to build tabs).
printCommonFooter ($zone= 'private')
Print common footer : conf->global->MAIN_HTML_FOOTER js for switch of menu hider js for conf->global->MAIN_GOOGLE_AN_ID js for conf->global->MAIN_SHOW_TUNING_INFO or $_SERVER["MAIN_SHOW_TUNING_INFO"] js for conf->logbuffer.
dolExplodeIntoArray ($string, $delimiter= ';', $kv= '=')
Split a string with 2 keys into key array.
dol_set_focus ($selector)
Set focus onto field with selector (similar behaviour of 'autofocus' HTML5 tag)
dol_getmypid ()
Return getmypid() or random PID when function is disabled Some web hosts disable this php function for security reasons and sometimes we can't redeclare function.
natural_search ($fields, $value, $mode=0, $nofirstand=0)
Generate natural SQL search string for a criteria (this criteria can be tested on one or several fields)
showDirectDownloadLink ($object)
Return string with full Url.
getImageFileNameForSize ($file, $extName, $extImgTarget= '')
Return the filename of file to get the thumbs.
getAdvancedPreviewUrl ($modulepart, $relativepath, $alldata=0, $param= '')
Return URL we can use for advanced preview links.
ajax_autoselect ($htmlname, $addlink= '')
Make content of an input box selected when we click into input field.
dol_mimetype ($file, $default= 'application/octet-stream', $mode=0)
Return mime type of a file.
getDictvalue ($tablename, $field, $id, $checkentity=false, $rowidfield= 'rowid')
Return value from dictionary.
colorIsLight ($stringcolor)
Return true if the color is light.
isVisibleToUserType ($type_user, &$menuentry, &$listofmodulesforexternal)
Function to test if an entry is enabled or not.
roundUpToNextMultiple ($n, $x=5)
Round to next multiple.
dolGetBadge ($label, $html= '', $type= 'primary', $mode= '', $url= '', $params=array())
Function dolGetBadge.
dolGetStatus ($statusLabel= '', $statusLabelShort= '', $html= '', $statusType= 'status0', $displayMode=0, $url= '', $params=array())
Function dolGetStatus.
dolGetButtonAction ($label, $html= '', $actionType= 'default', $url= '', $id= '', $userRight=1, $params=array())
Function dolGetButtonAction.
dolGetButtonTitle ($label, $helpText= '', $iconClass= 'fa fa-file', $url= '', $id= '', $status=1, $params=array())
Function dolGetButtonTitle : this kind of buttons are used in title in list.
isAFileWithExecutableContent ($filename)
Return if a file can contains executable content.
Detailed Description
A set of functions for Dolibarr This file contains all frequently used functions.
Definition in file functions.lib.php.
Function Documentation
ajax_autoselect ($htmlname, $addlink = '')
Make content of an input box selected when we click into input field.
Parameters
string $htmlname Id of html object
string $addlink Add a 'link to' after
Returns
string
Definition at line 7751 of file functions.lib.php.
Referenced by FormFile\list_of_documents(), showPaypalPaymentUrl(), and showStripePaymentUrl().
colorIsLight ($stringcolor)
Return true if the color is light.
Parameters
string $stringcolor String with hex (FFFFFF) or comma RGB ('255,255,255')
Returns
int -1 : Error with argument passed |0 : color is dark | 1 : color is light
Definition at line 7927 of file functions.lib.php.
Referenced by Categorie\getNomUrl(), Categorie\print_all_ways(), and FormOther\showColor().
complete_head_from_modules ($conf, $langs, $object, & $head, & $h, $type, $mode = 'add')
Complete or removed entries into a head array (used to build tabs).
For example, with value added by external modules. Such values are declared into $conf->modules_parts['tab']. Or by change using hook completeTabsHead
Parameters
Conf $conf Object conf
Translate $langs Object langs
object | null $object Object object
array $head Object head
int $h New position to fill
string $type Value for object where objectvalue can be 'thirdparty' to add a tab in third party view 'intervention' to add a tab in intervention view 'supplier_order' to add a tab in supplier order view 'supplier_invoice' to add a tab in supplier invoice view 'invoice' to add a tab in customer invoice view 'order' to add a tab in customer order view 'contract' to add a tabl in contract view 'product' to add a tab in product view 'propal' to add a tab in propal view 'user' to add a tab in user view 'group' to add a tab in group view 'member' to add a tab in fundation member view 'categories_x' to add a tab in category view ('x': type of category (0=product, 1=supplier, 2=customer, 3=member) 'ecm' to add a tab for another ecm view 'stock' to add a tab for warehouse view
string $mode 'add' to complete head, 'remove' to remove entries
Returns
void
Definition at line 7145 of file functions.lib.php.
References complete_substitutions_array(), dol_buildpath(), dol_syslog(), make_substitutions(), and verifCond().
Referenced by accounting_prepare_head(), actions_prepare_head(), agenda_prepare_head(), asset_admin_prepare_head(), asset_prepare_head(), asset_type_prepare_head(), bank_admin_prepare_head(), bank_prepare_head(), blockedlogadmin_prepare_head(), bomAdminPrepareHead(), bomPrepareHead(), calendars_prepare_head(), categories_prepare_head(), categoriesadmin_prepare_head(), commande_prepare_head(), company_admin_prepare_head(), contact_prepare_head(), contract_admin_prepare_head(), contract_prepare_head(), cron_prepare_head(), cronadmin_prepare_head(), datapolicyAdminPrepareHead(), dav_admin_prepare_head(), defaultvalues_prepare_head(), delivery_prepare_head(), donation_admin_prepare_head(), donation_prepare_head(), ecm_prepare_dasboard_head(), email_admin_prepare_head(), emailcollectorPrepareHead(), emailing_prepare_head(), establishment_prepare_head(), expedition_admin_prepare_head(), expedition_prepare_head(), expensereport_admin_prepare_head(), expensereport_prepare_head(), facture_prepare_head(), facturefourn_prepare_head(), fichinter_admin_prepare_head(), fichinter_prepare_head(), fichinter_rec_prepare_head(), fiscalyear_prepare_head(), group_prepare_head(), holiday_admin_prepare_head(), holiday_prepare_head(), hrm_admin_prepare_head(), inventoryAdminPrepareHead(), invoice_admin_prepare_head(), invoice_rec_prepare_head(), ldap_prepare_head(), loan_prepare_head(), marges_admin_prepare_head(), marges_prepare_head(), member_admin_prepare_head(), member_prepare_head(), member_stats_prepare_head(), member_type_prepare_head(), multicurrencyAdminPrepareHead(), mymoduleAdminPrepareHead(), myobjectPrepareHead(), oauthadmin_prepare_head(), opensurvey_prepare_head(), order_admin_prepare_head(), ordersupplier_prepare_head(), payment_expensereport_prepare_head(), paypaladmin_prepare_head(), prelevement_prepare_head(), product_admin_prepare_head(), product_lot_admin_prepare_head(), product_prepare_head(), productlot_prepare_head(), project_admin_prepare_head(), project_prepare_head(), project_timesheet_prepare_head(), propal_admin_prepare_head(), propal_prepare_head(), reception_admin_prepare_head(), reception_prepare_head(), resource_admin_prepare_head(), resource_prepare_head(), shipping_prepare_head(), societe_admin_prepare_head(), societe_prepare_head(), stock_admin_prepare_head(), stock_prepare_head(), stripeadmin_prepare_head(), subscription_prepare_head(), supplierorder_admin_prepare_head(), takepos_prepare_head(), takeposAdminPrepareHead(), task_prepare_head(), tax_prepare_head(), ticket_prepare_head(), ticketAdminPrepareHead(), translation_prepare_head(), trip_prepare_head(), user_admin_prepare_head(), user_prepare_head(), various_payment_prepare_head(), vat_prepare_head(), and websiteaccountPrepareHead().
complete_substitutions_array (& $substitutionarray, $outputlangs, $object = null, $parameters = null, $callfunc = "completesubstitutionarray")
Complete the $substitutionarray with more entries coming from external module that had set the "substitutions=1" into module_part array.
In this case, method completesubstitutionarray provided by module is called.
Parameters
array $substitutionarray Array substitution old value => new value value
Translate $outputlangs Output language
Object $object Source object
mixed $parameters Add more parameters (useful to pass product lines)
string $callfunc What is the name of the custom function that will be called? (default: completesubstitutionarray)
Returns
void
See also
make_substitutions()
Definition at line 6237 of file functions.lib.php.
References dol_buildpath(), dol_dir_list(), dol_is_dir(), and dol_syslog().
Referenced by checkLoginPassEntity(), complete_head_from_modules(), Facture\create(), llxFooterVierge(), Adherent\makeSubstitution(), pdf_pagefoot(), pdf_watermark(), Adherent\sendReminderForExpiredSubscription(), pdf_timespent\write_file(), pdf_beluga\write_file(), pdf_soleil\write_file(), pdf_baleine\write_file(), pdf_cornas\write_file(), doc_generic_odt\write_file(), pdf_cyan\write_file(), pdf_eratosthene\write_file(), pdf_stdmovement\write_file(), doc_generic_contract_odt\write_file(), doc_generic_reception_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_order_odt\write_file(), doc_generic_shipment_odt\write_file(), pdf_sponge\write_file(), pdf_aurore\write_file(), pdf_standard\write_file(), doc_generic_user_odt\write_file(), pdf_azur\write_file(), pdf_einstein\write_file(), doc_generic_stock_odt\write_file(), doc_generic_product_odt\write_file(), doc_generic_usergroup_odt\write_file(), doc_generic_proposal_odt\write_file(), pdf_crabe\write_file(), doc_generic_supplier_proposal_odt\write_file(), doc_generic_task_odt\write_file(), and doc_generic_project_odt\write_file().
dol_banner_tab ($object, $paramid, $morehtml = '', $shownav = 1, $fieldid = 'rowid', $fieldref = 'ref', $morehtmlref = '', $moreparam = '', $nodbprefix = 0, $morehtmlleft = '', $morehtmlstatus = '', $onlybanner = 0, $morehtmlright = '')
Show tab footer of a card.
Note: $object->next_prev_filter can be set to restrict select to find next or previous record by $form->showrefnav.
Parameters
Object $object Object to show
string $paramid Name of parameter to use to name the id into the URL next/previous link
string $morehtml More html content to output just before the nav bar
int $shownav Show Condition (navigation is shown if value is 1)
string $fieldid Nom du champ en base a utiliser pour select next et previous (we make the select max and min on this field). Use 'none' for no prev/next search.
string $fieldref Nom du champ objet ref (object->ref) a utiliser pour select next et previous
string $morehtmlref More html to show after ref
string $moreparam More param to add in nav link url.
int $nodbprefix Do not include DB prefix to forge table name
string $morehtmlleft More html code to show before ref
string $morehtmlstatus More html code to show under navigation arrows
int $onlybanner Put this to 1, if the card will contains only a banner (this add css 'arearefnobottom' on div)
string $morehtmlright More html code to show before navigation arrows
Returns
void
Definition at line 1309 of file functions.lib.php.
References ajax_object_onoff(), dol_convert_file(), dol_sanitizeFileName(), get_exdir(), if, img_picto(), and print.
dol_bc ($var, $moreclass = '')
Return string to add class property on html element with pair/impair.
Parameters
string $var 0 or 1
string $moreclass More class to add
Returns
string String to add class onto HTML element
Definition at line 1604 of file functions.lib.php.
dol_buildpath ($path, $type = 0, $returnemptyifnotfound = 0)
Return path of url or filesystem.
Can check into alternate dir or alternate dir + main dir depending on value of $returnemptyifnotfound.
Parameters
string $path Relative path to file (if mode=0) or relative url (if mode=1). Ie: mydir/myfile, ../myfile
int $type 0=Used for a Filesystem path, 1=Used for an URL path (output relative), 2=Used for an URL path (output full path using same host that current url), 3=Used for an URL path (output full path using host defined into $dolibarr_main_url_root of conf file)
int $returnemptyifnotfound 0:If $type==0 and if file was not found into alternate dir, return default path into main dir (no test on it) 1:If $type==0 and if file was not found into alternate dir, return empty string 2:If $type==0 and if file was not found into alternate dir, test into main dir, return default path if found, empty string if not found
Returns
string Full filesystem path (if path=0) or '' if file not found, Full url path (if mode=1)
Definition at line 674 of file functions.lib.php.
Referenced by ajouter_sondage(), analyseVarsForSqlAndScriptsInjection(), checkLoginPassEntity(), complete_head_from_modules(), complete_substitutions_array(), Project\createFromClone(), cron_prepare_head(), cronadmin_prepare_head(), FormMargin\displayMarginInfos(), doc_label_pdf_create(), EmailCollector\doCollectOneCollector(), dol_include_once(), dol_print_address(), emailcollectorPrepareHead(), fichinter_create(), Utils\generateDoc(), Don\generateDocument(), DolibarrCollector\getAssets(), Canvas\getCanvas(), DolibarrModules\getChangeLog(), Ticket\getDefaultRef(), DolibarrModules\getDescLong(), DolibarrModules\getDescLongReadmeFound(), Translate\getLabelFromNumber(), Reception\getNextNumRef(), Holiday\getNextNumRef(), Contrat\getNextNumRef(), Expedition\getNextNumRef(), Commande\getNextNumRef(), RemiseCheque\getNextNumRef(), BOM\getNextNumRef(), PaiementFourn\getNextNumRef(), CommandeFournisseur\getNextNumRef(), Fichinter\getNextNumRef(), Paiement\getNextNumRef(), ExpenseReport\getNextNumRef(), FactureFournisseur\getNextNumRef(), SupplierProposal\getNextNumRef(), Facture\getNextNumRef(), Propal\getNextNumRef(), EmailCollectorFilter\getNomUrl(), Asset\getNomUrl(), EmailCollectorAction\getNomUrl(), Inventory\getNomUrl(), CompanyPaymentMode\getNomUrl(), SocieteAccount\getNomUrl(), EmailCollector\getNomUrl(), MyObject\getNomUrl(), BOM\getNomUrl(), Project\getNomUrl(), ProductFournisseur\getNomUrl(), BOMLine\getNomUrl(), Ticket\getNomUrl(), Interfaces\getTriggersList(), ModeleBoxes\getWidgetsList(), inventoryPrepareHead(), ModeleAction\liste_modeles(), llxFooter(), llxHeaderTicket(), box_last_ticket\loadBox(), box_last_modified_ticket\loadBox(), members_card_pdf_create(), multicurrencyAdminPrepareHead(), mymoduleAdminPrepareHead(), myobjectPrepareHead(), Ticket\newMessage(), oauthadmin_prepare_head(), print_auguria_menu(), print_eldy_menu(), print_left_auguria_menu(), print_left_eldy_menu(), resource_prepare_head(), Interfaces\run_triggers(), InterfaceTicketEmail\runTrigger(), FormCompany\selectCompaniesForNewContact(), Ticket\sendLogByEmail(), DataPolicy\sendMailDataPolicyAdherent(), DataPolicy\sendMailDataPolicyCompany(), DataPolicy\sendMailDataPolicyContact(), Conf\setValues(), show_skin(), FormFile\showdocuments(), FormTicket\showForm(), Form\showLinkedObjectBlock(), MenuManager\showmenu(), showSkins(), takeposAdminPrepareHead(), ticket_prepare_head(), top_htmlhead(), and websiteaccountPrepareHead().
dol_clone ($object, $native = 0)
Create a clone of instance of object (new instance with same value for properties) With native = 0: Property that are reference are also new object (full isolation clone).
This means $this->db of new object is not valid. With native = 1: Use PHP clone. Property that are reference are same pointer. This means $this->db of new object is still valid but point to same this->db than original object.
Parameters
object $object Object to clone
int $native Native method or full isolation method
Returns
object Clone object
See also
https://php.net/manual/language.oop5.cloning.php
Definition at line 775 of file functions.lib.php.
Referenced by Ticket\assignUser(), and Products\put().
dol_concatdesc ($text1, $text2, $forxml = false, $invert = false)
Concat 2 descriptions with a new line between them (second operand after first one with appropriate new line separator) text1 html + text2 html => text1 + '
' + text2 text1 html + text2 txt => text1 + '
' + dol_nl2br(text2) text1 txt + text2 html => dol_nl2br(text1) + '
' + text2 text1 txt + text2 txt => text1 + '
' + text2.
Parameters
string $text1 Text 1
string $text2 Text 2
bool $forxml false=Use
instead of
if html content detected, true=Use
instead of
if html content detected
bool $invert invert order of description lines (we often use config MAIN_CHANGE_ORDER_CONCAT_DESCRIPTION in this parameter)
Returns
string Text 1 + new line + Text2
See also
dol_textishtml()
Definition at line 5807 of file functions.lib.php.
References dol_nl2br(), and dol_textishtml().
Referenced by Propal\cloture(), constructGanttLine(), Facture\create(), doc_getlinedesc(), EmailCollector\doCollectOneCollector(), llxFooterVierge(), Thirdparties\merge(), InterfaceActionsAuto\runTrigger(), DataPolicy\sendMailDataPolicyAdherent(), DataPolicy\sendMailDataPolicyCompany(), DataPolicy\sendMailDataPolicyContact(), Adherent\sendReminderForExpiredSubscription(), pdf_soleil\write_file(), pdf_strato\write_file(), pdf_cyan\write_file(), pdf_eratosthene\write_file(), pdf_sponge\write_file(), pdf_aurore\write_file(), pdf_standard\write_file(), pdf_azur\write_file(), pdf_einstein\write_file(), and pdf_crabe\write_file().
dol_escape_htmltag ($stringtoescape, $keepb = 0, $keepn = 0)
Returns text escaped for inclusion in HTML alt or title tags, or into values of HTML input fields.
Parameters
string $stringtoescape String to escape
int $keepb 1=Preserve b tags (otherwise, remove them)
int $keepn 1=Preserve
strings (otherwise, replace them with escaped value). Set to 1 when escaping for a <textarea>.
Returns
string Escaped string
See also
dol_string_nohtmltag(), dol_string_nospecial(), dol_string_unaccent()
Definition at line 948 of file functions.lib.php.
Referenced by ActionsStripeconnect\addMoreActionsButtons(), DolEditor\Create(), EmailCollector\doCollectOneCollector(), dol_print_error(), DolGraph\draw_artichow(), DolGraph\draw_jflot(), form_constantes(), Form\formconfirm(), mailing_contacts1\formFilter(), Dolistore\get_categories(), Subscription\getNomUrl(), Deplacement\getNomUrl(), AssetType\getNomUrl(), AdherentType\getNomUrl(), Loan\getNomUrl(), EcmDirectory\getNomUrl(), PaiementFourn\getNomUrl(), Localtax\getNomUrl(), PaymentDonation\getNomUrl(), PaymentExpenseReport\getNomUrl(), DiscountAbsolute\getNomUrl(), PaymentSocialContribution\getNomUrl(), Livraison\getNomUrl(), Don\getNomUrl(), Dolresource\getNomUrl(), Reception\getNomUrl(), Contact\getNomUrl(), Holiday\getNomUrl(), Facture\getNomUrl(), FactureRec\getNomUrl(), Categorie\getNomUrl(), Expedition\getNomUrl(), AccountLine\getNomUrl(), ContratLigne\getNomUrl(), img_help(), img_picto(), img_search(), img_searchclear(), info_admin(), left_menu(), FormFile\list_of_documents(), FormFile\listOfLinks(), llxFooterVierge(), Form\multiSelectArrayWithCheckbox(), print_fleche_navigation(), print_text_menu_entry(), print_text_menu_entry_auguria(), print_text_menu_entry_empty(), printBookmarksList(), Form\select_dolusers_forevent(), FormEcm\selectAllSections(), Form\selectMassAction(), Adherent\sendReminderForExpiredSubscription(), show_contacts(), CommonObject\show_photos(), ModeleBoxes\showBox(), ExtraFields\showInputField(), FormTicket\showMessageForm(), Form\textwithtooltip(), top_menu(), and treeOutputForAbsoluteDir().
dol_escape_js ($stringtoescape, $mode = 0, $noescapebackslashn = 0)
Returns text escaped for inclusion into javascript code.
Parameters
string $stringtoescape String to escape
int $mode 0=Escape also ' and " into ', 1=Escape ' but not " for usage into 'string', 2=Escape " but not ' for usage into "string", 3=Escape ' and " with \
int $noescapebackslashn 0=Escape also
. 1=Do not escape
.
Returns
string Escaped string. Both ' and " are escaped into ' if they are escaped.
Definition at line 925 of file functions.lib.php.
Referenced by ActionsCardCompany\assign_values(), constructGanttLine(), DolGraph\draw_jflot(), FormFile\form_attach_new_file(), Form\formconfirm(), get_htmloutput_mesg(), price2numjs(), FormOther\selectColor(), and FormFile\showdocuments().
dol_eval ($s, $returnvalue = 0, $hideerrors = 1)
Replace eval function to add more security.
This function is called by verifCond() or trans() and transnoentitiesnoconv().
Parameters
string $s String to evaluate
int $returnvalue 0=No return (used to execute eval($a=something)). 1=Value of eval is returned (used to eval($something)).
int $hideerrors 1=Hide errors
Returns
mixed Nothing or return of eval
Definition at line 6825 of file functions.lib.php.
Referenced by Export\build_file(), InterfaceTicketEmail\runTrigger(), ExtraFields\setOptionalsFromPost(), ExtraFields\showInputField(), ExtraFields\showOutputField(), Translate\transnoentitiesnoconv(), and verifCond().
dol_fiche_end ($notab = 0)
Show tab footer of a card.
Parameters
int $notab -1 or 0=Add tab footer, 1=no tab footer
Returns
void
Definition at line 1273 of file functions.lib.php.
References dol_get_fiche_end(), and print.
Referenced by journalHead(), llxFooterVierge(), report_header(), and FormTicket\showForm().
dol_fiche_head ($links = array(), $active = '0', $title = '', $notab = 0, $picto = '', $pictoisfullpath = 0, $morehtmlright = '', $morecss = '')
Show tab header of a card.
Parameters
array $links Array of tabs. Currently initialized by calling a function xxx_admin_prepare_head
string $active Active tab name (document', 'info', 'ldap', ....)
string $title Title
int $notab -1 or 0=Add tab header, 1=no tab header (if you set this to 1, using dol_fiche_end() to close tab is not required), -2=Add tab header with no seaparation under tab (to start a tab just after)
string $picto Add a picto on tab title
int $pictoisfullpath If 1, image path is a full path. If you set this to 1, you can use url returned by dol_buildpath('/mymodyle/img/myimg.png',1) for $picto.
string $morehtmlright Add more html content on right of tabs title
string $morecss More Css
Returns
void
Definition at line 1095 of file functions.lib.php.
References dol_get_fiche_head(), and print.
Referenced by journalHead(), llxFooterVierge(), report_header(), and FormTicket\showForm().
dol_format_address ($object, $withcountry = 0, $sep = "\n", $outputlangs = '', $mode = 0)
Return a formated address (part address/zip/town/state) according to country rules.
Parameters
Object $object A company or contact object
int $withcountry 1=Add country into address string
string $sep Separator to use to build string
Translate $outputlangs Object lang that contains language for text translation.
int $mode 0=Standard output, 1=Remove address
Returns
string Formated string
See also
dol_print_address()
Definition at line 1623 of file functions.lib.php.
References if.
Referenced by CommonObject\getFullAddress(), and pdf_build_address().
dol_get_fiche_end ($notab = 0)
Return tab footer of a card.
Parameters
int $notab -1 or 0=Add tab footer, 1=no tab footer
Returns
string
Definition at line 1284 of file functions.lib.php.
Referenced by ActionsCardService\assign_values(), ActionsCardProduct\assign_values(), ActionsContactCardDefault\assign_values(), ActionsAdherentCardDefault\assign_values(), ActionsCardCommon\assign_values(), and dol_fiche_end().
dol_get_fiche_head ($links = array(), $active = '', $title = '', $notab = 0, $picto = '', $pictoisfullpath = 0, $morehtmlright = '', $morecss = '')
Show tab header of a card.
Parameters
array $links Array of tabs
string $active Active tab name
string $title Title
int $notab -1 or 0=Add tab header, 1=no tab header (if you set this to 1, using dol_fiche_end() to close tab is not required), -2=Add tab header with no seaparation under tab (to start a tab just after)
string $picto Add a picto on tab title
int $pictoisfullpath If 1, image path is a full path. If you set this to 1, you can use url returned by dol_buildpath('/mymodyle/img/myimg.png',1) for $picto.
string $morehtmlright Add more html content on right of tabs title
string $morecss More Css
Returns
string
Definition at line 1113 of file functions.lib.php.
References img_picto().
Referenced by ActionsCardService\assign_values(), ActionsCardProduct\assign_values(), ActionsContactCardDefault\assign_values(), ActionsAdherentCardDefault\assign_values(), ActionsCardCommon\assign_values(), and dol_fiche_head().
dol_getdate ($timestamp, $fast = false)
Return an array with locale date info.
PHP getdate is restricted to the years 1901-2038 on Unix and 1970-2038 on Windows WARNING: This function always use PHP server timezone to return locale informations !!! Usage must be avoid. FIXME: Replace this with PHP date function and a parameter $gm
Parameters
int $timestamp Timestamp
boolean $fast Fast mode
Returns
array Array of informations If no fast mode: 'seconds' => $secs, 'minutes' => $min, 'hours' => $hour, 'mday' => $day, 'wday' => $dow, 0=sunday, 6=saturday 'mon' => $month, 'year' => $year, 'yday' => floor($secsInYear/$_day_power), 'weekday' => gmdate('l',$_day_power*(3+$dow)), 'month' => gmdate('F',mktime(0,0,0,$month,2,1971)), If fast mode: 'seconds' => $secs, 'minutes' => $min, 'hours' => $hour, 'mday' => $day, 'mon' => $month, 'year' => $year, 'yday' => floor($secsInYear/$_day_power), 'leap' => $leaf, 'ndays' => $ndays
See also
dol_print_date(), dol_stringtotime(), dol_mktime()
Definition at line 1908 of file functions.lib.php.
Referenced by modFacture\__construct(), modAdherent\__construct(), MouvementStock\_create(), FactureRec\createRecurringInvoices(), displayBox(), dol_get_first_day_week(), dol_get_next_day(), dol_get_next_week(), dol_get_prev_day(), dol_get_prev_week(), getCommonSubstitutionArray(), GETPOST(), PaiementFourn\initAsSpecimen(), RemiseCheque\initAsSpecimen(), Paiement\initAsSpecimen(), FactureRec\initAsSpecimen(), Facture\initAsSpecimen(), box_graph_invoices_permonth\loadBox(), box_graph_orders_supplier_permonth\loadBox(), box_graph_orders_permonth\loadBox(), box_graph_propales_permonth\loadBox(), box_graph_invoices_supplier_permonth\loadBox(), box_graph_product_distribution\loadBox(), projectLinesPerDay(), projectLinesPerWeek(), pt(), Adherent\sendReminderForExpiredSubscription(), show_actions_done(), and FormActions\showactions().
dol_getIdFromCode ($db, $key, $tablename, $fieldkey = 'code', $fieldid = 'id', $entityfilter = 0)
Return an id or code from a code or id.
Store also Code-Id into a cache to speed up next request on same key.
Parameters
DoliDB $db Database handler
string $key Code or Id to get Id or Code
string $tablename Table name without prefix
string $fieldkey Field to search the key into
string $fieldid Field to get
int $entityfilter Filter by entity
Returns
int <0 if KO, Id of code if OK
See also
$langs->getLabelFromKey
Definition at line 6758 of file functions.lib.php.
References $resql, dol_syslog(), and getEntity().
Referenced by SupplierInvoices\addPayment(), Invoices\addPayment(), Invoices\addPaymentDistributed(), Facture\demande_prelevement(), EmailCollector\doCollectOneCollector(), print_projecttasks_array(), RemiseCheque\rejectCheck(), Notify\send(), BlockedLog\setObjectData(), and Adherent\subscriptionComplementaryActions().
dol_getmypid ()
Return getmypid() or random PID when function is disabled Some web hosts disable this php function for security reasons and sometimes we can't redeclare function.
Returns
int
Definition at line 7480 of file functions.lib.php.
dol_html_entity_decode ($a, $b, $c = 'UTF-8')
Replace html_entity_decode functions to manage errors.
Parameters
string $a Operand a
string $b Operand b (ENT_QUOTES=convert simple and double quotes)
string $c Operand c
Returns
string String decoded
Definition at line 5640 of file functions.lib.php.
Referenced by Project\createFromClone(), Task\createFromClone(), dol_htmlentitiesbr_decode(), dol_string_nohtmltag(), Mailing\fetch(), jsUnEscape(), pdf_getlinedesc(), and Ticket\sendLogByEmail().
dol_htmlcleanlastbr ($stringtodecode)
This function remove all ending
and br at end.
Parameters
string $stringtodecode String to decode
Returns
string String decoded
Definition at line 5626 of file functions.lib.php.
Referenced by checkLoginPassEntity(), ActionComm\create(), ExportCsv\csvClean(), getInvoice(), and getSupplierInvoicesForThirdParty().
dol_htmlentities ($string, $flags = null, $encoding = 'UTF-8', $double_encode = false)
Replace htmlentities functions.
Goal of this function is to be sure to have default values of htmlentities that match what we need.
Parameters
string $string The input string to encode
int $flags Flags (see PHP doc above)
string $encoding Encoding page code
bool $double_encode When double_encode is turned off, PHP will not encode existing html entities
Returns
string $ret Encoded string
Definition at line 5655 of file functions.lib.php.
Referenced by dol_htmlentitiesbr(), dol_print_error(), FormMail\get_form(), getTaskProgressView(), box_task\loadBox(), run_sql(), Form\showrefnav(), and top_htmlhead().
dol_htmlentitiesbr ($stringtoencode, $nl2brmode = 0, $pagecodefrom = 'UTF-8', $removelasteolbr = 1)
This function is called to encode a string into a HTML string but differs from htmlentities because a detection is done before to see if text is already HTML or not.
Also, all entities but &,<,> are converted. This permits to encode special chars to entities with no double encoding for already encoded HTML strings. This function also remove last EOL or BR if $removelasteolbr=1 (default). For PDF usage, you can show text by 2 ways:
writeHTMLCell -> param must be encoded into HTML.
MultiCell -> param must not be encoded into HTML. Because writeHTMLCell convert also
into
, if function is used to build PDF, nl2brmode must be 1.
Parameters
string $stringtoencode String to encode
int $nl2brmode 0=Adding br before
, 1=Replacing
by br (for use with FPDF writeHTMLCell function for example)
string $pagecodefrom Pagecode stringtoencode is encoded
int $removelasteolbr 1=Remove last br or lasts
(default), 0=Do nothing
Returns
string String encoded
Definition at line 5582 of file functions.lib.php.
References dol_htmlentities(), dol_nl2br(), and dol_textishtml().
Referenced by DolEditor\__construct(), Form\editfieldval(), getCommonSubstitutionArray(), box_services_contracts\loadBox(), make_substitutions(), Adherent\makeSubstitution(), pdf_getlinedesc(), pdf_getlinenum(), pdf_getlineref(), pdf_getlineref_supplier(), pdf_pagefoot(), Adherent\send_an_email(), show_ldap_content(), show_list_sending_receive(), ExtraFields\showOutputField(), pdf_ban\write_file(), pdf_sepamandate\write_file(), pdf_timespent\write_file(), pdf_squille\write_file(), pdf_beluga\write_file(), pdf_espadon\write_file(), pdf_merou\write_file(), pdf_soleil\write_file(), pdf_strato\write_file(), pdf_baleine\write_file(), pdf_cornas\write_file(), pdf_rouget\write_file(), pdf_typhon\write_file(), pdf_cyan\write_file(), pdf_eratosthene\write_file(), pdf_stdmovement\write_file(), pdf_canelle\write_file(), pdf_aurore\write_file(), pdf_sponge\write_file(), pdf_standard\write_file(), pdf_muscadet\write_file(), pdf_azur\write_file(), pdf_einstein\write_file(), and pdf_crabe\write_file().
dol_htmlentitiesbr_decode ($stringtodecode, $pagecodeto = 'UTF-8')
This function is called to decode a HTML string (it decodes entities and br tags)
Parameters
string $stringtodecode String to decode
string $pagecodeto Page code for result
Returns
string String decoded
Definition at line 5610 of file functions.lib.php.
References dol_html_entity_decode().
Referenced by CommActionRapport\_pages(), AdherentType\getMailOnResiliate(), AdherentType\getMailOnSubscription(), and AdherentType\getMailOnValid().
dol_htmloutput_errors ($mesgstring = '', $mesgarray = array(), $keepembedded = 0)
Print formated error messages to output (Used to show messages on html output).
Parameters
string $mesgstring Error message
array $mesgarray Error messages array
int $keepembedded Set to 1 in error message must be kept embedded into its html place (this disable jnotify)
Returns
void
See also
dol_print_error()
dol_htmloutput_mesg()
Definition at line 6634 of file functions.lib.php.
References dol_htmloutput_mesg().
Referenced by llxFooterVierge().
dol_htmloutput_events ($disabledoutputofmessages = 0)
Print formated messages to output (Used to show messages on html output).
Note: Calling dol_htmloutput_events is done into pages by standard llxFooter() function, so there is no need to call it explicitely.
Parameters
int $disabledoutputofmessages Clear all messages stored into session without diplaying them
Returns
void
See also
dol_htmloutput_mesg()
Definition at line 6444 of file functions.lib.php.
References dol_htmloutput_mesg().
Referenced by llxFooterSurvey().
dol_htmloutput_mesg ($mesgstring = '', $mesgarray = array(), $style = 'ok', $keepembedded = 0)
Print formated messages to output (Used to show messages on html output).
Parameters
string $mesgstring Message string or message key
string[] $mesgarray Array of message strings or message keys
string $style Which style to use ('ok', 'warning', 'error')
int $keepembedded Set to 1 if message must be kept embedded into its html place (this disable jnotify)
Returns
void
See also
dol_print_error()
dol_htmloutput_errors()
setEventMessages()
Definition at line 6573 of file functions.lib.php.
References dol_syslog(), get_htmloutput_mesg(), and print.
Referenced by dol_htmloutput_errors(), dol_htmloutput_events(), and ActionsStripeconnect\formObjectOptions().
if (!function_exists('dol_getprefix')) dol_include_once ($relpath, $classname = '')
Make an include_once using default root and alternate root if it fails.
To link to a core file, use include(DOL_DOCUMENT_ROOT.'/pathtofile') To link to a module file from a module file, use include './mymodulefile'; To link to a module file from a core file, then this function can be used (call by hook / trigger / speciales pages)
Parameters
string $relpath Relative path to file (Ie: mydir/myfile, ../myfile, ...)
string $classname Class name (deprecated)
Returns
bool True if load is a success, False if it fails
Definition at line 645 of file functions.lib.php.
References dol_buildpath(), and dol_syslog().
Referenced by FileUpload\__construct(), analyseVarsForSqlAndScriptsInjection(), ActionsCardCommon\assign_values(), Product\check_barcode(), Societe\check_codeclient(), Societe\check_codefournisseur(), Societe\codeclient_modifiable(), Societe\codefournisseur_modifiable(), Utils\compressSyslogs(), Product\create(), Contrat\create(), Propal\createFromClone(), Project\createFromClone(), Contrat\createFromClone(), Commande\createFromProposal(), EmailCollector\doCollectOneCollector(), dolGetElementUrl(), Reception\fetch_lines(), CommonDocGenerator\fill_substitutionarray_with_extrafields(), Form\form_multicurrency_code(), Utils\generateDoc(), Product\get_barcode(), Societe\get_codeclient(), Societe\get_codecompta(), Societe\get_codefournisseur(), MouvementStock\get_origin(), CommonDocGenerator\get_substitutionarray_shipment(), CommonDocGenerator\get_substitutionarray_shipment_lines(), Ticket\getDefaultRef(), ImportCsv\import_insert(), ImportXlsx\import_insert(), HookManager\initHooks(), InfoBox\listBoxes(), box_last_ticket\loadBox(), box_last_modified_ticket\loadBox(), migrate_reload_modules(), AdvanceTargetingMailing\query_contact(), AdvanceTargetingMailing\query_thirdparty(), Cronjob\run_jobs(), CSMSFile\sendfile(), Conf\setValues(), show_actions_done(), FormSms\show_form(), FormTicket\showForm(), and ExtraFields\showOutputField().
dol_microtime_float ()
Same function than microtime in PHP 5 but compatible with PHP4.
Returns
float Time (millisecondes) with microsecondes in decimal part
Deprecated:
Dolibarr does not support PHP4, you should use native function
See also
microtime()
Definition at line 5750 of file functions.lib.php.
References dol_syslog().
dol_mimetype ($file, $default = 'application/octet-stream', $mode = 0)
Return mime type of a file.
Parameters
string $file Filename we looking for MIME type
string $default Default mime type if extension not found in known list
int $mode 0=Return full mime, 1=otherwise short mime string, 2=image for mime type, 3=source language, 4=css of font fa
Returns
string Return a mime type family (text/xxx, application/xxx, image/xxx, audio, video, archive)
See also
image_format_supported() from images.lib.php
Definition at line 7773 of file functions.lib.php.
Referenced by FormMail\add_attached_files(), Documents\builddoc(), dol_check_secure_access_document(), dol_init_file_process(), FormMail\get_form(), getDocument(), FormFile\getDocumentsLink(), FileUpload\getFileObject(), FileUpload\handleFileUpload(), img_mime(), Documents\index(), llxFooter(), Ticket\messageSend(), printing_printgcp\printFile(), FormFile\showdocuments(), FormTicket\showMessageForm(), pdf_standardlabel\write_file(), pdf_standard\write_file(), and pdf_tcpdflabel\write_file().
dol_mkdir ($dir, $dataroot = '', $newmask = null)
Creation of a directory (this can create recursive subdir)
Parameters
string $dir Directory to create (Separator must be '/'. Example: '/mydir/mysubdir')
string $dataroot Data root directory (To avoid having the data root in the loop. Using this will also lost the warning on first dir PHP has no permission when open_basedir is used)
string | null $newmask Mask for new file (Defaults to $conf->global->MAIN_UMASK or 0755 if unavailable). Example: '0444'
Returns
int < 0 if KO, 0 = already exists, > 0 if OK
Definition at line 5320 of file functions.lib.php.
References dol_osencode(), and dol_syslog().
Referenced by Categorie\add_photo(), Product\add_photo(), mailing_xinputfile\add_to_target(), ActionComm\build_exportfile(), Export\build_file(), Ticket\copyFilesForTicket(), EcmDirectory\create(), BonPrelevement\Create(), DolibarrModules\create_dirs(), Website\createFromClone(), Project\createFromClone(), Task\createFromClone(), FileUpload\createScaledImage(), dol_add_file_process(), dol_filecache(), dol_meta_create(), dolCopyDir(), dolSaveCssFile(), dolSaveHtaccessFile(), dolSaveHtmlHeader(), dolSaveIndexPage(), dolSaveJsFile(), dolSaveManifestJson(), dolSaveReadme(), dolSaveRobotFile(), Ldap\dump(), Utils\dumpDatabase(), Website\exportWebSite(), Utils\generateDoc(), Stats\getAllByProductEntry(), getAllImages(), Stats\getAmountByMonthWithPrevYear(), Stats\getNbByMonthWithPrevYear(), ProjectStats\getTransformRateByMonthWithPrevYear(), ProjectStats\getWeightedAmountByMonthWithPrevYear(), FileUpload\handleFileUpload(), Website\importWebSite(), modWebsite\init(), modSupplierProposal\init(), modContrat\init(), modReception\init(), modPropale\init(), modCommande\init(), modProjet\init(), modExpedition\init(), modStock\init(), modFacture\init(), modSociete\init(), migrate_user_photospath(), RssParser\parser(), pdf_getInstance(), Utils\purgeFiles(), rebuild_merge_pdf(), Cronjob\run_jobs(), InterfaceActionsAuto\runTrigger(), vignette(), html_cerfafr\write_file(), BordereauChequeBlochet\write_file(), pdf_paiement\write_file(), pdf_ban\write_file(), pdf_sepamandate\write_file(), pdf_timespent\write_file(), CommActionRapport\write_file(), pdf_squille\write_file(), pdf_beluga\write_file(), pdf_merou\write_file(), pdf_espadon\write_file(), pdf_soleil\write_file(), pdf_strato\write_file(), pdf_baleine\write_file(), pdf_cornas\write_file(), pdf_rouget\write_file(), doc_generic_odt\write_file(), pdf_typhon\write_file(), pdf_cyan\write_file(), pdf_eratosthene\write_file(), pdf_stdmovement\write_file(), doc_generic_contract_odt\write_file(), pdf_canelle\write_file(), doc_generic_reception_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_order_odt\write_file(), doc_generic_shipment_odt\write_file(), pdf_sponge\write_file(), pdf_aurore\write_file(), pdf_standard\write_file(), pdf_muscadet\write_file(), doc_generic_user_odt\write_file(), pdf_azur\write_file(), pdf_einstein\write_file(), doc_generic_product_odt\write_file(), doc_generic_stock_odt\write_file(), doc_generic_usergroup_odt\write_file(), doc_generic_proposal_odt\write_file(), pdf_crabe\write_file(), doc_generic_supplier_proposal_odt\write_file(), pdf_standardlabel\write_file(), pdf_tcpdflabel\write_file(), doc_generic_task_odt\write_file(), doc_generic_project_odt\write_file(), modTcpdfbarcode\writeBarCode(), and modPhpbarcode\writeBarCode().
dol_mktime ($hour, $minute, $second, $month, $day, $year, $gm = false, $check = 1)
Return a timestamp date built from detailed informations (by default a local PHP server timestamp) Replace function mktime not available under Windows if year < 1970 PHP mktime is restricted to the years 1901-2038 on Unix and 1970-2038 on Windows.
Parameters
int $hour Hour (can be -1 for undefined)
int $minute Minute (can be -1 for undefined)
int $second Second (can be -1 for undefined)
int $month Month (1 to 12)
int $day Day (1 to 31)
int $year Year
mixed $gm True or 1 or 'gmt'=Input informations are GMT values False or 0 or 'server' = local to server TZ 'user' = local to user TZ 'tz,TimeZone' = use specified timezone
int $check 0=No check on parameters (Can use day 32, etc...)
Returns
int|string Date as a timestamp, '' or false if error
See also
dol_print_date(), dol_stringtotime(), dol_getdate()
Definition at line 1947 of file functions.lib.php.
References dol_print_error(), and dol_syslog().
Referenced by modFacture\__construct(), modAdherent\__construct(), MouvementStock\_create(), Product\_get_stats(), pdf_paiement\_pagehead(), mailing_fraise\add_to_target(), CommonInvoice\calculate_date_lim_reglement(), Project\createFromClone(), Task\createFromClone(), FactureRec\createRecurringInvoices(), displayBox(), dol_get_first_day(), dol_get_first_day_week(), dol_get_last_day(), dol_get_next_day(), dol_get_next_week(), dol_get_prev_day(), dol_get_prev_week(), dol_print_date(), dol_stringtotime(), dolSqlDateFilter(), get_next_value(), ExtraFields\getOptionalsFromPost(), ICal\ical_date_to_unix(), PaiementFourn\initAsSpecimen(), RemiseCheque\initAsSpecimen(), Paiement\initAsSpecimen(), FactureRec\initAsSpecimen(), Facture\initAsSpecimen(), DoliDB\jdate(), llxFooterVierge(), pt(), Adherent\sendReminderForExpiredSubscription(), ExtraFields\setOptionalsFromPost(), and xyzToUnixTimestamp().
dol_nboflines ($s, $maxchar = 0)
Return nb of lines of a clear text.
Parameters
string $s String to check
int $maxchar Not yet used
Returns
int Number of lines
See also
dol_nboflines_bis(), dolGetFirstLineOfText()
Definition at line 5691 of file functions.lib.php.
Referenced by CommActionRapport\_pages().
dol_nboflines_bis ($text, $maxlinesize = 0, $charset = 'UTF-8')
Return nb of lines of a formated text with
and
(WARNING: string must not have mixed
and br separators)
Parameters
string $text Text
int $maxlinesize Largeur de ligne en caracteres (ou 0 si pas de limite - defaut)
string $charset Give the charset used to encode the $text variable in memory.
Returns
int Number of lines
See also
dol_nboflines(), dolGetFirstLineOfText()
Definition at line 5710 of file functions.lib.php.
References dol_strlen(), and dol_textishtml().
Referenced by pdf_aurore\_pagehead().
dol_nl2br ($stringtoencode, $nl2brmode = 0, $forxml = false)
Replace CRLF in string with a HTML BR tag.
Parameters
string $stringtoencode String to encode
int $nl2brmode 0=Adding br before
, 1=Replacing
by br
bool $forxml false=Use
, true=Use
Returns
string String encoded
See also
dol_nboflines(), dolGetFirstLineOfText()
Definition at line 5554 of file functions.lib.php.
Referenced by ActionsCardCommon\assign_values(), ActionsAdherentCardCommon\assign_values(), ActionsContactCardCommon\assign_values(), dol_concatdesc(), dol_htmlentitiesbr(), Form\editInPlace(), FormMail\get_form(), Ticket\messageSend(), InterfaceTicketEmail\runTrigger(), Ticket\sendLogByEmail(), Ticket\sendTicketMessageByEmail(), FormTicket\showMessageForm(), and ActionsTicket\viewTicketOriginalMessage().
dol_now ($mode = 'gmt')
Return date for now.
In most cases, we use this function without parameters (that means GMT time).
Parameters
string $mode 'gmt' => we return GMT timestamp, 'tzserver' => we add the PHP server timezone 'tzref' => we add the company timezone 'tzuser' => we add the user timezone
Returns
int $date Timestamp
Definition at line 2030 of file functions.lib.php.
References getServerTimeZoneInt().
Referenced by modAccounting\__construct(), modUser\__construct(), modFacture\__construct(), modSociete\__construct(), modAdherent\__construct(), modProduct\__construct(), modAgenda\__construct(), MouvementStock\_create(), Product\_log_price(), pdf_ban\_pagehead(), Contrat\activateAll(), Product\add_fournisseur(), mailing_thirdparties_services_expired\add_to_target(), mailing_fraise\add_to_target(), Account\addline(), Holiday\addLogCP(), BonPrelevement\AddNotification(), Tva\addPayment(), analyseVarsForSqlAndScriptsInjection(), CommandeFournisseur\approve(), build_calfile(), ActionComm\build_exportfile(), CommandeFournisseur\calcAndSetStatusDispatch(), Product\clone_fournisseurs(), Ticket\close(), Contrat\closeAll(), Commande\cloture(), SupplierProposal\cloture(), Propal\cloture(), Link\create(), Propalmergepdfproduct\create(), UserBankAccount\create(), CompanyBankAccount\create(), RejetPrelevement\create(), Livraison\create(), Tva\create(), Productcustomerprice\create(), Productlot\create(), PaymentDonation\create(), PaymentSocialContribution\create(), PaymentExpenseReport\create(), Mailing\create(), Subscription\create(), PaymentLoan\create(), AdvanceTargetingMailing\create(), Deplacement\create(), LoanSchedule\create(), Website\create(), CashControl\create(), FactureRec\create(), EcmFiles\create(), Fiscalyear\create(), Establishment\create(), EcmDirectory\create(), Entrepot\create(), AccountancySystem\create(), Cronjob\create(), CommandeFournisseurDispatch\create(), Bookmark\create(), RemiseCheque\create(), PaiementFourn\create(), BookKeeping\create(), Loan\create(), ExpenseReport\create(), Project\create(), ChargeSociales\create(), Reception\create(), Fichinter\create(), DiscountAbsolute\create(), Contact\create(), AccountingAccount\create(), Paiement\create(), Holiday\create(), ActionComm\create(), Expedition\create(), FactureFournisseur\create(), Facture\create(), PaymentVarious\create(), Ticket\create(), PaymentSalary\create(), Don\create(), Adherent\create(), Product\create(), Societe\create(), Account\create(), UserGroup\create(), BlockedLog\create(), Commande\create(), BonPrelevement\Create(), SupplierProposal\create(), Propal\create(), Contrat\create(), User\create(), CommandeFournisseur\create(), ExtraFields\create_label(), createActionComm(), CommonObject\createCommon(), createContact(), Mailing\createFromClone(), WebsitePage\createFromClone(), Website\createFromClone(), ActionComm\createFromClone(), Facture\createFromClone(), Commande\createFromClone(), SupplierProposal\createFromClone(), Propal\createFromClone(), Project\createFromClone(), Task\createFromClone(), Facture\createFromOrder(), Commande\createFromProposal(), createInvoice(), createInvoiceFromOrder(), createOrder(), createPayment(), SupplierProposal\createPriceFournisseur(), createProductOrService(), FactureRec\createRecurringInvoices(), BookKeeping\createStd(), createThirdParty(), Ticket\createTicketMessage(), Stripe\customerStripe(), deleteProductOrService(), Facture\demande_prelevement(), CommandeFournisseur\dispatchProduct(), displayBox(), EmailCollector\doCollectOneCollector(), dol_cache_refresh(), dol_print_error_email(), MyObject\doScheduledJob(), BOM\doScheduledJob(), AccountancyExport\exportCiel(), Website\exportWebSite(), Contrat\fetch_lines(), BonPrelevement\generate(), Utils\generateDoc(), get_next_value(), CommonDocGenerator\get_substitutionarray_other(), Stats\getAllByProductEntry(), Stats\getAmountByMonthWithPrevYear(), getCommonSubstitutionArray(), ContratLigne\getLibStatut(), getListOfGroups(), getListOfProductsOrServices(), getListOfThirdParties(), Stats\getNbByMonthWithPrevYear(), mailing_thirdparties_services_expired\getNbOfRecipients(), mod_codeclient_monkey\getNextValue(), mod_ticket_simple\getNextValue(), mod_ticket_universal\getNextValue(), mod_project_simple\getNextValue(), mod_project_universal\getNextValue(), mod_task_simple\getNextValue(), mod_task_universal\getNextValue(), mod_livraison_jade\getNextValue(), mod_barcode_product_standard\getNextValue(), mod_codeproduct_elephant\getNextValue(), mod_codeclient_elephant\getNextValue(), Stripe\getPaymentIntent(), GETPOST(), getServerTimeZoneInt(), ProjectStats\getTransformRateByMonthWithPrevYear(), ProjectStats\getWeightedAmountByMonthWithPrevYear(), ActionComm\hasDelay(), Project\hasDelay(), Task\hasDelay(), ExpenseReport\hasDelay(), FactureFournisseur\hasDelay(), Adherent\hasDelay(), CommandeFournisseur\hasDelay(), Commande\hasDelay(), Facture\hasDelay(), modBlockedLog\init(), Don\initAsSpecimen(), CompanyBankAccount\initAsSpecimen(), Loan\initAsSpecimen(), Opensurveysondage\initAsSpecimen(), WebsitePage\initAsSpecimen(), PaiementFourn\initAsSpecimen(), Entrepot\initAsSpecimen(), ExpenseReport\initAsSpecimen(), Website\initAsSpecimen(), EcmFiles\initAsSpecimen(), Livraison\initAsSpecimen(), RemiseCheque\initAsSpecimen(), Project\initAsSpecimen(), Paiement\initAsSpecimen(), Reception\initAsSpecimen(), Fichinter\initAsSpecimen(), FactureRec\initAsSpecimen(), BookKeeping\initAsSpecimen(), ActionComm\initAsSpecimen(), Expedition\initAsSpecimen(), Holiday\initAsSpecimen(), Contrat\initAsSpecimen(), FactureFournisseur\initAsSpecimen(), CommandeFournisseur\initAsSpecimen(), User\initAsSpecimen(), Societe\initAsSpecimen(), Facture\initAsSpecimen(), Product\initAsSpecimen(), CommonObject\initAsSpecimenCommon(), DolibarrModules\insert_cronjobs(), Holiday\LibStatut(), FormFile\listOfLinks(), llxFooter(), RemiseCheque\load_board(), Account\load_board(), Contrat\load_board(), FactureFournisseur\load_board(), Holiday\load_board(), SupplierProposal\load_board(), Adherent\load_board(), ExpenseReport\load_board(), Propal\load_board(), Facture\load_board(), box_graph_invoices_permonth\loadBox(), box_graph_invoices_supplier_permonth\loadBox(), box_graph_orders_permonth\loadBox(), box_graph_propales_permonth\loadBox(), box_graph_orders_supplier_permonth\loadBox(), box_factures\loadBox(), box_services_expired\loadBox(), box_contracts\loadBox(), box_ficheinter\loadBox(), box_actions\loadBox(), box_birthdays\loadBox(), box_birthdays_members\loadBox(), box_propales\loadBox(), box_services_contracts\loadBox(), box_graph_product_distribution\loadBox(), box_factures_imp\loadBox(), box_activity\loadBox(), Ticket\markAsRead(), Ticket\messageSend(), migrate_project_task_actors(), migrate_project_user_resp(), migrate_reset_blocked_log(), LoanSchedule\paimenttorecord(), PriceParser\parseExpression(), RssParser\parser(), SupplierOrders\post(), SupplierInvoices\post(), Invoices\post(), print_paybox_redirect(), printSearchForm(), pt(), Utils\purgeFiles(), modBlockedLog\remove(), Contrat\reopen(), Cronjob\run_jobs(), InterfaceLogevents\runTrigger(), InterfaceActionsAuto\runTrigger(), Form\selectDate(), Notify\send(), ActionComm\sendEmailsReminder(), Adherent\sendReminderForExpiredSubscription(), Societe\set_price_level(), Societe\set_remise_client(), Societe\set_remise_supplier(), ExpenseReport\setApproved(), Project\setClose(), Reception\setClosed(), ExpenseReport\setDeny(), Fichinter\setValid(), ExpenseReport\setValidate(), show_actions_done(), show_array_actions_to_do(), show_array_last_actions_done(), FormActions\showactions(), Account\solde(), Adherent\subscription(), BookKeeping\transformTransaction(), Link\update(), Productlot\update(), ProductStockEntrepot\update(), Website\update(), Productcustomerprice\update(), Societe\update(), ProductFournisseur\update_buyprice(), ExtraFields\update_label(), User\update_last_login_date(), updateActionComm(), CommonObject\updateCommon(), updateContact(), Lettering\updateLettering(), updateOrder(), updateProductOrService(), Holiday\updateSoldeCP(), updateThirdParty(), CashControl\valid(), Commande\valid(), Livraison\valid(), Mailing\valid(), Reception\valid(), CommandeFournisseur\valid(), BOM\valid(), Expedition\valid(), SupplierProposal\valid(), Propal\valid(), Contrat\validate(), FactureFournisseur\validate(), Adherent\validate(), Facture\validate(), write_conf_file(), html_cerfafr\write_file(), doc_generic_odt\write_file(), doc_generic_contract_odt\write_file(), doc_generic_reception_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_shipment_odt\write_file(), doc_generic_order_odt\write_file(), doc_generic_user_odt\write_file(), doc_generic_product_odt\write_file(), doc_generic_stock_odt\write_file(), doc_generic_usergroup_odt\write_file(), doc_generic_proposal_odt\write_file(), doc_generic_supplier_proposal_odt\write_file(), and doc_generic_project_odt\write_file().
dol_osencode ($str)
Return a string encoded into OS filesystem encoding.
This function is used to define value to pass to filesystem PHP functions.
Parameters
string $str String to encode (UTF-8)
Returns
string Encoded string (UTF-8, ISO-8859-1)
Definition at line 6731 of file functions.lib.php.
Referenced by CMailFile\_encode_file(), activateModulesRequiredByCountry(), Product\add_photo(), addFileIntoDatabaseIndex(), Documents\builddoc(), checkLoginPassEntity(), complete_dictionary_with_modules(), complete_elementList_with_modules(), completeFileArrayWithDatabaseInfo(), Website\createFromClone(), EcmDirectory\delete(), Product\delete_photo(), dol_convert_file(), dol_copy(), dol_count_nb_of_line(), dol_delete_dir(), dol_delete_dir_recursive(), dol_delete_file(), dol_dir_is_emtpy(), dol_dir_list(), dol_filemtime(), dol_filesize(), dol_getImageSize(), dol_imageResizeOrCrop(), dol_is_dir(), dol_is_file(), dol_is_link(), dol_mkdir(), dol_move(), dol_move_uploaded_file(), dolCopyDir(), dolReplaceInFile(), Translate\file_exists(), Product\get_image_size(), Translate\getLabelFromNumber(), Interfaces\getTriggersList(), ModeleBoxes\getWidgetsList(), ImportCsv\import_open_file(), Documents\index(), Ticket\is_photo_available(), Product\is_photo_available(), Product\liste_photos(), listOfSessions(), llxFooter(), Translate\load(), Import\load_arrays(), Export\load_arrays(), migrate_user_photospath(), purgeSessions(), Interfaces\run_triggers(), Conf\setValues(), and vignette().
dol_print_address ($address, $htmlid, $mode, $id, $noprint = 0, $charfornl = '')
Format address string.
Parameters
string $address Address
int $htmlid Html ID (for example 'gmap')
int $mode thirdparty|contact|member|other
int $id Id of object
int $noprint No output. Result is the function return
string $charfornl Char to use instead of nl2br. '' means we use a standad nl2br.
Returns
string|void Nothing if noprint is 0, formatted address if noprint is 1
See also
dol_format_address()
Definition at line 2744 of file functions.lib.php.
References dol_buildpath(), and print.
dol_print_date ($time, $format = '', $tzoutput = 'tzserver', $outputlangs = '', $encodetooutput = false)
Output date in a string format according to outputlangs (or langs if not defined).
Return charset is always UTF-8, except if encodetoouput is defined. In this case charset is output charset
Parameters
int $time GM Timestamps date
string $format Output date format (tag of strftime function) "%d %b %Y", "%d/%m/%Y %H:%M", "%d/%m/%Y %H:%M:%S", "%B"=Long text of month, "%A"=Long text of day, "%b"=Short text of month, "%a"=Short text of day "day", "daytext", "dayhour", "dayhourldap", "dayhourtext", "dayrfc", "dayhourrfc", "...reduceformat"
string $tzoutput true or 'gmt' => string is for Greenwich location false or 'tzserver' => output string is for local PHP server TZ usage 'tzuser' => output string is for user TZ (current browser TZ with current dst) => In a future, we should have same behaviour than 'tzuserrel' 'tzuserrel' => output string is for user TZ (current browser TZ with dst or not, depending on date position) (TODO not implemented yet)
Translate $outputlangs Object lang that contains language for text translation.
boolean $encodetooutput false=no convert into output pagecode
Returns
string Formated date or '' if time is null
See also
dol_mktime(), dol_stringtotime(), dol_getdate()
Definition at line 1726 of file functions.lib.php.
References dol_mktime(), dol_print_error(), dol_strlen(), dol_substr(), and dol_syslog().
Referenced by modAccounting\__construct(), modUser\__construct(), modSociete\__construct(), modAdherent\__construct(), modProduct\__construct(), printing_printgcp\__construct(), MouvementStock\_create(), Product\_get_stats(), Adherent\_load_ldap_info(), pdf_ban\_pagehead(), pdf_paiement\_pagehead(), pdf_timespent\_pagehead(), pdf_merou\_pagehead(), pdf_sepamandate\_pagehead(), pdf_soleil\_pagehead(), pdf_baleine\_pagehead(), pdf_strato\_pagehead(), pdf_standard\_pagehead(), pdf_typhon\_pagehead(), pdf_beluga\_pagehead(), pdf_squille\_pagehead(), pdf_espadon\_pagehead(), pdf_rouget\_pagehead(), pdf_stdmovement\_pagehead(), pdf_canelle\_pagehead(), pdf_muscadet\_pagehead(), pdf_cornas\_pagehead(), pdf_einstein\_pagehead(), pdf_eratosthene\_pagehead(), pdf_azur\_pagehead(), pdf_cyan\_pagehead(), pdf_crabe\_pagehead(), pdf_sponge\_pagehead(), CommActionRapport\_pages(), pdf_einstein\_tableau_info(), pdf_aurore\_tableau_info(), pdf_azur\_tableau_info(), pdf_crabe\_tableau_tot(), pdf_crabe\_tableau_versements(), pdf_canelle\_tableau_versements(), mailing_fraise\add_to_target(), build_calfile(), constructGanttLine(), convertSecondToTime(), Facture\create(), create_key_table(), Mailing\createFromClone(), Task\createFromClone(), displayBox(), ActionsDatapolicy\doActions(), doc_getlinedesc(), EmailCollector\doCollectOneCollector(), dol_meta_create(), dol_print_error(), dol_print_object_info(), dol_syslog(), pdf_eratosthene\drawInfoTable(), pdf_cyan\drawInfoTable(), pdf_sponge\drawPaymentsTable(), pdf_sponge\drawTotalTable(), Form\editfieldval(), Form\editInPlace(), BonPrelevement\EnregDestinataireSEPA(), BonPrelevement\EnregEmetteurSEPA(), AccountancyExport\exportAgiris(), AccountancyExport\exportBob50(), AccountancyExport\exportCegid(), AccountancyExport\exportCharlemagne(), AccountancyExport\exportCiel(), AccountancyExport\exportCoala(), AccountancyExport\exportCogilog(), AccountancyExport\exportConfigurable(), AccountancyExport\exportEbp(), AccountancyExport\exportFEC(), AccountancyExport\exportLDCompta(), AccountancyExport\exportOpenConcerto(), AccountancyExport\exportQuadratus(), AccountancyExport\exportSAGE50SWISS(), Website\exportWebSite(), CommonDocGenerator\fill_substitutionarray_with_extrafields(), Form\form_date(), BonPrelevement\generate(), Utils\generateDoc(), get_date_range(), Dolistore\get_products(), CommonDocGenerator\get_substitutionarray_lines(), doc_generic_project_odt\get_substitutionarray_object(), doc_generic_task_odt\get_substitutionarray_object(), CommonDocGenerator\get_substitutionarray_object(), CommonDocGenerator\get_substitutionarray_other(), doc_generic_task_odt\get_substitutionarray_project_file(), doc_generic_project_odt\get_substitutionarray_project_file(), doc_generic_task_odt\get_substitutionarray_project_reference(), doc_generic_project_odt\get_substitutionarray_project_reference(), CommonDocGenerator\get_substitutionarray_shipment(), doc_generic_task_odt\get_substitutionarray_task_file(), doc_generic_project_odt\get_substitutionarray_task_file(), doc_generic_project_odt\get_substitutionarray_tasks(), doc_generic_task_odt\get_substitutionarray_tasks(), doc_generic_task_odt\get_substitutionarray_taskstime(), doc_generic_project_odt\get_substitutionarray_taskstime(), getActionComm(), ExpenseReportRule\getAllRule(), getCommonSubstitutionArray(), CoreObject\getDate(), getInvoice(), getInvoicesForThirdParty(), PriceGlobalVariableUpdater\getLastUpdated(), Productlot\getNomUrl(), PaiementFourn\getNomUrl(), Project\getNomUrl(), Paiement\getNomUrl(), Facture\getNomUrl(), FactureRec\getNomUrl(), FactureFournisseur\getNomUrl(), User\getNomUrl(), getOrder(), getOrdersForThirdParty(), getProductOrService(), getProductsForCategory(), getProject(), getServerTimeZoneInt(), getStructuredData(), getSupplierInvoice(), getSupplierInvoicesForThirdParty(), getThirdParty(), getUser(), BordereauChequeBlochet\Header(), DoliDB\idate(), DoliDBMssql\idate(), DoliDBPgsql\idate(), printing_printgcp\listJobs(), FormFile\listOfLinks(), box_last_ticket\loadBox(), box_last_modified_ticket\loadBox(), box_lastlogin\loadBox(), box_factures_fourn_imp\loadBox(), box_factures\loadBox(), box_services_expired\loadBox(), box_supplier_orders\loadBox(), box_contracts\loadBox(), box_factures_fourn\loadBox(), box_ficheinter\loadBox(), box_fournisseurs\loadBox(), box_actions\loadBox(), box_birthdays_members\loadBox(), box_commandes\loadBox(), box_external_rss\loadBox(), box_propales\loadBox(), box_services_contracts\loadBox(), box_birthdays\loadBox(), box_factures_imp\loadBox(), box_contacts\loadBox(), box_clients\loadBox(), box_produits\loadBox(), box_prospect\loadBox(), box_goodcustomers\loadBox(), box_members\loadBox(), ActionsCardProduct\LoadListDatas(), Adherent\makeSubstitution(), ExpenseReport\offsetAlreadyGiven(), pdf_getlinedesc(), pdf_getLinkedObjects(), print_paybox_redirect(), pdf_standard\printLine(), printSearchForm(), projectLinesa(), projectLinesPerAction(), pt(), report_header(), Cronjob\reprogram_jobs(), InterfaceActionsAuto\runTrigger(), Form\selectDate(), BonPrelevement\set_infocredit(), BonPrelevement\set_infotrans(), vCard\setBirthday(), show_actions_done(), show_list_sending_receive(), FormActions\showactions(), CommandeFournisseur\showDelay(), Commande\showDelay(), FormFile\showdocuments(), ExtraFields\showOutputField(), pdf_standard\tablePayments(), top_menu_user(), treeOutputForAbsoluteDir(), Holiday\updateSoldeCP(), ActionsTicket\viewTicketMessages(), ActionsTicket\viewTicketTimelineMessages(), write_conf_file(), html_cerfafr\write_file(), pdf_paiement\write_file(), pdf_timespent\write_file(), pdf_beluga\write_file(), pdf_soleil\write_file(), pdf_strato\write_file(), pdf_baleine\write_file(), doc_generic_odt\write_file(), pdf_stdmovement\write_file(), doc_generic_contract_odt\write_file(), doc_generic_reception_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_shipment_odt\write_file(), doc_generic_order_odt\write_file(), doc_generic_user_odt\write_file(), doc_generic_product_odt\write_file(), doc_generic_stock_odt\write_file(), doc_generic_usergroup_odt\write_file(), doc_generic_proposal_odt\write_file(), doc_generic_supplier_proposal_odt\write_file(), pdf_standard\write_file(), and doc_generic_project_odt\write_file().
dol_print_email ($email, $cid = 0, $socid = 0, $addlink = 0, $max = 64, $showinvalid = 1, $withpicto = 0)
Show EMail link.
Parameters
string $email EMail to show (only email, without 'Name of recipient' before)
int $cid Id of contact if known
int $socid Id of third party if known
int $addlink 0=no link, 1=email has a html email link (+ link to create action if constant AGENDA_ADDACTIONFOREMAIL is on)
int $max Max number of characters to show
int $showinvalid Show warning if syntax email is wrong
int $withpicto Show picto
Returns
string HTML Link
Definition at line 2135 of file functions.lib.php.
References dol_trunc(), img_object(), img_picto(), img_warning(), and isValidEmail().
Referenced by ActionsCardCommon\assign_values(), ActionsAdherentCardCommon\assign_values(), ActionsContactCardCommon\assign_values(), Form\editfieldval(), and ExtraFields\showOutputField().
dol_print_error ($db = '', $error = '', $errors = null)
Affiche message erreur system avec toutes les informations pour faciliter le diagnostic et la remontee des bugs.
On doit appeler cette fonction quand une erreur technique bloquante est rencontree. Toutefois, il faut essayer de ne l'appeler qu'au sein de pages php, les classes devant renvoyer leur erreur par l'intermediaire de leur propriete "error".
Parameters
DoliDB $db Database handler
mixed $error String or array of errors strings to show
array $errors Array of errors
Returns
void
See also
dol_htmloutput_errors()
Definition at line 3749 of file functions.lib.php.
References dol_escape_htmltag(), dol_htmlentities(), dol_print_date(), dol_syslog(), and print.
Referenced by mailing_thirdparties_services_expired\__construct(), modAgenda\__construct(), MouvementStock\_create(), Stats\_getAllByProduct(), Stats\_getAllByYear(), Stats\_getAmountByMonth(), Stats\_getAverageByMonth(), Stats\_getNbByMonth(), Stats\_getNbByYear(), Product\_log_price(), pdf_standard\_pagehead(), pdf_stdmovement\_pagehead(), Product\add_sousproduit(), MailingTargets\add_to_target(), mailing_contacts1\add_to_target(), addDocumentModel(), Account\addline(), ActionsStripeconnect\addMoreActionsButtons(), Localtax\addPayment(), Tva\addPayment(), PaymentLoan\addPaymentToBank(), PaymentDonation\addPaymentToBank(), PaymentExpenseReport\addPaymentToBank(), PaymentSocialContribution\addPaymentToBank(), Paiement\addPaymentToBank(), UserGroup\addrights(), User\addrights(), Task\addTimeSpent(), ajouter_sondage(), BlockedLog\alreadyUsed(), analyseVarsForSqlAndScriptsInjection(), ActionsAdherentCardCommon\assign_post(), ActionsContactCardCommon\assign_post(), Export\build_filterField(), calcul_price_total(), MouvementStock\calculateBalanceForProductBefore(), Account\can_be_deleted(), Stripe\cardStripe(), checkUserAccessToObject(), chequereceipt_pdf_create(), CommandeFournisseur\classifyBilled(), clean_data_ecm_directories(), cleanCorruptedTree(), Form\constructProductListOption(), Societe\contact_array(), Societe\contact_array_objects(), Societe\contact_get_property(), Societe\contact_property_array(), Categorie\containing(), Account\countAccountToReconcile(), Menubase\create(), Fichinter\create(), FactureFournisseur\create(), Facture\create(), PaymentVarious\create(), PaymentSalary\create(), Commande\create(), SupplierProposal\create(), Propal\create(), Contrat\create(), CommandeFournisseur\create(), Holiday\createCPusers(), FactureRec\createRecurringInvoices(), Stripe\customerStripe(), AccountLine\dateo_change(), AccountLine\datev_change(), Product\del_sousproduit(), delDocumentModel(), DiscountAbsolute\delete(), UserGroup\delete(), BonPrelevement\delete(), ExtraFields\delete_label(), Facture\deleteline(), UserGroup\delrights(), User\delrights(), doc_label_pdf_create(), dol_check_secure_access_document(), dol_dir_list_in_database(), dol_mktime(), dol_print_date(), dol_set_user_param(), dolibarr_del_const(), dolibarr_set_const(), facture_prepare_head(), PaiementFourn\fetch(), Bookmark\fetch(), UserBankAccount\fetch(), Paiement\fetch(), CompanyBankAccount\fetch(), Categorie\fetch(), Import\fetch(), Ticket\fetch(), Don\fetch(), Export\fetch(), Product\fetch(), ExpenseReportLine\fetch(), SupplierProposalLine\fetch(), CommandeFournisseurLigne\fetch(), Opensurveysondage\fetch_lines(), Adherent\fetch_login(), Adherent\fetch_name(), ActionComm\fetch_userassigned(), EmailCollector\fetchActions(), ProductAttribute\fetchAll(), ExpeditionLineBatch\fetchAll(), Task\fetchAllTimeSpent(), EmailCollector\fetchFilters(), ActionComm\fetchResources(), fichinter_create(), FormCompany\form_prospect_level(), mailing_fraise\formFilter(), mailing_contacts1\formFilter(), mailing_advthirdparties\formFilter(), mailing_thirdparties\formFilter(), Utils\generateDoc(), Don\generateDocument(), Societe\generateDocument(), RemiseCheque\generatePdf(), Categorie\get_all_categories(), User\get_children(), Project\get_element_list(), Categorie\get_filles(), FormMail\get_form(), EcmDirectory\get_full_arbo(), Entrepot\get_full_arbo(), Categorie\get_full_arbo(), User\get_full_tree(), Categorie\get_meres(), get_next_value(), get_product_localtax_for_country(), get_product_vat_for_country(), Account\get_url(), Fiscalyear\getAccountancyEntriesByFiscalYear(), Fiscalyear\getAccountancyMovementsByFiscalYear(), ExpenseReportIk\getAllRanges(), ExpenseReportRule\getAllRule(), AccountancyCategory\getCats(), AccountancyCategory\getCatsCpts(), Product\getChildsArbo(), getCountry(), AccountancyCategory\getCptsCat(), CommandeFournisseur\getDispachedLines(), Establishment\getEstablishment(), ExpenseReportLine\getExpAmount(), Product\getFather(), ActionsCardService\getFieldList(), ActionsCardProduct\getFieldList(), CommandeFournisseur\getInputMethod(), CommonInvoice\getListIdAvoirFromInvoice(), InterfaceNotification\getListOfManagedEvents(), getListOfModels(), CommonInvoice\getListOfPayments(), ExpenseReportIk\getMaxRangeNumber(), Reception\getNextNumRef(), Holiday\getNextNumRef(), Contrat\getNextNumRef(), Expedition\getNextNumRef(), Commande\getNextNumRef(), RemiseCheque\getNextNumRef(), BOM\getNextNumRef(), PaiementFourn\getNextNumRef(), CommandeFournisseur\getNextNumRef(), Fichinter\getNextNumRef(), Paiement\getNextNumRef(), ExpenseReport\getNextNumRef(), FactureFournisseur\getNextNumRef(), SupplierProposal\getNextNumRef(), Facture\getNextNumRef(), Propal\getNextNumRef(), mod_expensereport_jade\getNextValue(), mod_facture_mars\getNextValue(), mod_facture_fournisseur_cactus\getNextValue(), mod_facture_terre\getNextValue(), Stripe\getPaymentIntent(), BlockedLog\getPreviousHash(), Project\getProjectsAuthorizedForUser(), ExpenseReportIk\getRangesByCategory(), Societe\getSalesRepresentatives(), getServerTimeZoneInt(), getSourceDocRef(), getState(), Stripe\getStripeAccount(), DiscountAbsolute\getSumCreditNotesUsed(), DiscountAbsolute\getSumDepositsUsed(), DiscountAbsolute\getSumFromThisCreditNotesNotUsed(), Task\getSummaryOfTimeSpent(), Task\getSumOfAmount(), Task\getTasksArray(), ExpenseReportIk\getTaxCategories(), getTaxesFromId(), Holiday\getTypes(), Task\getUserRolesForProjectsOrTasks(), ImportCsv\import_insert(), ImportXlsx\import_insert(), Fiscalyear\info(), Establishment\info(), EmailSenderProfile\info(), PaiementFourn\info(), Asset\info(), EmailCollectorFilter\info(), Inventory\info(), Deplacement\info(), Subscription\info(), EmailCollectorAction\info(), Entrepot\info(), SocieteAccount\info(), AccountingAccount\info(), CompanyPaymentMode\info(), EmailCollector\info(), ChargeSociales\info(), MyObject\info(), PaymentVarious\info(), PaymentSalary\info(), ExpenseReport\info(), PaymentExpenseReport\info(), Tva\info(), BOM\info(), Fichinter\info(), Don\info(), Paiement\info(), ActionComm\info(), BOMLine\info(), Project\info(), FactureFournisseur\info(), Contrat\info(), SupplierProposal\info(), AccountLine\info(), Adherent\info(), User\info(), CommandeFournisseur\info(), Propal\info(), Societe\info(), Facture\info(), Commande\info(), Product\info(), FichinterLigne\insert(), DolibarrModules\insert_permissions(), Product\is_sousproduit(), CommonObject\isExistingObject(), Product\isVariant(), Export\list_export_model(), Fournisseur\ListArray(), SupplierProposal\liste_array(), Commande\liste_array(), Propal\liste_array(), Facture\liste_array(), ModeleAction\liste_modeles(), Ticket\listeContact(), Deplacement\listOfTypes(), ExpenseReport\listOfTypes(), llxFooter(), llxFooterVierge(), Translate\load(), RemiseCheque\load_board(), ActionComm\load_board(), Account\load_board(), Contrat\load_board(), FactureFournisseur\load_board(), Holiday\load_board(), Adherent\load_board(), ExpenseReport\load_board(), Facture\load_board(), Form\load_cache_availability(), Dolresource\load_cache_code_type_resource(), Form\load_cache_conditions_paiements(), Form\load_cache_types_fees(), Form\load_cache_types_paiements(), EcmDirectory\load_motherof(), Categorie\load_motherof(), Client\load_state_board(), Fournisseur\load_state_board(), Fichinter\load_state_board(), Contact\load_state_board(), RemiseCheque\load_state_board(), Don\load_state_board(), Account\load_state_board(), Project\load_state_board(), Task\load_state_board(), Holiday\load_state_board(), Contrat\load_state_board(), Adherent\load_state_board(), ExpenseReport\load_state_board(), SupplierProposal\load_state_board(), FactureFournisseur\load_state_board(), CommandeFournisseur\load_state_board(), User\load_state_board(), Propal\load_state_board(), Commande\load_state_board(), Facture\load_state_board(), Product\load_state_board(), Product\load_virtual_stock(), Product\loadBatchInfo(), box_last_ticket\loadBox(), box_last_modified_ticket\loadBox(), box_task\loadBox(), box_activity\loadBox(), Ticket\loadCacheCategoriesTickets(), Translate\loadCacheCurrencies(), Form\loadCacheInputReason(), Ticket\loadCacheSeveritiesTickets(), Ticket\loadCacheTypesTickets(), User\loadDefaultValues(), Translate\loadFromDatabase(), ActionsCardProduct\LoadListDatas(), FormProduct\loadLotStock(), User\loadParentOf(), Project\loadTimeSpent(), FormProduct\loadWarehouses(), Invoices\markAsCreditAvailable(), members_card_pdf_create(), Menubase\menuLoad(), Ticket\messageSend(), migrate_actioncomm_element(), migrate_categorie_association(), migrate_commande_deliveryaddress(), migrate_commande_expedition(), migrate_commande_livraison(), migrate_contracts_date1(), migrate_contracts_date3(), migrate_contracts_det(), migrate_contracts_open(), migrate_customerorder_shipping(), migrate_detail_livraison(), migrate_event_assignement(), migrate_event_assignement_contact(), migrate_links_transfert(), migrate_menus(), migrate_mode_reglement(), migrate_modeles(), migrate_paiements(), migrate_paiements_orphelins_1(), migrate_paiements_orphelins_2(), migrate_project_task_actors(), migrate_project_task_time(), migrate_project_user_resp(), migrate_relationship_tables(), migrate_remise_entity(), migrate_remise_except_entity(), migrate_reset_blocked_log(), migrate_restore_missing_links(), migrate_shipping_delivery(), migrate_shipping_delivery2(), migrate_stocks(), migrate_user_rights_entity(), migrate_usergroup_rights_entity(), FormAdvTargetEmailing\multiselectCategories(), FormAdvTargetEmailing\multiselectCivility(), FormAdvTargetEmailing\multiselectCountry(), FormAdvTargetEmailing\multiselectProspectionStatus(), FormAdvTargetEmailing\multiselectselectSalesRepresentatives(), Commande\nb_expedition(), ExpenseReport\offsetAlreadyGiven(), ordered(), pdf_bank(), print_left_auguria_menu(), print_left_eldy_menu(), print_paybox_redirect(), print_projecttasks_array(), printBookmarksList(), printing_printipp\printFile(), printing_printgcp\printFile(), project_prepare_head(), pt(), rebuild_merge_pdf(), Contrat\reopen(), security_prepare_head(), FormAccounting\select_accounting_category(), Form\select_address(), Form\select_all_categories(), FormCompany\select_civility(), Form\select_comptes(), FormContract\select_contract(), Form\select_country(), FormOther\select_dictionary(), Form\select_dolgroups(), Form\select_dolusers(), FormOther\select_ecotaxes(), FormProjets\select_element(), FormOther\select_export_model(), Form\select_export_model(), FormOther\select_import_model(), Form\select_incoterms(), FormIntervention\select_interventions(), FormCompany\select_juridicalstatus(), FormAdmin\select_paper_format(), Form\select_product_fourn_price(), Form\select_produits_fournisseurs_list(), Form\select_produits_list(), FormProjets\select_projects_list(), FormCompany\select_region(), Form\select_remises(), FormResource\select_resource_list(), FormOther\select_revenue_stamp(), FormOther\select_salesrepresentatives(), FormCompany\select_state(), Form\select_thirdparty_list(), FormSocialContrib\select_type_socialcontrib(), FormAdvTargetEmailing\selectAdvtargetemailingTemplate(), FormBarCode\selectBarcodeType(), FormCompany\selectCompaniesForNewContact(), Form\selectcontacts(), Form\selectEstablishments(), Form\selectExpense(), Form\selectExpenseCategories(), Form\selectExpenseRanges(), FormOrder\selectInputMethod(), FormProduct\selectMeasuringUnits(), FormPropal\selectProposalStatus(), Form\selectShippingMethod(), FormProjets\selectTasks(), FormWebsite\selectTypeOfContainer(), FormWebsite\selectWebsite(), Notify\send(), CSMSFile\sendfile(), DataPolicy\sendMailDataPolicyAdherent(), DataPolicy\sendMailDataPolicyCompany(), DataPolicy\sendMailDataPolicyContact(), Don\set_cancel(), ExpenseReport\set_paid(), Don\set_paid(), FactureFournisseur\set_paid(), Societe\set_price_level(), Commande\set_reopen(), Facture\set_unpaid(), CompanyBankAccount\setAsDefault(), CompanyPaymentMode\setAsDefault(), FactureRec\setAutoValidate(), Reception\setClosed(), Expedition\setClosed(), Ticket\setContract(), setEventMessages(), FactureRec\setFrequencyAndUnit(), FactureRec\setGeneratePdf(), FactureRec\setMaxPeriod(), FactureRec\setModelPdf(), FactureRec\setNextDate(), Adherent\setPassword(), User\setPassword(), Ticket\setProject(), Fichinter\setValid(), show_actions_done(), show_array_actions_to_do(), show_array_last_actions_done(), show_contacts(), FormSms\show_form(), show_list_sending_receive(), show_projects(), show_stats_for_company(), FormActions\showactions(), FormFile\showdocuments(), Form\showLinkToObjectBlock(), Form\showphoto(), societe_prepare_head(), task_prepare_head(), tax_by_rate(), tax_by_thirdparty(), UserBankAccount\update(), CompanyBankAccount\update(), Categorie\update(), Account\update(), UserGroup\update(), Product\update(), ExpenseReportLine\update(), Account\update_bban(), Reception\update_delivery_method(), Expedition\update_delivery_method(), PaymentVarious\update_fk_bank(), PaymentSalary\update_fk_bank(), Localtax\update_fk_bank(), Tva\update_fk_bank(), ExtraFields\update_label(), Product\update_sousproduit(), Product\updatePrice(), User\user_get_property(), user_prepare_head(), Commande\valid(), Livraison\valid(), CommandeFournisseur\valid(), BOM\valid(), SupplierProposal\valid(), Propal\valid(), Contrat\validate(), Facture\validate(), Auth\verif(), Holiday\verifDateHolidayCP(), Holiday\verifDateHolidayForTimestamp(), ActionsTicket\viewTicketMessages(), pdf_paiement\write_file(), pdf_standard\write_file(), pdf_stdmovement\write_file(), doc_generic_contract_odt\write_file(), doc_generic_reception_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_order_odt\write_file(), doc_generic_shipment_odt\write_file(), doc_generic_user_odt\write_file(), doc_generic_stock_odt\write_file(), doc_generic_product_odt\write_file(), doc_generic_usergroup_odt\write_file(), doc_generic_proposal_odt\write_file(), doc_generic_supplier_proposal_odt\write_file(), pdf_standardlabel\write_file(), pdf_tcpdflabel\write_file(), doc_generic_task_odt\write_file(), doc_generic_project_odt\write_file(), ExportTsv\write_record(), ExportCsv\write_record(), ExportExcel2007new\write_record(), ExportExcel\write_record(), ExportExcel2007new\write_title(), and ExportExcel\write_title().
dol_print_error_email ($prefixcode, $errormessage = '', $errormessages = array(), $morecss = 'error', $email = '')
Show a public email and error code to contact if technical error.
Parameters
string $prefixcode Prefix of public error code
string $errormessage Complete error message
array $errormessages Array of error messages
string $morecss More css
string $email Email
Returns
void
Definition at line 3882 of file functions.lib.php.
References dol_now(), and print.
dol_print_ip ($ip, $mode = 0)
Return an IP formated to be shown on screen.
Parameters
string $ip IP
int $mode 0=return IP + country/flag, 1=return only country/flag, 2=return only IP
Returns
string Formated IP, with country if GeoIP module is enabled
Definition at line 2637 of file functions.lib.php.
References dolGetCountryCodeFromIp().
dol_print_phone ($phone, $countrycode = '', $cid = 0, $socid = 0, $addlink = '', $separ = "&nbsp;", $withpicto = '', $titlealt = '', $adddivfloat = 0)
Format phone numbers according to country.
Parameters
string $phone Phone number to format
string $countrycode Country code to use for formatting
int $cid Id of contact if known
int $socid Id of third party if known
string $addlink ''=no link to create action, 'AC_TEL'=add link to clicktodial (if module enabled) and add link to create event (if conf->global->AGENDA_ADDACTIONFORPHONE set)
string $separ Separation between numbers for a better visibility example : xx.xx.xx.xx.xx
string $withpicto Show picto
string $titlealt Text to show on alt
int $adddivfloat Add div float around phone.
Returns
string Formated phone number
Definition at line 2248 of file functions.lib.php.
References dol_strlen(), img_object(), img_picto(), and make_substitutions().
Referenced by ActionsCardCommon\assign_values(), ActionsAdherentCardCommon\assign_values(), ActionsContactCardCommon\assign_values(), show_actions_done(), and ExtraFields\showOutputField().
dol_print_size ($size, $shortvalue = 0, $shortunit = 0)
Return string with formated size.
Parameters
int $size Size to print
int $shortvalue Tell if we want long value to use another unit (Ex: 1.5Kb instead of 1500b)
int $shortunit Use short label of size unit (for example 'b' instead of 'bytes')
Returns
string Link
Definition at line 2069 of file functions.lib.php.
Referenced by FormFile\list_of_autoecmfiles(), FormFile\list_of_documents(), and showWebsiteTemplates().
dol_print_socialnetworks ($value, $cid, $socid, $type)
Show social network link.
Parameters
string $value Skype to show (only skype, without 'Name of recipient' before)
int $cid Id of contact if known
int $socid Id of third party if known
string $type 'skype','facebook',...
Returns
string HTML Link
Definition at line 2192 of file functions.lib.php.
References img_object(), img_picto(), and img_warning().
dol_print_url ($url, $target = '_blank', $max = 32, $withpicto = 0)
Show Url link.
Parameters
string $url Url to show
string $target Target for link
int $max Max number of characters to show
int $withpicto With picto
Returns
string HTML Link
Definition at line 2105 of file functions.lib.php.
References dol_trunc(), and img_picto().
Referenced by ActionsCardCommon\assign_values(), and ExtraFields\showOutputField().
dol_sanitizeFileName ($str, $newstr = '_', $unaccent = 1)
Clean a string to use it as a file name.
Parameters
string $str String to clean
string $newstr String to replace bad chars with
int $unaccent 1=Remove also accent (default), 0 do not remove them
Returns
string String cleaned (a-zA-Z_)
See also
dol_string_nospecial(), dol_string_unaccent(), dol_sanitizePathName()
Definition at line 817 of file functions.lib.php.
References dol_string_nospecial(), and dol_string_unaccent().
Referenced by FileUpload\__construct(), asset_prepare_head(), bank_prepare_head(), bomPrepareHead(), Product\check(), clean_data_ecm_directories(), commande_prepare_head(), contact_prepare_head(), contract_prepare_head(), EcmDirectory\create(), Reception\create(), Expedition\create(), Project\createFromClone(), Task\createFromClone(), Dolresource\delete(), Task\delete(), Project\delete(), Livraison\delete(), Reception\delete(), Fichinter\delete(), FactureFournisseur\delete(), Product\delete(), Contrat\delete(), Expedition\delete(), CommandeFournisseur\delete(), Facture\delete(), SupplierProposal\delete(), Propal\delete(), Commande\delete(), dol_add_file_process(), dol_banner_tab(), dol_delete_preview(), dol_meta_create(), donation_prepare_head(), Utils\dumpDatabase(), expensereport_prepare_head(), facture_prepare_head(), fichinter_prepare_head(), Thirdparties\generateBankAccountDocument(), Documents\getDocumentsListByElement(), EcmDirectory\getRelativePath(), holiday_prepare_head(), FormFile\list_of_documents(), loan_prepare_head(), myobjectPrepareHead(), ordersupplier_prepare_head(), product_prepare_head(), productlot_prepare_head(), project_prepare_head(), propal_prepare_head(), resource_prepare_head(), Notify\send(), Fichinter\setValid(), ExpenseReport\setValidate(), Conf\setValues(), shipping_prepare_head(), task_prepare_head(), tax_prepare_head(), Dolresource\update(), Project\update(), Task\update(), Product\update(), Societe\update(), Commande\valid(), Livraison\valid(), Reception\valid(), CommandeFournisseur\valid(), BOM\valid(), Expedition\valid(), SupplierProposal\valid(), Propal\valid(), Contrat\validate(), FactureFournisseur\validate(), Facture\validate(), various_payment_prepare_head(), vat_prepare_head(), html_cerfafr\write_file(), pdf_ban\write_file(), pdf_sepamandate\write_file(), pdf_timespent\write_file(), pdf_squille\write_file(), pdf_beluga\write_file(), pdf_espadon\write_file(), pdf_merou\write_file(), pdf_soleil\write_file(), pdf_strato\write_file(), pdf_baleine\write_file(), pdf_cornas\write_file(), pdf_rouget\write_file(), doc_generic_odt\write_file(), pdf_typhon\write_file(), pdf_cyan\write_file(), pdf_stdmovement\write_file(), pdf_eratosthene\write_file(), doc_generic_contract_odt\write_file(), pdf_canelle\write_file(), doc_generic_reception_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_shipment_odt\write_file(), doc_generic_order_odt\write_file(), pdf_aurore\write_file(), pdf_sponge\write_file(), pdf_standard\write_file(), pdf_muscadet\write_file(), pdf_azur\write_file(), doc_generic_user_odt\write_file(), pdf_einstein\write_file(), doc_generic_product_odt\write_file(), doc_generic_stock_odt\write_file(), doc_generic_usergroup_odt\write_file(), doc_generic_proposal_odt\write_file(), pdf_crabe\write_file(), doc_generic_supplier_proposal_odt\write_file(), doc_generic_task_odt\write_file(), and doc_generic_project_odt\write_file().
dol_sanitizePathName ($str, $newstr = '_', $unaccent = 1)
Clean a string to use it as a path name.
Parameters
string $str String to clean
string $newstr String to replace bad chars with
int $unaccent 1=Remove also accent (default), 0 do not remove them
Returns
string String cleaned (a-zA-Z_)
See also
dol_string_nospecial(), dol_string_unaccent(), dol_sanitizeFileName()
Definition at line 834 of file functions.lib.php.
References dol_string_nospecial(), and dol_string_unaccent().
Referenced by Documents\getDocumentsListByElement().
dol_set_focus ($selector)
Set focus onto field with selector (similar behaviour of 'autofocus' HTML5 tag)
Parameters
string $selector Selector ('#id' or 'input[name="ref"]') to use to find the HTML input field that must get the autofocus. You must use a CSS selector, so unique id preceding with the '#' char.
Returns
string HTML code to set focus
Definition at line 7466 of file functions.lib.php.
dol_shutdown ()
Function called at end of web php process.
Returns
void
Definition at line 212 of file functions.lib.php.
References dol_syslog().
dol_size ($size, $type = '')
Optimize a size for some browsers (phone, smarphone, ...)
Parameters
int $size Size we want
string $type Type of optimizing: '' = function used to define a size for truncation 'width' = function is used to define a width
Returns
int New size after optimizing
Definition at line 798 of file functions.lib.php.
dol_sort_array (& $array, $index, $order = 'asc', $natsort = 0, $case_sensitive = 0, $keepindex = 0)
Advanced sort array by second index function, which produces ascending (default) or descending output and uses optionally natural case insensitive sorting (which can be optionally case sensitive as well).
Parameters
array $array Array to sort (array of array('key1'=>val1,'key2'=>val2,'key3'...) or array of objects)
string $index Key in array to use for sorting criteria
int $order Sort order ('asc' or 'desc')
int $natsort 1=use "natural" sort (natsort), 0=use "standard" sort (asort)
int $case_sensitive 1=sort is case sensitive, 0=not case sensitive
int $keepindex If 0 and index key of array to sort is a numeric, than index will be rewrote. If 1 or index key is not numeric, key for index is kept after sorting.
Returns
array Sorted array
Definition at line 6652 of file functions.lib.php.
Referenced by dol_dir_list(), EcmDirectory\get_full_arbo(), Categorie\get_full_arbo(), User\get_full_tree(), Setup\getCheckIntegrity(), FormFile\list_of_documents(), Form\load_cache_availability(), Form\load_cache_types_paiements(), Form\loadCacheInputReason(), print_auguria_menu(), print_eldy_menu(), Form\select_country(), FormCompany\select_juridicalstatus(), show_contacts(), and MenuManager\showmenu().
dol_strftime ($fmt, $ts = false, $is_gmt = false)
Format a string.
Parameters
string $fmt Format of strftime function (http://php.net/manual/fr/function.strftime.php)
int $ts Timesamp (If is_gmt is true, timestamp is already includes timezone and daylight saving offset, if is_gmt is false, timestamp is a GMT timestamp and we must compensate with server PHP TZ)
int $is_gmt See comment of timestamp parameter
Returns
string A formatted string
Definition at line 1697 of file functions.lib.php.
dol_string_is_good_iso ($s)
Check if a string is a correct iso string If not, it will we considered not HTML encoded even if it is by FPDF.
Example, if string contains euro symbol that has ascii code 128
Parameters
string $s String to check
Returns
int 0 if bad iso, 1 if good iso
Definition at line 5668 of file functions.lib.php.
References dol_strlen().
dol_string_neverthesehtmltags ($stringtoclean, $disallowed_tags = array('textarea'))
Clean a string from some undesirable HTML tags.
Parameters
string $stringtoclean String to clean
array $disallowed_tags Array of tags not allowed
Returns
string String cleaned
See also
dol_escape_htmltag() strip_tags() dol_string_nohtmltag() dol_string_onlythesehtmltags()
Definition at line 5475 of file functions.lib.php.
Referenced by Form\editfieldval().
dol_string_nohtmltag ($stringtoclean, $removelinefeed = 1, $pagecodeto = 'UTF-8', $strip_tags = 0)
Clean a string from all HTML tags and entities.
This function differs from strip_tags because:
are replaced with
if removelinefeed=0 or 1
if entities are found, they are decoded BEFORE the strip
you can decide to convert line feed into a space
Parameters
string $stringtoclean String to clean
integer $removelinefeed 1=Replace all new lines by 1 space, 0=Only ending new lines are removed others are replaced with
, 2=Ending new lines are removed but others are kept with a same number of
than nb of
when there is both "...<br>\n..."
string $pagecodeto Encoding of input/output string
integer $strip_tags 0=Use internal strip, 1=Use strip_tags() php function (bugged when text contains a < char that is not for a html tag)
Returns
string String cleaned
See also
dol_escape_htmltag() strip_tags() dol_string_onlythesehtmltags() dol_string_neverthesehtmltags()
Definition at line 5411 of file functions.lib.php.
References dol_html_entity_decode().
Referenced by AdherentType\_load_ldap_info(), Contact\_load_ldap_info(), UserGroup\_load_ldap_info(), Adherent\_load_ldap_info(), User\_load_ldap_info(), ajax_dialog(), build_calfile(), build_rssfile(), EmailCollector\doCollectOneCollector(), dol_add_file_process(), dol_trunc(), ExportExcel2007new\excel_clean(), ExportExcel\excel_clean(), FormMail\get_form(), getCommonSubstitutionArray(), Facture\getNomUrl(), GETPOST(), pdf_build_address(), printCommonFooter(), AccountancyExport\toAnsi(), and ExportTsv\tsv_clean().
dol_string_nospecial ($str, $newstr = '_', $badcharstoreplace = '')
Clean a string from all punctuation characters to use it as a ref or login.
This is a more complete function than dol_sanitizeFileName.
Parameters
string $str String to clean
string $newstr String to replace forbidden chars with
array $badcharstoreplace List of forbidden characters
Returns
string Cleaned string
See also
dol_sanitizeFilename(), dol_string_unaccent()
Definition at line 906 of file functions.lib.php.
Referenced by check_value(), Societe\contact_get_property(), Product\create(), dol_buildlogin(), dol_sanitizeFileName(), dol_sanitizePathName(), DolGraph\draw_jflot(), get_next_value(), GETPOST(), Product\update(), and doc_generic_odt\write_file().
dol_string_onlythesehtmltags ($stringtoclean)
Clean a string to keep only desirable HTML tags.
Parameters
string $stringtoclean String to clean
Returns
string String cleaned
See also
dol_escape_htmltag() strip_tags() dol_string_nohtmltag() dol_string_neverthesehtmltags()
Definition at line 5449 of file functions.lib.php.
dol_string_unaccent ($str)
Clean a string from all accent characters to be used as ref, login or by dol_sanitizeFileName.
Parameters
string $str String to clean
Returns
string Cleaned string
See also
dol_sanitizeFilename(), dol_string_nospecial()
Definition at line 848 of file functions.lib.php.
References utf8_check().
Referenced by dol_buildlogin(), dol_sanitizeFileName(), dol_sanitizePathName(), DolGraph\draw_jflot(), BonPrelevement\EnregDestinataireSEPA(), BonPrelevement\EnregEmetteurSEPA(), AccountancyExport\exportCiel(), AccountancyExport\exportQuadratus(), BonPrelevement\generate(), get_next_value(), and Form\select_country().
dol_strlen ($string, $stringencoding = 'UTF-8')
Make a strlen call.
Works even if mbstring module not enabled
Parameters
string $string String to calculate length
string $stringencoding Encoding of string
Returns
int Length of string
Definition at line 2853 of file functions.lib.php.
Referenced by Product\_get_stats(), Contact\_load_ldap_info(), User\_load_ldap_info(), activateModulesRequiredByCountry(), ContratLigne\active_line(), Contrat\addline(), ActionsCardCommon\assign_values(), ActionsAdherentCardCommon\assign_values(), ActionsContactCardCommon\assign_values(), binhex(), Categorie\build_path_from_id_categ(), User\build_path_from_id_user(), calEncode(), Don\check(), Product\check(), check_value(), chequereceipt_pdf_create(), complete_dictionary_with_modules(), complete_elementList_with_modules(), Form\constructProductListOption(), Productbatch\create(), Productlot\create(), ExpeditionLineBatch\create(), Website\create(), EcmFiles\create(), Cronjob\create(), CommandeFournisseurDispatch\create(), BookKeeping\create(), Ticket\create(), Product\create(), Contrat\create(), BookKeeping\createStd(), doc_label_pdf_create(), dol_ch_controle_bvrb(), dol_decode(), dol_encode(), dol_nboflines_bis(), dol_print_date(), dol_print_phone(), dol_setshmop(), dol_string_is_good_iso(), dol_trunc(), DolGraph\draw_artichow(), Product\fetch(), fichinter_create(), Fichinter\generateDocument(), MyObject\generateDocument(), Entrepot\generateDocument(), BOM\generateDocument(), Don\generateDocument(), UserGroup\generateDocument(), Livraison\generateDocument(), MouvementStock\generateDocument(), Project\generateDocument(), Task\generateDocument(), Reception\generateDocument(), ExpenseReport\generateDocument(), Expedition\generateDocument(), Adherent\generateDocument(), Contrat\generateDocument(), SupplierProposal\generateDocument(), CommandeFournisseur\generateDocument(), User\generateDocument(), Propal\generateDocument(), Commande\generateDocument(), Societe\generateDocument(), Product\generateDocument(), Facture\generateDocument(), get_next_value(), DolGraph\GetCeilMaxValue(), DolGraph\GetFloorMinValue(), modGeneratePassStandard\getNewGeneratedPassword(), getPagesFromSearchCriterias(), hexbin(), Societe\id_prof_check(), ImportCsv\import_read_record(), ImportXlsx\import_read_record(), DolibarrModules\insert_permissions(), ModeleAction\liste_modeles(), Ldap\littleEndian(), load_fiche_titre(), Form\load_tva(), box_last_ticket\loadBox(), box_last_modified_ticket\loadBox(), box_graph_invoices_supplier_permonth\loadBox(), box_graph_invoices_permonth\loadBox(), box_graph_propales_permonth\loadBox(), box_graph_orders_supplier_permonth\loadBox(), box_graph_orders_permonth\loadBox(), box_lastlogin\loadBox(), box_factures\loadBox(), box_graph_product_distribution\loadBox(), box_project\loadBox(), box_task\loadBox(), box_activity\loadBox(), ActionsCardService\LoadListDatas(), ActionsCardProduct\LoadListDatas(), makesalt(), members_card_pdf_create(), Ticket\messageSend(), pdf_bank(), price(), price2num(), Form\select_produits_fournisseurs_list(), Notify\send(), FormSms\show_form(), CompanyBankAccount\update(), Productlot\update(), Project\update(), Fichinter\update(), Website\update(), EcmFiles\update(), Cronjob\update(), Productcustomerprice\update(), Ticket\update(), FactureFournisseur\update(), BookKeeping\update(), Contrat\updateline(), utf8_check(), modGeneratePassStandard\validatePassword(), mod_codeclient_monkey\verif(), mod_barcode_product_standard\verif(), and mod_codeclient_monkey\verif_syntax().
dol_strtolower ($utf8_string)
Convert a string to lower.
Never use strtolower because it does not works with UTF8 strings.
Parameters
string $utf8_string String to encode
Returns
string String converted
Definition at line 964 of file functions.lib.php.
dol_strtoupper ($utf8_string)
Convert a string to upper.
Never use strtolower because it does not works with UTF8 strings.
Parameters
string $utf8_string String to encode
Returns
string String converted
Definition at line 975 of file functions.lib.php.
dol_substr ($string, $start, $length, $stringencoding = '', $trunconbytes = 0)
Make a substring.
Works even if mbstring module is not enabled for better compatibility.
Parameters
string $string String to scan
string $start Start position
int $length Length (in nb of characters or nb of bytes depending on trunconbytes param)
string $stringencoding Page code used for input string encoding
int $trunconbytes 1=Length is max of bytes instead of max of characters
Returns
string substring
Definition at line 2869 of file functions.lib.php.
Referenced by Project\create(), BonPrelevement\Create(), dol_print_date(), and dol_trunc().
dol_syslog ($message, $level = LOG_INFO, $ident = 0, $suffixinfilename = '', $restricttologhandler = '', $logcontext = null)
Write log message into outputs.
Possible outputs can be: SYSLOG_HANDLERS = ["mod_syslog_file"] file name is then defined by SYSLOG_FILE SYSLOG_HANDLERS = ["mod_syslog_syslog"] facility is then defined by SYSLOG_FACILITY Warning, syslog functions are bugged on Windows, generating memory protection faults. To solve this, use logging to files instead of syslog (see setup of module). Note: If constant 'SYSLOG_FILE_NO_ERROR' defined, we never output any error message when writing to log fails. Note: You can get log message into html sources by adding parameter &logtohtml=1 (constant MAIN_LOGTOHTML must be set) This function works only if syslog module is enabled. This must not use any call to other function calling dol_syslog (avoid infinite loop).
Parameters
string $message Line to log. ''=Show nothing
int $level Log level On Windows LOG_ERR=4, LOG_WARNING=5, LOG_NOTICE=LOG_INFO=6, LOG_DEBUG=6 si define_syslog_variables ou PHP 5.3+, 7 si dolibarr On Linux LOG_ERR=3, LOG_WARNING=4, LOG_INFO=6, LOG_DEBUG=7
int $ident 1=Increase ident of 1, -1=Decrease ident of 1
string $suffixinfilename When output is a file, append this suffix into default log filename.
string $restricttologhandler Force output of log only to this log handler
array | null $logcontext If defined, an array with extra informations (can be used by some log handlers)
Returns
void
Definition at line 1002 of file functions.lib.php.
References dol_print_date(), and print.
Referenced by DolGeoIP\__construct(), mailing_thirdparties_services_expired\__construct(), DoliDBMysqli\__construct(), DoliDBMssql\__construct(), DoliDBSqlite3\__construct(), CSMSFile\__construct(), DoliDBPgsql\__construct(), DolEditor\__construct(), CMailFile\__construct(), DolibarrApiAccess\__isAllowed(), DolibarrModules\_active(), DolibarrApi\_checkFilters(), MouvementStock\_create(), MouvementStock\_createSubProduct(), CMailFile\_encode_file(), Stats\_getAllByProduct(), Stats\_getAllByYear(), Stats\_getAmountByMonth(), Stats\_getAverageByMonth(), Stats\_getNbByMonth(), Stats\_getNbByYear(), DolibarrModules\_init(), DolibarrModules\_load_tables(), Product\_log_price(), CommActionRapport\_pages(), DolibarrModules\_remove(), RejetPrelevement\_send_email(), DolibarrModules\_unactive(), AccountingAccount\account_activate(), AccountingAccount\account_desactivate(), activateModule(), activateModulesRequiredByCountry(), ContratLigne\active_line(), Ldap\add(), Societe\add_commercial(), Product\add_fournisseur(), SupplierProposal\add_product(), Propal\add_product(), MailmanSpip\add_to_mailman(), MailmanSpip\add_to_spip(), mailing_thirdparties\add_to_target(), mailing_thirdparties_services_expired\add_to_target(), mailing_mailinglist_mymodule_myobject\add_to_target(), mailing_xinputfile\add_to_target(), mailing_pomme\add_to_target(), MailingTargets\add_to_target(), mailing_fraise\add_to_target(), mailing_contacts1\add_to_target(), mailing_advthirdparties\add_to_target_spec(), Categorie\add_type(), Account\add_url_line(), Ldap\addAttribute(), addDocumentModel(), BonPrelevement\AddFacture(), addFileIntoDatabaseIndex(), BonPrelevement\addline(), SupplierProposal\addline(), Account\addline(), Propal\addline(), FactureRec\addline(), Fichinter\addline(), Commande\addline(), Contrat\addline(), CommandeFournisseur\addline(), FactureFournisseur\addline(), ExpenseReport\addline(), Facture\addline(), Expedition\addline_batch(), Holiday\addLogCP(), BonPrelevement\AddNotification(), Localtax\addPayment(), Tva\addPayment(), PaymentExpenseReport\addPaymentToBank(), Paiement\addPaymentToBank(), MultiCurrency\addRateFromDolibarr(), UserGroup\addrights(), User\addrights(), Task\addTimeSpent(), FormAdvTargetEmailing\advMultiselectarraySelllist(), ActionsMyModule\afterPDFCreation(), Categorie\already_exists(), BlockedLog\alreadyUsed(), analyseVarsForSqlAndScriptsInjection(), Holiday\approve(), CommandeFournisseur\approve(), Contrat\array_detail(), Ticket\assignUser(), Commande\availability(), Propal\availability(), barcode_encode(), barcode_encode_genbarcode(), barcode_print(), ActionsMyModule\beforePDFCreation(), ActionsDatapolicy\beforePDFCreation(), DoliDB\begin(), DoliDBMssql\begin(), build_calfile(), Import\build_example_file(), ActionComm\build_exportfile(), Export\build_file(), Export\build_filterQuery(), Categorie\build_path_from_id_categ(), User\build_path_from_id_user(), build_rssfile(), modTcpdfbarcode\buildBarCode(), modPhpbarcode\buildBarCode(), calcul_price_total(), CommonInvoice\calculate_date_lim_reglement(), MouvementStock\calculateBalanceForProductBefore(), MailmanSpip\callMailman(), Commande\cancel(), CommandeFournisseur\Cancel(), Stripe\cardStripe(), EcmDirectory\changeNbOfFiles(), Product\check_barcode(), Societe\check_codeclient(), Societe\check_codefournisseur(), CMailFile\check_server_port(), check_user_password_dolibarr(), check_user_password_empty(), check_user_password_forceuser(), check_user_password_http(), check_user_password_ldap(), check_user_password_openid(), check_value(), checkBanForAccount(), mod_syslog_file\checkConfiguration(), mod_syslog_syslog\checkConfiguration(), checkLoginPassEntity(), AccountingAccount\checkUsage(), Propal\classifyBilled(), Commande\classifyBilled(), Commande\classifyUnBilled(), MailingTargets\clear_target(), User\clearrights(), Product\clone_associations(), Product\clone_fournisseurs(), Product\clone_price(), DoliDBMssql\close(), DoliDBMysqli\close(), DoliDBSqlite3\close(), DoliDBPgsql\close(), Ticket\close(), Societe\codeclient_modifiable(), Societe\codefournisseur_modifiable(), CommandeFournisseur\commande(), DoliDB\commit(), DoliDBMssql\commit(), complete_dictionary_with_modules(), complete_elementList_with_modules(), complete_head_from_modules(), complete_substitutions_array(), completeFileArrayWithDatabaseInfo(), Utils\compressSyslogs(), DoliDBMssql\connect(), DoliDBMysqli\connect(), DoliDBSqlite3\connect(), Ldap\connect_bind(), MailmanSpip\connectSpip(), Form\constructProductListOption(), Categorie\containsObject(), DoliDBSqlite3\convertSQLFromMysql(), BankCateg\create(), Cpaiement\create(), Productbatch\create(), Link\create(), Propalmergepdfproduct\create(), PriceExpression\create(), Ctyperesource\create(), Cchargesociales\create(), Ctypent\create(), Dolresource\create(), CUnits\create(), PriceGlobalVariable\create(), PaymentTerm\create(), RejetPrelevement\create(), ProductStockEntrepot\create(), Cstate\create(), Localtax\create(), Ccountry\create(), AssetType\create(), Livraison\create(), Comment\create(), PriceGlobalVariableUpdater\create(), Tva\create(), Productcustomerprice\create(), Productlot\create(), PaymentDonation\create(), Mailing\create(), PaymentSocialContribution\create(), ExpeditionLineBatch\create(), PaymentExpenseReport\create(), Menubase\create(), PaymentLoan\create(), AdvanceTargetingMailing\create(), AdherentType\create(), Deplacement\create(), LoanSchedule\create(), MultiCurrency\create(), Website\create(), CashControl\create(), Establishment\create(), EcmFiles\create(), Fiscalyear\create(), EcmDirectory\create(), Opensurveysondage\create(), Entrepot\create(), AccountancySystem\create(), Cronjob\create(), CommandeFournisseurDispatch\create(), Task\create(), Bookmark\create(), RemiseCheque\create(), AccountancyCategory\create(), Events\create(), PaiementFourn\create(), BookKeeping\create(), Loan\create(), ExpenseReport\create(), Project\create(), ChargeSociales\create(), Reception\create(), Fichinter\create(), BlockedLogAuthority\create(), DiscountAbsolute\create(), Contact\create(), AccountingAccount\create(), Paiement\create(), Import\create(), Holiday\create(), Expedition\create(), ActionComm\create(), FactureFournisseur\create(), Facture\create(), Categorie\create(), PaymentVarious\create(), Ticket\create(), PaymentSalary\create(), Adherent\create(), Product\create(), Societe\create(), Account\create(), UserGroup\create(), Export\create(), CurrencyRate\create(), BlockedLog\create(), Commande\create(), BonPrelevement\Create(), SupplierProposal\create(), Propal\create(), Contrat\create(), User\create(), CommandeFournisseur\create(), DolibarrModules\create_dirs(), User\create_from_contact(), User\create_from_member(), Societe\create_from_member(), Societe\create_individual(), ExtraFields\create_label(), Livraison\create_line(), createActionComm(), MouvementStock\createBatch(), Fournisseur\CreateCategory(), createContact(), Holiday\createCPusers(), EmailSenderProfile\createFromClone(), EmailCollectorFilter\createFromClone(), EmailCollectorAction\createFromClone(), Asset\createFromClone(), SocieteAccount\createFromClone(), BOM\createFromClone(), Inventory\createFromClone(), EmailCollector\createFromClone(), CompanyPaymentMode\createFromClone(), MyObject\createFromClone(), Cchargesociales\createFromClone(), WebsitePage\createFromClone(), Ctyperesource\createFromClone(), ProductStockEntrepot\createFromClone(), Productlot\createFromClone(), Website\createFromClone(), EcmFiles\createFromClone(), Propal\createFromClone(), Project\createFromClone(), BookKeeping\createFromClone(), Task\createFromClone(), Contrat\createFromClone(), Facture\createFromCurrent(), createInvoice(), createInvoiceFromOrder(), createOrder(), createPayment(), Stripe\createPaymentStripe(), createProductOrService(), createProject(), FactureRec\createRecurringInvoices(), BookKeeping\createStd(), createThirdParty(), createUserFromThirdparty(), Stripe\customerStripe(), DoliDBPgsql\DDLAddField(), DoliDBPgsql\DDLCreateDb(), DoliDBMssql\DDLCreateTable(), DoliDBPgsql\DDLCreateTable(), DoliDBMssql\DDLCreateUser(), DoliDBPgsql\DDLCreateUser(), DoliDBMssql\DDLDescTable(), DoliDBPgsql\DDLDescTable(), DoliDBMssql\DDLDropField(), DoliDBPgsql\DDLDropField(), DoliDBPgsql\DDLInfoTable(), DoliDBMssql\DDLUpdateField(), DoliDBPgsql\DDLUpdateField(), Societe\del_commercial(), Product\del_sousproduit(), MailmanSpip\del_to_mailman(), MailmanSpip\del_to_spip(), Categorie\del_type(), delDocumentModel(), BankCateg\delete(), ChargeSociales\delete(), PriceGlobalVariable\delete(), Fiscalyear\delete(), Loan\delete(), PaymentVarious\delete(), PriceGlobalVariableUpdater\delete(), Cstate\delete(), Establishment\delete(), Productbatch\delete(), DiscountAbsolute\delete(), CompanyBankAccount\delete(), PaymentSalary\delete(), Ctypent\delete(), Localtax\delete(), Events\delete(), Ccountry\delete(), Entrepot\delete(), Comment\delete(), Subscription\delete(), RemiseCheque\delete(), Cchargesociales\delete(), Deplacement\delete(), Cpaiement\delete(), Tva\delete(), Import\delete(), PriceExpression\delete(), MultiCurrency\delete(), PaymentDonation\delete(), PaymentExpenseReport\delete(), PaymentTerm\delete(), LoanSchedule\delete(), PaymentLoan\delete(), Opensurveysondage\delete(), Link\delete(), Ctyperesource\delete(), ProductStockEntrepot\delete(), EcmDirectory\delete(), Propalmergepdfproduct\delete(), Productlot\delete(), PaymentSocialContribution\delete(), AccountancyCategory\delete(), CUnits\delete(), Menubase\delete(), AccountingAccount\delete(), Dolresource\delete(), CommandeFournisseurDispatch\delete(), Mailing\delete(), Task\delete(), AdvanceTargetingMailing\delete(), Website\delete(), Paiement\delete(), Categorie\delete(), Don\delete(), Project\delete(), Ldap\delete(), UserGroup\delete(), FactureRec\delete(), EcmFiles\delete(), Cronjob\delete(), ActionComm\delete(), Export\delete(), Productcustomerprice\delete(), Adherent\delete(), Reception\delete(), Ticket\delete(), CurrencyRate\delete(), Fichinter\delete(), Contact\delete(), Holiday\delete(), Account\delete(), User\delete(), ExpenseReport\delete(), FactureFournisseur\delete(), Product\delete(), Contrat\delete(), Expedition\delete(), BookKeeping\delete(), Societe\delete(), AccountLine\delete(), CommandeFournisseur\delete(), Facture\delete(), SupplierProposal\delete(), ExpeditionLigne\delete(), Propal\delete(), SupplierInvoiceLine\delete(), SupplierProposalLine\delete(), Commande\delete(), CommandeFournisseurLigne\delete(), PropaleLigne\delete(), OrderLine\delete(), FactureLigne\delete(), DolibarrModules\delete_boxes(), Propalmergepdfproduct\delete_by_file(), Propalmergepdfproduct\delete_by_product(), DolibarrModules\delete_const(), DolibarrModules\delete_cronjobs(), DolibarrModules\delete_dirs(), ExtraFields\delete_label(), DolibarrModules\delete_menus(), DolibarrModules\delete_module_parts(), DolibarrModules\delete_permissions(), DolibarrModules\delete_tabs(), Mailing\delete_targets(), AccountLine\delete_urls(), Ldap\deleteAttribute(), BookKeeping\deleteByImportkey(), BookKeeping\deleteByYearAndJournal(), CommonObject\deleteCommon(), AccountancyCategory\deleteCptCat(), deleteFilesIntoDatabaseIndex(), ExpeditionLineBatch\deletefromexp(), FichinterLigne\deleteline(), Contrat\deleteline(), FactureFournisseur\deleteline(), ExpenseReport\deleteline(), Facture\deleteline(), CommonObject\deleteLineCommon(), BookKeeping\deleteMvtNum(), deleteProductOrService(), deleteThirdParty(), Product\delMultiLangs(), Task\delTimeSpent(), Commande\demand_reason(), Propal\demand_reason(), Facture\demande_prelevement(), Facture\demande_prelevement_delete(), CommandeFournisseur\dispatchProduct(), AccountancyCategory\display(), doc_label_pdf_create(), EmailCollector\doCollect(), EmailCollector\doCollectOneCollector(), dol_add_file_process(), AntiVir\dol_avscan_file(), dol_check_secure_access_document(), dol_convert_file(), dol_copy(), dol_delete_dir(), dol_delete_dir_recursive(), dol_delete_file(), dol_dir_list(), dol_ftp_connect(), dol_getIdFromCode(), dol_htmloutput_mesg(), dol_imageResizeOrCrop(), dol_include_once(), dol_json_decode(), dol_json_encode(), dol_meta_create(), dol_microtime_float(), dol_mkdir(), dol_mktime(), dol_move(), dol_move_uploaded_file(), dol_print_date(), dol_print_error(), dol_print_file(), dol_set_user_param(), dol_shutdown(), dol_stringtotime(), dol_uncompress(), dolCopyDir(), dolGetElementUrl(), dolibarr_del_const(), dolibarr_get_const(), dolibarr_install_syslog(), dolibarr_set_const(), dolReplaceInFile(), dolSaveCssFile(), dolSaveHtaccessFile(), dolSaveHtmlHeader(), dolSaveJsFile(), dolSaveManifestJson(), dolSaveMasterFile(), dolSavePageAlias(), dolSavePageContent(), dolSaveReadme(), dolSaveRobotFile(), dolWebsiteOutput(), dolWebsiteReplacementOfLinks(), Asset\doScheduledJob(), MyObject\doScheduledJob(), BOM\doScheduledJob(), DolGraph\draw(), DolGraph\draw_artichow(), DolGraph\draw_jflot(), Utils\dumpDatabase(), FormCompany\effectif_array(), encodedecode_dbpassconf(), envoi_mail(), Utils\executeCLI(), HookManager\executeHooks(), PrestaShopWebservice\executeRequest(), BookKeeping\export_bookkeping(), Website\exportWebSite(), LignePrelevement\fetch(), AccountancySystem\fetch(), CActionComm\fetch(), RemiseCheque\fetch(), AccountingJournal\fetch(), ChargeSociales\fetch(), Bookmark\fetch(), Loan\fetch(), UserGroup\fetch(), DiscountAbsolute\fetch(), BankCateg\fetch(), PriceExpression\fetch(), ModeleBoxes\fetch(), Productbatch\fetch(), BlockedLogAuthority\fetch(), PriceGlobalVariable\fetch(), AccountingAccount\fetch(), WebsitePage\fetch(), PriceGlobalVariableUpdater\fetch(), Ctyperesource\fetch(), Cstate\fetch(), Comment\fetch(), ProductStockEntrepot\fetch(), Cpaiement\fetch(), Cchargesociales\fetch(), Propalmergepdfproduct\fetch(), Ccountry\fetch(), PaymentTerm\fetch(), Subscription\fetch(), Dolresource\fetch(), MultiCurrency\fetch(), PaymentVarious\fetch(), PaymentExpenseReport\fetch(), PaymentLoan\fetch(), AdvanceTargetingMailing\fetch(), PaymentDonation\fetch(), LoanSchedule\fetch(), Mailing\fetch(), PaymentSalary\fetch(), Opensurveysondage\fetch(), Productlot\fetch(), Website\fetch(), Fiscalyear\fetch(), PaymentSocialContribution\fetch(), Localtax\fetch(), Establishment\fetch(), Categorie\fetch(), Task\fetch(), Events\fetch(), User\fetch(), AccountancyCategory\fetch(), Tva\fetch(), CommandeFournisseur\fetch(), CommandeFournisseurDispatch\fetch(), Deplacement\fetch(), Productcustomerprice\fetch(), AssetType\fetch(), Livraison\fetch(), Import\fetch(), BonPrelevement\fetch(), AdherentType\fetch(), Cronjob\fetch(), Menubase\fetch(), Link\fetch(), EcmFiles\fetch(), EcmDirectory\fetch(), RejetPrelevement\fetch(), Holiday\fetch(), Reception\fetch(), FactureRec\fetch(), Entrepot\fetch(), Fichinter\fetch(), Project\fetch(), Ticket\fetch(), Expedition\fetch(), FactureFournisseur\fetch(), MouvementStock\fetch(), ActionComm\fetch(), Contrat\fetch(), BookKeeping\fetch(), Don\fetch(), BlockedLog\fetch(), Contact\fetch(), Export\fetch(), CurrencyRate\fetch(), Account\fetch(), SupplierProposal\fetch(), Adherent\fetch(), Societe\fetch(), Ldap\fetch(), Facture\fetch(), Propal\fetch(), FichinterLigne\fetch(), Commande\fetch(), AccountLine\fetch(), FactureLigneRec\fetch(), Product\fetch(), ContratLigne\fetch(), CommandeFournisseurLigne\fetch(), Productcustomerprice\fetch_all(), Cronjob\fetch_all(), Dolresource\fetch_all(), Productcustomerprice\fetch_all_log(), Dolresource\fetch_all_resources(), Dolresource\fetch_all_used(), AdvanceTargetingMailing\fetch_by_element(), AdvanceTargetingMailing\fetch_by_mailing(), Propalmergepdfproduct\fetch_by_product(), Dolresource\fetch_element_resource(), ExpenseReport\fetch_line_by_project(), CommandeFournisseur\fetch_lines(), FactureRec\fetch_lines(), FactureFournisseur\fetch_lines(), Contrat\fetch_lines(), Livraison\fetch_lines(), ExpenseReport\fetch_lines(), Fichinter\fetch_lines(), Expedition\fetch_lines(), Facture\fetch_lines(), Propal\fetch_lines(), Commande\fetch_lines(), ExtraFields\fetch_name_optionals_label(), ProductFournisseur\fetch_product_fournisseur_price(), Adherent\fetch_subscriptions(), ExpenseReport\fetch_users_approver_expensereport(), Holiday\fetch_users_approver_holiday(), AccountingJournal\fetchAll(), ExpeditionLineBatch\fetchAll(), Ctyperesource\fetchAll(), CUnits\fetchAll(), ProductStockEntrepot\fetchAll(), Link\fetchAll(), WebsitePage\fetchAll(), Website\fetchAll(), EmailCollector\fetchAll(), BOM\fetchAll(), MyObject\fetchAll(), LoanSchedule\fetchAll(), EcmFiles\fetchAll(), Holiday\fetchAll(), Ticket\fetchAll(), CommandeFournisseurDispatch\fetchAll(), BookKeeping\fetchAll(), BOMLine\fetchAll(), User\fetchAll(), BookKeeping\fetchAllBalance(), BookKeeping\fetchAllByAccount(), Comment\fetchAllFor(), BookKeeping\fetchAllPerMvt(), Task\fetchAllTimeSpent(), Holiday\fetchByUser(), ExpeditionLineBatch\fetchFromStock(), Holiday\fetchLog(), BookKeeping\fetchPerMvt(), Facture\fetchPreviousNextSituationInvoice(), Task\fetchTimeSpent(), Holiday\fetchUsers(), Productbatch\find(), ProductFournisseur\find_min_price_product_fournisseur(), PriceExpression\find_title(), Productbatch\findAll(), FormFile\form_attach_new_file(), Form\form_confirm(), form_constantes(), FormCompany\form_prospect_level(), BonPrelevement\generate(), Don\generateDocument(), RemiseCheque\generatePdf(), Donations\get(), Orders\get(), Proposals\get(), Shipments\get(), Projects\get(), Contracts\get(), Interventions\get(), Product\get_barcode(), Product\get_buyprice(), User\get_children(), mod_codecompta_aquarium\get_code(), Societe\get_codeclient(), Societe\get_codefournisseur(), BookKeeping\get_compte_desc(), BookKeeping\get_compte_racine(), get_default_tva(), Project\get_element_list(), EcmDirectory\get_full_arbo(), Categorie\get_full_arbo(), User\get_full_tree(), get_localtax(), get_next_value(), Societe\get_OutstandingBill(), FactureLigne\get_prev_progress(), Facture\get_prev_sits(), get_product_localtax_for_country(), get_product_vat_for_country(), doc_generic_project_odt\get_substitutionarray_project_contacts(), Account\get_url(), AccountancyCategory\getAccountsWithNoCategory(), getActionComm(), ActionComm\getActions(), Stats\getAllByProductEntry(), User\getAllChildIds(), getAllImages(), ProjectStats\getAllProjectByStatus(), ExpenseReportIk\getAllRanges(), ExpenseReportRule\getAllRule(), TaskStats\getAllTaskByStatus(), Stats\getAmountByMonthWithPrevYear(), Paiement\getAmountsArray(), DiscountAbsolute\getAvailableDiscounts(), PaiementFourn\getBillsArray(), Paiement\getBillsArray(), getCategory(), AccountancyCategory\getCats(), AccountancyCategory\getCatsCpts(), Product\getChildsArbo(), Holiday\getConfCP(), getContact(), getContactsForThirdParty(), Holiday\getCPforUser(), AccountancyCategory\getCptBK(), AccountancyCategory\getCptsCat(), SocieteAccount\getCustomerAccount(), PaymentTerm\getDefaultId(), getDocument(), Dolresource\getElementResources(), Establishment\getEstablishment(), ExpenseReportLine\getExpAmount(), getFormeJuridiqueLabel(), getInvoice(), MultiCurrency\getInvoiceRate(), getInvoicesForThirdParty(), Translate\getLabelFromKey(), CommonObjectLine\getLabelOfUnit(), Product\getLabelOfUnit(), getLanguageCodeFromCountryCode(), DolibarrModules\getLastActivationDate(), DolibarrModules\getLastActivationInfo(), SupplierProposal\getLinesArray(), getListActionCommType(), RejetPrelevement\getListInvoices(), BonPrelevement\getListInvoices(), Contrat\getListOfContracts(), getListOfGroups(), InterfaceNotification\getListOfManagedEvents(), getListOfModels(), CommonInvoice\getListOfPayments(), getListOfProductsOrServices(), getListOfThirdParties(), getLocalTaxesFromRate(), ExpenseReportIk\getMaxRangeNumber(), Stats\getNbByMonthWithPrevYear(), Commande\getNbOfShipments(), BookKeeping\getNextNumMvt(), Facture\getNextNumRef(), mod_reception_beryl\getNextValue(), mod_chequereceipt_mint\getNextValue(), mod_bom_standard\getNextValue(), mod_commande_marbre\getNextValue(), mod_expedition_safor\getNextValue(), mod_expensereport_jade\getNextValue(), mod_codeclient_monkey\getNextValue(), mod_contract_serpis\getNextValue(), mod_payment_cicada\getNextValue(), mod_supplier_payment_bronan\getNextValue(), mod_ticket_simple\getNextValue(), mod_holiday_madonna\getNextValue(), mod_project_simple\getNextValue(), mod_task_simple\getNextValue(), mod_propale_marbre\getNextValue(), mod_supplier_proposal_marbre\getNextValue(), mod_livraison_jade\getNextValue(), mod_facture_mars\getNextValue(), mod_facture_fournisseur_cactus\getNextValue(), mod_facture_terre\getNextValue(), Notify\getNotificationsArray(), Categories\getObjects(), Categorie\getObjectsInCateg(), getOrder(), getOrdersForThirdParty(), Societe\getOutstandingBills(), Societe\getOutstandingOrders(), Societe\getOutstandingProposals(), Stripe\getPaymentIntent(), GETPOST(), getProductOrService(), getProductsForCategory(), getProject(), ExpenseReportIk\getRangesByCategory(), MultiCurrency\getRate(), Ldap\getRecords(), Dolistore\getRemoteCategories(), Dolistore\getRemoteProducts(), UserGroup\getrights(), CommonInvoice\getSommePaiement(), ChargeSociales\getSommePaiement(), Tva\getSommePaiement(), getSourceDocRef(), getState(), Stripe\getStripeAccount(), DiscountAbsolute\getSumCreditNotesUsed(), AccountancyCategory\getSumDebitCredit(), DiscountAbsolute\getSumDepositsUsed(), DiscountAbsolute\getSumFromThisCreditNotesNotUsed(), Task\getSummaryOfTimeSpent(), Task\getSumOfAmount(), Loan\getSumPayment(), ExpenseReport\getSumPayments(), getSupplierInvoice(), getSupplierInvoicesForThirdParty(), Task\getTasksArray(), ExpenseReportIk\getTaxCategories(), getTaxesFromId(), getThirdParty(), SocieteAccount\getThirdPartyID(), ProjectStats\getTransformRateByMonthWithPrevYear(), getURLContent(), getUser(), Task\getUserRolesForProjectsOrTasks(), ProjectStats\getWeightedAmountByMonthWithPrevYear(), Task\hasChildren(), hash_call(), Task\hasTimeSpent(), ImportCsv\import_insert(), ImportXlsx\import_insert(), ImportCsv\import_open_file(), ImportXlsx\import_open_file(), Website\importWebSite(), Login\index(), BankAccounts\index(), Documents\index(), Tasks\index(), Fiscalyear\info(), Establishment\info(), Deplacement\info(), Entrepot\info(), AccountingAccount\info(), Loan\info(), ChargeSociales\info(), PaymentVarious\info(), PaymentSalary\info(), PaymentExpenseReport\info(), Tva\info(), Cronjob\info(), Don\info(), Paiement\info(), ActionComm\info(), Adherent\info(), Reception\initAsSpecimen(), Expedition\initAsSpecimen(), Categorie\initAsSpecimen(), CommandeFournisseur\initAsSpecimen(), Commande\initAsSpecimen(), HookManager\initHooks(), FichinterLigne\insert(), AccountLine\insert(), ExpeditionLigne\insert(), ExpenseReportLine\insert(), SupplierProposalLine\insert(), SupplierInvoiceLine\insert(), ContratLigne\insert(), CommandeFournisseurLigne\insert(), PropaleLigne\insert(), OrderLine\insert(), FactureLigne\insert(), DolibarrModules\insert_boxes(), DolibarrModules\insert_const(), DolibarrModules\insert_cronjobs(), DolibarrModules\insert_dirs(), DolibarrModules\insert_menus(), DolibarrModules\insert_module_parts(), DolibarrModules\insert_permissions(), DolibarrModules\insert_tabs(), Propal\InvoiceArrayList(), Facture\is_last_in_cycle(), CommonObject\isExistingObject(), left_menu(), Lettering\letteringThirdparty(), DiscountAbsolute\link_to_invoice(), FormFile\list_of_autoecmfiles(), PriceExpression\list_price_expression(), ProductFournisseur\list_product_fournisseur_price(), Facture\list_qualified_avoir_invoices(), FactureFournisseur\list_qualified_avoir_supplier_invoices(), Facture\list_replacable_invoices(), FactureFournisseur\list_replacable_supplier_invoices(), AssetType\listAssetForAssetType(), InfoBox\listBoxes(), CActionComm\liste_array(), ModeleExports\liste_modeles(), ModeleImports\liste_modeles(), PriceGlobalVariable\listGlobalVariables(), UserGroup\listGroupsForUser(), AdherentType\listMembersForMemberType(), listOfSessions(), Deplacement\listOfTypes(), ExpenseReport\listOfTypes(), PriceGlobalVariableUpdater\listPendingUpdaters(), ProductFournisseur\listProductFournisseurPriceLog(), PriceGlobalVariableUpdater\listUpdaters(), UserGroup\listUsersForGroup(), CommandeFournisseur\Livraison(), llxFooter(), llxFooterVierge(), Translate\load(), Import\load_arrays(), Export\load_arrays(), Form\load_cache_availability(), Dolresource\load_cache_code_type_resource(), Form\load_cache_conditions_paiements(), Form\load_cache_types_fees(), Form\load_cache_types_paiements(), Form\load_cache_vatrates(), EcmDirectory\load_motherof(), Categorie\load_motherof(), Contact\load_ref_elements(), Product\load_stats_commande(), Product\load_stock(), Product\loadBatchInfo(), box_ficheinter\loadBox(), box_birthdays\loadBox(), box_actions\loadBox(), box_birthdays_members\loadBox(), box_clients\loadBox(), box_goodcustomers\loadBox(), box_prospect\loadBox(), box_comptes\loadBox(), Ticket\loadCacheCategoriesTickets(), Translate\loadCacheCurrencies(), Ticket\loadCacheMsgsTicket(), Ticket\loadCacheSeveritiesTickets(), Ticket\loadCacheTypesTickets(), Commande\loadExpeditions(), Translate\loadFromDatabase(), FormProduct\loadLotStock(), User\loadParentOf(), CommandeFournisseur\loadReceptions(), Project\loadTimeSpent(), FormProduct\loadWarehouses(), makesalt(), Ticket\markAsRead(), Menubase\menuLeftCharger(), Menubase\menuLoad(), Thirdparties\merge(), Ticket\messageSend(), Ldap\modify(), FormAdvTargetEmailing\multiselectCategories(), FormAdvTargetEmailing\multiselectCivility(), FormAdvTargetEmailing\multiselectCountry(), FormAdvTargetEmailing\multiselectProspectionStatus(), BonPrelevement\NbFactureAPrelever(), Facture\newCycle(), num_open_day(), ExpenseReport\offsetAlreadyGiven(), ExportTsv\open_file(), ExportCsv\open_file(), ExportExcel2007new\open_file(), ExportExcel\open_file(), EmailCollector\overwritePropertiesOfObject(), RssParser\parser(), pdf_getFormat(), ExpenseReport\periode_existe(), print_paybox_redirect(), print_paypal_redirect(), print_titre(), printing_printipp\printFile(), PriceGlobalVariableUpdater\process(), Utils\purgeFiles(), purgeSessions(), DoliDBMysqli\query(), DoliDBMssql\query(), DoliDBSqlite3\query(), DoliDBPgsql\query(), AdvanceTargetingMailing\query_contact(), AdvanceTargetingMailing\query_thirdparty(), rebuild_merge_pdf(), ExpenseReport\recalculer(), Categorie\rechercher(), EcmDirectory\refreshcachenboffile(), CommandeFournisseur\refuse(), Paiement\reject(), Bookmark\remove(), Project\remove_element(), ProductFournisseur\remove_fournisseur(), ProductFournisseur\remove_product_fournisseur_price(), RemiseCheque\removeCheck(), User\RemoveFromGroup(), Ldap\rename(), Contrat\reopen(), SupplierProposal\reopen(), Reception\reOpen(), Expedition\reOpen(), Propal\reopen(), Societe\replaceThirdparty(), Cronjob\reprogram_jobs(), Mailing\reset_targets_status(), Adherent\resiliate(), DoliDB\rollback(), DoliDBMssql\rollback(), Cronjob\run_jobs(), run_sql(), Interfaces\run_triggers(), InterfaceMailmanSpipsynchro\runTrigger(), InterfaceActionsBlockedLog\runTrigger(), InterfaceLdapsynchro\runTrigger(), InterfaceWorkflowManager\runTrigger(), InterfaceLogevents\runTrigger(), InterfaceActionsAuto\runTrigger(), InterfaceNotification\runTrigger(), InterfaceMyModuleTriggers\runTrigger(), InterfaceIFTTT\runTrigger(), InterfaceTicketEmail\runTrigger(), InterfaceStripe\runTrigger(), InfoBox\saveboxorder(), Ldap\search(), Ticket\searchContactByEmail(), Ticket\searchSocidByEmail(), FormAccounting\select_account(), BookKeeping\select_account(), FormAccounting\select_accounting_category(), Form\select_address(), Form\select_all_categories(), FormAccounting\select_auxaccount(), FormAccounting\select_bookkeeping_importkey(), FormOther\select_categories(), FormCompany\select_civility(), Form\select_comptes(), Form\select_conditions_paiements(), FormContract\select_contract(), Form\select_country(), DoliDBMysqli\select_db(), DoliDBSqlite3\select_db(), FormOther\select_dictionary(), Form\select_dolgroups(), Form\select_dolusers(), FormOther\select_ecotaxes(), FormProjets\select_element(), Form\select_incoterms(), FormIntervention\select_interventions(), FormAccounting\select_journal(), FormCompany\select_juridicalstatus(), Form\select_product_fourn_price(), Form\select_produits_fournisseurs_list(), Form\select_produits_list(), FormCompany\select_region(), Form\select_remises(), FormOther\select_revenue_stamp(), FormCompany\select_state(), Form\select_thirdparty_list(), Form\select_type_fees(), FormSocialContrib\select_type_socialcontrib(), Form\select_types_paiements(), FormResource\select_types_resource(), FormAdvTargetEmailing\selectAdvtargetemailingTemplate(), Form\selectAvailabilityDelay(), FormOther\selectColor(), Form\selectcontacts(), Form\selectEstablishments(), FormTicket\selectGroupTickets(), FormOrder\selectInputMethod(), FormProduct\selectLotStock(), FormProjets\selectOpportunityStatus(), FormPropal\selectProposalStatus(), FormTicket\selectSeveritiesTickets(), Form\selectShippingMethod(), Form\selectSituationInvoices(), FormWebsite\selectTypeOfContainer(), FormTicket\selectTypesTickets(), FormProduct\selectWarehouses(), FormAccounting\selectyear_accountancy_bookkepping(), Notify\send(), Adherent\send_an_email(), User\send_password(), ActionComm\sendEmailsReminder(), CSMSFile\sendfile(), CMailFile\sendfile(), Adherent\sendReminderForExpiredSubscription(), Ticket\sendTicketMessageByEmail(), Propal\set_availability(), ExpenseReport\set_cancel(), Facture\set_canceled(), BonPrelevement\set_credite(), RemiseCheque\set_date(), Propal\set_date(), Commande\set_date(), Fichinter\set_date_delivery(), Livraison\set_date_livraison(), Reception\set_date_livraison(), SupplierProposal\set_date_livraison(), Expedition\set_date_livraison(), Propal\set_date_livraison(), CommandeFournisseur\set_date_livraison(), Commande\set_date_livraison(), Propal\set_demand_reason(), Fichinter\set_description(), Propal\set_echeance(), CommandeFournisseur\set_id_projet(), BonPrelevement\set_infocredit(), BonPrelevement\set_infotrans(), RemiseCheque\set_number(), ExpenseReport\set_paid(), FactureFournisseur\set_paid(), Facture\set_paid(), Societe\set_parent(), Facture\set_ref_client(), Propal\set_ref_client(), Commande\set_ref_client(), Commande\set_remise(), Facture\set_remise(), Propal\set_remise_absolue(), Commande\set_remise_absolue(), Facture\set_remise_absolue(), Societe\set_remise_client(), Propal\set_remise_percent(), Societe\set_remise_supplier(), Commande\set_reopen(), ExpenseReport\set_save_from_refuse(), FactureFournisseur\set_unpaid(), ExpenseReport\set_unpaid(), Facture\set_unpaid(), ExpenseReport\setApproved(), CompanyBankAccount\setAsDefault(), CompanyPaymentMode\setAsDefault(), FactureRec\setAutoValidate(), Societe\setCategories(), Project\setClose(), Reception\setClosed(), Expedition\setClosed(), Ticket\setContract(), Ticket\setCustomer(), ExpenseReport\setDeny(), Fichinter\setDraft(), Commande\setDraft(), BOM\setDraft(), FactureFournisseur\setDraft(), Reception\setDraft(), SupplierProposal\setDraft(), Facture\setDraft(), Propal\setDraft(), setEventMessages(), Facture\setFinal(), FactureRec\setFrequencyAndUnit(), FactureRec\setGeneratePdf(), User\SetInGroup(), FactureRec\setMaxPeriod(), FactureRec\setModelPdf(), Product\setMultiLangs(), Categorie\setMultiLangs(), Societe\setMysoc(), FactureRec\setNextDate(), BlockedLog\setObjectData(), Adherent\setPassword(), User\setPassword(), Productcustomerprice\setPriceOnAffiliateThirdparty(), Ticket\setProgression(), Ticket\setProject(), Facture\setRetainedWarranty(), Facture\setRetainedWarrantyDateLimit(), User\setstatus(), Contact\setstatus(), CommandeFournisseur\setStatus(), ProductFournisseur\setSupplierPriceExpression(), Adherent\setThirdPartyId(), Adherent\setUserId(), setUserPassword(), Fichinter\setValid(), Project\setValid(), ExpenseReport\setValidate(), Conf\setValues(), show_actions_done(), show_contacts(), FormSms\show_form(), show_list_sending_receive(), ModeleBoxes\showBox(), FormFile\showdocuments(), ExtraFields\showInputField(), ExtraFields\showOutputField(), BonPrelevement\SommeAPrelever(), Adherent\subscriptionComplementaryActions(), MultiCurrency\syncRates(), tax_by_rate(), tax_by_thirdparty(), thirdparty_doc_create(), top_htmlhead(), BookKeeping\transformTransaction(), tree_recur(), FormCompany\typent_array(), unActivateModule(), DiscountAbsolute\unlink_invoice(), PaymentSalary\update(), PaymentVarious\update(), BankCateg\update(), Link\update(), Localtax\update(), Mailing\update(), AssetType\update(), Tva\update(), Fiscalyear\update(), AdherentType\update(), PriceGlobalVariable\update(), Establishment\update(), Deplacement\update(), Bookmark\update(), Events\update(), Productbatch\update(), PriceGlobalVariableUpdater\update(), Cstate\update(), Entrepot\update(), Ctypent\update(), Ccountry\update(), Comment\update(), Cpaiement\update(), Cchargesociales\update(), EcmDirectory\update(), Subscription\update(), Dolresource\update(), Menubase\update(), BlockedLogAuthority\update(), PriceExpression\update(), PaymentExpenseReport\update(), PaymentDonation\update(), PaymentLoan\update(), PaymentTerm\update(), LoanSchedule\update(), Productlot\update(), Opensurveysondage\update(), Ctyperesource\update(), PaymentSocialContribution\update(), Project\update(), AccountancyCategory\update(), Propalmergepdfproduct\update(), ProductStockEntrepot\update(), ChargeSociales\update(), CUnits\update(), Contact\update(), FactureRec\update(), CommandeFournisseurDispatch\update(), AccountingAccount\update(), Loan\update(), Fichinter\update(), Task\update(), Website\update(), AdvanceTargetingMailing\update(), ExpenseReport\update(), Categorie\update(), Don\update(), Adherent\update(), EcmFiles\update(), Cronjob\update(), Productcustomerprice\update(), Ldap\update(), ExtraFields\update(), Account\update(), Ticket\update(), UserGroup\update(), Reception\update(), Product\update(), FactureFournisseur\update(), Societe\update(), Holiday\update(), CurrencyRate\update(), ActionComm\update(), Expedition\update(), BookKeeping\update(), Contrat\update(), User\update(), Propal\update(), FichinterLigne\update(), Facture\update(), FactureLigneRec\update(), AccountLine\update(), ExpenseReportLine\update(), ExpeditionLigne\update(), ContratLigne\update(), SupplierInvoiceLine\update(), Commande\update(), SupplierProposalLine\update(), CommandeFournisseurLigne\update(), PropaleLigne\update(), OrderLine\update(), FactureLigne\update(), Account\update_bban(), ProductFournisseur\update_buyprice(), User\update_clicktodial(), AccountLine\update_conciliation(), Paiement\update_date(), Project\update_element(), Dolresource\update_element_resource(), Adherent\update_end_date(), PaymentLoan\update_fk_bank(), PaymentDonation\update_fk_bank(), PaymentSocialContribution\update_fk_bank(), PaymentExpenseReport\update_fk_bank(), Paiement\update_fk_bank(), ExtraFields\update_label(), User\update_last_login_date(), User\update_ldap2dolibarr(), MailingTargets\update_nb(), PriceGlobalVariableUpdater\update_next_update(), Paiement\update_num(), Contact\update_perso(), PriceGlobalVariableUpdater\update_status(), Contrat\update_statut(), FichinterLigne\update_total(), ContratLigne\update_total(), SupplierInvoiceLine\update_total(), SupplierProposalLine\update_total(), PropaleLigne\update_total(), OrderLine\update_total(), FactureLigne\update_total(), AccountancyCategory\updateAccAcc(), updateActionComm(), RemiseCheque\updateAmount(), Ldap\updateAttribute(), BookKeeping\updateByMvt(), Holiday\updateConfCP(), updateContact(), updateInvoice(), Lettering\updateLettering(), SupplierProposal\updateline(), Propal\updateline(), FactureRec\updateline(), Contrat\updateline(), FactureFournisseur\updateline(), CommandeFournisseur\updateline(), Facture\updateline(), Commande\updateline(), SupplierProposal\updateOrCreatePriceFournisseur(), updateOrder(), Product\updatePrice(), updateProductOrService(), Holiday\updateSoldeCP(), updateThirdParty(), Task\updateTimeSpent(), Societe\useLocalTax(), Societe\useNPR(), Societe\useRevenueStamp(), CashControl\valid(), Commande\valid(), Livraison\valid(), Mailing\valid(), Reception\valid(), CommandeFournisseur\valid(), BOM\valid(), Expedition\valid(), SupplierProposal\valid(), Propal\valid(), RemiseCheque\validate(), Contrat\validate(), Holiday\validate(), FactureFournisseur\validate(), Adherent\validate(), Facture\validate(), Paiement\valide(), validOrder(), mod_contract_olive\verif(), mod_codeclient_leopard\verif(), mod_codeproduct_leopard\verif(), mod_codeclient_monkey\verif(), mod_barcode_product_standard\verif(), mod_codecompta_aquarium\verif(), mod_codeproduct_elephant\verif(), mod_codeclient_elephant\verif(), mod_codeclient_monkey\verif_dispo(), mod_barcode_product_standard\verif_syntax(), Holiday\verifNbUsers(), Ticket\verify(), vignette(), html_cerfafr\write_file(), pdf_paiement\write_file(), doc_generic_odt\write_file(), pdf_cyan\write_file(), doc_generic_contract_odt\write_file(), doc_generic_reception_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_shipment_odt\write_file(), doc_generic_order_odt\write_file(), pdf_azur\write_file(), doc_generic_user_odt\write_file(), doc_generic_product_odt\write_file(), doc_generic_stock_odt\write_file(), doc_generic_usergroup_odt\write_file(), doc_generic_proposal_odt\write_file(), pdf_crabe\write_file(), doc_generic_supplier_proposal_odt\write_file(), doc_generic_task_odt\write_file(), doc_generic_project_odt\write_file(), CMailFile\write_files(), CMailFile\write_images(), CMailFile\write_mimeheaders(), CMailFile\write_smtpheaders(), and modTcpdfbarcode\writeBarCode().
dol_textishtml ($msg, $option = 0)
Return if a text is a html content.
Parameters
string $msg Content to check
int $option 0=Full detection, 1=Fast check
Returns
boolean true/false
See also
dol_concatdesc()
Definition at line 5765 of file functions.lib.php.
Referenced by CMailFile\__construct(), ajax_dialog(), dol_concatdesc(), dol_htmlentitiesbr(), dol_nboflines_bis(), dol_trunc(), dolGetFirstLineOfText(), envoi_mail(), Mailing\fetch(), FormMail\get_form(), ActionComm\getNomUrl(), make_substitutions(), Adherent\makeSubstitution(), pdf_getlinedesc(), Adherent\send_an_email(), FormTicket\showMessageForm(), and ActionsTicket\viewTicketOriginalMessage().
dol_trunc ($string, $size = 40, $trunc = 'right', $stringencoding = 'UTF-8', $nodot = 0, $display = 0)
Truncate a string to a particular length adding '...' if string larger than length.
If length = max length+1, we do no truncate to avoid having just 1 char replaced with '...'. MAIN_DISABLE_TRUNC=1 can disable all truncings
Parameters
string $string String to truncate
int $size Max string size visible (excluding ...). 0 for no limit. WARNING: Final string size can have 3 more chars (if we added ..., or if size was max+1 or max+2 or max+3 so it does not worse to replace with ...)
string $trunc Where to trunc: right, left, middle (size must be a 2 power), wrap
string $stringencoding Tell what is source string encoding
int $nodot Truncation do not add ... after truncation. So it's an exact truncation.
int $display Trunc is used to display data and can be changed for small screen. TODO Remove this param (must be dealt with CSS)
Returns
string Truncated string. WARNING: length is never higher than $size if $nodot is set, but can be 3 chars higher otherwise.
Definition at line 2915 of file functions.lib.php.
References dol_string_nohtmltag(), dol_strlen(), dol_substr(), and dol_textishtml().
Referenced by Product\_get_stats(), CommActionRapport\_pages(), FormAdvTargetEmailing\advMultiselectarraySelllist(), BordereauChequeBlochet\Body(), Export\build_filterField(), WebsitePage\create(), Events\create(), ActionComm\create(), Stripe\createPaymentStripe(), dol_print_email(), dol_print_url(), BonPrelevement\EnregDestinataireSEPA(), AccountancyExport\exportBob50(), mailing_fraise\formFilter(), mailing_advthirdparties\formFilter(), mailing_thirdparties\formFilter(), Translate\get_available_languages(), getCommonSubstitutionArray(), CommonObject\getFullName(), getListOfModels(), AssetType\getNomUrl(), AdherentType\getNomUrl(), Loan\getNomUrl(), EcmDirectory\getNomUrl(), ChargeSociales\getNomUrl(), PaymentLoan\getNomUrl(), PaymentDonation\getNomUrl(), Task\getNomUrl(), PaymentExpenseReport\getNomUrl(), PaymentSocialContribution\getNomUrl(), Project\getNomUrl(), Contact\getNomUrl(), Facture\getNomUrl(), ActionComm\getNomUrl(), ExpenseReport\getNomUrl(), Societe\getNomUrl(), Adherent\getNomUrl(), FactureFournisseur\getNomUrl(), User\getNomUrl(), Product\getNomUrl(), Stripe\getPaymentIntent(), getSourceDocRef(), FormFile\list_of_autoecmfiles(), FormFile\list_of_documents(), box_ficheinter\loadBox(), box_graph_product_distribution\loadBox(), ActionsCardProduct\LoadListDatas(), FormAdvTargetEmailing\multiselectCountry(), print_left_auguria_menu(), print_left_eldy_menu(), FormAccounting\select_account(), FormAccounting\select_accounting_category(), Form\select_all_categories(), FormContract\select_contract(), Form\select_country(), FormIntervention\select_interventions(), Form\select_produits_fournisseurs_list(), FormProjets\select_projects_list(), Form\select_remises(), Form\select_types_paiements(), FormResource\select_types_resource(), FormTicket\selectGroupTickets(), FormTicket\selectSeveritiesTickets(), FormProjets\selectTasks(), FormTicket\selectTypesTickets(), show_actions_done(), ModeleBoxes\showBox(), FormFile\showdocuments(), ExtraFields\showInputField(), ExtraFields\showOutputField(), Societe\thirdparty_and_contact_email_array(), Societe\thirdparty_and_contact_phone_array(), top_menu_user(), Translate\trans(), AccountancyExport\trunc(), CompanyBankAccount\update(), WebsitePage\update(), and pdf_beluga\write_file().
dol_user_country ()
Return country code for current user.
If software is used inside a local network, detection may fails (we need a public ip)
Returns
string Country code (fr, es, it, us, ...)
Definition at line 2712 of file functions.lib.php.
References getUserRemoteIP().
Referenced by llxFooterVierge().
dol_validElement ($element)
Return if var element is ok.
Parameters
string $element Variable to check
Returns
boolean Return true of variable is not empty
Definition at line 6856 of file functions.lib.php.
dolExplodeIntoArray ($string, $delimiter = ';', $kv = '=')
Split a string with 2 keys into key array.
For example: "A=1;B=2;C=2" is exploded into array('A'=>1,'B'=>2,'C'=>3)
Parameters
string $string String to explode
string $delimiter Delimiter between each couple of data
string $kv Delimiter between key and value
Returns
array Array of data exploded
Definition at line 7440 of file functions.lib.php.
Referenced by EmailCollector\doCollectOneCollector(), and EmailCollector\overwritePropertiesOfObject().
dolGetBadge ($label, $html = '', $type = 'primary', $mode = '', $url = '', $params = array())
Function dolGetBadge.
Parameters
string $label label of badge no html : use in alt attribute for accessibility
string $html optional : label of badge with html
string $type type of badge : Primary Secondary Success Danger Warning Info Light Dark status0 status1 status2 status3 status4 status5 status6 status7 status8 status9
string $mode default '' , pill, dot
string $url the url for link
array $params various params for future : recommended rather than adding more fuction arguments
Returns
string Html badge
Definition at line 8012 of file functions.lib.php.
dolGetButtonAction ($label, $html = '', $actionType = 'default', $url = '', $id = '', $userRight = 1, $params = array())
Function dolGetButtonAction.
Parameters
string $label label of button no html : use in alt attribute for accessibility $html is not empty
string $html optional : content with html
string $actionType default, delete, danger
string $url the url for link
string $id attribute id of button
int $userRight user action right
array $params various params for future : recommended rather than adding more function arguments
Returns
string html button
Definition at line 8158 of file functions.lib.php.
dolGetButtonTitle ($label, $helpText = '', $iconClass = 'fa fa-file', $url = '', $id = '', $status = 1, $params = array())
Function dolGetButtonTitle : this kind of buttons are used in title in list.
Parameters
string $label label of button
string $helpText optional : content for help tooltip
string $iconClass class for icon element
string $url the url for link
string $id attribute id of button
int $status 0 no user rights, 1 active, -1 Feature Disabled, -2 disable Other reason use helpText as tooltip
array $params various params for future : recommended rather than adding more function arguments
Returns
string html button
Definition at line 8233 of file functions.lib.php.
Referenced by show_contacts(), show_projects(), and FormActions\showactions().
dolGetCountryCodeFromIp ($ip)
Return a country code from IP.
Empty string if not found.
Parameters
string $ip IP
Returns
string Country code ('us', 'fr', ...)
Definition at line 2685 of file functions.lib.php.
Referenced by dol_print_ip().
dolGetFirstLastname ($firstname, $lastname, $nameorder = -1)
Return firstname and lastname in correct order.
Parameters
string $firstname Firstname
string $lastname Lastname
int $nameorder -1=Auto, 0=Lastname+Firstname, 1=Firstname+Lastname, 2=Firstname, 3=Firstname if defined else lastname
Returns
string Firstname + lastname or Lastname + firstname
Definition at line 6340 of file functions.lib.php.
Referenced by pdf_standard\_pagehead(), ActionComm\build_exportfile(), Societe\contact_array(), Societe\contact_get_property(), Societe\contact_property_array(), Tickets\getCommon(), CommonObject\getFullName(), mod_expensereport_jade\getNextValue(), ExpenseReportRule\getUserName(), llxFooterVierge(), Ticket\newMessage(), InterfaceTicketEmail\runTrigger(), FormAccounting\select_auxaccount(), FormOther\select_salesrepresentatives(), Notify\send(), Ticket\sendLogByEmail(), BonPrelevement\set_infotrans(), ExpenseReport\update(), and User\user_get_property().
dolGetFirstLineOfText ($text, $nboflines = 1, $charset = 'UTF-8')
Return first line of text.
Cut will depends if content is HTML or not.
Parameters
string $text Input text
int $nboflines Nb of lines to get (default is 1 = first line only)
string $charset Charset of $text string (UTF-8 by default)
Returns
string Output text
See also
dol_nboflines_bis(), dol_string_nohtmltag(), dol_escape_htmltag()
Definition at line 5496 of file functions.lib.php.
References dol_textishtml().
Referenced by EmailCollector\doCollectOneCollector().
dolGetStatus ($statusLabel = '', $statusLabelShort = '', $html = '', $statusType = 'status0', $displayMode = 0, $url = '', $params = array())
Function dolGetStatus.
Parameters
string $statusLabel Label of badge no html : use in alt attribute for accessibility
string $statusLabelShort Short label of badge no html
string $html Optional : label of badge with html
string $statusType status0 status1 status2 status3 status4 status5 status6 status7 status8 status9 : image name or badge name
int $displayMode 0=Long label, 1=Short label, 2=Picto + Short label, 3=Picto, 4=Picto + Long label, 5=Short label + Picto, 6=Long label + Picto
string $url The url for link
array $params Various params for future : recommended rather than adding more function arguments
Returns
string Html status string
Definition at line 8071 of file functions.lib.php.
Referenced by CommonInvoice\LibStatut(), Propal\LibStatut(), Commande\LibStatut(), and Product\LibStatut().
fieldLabel ($langkey, $fieldkey, $fieldrequired = 0)
Show a string with the label tag dedicated to the HTML edit field.
Parameters
string $langkey Translation key
string $fieldkey Key of the html select field the text refers to
int $fieldrequired 1=Field is mandatory
Returns
string
Deprecated:
Form::editfieldkey
Definition at line 1585 of file functions.lib.php.
get_date_range ($date_start, $date_end, $format = '', $outputlangs = '', $withparenthesis = 1)
Format output for start and end date.
Parameters
int $date_start Start date
int $date_end End date
string $format Output format
Translate $outputlangs Output language
integer $withparenthesis 1=Add parenthesis, 0=non parenthesis
Returns
string String
Definition at line 6308 of file functions.lib.php.
References dol_print_date().
Referenced by print_date_range().
get_default_localtax ($thirdparty_seller, $thirdparty_buyer, $local, $idprod = 0)
Function that return localtax of a product line (according to seller, buyer and product vat rate) Si vendeur non assujeti a TVA, TVA par defaut=0.
Fin de regle. Si le (pays vendeur = pays acheteur) alors TVA par defaut=TVA du produit vendu. Fin de regle. Sinon TVA proposee par defaut=0. Fin de regle.
Parameters
Societe $thirdparty_seller Thirdparty seller
Societe $thirdparty_buyer Thirdparty buyer
int $local Localtax to process (1 or 2)
int $idprod Id product
Returns
integer localtax, -1 si ne peut etre determine
See also
get_default_tva(), get_default_npr()
Definition at line 5191 of file functions.lib.php.
References get_product_localtax_for_country().
get_default_npr (Societe $thirdparty_seller, Societe $thirdparty_buyer, $idprod = 0, $idprodfournprice = 0)
Fonction qui renvoie si tva doit etre tva percue recuperable.
Parameters
Societe $thirdparty_seller Thirdparty seller
Societe $thirdparty_buyer Thirdparty buyer
int $idprod Id product
int $idprodfournprice Id supplier price for product
Returns
float 0 or 1
See also
get_default_tva(), get_default_localtax()
Definition at line 5154 of file functions.lib.php.
Referenced by SupplierProposal\add_product(), Propal\add_product(), Commande\add_product(), Product\getSellPrice(), and Form\load_tva().
get_default_tva (Societe $thirdparty_seller, Societe $thirdparty_buyer, $idprod = 0, $idprodfournprice = 0)
Function that return vat rate of a product line (according to seller, buyer and product vat rate) Si vendeur non assujeti a TVA, TVA par defaut=0.
Fin de regle. Si le (pays vendeur = pays acheteur) alors TVA par defaut=TVA du produit vendu. Fin de regle. Si (vendeur et acheteur dans Communaute europeenne) et (bien vendu = moyen de transports neuf comme auto, bateau, avion) alors TVA par defaut=0 (La TVA doit etre paye par acheteur au centre d'impots de son pays et non au vendeur). Fin de regle. Si (vendeur et acheteur dans Communaute europeenne) et (acheteur = particulier ou entreprise sans num TVA intra) alors TVA par defaut=TVA du produit vendu. Fin de regle Si (vendeur et acheteur dans Communaute europeenne) et (acheteur = entreprise avec num TVA) intra alors TVA par defaut=0. Fin de regle Sinon TVA proposee par defaut=0. Fin de regle.
Parameters
Societe $thirdparty_seller Objet societe vendeuse
Societe $thirdparty_buyer Objet societe acheteuse
int $idprod Id product
int $idprodfournprice Id product_fournisseur_price (for supplier order/invoice)
Returns
float|string Vat rate to use with format 5.0 or '5.0 (XXX)', -1 if we can't guess it
See also
get_default_npr(), get_default_localtax()
Definition at line 5067 of file functions.lib.php.
References dol_syslog(), get_product_vat_for_country(), Societe\isACompany(), and isInEEC().
Referenced by SupplierProposal\add_product(), Propal\add_product(), Commande\add_product(), Product\getSellPrice(), Form\load_tva(), Adherent\subscriptionComplementaryActions(), and doc_generic_project_odt\write_file().
get_exdir ($num, $level, $alpha, $withoutslash, $object, $modulepart)
Return a path to have a the directory according to object where files are stored.
New usage: $conf->module->multidir_output[$object->entity].'/'.get_exdir(0, 0, 0, 1, $object, $modulepart) or: $conf->module->dir_output.'/'.get_exdir(0, 0, 0, 1, $object, $modulepart) if multidir_output not defined. Example our with new usage: $object is invoice -> 'INYYMM-ABCD' Example our with old usage: '015' with level 3->"0/1/5/", '015' with level 1->"5/", 'ABC-1' with level 3 ->"0/0/1/"
Parameters
string $num Id of object (deprecated, $object will be used in future)
int $level Level of subdirs to return (1, 2 or 3 levels). (deprecated, global option will be used in future)
int $alpha 0=Keep number only to forge path, 1=Use alpha part afer the - (By default, use 0). (deprecated, global option will be used in future)
int $withoutslash 0=With slash at end (except if '/', we return ''), 1=without slash at end
Object $object Object
string $modulepart Type of object ('invoice_supplier, 'donation', 'invoice', ...')
Returns
string Dir to use ending. Example '' or '1/' or '1/2/'
Definition at line 5276 of file functions.lib.php.
Referenced by FileUpload\__construct(), pdf_standard\Add_PDF_card(), Categorie\add_photo(), Product\add_photo(), asset_prepare_head(), FactureFournisseur\delete(), dol_banner_tab(), donation_prepare_head(), facturefourn_prepare_head(), CommonDocGenerator\get_substitutionarray_user(), getCategory(), FormFile\getDocumentsLink(), Documents\getDocumentsListByElement(), getProductOrService(), getProductsForCategory(), Product\is_photo_available(), FormFile\list_of_documents(), member_prepare_head(), migrate_user_photospath(), product_prepare_head(), Form\showphoto(), FactureFournisseur\validate(), pdf_squille\write_file(), pdf_espadon\write_file(), pdf_cornas\write_file(), pdf_rouget\write_file(), pdf_cyan\write_file(), pdf_eratosthene\write_file(), pdf_canelle\write_file(), pdf_aurore\write_file(), pdf_sponge\write_file(), pdf_muscadet\write_file(), pdf_azur\write_file(), pdf_crabe\write_file(), and pdf_standard\write_file().
get_htmloutput_errors ($mesgstring = '', $mesgarray = array(), $keepembedded = 0)
Get formated error messages to output (Used to show messages on html output).
Parameters
string $mesgstring Error message
array $mesgarray Error messages array
int $keepembedded Set to 1 in error message must be kept embedded into its html place (this disable jnotify)
Returns
string Return html output
See also
dol_print_error()
dol_htmloutput_mesg()
Definition at line 6555 of file functions.lib.php.
References get_htmloutput_mesg().
Referenced by ActionsCardService\assign_values(), ActionsCardProduct\assign_values(), and ActionsCardCommon\assign_values().
get_htmloutput_mesg ($mesgstring = '', $mesgarray = '', $style = 'ok', $keepembedded = 0)
Get formated messages to output (Used to show messages on html output).
This include also the translation of the message key.
Parameters
string $mesgstring Message string or message key
string[] $mesgarray Array of message strings or message keys
string $style Style of message output ('ok' or 'error')
int $keepembedded Set to 1 in error message must be kept embedded into its html place (this disable jnotify)
Returns
string Return html output
See also
dol_print_error()
dol_htmloutput_errors()
setEventMessages()
Definition at line 6479 of file functions.lib.php.
References dol_escape_js().
Referenced by ActionsCardCommon\assign_values(), dol_htmloutput_mesg(), and get_htmloutput_errors().
get_localtax ($vatrate, $local, $thirdparty_buyer = "", $thirdparty_seller = "", $vatnpr = 0)
Return localtax rate for a particular vat, when selling a product with vat $vatrate, from a $thirdparty_buyer to a $thirdparty_seller Note: This function applies same rules than get_default_tva.
Parameters
float $vatrate Vat rate. Can be '8.5' or '8.5 (VATCODEX)' for example
int $local Local tax to search and return (1 or 2 return only tax rate 1 or tax rate 2)
Societe $thirdparty_buyer Object of buying third party
Societe $thirdparty_seller Object of selling third party ($mysoc if not defined)
int $vatnpr If vat rate is NPR or not
Returns
mixed 0 if not found, localtax rate if found
See also
get_default_tva()
Definition at line 4613 of file functions.lib.php.
References $resql, dol_syslog(), and isOnlyOneLocalTax().
Referenced by SupplierProposal\add_product(), Propal\add_product(), Commande\add_product(), Expedition\fetch_lines(), getLocalTaxesFromRate(), ProductFournisseur\update_buyprice(), and Product\updatePrice().
get_localtax_by_third ($local)
Get values of localtaxes (1 or 2) for company country for the common vat with the highest value.
Parameters
int $local LocalTax to get
Returns
number Values of localtax
Definition at line 4770 of file functions.lib.php.
References $resql.
Referenced by isOnlyOneLocalTax(), and FormCompany\select_localtax().
get_product_localtax_for_country ($idprod, $local, $thirdparty_seller)
Return localtax vat rate of a product in a particular selling country or default country vat if product is unknown.
Parameters
int $idprod Id of product
int $local 1 for localtax1, 2 for localtax 2
Societe $thirdparty_seller Thirdparty with a ->country_code defined (FR, US, IT, ...)
Returns
int <0 if KO, Vat rate if OK
See also
get_product_vat_for_country()
Definition at line 4994 of file functions.lib.php.
References $resql, dol_print_error(), and dol_syslog().
Referenced by get_default_localtax().
get_product_vat_for_country ($idprod, $thirdparty_seller, $idprodfournprice = 0)
Return vat rate of a product in a particular selling country or default country vat if product is unknown Function called by get_default_tva.
Parameters
int $idprod Id of product or 0 if not a predefined product
Societe $thirdparty_seller Thirdparty with a ->country_code defined (FR, US, IT, ...)
int $idprodfournprice Id product_fournisseur_price (for "supplier" proposal/order/invoice)
Returns
float|string Vat rate to use with format 5.0 or '5.0 (XXX)'
See also
get_product_localtax_for_country()
Definition at line 4917 of file functions.lib.php.
References $resql, dol_print_error(), and dol_syslog().
Referenced by get_default_tva().
getAdvancedPreviewUrl ($modulepart, $relativepath, $alldata = 0, $param = '')
Return URL we can use for advanced preview links.
Parameters
string $modulepart propal, facture, facture_fourn, ...
string $relativepath Relative path of docs.
int $alldata Return array with all components (1 is recommended, then use a simple a href link with the class, target and mime attribute added. 'documentpreview' css class is handled by jquery code into main.inc.php)
string $param More param on http links
Returns
string|array Output string with href link or array with all components of link
Definition at line 7721 of file functions.lib.php.
Referenced by FormFile\getDocumentsLink(), FormFile\list_of_documents(), CommonObject\show_photos(), Form\showphoto(), FormFile\showPreview(), and showWebsiteTemplates().
getBrowserInfo ($user_agent)
Return information about user browser.
Returns array with the following format: array('browsername' => Browser name (firefox|chrome|iceweasel|epiphany|safari|opera|ie|unknown) 'browserversion' => Browser version. Empty if unknown 'browseros' => Set with mobile OS (android|blackberry|ios|palm|symbian|webos|maemo|windows|unknown) 'layout' => (tablet|phone|classic) 'phone' => empty if not mobile, (android|blackberry|ios|palm|unknown) if mobile 'tablet' => true/false)
Parameters
string $user_agent Content of $_SERVER["HTTP_USER_AGENT"] variable
Returns
array Check function documentation
Definition at line 134 of file functions.lib.php.
Referenced by analyseVarsForSqlAndScriptsInjection().
getCommonSubstitutionArray ($outputlangs, $onlykey = 0, $exclude = null, $object = null)
Return array of possible common substitutions.
This includes several families like: 'system', 'mycompany', 'object', 'objectamount', 'date', 'user'
Parameters
Translate $outputlangs Output language
int $onlykey 1=Do not calculate some heavy values of keys (performance enhancement when we need only the keys), 2=Values are trunc and html sanitized (to use for help tooltip)
array $exclude Array of family keys we want to exclude. For example array('system', 'mycompany', 'object', 'objectamount', 'date', 'user', ...)
Object $object Object for keys on object
Returns
array Array of substitutions
See also
setSubstitFromObject()
Definition at line 5835 of file functions.lib.php.
References dol_get_next_day(), dol_get_next_month(), dol_get_prev_day(), dol_get_prev_month(), dol_getdate(), dol_htmlentitiesbr(), dol_now(), dol_print_date(), dol_string_nohtmltag(), dol_trunc(), getUserRemoteIP(), and price().
Referenced by checkLoginPassEntity(), Facture\create(), llxFooterVierge(), pdf_getSubstitutionArray(), Adherent\sendReminderForExpiredSubscription(), doc_generic_contract_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_order_odt\write_file(), doc_generic_product_odt\write_file(), doc_generic_stock_odt\write_file(), doc_generic_proposal_odt\write_file(), doc_generic_supplier_proposal_odt\write_file(), doc_generic_task_odt\write_file(), and doc_generic_project_odt\write_file().
getDictvalue ($tablename, $field, $id, $checkentity = false, $rowidfield = 'rowid')
Return value from dictionary.
Parameters
string $tablename name of dictionary
string $field the value to return
int $id id of line
bool $checkentity add filter on entity
string $rowidfield name of the column rowid
Returns
string
Definition at line 7889 of file functions.lib.php.
getDoliDBInstance ($type, $host, $user, $pass, $name, $port)
Return a DoliDB instance (database handler).
Parameters
string $type Type of database (mysql, pgsql...)
string $host Address of database server
string $user Nom de l'utilisateur autorise
string $pass Mot de passe
string $name Nom de la database
int $port Port of database server
Returns
DoliDB A DoliDB instance
Definition at line 54 of file functions.lib.php.
Referenced by MailmanSpip\connectSpip().
getEntity ($element, $shared = 1, $currentobject = null)
Get list of entity id to use.
Parameters
string $element Current element 'societe', 'socpeople', 'actioncomm', 'agenda', 'resource', 'product', 'productprice', 'stock', 'propal', 'supplier_proposal', 'invoice', 'facture_fourn', 'payment_various', 'categorie', 'bank_account', 'bank_account', 'adherent', 'user', 'commande', 'commande_fournisseur', 'expedition', 'intervention', 'survey', 'contract', 'tax', 'expensereport', 'holiday', 'multicurrency', 'project', 'email_template', 'event', 'donation' 'c_paiement', 'c_payment_term', ...
int $shared 0=Return id of current entity only, 1=Return id of current entity + shared entities (default)
object $currentobject Current object if needed
Returns
mixed Entity id(s) to use (eg. entity IN ('.getEntity(elementname).')')
Definition at line 80 of file functions.lib.php.
Referenced by modProjet\__construct(), modSociete\__construct(), MailingTargets\add_to_target(), TaskStats\buildWhere(), ProjectStats\buildWhere(), Categorie\containing(), ProductAttribute\countChildProducts(), ProductCombination\countNbOfCombinationForFkProductParent(), Cpaiement\create(), PaymentTerm\create(), BookKeeping\create(), BookKeeping\deleteByYearAndJournal(), BookKeeping\deleteMvtNum(), dol_check_secure_access_document(), dol_getIdFromCode(), BookKeeping\export_bookkeping(), ProductAttributeValue\fetch(), ProductAttribute\fetch(), ProductCombination\fetch(), Paiement\fetch(), Categorie\fetch(), Ticket\fetch(), FactureFournisseur\fetch(), BookKeeping\fetch(), Propal\fetch(), Productcustomerprice\fetch_all(), Productcustomerprice\fetch_all_log(), ProductAttribute\fetchAll(), AccountingJournal\fetchAll(), Ticket\fetchAll(), BookKeeping\fetchAll(), BookKeeping\fetchAllBalance(), BookKeeping\fetchAllByAccount(), ProductCombination\fetchAllByFkProductParent(), BookKeeping\fetchAllPerMvt(), ProductCombination\fetchByFkProductChild(), BookKeeping\fetchPerMvt(), Contacts\get(), BookKeeping\get_compte_desc(), BookKeeping\get_compte_racine(), Project\get_element_list(), Categorie\get_full_arbo(), ExpenseReportIk\getAllRanges(), ExpenseReportRule\getAllRule(), Translate\getLabelFromKey(), CommonInvoice\getListOfPayments(), BookKeeping\getNextNumMvt(), mod_commande_saphir\getNextValue(), mod_propale_saphir\getNextValue(), mod_facture_mercure\getNextValue(), Categorie\getObjectsInCateg(), mailing_fraise\getSqlArrayForStats(), CdavLib\getSqlCalEvents(), ExpenseReportIk\getTaxCategories(), Societe\id_prof_exists(), Product\isVariant(), SupplierProposal\load_board(), Propal\load_board(), Commande\load_board(), Fichinter\load_state_board(), Contact\load_state_board(), SupplierProposal\load_state_board(), Propal\load_state_board(), Commande\load_state_board(), Facture\load_state_board(), FormProduct\loadLotStock(), AdvanceTargetingMailing\query_contact(), Categorie\rechercher(), Ticket\searchContactByEmail(), Ticket\searchSocidByEmail(), BookKeeping\select_account(), FormAccounting\select_auxaccount(), Form\select_produits_list(), FormOther\select_salesrepresentatives(), FormAccounting\selectyear_accountancy_bookkepping(), Productcustomerprice\setPriceOnAffiliateThirdparty(), and Form\showLinkToObjectBlock().
getImageFileNameForSize ($file, $extName, $extImgTarget = '')
Return the filename of file to get the thumbs.
Parameters
string $file Original filename (full or relative path)
string $extName Extension to differenciate thumb file name ('', '_small', '_mini')
string $extImgTarget Force image extension for thumbs. Use '' to keep same extension than original image (default).
Returns
string New file name (full or relative path, including the thumbs/)
Definition at line 7689 of file functions.lib.php.
Referenced by FormFile\list_of_documents(), Form\showphoto(), and vignette().
getLanguageCodeFromCountryCode ($countrycode)
Return default language from country code.
Return null if not found.
Parameters
string $countrycode Country code like 'US', 'FR', 'CA', ...
Returns
string Value of locale like 'en_US', 'fr_FR', ...
Definition at line 6904 of file functions.lib.php.
References dol_syslog().
Referenced by Adherent\sendReminderForExpiredSubscription().
getLocalTaxesFromRate ($vatrate, $local, $buyer, $seller, $firstparamisid = 0)
Get type and rate of localtaxes for a particular vat rate/country of a thirdparty.
This does not take into account the seller setup if subject to vat or not, only country. TODO This function is ALSO called to retrieve type for building PDF. Such call of function must be removed. Instead this function must be called when adding a line to get the array of localtax and type, and then provide it to the function calcul_price_total.
Parameters
int | string $vatrate VAT ID or Rate+Code. Value can be value or the string with code into parenthesis or rowid if $firstparamisid is 1. Example: '8.5' or '8.5 (8.5NPR)' or 123.
int $local Number of localtax (1 or 2, or 0 to return 1 & 2)
Societe $buyer Company object
Societe $seller Company object
int $firstparamisid 1 if first param is ID into table instead of Rate+code (use this if you can)
Returns
array array(localtax_type1(1-6/0 if not found), rate localtax1, localtax_type2, rate localtax2, accountancycodecust, accountancycodesupp)
See also
getTaxesFromId()
Definition at line 4859 of file functions.lib.php.
References $resql, dol_syslog(), and get_localtax().
Referenced by SupplierProposal\addline(), Propal\addline(), FactureRec\addline(), Commande\addline(), Contrat\addline(), CommandeFournisseur\addline(), FactureFournisseur\addline(), ExpenseReport\addline(), Facture\addline(), Facturation\ajoutArticle(), ContratLigne\update(), SupplierProposal\updateline(), Propal\updateline(), FactureRec\updateline(), Contrat\updateline(), FactureFournisseur\updateline(), ExpenseReport\updateline(), CommandeFournisseur\updateline(), Facture\updateline(), Commande\updateline(), pdf_cornas\write_file(), pdf_cyan\write_file(), pdf_eratosthene\write_file(), pdf_sponge\write_file(), pdf_aurore\write_file(), pdf_muscadet\write_file(), pdf_azur\write_file(), pdf_einstein\write_file(), and pdf_crabe\write_file().
GETPOST ($paramname, $check = 'none', $method = 0, $filter = null, $options = null, $noreplace = 0)
Return value of a param into GET or POST supervariable.
Use the property $user->default_values[path]['creatform'] and/or $user->default_values[path]['filters'] and/or $user->default_values[path]['sortorder'] Note: The property $user->default_values is loaded by main.php when loading the user.
Parameters
string $paramname Name of parameter to found
string $check Type of check ''=no check (deprecated) 'none'=no check (only for param that should have very rich content) 'int'=check it's numeric (integer or float) 'intcomma'=check it's integer+comma ('1,2,3,4...') 'alpha'=check it's text and sign 'aZ'=check it's a-z only 'aZ09'=check it's simple alpha string (recommended for keys) 'array'=check it's array 'san_alpha'=Use filter_var with FILTER_SANITIZE_STRING (do not use this for free text string) 'nohtml', 'alphanohtml'=check there is no html content 'custom'= custom filter specify $filter and $options)
int $method Type of method (0 = get then post, 1 = only get, 2 = only post, 3 = post then get)
int $filter Filter to apply when $check is set to 'custom'. (See http://php.net/manual/en/filter.filters.php for dtails)
mixed $options Options to pass to filter_var when $check is set to 'custom'
string $noreplace Force disable of replacement of xxx strings.
Returns
string|string[] Value found (string or array), or '' if check fails
Return a prefix to use for this Dolibarr instance, for session/cookie names or email id. The prefix is unique for instance and avoid conflict between multi-instances, even when having two instances with same root dir or two instances in same virtual servers.
Parameters
string $mode '' (prefix for session name) or 'email' (prefix for email id)
Returns
string A calculated prefix
Definition at line 255 of file functions.lib.php.
References dol_get_next_day(), dol_get_next_month(), dol_get_prev_day(), dol_get_prev_month(), dol_getdate(), dol_hash(), dol_now(), dol_string_nohtmltag(), dol_string_nospecial(), and dol_syslog().
Referenced by ImportCsv\__construct(), mailing_thirdparties_services_expired\add_to_target(), mailing_xinputuser\add_to_target(), mailing_contacts1\add_to_target(), analyseVarsForSqlAndScriptsInjection(), ActionsCardIndividual\assign_values(), checkLoginPassEntity(), SupplierProposal\cloture(), Propal\cloture(), Utils\compressSyslogs(), Facture\create(), create_script_table(), ActionsDatapolicy\doActions(), dol_add_file_process(), dol_check_secure_access_document(), Utils\dumpDatabase(), Form\editfieldkey(), Form\editfieldval(), fieldList(), fieldListAccountingCategories(), ActionsStripeconnect\formObjectOptions(), Thirdparties\generateBankAccountDocument(), FormMail\get_form(), FormOther\getBoxesArea(), Setup\getCheckIntegrity(), ExtraFields\getOptionalsFromPost(), hash_call(), FormFile\list_of_documents(), llxFooter(), llxFooterVierge(), box_graph_invoices_permonth\loadBox(), box_graph_invoices_supplier_permonth\loadBox(), box_graph_orders_permonth\loadBox(), box_graph_orders_supplier_permonth\loadBox(), box_graph_propales_permonth\loadBox(), box_graph_product_distribution\loadBox(), box_task\loadBox(), ActionsCardService\LoadListDatas(), ActionsCardProduct\LoadListDatas(), Ticket\newMessage(), print_auguria_menu(), print_left_eldy_menu(), ActionsDatapolicy\printCommonFooter(), printingAdminPrepareHead(), restrictedArea(), InterfaceStripe\runTrigger(), ExtraFields\setOptionalsFromPost(), show_contacts(), FormSms\show_form(), FormTicket\showForm(), FormTicket\showMessageForm(), ExtraFields\showSeparator(), societe_prepare_head(), Adherent\subscriptionComplementaryActions(), top_htmlhead(), top_menu(), Auth\verif(), ActionsTicket\viewTicketMessages(), ActionsTicket\viewTicketOriginalMessage(), ActionsTicket\viewTicketTimelineMessages(), and pdf_stdmovement\write_file().
GETPOSTISSET ($paramname)
Return true if we are in a context of submitting a parameter.
Parameters
string $paramname Name or parameter to test
Returns
boolean True if we have just submit a POST or GET request with the parameter provided (even if param is empty)
Definition at line 226 of file functions.lib.php.
Referenced by analyseVarsForSqlAndScriptsInjection(), fieldList(), FormMail\get_form(), llxFooter(), FormTicket\showForm(), and top_htmlhead().
getTaxesFromId ($vatrate, $buyer = null, $seller = null, $firstparamisid = 1)
Get vat main information from Id.
You can call getLocalTaxesFromRate after to get other fields.
Parameters
int | string $vatrate VAT ID or Rate. Value can be value or the string with code into parenthesis or rowid if $firstparamisid is 1. Example: '8.5' or '8.5 (8.5NPR)' or 123.
Societe $buyer Company object
Societe $seller Company object
int $firstparamisid 1 if first param is id into table (use this if you can)
Returns
array array('rowid'=> , 'code'=> ...)
See also
getLocalTaxesFromRate()
Definition at line 4803 of file functions.lib.php.
References $resql, dol_print_error(), and dol_syslog().
Referenced by Facturation\ajoutArticle().
getTitleFieldOfList ($name, $thead = 0, $file = "", $field = "", $begin = "", $moreparam = "", $moreattrib = "", $sortfield = "", $sortorder = "", $prefix = "", $disablesortlink = 0, $tooltip = '')
Get title line of an array.
Parameters
string $name Translation key of field
int $thead 0=To use with standard table format, 1=To use inside <thead>
, 2=To use with
Parameters
string $file Url used when we click on sort picto
string $field Field to use for new sorting. Empty if this field is not sortable. Example "t.abc" or "t.abc,t.def"
string $begin ("" by defaut)
string $moreparam Add more parameters on sort url links ("" by default)
string $moreattrib Add more attributes on th ("" by defaut, example: 'align="center"'). To add more css class, use param $prefix.
string $sortfield Current field used to sort (Ex: 'd.datep,d.id')
string $sortorder Current sort order (Ex: 'asc,desc')
string $prefix Prefix for css. Use space after prefix to add your own CSS tag, for example 'mycss '.
string $disablesortlink 1=Disable sort link
string $tooltip Tooltip
Returns
string
Definition at line 3941 of file functions.lib.php.
Referenced by print_liste_field_titre(), show_actions_done(), show_contacts(), and FormActions\showactions().
getUserRemoteIP ()
Return the IP of remote user.
Take HTTP_X_FORWARDED_FOR (defined when using proxy) Then HTTP_CLIENT_IP if defined (rare) Then REMOTE_ADDR (no way to be modified by user but may be wrong if user is using a proxy)
Returns
string Ip of remote user.
Definition at line 2673 of file functions.lib.php.
Referenced by Events\create(), Stripe\customerStripe(), dol_user_country(), getCommonSubstitutionArray(), and Stripe\getPaymentIntent().
img_action ($titlealt, $numaction)
Show logo action.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
string $numaction Action id or code to show
Returns
string Return an img tag
Definition at line 3294 of file functions.lib.php.
References img_picto().
Referenced by Societe\LibProspCommStatut().
img_allow ($allow, $titlealt = 'default')
Show tick logo if allowed.
Parameters
string $allow Allow
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
Returns
string Return img tag
Definition at line 3619 of file functions.lib.php.
References img_picto().
img_credit_card ($brand)
Return image of a credit card according to its brand name.
Parameters
string $brand Brand name of credit card
Returns
string Return img tag
Definition at line 3636 of file functions.lib.php.
img_delete ($titlealt = 'default', $other = 'class="pictodelete"')
Show delete logo.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
string $other Add more attributes on img
Returns
string Retourne tag img
Definition at line 3402 of file functions.lib.php.
References img_picto().
Referenced by Export\list_export_model(), FormFile\list_of_documents(), FormFile\listOfLinks(), and CommonObject\show_photos().
img_down ($titlealt = 'default', $selected = 0, $moreclass = '')
Show down arrow logo.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
int $selected Selected
string $moreclass Add more CSS classes
Returns
string Return img tag
Definition at line 3552 of file functions.lib.php.
References img_picto().
Referenced by form_constantes(), and FormFile\list_of_documents().
img_edit ($titlealt = 'default', $float = 0, $other = '')
Show logo editer/modifier fiche.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
integer $float Si il faut y mettre le style "float: right"
string $other Add more attributes on img
Returns
string Return tag img
Definition at line 3367 of file functions.lib.php.
References img_picto().
Referenced by ActionsCardCommon\assign_values(), Form\editfieldkey(), FormFile\list_of_documents(), FormFile\listOfLinks(), show_contacts(), show_subsidiaries(), and ActionsTicket\viewTicketOriginalMessage().
img_edit_add ($titlealt = 'default', $other = '')
Show logo +.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
string $other Add more attributes on img
Returns
string Return tag img
Definition at line 3335 of file functions.lib.php.
References img_picto().
img_edit_remove ($titlealt = 'default', $other = '')
Show logo -.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
string $other Add more attributes on img
Returns
string Return tag img
Definition at line 3350 of file functions.lib.php.
References img_picto().
img_error ($titlealt = 'default')
Show error logo.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
Returns
string Return img tag
Definition at line 3501 of file functions.lib.php.
References img_picto().
Referenced by Mailing\libStatutDest().
img_help ($usehelpcursor = 1, $usealttitle = 1)
Show help logo with cursor "?".
Parameters
int $usehelpcursor 1=Use help cursor, 2=Use click pointer cursor, 0=No specific cursor
int | string $usealttitle Text to use as alt title
Returns
string Return tag img
Definition at line 3449 of file functions.lib.php.
References dol_escape_htmltag(), and img_picto().
Referenced by ActionsDatapolicy\addMoreActionsButtons(), and Form\textwithpicto().
img_info ($titlealt = 'default')
Show info logo.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
Returns
string Return img tag
Definition at line 3468 of file functions.lib.php.
References img_picto().
img_left ($titlealt = 'default', $selected = 0, $moreatt = '')
Show left arrow logo.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
int $selected Selected
string $moreatt Add more attribute on img tag (For example 'style="float: right"')
Returns
string Return img tag
Definition at line 3586 of file functions.lib.php.
References img_picto().
img_mime ($file, $titlealt = '', $morecss = '')
Show MIME img of a file.
Parameters
string $file Filename
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
string $morecss More css
Returns
string Return img tag
Definition at line 3657 of file functions.lib.php.
References dol_mimetype().
Referenced by FormMail\get_form(), FormFile\getDocumentsLink(), FormFile\list_of_autoecmfiles(), FormFile\list_of_documents(), FormFile\showdocuments(), FormTicket\showForm(), FormTicket\showMessageForm(), and FormFile\showPreview().
img_next ($titlealt = 'default', $moreatt = '')
Show next logo.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
string $moreatt Add more attribute on img tag (For example 'style="float: right"')
Returns
string Return img tag
Definition at line 3517 of file functions.lib.php.
img_object ($titlealt, $picto, $moreatt = '', $pictoisfullpath = false, $srconly = 0, $notitle = 0)
Show a picto called object_picto (generic function)
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
string $picto Name of image to show object_picto (example: user, group, action, bill, contract, propal, product, ...) For external modules use imagename to search into directory "img" of module.
string $moreatt Add more attribute on img tag (ie: class="datecallink")
int $pictoisfullpath If 1, image path is a full path
int $srconly Return only content of the src attribute of img.
int $notitle 1=Disable tag title. Use it if you add js tooltip, to avoid duplicate tooltip.
Returns
string Return img tag
See also
img_picto, img_picto_common
Definition at line 3222 of file functions.lib.php.
References img_picto().
Referenced by Notify\confirmMessage(), dol_print_email(), dol_print_phone(), dol_print_socialnetworks(), User\getLoginUrl(), AccountingJournal\getNomUrl(), EmailCollectorFilter\getNomUrl(), Asset\getNomUrl(), EmailCollectorAction\getNomUrl(), Inventory\getNomUrl(), CompanyPaymentMode\getNomUrl(), CashControl\getNomUrl(), SocieteAccount\getNomUrl(), Subscription\getNomUrl(), AssetType\getNomUrl(), BookKeeping\getNomUrl(), EmailCollector\getNomUrl(), Opensurveysondage\getNomUrl(), AdherentType\getNomUrl(), Loan\getNomUrl(), EcmDirectory\getNomUrl(), MyObject\getNomUrl(), ChargeSociales\getNomUrl(), Productlot\getNomUrl(), Mailing\getNomUrl(), PaiementFourn\getNomUrl(), PaymentVarious\getNomUrl(), PaymentSalary\getNomUrl(), Task\getNomUrl(), Entrepot\getNomUrl(), Tva\getNomUrl(), BOM\getNomUrl(), CommandeFournisseur\getNomUrl(), Fichinter\getNomUrl(), Cronjob\getNomUrl(), UserGroup\getNomUrl(), Don\getNomUrl(), Dolresource\getNomUrl(), Project\getNomUrl(), RemiseCheque\getNomUrl(), ProductFournisseur\getNomUrl(), Contact\getNomUrl(), Holiday\getNomUrl(), Paiement\getNomUrl(), BonPrelevement\getNomUrl(), Facture\getNomUrl(), FactureRec\getNomUrl(), BOMLine\getNomUrl(), ActionComm\getNomUrl(), Ticket\getNomUrl(), Account\getNomUrl(), ExpenseReport\getNomUrl(), Expedition\getNomUrl(), Contrat\getNomUrl(), Societe\getNomUrl(), Adherent\getNomUrl(), FactureFournisseur\getNomUrl(), AccountLine\getNomUrl(), User\getNomUrl(), SupplierProposal\getNomUrl(), Propal\getNomUrl(), Commande\getNomUrl(), Product\getNomUrl(), Interfaces\getTriggersList(), ModeleBoxes\getWidgetsList(), Export\list_export_model(), RemiseCheque\load_board(), ActionComm\load_board(), Account\load_board(), Project\load_board(), Task\load_board(), Contrat\load_board(), FactureFournisseur\load_board(), Holiday\load_board(), SupplierProposal\load_board(), Adherent\load_board(), ExpenseReport\load_board(), CommandeFournisseur\load_board(), Propal\load_board(), Commande\load_board(), Facture\load_board(), box_services_contracts\loadBox(), show_actions_done(), show_contacts(), show_list_sending_receive(), show_projects(), show_stats_for_company(), box_actions\showBox(), ModeleBoxes\showBox(), Form\showCategories(), mailing_mailinglist_mymodule_myobject\url(), mailing_pomme\url(), mailing_fraise\url(), mailing_thirdparties_services_expired\url(), mailing_thirdparties\url(), and mailing_contacts1\url().
img_pdf ($titlealt = 'default', $size = 3)
Show pdf logo.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
int $size Taille de l'icone : 3 = 16x16px , 2 = 14x14px
Returns
string Retourne tag img
Definition at line 3319 of file functions.lib.php.
References img_picto().
img_picto ($titlealt, $picto, $moreatt = '', $pictoisfullpath = false, $srconly = 0, $notitle = 0, $alt = '', $morecss = '', $marginleftonlyshort = 2)
Show picto whatever it's its name (generic function)
Parameters
string $titlealt Text on title tag for tooltip. Not used if param notitle is set to 1.
string $picto Name of image file to show ('filenew', ...) If no extension provided, we use '.png'. Image must be stored into theme/xxx/img directory. Example: picto.png if picto.png is stored into htdocs/theme/mytheme/img Example: picto.png if picto.png is stored into htdocs/mymodule/img Example: /mydir/mysubdir/picto.png if picto.png is stored into htdocs/mydir/mysubdir (pictoisfullpath must be set to 1)
string $moreatt Add more attribute on img tag (For example 'style="float: right"')
boolean | int $pictoisfullpath If true or 1, image path is a full path
int $srconly Return only content of the src attribute of img.
int $notitle 1=Disable tag title. Use it if you add js tooltip, to avoid duplicate tooltip.
string $alt Force alt for bind people
string $morecss Add more class css on img tag (For example 'myclascss'). Work only if $moreatt is empty.
string $marginleftonlyshort 1 = Add a short left margin on picto, 2 = Add a larger left maring on picto, 0 = No margin left. Works for fontawesome picto only.
Returns
string Return img tag
See also
img_object(), img_picto_common()
Definition at line 2985 of file functions.lib.php.
References dol_escape_htmltag().
Referenced by ajax_constantonoff(), ActionsCardCompany\assign_values(), checkLoginPassEntity(), FormMargin\displayMarginInfos(), dol_banner_tab(), dol_get_fiche_head(), dol_print_cron_urls(), dol_print_email(), dol_print_phone(), dol_print_socialnetworks(), dol_print_url(), ExpenseReport\fetch_line_by_project(), Facture\getNomUrl(), Interfaces\getTriggersList(), ModeleBoxes\getWidgetsList(), img_action(), img_allow(), img_delete(), img_down(), img_edit(), img_edit_add(), img_edit_remove(), img_error(), img_help(), img_info(), img_left(), img_object(), img_pdf(), img_picto_common(), img_printer(), img_right(), img_search(), img_searchclear(), img_split(), img_up(), img_view(), img_warning(), img_weather(), info_admin(), left_menu(), Don\LibStatut(), LignePrelevement\LibStatut(), ActionCommReminder\LibStatut(), Fiscalyear\LibStatut(), CashControl\LibStatut(), Establishment\LibStatut(), EmailSenderProfile\LibStatut(), Deplacement\LibStatut(), EmailCollectorFilter\LibStatut(), Asset\LibStatut(), Inventory\LibStatut(), EmailCollectorAction\LibStatut(), Loan\LibStatut(), Cchargesociales\LibStatut(), SocieteAccount\LibStatut(), ChargeSociales\LibStatut(), CompanyPaymentMode\LibStatut(), EmailCollector\LibStatut(), WebsitePage\LibStatut(), ProductStockEntrepot\LibStatut(), PaymentVarious\LibStatut(), CommandeFournisseurDispatch\LibStatut(), MyObject\LibStatut(), Mailing\LibStatut(), Entrepot\LibStatut(), CommandeFournisseur\LibStatut(), ExpenseReport\LibStatut(), Opensurveysondage\LibStatut(), AccountingAccount\LibStatut(), Fichinter\LibStatut(), Website\LibStatut(), BOM\LibStatut(), Livraison\LibStatut(), Project\LibStatut(), MouvementStock\LibStatut(), RemiseCheque\LibStatut(), Account\LibStatut(), Reception\LibStatut(), Ticket\LibStatut(), ActionComm\LibStatut(), Holiday\LibStatut(), Contact\LibStatut(), FactureRec\LibStatut(), Cronjob\LibStatut(), BOMLine\LibStatut(), Expedition\LibStatut(), Task\LibStatut(), Contrat\LibStatut(), BonPrelevement\LibStatut(), Adherent\LibStatut(), SupplierProposal\LibStatut(), Societe\LibStatut(), User\LibStatut(), ContratLigne\LibStatut(), Mailing\libStatutDest(), FormFile\list_of_documents(), printing_printipp\listAvailablePrinters(), printing_printgcp\listAvailablePrinters(), FormFile\listOfLinks(), box_graph_orders_supplier_permonth\loadBox(), box_graph_propales_permonth\loadBox(), box_graph_invoices_supplier_permonth\loadBox(), box_graph_invoices_permonth\loadBox(), box_graph_orders_permonth\loadBox(), box_services_contracts\loadBox(), box_graph_product_distribution\loadBox(), Form\multiSelectArrayWithCheckbox(), print_barre_liste(), Form\select_company(), Form\select_produits(), show_actions_done(), show_elem(), CommonObject\show_photos(), FormActions\showactions(), ModeleBoxes\showBox(), showPaypalPaymentUrl(), showStripePaymentUrl(), Form\textwithpicto(), top_menu(), and ActionsTicket\viewStatusActions().
img_picto_common ($titlealt, $picto, $moreatt = '', $pictoisfullpath = 0)
Show picto (generic function)
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
string $picto Name of image file to show (If no extension provided, we use '.png'). Image must be stored into htdocs/theme/common directory.
string $moreatt Add more attribute on img tag
int $pictoisfullpath If 1, image path is a full path
Returns
string Return img tag
See also
img_object, img_picto
Definition at line 3265 of file functions.lib.php.
References img_picto().
Referenced by picto_from_langcode(), and tree_showpad().
img_previous ($titlealt = 'default', $moreatt = '')
Show previous logo.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
string $moreatt Add more attribute on img tag (For example 'style="float: right"')
Returns
string Return img tag
Definition at line 3534 of file functions.lib.php.
img_printer ($titlealt = "default", $other = '')
Show printer logo.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
string $other Add more attributes on img
Returns
string Retourne tag img
Definition at line 3419 of file functions.lib.php.
References img_picto().
img_right ($titlealt = 'default', $selected = 0, $moreatt = '')
Show right arrow logo.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
int $selected Selected
string $moreatt Add more attribute on img tag (For example 'style="float: right"')
Returns
string Return img tag
Definition at line 3603 of file functions.lib.php.
References img_picto().
img_search ($titlealt = 'default', $other = '')
Show search logo.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
string $other Add more attributes on img
Returns
string Retourne tag img
Definition at line 3679 of file functions.lib.php.
References dol_escape_htmltag(), and img_picto().
img_searchclear ($titlealt = 'default', $other = '')
Show search logo.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
string $other Add more attributes on img
Returns
string Retourne tag img
Definition at line 3700 of file functions.lib.php.
References dol_escape_htmltag(), and img_picto().
img_split ($titlealt = 'default', $other = 'class="pictosplit"')
Show split logo.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
string $other Add more attributes on img
Returns
string Retourne tag img
Definition at line 3433 of file functions.lib.php.
References img_picto().
img_up ($titlealt = 'default', $selected = 0, $moreclass = '')
Show top arrow logo.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
int $selected Selected
string $moreclass Add more CSS classes
Returns
string Return img tag
Definition at line 3569 of file functions.lib.php.
References img_picto().
Referenced by FormFile\list_of_documents().
img_view ($titlealt = 'default', $float = 0, $other = '')
Show logo view card.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
integer $float Si il faut y mettre le style "float: right"
string $other Add more attributes on img
Returns
string Return tag img
Definition at line 3384 of file functions.lib.php.
References img_picto().
img_warning ($titlealt = 'default', $moreatt = '', $morecss = 'pictowarning')
Show warning logo.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
string $moreatt Add more attribute on img tag (For example 'style="float: right"'). If 1, add float: right. Can't be "class" attribute.
string $morecss Add more CSS
Returns
string Return img tag
Definition at line 3485 of file functions.lib.php.
References img_picto().
Referenced by dol_print_email(), dol_print_socialnetworks(), getTaskProgressView(), doc_generic_odt\info(), doc_generic_reception_odt\info(), doc_generic_user_odt\info(), doc_generic_proposal_odt\info(), doc_generic_product_odt\info(), doc_generic_stock_odt\info(), doc_generic_contract_odt\info(), doc_generic_supplier_proposal_odt\info(), doc_generic_usergroup_odt\info(), doc_generic_order_odt\info(), doc_generic_invoice_odt\info(), doc_generic_shipment_odt\info(), doc_generic_task_odt\info(), doc_generic_project_odt\info(), box_factures_fourn_imp\loadBox(), box_services_expired\loadBox(), box_factures\loadBox(), box_factures_fourn\loadBox(), box_actions\loadBox(), box_propales\loadBox(), box_factures_imp\loadBox(), box_produits_alerte_stock\loadBox(), ActionsCardProduct\LoadListDatas(), projectLinesa(), show_actions_done(), show_array_actions_to_do(), and Form\textwithpicto().
img_weather ($titlealt, $picto, $moreatt = '', $pictoisfullpath = 0, $morecss = '')
Show weather picto.
Parameters
string $titlealt Text on alt and title of image. Alt only if param notitle is set to 1. If text is "TextA:TextB", use Text A on alt and Text B on title.
string | int $picto Name of image file to show (If no extension provided, we use '.png'). Image must be stored into htdocs/theme/common directory. Or level of meteo image (0-4).
string $moreatt Add more attribute on img tag
int $pictoisfullpath If 1, image path is a full path
string $morecss More CSS
Returns
string Return img tag
See also
img_object, img_picto
Definition at line 3238 of file functions.lib.php.
References img_picto().
Referenced by showWeather().
info_admin ($text, $infoonimgalt = 0, $nodiv = 0, $admin = '1', $morecss = '')
Show information for admin users or standard users.
Parameters
string $text Text info
integer $infoonimgalt Info is shown only on alt of star picto, otherwise it is show on output after the star picto
int $nodiv No div
string $admin '1'=Info for admin users. '0'=Info for standard users (change only the look), 'error','xxx'=Other
string $morecss More CSS
Returns
string String with info text
Definition at line 3724 of file functions.lib.php.
References dol_escape_htmltag(), and img_picto().
Referenced by ActionsCardCommon\assign_values(), ActionsAdherentCardCommon\assign_values(), ActionsContactCardCommon\assign_values(), FormFile\form_attach_new_file(), FormMail\get_form(), main_area(), FormCompany\select_civility(), Form\select_conditions_paiements(), FormActions\select_type_actions(), Form\select_type_fees(), FormSocialContrib\select_type_socialcontrib(), Form\select_types_paiements(), FormResource\select_types_resource(), Form\selectAvailabilityDelay(), Form\selectCurrency(), FormTicket\selectGroupTickets(), Form\selectInputReason(), FormTicket\selectSeveritiesTickets(), Form\selectShippingMethod(), FormWebsite\selectTypeOfContainer(), FormTicket\selectTypesTickets(), and FormTicket\showMessageForm().
isAFileWithExecutableContent ($filename)
Return if a file can contains executable content.
Parameters
string $filename File NamedRange
Returns
boolean True if yes, False if no
Definition at line 8339 of file functions.lib.php.
Referenced by dol_move_uploaded_file().
isOnlyOneLocalTax ($local)
Return true if LocalTax (1 or 2) is unique.
Example: If localtax1 is 5 on line with highest common vat rate, return true Example: If localtax1 is 5:8:15 on line with highest common vat rate, return false
Parameters
int $local Local tax to test (1 or 2)
Returns
boolean True if LocalTax have multiple values, False if not
Definition at line 4748 of file functions.lib.php.
References get_localtax_by_third().
Referenced by get_localtax().
isValidEmail ($address, $acceptsupervisorkey = 0)
Return true if email syntax is ok.
Parameters
string $address email (Ex: "toto@examle.com", "John Do <johndo@example.com>")
int $acceptsupervisorkey If 1, the special string 'SUPERVISOREMAIL' is also accepted as valid
Returns
boolean true if email syntax is OK, false if KO or empty string
Definition at line 2796 of file functions.lib.php.
Referenced by dol_print_email(), dolObfuscateEmail(), Notify\getNotificationsArray(), and llxFooterVierge().
isValidMXRecord ($domain)
Return if the domain name has a valid MX record.
WARNING: This need function idn_to_ascii, checkdnsrr and getmxrr
Parameters
string $domain Domain name (Ex: "yahoo.com", "yhaoo.com", "dolibarr.fr")
Returns
int -1 if error (function not available), 0=Not valid, 1=Valid
Definition at line 2811 of file functions.lib.php.
isValidPhone ($phone)
Return true if phone number syntax is ok TODO Decide what to do with this.
Parameters
string $phone phone (Ex: "0601010101")
Returns
boolean true if phone syntax is OK, false if KO or empty string
Definition at line 2840 of file functions.lib.php.
isVisibleToUserType ($type_user, & $menuentry, & $listofmodulesforexternal)
Function to test if an entry is enabled or not.
Parameters
string $type_user 0=We test for internal user, 1=We test for external user
array $menuentry Array for feature entry to test
array $listofmodulesforexternal Array with list of modules allowed to external users
Returns
int 0=Hide, 1=Show, 2=Show gray
Definition at line 7964 of file functions.lib.php.
Referenced by box_produits\__construct(), box_produits_alerte_stock\__construct(), print_eldy_menu(), and print_left_eldy_menu().
load_fiche_titre ($titre, $morehtmlright = '', $picto = 'title_generic.png', $pictoisfullpath = 0, $id = '', $morecssontable = '', $morehtmlcenter = '')
Load a title with picto.
Parameters
string $titre Title to show
string $morehtmlright Added message to show on right
string $picto Icon to use before title (should be a 32x32 transparent png file)
int $pictoisfullpath 1=Icon name is a full absolute url of image
string $id To force an id on html objects
string $morecssontable More css on table
string $morehtmlcenter Added message to show on center
Returns
string
See also
print_barre_liste()
Definition at line 4086 of file functions.lib.php.
References dol_strlen().
Referenced by ActionsCardCompany\assign_values(), ActionsCardIndividual\assign_values(), create_key_table(), FormFile\form_attach_new_file(), Setup\getCheckIntegrity(), FormFile\list_of_autoecmfiles(), FormFile\list_of_documents(), FormFile\listOfLinks(), llxFooterVierge(), print_fiche_titre(), pt(), show_contacts(), show_list_sending_receive(), show_projects(), show_subsidiaries(), FormActions\showactions(), FormFile\showdocuments(), Form\showLinkedObjectBlock(), and valeur().
make_substitutions ($text, $substitutionarray, $outputlangs = null)
Make substitution into a text string, replacing keys with vals from $substitutionarray (oldval=>newval), and texts like __(TranslationKey|langfile)__ and [ConstantKey] are also replaced.
Example of usage: $substitutionarray = getCommonSubstitutionArray($langs, 0, null, $thirdparty); complete_substitutions_array($substitutionarray, $langs, $thirdparty); $mesg = make_substitutions($mesg, $substitutionarray, $langs);
Parameters
string $text Source string in which we must do substitution
array $substitutionarray Array with key->val to substitute. Example: array('MYKEY' => 'MyVal', ...)
Translate $outputlangs Output language
Returns
string Output string after substitutions
See also
complete_substitutions_array(), getCommonSubstitutionArray()
Definition at line 6174 of file functions.lib.php.
References dol_htmlentitiesbr(), and dol_textishtml().
Referenced by BordereauChequeBlochet\_pagefoot(), checkLoginPassEntity(), complete_head_from_modules(), Facture\create(), dol_print_phone(), dolReplaceInFile(), FormMail\get_form(), llxFooterVierge(), Adherent\makeSubstitution(), Menubase\menuLoad(), EmailCollector\overwritePropertiesOfObject(), pdf_pagefoot(), pdf_watermark(), print_auguria_menu(), print_eldy_menu(), print_left_auguria_menu(), print_left_eldy_menu(), DataPolicy\sendMailDataPolicyAdherent(), DataPolicy\sendMailDataPolicyCompany(), DataPolicy\sendMailDataPolicyContact(), Adherent\sendReminderForExpiredSubscription(), FormSms\show_form(), MenuManager\showmenu(), FormTicket\showMessageForm(), pdf_timespent\write_file(), pdf_beluga\write_file(), pdf_soleil\write_file(), pdf_baleine\write_file(), pdf_cornas\write_file(), pdf_cyan\write_file(), pdf_eratosthene\write_file(), pdf_stdmovement\write_file(), doc_generic_contract_odt\write_file(), doc_generic_reception_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_shipment_odt\write_file(), doc_generic_order_odt\write_file(), pdf_sponge\write_file(), pdf_aurore\write_file(), pdf_standard\write_file(), pdf_azur\write_file(), pdf_einstein\write_file(), doc_generic_stock_odt\write_file(), doc_generic_product_odt\write_file(), doc_generic_usergroup_odt\write_file(), doc_generic_proposal_odt\write_file(), pdf_crabe\write_file(), and doc_generic_supplier_proposal_odt\write_file().
natural_search ($fields, $value, $mode = 0, $nofirstand = 0)
Generate natural SQL search string for a criteria (this criteria can be tested on one or several fields)
Parameters
string|string[] $fields String or array of strings, filled with the name of all fields in the SQL query we must check (combined with a OR). Example: array("p.field1","p.field2")
string $value The value to look for. If param $mode is 0, can contains several keywords separated with a space or | like "keyword1 keyword2" = We want record field like keyword1 AND field like keyword2 or like "keyword1|keyword2" = We want record field like keyword1 OR field like keyword2 If param $mode is 1, can contains an operator <, > or = like "<10" or ">=100.5 < 1000" If param $mode is 2, can contains a list of int id separated by comma like "1,3,4" If param $mode is 3, can contains a list of string separated by comma like "a,b,c"
integer $mode 0=value is list of keyword strings, 1=value is a numeric test (Example ">5.5 <10"), 2=value is a list of ID separated with comma (Example '1,3,4') 3=value is list of string separated with comma (Example 'text 1,text 2'), 4=value is a list of ID separated with comma (Example '1,3,4') for search into a multiselect string ('1,2')
integer $nofirstand 1=Do not output the first 'AND'
Returns
string $res The statement to append to the SQL query
Definition at line 7506 of file functions.lib.php.
Referenced by BookKeeping\fetchAll(), BookKeeping\fetchAllByAccount(), BlockedLog\getLog(), Task\getTasksArray(), FormProjets\select_projects_list(), show_actions_done(), show_contacts(), and pdf_stdmovement\write_file().
picto_from_langcode ($codelang, $moreatt = '')
Return img flag of country for a language code or country code.
Parameters
string $codelang Language code (en_IN, fr_CA...) or Country code (IN, FR)
string $moreatt Add more attribute on img tag (For example 'style="float: right"')
Returns
string HTML img string with flag.
Definition at line 6868 of file functions.lib.php.
References img_picto_common().
Referenced by ActionsCardCommon\assign_values(), ActionsAdherentCardCommon\assign_values(), ActionsContactCardCommon\assign_values(), User\getNomUrl(), and top_menu_user().
picto_required ()
Return picto saying a field is required.
Returns
string Chaine avec picto obligatoire
Definition at line 5390 of file functions.lib.php.
price ($amount, $form = 0, $outlangs = '', $trunc = 1, $rounding = -1, $forcerounding = -1, $currency_code = '')
Function to format a value into an amount for visual output Function used into PDF and HTML pages.
Parameters
float $amount Amount to format
integer $form Type of format, HTML or not (not by default)
Translate $outlangs Object langs for output
int $trunc 1=Truncate if there is more decimals than MAIN_MAX_DECIMALS_SHOWN (default), 0=Does not truncate. Deprecated because amount are rounded (to unit or total amount accurancy) before beeing inserted into database or after a computation, so this parameter should be useless.
int $rounding Minimum number of decimal to show. If 0, no change, if -1, we use min($conf->global->MAIN_MAX_DECIMALS_UNIT,$conf->global->MAIN_MAX_DECIMALS_TOT)
int $forcerounding Force the number of decimal to forcerounding decimal (-1=do not force)
string $currency_code To add currency symbol (''=add nothing, 'auto'=Use default currency, 'XXX'=add currency symbols for XXX currency)
Returns
string Chaine avec montant formate
See also
price2num() Revert function of price
Definition at line 4380 of file functions.lib.php.
References dol_strlen().
Referenced by MouvementStock\_create(), Product\_log_price(), pdf_standard\_pagehead(), pdf_stdmovement\_pagehead(), RejetPrelevement\_send_email(), pdf_standard\_tableau_cheque(), pdf_squille\_tableau_tot(), pdf_canelle\_tableau_tot(), pdf_espadon\_tableau_tot(), pdf_rouget\_tableau_tot(), pdf_muscadet\_tableau_tot(), pdf_einstein\_tableau_tot(), pdf_cornas\_tableau_tot(), pdf_aurore\_tableau_tot(), pdf_azur\_tableau_tot(), pdf_crabe\_tableau_tot(), pdf_crabe\_tableau_versements(), pdf_canelle\_tableau_versements(), BordereauChequeBlochet\Body(), pdf_paiement\Body(), ExpenseReport\checkRules(), Form\constructProductListOption(), Productcustomerprice\create(), Product\create(), ProductFournisseur\display_price_product_fournisseur(), FormMargin\displayMarginInfos(), pdf_sponge\drawPaymentsTable(), pdf_eratosthene\drawTotalTable(), pdf_cyan\drawTotalTable(), pdf_sponge\drawTotalTable(), Form\editfieldval(), Form\editInPlace(), envoi_mail(), AccountancyExport\exportAgiris(), AccountancyExport\exportBob50(), AccountancyExport\exportCegid(), AccountancyExport\exportCharlemagne(), AccountancyExport\exportCoala(), AccountancyExport\exportCogilog(), AccountancyExport\exportLDCompta(), AccountancyExport\exportOpenConcerto(), Productcustomerprice\fetch(), MouvementStock\fetch(), FactureLigneRec\fetch(), Product\fetch(), SupplierProposalLine\fetch(), PropaleLigne\fetch(), OrderLine\fetch(), ExpenseReport\fetch_line_by_project(), CommonDocGenerator\fill_substitutionarray_with_extrafields(), Form\form_multicurrency_rate(), Form\form_remise_dispo(), CommonDocGenerator\get_substitutionarray_contact(), CommonDocGenerator\get_substitutionarray_lines(), CommonDocGenerator\get_substitutionarray_object(), doc_generic_task_odt\get_substitutionarray_project_reference(), doc_generic_project_odt\get_substitutionarray_project_reference(), CommonDocGenerator\get_substitutionarray_shipment(), CommonDocGenerator\get_substitutionarray_shipment_lines(), CommonDocGenerator\get_substitutionarray_thirdparty(), ProjectStats\getAllProjectByStatus(), getCommonSubstitutionArray(), CommandeFournisseur\getNomUrl(), Facture\getNomUrl(), ExpenseReport\getNomUrl(), Contrat\getNomUrl(), FactureFournisseur\getNomUrl(), SupplierProposal\getNomUrl(), Propal\getNomUrl(), Commande\getNomUrl(), Product\getSellPrice(), BordereauChequeBlochet\Header(), Productcustomerprice\initAsSpecimen(), OrderLine\insert(), box_supplier_orders\loadBox(), box_factures\loadBox(), box_factures_fourn_imp\loadBox(), box_factures_fourn\loadBox(), box_propales\loadBox(), box_commandes\loadBox(), box_factures_imp\loadBox(), box_produits\loadBox(), box_activity\loadBox(), box_produits_alerte_stock\loadBox(), box_comptes\loadBox(), ActionsCardProduct\LoadListDatas(), pdf_getlinetotalexcltax(), pdf_getlinetotalwithtax(), pdf_getlineupexcltax(), pdf_getlineupwithtax(), pdf_pagefoot(), print_projecttasks_array(), pdf_standard\printLine(), pt(), FormOther\select_ecotaxes(), Form\select_product_fourn_price(), Form\select_produits_fournisseurs_list(), Form\select_remises(), Form\selectExpenseRanges(), BonPrelevement\set_infotrans(), show_projects(), showDimensionInBestUnit(), ExtraFields\showInputField(), Form\showLinkToObjectBlock(), ExtraFields\showOutputField(), pdf_standard\tablePayments(), Productcustomerprice\update(), FactureLigneRec\update(), SupplierProposalLine\update(), PropaleLigne\update(), OrderLine\update(), Product\updatePrice(), valeur(), vatrate(), html_cerfafr\write_file(), pdf_paiement\write_file(), pdf_squille\write_file(), pdf_beluga\write_file(), pdf_espadon\write_file(), pdf_strato\write_file(), pdf_rouget\write_file(), and pdf_standard\write_file().
price2num ($amount, $rounding = '', $alreadysqlnb = 0)
Function that return a number with universal decimal format (decimal separator is '.
') from an amount typed by a user. Function to use on each input amount before any numeric test or database insert
Parameters
float $amount Amount to convert/clean
string $rounding ''=No rounding 'MU'=Round to Max unit price (MAIN_MAX_DECIMALS_UNIT) 'MT'=Round to Max for totals with Tax (MAIN_MAX_DECIMALS_TOT) 'MS'=Round to Max for stock quantity (MAIN_MAX_DECIMALS_STOCK) Numeric = Nb of digits for rounding
int $alreadysqlnb Put 1 if you know that content is already universal format number
Returns
string Amount with universal numeric format (Example: '99.99999') or unchanged text if conversion fails. If amount is null or '', it returns ''.
See also
price() Opposite function of price2num
Definition at line 4472 of file functions.lib.php.
References dol_strlen().
Referenced by MouvementStock\_create(), pdf_standard\_pagehead(), pdf_stdmovement\_pagehead(), pdf_canelle\_tableau_tot(), pdf_muscadet\_tableau_tot(), pdf_einstein\_tableau_tot(), pdf_cornas\_tableau_tot(), pdf_crabe\_tableau_tot(), SupplierProposal\addline(), Propal\addline(), FactureRec\addline(), Commande\addline(), Contrat\addline(), CommandeFournisseur\addline(), FactureFournisseur\addline(), ExpenseReport\addline(), Facture\addline(), Holiday\addLogCP(), SupplierInvoices\addPayment(), Localtax\addPayment(), Tva\addPayment(), Invoices\addPayment(), Invoices\addPaymentDistributed(), Facturation\ajoutArticle(), CommandeFournisseur\approve(), calcul_price_total(), ChargeSociales\check(), Form\constructProductListOption(), RejetPrelevement\create(), Productcustomerprice\create(), PaymentDonation\create(), PaymentExpenseReport\create(), PaymentSocialContribution\create(), PaymentLoan\create(), LoanSchedule\create(), PaiementFourn\create(), Loan\create(), Project\create(), ChargeSociales\create(), DiscountAbsolute\create(), Paiement\create(), Facture\create(), PaymentVarious\create(), PaymentSalary\create(), Product\create(), Account\create(), CurrencyRate\create(), SupplierProposal\createPriceFournisseur(), ProductCombination\createProductCombination(), BookKeeping\createStd(), Facture\demande_prelevement(), pdf_eratosthene\drawTotalTable(), pdf_sponge\drawTotalTable(), Form\editfieldval(), AccountancyExport\exportConfigurable(), AccountancyExport\exportEbp(), AccountancyExport\exportFEC(), Societe\fetch(), Product\fetch(), Contrat\fetch_lines(), ProductFournisseur\fetch_product_fournisseur_price(), CommonDocGenerator\fill_substitutionarray_with_extrafields(), ProductFournisseur\find_min_price_product_fournisseur(), Invoices\get(), Thirdparties\get(), Dolistore\get_products(), CommonDocGenerator\get_substitutionarray_lines(), CommonDocGenerator\get_substitutionarray_object(), ProjectStats\getAllProjectByStatus(), Fichinter\getAmount(), getMarginInfos(), ExtraFields\getOptionalsFromPost(), ImportCsv\import_insert(), ImportXlsx\import_insert(), ExpenseReportLine\insert(), SupplierProposalLine\insert(), SupplierInvoiceLine\insert(), ContratLigne\insert(), CommandeFournisseurLigne\insert(), PropaleLigne\insert(), OrderLine\insert(), ProductFournisseur\list_product_fournisseur_price(), llxFooterVierge(), FormProduct\loadWarehouses(), ProductFournisseur\logPrice(), pdf_pagefoot(), print_projecttasks_array(), pt(), RemiseCheque\rejectCheck(), InterfaceActionsBlockedLog\runTrigger(), Form\select_produits_list(), BonPrelevement\set_infocredit(), Commande\set_remise(), Facture\set_remise(), SupplierProposal\set_remise_absolue(), Propal\set_remise_absolue(), Commande\set_remise_absolue(), Facture\set_remise_absolue(), Societe\set_remise_except(), SupplierProposal\set_remise_percent(), Propal\set_remise_percent(), ExtraFields\setOptionalsFromPost(), CommonObject\setSaveQuery(), CoreObject\setValues(), InterfaceWorkflowManager\shouldClassify(), showMyBalance(), Account\solde(), Adherent\subscriptionComplementaryActions(), BankAccounts\transfer(), Deplacement\update(), Project\update(), Don\update(), Productcustomerprice\update(), Account\update(), Product\update(), Societe\update(), CurrencyRate\update(), BookKeeping\update(), ExpenseReportLine\update(), ExpeditionLigne\update(), ContratLigne\update(), SupplierInvoiceLine\update(), ProductFournisseur\update_buyprice(), CommandeFournisseur\updateFromCommandeClient(), SupplierProposal\updateline(), Propal\updateline(), FactureRec\updateline(), Contrat\updateline(), FactureFournisseur\updateline(), ExpenseReport\updateline(), CommandeFournisseur\updateline(), Facture\updateline(), Commande\updateline(), Product\updatePrice(), SupplierProposal\updatePriceFournisseur(), Holiday\updateSoldeCP(), FactureFournisseur\validate(), pdf_standard\write_file(), pdf_stdmovement\write_file(), and doc_generic_project_odt\write_file().
print_barre_liste ($titre, $page, $file, $options = '', $sortfield = '', $sortorder = '', $morehtmlcenter = '', $num = -1, $totalnboflines = '', $picto = 'title_generic.png', $pictoisfullpath = 0, $morehtmlright = '', $morecss = '', $limit = -1, $hideselectlimit = 0, $hidenavigation = 0)
Print a title with navigation controls for pagination.
Parameters
string $titre Title to show (required)
int $page Numero of page to show in navigation links (required)
string $file Url of page (required)
string $options More parameters for links ('' by default, does not include sortfield neither sortorder). Value must be 'urlencoded' before calling function.
string $sortfield Field to sort on ('' by default)
string $sortorder Order to sort ('' by default)
string $morehtmlcenter String in the middle ('' by default). We often find here string $massaction comming from $form->selectMassAction()
int $num Number of records found by select with limit+1
int | string $totalnboflines Total number of records/lines for all pages (if known). Use a negative value of number to not show number. Use '' if unknown.
string $picto Icon to use before title (should be a 32x32 transparent png file)
int $pictoisfullpath 1=Icon name is a full absolute url of image
string $morehtmlright More html to show
string $morecss More css to the table
int $limit Max number of lines (-1 = use default, 0 = no limit, > 0 = limit).
int $hideselectlimit Force to hide select limit
int $hidenavigation Force to hide all navigation tools
Returns
void
Definition at line 4134 of file functions.lib.php.
References img_picto(), print, and print_fleche_navigation().
Referenced by llxFooterVierge().
print_date_range ($date_start, $date_end, $format = '', $outputlangs = '')
Format output for start and end date.
Parameters
int $date_start Start date
int $date_end End date
string $format Output format
Translate $outputlangs Output language
Returns
void
Definition at line 6293 of file functions.lib.php.
References get_date_range(), and print.
Referenced by show_list_sending_receive().
print_fiche_titre ($title, $mesg = '', $picto = 'title_generic.png', $pictoisfullpath = 0, $id = '')
Show a title with picto.
Parameters
string $title Title to show
string $mesg Added message to show on right
string $picto Icon to use before title (should be a 32x32 transparent png file)
int $pictoisfullpath 1=Icon name is a full absolute url of image
int $id To force an id on html objects
Returns
void
Deprecated:
Use print load_fiche_titre instead
Definition at line 4068 of file functions.lib.php.
References load_fiche_titre(), and print.
print_fleche_navigation ($page, $file, $options = '', $nextpage = 0, $betweenarrows = '', $afterarrows = '', $limit = -1, $totalnboflines = 0, $hideselectlimit = 0)
Function to show navigation arrows into lists.
Parameters
int $page Number of page
string $file Page URL (in most cases provided with $_SERVER["PHP_SELF"])
string $options Other url parameters to propagate ("" by default, may include sortfield and sortorder)
integer $nextpage Do we show a next page button
string $betweenarrows HTML content to show between arrows. MUST contains ' ' tags or ' '.
string $afterarrows HTML content to show after arrows. Must NOT contains ' ' tags.
int $limit Max nb of record to show (-1 = no combo with limit, 0 = no limit, > 0 = limit)
int $totalnboflines Total number of records/lines for all pages (if known)
int $hideselectlimit Force to hide select limit
Returns
void
Definition at line 4247 of file functions.lib.php.
References dol_escape_htmltag(), and print.
Referenced by print_barre_liste().
print_liste_field_titre ($name, $file = "", $field = "", $begin = "", $moreparam = "", $moreattrib = "", $sortfield = "", $sortorder = "", $prefix = "", $tooltip = "")
Show title line of an array.
Parameters
string $name Label of field
string $file Url used when we click on sort picto
string $field Field to use for new sorting
string $begin ("" by defaut)
string $moreparam Add more parameters on sort url links ("" by default)
string $moreattrib Options of attribute td ("" by defaut, example: 'align="center"')
string $sortfield Current field used to sort
string $sortorder Current sort order
string $prefix Prefix for css. Use space after prefix to add your own CSS tag.
string $tooltip Tooltip
Returns
void
Definition at line 3919 of file functions.lib.php.
References getTitleFieldOfList(), and print.
Referenced by FormFile\list_of_autoecmfiles(), FormFile\list_of_documents(), FormFile\listOfLinks(), llxFooterVierge(), and print_projecttasks_array().
print_titre ($title)
Show a title.
Parameters
string $title Title to show
Returns
string Title to show
Deprecated:
Use load_fiche_titre instead
See also
load_fiche_titre()
Definition at line 4050 of file functions.lib.php.
References dol_syslog(), and print.
printCommonFooter ($zone = 'private')
Print common footer : conf->global->MAIN_HTML_FOOTER js for switch of menu hider js for conf->global->MAIN_GOOGLE_AN_ID js for conf->global->MAIN_SHOW_TUNING_INFO or $_SERVER["MAIN_SHOW_TUNING_INFO"] js for conf->logbuffer.
Parameters
string $zone 'private' (for private pages) or 'public' (for public pages)
Returns
void
Definition at line 7240 of file functions.lib.php.
References dol_string_nohtmltag(), name, and print.
Referenced by llxFooterSurvey(), and llxFooterVierge().
roundUpToNextMultiple ($n, $x = 5)
Round to next multiple.
Parameters
double $n Number to round up
integer $x Multiple. For example 60 to round up to nearest exact minute for a date with seconds.
Returns
integer Value rounded.
Definition at line 7996 of file functions.lib.php.
setEntity ($currentobject)
Set entity id to use when to create an object.
Parameters
object $currentobject Current object
Returns
mixed Entity id to use (eg. entity = '.setEntity($object))
Definition at line 104 of file functions.lib.php.
setEventMessage ($mesgs, $style = 'mesgs')
Set event message in dol_events session object.
Will be output by calling dol_htmloutput_events. Note: Calling dol_htmloutput_events is done into pages by standard llxFooter() function. Note: Prefer to use setEventMessages instead.
Parameters
mixed $mesgs Message string or array
string $style Which style to use ('mesgs' by default, 'warnings', 'errors')
Returns
void
See also
dol_htmloutput_events()
Definition at line 6381 of file functions.lib.php.
Referenced by DataPolicy\sendMailDataPolicyAdherent(), DataPolicy\sendMailDataPolicyCompany(), DataPolicy\sendMailDataPolicyContact(), setEventMessages(), and show_actions_done().
setEventMessages ($mesg, $mesgs, $style = 'mesgs', $messagekey = '')
Set event messages in dol_events session object.
Will be output by calling dol_htmloutput_events. Note: Calling dol_htmloutput_events is done into pages by standard llxFooter() function.
Parameters
string $mesg Message string
array $mesgs Message array
string $style Which style to use ('mesgs' by default, 'warnings', 'errors')
string $messagekey A key to be used to allow the feature "Never show this message again"
Returns
void
See also
dol_htmloutput_events()
Definition at line 6408 of file functions.lib.php.
References dol_print_error(), dol_syslog(), and setEventMessage().
Referenced by activateModulesRequiredByCountry(), analyseVarsForSqlAndScriptsInjection(), completeFileArrayWithDatabaseInfo(), Website\createFromClone(), pdf_espadon\defineColumnField(), pdf_cornas\defineColumnField(), pdf_eratosthene\defineColumnField(), pdf_cyan\defineColumnField(), pdf_sponge\defineColumnField(), ActionsDatapolicy\doActions(), EmailCollector\doCollectOneCollector(), dol_add_file_process(), dol_delete_file(), dol_move(), dol_remove_file_process(), Website\exportWebSite(), FormMail\get_form(), getAllImages(), Ticket\newMessage(), CommonDocGenerator\pdfTabTitles(), CommonDocGenerator\printStdColumnContent(), pdf_cornas\printStdColumnContent(), redirectToContainer(), InterfaceTicketEmail\runTrigger(), Ticket\sendLogByEmail(), dolReceiptPrinter\sendTestToPrinter(), Ticket\sendTicketMessageByEmail(), dolReceiptPrinter\sendToPrinter(), ExtraFields\setOptionalsFromPost(), FormTicket\showMessageForm(), MultiCurrency\syncRates(), Link\update(), pdf_cyan\write_file(), and pdf_azur\write_file().
showDimensionInBestUnit ($dimension, $unit, $type, $outputlangs, $round = -1, $forceunitoutput = 'no')
Output a dimension with best unit.
Parameters
float $dimension Dimension
int $unit Unit of dimension (Example: 0=kg, -3=g, 98=ounce, 99=pound, ...)
string $type 'weight', 'volume', ...
Translate $outputlangs Translate language object
int $round -1 = non rounding, x = number of decimal
string $forceunitoutput 'no' or numeric (-3, -6, ...) compared to $unit (In most case, this value is value defined into $conf->global->MAIN_WEIGHT_DEFAULT_UNIT)
Returns
string String to show dimensions
Definition at line 4558 of file functions.lib.php.
References measuring_units_string(), and price().
Referenced by pdf_squille\_tableau_tot(), pdf_espadon\_tableau_tot(), and pdf_rouget\_tableau_tot().
showDirectDownloadLink ($object)
Return string with full Url.
The file qualified is the one defined by relative path in $object->last_main_doc
Parameters
Object $object Object
Returns
string Url string
Definition at line 7665 of file functions.lib.php.
utf8_check ($str)
Check if a string is in UTF8.
Parameters
string $str String to check
Returns
boolean True if string is UTF8 or ISO compatible with UTF8, False if not (ISO with special char or Binary)
Definition at line 6702 of file functions.lib.php.
References dol_strlen().
Referenced by CMailFile\check_server_port(), dol_delete_dir_recursive(), dol_dir_list(), dol_print_file(), dol_string_unaccent(), ImportCsv\import_read_record(), Ticket\is_photo_available(), Product\is_photo_available(), Product\liste_photos(), box_external_rss\loadBox(), and show_elem().
vatrate ($rate, $addpercent = false, $info_bits = 0, $usestarfornpr = 0)
Return a string with VAT rate label formated for view output Used into pdf and HTML pages.
Parameters
string $rate Rate value to format ('19.6', '19,6', '19.6', '19,6', '19.6 (CODEX)', ...)
boolean $addpercent Add a percent % sign in output
int $info_bits Miscellaneous information on vat (0=Default, 1=French NPR vat)
int $usestarfornpr -1=Never show, 0 or 1=Use '*' for NPR vat rates
Returns
string String with formated amounts ('19,6' or '19,6' or '8.5% (NPR)' or '8.5% *' or '19,6 (CODEX)')
Definition at line 4332 of file functions.lib.php.
References price().
Referenced by pdf_canelle\_tableau_tot(), pdf_muscadet\_tableau_tot(), pdf_einstein\_tableau_tot(), pdf_cornas\_tableau_tot(), pdf_aurore\_tableau_tot(), pdf_azur\_tableau_tot(), pdf_crabe\_tableau_tot(), Form\constructProductListOption(), dol_print_reduction(), pdf_eratosthene\drawTotalTable(), pdf_cyan\drawTotalTable(), pdf_sponge\drawTotalTable(), ExpenseReportLine\fetch(), CommonDocGenerator\get_substitutionarray_lines(), CommonDocGenerator\get_substitutionarray_object(), CommonDocGenerator\get_substitutionarray_shipment_lines(), ExpenseReportLine\insert(), Form\load_tva(), pdf_getlinevatrate(), Form\select_produits_fournisseurs_list(), and ExpenseReportLine\update().
verifCond ($strRights)
Verify if condition in string is ok or not.
Parameters
string $strRights String with condition to check
Returns
boolean True or False. Return True if strRights is ''
Definition at line 6800 of file functions.lib.php.
References dol_eval().
Referenced by complete_head_from_modules(), ActionsCardService\getFieldList(), ActionsCardProduct\getFieldList(), Export\load_arrays(), and Menubase\menuLoad().
yn ($yesno, $case = 1, $color = 0)
Return yes or no in current language.
Parameters
string $yesno Value to test (1, 'yes', 'true' or 0, 'no', 'false')
integer $case 1=Yes/No, 0=yes/no, 2=Disabled checkbox, 3=Disabled checkbox + Yes/No
int $color 0=texte only, 1=Text is formated with a color font style ('ok' or 'error'), 2=Text is formated with 'ok' color.
Returns
string HTML string
Definition at line 5234 of file functions.lib.php.
Referenced by ActionsCardCommon\assign_values(), AccountLine\getNomUrl(), User\getNomUrl(), ModeleNumRefBarCode\getToolTip(), ModeleProductCode\getToolTip(), ModeleThirdPartyCode\getToolTip(), mod_codecompta_aquarium\info(), Adherent\makeSubstitution(), showSkins(), and top_menu_user().