Dolibarr: Tva Class Reference
Tva Class Reference
Put here description of your class.
Public Member Functions
__construct ($db)
Constructor.
create ($user)
Create in database.
update ($user, $notrigger=0)
Update database.
fetch ($id, $user=null)
Load object in memory from database.
delete ($user)
Delete object in database.
initAsSpecimen ()
Initialise an instance with random values.
solde ($year=0)
Balance of VAT.
tva_sum_collectee ($year=0)
Total of the VAT from invoices emitted by the thirdparty.
tva_sum_payee ($year=0)
VAT payed.
tva_sum_reglee ($year=0)
Total of the VAT payed.
addPayment ($user)
Create in database.
update_fk_bank ($id_bank)
Update link between payment tva and line generate into llx_bank.
getNomUrl ($withpicto=0, $option= '', $notooltip=0, $morecss= '')
Send name clicable (with possibly the picto)
getSommePaiement ()
Return amount of payments already done.
info ($id)
Informations of vat payment object.
getLibStatut ($mode=0)
Retourne le libelle du statut d'une facture (brouillon, validee, abandonnee, payee)
LibStatut ($status, $mode=0)
Renvoi le libelle d'un statut donne.
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0)
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source= 'external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source= 'internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source= '', $code= '')
Delete all links between an object $this and all its contacts.
liste_contact ($statut=-1, $source= 'external', $list=0, $code= '')
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source= 'internal', $order= 'position', $option=0, $activeonly=0, $code= '')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contactid into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table= '', $id=null, $format= '', $id_field= '', $fuser=null, $trigkey= '', $fk_user_field= 'fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source= 'external')
Return list of id of contacts of object.
setProject ($projectid)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id)
Change the payments terms.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder= 'ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix= '')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust= 'none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null)
Add objects linked in llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $clause= 'OR', $alsosametype=1, $orderby= 'sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
updateObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '')
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $rowid= '')
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType= '', $trigkey= '')
Set status of an object.
getCanvas ($id=0, $ref= '')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
display_incoterms ()
Return incoterms informations TODO Use a cache for label get.
getIncotermsForPDF ()
Return incoterms informations for pdf display.
setIncoterms ($id_incoterm, $location)
Define incoterms values of current object.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir= '/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir= '/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafieldsline=0, $defaulttpldir= '/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist= '', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist= '', $defaulttpldir= '/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
addThumbs ($file)
Build thumb Move this into files.lib.php.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($trigger_name, $user)
Call trigger based on this instance.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger= '', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update an extra field value for the current object.
showInputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
showOutputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss= '')
Return HTML string to show a field into a page Code very similar with showOutputField of extra fields.
showOptionals ($extrafields, $mode= 'view', $params=null, $keysuffix= '', $keyprefix= '', $onetrtd=0)
Function to show lines of extrafields with output datas.
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere= '')
Load object in memory from the database.
fetchLinesCommon ($morewhere= '')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
Additional Inherited Members
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref= '', $ref_ext= '')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static commonReplaceThirdparty (DoliDB $db, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
Data Fields inherited from CommonObject
$projet
$note
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
isNull ($info)
Function test if type is null.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare the values to insert.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ()
Function to concat keys of fields.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Put here description of your class.
Definition at line 35 of file tva.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 84 of file tva.class.php.
References db.
Member Function Documentation
addPayment ($user)
Create in database.
Parameters
User $user Object user that insert
Returns
int <0 if KO, rowid in tva table if OK
Definition at line 513 of file tva.class.php.
References CommonObject\call_trigger(), db, dol_now(), dol_print_error(), dol_syslog(), label, note, price2num(), and update_fk_bank().
create ($user)
Create in database.
Parameters
User $user User that create
Returns
int <0 if KO, >0 if OK
Definition at line 96 of file tva.class.php.
References $resql, CommonObject\call_trigger(), db, dol_now(), dol_syslog(), label, and note.
delete ($user)
Delete object in database.
Parameters
User $user User that delete
Returns
int <0 if KO, >0 if OK
Definition at line 312 of file tva.class.php.
References $resql, CommonObject\call_trigger(), db, and dol_syslog().
fetch ($id, $user = null)
Load object in memory from database.
Parameters
int $id id object
User $user User that load
Returns
int <0 if KO, >0 if OK
Definition at line 244 of file tva.class.php.
References $resql, db, dol_syslog(), label, and note.
getLibStatut ($mode = 0)
Retourne le libelle du statut d'une facture (brouillon, validee, abandonnee, payee)
Parameters
int $mode 0=libelle long, 1=libelle court, 2=Picto + Libelle court, 3=Picto, 4=Picto + Libelle long, 5=Libelle court + Picto
Returns
string Libelle
Definition at line 816 of file tva.class.php.
References LibStatut().
getNomUrl ($withpicto = 0, $option = '', $notooltip = 0, $morecss = '')
Send name clicable (with possibly the picto)
Parameters
int $withpicto 0=No picto, 1=Include picto into link, 2=Only picto
string $option link option
int $notooltip 1=Disable tooltip
string $morecss More CSS
Returns
string Chaine with URL
Definition at line 690 of file tva.class.php.
References img_object().
getSommePaiement ()
Return amount of payments already done.
Returns
int Amount of payment already done, <0 if KO
Definition at line 736 of file tva.class.php.
References $resql, db, and dol_syslog().
info ($id)
Informations of vat payment object.
Parameters
int $id Id of vat payment
Returns
int <0 if KO, >0 if OK
Definition at line 769 of file tva.class.php.
References db, dol_print_error(), and dol_syslog().
initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
void
Definition at line 346 of file tva.class.php.
References label, and note.
LibStatut ($status, $mode = 0)
Renvoi le libelle d'un statut donne.
Parameters
int $status Statut
int $mode 0=libelle long, 1=libelle court, 2=Picto + Libelle court, 3=Picto, 4=Picto + Libelle long, 5=Libelle court + Picto
Returns
string Libelle du statut
Definition at line 829 of file tva.class.php.
Referenced by getLibStatut().
solde ($year = 0)
Balance of VAT.
Parameters
int $year Year
Returns
double Amount
Definition at line 368 of file tva.class.php.
References tva_sum_collectee(), tva_sum_payee(), and tva_sum_reglee().
tva_sum_collectee ($year = 0)
Total of the VAT from invoices emitted by the thirdparty.
Parameters
int $year Year
Returns
double Amount
Definition at line 388 of file tva.class.php.
References db, and print.
Referenced by solde().
tva_sum_payee ($year = 0)
VAT payed.
Parameters
int $year Year
Returns
double Amount
Definition at line 429 of file tva.class.php.
References db, and print.
Referenced by solde().
tva_sum_reglee ($year = 0)
Total of the VAT payed.
Parameters
int $year Year
Returns
double Amount
Definition at line 471 of file tva.class.php.
References db, and print.
Referenced by solde().
update ($user, $notrigger = 0)
Update database.
Parameters
User $user User that modify
int $notrigger 0=no, 1=yes (no update trigger)
Returns
int <0 if KO, >0 if OK
Definition at line 176 of file tva.class.php.
References $resql, CommonObject\call_trigger(), db, dol_syslog(), label, and note.
update_fk_bank ($id_bank)
Update link between payment tva and line generate into llx_bank.
Parameters
int $id_bank Id bank account
Returns
int <0 if KO, >0 if OK
Definition at line 664 of file tva.class.php.
References db, and dol_print_error().
Referenced by addPayment().
The documentation for this class was generated from the following file:
htdocs/compta/tva/class/tva.class.php