Dolibarr: doc_generic_odt Class Reference
doc_generic_odt Class Reference
Class to build documents using ODF templates generator.
Public Member Functions
__construct ($db)
Constructor.
info ($langs)
Return description of a module.
write_file ($object, $outputlangs, $srctemplatepath, $hidedetails=0, $hidedesc=0, $hideref=0)
Function to build a document on disk using the generic odt module.
Public Member Functions inherited from CommonDocGenerator
__construct ($db)
Constructor.
get_substitutionarray_user ($user, $outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_mysoc ($mysoc, $outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_thirdparty ($object, $outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_contact ($object, $outputlangs, $array_key= 'object')
Define array with couple subtitution key => subtitution value.
get_substitutionarray_other ($outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_object ($object, $outputlangs, $array_key= 'object')
Define array with couple substitution key => substitution value.
get_substitutionarray_lines ($line, $outputlangs)
Define array with couple substitution key => substitution value.
get_substitutionarray_shipment ($object, $outputlangs, $array_key= 'object')
Define array with couple substitution key => substitution value.
get_substitutionarray_shipment_lines ($line, $outputlangs)
Define array with couple substitution key => substitution value.
get_substitutionarray_each_var_object (&$object, $outputlangs, $recursive=true)
Define array with couple subtitution key => subtitution value.
fill_substitutionarray_with_extrafields ($object, $array_to_fill, $extrafields, $array_key, $outputlangs)
Fill array with couple extrafield key => extrafield value.
printRect ($pdf, $x, $y, $l, $h, $hidetop=0, $hidebottom=0)
Rect pdf.
columnSort ($a, $b)
uasort callback function to Sort colums fields
prepareArrayColumnField ($object, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0)
Prepare Array Column Field.
getColumnContentWidth ($colKey)
get column content width from column key
getColumnContentXStart ($colKey)
get column content X (abscissa) left position from column key
getColumnRank ($colKey)
get column position rank from column key
insertNewColumnDef ($newColKey, $defArray, $targetCol=false, $insertAfterTarget=false)
get column position rank from column key
printStdColumnContent ($pdf, &$curY, $colKey, $columnText= '')
print standard column content
getColumnStatus ($colKey)
get column status from column key
pdfTabTitles (&$pdf, $tab_top, $tab_height, $outputlangs, $hidetop=0)
Print standard column content.
Additional Inherited Members
Static Public Member Functions inherited from ModeleThirdPartyDoc
static liste_modeles ($db, $maxfilenamelength=0)
Return list of active generation modules.
Detailed Description
Class to build documents using ODF templates generator.
Definition at line 37 of file doc_generic_odt.modules.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 57 of file doc_generic_odt.modules.php.
References db, description, name, and type.
Member Function Documentation
info ($langs)
Return description of a module.
Parameters
Translate $langs Object language
Returns
string Description
Definition at line 93 of file doc_generic_odt.modules.php.
References db, description, dol_dir_list(), and img_warning().
write_file ($object, $outputlangs, $srctemplatepath, $hidedetails = 0, $hidedesc = 0, $hideref = 0)
Function to build a document on disk using the generic odt module.
Parameters
Societe $object Object source to build document
Translate $outputlangs Lang output object
string $srctemplatepath Full path of source filename for generator using a template file
int $hidedetails Do not show line details
int $hidedesc Do not show desc
int $hideref Do not show ref
Returns
int 1 if OK, <=0 if KO
Definition at line 189 of file doc_generic_odt.modules.php.
References complete_substitutions_array(), db, dol_mkdir(), dol_now(), dol_print_date(), dol_sanitizeFileName(), dol_string_nospecial(), dol_syslog(), CommonDocGenerator\get_substitutionarray_contact(), CommonDocGenerator\get_substitutionarray_mysoc(), CommonDocGenerator\get_substitutionarray_other(), CommonDocGenerator\get_substitutionarray_thirdparty(), and CommonDocGenerator\get_substitutionarray_user().
The documentation for this class was generated from the following file:
htdocs/core/modules/societe/doc/doc_generic_odt.modules.php