Dolibarr: htdocs/core/lib/company.lib.php File Reference
company.lib.php File Reference
Module societe
Ensemble de fonctions de base pour le module societe.
Functions
societe_prepare_head (Societe $object)
Return array of tabs to used on pages for third parties cards.
societe_prepare_head2 ($object)
Return array of tabs to used on page.
societe_admin_prepare_head ()
Return array head with list of tabs to view object informations.
getCountry ($searchkey, $withcode= '', $dbtouse=0, $outputlangs= '', $entconv=1, $searchlabel= '')
Return country label, code or id from an id, code or label.
getState ($id, $withcode= '', $dbtouse=0, $withregion=0, $outputlangs= '', $entconv=1)
Return state translated from an id.
currency_name ($code_iso, $withcode= '', $outputlangs=null)
Return label of currency or code+label.
getFormeJuridiqueLabel ($code)
Retourne le nom traduit de la forme juridique.
getCountriesInEEC ()
Return list of countries that are inside the EEC (European Economic Community) TODO Add a field into country dictionary.
isInEEC ($object)
Return if a country of an object is inside the EEC (European Economic Community)
show_projects ($conf, $langs, $db, $object, $backtopage= '', $nocreatelink=0, $morehtmlright= '')
Show html area for list of projects.
show_contacts ($conf, $langs, $db, $object, $backtopage= '')
Show html area for list of contacts.
show_actions_todo ($conf, $langs, $db, $filterobj, $objcon= '', $noprint=0, $actioncode= '')
Show html area with actions to do.
show_actions_done ($conf, $langs, $db, $filterobj, $objcon= '', $noprint=0, $actioncode= '', $donetodo= 'done', $filters=array(), $sortfield= 'a.datep, a.id', $sortorder= 'DESC')
Show html area with actions (done or not, ignore the name of function).
show_subsidiaries ($conf, $langs, $db, $object)
Show html area for list of subsidiaries.
Detailed Description
Ensemble de fonctions de base pour le module societe.
Definition in file company.lib.php.
Function Documentation
currency_name ($code_iso, $withcode = '', $outputlangs = null)
Return label of currency or code+label.
Parameters
string $code_iso Code iso of currency
int $withcode '1'=show code + label
Translate $outputlangs Output language
Returns
string Label translated of currency
Definition at line 572 of file company.lib.php.
References $resql.
Referenced by Form\form_multicurrency_code().
getCountriesInEEC ()
Return list of countries that are inside the EEC (European Economic Community) TODO Add a field into country dictionary.
Returns
array Array of countries code in EEC
Definition at line 651 of file company.lib.php.
Referenced by isInEEC().
getCountry ($searchkey, $withcode = '', $dbtouse = 0, $outputlangs = '', $entconv = 1, $searchlabel = '')
Return country label, code or id from an id, code or label.
Parameters
int $searchkey Id or code of country to search
string $withcode '0'=Return label, '1'=Return code + label, '2'=Return code from id, '3'=Return id from code, 'all'=Return array('id'=>,'code'=>,'label'=>)
DoliDB $dbtouse Database handler (using in global way may fail because of conflicts with some autoload features)
Translate $outputlangs Langs object for output translation
int $entconv 0=Return value without entities and not converted to output charset, 1=Ready for html output
int $searchlabel Label of country to search (warning: searching on label is not reliable)
Returns
mixed Integer with country id or String with country code or translated country name or Array('id','code','label') or 'NotDefined'
Definition at line 431 of file company.lib.php.
References $resql, and dol_print_error().
Referenced by ActionsCardCommon\assign_post(), createProductOrService(), createThirdParty(), Entrepot\fetch(), Product\fetch(), CommonObject\getFullAddress(), llxFooterVierge(), Societe\setMysoc(), show_contacts(), updateContact(), updateProductOrService(), and updateThirdParty().
getFormeJuridiqueLabel ($code)
Retourne le nom traduit de la forme juridique.
Parameters
string $code Code de la forme juridique
Returns
string Nom traduit du pays
Definition at line 616 of file company.lib.php.
References $resql, and dol_syslog().
Referenced by CommonDocGenerator\get_substitutionarray_mysoc(), html_print_stripe_footer(), and pdf_pagefoot().
getState ($id, $withcode = '', $dbtouse = 0, $withregion = 0, $outputlangs = '', $entconv = 1)
Return state translated from an id.
Return value is always utf8 encoded and without entities.
Parameters
int $id id of state (province/departement)
int $withcode '0'=Return label, '1'=Return string code + label, '2'=Return code, 'all'=return array('id'=>,'code'=>,'label'=>)
DoliDB $dbtouse Database handler (using in global way may fail because of conflicts with some autoload features)
int $withregion '0'=Ignores region, '1'=Add region name/code/id as needed to output,
Translate $outputlangs Langs object for output translation, not fully implemented yet
int $entconv 0=Return value without entities and not converted to output charset, 1=Ready for html output
Returns
string|array String with state code or state name or Array('id','code','label')/Array('id','code','label','region_code','region')
Definition at line 496 of file company.lib.php.
References $resql, dol_print_error(), and dol_syslog().
Referenced by CommonDocGenerator\get_substitutionarray_contact(), CommonDocGenerator\get_substitutionarray_mysoc(), CommonDocGenerator\get_substitutionarray_thirdparty(), CommonObject\getFullAddress(), pdf_build_address(), and Societe\setMysoc().
isInEEC ($object)
Return if a country of an object is inside the EEC (European Economic Community)
Parameters
Object $object Object
Returns
boolean true = country inside EEC, false = country outside EEC
Definition at line 708 of file company.lib.php.
References getCountriesInEEC().
Referenced by Stripe\customerStripe(), get_default_tva(), Form\load_tva(), and InterfaceStripe\runTrigger().
show_actions_done ($conf, $langs, $db, $filterobj, $objcon = '', $noprint = 0, $actioncode = '', $donetodo = 'done', $filters = array(), $sortfield = 'a.datep, a.id' , $sortorder = 'DESC')
Show html area with actions (done or not, ignore the name of function).
Note: Global parameter $param must be defined.
Parameters
Conf $conf Object conf
Translate $langs Object langs
DoliDB $db Object db
mixed $filterobj Filter on object Adherent|Societe|Project|Product|CommandeFournisseur|Dolresource|Ticket|... to list events linked to an object
Contact $objcon Filter on object contact to filter events on a contact
int $noprint Return string but does not output it
string $actioncode Filter on actioncode
string $donetodo Filter on event 'done' or 'todo' or ''=nofilter (all).
array $filters Filter on other fields
string $sortfield Sort field
string $sortorder Sort order
Returns
string|void Return html part or void if noprint is 1
Definition at line 1216 of file company.lib.php.
References $formactions, $resql, dol_getdate(), dol_include_once(), dol_now(), dol_print_date(), dol_print_error(), dol_print_phone(), dol_syslog(), dol_trunc(), dolGetElementUrl(), getTitleFieldOfList(), img_object(), img_picto(), img_warning(), natural_search(), print, and setEventMessage().
Referenced by ActionsContactCardDefault\assign_values(), ActionsAdherentCardDefault\assign_values(), and show_actions_todo().
show_actions_todo ($conf, $langs, $db, $filterobj, $objcon = '', $noprint = 0, $actioncode = '')
Show html area with actions to do.
Parameters
Conf $conf Object conf
Translate $langs Object langs
DoliDB $db Object db
Adherent | Societe $filterobj Object thirdparty or member
Contact $objcon Object contact
int $noprint Return string but does not output it
int $actioncode Filter on actioncode
Returns
string|void Return html part or void if noprint is 1
Definition at line 1189 of file company.lib.php.
References print, and show_actions_done().
Referenced by ActionsContactCardDefault\assign_values(), and ActionsAdherentCardDefault\assign_values().
show_contacts ($conf, $langs, $db, $object, $backtopage = '')
Show html area for list of contacts.
Parameters
Conf $conf Object conf
Translate $langs Object langs
DoliDB $db Database handler
Societe $object Third party object
string $backtopage Url to go once contact is created
Returns
int
Definition at line 857 of file company.lib.php.
References dol_escape_htmltag(), dol_print_error(), dol_sort_array(), dol_syslog(), dolGetButtonTitle(), getCountry(), GETPOST(), getTitleFieldOfList(), img_edit(), img_object(), load_fiche_titre(), natural_search(), and print.
show_projects ($conf, $langs, $db, $object, $backtopage = '', $nocreatelink = 0, $morehtmlright = '')
Show html area for list of projects.
Parameters
Conf $conf Object conf
Translate $langs Object langs
DoliDB $db Database handler
Object $object Third party object
string $backtopage Url to go once contact is created
int $nocreatelink 1=Hide create project link
string $morehtmlright More html on right of title
Returns
int
Definition at line 731 of file company.lib.php.
References dol_print_error(), dolGetButtonTitle(), img_object(), load_fiche_titre(), price(), and print.
show_subsidiaries ($conf, $langs, $db, $object)
Show html area for list of subsidiaries.
Parameters
Conf $conf Object conf
Translate $langs Object langs
DoliDB $db Database handler
Societe $object Third party object
Returns
int
Definition at line 1711 of file company.lib.php.
References img_edit(), load_fiche_titre(), and print.
societe_admin_prepare_head ()
Return array head with list of tabs to view object informations.
Returns
array head array with tabs
Definition at line 381 of file company.lib.php.
References complete_head_from_modules().
societe_prepare_head (Societe $object)
Return array of tabs to used on pages for third parties cards.
Parameters
Societe $object Object company shown
Returns
array Array of tabs
Definition at line 42 of file company.lib.php.
References $resql, complete_head_from_modules(), Link\count(), dol_dir_list(), dol_print_error(), GETPOST(), and CommonObject\liste_contact().
Referenced by ActionsCardCommon\assign_values().
societe_prepare_head2 ($object)
Return array of tabs to used on page.
Parameters
Object $object Object for tabs
Returns
array Array of tabs
Definition at line 355 of file company.lib.php.