Dolibarr: Orders Class Reference
Orders Class Reference
Public Member Functions
__construct ()
Constructor.
get ($id, $contact_list=1)
Get properties of an order object.
post ($request_data=null)
Create order object.
getLines ($id)
Get lines of an order.
postLine ($id, $request_data=null)
Add a line to given order.
putLine ($id, $lineid, $request_data=null)
Update a line to given order.
deleteLine ($id, $lineid)
Delete a line to given order.
postContact ($id, $contactid, $type)
Add a contact type of given order.
deleteContact ($id, $rowid)
Delete a contact type of given order.
put ($id, $request_data=null)
Update order general fields (won't touch lines of order)
delete ($id)
Delete order.
validate ($id, $idwarehouse=0, $notrigger=0)
Validate an order.
reopen ($id)
Tag the order as validated (opened)
setinvoiced ($id)
Classify the order as invoiced.
close ($id, $notrigger=0)
Close an order (Classify it as "Delivered")
settodraft ($id, $idwarehouse=-1)
Set an order to draft.
createOrderFromProposal ($proposalid)
Create an order using an existing proposal.
Public Member Functions inherited from DolibarrApi
__construct ($db, $cachedir= '', $refreshCache=false)
Constructor.
Protected Member Functions
_cleanObjectDatas ($object)
Clean sensible object datas.
Protected Member Functions inherited from DolibarrApi
_cleanObjectDatas ($object)
Executed method when API is called without parameter.
_checkFilters ($sqlfilters)
Return if a $sqlfilters parameter is valid.
Private Member Functions
_validate ($data)
Validate fields before create or update object.
Additional Inherited Members
Static Protected Member Functions inherited from DolibarrApi
static _checkAccessToResource ($resource, $resource_id=0, $dbtablename= '', $feature2= '', $dbt_keyfield= 'fk_soc', $dbt_select= 'rowid')
Check user access to a resource.
static _forge_criteria_callback ($matches)
Function to forge a SQL criteria.
Detailed Description
Definition at line 29 of file api_orders.class.php.
Member Function Documentation
_cleanObjectDatas ($object) protected
Clean sensible object datas.
Parameters
object $object Object to clean
Returns
array Array of cleaned object properties
Definition at line 842 of file api_orders.class.php.
Referenced by close(), createOrderFromProposal(), get(), getLines(), putLine(), setinvoiced(), settodraft(), and validate().
_validate ($data) private
Validate fields before create or update object.
Parameters
array $data Array with data to verify
Returns
array
Exceptions
RestException
Definition at line 864 of file api_orders.class.php.
Referenced by post().
close ($id, $notrigger = 0)
Close an order (Classify it as "Delivered")
Parameters
int $id Order ID
int $notrigger Disabled triggers
POST {id}/close
Returns
int
Definition at line 707 of file api_orders.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
createOrderFromProposal ($proposalid)
Create an order using an existing proposal.
Parameters
int $proposalid Id of the proposal
POST /createfromproposal/{proposalid}
Returns
int
Exceptions
400
401
404
405
Definition at line 804 of file api_orders.class.php.
References _cleanObjectDatas(), and db.
delete ($id)
Delete order.
Parameters
int $id Order ID
Returns
array
Definition at line 526 of file api_orders.class.php.
References DolibarrApi\_checkAccessToResource().
deleteContact ($id, $rowid)
Delete a contact type of given order.
Parameters
int $id Id of order to update
int $rowid Row key of the contact in the array contact_ids.
DELETE {id}/contact/{rowid}
Returns
int
Exceptions
401
404
500
Definition at line 453 of file api_orders.class.php.
References DolibarrApi\_checkAccessToResource().
deleteLine ($id, $lineid)
Delete a line to given order.
Parameters
int $id Id of order to update
int $lineid Id of line to delete
DELETE {id}/lines/{lineid}
Returns
int
Exceptions
401
404
Definition at line 378 of file api_orders.class.php.
References DolibarrApi\_checkAccessToResource().
get ($id, $contact_list = 1)
Get properties of an order object.
Return an array with order informations
Parameters
int $id ID of order
int $contact_list 0: Returned array of contacts/addresses contains all properties, 1: Return array contains just id
Returns
array|mixed data without useless information
Exceptions
RestException
Definition at line 65 of file api_orders.class.php.
References DolibarrApi\_checkAccessToResource(), DolibarrApi\_checkFilters(), _cleanObjectDatas(), and dol_syslog().
getLines ($id)
Get lines of an order.
Parameters
int $id Id of order
GET {id}/lines
Returns
int
Definition at line 223 of file api_orders.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
post ($request_data = null)
Create order object.
Parameters
array $request_data Request data
Returns
int ID of order
Definition at line 188 of file api_orders.class.php.
References _validate().
postContact ($id, $contactid, $type)
Add a contact type of given order.
Parameters
int $id Id of order to update
int $contactid Id of contact to add
string $type Type of the contact (BILLING, SHIPPING, CUSTOMER)
POST {id}/contact/{contactid}/{type}
Returns
int
Exceptions
401
404
Definition at line 416 of file api_orders.class.php.
References DolibarrApi\_checkAccessToResource().
postLine ($id, $request_data = null)
Add a line to given order.
Parameters
int $id Id of order to update
array $request_data OrderLine data
POST {id}/lines
Returns
int
Definition at line 255 of file api_orders.class.php.
References DolibarrApi\_checkAccessToResource().
put ($id, $request_data = null)
Update order general fields (won't touch lines of order)
Parameters
int $id Id of order to update
array $request_data Datas
Returns
int
Definition at line 485 of file api_orders.class.php.
References DolibarrApi\_checkAccessToResource().
putLine ($id, $lineid, $request_data = null)
Update a line to given order.
Parameters
int $id Id of order to update
int $lineid Id of line to update
array $request_data OrderLine data
PUT {id}/lines/{lineid}
Returns
object
Definition at line 317 of file api_orders.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
reopen ($id)
Tag the order as validated (opened)
Function used when order is reopend after being closed.
Parameters
int $id Id of the order
POST {id}/reopen
Returns
int
Exceptions
304
400
401
404
405
Definition at line 626 of file api_orders.class.php.
setinvoiced ($id)
Classify the order as invoiced.
Could be also called setbilled
Parameters
int $id Id of the order
POST {id}/setinvoiced
Returns
int
Exceptions
400
401
404
405
Definition at line 664 of file api_orders.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
settodraft ($id, $idwarehouse = -1)
Set an order to draft.
Parameters
int $id Order ID
int $idwarehouse Warehouse ID to use for stock change (Used only if option STOCK_CALCULATE_ON_VALIDATE_ORDER is on)
POST {id}/settodraft
Returns
array
Definition at line 753 of file api_orders.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
validate ($id, $idwarehouse = 0, $notrigger = 0)
Validate an order.
If you get a bad value for param notrigger check, provide this in body { "idwarehouse": 0, "notrigger": 0 }
Parameters
int $id Order ID
int $idwarehouse Warehouse ID
int $notrigger 1=Does not execute triggers, 0= execute triggers
POST {id}/validate
Exceptions
304
401
404
500
Returns
array
Definition at line 574 of file api_orders.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
The documentation for this class was generated from the following file:
htdocs/commande/class/api_orders.class.php