Dolibarr: box_factures Class Reference
box_factures Class Reference
Class to manage the box to show last invoices.
Public Member Functions
__construct ($db, $param)
Constructor.
loadBox ($max=5)
Load data into info_box_contents array to show array later.
showBox ($head=null, $contents=null, $nooutput=0)
Method to show box.
Public Member Functions inherited from ModeleBoxes
__construct ($db, $param= '')
Constructor.
error ()
Return last error message.
fetch ($rowid)
Load a box line from its rowid.
outputBox ($head=null, $contents=null)
Standard method to get content of a box.
showBox ($head=null, $contents=null, $nooutput=0)
Standard method to show a box (usage by boxes not mandatory, a box can still use its own showBox function)
Additional Inherited Members
Static Public Member Functions inherited from ModeleBoxes
static getWidgetsList ($forcedirwidget=null)
Return list of widget.
Detailed Description
Class to manage the box to show last invoices.
Definition at line 31 of file box_factures.php.
Constructor & Destructor Documentation
__construct ($db, $param)
Constructor.
Parameters
DoliDB $db Database handler
string $param More parameters
Definition at line 55 of file box_factures.php.
References db.
Member Function Documentation
loadBox ($max = 5)
Load data into info_box_contents array to show array later.
Parameters
int $max Maximum number of records to load
Returns
void
Definition at line 70 of file box_factures.php.
References dol_now(), dol_print_date(), dol_strlen(), img_warning(), and price().
showBox ($head = null, $contents = null, $nooutput = 0)
Method to show box.
Parameters
array $head Array with properties of box title
array $contents Array with properties of box lines
int $nooutput No print, only return string
Returns
string
Definition at line 212 of file box_factures.php.
The documentation for this class was generated from the following file:
htdocs/core/boxes/box_factures.php