Dolibarr: htdocs/webservices/server_productorservice.php File Reference
server_productorservice.php File Reference
File that is entry point to call Dolibarr WebServices.
Functions
getProductOrService ($authentication, $id= '', $ref= '', $ref_ext= '', $lang= '')
Get produt or service.
createProductOrService ($authentication, $product)
Create an invoice.
updateProductOrService ($authentication, $product)
Update a product or service.
deleteProductOrService ($authentication, $listofidstring)
Delete a product or service.
getListOfProductsOrServices ($authentication, $filterproduct)
getListOfProductsOrServices
getProductsForCategory ($authentication, $id, $lang= '')
Get list of products for a category.
Detailed Description
File that is entry point to call Dolibarr WebServices.
Definition in file server_productorservice.php.
Function Documentation
createProductOrService ($authentication, $product)
Create an invoice.
Parameters
array $authentication Array of authentication information
Product $product Product
Returns
array Array result
Definition at line 471 of file server_productorservice.php.
References check_authentication(), db, dol_now(), dol_syslog(), and getCountry().
deleteProductOrService ($authentication, $listofidstring)
Delete a product or service.
Parameters
array $authentication Array of authentication information
string $listofidstring List of id with comma
Returns
array Array result
Definition at line 827 of file server_productorservice.php.
References check_authentication(), dol_now(), and dol_syslog().
getListOfProductsOrServices ($authentication, $filterproduct)
getListOfProductsOrServices
Parameters
array $authentication Array of authentication information
array $filterproduct Filter fields
Returns
array Array result
Definition at line 924 of file server_productorservice.php.
References $resql, check_authentication(), dol_now(), and dol_syslog().
getProductOrService ($authentication, $id = '', $ref = '', $ref_ext = '', $lang = '')
Get produt or service.
Parameters
array $authentication Array of authentication information
int $id Id of object
string $ref Ref of object
string $ref_ext Ref external of object
string $lang Lang to force
Returns
mixed
French VAT NPR
Spanish local taxes
Definition at line 336 of file server_productorservice.php.
References check_authentication(), dol_print_date(), dol_syslog(), and get_exdir().
getProductsForCategory ($authentication, $id, $lang = '')
Get list of products for a category.
Parameters
array $authentication Array of authentication information
array $id Category id
$lang $lang Force lang
Returns
array Array result
Definition at line 1001 of file server_productorservice.php.
References check_authentication(), dol_print_date(), dol_syslog(), and get_exdir().
updateProductOrService ($authentication, $product)
Update a product or service.
Parameters
array $authentication Array of authentication information
Product $product Product
Returns
array Array result
Definition at line 639 of file server_productorservice.php.
References check_authentication(), db, dol_now(), dol_syslog(), and getCountry().