Dolibarr: Product Class Reference
Product Class Reference
Class to manage products or services.
Public Member Functions
__construct ($db)
Constructor.
check ()
Check that ref and label are ok.
create ($user, $notrigger=0)
Insert product into database.
verify ()
Check properties of product are ok (like name, barcode, ...).
check_barcode ($valuetotest, $typefortest)
Check barcode.
update ($id, $user, $notrigger=false, $action= 'update')
Update a record into database.
delete (User $user, $notrigger=0)
Delete a product from database (if not used)
setMultiLangs ($user)
Update or add a translation for a product.
delMultiLangs ($langtodelete, $user)
Delete a language for this product.
getMultiLangs ()
Load array this->multilangs.
log_price_delete ($user, $rowid)
Delete a price line.
getSellPrice ($thirdparty_seller, $thirdparty_buyer, $pqp=0)
Return price of sell of a product for a seller/buyer/product.
get_buyprice ($prodfournprice, $qty, $product_id=0, $fourn_ref= '', $fk_soc=0)
Read price used by a provider.
updatePrice ($newprice, $newpricebase, $user, $newvat= '', $newminprice=0, $level=0, $newnpr=0, $newpbq=0, $ignore_autogen=0, $localtaxes_array=array(), $newdefaultvatcode= '')
Modify customer price of a product/Service.
setPriceExpression ($expression_id)
Sets the supplier price expression.
fetch ($id= '', $ref= '', $ref_ext= '', $barcode= '', $ignore_expression=0)
Load a product in memory from database.
load_stats_propale ($socid=0)
Charge tableau des stats propale pour le produit/service.
load_stats_proposal_supplier ($socid=0)
Charge tableau des stats propale pour le produit/service.
load_stats_commande ($socid=0, $filtrestatut= '', $forVirtualStock=0)
Charge tableau des stats commande client pour le produit/service.
load_stats_commande_fournisseur ($socid=0, $filtrestatut= '', $forVirtualStock=0)
Charge tableau des stats commande fournisseur pour le produit/service.
load_stats_sending ($socid=0, $filtrestatut= '', $forVirtualStock=0)
Charge tableau des stats expedition client pour le produit/service.
load_stats_reception ($socid=0, $filtrestatut= '', $forVirtualStock=0)
Charge tableau des stats réception fournisseur pour le produit/service.
load_stats_contrat ($socid=0)
Charge tableau des stats contrat pour le produit/service.
load_stats_facture ($socid=0)
Charge tableau des stats facture pour le produit/service.
load_stats_facture_fournisseur ($socid=0)
Charge tableau des stats facture pour le produit/service.
get_nb_vente ($socid, $mode, $filteronproducttype=-1, $year=0, $morefilter= '')
Return nb of units or customers invoices in which product is included.
get_nb_achat ($socid, $mode, $filteronproducttype=-1, $year=0, $morefilter= '')
Return nb of units or supplier invoices in which product is included.
get_nb_propal ($socid, $mode, $filteronproducttype=-1, $year=0, $morefilter= '')
Return nb of units or proposals in which product is included.
get_nb_propalsupplier ($socid, $mode, $filteronproducttype=-1, $year=0, $morefilter= '')
Return nb of units or proposals in which product is included.
get_nb_order ($socid, $mode, $filteronproducttype=-1, $year=0, $morefilter= '')
Return nb of units or orders in which product is included.
get_nb_ordersupplier ($socid, $mode, $filteronproducttype=-1, $year=0, $morefilter= '')
Return nb of units or orders in which product is included.
get_nb_contract ($socid, $mode, $filteronproducttype=-1, $year=0, $morefilter= '')
Return nb of units or orders in which product is included.
add_sousproduit ($id_pere, $id_fils, $qty, $incdec=1)
Link a product/service to a parent product/service.
update_sousproduit ($id_pere, $id_fils, $qty, $incdec=1)
Modify composed product.
del_sousproduit ($fk_parent, $fk_child)
Retire le lien entre un sousproduit et un produit/service.
is_sousproduit ($fk_parent, $fk_child)
Verifie si c'est un sous-produit.
add_fournisseur ($user, $id_fourn, $ref_fourn, $quantity)
Add a supplier price for the product.
list_suppliers ()
Renvoie la liste des fournisseurs du produit/service.
clone_price ($fromId, $toId)
Recopie les prix d'un produit/service sur un autre.
clone_associations ($fromId, $toId)
Clone links between products.
clone_fournisseurs ($fromId, $toId)
Recopie les fournisseurs et prix fournisseurs d'un produit/service sur un autre.
fetch_prod_arbo ($prod, $compl_path="", $multiply=1, $level=1, $id_parent=0)
Fonction recursive uniquement utilisee par get_arbo_each_prod, recompose l'arborescence des sousproduits Define value of this->res.
get_arbo_each_prod ($multiply=1)
Build the tree of subproducts into an array this->sousprods is loaded by this->get_sousproduits_arbo()
hasFatherOrChild ()
Return all parent products for current product (first level only)
hasVariants ()
Return if a product has variants or not.
isVariant ()
Return if loaded product is a variant.
getFather ()
Return all parent products for current product (first level only)
getChildsArbo ($id, $firstlevelonly=0, $level=1)
Return childs of product $id.
get_sousproduits_arbo ()
Return tree of all subproducts for product.
getNomUrl ($withpicto=0, $option= '', $maxlength=0, $save_lastsearch_value=-1, $notooltip=0)
Return clicable link of object (with eventually picto)
generateDocument ($modele, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0)
Create a document onto disk according to template module.
getLibStatut ($mode=0, $type=0)
Return label of status of object.
LibStatut ($status, $mode=0, $type=0)
Return label of a given status.
getLibFinished ()
Retourne le libelle du finished du produit.
correct_stock ($user, $id_entrepot, $nbpiece, $movement, $label= '', $price=0, $inventorycode= '', $origin_element= '', $origin_id=null)
Adjust stock in a warehouse for product.
correct_stock_batch ($user, $id_entrepot, $nbpiece, $movement, $label= '', $price=0, $dlc= '', $dluo= '', $lot= '', $inventorycode= '', $origin_element= '', $origin_id=null)
Adjust stock in a warehouse for product with batch number.
load_stock ($option= '')
Load information about stock of a product into ->stock_reel, ->stock_warehouse[] (including stock_warehouse[idwarehouse]->detail_batch for batch products) This function need a lot of load.
load_virtual_stock ()
Load value ->stock_theorique of a product.
loadBatchInfo ($batch)
Load existing information about a serial.
add_photo ($sdir, $file)
Move an uploaded file described into $file array into target directory $sdir.
is_photo_available ($sdir)
Return if at least one photo is available.
liste_photos ($dir, $nbmax=0)
Retourne tableau de toutes les photos du produit.
delete_photo ($file)
Efface la photo du produit et sa vignette.
get_image_size ($file)
Load size of image file.
load_state_board ()
Load indicators this->nb for the dashboard.
isProduct ()
Return if object is a product.
isService ()
Return if object is a product.
get_barcode ($object, $type= '')
Get a barcode from the module to generate barcode values.
initAsSpecimen ()
Initialise an instance with random values.
getLabelOfUnit ($type= 'long')
Returns the text label from units dictionary.
hasbatch ()
Return if object has a sell-by date or eat-by date.
min_recommended_price ()
Return minimum product recommended price.
setCategories ($categories)
Sets object to supplied categories.
generateMultiprices (User $user, $baseprice, $price_type, $price_vat, $npr, $psq)
Generates prices for a product based on product multiprice generation rules.
getRights ()
Returns the rights used for this class.
info ($id)
Load information for tab info.
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0)
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source= 'external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source= 'internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source= '', $code= '')
Delete all links between an object $this and all its contacts.
liste_contact ($statut=-1, $source= 'external', $list=0, $code= '')
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source= 'internal', $order= 'position', $option=0, $activeonly=0, $code= '')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contactid into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table= '', $id=null, $format= '', $id_field= '', $fuser=null, $trigkey= '', $fk_user_field= 'fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source= 'external')
Return list of id of contacts of object.
setProject ($projectid)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id)
Change the payments terms.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder= 'ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix= '')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust= 'none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null)
Add objects linked in llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $clause= 'OR', $alsosametype=1, $orderby= 'sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
updateObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '')
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $rowid= '')
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType= '', $trigkey= '')
Set status of an object.
getCanvas ($id=0, $ref= '')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
display_incoterms ()
Return incoterms informations TODO Use a cache for label get.
getIncotermsForPDF ()
Return incoterms informations for pdf display.
setIncoterms ($id_incoterm, $location)
Define incoterms values of current object.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir= '/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir= '/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafieldsline=0, $defaulttpldir= '/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist= '', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist= '', $defaulttpldir= '/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
addThumbs ($file)
Build thumb Move this into files.lib.php.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($trigger_name, $user)
Call trigger based on this instance.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger= '', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update an extra field value for the current object.
showInputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
showOutputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss= '')
Return HTML string to show a field into a page Code very similar with showOutputField of extra fields.
showOptionals ($extrafields, $mode= 'view', $params=null, $keysuffix= '', $keyprefix= '', $onetrtd=0)
Function to show lines of extrafields with output datas.
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere= '')
Load object in memory from the database.
fetchLinesCommon ($morewhere= '')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
Static Public Member Functions
static replaceThirdparty (DoliDB $db, $origin_id, $dest_id)
Function used to replace a thirdparty id with another one.
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref= '', $ref_ext= '')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static commonReplaceThirdparty (DoliDB $db, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
Data Fields
$multiprices =array()
Arrays for multiprices.
$price_by_qty
Price by quantity arrays.
$default_vat_code
Default VAT code for product (link to code into llx_c_tva but without foreign keys)
$tva_tx
Default VAT rate of product.
$tva_npr =0
French VAT NPR (0 or 1)
$localtax1_tx
Other local taxes.
$pmp
Average price value for product entry into stock (PMP)
$desiredstock =0
Ask for replenishment when $desiredstock < $stock_reel.
$duration_unit
Exoiration unit.
$weight
Unites de mesure.
$imgWidth
Size of image.
$product_fourn_id
Id du fournisseur.
$product_id_already_linked
Product ID already linked to a reference supplier.
$stock_warehouse =array()
Contains detail of stock of product into each warehouse.
$ref_fourn
const TYPE_PRODUCT = 0
Regular product.
const TYPE_SERVICE = 1
Service.
const TYPE_ASSEMBLYKIT = 2
Advanced feature: assembly kit.
const TYPE_STOCKKIT = 3
Advanced feature: stock kit.
Data Fields inherited from CommonObject
$projet
$note
Protected Attributes
$table_ref_field = 'ref'
{}
Private Member Functions
_log_price ($user, $level=0)
Insert a track that we changed a customer price.
_get_stats ($sql, $mode, $year=0)
Return an array formated for showing graphs.
Additional Inherited Members
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
isNull ($info)
Function test if type is null.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare the values to insert.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ()
Function to concat keys of fields.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage products or services.
Definition at line 45 of file product.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 403 of file product.class.php.
References db.
Member Function Documentation
_get_stats ($sql, $mode, $year = 0) private
Return an array formated for showing graphs.
Parameters
string $sql Request to execute
string $mode 'byunit'=number of unit, 'bynumber'=nb of entities
int $year Year (0=current year)
Returns
array <0 if KO, result[month]=array(valuex,valuey) where month is 0 to 11
Definition at line 2887 of file product.class.php.
References $resql, db, dol_mktime(), dol_print_date(), dol_strlen(), and dol_trunc().
Referenced by get_nb_achat(), get_nb_contract(), get_nb_order(), get_nb_ordersupplier(), get_nb_propal(), get_nb_propalsupplier(), and get_nb_vente().
_log_price ($user, $level = 0) private
Insert a track that we changed a customer price.
Parameters
User $user User making change
int $level price level to change
Returns
int <0 if KO, >0 if OK
Definition at line 1510 of file product.class.php.
References $resql, db, dol_now(), dol_print_error(), dol_syslog(), and price().
Referenced by create(), and updatePrice().
add_fournisseur ($user, $id_fourn, $ref_fourn, $quantity)
Add a supplier price for the product.
Note: Duplicate ref is accepted for different quantity only, or for different companies.
Parameters
User $user User that make link
int $id_fourn Supplier id
string $ref_fourn Supplier ref
float $quantity Quantity minimum for price
Returns
int < 0 if KO, 0 if link already exists for this product, > 0 if OK
Definition at line 3492 of file product.class.php.
References $ref_fourn, $resql, db, dol_now(), and dol_syslog().
add_photo ($sdir, $file)
Move an uploaded file described into $file array into target directory $sdir.
Parameters
string $sdir Target directory
string $file Array of file info of file to upload: array('name'=>..., 'tmp_name'=>...)
Returns
int <0 if KO, >0 if OK
Definition at line 4597 of file product.class.php.
References CommonObject\addThumbs(), dol_mkdir(), dol_move_uploaded_file(), dol_osencode(), and get_exdir().
add_sousproduit ($id_pere, $id_fils, $qty, $incdec = 1)
Link a product/service to a parent product/service.
Parameters
int $id_pere Id of parent product/service
int $id_fils Id of child product/service
int $qty Quantity
int $incdec 1=Increase/decrease stock of child when parent stock increase/decrease
Returns
int < 0 if KO, > 0 if OK
Definition at line 3316 of file product.class.php.
References db, del_sousproduit(), and dol_print_error().
check ()
Check that ref and label are ok.
Returns
int >1 if OK, <=0 if KO
Definition at line 414 of file product.class.php.
References dol_sanitizeFileName(), dol_strlen(), and label.
check_barcode ($valuetotest, $typefortest)
Check barcode.
Parameters
string $valuetotest Value to test
string $typefortest Type of barcode (ISBN, EAN, ...)
Returns
int 0 if OK -1 ErrorBadBarCodeSyntax -2 ErrorBarCodeRequired -3 ErrorBarCodeAlreadyUsed
Definition at line 757 of file product.class.php.
References db, dol_include_once(), and dol_syslog().
Referenced by verify().
clone_associations ($fromId, $toId)
Clone links between products.
Parameters
int $fromId Product id
int $toId Product id
Returns
int <0 if KO, >0 if OK
Definition at line 3652 of file product.class.php.
References db, and dol_syslog().
clone_fournisseurs ($fromId, $toId)
Recopie les fournisseurs et prix fournisseurs d'un produit/service sur un autre.
Parameters
int $fromId Id produit source
int $toId Id produit cible
Returns
int < 0 si erreur, > 0 si ok
Definition at line 3679 of file product.class.php.
References $resql, db, dol_now(), and dol_syslog().
clone_price ($fromId, $toId)
Recopie les prix d'un produit/service sur un autre.
Parameters
int $fromId Id product source
int $toId Id product target
Returns
int < 0 if KO, > 0 if OK
Definition at line 3623 of file product.class.php.
References db, and dol_syslog().
correct_stock ($user, $id_entrepot, $nbpiece, $movement, $label = '', $price = 0, $inventorycode = '', $origin_element = '', $origin_id = null)
Adjust stock in a warehouse for product.
Parameters
User $user user asking change
int $id_entrepot id of warehouse
double $nbpiece nb of units
int $movement 0 = add, 1 = remove
string $label Label of stock movement
double $price Unit price HT of product, used to calculate average weighted price (PMP in french). If 0, average weighted price is not changed.
string $inventorycode Inventory code
string $origin_element Origin element type
int $origin_id Origin id of element
Returns
int <0 if KO, >0 if OK
Definition at line 4323 of file product.class.php.
References db.
correct_stock_batch ($user, $id_entrepot, $nbpiece, $movement, $label = '', $price = 0, $dlc = '', $dluo = '', $lot = '', $inventorycode = '', $origin_element = '', $origin_id = null)
Adjust stock in a warehouse for product with batch number.
Parameters
User $user user asking change
int $id_entrepot id of warehouse
double $nbpiece nb of units
int $movement 0 = add, 1 = remove
string $label Label of stock movement
double $price Price to use for stock eval
integer $dlc eat-by date
integer $dluo sell-by date
string $lot Lot number
string $inventorycode Inventory code
string $origin_element Origin element type
int $origin_id Origin id of element
Returns
int <0 if KO, >0 if OK
Definition at line 4371 of file product.class.php.
References db.
create ($user, $notrigger = 0)
Insert product into database.
Parameters
User $user User making insert
int $notrigger Disable triggers
Returns
int Id of product/service if OK, < 0 if KO
Definition at line 443 of file product.class.php.
References _log_price(), CommonObject\call_trigger(), db, dol_include_once(), dol_now(), dol_string_nospecial(), dol_strlen(), dol_syslog(), get_barcode(), label, price(), price2num(), type, update(), and verify().
del_sousproduit ($fk_parent, $fk_child)
Retire le lien entre un sousproduit et un produit/service.
Parameters
int $fk_parent Id du produit auquel ne sera plus lie le produit lie
int $fk_child Id du produit a ne plus lie
Returns
int < 0 if KO, > 0 if OK
Definition at line 3418 of file product.class.php.
References db, dol_print_error(), and dol_syslog().
Referenced by add_sousproduit().
delete (User $user, $notrigger = 0)
Delete a product from database (if not used)
Parameters
User $user Product id (usage of this is deprecated, delete should be called without parameters on a fetched object)
int $notrigger Do not execute trigger
Returns
int < 0 if KO, 0 = Not possible, > 0 if OK
Definition at line 1098 of file product.class.php.
References CommonObject\call_trigger(), db, CommonObject\deleteExtraFields(), dol_delete_dir_recursive(), dol_sanitizeFileName(), dol_syslog(), fetch(), CommonObject\isObjectUsed(), type, TYPE_PRODUCT, and TYPE_SERVICE.
delete_photo ($file)
Efface la photo du produit et sa vignette.
Parameters
string $file Chemin de l'image
Returns
void
Definition at line 4738 of file product.class.php.
References dol_delete_file(), and dol_osencode().
delMultiLangs ($langtodelete, $user)
Delete a language for this product.
Parameters
string $langtodelete Language code to delete
User $user Object user making delete
Returns
int <0 if KO, >0 if OK
Definition at line 1377 of file product.class.php.
References $resql, CommonObject\call_trigger(), db, and dol_syslog().
fetch ($id = '', $ref = '', $ref_ext = '', $barcode = '', $ignore_expression = 0)
Load a product in memory from database.
Parameters
int $id Id of product/service to load
string $ref Ref of product/service to load
string $ref_ext Ref ext of product/service to load
string $barcode Barcode of product/service to load
int $ignore_expression Ignores the math expression for calculating price and uses the db value instead
Returns
int <0 if KO, 0 if not found, >0 if OK
French VAT NPR
Local taxes
Definition at line 2030 of file product.class.php.
References $resql, db, description, dol_print_error(), dol_strlen(), dol_syslog(), CommonObject\fetch_optionals(), getCountry(), getMultiLangs(), label, note, price(), price2num(), and type.
Referenced by delete().
fetch_prod_arbo ($prod, $compl_path = "", $multiply = 1, $level = 1, $id_parent = 0)
Fonction recursive uniquement utilisee par get_arbo_each_prod, recompose l'arborescence des sousproduits Define value of this->res.
Parameters
array $prod Products array
string $compl_path Directory path of parents to add before
int $multiply Because each sublevel must be multiplicated by parent nb
int $level Init level
int $id_parent Id parent
Returns
void
Definition at line 3731 of file product.class.php.
References db.
Referenced by get_arbo_each_prod().
generateDocument ($modele, $outputlangs, $hidedetails = 0, $hidedesc = 0, $hideref = 0)
Create a document onto disk according to template module.
Parameters
string $modele Force model to use ('' to not force)
Translate $outputlangs Object langs to use for output
int $hidedetails Hide details of lines
int $hidedesc Hide description
int $hideref Hide ref
Returns
int 0 if KO, 1 if OK
Definition at line 4160 of file product.class.php.
References CommonObject\commonGenerateDocument(), and dol_strlen().
generateMultiprices (User $user, $baseprice, $price_type, $price_vat, $npr, $psq)
Generates prices for a product based on product multiprice generation rules.
Parameters
User $user User that updates the prices
float $baseprice Base price
string $price_type Base price type
float $price_vat VAT % tax
int $npr NPR
string $psq ¿?
Returns
int -1 KO, 1 OK
Definition at line 5081 of file product.class.php.
References updatePrice().
Referenced by updatePrice().
get_arbo_each_prod ($multiply = 1)
Build the tree of subproducts into an array this->sousprods is loaded by this->get_sousproduits_arbo()
Parameters
int $multiply Because each sublevel must be multiplicated by parent nb
Returns
array $this->res
Definition at line 3791 of file product.class.php.
References fetch_prod_arbo().
get_barcode ($object, $type = '')
Get a barcode from the module to generate barcode values.
Return value is stored into this->barcode
Parameters
Product $object Object product or service
string $type Barcode type (ean, isbn, ...)
Returns
string
Definition at line 4853 of file product.class.php.
References dol_include_once(), and dol_syslog().
Referenced by create(), and update().
get_buyprice ($prodfournprice, $qty, $product_id = 0, $fourn_ref = '', $fk_soc = 0)
Read price used by a provider.
We enter as input couple prodfournprice/qty or triplet qty/product_id/fourn_ref. This also set some properties on product like ->buyprice, ->fourn_pu, ...
Parameters
int $prodfournprice Id du tarif = rowid table product_fournisseur_price
double $qty Quantity asked or -1 to get first entry found
int $product_id Filter on a particular product id
string $fourn_ref Filter on a supplier price ref. 'none' to exclude ref in search.
int $fk_soc If of supplier
Returns
int <-1 if KO, -1 if qty not enough, 0 if OK but nothing found, id_product if OK and found. May also initialize some properties like (->ref_supplier, buyprice, fourn_pu, vatrate_supplier...)
See also
getSellPrice(), find_min_price_product_fournisseur()
Definition at line 1693 of file product.class.php.
References $resql, db, and dol_syslog().
get_image_size ($file)
Load size of image file.
Parameters
string $file Path to file
Returns
void
Definition at line 4772 of file product.class.php.
References dol_osencode().
get_nb_achat ($socid, $mode, $filteronproducttype = -1, $year = 0, $morefilter = '')
Return nb of units or supplier invoices in which product is included.
Parameters
int $socid Limit count on a particular third party id
string $mode 'byunit'=number of unit, 'bynumber'=nb of entities
int $filteronproducttype 0=To filter on product only, 1=To filter on services only
int $year Year (0=last 12 month)
string $morefilter More sql filters
Returns
array <0 if KO, result[month]=array(valuex,valuey) where month is 0 to 11
Definition at line 3008 of file product.class.php.
References _get_stats().
get_nb_contract ($socid, $mode, $filteronproducttype = -1, $year = 0, $morefilter = '')
Return nb of units or orders in which product is included.
Parameters
int $socid Limit count on a particular third party id
string $mode 'byunit'=number of unit, 'bynumber'=nb of entities
int $filteronproducttype 0=To filter on product only, 1=To filter on services only
int $year Year (0=last 12 month)
string $morefilter More sql filters
Returns
array <0 if KO, result[month]=array(valuex,valuey) where month is 0 to 11
Definition at line 3266 of file product.class.php.
References _get_stats().
get_nb_order ($socid, $mode, $filteronproducttype = -1, $year = 0, $morefilter = '')
Return nb of units or orders in which product is included.
Parameters
int $socid Limit count on a particular third party id
string $mode 'byunit'=number of unit, 'bynumber'=nb of entities
int $filteronproducttype 0=To filter on product only, 1=To filter on services only
int $year Year (0=last 12 month)
string $morefilter More sql filters
Returns
array <0 if KO, result[month]=array(valuex,valuey) where month is 0 to 11
Definition at line 3164 of file product.class.php.
References _get_stats().
get_nb_ordersupplier ($socid, $mode, $filteronproducttype = -1, $year = 0, $morefilter = '')
Return nb of units or orders in which product is included.
Parameters
int $socid Limit count on a particular third party id
string $mode 'byunit'=number of unit, 'bynumber'=nb of entities
int $filteronproducttype 0=To filter on product only, 1=To filter on services only
int $year Year (0=last 12 month)
string $morefilter More sql filters
Returns
array <0 if KO, result[month]=array(valuex,valuey) where month is 0 to 11
Definition at line 3215 of file product.class.php.
References _get_stats().
get_nb_propal ($socid, $mode, $filteronproducttype = -1, $year = 0, $morefilter = '')
Return nb of units or proposals in which product is included.
Parameters
int $socid Limit count on a particular third party id
string $mode 'byunit'=number of unit, 'bynumber'=nb of entities
int $filteronproducttype 0=To filter on product only, 1=To filter on services only
int $year Year (0=last 12 month)
string $morefilter More sql filters
Returns
array <0 if KO, result[month]=array(valuex,valuey) where month is 0 to 11
Definition at line 3060 of file product.class.php.
References _get_stats().
get_nb_propalsupplier ($socid, $mode, $filteronproducttype = -1, $year = 0, $morefilter = '')
Return nb of units or proposals in which product is included.
Parameters
int $socid Limit count on a particular third party id
string $mode 'byunit'=number of unit, 'bynumber'=nb of entities
int $filteronproducttype 0=To filter on product only, 1=To filter on services only
int $year Year (0=last 12 month)
string $morefilter More sql filters
Returns
array <0 if KO, result[month]=array(valuex,valuey) where month is 0 to 11
Definition at line 3112 of file product.class.php.
References _get_stats().
get_nb_vente ($socid, $mode, $filteronproducttype = -1, $year = 0, $morefilter = '')
Return nb of units or customers invoices in which product is included.
Parameters
int $socid Limit count on a particular third party id
string $mode 'byunit'=number of unit, 'bynumber'=nb of entities
int $filteronproducttype 0=To filter on product only, 1=To filter on services only
int $year Year (0=last 12 month)
string $morefilter More sql filters
Returns
array <0 if KO, result[month]=array(valuex,valuey) where month is 0 to 11
Definition at line 2955 of file product.class.php.
References _get_stats().
get_sousproduits_arbo ()
Return tree of all subproducts for product.
Tree contains id, name and quantity. Set this->sousprods
Returns
void
Definition at line 3989 of file product.class.php.
References getChildsArbo().
getChildsArbo ($id, $firstlevelonly = 0, $level = 1)
Return childs of product $id.
Parameters
int $id Id of product to search childs of
int $firstlevelonly Return only direct child
int $level Level of recursing call (start to 1)
Returns
array Return array(prodid=>array(0=prodid, 1=>qty, 2=> ...)
Definition at line 3926 of file product.class.php.
References db, dol_print_error(), and dol_syslog().
Referenced by get_sousproduits_arbo().
getFather ()
Return all parent products for current product (first level only)
Returns
array Array of product
Definition at line 3886 of file product.class.php.
References db, and dol_print_error().
Referenced by load_stats_commande().
getLabelOfUnit ($type = 'long')
Returns the text label from units dictionary.
Parameters
string $type Label type (long or short)
Returns
string|int <0 if ko, label if ok
Definition at line 4929 of file product.class.php.
References $resql, db, and dol_syslog().
getLibFinished ()
Retourne le libelle du finished du produit.
Returns
string Libelle
Definition at line 4295 of file product.class.php.
getLibStatut ($mode = 0, $type = 0)
Return label of status of object.
Parameters
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto
int $type 0=Sell, 1=Buy, 2=Batch Number management
Returns
string Label of status
Definition at line 4189 of file product.class.php.
References LibStatut().
Referenced by getNomUrl().
getMultiLangs ()
Load array this->multilangs.
Returns
int <0 if KO, >0 if OK
Definition at line 1466 of file product.class.php.
References db, description, and label.
Referenced by fetch().
getNomUrl ($withpicto = 0, $option = '', $maxlength = 0, $save_lastsearch_value = -1, $notooltip = 0)
Return clicable link of object (with eventually picto)
Parameters
int $withpicto Add picto into link
string $option Where point the link ('stock', 'composition', 'category', 'supplier', '')
int $maxlength Maxlength of ref
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
int $notooltip No tooltip
Returns
string String with URL
Definition at line 4014 of file product.class.php.
References dol_trunc(), getLibStatut(), img_object(), label, length_accountg(), measuring_units_string(), CommonObject\show_photos(), type, TYPE_PRODUCT, and TYPE_SERVICE.
getRights ()
Returns the rights used for this class.
Returns
Object
Definition at line 5138 of file product.class.php.
References isProduct().
getSellPrice ($thirdparty_seller, $thirdparty_buyer, $pqp = 0)
Return price of sell of a product for a seller/buyer/product.
Parameters
Societe $thirdparty_seller Seller
Societe $thirdparty_buyer Buyer
int $pqp Id of product per price if a selection was done of such a price
Returns
array Array of price information
See also
get_buyprice(), find_min_price_product_fournisseur()
Definition at line 1581 of file product.class.php.
References $tva_npr, $tva_tx, get_default_npr(), get_default_tva(), and price().
hasbatch ()
Return if object has a sell-by date or eat-by date.
Returns
boolean True if it's has
Definition at line 4966 of file product.class.php.
Referenced by load_stock(), and update().
hasFatherOrChild ()
Return all parent products for current product (first level only)
Returns
int Nb of father + child
Definition at line 3811 of file product.class.php.
References $resql, and db.
hasVariants ()
Return if a product has variants or not.
Returns
int Number of variants
Definition at line 3837 of file product.class.php.
References $resql, and db.
info ($id)
Load information for tab info.
Parameters
int $id Id of thirdparty to load
Returns
void
Definition at line 5155 of file product.class.php.
References db, and dol_print_error().
initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
void
Definition at line 4884 of file product.class.php.
References description, dol_now(), label, and note.
is_photo_available ($sdir)
Return if at least one photo is available.
Parameters
string $sdir Directory to scan
Returns
boolean True if at least one photo is available, False if not
Definition at line 4643 of file product.class.php.
References dol_is_file(), dol_osencode(), get_exdir(), image_format_supported(), and utf8_check().
is_sousproduit ($fk_parent, $fk_child)
Verifie si c'est un sous-produit.
Parameters
int $fk_parent Id du produit auquel le produit est lie
int $fk_child Id du produit lie
Returns
int < 0 si erreur, > 0 si ok
Definition at line 3449 of file product.class.php.
References db, and dol_print_error().
isProduct ()
Return if object is a product.
Returns
boolean True if it's a product
Definition at line 4829 of file product.class.php.
References type, and TYPE_PRODUCT.
Referenced by getRights().
isService ()
Return if object is a product.
Returns
boolean True if it's a service
Definition at line 4839 of file product.class.php.
References type, and TYPE_SERVICE.
isVariant ()
Return if loaded product is a variant.
Returns
int
Definition at line 3859 of file product.class.php.
References db, dol_print_error(), and getEntity().
LibStatut ($status, $mode = 0, $type = 0)
Return label of a given status.
Parameters
int $status Statut
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto
int $type 0=Status "to sell", 1=Status "to buy", 2=Status "to Batch"
Returns
string Label of status
Definition at line 4214 of file product.class.php.
References dolGetStatus().
Referenced by getLibStatut().
list_suppliers ()
Renvoie la liste des fournisseurs du produit/service.
Returns
array Tableau des id de fournisseur
Definition at line 3588 of file product.class.php.
References db.
liste_photos ($dir, $nbmax = 0)
Retourne tableau de toutes les photos du produit.
Parameters
string $dir Repertoire a scanner
int $nbmax Nombre maximum de photos (0=pas de max)
Returns
array Tableau de photos
Definition at line 4682 of file product.class.php.
References dol_is_file(), dol_osencode(), image_format_supported(), and utf8_check().
load_state_board ()
Load indicators this->nb for the dashboard.
Returns
int <0 if KO, >0 if OK
Definition at line 4787 of file product.class.php.
References $resql, db, and dol_print_error().
load_stats_commande ($socid = 0, $filtrestatut = '', $forVirtualStock = 0)
Charge tableau des stats commande client pour le produit/service.
Parameters
int $socid Id societe pour filtrer sur une societe
string $filtrestatut Id statut pour filtrer sur un statut
int $forVirtualStock Ignore rights filter for virtual stock calculation.
Returns
integer Array of stats in $this->stats_commande (nb=nb of order, qty=qty ordered), <0 if ko or >0 if ok
Definition at line 2486 of file product.class.php.
References $resql, db, dol_syslog(), and getFather().
Referenced by load_virtual_stock().
load_stats_commande_fournisseur ($socid = 0, $filtrestatut = '', $forVirtualStock = 0)
Charge tableau des stats commande fournisseur pour le produit/service.
Parameters
int $socid Id societe pour filtrer sur une societe
string $filtrestatut Id des statuts pour filtrer sur des statuts
int $forVirtualStock Ignore rights filter for virtual stock calculation.
Returns
array Tableau des stats
Definition at line 2585 of file product.class.php.
References db.
Referenced by load_virtual_stock().
load_stats_contrat ($socid = 0)
Charge tableau des stats contrat pour le produit/service.
Parameters
int $socid Id societe
Returns
array Tableau des stats
Definition at line 2739 of file product.class.php.
References db.
load_stats_facture ($socid = 0)
Charge tableau des stats facture pour le produit/service.
Parameters
int $socid Id societe
Returns
array Tableau des stats
Definition at line 2788 of file product.class.php.
References db.
load_stats_facture_fournisseur ($socid = 0)
Charge tableau des stats facture pour le produit/service.
Parameters
int $socid Id societe
Returns
array Tableau des stats
Definition at line 2836 of file product.class.php.
References db.
load_stats_propale ($socid = 0)
Charge tableau des stats propale pour le produit/service.
Parameters
int $socid Id societe
Returns
integer Tableau des stats dans $this->stats_propale, <0 if ko >0 if ok
Definition at line 2387 of file product.class.php.
References db.
load_stats_proposal_supplier ($socid = 0)
Charge tableau des stats propale pour le produit/service.
Parameters
int $socid Id thirdparty
Returns
array Tableau des stats
Definition at line 2437 of file product.class.php.
References db.
load_stats_reception ($socid = 0, $filtrestatut = '', $forVirtualStock = 0)
Charge tableau des stats réception fournisseur pour le produit/service.
Parameters
int $socid Id societe pour filtrer sur une societe
string $filtrestatut Id statut pour filtrer sur un statut
int $forVirtualStock Ignore rights filter for virtual stock calculation.
Returns
array Tableau des stats
Definition at line 2693 of file product.class.php.
References db.
Referenced by load_virtual_stock().
load_stats_sending ($socid = 0, $filtrestatut = '', $forVirtualStock = 0)
Charge tableau des stats expedition client pour le produit/service.
Parameters
int $socid Id societe pour filtrer sur une societe
string $filtrestatut Id statut pour filtrer sur un statut
int $forVirtualStock Ignore rights filter for virtual stock calculation.
Returns
array Tableau des stats
Definition at line 2637 of file product.class.php.
References db.
Referenced by load_virtual_stock().
load_stock ($option = '')
Load information about stock of a product into ->stock_reel, ->stock_warehouse[] (including stock_warehouse[idwarehouse]->detail_batch for batch products) This function need a lot of load.
If you use it on list, use a cache to execute it once for each product id. If ENTREPOT_EXTRA_STATUS set, filtering on warehouse status possible.
Parameters
string $option '' = Load all stock info, also from closed and internal warehouses,
Returns
int < 0 if KO, > 0 if OK
See also
load_virtual_stock(), loadBatchInfo()
Definition at line 4411 of file product.class.php.
References db, dol_syslog(), Productbatch\findAll(), hasbatch(), load_virtual_stock(), Entrepot\STATUS_CLOSED, Entrepot\STATUS_OPEN_ALL, and Entrepot\STATUS_OPEN_INTERNAL.
Referenced by update().
load_virtual_stock ()
Load value ->stock_theorique of a product.
Property this->id must be defined. This function need a lot of load. If you use it on list, use a cache to execute it one for each product id.
Returns
int < 0 if KO, > 0 if OK
See also
load_stock(), loadBatchInfo()
Definition at line 4483 of file product.class.php.
References db, dol_print_error(), load_stats_commande(), load_stats_commande_fournisseur(), load_stats_reception(), and load_stats_sending().
Referenced by load_stock().
loadBatchInfo ($batch)
Load existing information about a serial.
Parameters
string $batch Lot/serial number
Returns
array Array with record into product_batch
See also
load_stock(), load_virtual_stock()
Definition at line 4561 of file product.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
log_price_delete ($user, $rowid)
Delete a price line.
Parameters
User $user Object user
int $rowid Line id to delete
Returns
int <0 if KO, >0 if OK
Definition at line 1551 of file product.class.php.
References $resql, and db.
min_recommended_price ()
Return minimum product recommended price.
Returns
int Minimum recommanded price that is higher price among all suppliers * PRODUCT_MINIMUM_RECOMMENDED_PRICE
Definition at line 4978 of file product.class.php.
References db.
static replaceThirdparty (DoliDB $db, $origin_id, $dest_id) static
Function used to replace a thirdparty id with another one.
Parameters
DoliDB $db Database handler
int $origin_id Old thirdparty id
int $dest_id New thirdparty id
Returns
bool
Definition at line 5060 of file product.class.php.
References CommonObject\commonReplaceThirdparty().
setCategories ($categories)
Sets object to supplied categories.
Deletes object from existing categories not supplied. Adds it to non existing supplied categories. Existing categories are left untouch.
Parameters
int[]|int $categories Category or categories IDs
Returns
void
Definition at line 5016 of file product.class.php.
References db.
setMultiLangs ($user)
Update or add a translation for a product.
Parameters
User $user Object user making update
Returns
int <0 if KO, >0 if OK
Definition at line 1268 of file product.class.php.
References CommonObject\call_trigger(), db, description, dol_syslog(), and label.
Referenced by update().
setPriceExpression ($expression_id)
Sets the supplier price expression.
Parameters
int $expression_id Expression
Returns
int <0 if KO, >0 if OK
Deprecated:
Use Product::update instead
Definition at line 2011 of file product.class.php.
References update().
update ($id, $user, $notrigger = false, $action = 'update')
Update a record into database.
If batch flag is set to on, we create records into llx_product_batch
Parameters
int $id Id of product
User $user Object user making update
int $notrigger Disable triggers
string $action Current action for hookmanager ('add' or 'update')
Returns
int 1 if OK, -1 if ref already exists, -2 if other error
Definition at line 794 of file product.class.php.
References $localtax1_tx, $resql, $tva_npr, $tva_tx, CommonObject\call_trigger(), db, description, dol_print_error(), dol_sanitizeFileName(), dol_string_nospecial(), dol_syslog(), get_barcode(), hasbatch(), CommonObject\insertExtraFields(), label, load_stock(), measuring_units_cubed(), measuring_units_squared(), note, price2num(), setMultiLangs(), and verify().
Referenced by create(), and setPriceExpression().
update_sousproduit ($id_pere, $id_fils, $qty, $incdec = 1)
Modify composed product.
Parameters
int $id_pere Id of parent product/service
int $id_fils Id of child product/service
int $qty Quantity
int $incdec 1=Increase/decrease stock of child when parent stock increase/decrease
Returns
int < 0 if KO, > 0 if OK
Definition at line 3378 of file product.class.php.
References db, and dol_print_error().
updatePrice ($newprice, $newpricebase, $user, $newvat = '', $newminprice = 0, $level = 0, $newnpr = 0, $newpbq = 0, $ignore_autogen = 0, $localtaxes_array = array(), $newdefaultvatcode = '')
Modify customer price of a product/Service.
Parameters
double $newprice New price
string $newpricebase HT or TTC
User $user Object user that make change
double $newvat New VAT Rate (For example 8.5. Should not be a string)
double $newminprice New price min
int $level 0=standard, >0 = level if multilevel prices
int $newnpr 0=Standard vat rate, 1=Special vat rate for French NPR VAT
int $newpbq 1 if it has price by quantity
int $ignore_autogen Used to avoid infinite loops
array $localtaxes_array Array with localtaxes info array('0'=>type1,'1'=>rate1,'2'=>type2,'3'=>rate2) (loaded by getLocalTaxesFromRate(vatrate, 0, ...) function).
string $newdefaultvatcode Default vat code
Returns
int <0 if KO, >0 if OK
Definition at line 1843 of file product.class.php.
References $resql, $tva_tx, _log_price(), CommonObject\call_trigger(), db, dol_print_error(), dol_syslog(), generateMultiprices(), get_localtax(), price(), and price2num().
Referenced by generateMultiprices(), and ProductCombination\updateProperties().
verify ()
Check properties of product are ok (like name, barcode, ...).
All properties must be already loaded on object (this->barcode, this->barcode_type_code, ...).
Returns
int 0 if OK, <0 if KO
Definition at line 715 of file product.class.php.
References check_barcode().
Referenced by create(), and update().
Field Documentation
$ref_fourn
Deprecated:
See also
$ref_supplier
Definition at line 345 of file product.class.php.
Referenced by add_fournisseur(), and ProductFournisseur\update_buyprice().
The documentation for this class was generated from the following file:
htdocs/product/class/product.class.php