Dolibarr: FormOrder Class Reference
FormOrder Class Reference
Class to manage HTML output components for orders Before adding component here, check they are not into common part Form.class.php.
Public Member Functions
selectSupplierOrderStatus ($selected= '', $short=0, $hmlname= 'order_status')
Return combo list of differents status of a orders.
selectInputMethod ($selected= '', $htmlname= 'source_id', $addempty=0)
Return list of input method (mode used to receive order, like order received by email, fax, online) List found into table c_input_method.
Public Member Functions inherited from Form
__construct ($db)
Constructor.
editfieldkey ($text, $htmlname, $preselected, $object, $perm, $typeofdata= 'string', $moreparam= '', $fieldrequired=0, $notabletag=0, $paramid= 'id')
Output key field for an editable field.
editfieldval ($text, $htmlname, $value, $object, $perm, $typeofdata= 'string', $editvalue= '', $extObject=null, $custommsg=null, $moreparam= '', $notabletag=0, $formatfunc= '', $paramid= 'id')
Output value of a field for an editable field.
textwithtooltip ($text, $htmltext, $tooltipon=1, $direction=0, $img= '', $extracss= '', $notabs=2, $incbefore= '', $noencodehtmltext=0, $tooltiptrigger= '', $forcenowrap=0)
Show a text and picto with tooltip on text or picto.
textwithpicto ($text, $htmltext, $direction=1, $type= 'help', $extracss= '', $noencodehtmltext=0, $notabs=2, $tooltiptrigger= '', $forcenowrap=0)
Show a text with a picto and a tooltip on picto.
selectMassAction ($selected, $arrayofaction, $alwaysvisible=0)
Generate select HTML to choose massaction.
select_country ($selected= '', $htmlname= 'country_id', $htmloption= '', $maxlength=0, $morecss= 'minwidth300', $usecodeaskey= '', $showempty=1, $disablefavorites=0, $addspecialentries=0)
Return combo list of activated countries, into language of user.
select_incoterms ($selected= '', $location_incoterms= '', $page= '', $htmlname= 'incoterm_id', $htmloption= '', $forcecombo=1, $events=array())
Return select list of incoterms.
select_type_of_lines ($selected= '', $htmlname= 'type', $showempty=0, $hidetext=0, $forceall=0)
Return list of types of lines (product or service) Example: 0=product, 1=service, 9=other (for external module)
load_cache_types_fees ()
Load into cache cache_types_fees, array of types of fees.
select_type_fees ($selected= '', $htmlname= 'type', $showempty=0)
Return list of types of notes.
select_thirdparty ($selected= '', $htmlname= 'socid', $filter= '', $limit=20, $ajaxoptions=array(), $forcecombo=0)
Return HTML code to select a company.
select_company ($selected= '', $htmlname= 'socid', $filter= '', $showempty= '', $showtype=0, $forcecombo=0, $events=array(), $limit=0, $morecss= 'minwidth100', $moreparam= '', $selected_input_value= '', $hidelabel=1, $ajaxoptions=array(), $multiple=false)
Output html form to select a third party.
select_thirdparty_list ($selected= '', $htmlname= 'socid', $filter= '', $showempty= '', $showtype=0, $forcecombo=0, $events=array(), $filterkey= '', $outputmode=0, $limit=0, $morecss= 'minwidth100', $moreparam= '', $multiple=false)
Output html form to select a third party.
select_remises ($selected, $htmlname, $filter, $socid, $maxvalue=0)
Return HTML combo list of absolute discounts.
select_contacts ($socid, $selected= '', $htmlname= 'contactid', $showempty=0, $exclude= '', $limitto= '', $showfunction=0, $moreclass= '', $showsoc=0, $forcecombo=0, $events=array(), $options_only=false, $moreparam= '', $htmlid= '')
Return list of all contacts (for a third party or all)
selectcontacts ($socid, $selected= '', $htmlname= 'contactid', $showempty=0, $exclude= '', $limitto= '', $showfunction=0, $moreclass= '', $options_only=false, $showsoc=0, $forcecombo=0, $events=array(), $moreparam= '', $htmlid= '', $multiple=false)
Return HTML code of the SELECT of list of all contacts (for a third party or all).
select_users ($selected= '', $htmlname= 'userid', $show_empty=0, $exclude=null, $disabled=0, $include= '', $enableonly= '', $force_entity= '0')
Return select list of users.
select_dolusers ($selected= '', $htmlname= 'userid', $show_empty=0, $exclude=null, $disabled=0, $include= '', $enableonly= '', $force_entity= '0', $maxlength=0, $showstatus=0, $morefilter= '', $show_every=0, $enableonlytext= '', $morecss= '', $noactive=0, $outputmode=0, $multiple=false)
Return select list of users.
select_dolusers_forevent ($action= '', $htmlname= 'userid', $show_empty=0, $exclude=null, $disabled=0, $include= '', $enableonly= '', $force_entity= '0', $maxlength=0, $showstatus=0, $morefilter= '', $showproperties=0, $listofuserid=array(), $listofcontactid=array(), $listofotherid=array())
Return select list of users.
select_produits ($selected= '', $htmlname= 'productid', $filtertype= '', $limit=20, $price_level=0, $status=1, $finished=2, $selected_input_value= '', $hidelabel=0, $ajaxoptions=array(), $socid=0, $showempty= '1', $forcecombo=0, $morecss= '', $hidepriceinlabel=0, $warehouseStatus= '', $selected_combinations=array())
Return list of products for customer in Ajax if Ajax activated or go to select_produits_list.
select_produits_list ($selected= '', $htmlname= 'productid', $filtertype= '', $limit=20, $price_level=0, $filterkey= '', $status=1, $finished=2, $outputmode=0, $socid=0, $showempty= '1', $forcecombo=0, $morecss= '', $hidepriceinlabel=0, $warehouseStatus= '')
Return list of products for a customer.
select_produits_fournisseurs ($socid, $selected= '', $htmlname= 'productid', $filtertype= '', $filtre= '', $ajaxoptions=array(), $hidelabel=0, $alsoproductwithnosupplierprice=0, $morecss= '')
Return list of products for customer (in Ajax if Ajax activated or go to select_produits_fournisseurs_list)
select_produits_fournisseurs_list ($socid, $selected= '', $htmlname= 'productid', $filtertype= '', $filtre= '', $filterkey= '', $statut=-1, $outputmode=0, $limit=100, $alsoproductwithnosupplierprice=0, $morecss= '')
Return list of suppliers products.
select_product_fourn_price ($productid, $htmlname= 'productfournpriceid', $selected_supplier= '')
Return list of suppliers prices for a product.
select_address ($selected, $socid, $htmlname= 'address_id', $showempty=0)
Return list of delivery address.
load_cache_conditions_paiements ()
Load into cache list of payment terms.
load_cache_availability ()
Charge dans cache la liste des délais de livraison possibles.
selectAvailabilityDelay ($selected= '', $htmlname= 'availid', $filtertype= '', $addempty=0)
Retourne la liste des types de delais de livraison possibles.
loadCacheInputReason ()
Load into cache cache_demand_reason, array of input reasons.
selectInputReason ($selected= '', $htmlname= 'demandreasonid', $exclude= '', $addempty=0)
Return list of input reason (events that triggered an object creation, like after sending an emailing, making an advert, ...) List found into table c_input_reason loaded by loadCacheInputReason.
load_cache_types_paiements ()
Charge dans cache la liste des types de paiements possibles.
select_conditions_paiements ($selected=0, $htmlname= 'condid', $filtertype=-1, $addempty=0, $noinfoadmin=0, $morecss= '')
Return list of payment modes.
select_types_paiements ($selected= '', $htmlname= 'paiementtype', $filtertype= '', $format=0, $empty=1, $noadmininfo=0, $maxlength=0, $active=1, $morecss= '')
Return list of payment methods.
selectPriceBaseType ($selected= '', $htmlname= 'price_base_type')
Selection HT or TTC.
selectShippingMethod ($selected= '', $htmlname= 'shipping_method_id', $filtre= '', $useempty=0, $moreattrib= '')
Return a HTML select list of shipping mode.
formSelectShippingMethod ($page, $selected= '', $htmlname= 'shipping_method_id', $addempty=0)
Display form to select shipping mode.
selectSituationInvoices ($selected= '', $socid=0)
Creates HTML last in cycle situation invoices selector.
selectUnits ($selected= '', $htmlname= 'units', $showempty=0)
Creates HTML units selector (code => label)
select_comptes ($selected= '', $htmlname= 'accountid', $statut=0, $filtre= '', $useempty=0, $moreattrib= '', $showcurrency=0, $morecss= '')
Return a HTML select list of bank accounts.
selectEstablishments ($selected= '', $htmlname= 'entity', $statut=0, $filtre= '', $useempty=0, $moreattrib= '')
Return a HTML select list of establishment.
formSelectAccount ($page, $selected= '', $htmlname= 'fk_account', $addempty=0)
Display form to select bank account.
select_all_categories ($type, $selected= '', $htmlname="parent", $maxlength=64, $markafterid=0, $outputmode=0, $include=0)
Return list of categories having choosed type.
form_confirm ($page, $title, $question, $action, $formquestion= '', $selectedchoice="", $useajax=0, $height=170, $width=500)
Show a confirmation HTML form or AJAX popup.
formconfirm ($page, $title, $question, $action, $formquestion= '', $selectedchoice= '', $useajax=0, $height=210, $width=500, $disableformtag=0)
Show a confirmation HTML form or AJAX popup.
form_project ($page, $socid, $selected= '', $htmlname= 'projectid', $discard_closed=0, $maxlength=20, $forcefocus=0, $nooutput=0)
Show a form to select a project.
form_conditions_reglement ($page, $selected= '', $htmlname= 'cond_reglement_id', $addempty=0)
Show a form to select payment conditions.
form_availability ($page, $selected= '', $htmlname= 'availability', $addempty=0)
Show a form to select a delivery delay.
formInputReason ($page, $selected= '', $htmlname= 'demandreason', $addempty=0)
Output HTML form to select list of input reason (events that triggered an object creation, like after sending an emailing, making an advert, ...) List found into table c_input_reason loaded by loadCacheInputReason.
form_date ($page, $selected, $htmlname, $displayhour=0, $displaymin=0, $nooutput=0)
Show a form + html select a date.
form_users ($page, $selected= '', $htmlname= 'userid', $exclude= '', $include= '')
Show a select form to choose a user.
form_modes_reglement ($page, $selected= '', $htmlname= 'mode_reglement_id', $filtertype= '', $active=1, $addempty=0)
Show form with payment mode.
form_multicurrency_code ($page, $selected= '', $htmlname= 'multicurrency_code')
Show form with multicurrency code.
form_multicurrency_rate ($page, $rate= '', $htmlname= 'multicurrency_tx', $currency= '')
Show form with multicurrency rate.
form_remise_dispo ($page, $selected, $htmlname, $socid, $amount, $filter= '', $maxvalue=0, $more= '', $hidelist=0, $discount_type=0)
Show a select box with available absolute discounts.
form_contacts ($page, $societe, $selected= '', $htmlname= 'contactid')
Show forms to select a contact.
form_thirdparty ($page, $selected= '', $htmlname= 'socid', $filter= '', $showempty=0, $showtype=0, $forcecombo=0, $events=array(), $nooutput=0)
Output html select to select thirdparty.
select_currency ($selected= '', $htmlname= 'currency_id')
Retourne la liste des devises, dans la langue de l'utilisateur.
selectCurrency ($selected= '', $htmlname= 'currency_id', $mode=0)
Retourne la liste des devises, dans la langue de l'utilisateur.
selectMultiCurrency ($selected= '', $htmlname= 'multicurrency_code', $useempty=0)
Return array of currencies in user language.
load_cache_vatrates ($country_code)
Load into the cache vat rates of a country.
load_tva ($htmlname= 'tauxtva', $selectedrate= '', $societe_vendeuse= '', $societe_acheteuse= '', $idprod=0, $info_bits=0, $type= '', $options_only=false, $mode=0)
Output an HTML select vat rate.
select_date ($set_time= '', $prefix= 're', $h=0, $m=0, $empty=0, $form_name="", $d=1, $addnowlink=0, $nooutput=0, $disabled=0, $fullday= '', $addplusone= '', $adddateof= '')
Show a HTML widget to input a date or combo list for day, month, years and optionaly hours and minutes.
selectDate ($set_time= '', $prefix= 're', $h=0, $m=0, $empty=0, $form_name="", $d=1, $addnowlink=0, $disabled=0, $fullday= '', $addplusone= '', $adddateof= '', $openinghours= '', $stepminutes=1)
Show a HTML widget to input a date or combo list for day, month, years and optionaly hours and minutes.
select_duration ($prefix, $iSecond= '', $disabled=0, $typehour= 'select', $minunderhours=0, $nooutput=0)
Function to show a form to select a duration on a page.
selectForForms ($objectdesc, $htmlname, $preselectedvalue, $showempty= '', $searchkey= '', $placeholder= '', $morecss= '', $moreparams= '', $forcecombo=0)
Generic method to select a component from a combo list.
selectForFormsList ($objecttmp, $htmlname, $preselectedvalue, $showempty= '', $searchkey= '', $placeholder= '', $morecss= '', $moreparams= '', $forcecombo=0, $outputmode=0)
Output html form to select an object.
showCategories ($id, $type, $rendermode=0)
Render list of categories linked to object with id $id and type $type.
showLinkedObjectBlock ($object, $morehtmlright= '', $compatibleImportElementsList=false)
Show linked object block.
showLinkToObjectBlock ($object, $restrictlinksto=array(), $excludelinksto=array())
Show block with links to link to other objects.
selectyesno ($htmlname, $value= '', $option=0, $disabled=false, $useempty=0)
Return an html string with a select combo box to choose yes or no.
select_export_model ($selected= '', $htmlname= 'exportmodelid', $type= '', $useempty=0)
Return list of export templates.
showrefnav ($object, $paramid, $morehtml= '', $shownav=1, $fieldid= 'rowid', $fieldref= 'ref', $morehtmlref= '', $moreparam= '', $nodbprefix=0, $morehtmlleft= '', $morehtmlstatus= '', $morehtmlright= '')
Return a HTML area with the reference of object and a navigation bar for a business object Note: To complete search with a particular filter on select, you can set $object->next_prev_filter set to define SQL criterias.
showbarcode (&$object, $width=100)
Return HTML code to output a barcode.
select_dolgroups ($selected= '', $htmlname= 'groupid', $show_empty=0, $exclude= '', $disabled=0, $include= '', $enableonly= '', $force_entity= '0', $multiple=false)
Return select list of groups.
showFilterButtons ()
Return HTML to show the search and clear seach button.
showCheckAddButtons ($cssclass= 'checkforaction', $calljsfunction=0)
Return HTML to show the search and clear seach button.
showFilterAndCheckAddButtons ($addcheckuncheckall=0, $cssclass= 'checkforaction', $calljsfunction=0)
Return HTML to show the search and clear seach button.
selectExpenseCategories ($selected= '', $htmlname= 'fk_c_exp_tax_cat', $useempty=0, $excludeid=array(), $target= '', $default_selected=0, $params=array())
Return HTML to show the select of expense categories.
selectExpenseRanges ($selected= '', $htmlname= 'fk_range', $useempty=0)
Return HTML to show the select ranges of expense range.
selectExpense ($selected= '', $htmlname= 'fk_c_type_fees', $useempty=0, $allchoice=1, $useid=0)
Return HTML to show a select of expense.
Additional Inherited Members
Static Public Member Functions inherited from Form
static selectarray ($htmlname, $array, $id= '', $show_empty=0, $key_in_label=0, $value_as_key=0, $moreparam= '', $translate=0, $maxlen=0, $disabled=0, $sort= '', $morecss= '', $addjscombo=0, $moreparamonempty= '', $disablebademail=0, $nohtmlescape=0)
Return a HTML select string, built from an array of key+value.
static selectArrayAjax ($htmlname, $url, $id= '', $moreparam= '', $moreparamtourl= '', $disabled=0, $minimumInputLength=1, $morecss= '', $callurlonselect=0, $placeholder= '', $acceptdelayedhtml=0)
Return a HTML select string, built from an array of key+value, but content returned into select come from an Ajax call of an URL.
static selectArrayFilter ($htmlname, $array, $id= '', $moreparam= '', $disableFiltering=0, $disabled=0, $minimumInputLength=1, $morecss= '', $callurlonselect=0, $placeholder= '', $acceptdelayedhtml=0)
Return a HTML select string, built from an array of key+value, but content returned into select is defined into $array parameter.
static multiselectarray ($htmlname, $array, $selected=array(), $key_in_label=0, $value_as_key=0, $morecss= '', $translate=0, $width=0, $moreattrib= '', $elemtype= '', $placeholder= '', $addjscombo=-1)
Show a multiselect form from an array.
static multiSelectArrayWithCheckbox ($htmlname, &$array, $varpage)
Show a multiselect dropbox from an array.
static showphoto ($modulepart, $object, $width=100, $height=0, $caneditfield=0, $cssclass= 'photowithmargin', $imagesize= '', $addlinktofullsize=1, $cache=0, $forcecapture= '')
Return HTML code to output a photo.
Protected Member Functions inherited from Form
editInPlace ($object, $value, $htmlname, $condition, $inputType= 'textarea', $editvalue=null, $extObject=null, $custommsg=null)
Output edit in place form.
constructProductListOption (&$objp, &$opt, &$optJson, $price_level, $selected, $hidepriceinlabel=0, $filterkey= '')
constructProductListOption.
Detailed Description
Class to manage HTML output components for orders Before adding component here, check they are not into common part Form.class.php.
Definition at line 31 of file html.formorder.class.php.
Member Function Documentation
selectInputMethod ($selected = '', $htmlname = 'source_id', $addempty = 0)
Return list of input method (mode used to receive order, like order received by email, fax, online) List found into table c_input_method.
Parameters
string $selected Id of preselected input method
string $htmlname Name of HTML select list
int $addempty 0=list with no empty value, 1=list with empty value
Returns
array Tableau des sources de commandes
Definition at line 77 of file html.formorder.class.php.
References $resql, db, dol_print_error(), dol_syslog(), print, and Form\selectarray().
selectSupplierOrderStatus ($selected = '', $short = 0, $hmlname = 'order_status')
Return combo list of differents status of a orders.
Parameters
string $selected Preselected value
int $short Use short labels
string $hmlname Name of HTML select element
Returns
void
Definition at line 42 of file html.formorder.class.php.
References db, print, and Form\selectarray().
The documentation for this class was generated from the following file:
htdocs/core/class/html.formorder.class.php