Dolibarr: ActionsCardService Class Reference
ActionsCardService Class Reference
Class with controller methods for product canvas.
Public Member Functions
__construct ($db, $targetmodule, $canvas, $card)
Constructor.
assign_values (&$action, $id=0, $ref= '')
Assign custom values for canvas (for example into this->tpl to be used by templates)
LoadListDatas ($limit, $offset, $sortfield, $sortorder)
Fetch datas list and save into ->list_datas.
Data Fields
$tpl = array()
Template container.
Private Member Functions
getFieldList ()
Fetch field list.
Detailed Description
Class with controller methods for product canvas.
Definition at line 29 of file actions_card_service.class.php.
Constructor & Destructor Documentation
__construct ($db, $targetmodule, $canvas, $card)
Constructor.
Parameters
DoliDB $db Handler acces base de donnees
string $targetmodule Name of directory of module where canvas is stored
string $canvas Name of canvas
string $card Name of tab (sub-canvas)
Definition at line 51 of file actions_card_service.class.php.
References db, and name.
Member Function Documentation
assign_values (& $action, $id = 0, $ref = '')
Assign custom values for canvas (for example into this->tpl to be used by templates)
Parameters
string $action Type of action
integer $id Id of object
string $ref Ref of object
Returns
void
Definition at line 75 of file actions_card_service.class.php.
References db, description, dol_get_fiche_end(), dol_get_fiche_head(), get_htmloutput_errors(), LoadListDatas(), note, product_prepare_head(), and Product\TYPE_SERVICE.
getFieldList () private
Fetch field list.
Returns
void
Definition at line 230 of file actions_card_service.class.php.
References $resql, db, dol_print_error(), and verifCond().
Referenced by LoadListDatas().
LoadListDatas ($limit, $offset, $sortfield, $sortorder)
Fetch datas list and save into ->list_datas.
Parameters
int $limit Limit number of responses
int $offset Offset for first response
string $sortfield Sort field
string $sortorder Sort order ('ASC' or 'DESC')
Returns
void
Definition at line 287 of file actions_card_service.class.php.
References $resql, db, dol_strlen(), getFieldList(), GETPOST(), and print.
Referenced by assign_values().
The documentation for this class was generated from the following file:
htdocs/product/canvas/service/actions_card_service.class.php