Dolibarr: ProjectStats Class Reference
ProjectStats Class Reference
Class to manage statistics on projects.
Public Member Functions
__construct ($db)
Constructor.
getAllProjectByStatus ($limit=5)
Return all leads grouped by opportunity status.
getAllByYear ()
Return count, and sum of products.
buildWhere ()
Build the where part.
getNbByMonth ($year, $format=0)
Return Project number by month for a year.
getAmountByMonth ($year, $format=0)
Return the Project amount by month for a year.
getWeightedAmountByMonthWithPrevYear ($endyear, $startyear, $cachedelay=0, $wonlostfilter=1)
Return amount of elements by month for several years.
getWeightedAmountByMonth ($year, $wonlostfilter=1)
Return the Project weighted opp amount by month for a year.
getTransformRateByMonthWithPrevYear ($endyear, $startyear, $cachedelay=0)
Return amount of elements by month for several years.
getTransformRateByMonth ($year, $format=0)
Return the Project transformation rate by month for a year.
Public Member Functions inherited from Stats
getNbByMonthWithPrevYear ($endyear, $startyear, $cachedelay=0, $format=0, $startmonth=1)
Return nb of elements by month for several years.
getAmountByMonthWithPrevYear ($endyear, $startyear, $cachedelay=0, $format=0, $startmonth=1)
Return amount of elements by month for several years.
getAverageByMonthWithPrevYear ($endyear, $startyear)
Return average of entity by month for several years.
getAllByProductEntry ($year, $cachedelay=0)
Return count, and sum of products.
Additional Inherited Members
Protected Member Functions inherited from Stats
_getNbByYear ($sql)
Return nb of elements by year.
_getAllByYear ($sql)
Return nb of elements, total amount and avg amount each year.
_getNbByMonth ($year, $sql, $format=0)
Renvoie le nombre de documents par mois pour une annee donnee Return number of documents per month for a given year.
_getAmountByMonth ($year, $sql, $format=0)
Renvoie le montant totalise par mois pour une annee donnee Return the amount per month for a given year.
_getAverageByMonth ($year, $sql, $format=0)
Renvoie le montant moyen par mois pour une annee donnee Return the amount average par month for a given year.
_getAllByProduct ($sql, $limit=10)
Return number or total of product refs.
Detailed Description
Class to manage statistics on projects.
Definition at line 25 of file projectstats.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 37 of file projectstats.class.php.
References db.
Member Function Documentation
buildWhere ()
Build the where part.
Returns
string
Definition at line 152 of file projectstats.class.php.
References db, dol_get_first_day(), dol_get_last_day(), and getEntity().
Referenced by getAllByYear(), getAllProjectByStatus(), getAmountByMonth(), getNbByMonth(), getTransformRateByMonth(), and getWeightedAmountByMonth().
getAllByYear ()
Return count, and sum of products.
Returns
array of values
Definition at line 121 of file projectstats.class.php.
References Stats\_getAllByYear(), buildWhere(), and db.
getAllProjectByStatus ($limit = 5)
Return all leads grouped by opportunity status.
Warning: There is no filter on WON/LOST because we want this for statistics.
Parameters
int $limit Limit results
Returns
array|int Array with value or -1 if error
Exceptions
Exception
Definition at line 56 of file projectstats.class.php.
References $resql, buildWhere(), db, dol_syslog(), price(), and price2num().
getAmountByMonth ($year, $format = 0)
Return the Project amount by month for a year.
Parameters
int $year Year to scan
int $format 0=Label of absiss is a translated text, 1=Label of absiss is month number, 2=Label of absiss is first letter of month
Returns
array Array with amount by month
Definition at line 225 of file projectstats.class.php.
References Stats\_getAmountByMonth(), buildWhere(), and db.
getNbByMonth ($year, $format = 0)
Return Project number by month for a year.
Parameters
int $year Year to scan
int $format 0=Label of absiss is a translated text, 1=Label of absiss is month number, 2=Label of absiss is first letter of month
Returns
array Array of values
Definition at line 196 of file projectstats.class.php.
References Stats\_getNbByMonth(), buildWhere(), and db.
getTransformRateByMonth ($year, $format = 0)
Return the Project transformation rate by month for a year.
Parameters
int $year Year to scan
int $format 0=Label of absiss is a translated text, 1=Label of absiss is month number, 2=Label of absiss is first letter of month
Returns
array Array with amount by month
Definition at line 459 of file projectstats.class.php.
References Stats\_getNbByMonth(), buildWhere(), and db.
Referenced by getTransformRateByMonthWithPrevYear().
getTransformRateByMonthWithPrevYear ($endyear, $startyear, $cachedelay = 0)
Return amount of elements by month for several years.
Parameters
int $endyear End year
int $startyear Start year
int $cachedelay accept for cache file (0=No read, no save of cache, -1=No read but save)
Returns
array of values
Definition at line 378 of file projectstats.class.php.
References dol_filemtime(), dol_is_dir(), dol_mkdir(), dol_now(), dol_syslog(), and getTransformRateByMonth().
getWeightedAmountByMonth ($year, $wonlostfilter = 1)
Return the Project weighted opp amount by month for a year.
Parameters
int $year Year to scan
int $wonlostfilter Add a filter on status won/lost
Returns
array Array with amount by month
Definition at line 349 of file projectstats.class.php.
References Stats\_getAmountByMonth(), buildWhere(), and db.
Referenced by getWeightedAmountByMonthWithPrevYear().
getWeightedAmountByMonthWithPrevYear ($endyear, $startyear, $cachedelay = 0, $wonlostfilter = 1)
Return amount of elements by month for several years.
Parameters
int $endyear Start year
int $startyear End year
int $cachedelay Delay we accept for cache file (0=No read, no save of cache, -1=No read but save)
int $wonlostfilter Add a filter on status won/lost
Returns
array Array of values
Definition at line 256 of file projectstats.class.php.
References dol_filemtime(), dol_is_dir(), dol_mkdir(), dol_now(), dol_syslog(), and getWeightedAmountByMonth().
The documentation for this class was generated from the following file:
htdocs/projet/class/projectstats.class.php