Dolibarr: Canvas Class Reference
Canvas Class Reference
Class to manage canvas.
Public Member Functions
__construct ($db, $actiontype= 'view')
Constructor.
getCanvas ($module, $card, $canvas)
Initialize properties: ->targetmodule, ->canvas, ->card, ->dirmodule, ->template_dir.
assign_values (&$action= 'view', $id=0, $ref= '')
Shared method for canvas to assign values for templates.
displayCanvasExists ($action)
Return the template to display canvas (if it exists)
display_canvas ($action)
Display a canvas page.
hasActions ()
Return if a canvas contains an action controller.
doActions (&$action= 'view', $id=0)
Shared method for canvas to execute actions.
Private Member Functions
_cleanaction ($action)
Return action code cleaned.
Detailed Description
Class to manage canvas.
Definition at line 29 of file canvas.class.php.
Constructor & Destructor Documentation
__construct ($db, $actiontype = 'view')
Constructor.
Parameters
DoliDB $db Database handler
string $actiontype Action type ('create', 'view', 'edit', 'list')
Definition at line 63 of file canvas.class.php.
References _cleanaction(), and db.
Member Function Documentation
_cleanaction ($action) private
Return action code cleaned.
Parameters
string $action Action type ('create', 'view', 'edit', 'list', 'add', 'update')
Returns
string Cleaned action type ('create', 'view', 'edit', 'list')
Definition at line 76 of file canvas.class.php.
Referenced by __construct(), and display_canvas().
assign_values (& $action = 'view', $id = 0, $ref = '')
Shared method for canvas to assign values for templates.
Parameters
string $action Action string
int $id Object id (if ref not provided)
string $ref Object ref (if id not provided)
Returns
void
Definition at line 145 of file canvas.class.php.
display_canvas ($action)
Display a canvas page.
This will include the template for output. Variables used by templates may have been defined or loaded before into the assign_values function.
Parameters
string $action Action code
Returns
void
Definition at line 173 of file canvas.class.php.
References _cleanaction().
displayCanvasExists ($action)
Return the template to display canvas (if it exists)
Parameters
string $action Action code
Returns
int 0=Canvas template file does not exist, 1=Canvas template file exists
Definition at line 157 of file canvas.class.php.
doActions (& $action = 'view', $id = 0)
Shared method for canvas to execute actions.
Deprecated:
Use the doActions of hooks instead of this. This function is called if you add a doActions class inside your canvas. Try to not do that and add action code into a hook instead.
Parameters
string $action Action string
int $id Object id
Returns
mixed Return return code of doActions of canvas
See also
http://wiki.dolibarr.org/index.php/Canvas_development
Definition at line 207 of file canvas.class.php.
getCanvas ($module, $card, $canvas)
Initialize properties: ->targetmodule, ->canvas, ->card, ->dirmodule, ->template_dir.
Parameters
string $module Name of target module (thirdparty, contact, ...)
string $card Tab name of card (ex: 'card', 'info', 'contactcard', ...) or '' for a list page
string $canvas Name of canvas (ex: mycanvas, default, or mycanvas)
Returns
void
Definition at line 94 of file canvas.class.php.
References db, and dol_buildpath().
hasActions ()
Return if a canvas contains an action controller.
Returns
boolean Return if canvas contains actions (old feature. now actions should be inside hooks)
Definition at line 191 of file canvas.class.php.
The documentation for this class was generated from the following file:
htdocs/core/class/canvas.class.php