Dolibarr: Utils Class Reference
Utils Class Reference
Class to manage utility methods.
Public Member Functions
__construct ($db)
Constructor.
purgeFiles ($choice= 'tempfilesold', $nbsecondsold=86400)
Purge files into directory of data files.
dumpDatabase ($compression= 'none', $type= 'auto', $usedefault=1, $file= 'auto', $keeplastnfiles=0, $execmethod=0)
Make a backup of database CAN BE A CRON TASK.
executeCLI ($command, $outputfile, $execmethod=0)
Execute a CLI command.
generateDoc ($module)
Generate documentation of a Module.
compressSyslogs ()
This saves syslog files and compresses older ones.
Detailed Description
Class to manage utility methods.
Definition at line 28 of file utils.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 43 of file utils.class.php.
References db.
Member Function Documentation
compressSyslogs ()
This saves syslog files and compresses older ones.
Nb of archive to keep is defined into $conf->global->SYSLOG_FILE_SAVES CAN BE A CRON TASK
Returns
int 0 if OK, < 0 if KO
Definition at line 790 of file utils.class.php.
References dol_delete_file(), dol_dir_list(), dol_filesize(), dol_include_once(), dol_is_file(), dol_move(), dol_syslog(), and GETPOST().
dumpDatabase ($compression = 'none', $type = 'auto', $usedefault = 1, $file = 'auto', $keeplastnfiles = 0, $execmethod = 0)
Make a backup of database CAN BE A CRON TASK.
Parameters
string $compression 'gz' or 'bz' or 'none'
string $type 'mysql', 'postgresql', ...
int $usedefault 1=Use default backup profile (Set this to 1 when used as cron)
string $file 'auto' or filename to build
int $keeplastnfiles Keep only last n files (not used yet)
int $execmethod 0=Use default method (that is 1 by default), 1=Use the PHP 'exec', 2=Use the 'popen' method
Returns
int 0 if OK, < 0 if KO (this function is used also by cron so only 0 is OK)
Definition at line 196 of file utils.class.php.
References dol_delete_file(), dol_dir_list(), dol_mkdir(), dol_sanitizeFileName(), dol_syslog(), and GETPOST().
executeCLI ($command, $outputfile, $execmethod = 0)
Execute a CLI command.
Parameters
string $command Command line to execute.
string $outputfile Output file (used only when method is 2). For exemple $conf->admin->dir_temp.'/out.tmp';
int $execmethod 0=Use default method (that is 1 by default), 1=Use the PHP 'exec', 2=Use the 'popen' method
Returns
array array('result'=>...,'output'=>...,'error'=>...). result = 0 means OK.
Definition at line 517 of file utils.class.php.
References dol_syslog().
generateDoc ($module)
Generate documentation of a Module.
Parameters
string $module Module name
Returns
int <0 if KO, >0 if OK
Definition at line 586 of file utils.class.php.
References db, dol_buildpath(), dol_copy(), dol_dir_list(), dol_include_once(), dol_is_dir(), dol_mkdir(), dol_now(), dol_print_date(), dol_print_error(), dolMd2Asciidoc(), and dolReplaceInFile().
purgeFiles ($choice = 'tempfilesold', $nbsecondsold = 86400)
Purge files into directory of data files.
CAN BE A CRON TASK
Parameters
string $choice Choice of purge mode ('tempfiles', '' or 'tempfilesold' to purge temp older than $nbsecondsold seconds, 'allfiles', 'logfile')
int $nbsecondsold Nb of seconds old to accept deletion of a directory if $choice is 'tempfilesold'
Returns
int 0 if OK, < 0 if KO (this function is used also by cron so only 0 is OK)
Definition at line 57 of file utils.class.php.
References db, dol_delete_dir_recursive(), dol_delete_file(), dol_dir_list(), dol_mkdir(), dol_now(), and dol_syslog().
The documentation for this class was generated from the following file:
htdocs/core/class/utils.class.php