Dolibarr: mod_contract_serpis Class Reference
mod_contract_serpis Class Reference
Class to manage contract numbering rules Serpis.
Public Member Functions
info ()
Return default description of numbering model.
getExample ()
Return numbering example.
canBeActivated ()
Test if existing numbers make problems with numbering.
getNextValue ($objsoc, $contract)
Return next value.
contract_get_num ($objsoc, $objforref)
Return next value.
Public Member Functions inherited from ModelNumRefContracts
isEnabled ()
Return if a module can be used or not.
info ()
Return default description of numbering model.
getExample ()
Return numbering example.
canBeActivated ()
Test if existing numbers make problems with numbering.
getNextValue ($objsoc, $contract)
Return next value.
getVersion ()
Return numbering version module.
Detailed Description
Class to manage contract numbering rules Serpis.
Definition at line 29 of file mod_contract_serpis.php.
Member Function Documentation
canBeActivated ()
Test if existing numbers make problems with numbering.
Returns
boolean false if conflit, true if ok
Definition at line 87 of file mod_contract_serpis.php.
References $resql.
contract_get_num ($objsoc, $objforref)
Return next value.
Parameters
Societe $objsoc third party object
Object $objforref contract object
Returns
string Value if OK, 0 if KO
Definition at line 164 of file mod_contract_serpis.php.
References getNextValue().
getExample ()
Return numbering example.
Returns
string Example
Definition at line 76 of file mod_contract_serpis.php.
getNextValue ($objsoc, $contract)
Return next value.
Parameters
Societe $objsoc third party object
Object $contract contract object
Returns
string Value if OK, 0 if KO
Definition at line 122 of file mod_contract_serpis.php.
References $resql, and dol_syslog().
Referenced by contract_get_num().
info ()
Return default description of numbering model.
Returns
string text description
Definition at line 64 of file mod_contract_serpis.php.
The documentation for this class was generated from the following file:
htdocs/core/modules/contract/mod_contract_serpis.php