Dolibarr: dolReceiptPrinter Class Reference
dolReceiptPrinter Class Reference
Class to manage Receipt Printers.
Public Member Functions
__construct ($db)
Constructor.
listPrinters ()
list printers
listPrintersTemplates ()
List printers templates.
selectTypePrinter ($selected= '', $htmlname= 'printertypeid')
Form to Select type printer.
selectProfilePrinter ($selected= '', $htmlname= 'printerprofileid')
Form to Select Profile printer.
addPrinter ($name, $type, $profile, $parameter)
Function to Add a printer in db.
updatePrinter ($name, $type, $profile, $parameter, $printerid)
Function to Update a printer in db.
deletePrinter ($printerid)
Function to Delete a printer from db.
updateTemplate ($name, $template, $templateid)
Function to Update a printer template in db.
sendTestToPrinter ($printerid)
Function to Send Test page to Printer.
sendToPrinter ($object, $templateid, $printerid)
Function to Print Receipt Ticket.
loadTemplate ($templateid)
Function to load Template.
initPrinter ($printerid)
Function Init Printer.
Detailed Description
Class to manage Receipt Printers.
Definition at line 101 of file dolreceiptprinter.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db database
Definition at line 135 of file dolreceiptprinter.class.php.
References db.
Member Function Documentation
addPrinter ($name, $type, $profile, $parameter)
Function to Add a printer in db.
Parameters
string $name Printer name
int $type Printer type
int $profile Printer profile
string $parameter Printer parameter
Returns
int 0 if OK; >0 if KO
Definition at line 364 of file dolreceiptprinter.class.php.
References $resql, and db.
deletePrinter ($printerid)
Function to Delete a printer from db.
Parameters
int $printerid Printer id
Returns
int 0 if OK; >0 if KO
Definition at line 413 of file dolreceiptprinter.class.php.
References $resql, and db.
initPrinter ($printerid)
Function Init Printer.
Parameters
int $printerid Printer id
Returns
int 0 if OK; >0 if KO
Definition at line 650 of file dolreceiptprinter.class.php.
References $resql, and db.
Referenced by sendTestToPrinter(), and sendToPrinter().
listPrinters ()
list printers
Returns
int 0 if OK; >0 if KO
Definition at line 214 of file dolreceiptprinter.class.php.
References $resql, and db.
listPrintersTemplates ()
List printers templates.
Returns
int 0 if OK; >0 if KO
Definition at line 282 of file dolreceiptprinter.class.php.
References $resql, and db.
loadTemplate ($templateid)
Function to load Template.
Parameters
int $templateid Template id
Returns
int 0 if OK; >0 if KO
Definition at line 618 of file dolreceiptprinter.class.php.
References $resql, and db.
Referenced by sendToPrinter().
selectProfilePrinter ($selected = '', $htmlname = 'printerprofileid')
Form to Select Profile printer.
Parameters
string $selected Id printer profile pre-selected
string $htmlname select html name
Returns
int 0 if OK; >0 if KO
Definition at line 338 of file dolreceiptprinter.class.php.
References Form\selectarray().
selectTypePrinter ($selected = '', $htmlname = 'printertypeid')
Form to Select type printer.
Parameters
string $selected Id printer type pre-selected
string $htmlname select html name
Returns
int 0 if OK; >0 if KO
Definition at line 314 of file dolreceiptprinter.class.php.
References Form\selectarray().
sendTestToPrinter ($printerid)
Function to Send Test page to Printer.
Parameters
int $printerid Printer id
Returns
int 0 if OK; >0 if KO
Definition at line 458 of file dolreceiptprinter.class.php.
References initPrinter(), and setEventMessages().
sendToPrinter ($object, $templateid, $printerid)
Function to Print Receipt Ticket.
Parameters
object $object order or invoice object
int $templateid Template id
int $printerid Printer id
Returns
int 0 if OK; >0 if KO
Definition at line 493 of file dolreceiptprinter.class.php.
References initPrinter(), loadTemplate(), print, and setEventMessages().
updatePrinter ($name, $type, $profile, $parameter, $printerid)
Function to Update a printer in db.
Parameters
string $name Printer name
int $type Printer type
int $profile Printer profile
string $parameter Printer parameter
int $printerid Printer id
Returns
int 0 if OK; >0 if KO
Definition at line 389 of file dolreceiptprinter.class.php.
References $resql, and db.
updateTemplate ($name, $template, $templateid)
Function to Update a printer template in db.
Parameters
string $name Template name
int $template Template
int $templateid Template id
Returns
int 0 if OK; >0 if KO
Definition at line 435 of file dolreceiptprinter.class.php.
References $resql, and db.
The documentation for this class was generated from the following file:
htdocs/core/class/dolreceiptprinter.class.php