Dolibarr: PaymentTerm Class Reference
PaymentTerm Class Reference
Class to manage payment terms records in dictionary.
Public Member Functions
__construct ($db)
Constructor.
create ($user, $notrigger=0)
Create in database.
fetch ($id)
Load object in memory from database.
getDefaultId ()
Return id of default payment term.
update ($user=null, $notrigger=0)
Update database.
delete ($user, $notrigger=0)
Delete object in database.
createFromClone (User $user, $fromid)
Load an object from its id and create a new one in database.
initAsSpecimen ()
Initialise an instance with random values.
Detailed Description
Class to manage payment terms records in dictionary.
Definition at line 29 of file paymentterm.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 72 of file paymentterm.class.php.
References db.
Member Function Documentation
create ($user, $notrigger = 0)
Create in database.
Parameters
User $user User that create
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, Id of created object if OK
Definition at line 85 of file paymentterm.class.php.
References $resql, db, dol_syslog(), and getEntity().
createFromClone (User $user, $fromid)
Load an object from its id and create a new one in database.
Parameters
User $user User making the clone
int $fromid Id of object to clone
Returns
int New id of clone
Definition at line 400 of file paymentterm.class.php.
References db.
delete ($user, $notrigger = 0)
Delete object in database.
Parameters
User $user User that delete
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 348 of file paymentterm.class.php.
References $resql, db, and dol_syslog().
fetch ($id)
Load object in memory from database.
Parameters
int $id Id object
Returns
int <0 if KO, >0 if OK
Definition at line 176 of file paymentterm.class.php.
References $resql, db, and dol_syslog().
getDefaultId ()
Return id of default payment term.
Returns
int <0 if KO, >0 if OK
Definition at line 232 of file paymentterm.class.php.
References $resql, db, and dol_syslog().
initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
void
Definition at line 450 of file paymentterm.class.php.
update ($user = null, $notrigger = 0)
Update database.
Parameters
User $user User that modify
int $notrigger 0=launch triggers after, 1=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 271 of file paymentterm.class.php.
References $resql, db, and dol_syslog().
The documentation for this class was generated from the following file:
htdocs/compta/facture/class/paymentterm.class.php