Dolibarr: pdf_eratosthene Class Reference
pdf_eratosthene Class Reference
Class to generate PDF orders with template Eratosthene.
Public Member Functions
__construct ($db)
Constructor.
write_file ($object, $outputlangs, $srctemplatepath= '', $hidedetails=0, $hidedesc=0, $hideref=0)
Function to build pdf onto disk.
defineColumnField ($object, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0)
Define Array Column Field.
Public Member Functions inherited from CommonDocGenerator
__construct ($db)
Constructor.
get_substitutionarray_user ($user, $outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_mysoc ($mysoc, $outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_thirdparty ($object, $outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_contact ($object, $outputlangs, $array_key= 'object')
Define array with couple subtitution key => subtitution value.
get_substitutionarray_other ($outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_object ($object, $outputlangs, $array_key= 'object')
Define array with couple substitution key => substitution value.
get_substitutionarray_lines ($line, $outputlangs)
Define array with couple substitution key => substitution value.
get_substitutionarray_shipment ($object, $outputlangs, $array_key= 'object')
Define array with couple substitution key => substitution value.
get_substitutionarray_shipment_lines ($line, $outputlangs)
Define array with couple substitution key => substitution value.
get_substitutionarray_each_var_object (&$object, $outputlangs, $recursive=true)
Define array with couple subtitution key => subtitution value.
fill_substitutionarray_with_extrafields ($object, $array_to_fill, $extrafields, $array_key, $outputlangs)
Fill array with couple extrafield key => extrafield value.
printRect ($pdf, $x, $y, $l, $h, $hidetop=0, $hidebottom=0)
Rect pdf.
columnSort ($a, $b)
uasort callback function to Sort colums fields
prepareArrayColumnField ($object, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0)
Prepare Array Column Field.
getColumnContentWidth ($colKey)
get column content width from column key
getColumnContentXStart ($colKey)
get column content X (abscissa) left position from column key
getColumnRank ($colKey)
get column position rank from column key
insertNewColumnDef ($newColKey, $defArray, $targetCol=false, $insertAfterTarget=false)
get column position rank from column key
printStdColumnContent ($pdf, &$curY, $colKey, $columnText= '')
print standard column content
getColumnStatus ($colKey)
get column status from column key
pdfTabTitles (&$pdf, $tab_top, $tab_height, $outputlangs, $hidetop=0)
Print standard column content.
Protected Member Functions
drawPaymentsTable (&$pdf, $object, $posy, $outputlangs)
Show payments table.
drawInfoTable (&$pdf, $object, $posy, $outputlangs)
Show miscellaneous information (payment mode, payment term, ...)
drawTotalTable (&$pdf, $object, $deja_regle, $posy, $outputlangs)
Show total to pay.
_tableau (&$pdf, $tab_top, $tab_height, $nexY, $outputlangs, $hidetop=0, $hidebottom=0, $currency= '')
Show table for lines.
_pagehead (&$pdf, $object, $showaddress, $outputlangs, $titlekey="PdfOrderTitle")
Show top header of page.
_pagefoot (&$pdf, $object, $outputlangs, $hidefreetext=0)
Show footer of page.
Additional Inherited Members
Static Public Member Functions inherited from ModelePDFCommandes
static liste_modeles ($db, $maxfilenamelength=0)
Return list of active generation modules.
Detailed Description
Class to generate PDF orders with template Eratosthene.
Definition at line 43 of file pdf_eratosthene.modules.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 129 of file pdf_eratosthene.modules.php.
References db, description, name, pdf_getFormat(), and type.
Member Function Documentation
_pagefoot (& $pdf, $object, $outputlangs, $hidefreetext = 0) protected
Show footer of page.
Need this->emetteur object
Parameters
TCPDF $pdf PDF
Object $object Object to show
Translate $outputlangs Object lang for output
int $hidefreetext 1=Hide free text
Returns
int Return height of bottom margin including footer text
Definition at line 1582 of file pdf_eratosthene.modules.php.
References pdf_pagefoot().
Referenced by write_file().
_pagehead (& $pdf, $object, $showaddress, $outputlangs, $titlekey = "PdfOrderTitle") protected
Show top header of page.
Parameters
TCPDF $pdf Object PDF
Object $object Object to show
int $showaddress 0=no, 1=yes
Translate $outputlangs Object lang for output
string $titlekey Translation key to show as title of document
Returns
void
Definition at line 1368 of file pdf_eratosthene.modules.php.
References db, dol_print_date(), pdf_build_address(), pdf_getHeightForLogo(), pdf_getPDFFontSize(), pdf_pagehead(), pdf_watermark(), pdf_writeLinkedObjects(), and pdfBuildThirdpartyName().
Referenced by write_file().
_tableau (& $pdf, $tab_top, $tab_height, $nexY, $outputlangs, $hidetop = 0, $hidebottom = 0, $currency = '') protected
Show table for lines.
Parameters
TCPDF $pdf Object PDF
string $tab_top Top position of table
string $tab_height Height of table (rectangle)
int $nexY Y (not used)
Translate $outputlangs Langs object
int $hidetop 1=Hide top bar of array and title, 0=Hide nothing, -1=Hide only title
int $hidebottom Hide bottom bar of array
string $currency Currency code
Returns
void
Definition at line 1317 of file pdf_eratosthene.modules.php.
References pdf_getPDFFontSize(), CommonDocGenerator\pdfTabTitles(), and CommonDocGenerator\printRect().
Referenced by write_file().
defineColumnField ($object, $outputlangs, $hidedetails = 0, $hidedesc = 0, $hideref = 0)
Define Array Column Field.
Parameters
object $object common object
Translate $outputlangs langs
int $hidedetails Do not show line details
int $hidedesc Do not show desc
int $hideref Do not show ref
Returns
null
Definition at line 1602 of file pdf_eratosthene.modules.php.
References setEventMessages().
drawInfoTable (& $pdf, $object, $posy, $outputlangs) protected
Show miscellaneous information (payment mode, payment term, ...)
Parameters
TCPDF $pdf Object PDF
Object $object Object to show
int $posy Y
Translate $outputlangs Langs object
Returns
void
Definition at line 871 of file pdf_eratosthene.modules.php.
References db, dol_print_date(), pdf_bank(), and pdf_getPDFFontSize().
Referenced by write_file().
drawPaymentsTable (& $pdf, $object, $posy, $outputlangs) protected
Show payments table.
Parameters
TCPDF $pdf Object PDF
Object $object Object order
int $posy Position y in PDF
Translate $outputlangs Object langs for output
Returns
int <0 if KO, >0 if OK
Definition at line 858 of file pdf_eratosthene.modules.php.
drawTotalTable (& $pdf, $object, $deja_regle, $posy, $outputlangs) protected
Show total to pay.
Parameters
TCPDF $pdf Object PDF
Facture $object Object invoice
int $deja_regle Montant deja regle
int $posy Position depart
Translate $outputlangs Objet langs
Returns
int Position pour suite
Definition at line 1057 of file pdf_eratosthene.modules.php.
References if, pdf_getPDFFontSize(), price(), price2num(), and vatrate().
Referenced by write_file().
write_file ($object, $outputlangs, $srctemplatepath = '', $hidedetails = 0, $hidedesc = 0, $hideref = 0)
Function to build pdf onto disk.
Parameters
Object $object Object to generate
Translate $outputlangs Lang output object
string $srctemplatepath Full path of source filename for generator using a template file
int $hidedetails Do not show line details
int $hidedesc Do not show desc
int $hideref Do not show ref
Returns
int 1=OK, 0=KO
Does we have at least one line with discount $this->atleastonediscount
Definition at line 194 of file pdf_eratosthene.modules.php.
References _pagefoot(), _pagehead(), _tableau(), complete_substitutions_array(), convertBackOfficeMediasLinksToPublicLinks(), db, dol_concatdesc(), dol_htmlentitiesbr(), dol_mkdir(), dol_sanitizeFileName(), drawInfoTable(), drawTotalTable(), get_exdir(), CommonDocGenerator\getColumnContentWidth(), CommonDocGenerator\getColumnContentXStart(), CommonDocGenerator\getColumnStatus(), getLocalTaxesFromRate(), if, make_substitutions(), pdf_getInstance(), pdf_getlineqty(), pdf_getlineremisepercent(), pdf_getlinetotalexcltax(), pdf_getlineunit(), pdf_getlineupexcltax(), pdf_getlinevatrate(), pdf_getPDFFont(), pdf_getPDFFontSize(), pdf_getSizeForImage(), pdf_getSubstitutionArray(), pdf_writelinedesc(), CommonDocGenerator\pdfTabTitles(), CommonDocGenerator\prepareArrayColumnField(), and CommonDocGenerator\printStdColumnContent().
The documentation for this class was generated from the following file:
htdocs/core/modules/commande/doc/pdf_eratosthene.modules.php