Dolibarr: htdocs/core/lib/parsemd.lib.php File Reference
parsemd.lib.php File Reference
This file contains functions dedicated to MD parsind.
Functions
dolMd2Html ($content, $parser= 'parsedown', $replaceimagepath=null)
Function to parse MD content into HTML.
dolMd2Asciidoc ($content, $parser= 'dolibarr', $replaceimagepath=null)
Function to parse MD content into ASCIIDOC.
Detailed Description
This file contains functions dedicated to MD parsind.
Definition in file parsemd.lib.php.
Function Documentation
dolMd2Asciidoc ($content, $parser = 'dolibarr', $replaceimagepath = null)
Function to parse MD content into ASCIIDOC.
Parameters
string $content MD content
string $parser 'dolibarr'
string $replaceimagepath Replace path to image with another path. Exemple: ('doc/'=>'xxx/aaa/')
Returns
string Parsed content
Definition at line 66 of file parsemd.lib.php.
Referenced by Utils\generateDoc().
dolMd2Html ($content, $parser = 'parsedown', $replaceimagepath = null)
Function to parse MD content into HTML.
Parameters
string $content MD content
string $parser 'parsedown' or 'nl2br'
string $replaceimagepath Replace path to image with another path. Exemple: ('doc/'=>'xxx/aaa/')
Returns
string Parsed content
Definition at line 32 of file parsemd.lib.php.
Referenced by DolibarrModules\getChangeLog(), and DolibarrModules\getDescLong().