Dolibarr: Ctyperesource Class Reference
Ctyperesource Class Reference
Class Ctyperesource.
Public Member Functions
__construct (DoliDB $db)
Constructor.
create (User $user, $notrigger=false)
Create object into database.
fetch ($id, $code= '', $label= '')
Load object in memory from the database.
fetchAll ($sortorder= '', $sortfield= '', $limit=0, $offset=0, array $filter=array(), $filtermode= 'AND')
Load object in memory from the database.
update (User $user, $notrigger=false)
Update object into database.
delete (User $user, $notrigger=false)
Delete object in database.
createFromClone (User $user, $fromid)
Load an object from its id and create a new one in database.
initAsSpecimen ()
Initialise object with example values Id must be 0 if object instance is a specimen.
Detailed Description
Class Ctyperesource.
Put here description of your class
See also
CommonObject
Definition at line 33 of file ctyperesource.class.php.
Constructor & Destructor Documentation
__construct (DoliDB $db)
Constructor.
Parameters
DoliDb $db Database handler
Definition at line 65 of file ctyperesource.class.php.
References db.
Member Function Documentation
create (User $user, $notrigger = false)
Create object into database.
Parameters
User $user User that creates
bool $notrigger false=launch triggers after, true=disable triggers
Returns
int <0 if KO, Id of created object if OK
Definition at line 78 of file ctyperesource.class.php.
References $resql, db, dol_syslog(), and label.
createFromClone (User $user, $fromid)
Load an object from its id and create a new one in database.
Parameters
User $user User making the clone
int $fromid Id of object to clone
Returns
int New id of clone
Definition at line 411 of file ctyperesource.class.php.
References db, and dol_syslog().
delete (User $user, $notrigger = false)
Delete object in database.
Parameters
User $user User that deletes
bool $notrigger false=launch triggers after, true=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 360 of file ctyperesource.class.php.
References $resql, db, and dol_syslog().
fetch ($id, $code = '', $label = '')
Load object in memory from the database.
Parameters
int $id Id object
string $code code
string $label Label
Returns
int <0 if KO, 0 if not found, >0 if OK
Definition at line 162 of file ctyperesource.class.php.
References $resql, db, dol_syslog(), and label.
fetchAll ($sortorder = '', $sortfield = '', $limit = 0, $offset = 0, array $filter = array(), $filtermode = 'AND')
Load object in memory from the database.
Parameters
string $sortorder Sort Order
string $sortfield Sort field
int $limit offset limit
int $offset offset limit
array $filter filter array
string $filtermode filter mode (AND or OR)
Returns
int <0 if KO, >0 if OK
Definition at line 226 of file ctyperesource.class.php.
References $resql, db, and dol_syslog().
initAsSpecimen ()
Initialise object with example values Id must be 0 if object instance is a specimen.
Returns
void
Definition at line 459 of file ctyperesource.class.php.
References label.
update (User $user, $notrigger = false)
Update object into database.
Parameters
User $user User that modifies
bool $notrigger false=launch triggers after, true=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 290 of file ctyperesource.class.php.
References $resql, db, dol_syslog(), and label.
The documentation for this class was generated from the following file:
htdocs/core/class/ctyperesource.class.php