Dolibarr: DolibarrModules Class Reference
DolibarrModules Class Reference
Class DolibarrModules.
Public Member Functions
__construct ($db)
Constructor.
getName ()
Gives the translated module name if translation exists in admin.lang or into language files of module.
getDesc ()
Gives the translated module description if translation exists in admin.lang or the default module description.
getDescLong ()
Gives the long description of a module.
getDescLongReadmeFound ()
Return path of file if a README file was found.
getChangeLog ()
Gives the changelog.
getPublisher ()
Gives the publisher name.
getPublisherUrl ()
Gives the publisher url.
getVersion ($translated=1)
Gives module version (translated if param $translated is on) For 'experimental' modules, gives 'experimental' translation For 'dolibarr' modules, gives Dolibarr version.
isCoreOrExternalModule ()
Tells if module is core or external.
getLangFilesArray ()
Gives module related language files list.
getExportDatasetLabel ($r)
Gives translated label of an export dataset.
getImportDatasetLabel ($r)
Gives translated label of an import dataset.
getLastActivationDate ()
Gives the last date of activation.
getLastActivationInfo ()
Gives the last author of activation.
insert_boxes ($option= '')
Adds boxes.
delete_boxes ()
Removes boxes.
insert_cronjobs ()
Adds cronjobs.
delete_cronjobs ()
Removes boxes.
delete_tabs ()
Removes tabs.
insert_tabs ()
Adds tabs.
insert_const ()
Adds constants.
delete_const ()
Removes constants tagged 'deleteonunactive'.
insert_permissions ($reinitadminperms=0, $force_entity=null, $notrigger=0)
Adds access rights.
delete_permissions ()
Removes access rights.
insert_menus ()
Adds menu entries.
delete_menus ()
Removes menu entries.
create_dirs ()
Creates directories.
insert_dirs ($name, $dir)
Adds directories definitions.
delete_dirs ()
Removes directories.
insert_module_parts ()
Adds generic parts.
delete_module_parts ()
Removes generic parts.
init ($options= '')
Function called when module is enabled.
remove ($options= '')
Function called when module is disabled.
Protected Member Functions
_init ($array_sql, $options= '')
Enables a module.
_remove ($array_sql, $options= '')
Disable function.
_active ()
Insert constants for module activation.
_unactive ()
Module deactivation.
_load_tables ($reldir)
Create tables and keys required by module.
Detailed Description
Class DolibarrModules.
Parent class for module descriptor class files
Definition at line 37 of file DolibarrModules.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Define names, constants, directories, boxes, permissions
Parameters
DoliDB $db Database handler
Definition at line 363 of file DolibarrModules.class.php.
References db.
Member Function Documentation
_active () protected
Insert constants for module activation.
Returns
int Error count (0 if OK)
Definition at line 991 of file DolibarrModules.class.php.
References $resql, db, and dol_syslog().
Referenced by _init().
_init ($array_sql, $options = '') protected
Enables a module.
Inserts all informations into database
Parameters
array $array_sql SQL requests to be executed when enabling module
string $options String with options when disabling module:
'noboxes' = Do not insert boxes - 'newboxdefonly' = For boxes, insert def of boxes only and not boxes activation
Returns
int 1 if OK, 0 if KO
Definition at line 386 of file DolibarrModules.class.php.
References _active(), create_dirs(), db, dol_syslog(), insert_boxes(), insert_const(), insert_cronjobs(), insert_menus(), insert_module_parts(), insert_permissions(), and insert_tabs().
Referenced by modExternalRss\init(), modNotification\init(), modDebugBar\init(), modLabel\init(), modDocumentGeneration\init(), modComptabilite\init(), modProductBatch\init(), modBarcode\init(), modOauth\init(), modReceiptPrinter\init(), modHRM\init(), modCashDesk\init(), modPrelevement\init(), modMailing\init(), modWorkflow\init(), modDon\init(), modWebsite\init(), modDeplacement\init(), modLoan\init(), modBlockedLog\init(), modSalaries\init(), modOpenSurvey\init(), modTax\init(), modSupplierProposal\init(), modFicheinter\init(), modDataPolicy\init(), modExpenseReport\init(), modBanque\init(), modContrat\init(), modAsset\init(), modApi\init(), modReception\init(), modMultiCurrency\init(), modPropale\init(), modCommande\init(), modTicket\init(), modEmailCollector\init(), modTakePos\init(), modDav\init(), modResource\init(), modProjet\init(), modBom\init(), modExpedition\init(), modUser\init(), modStock\init(), modMyModule\init(), modFacture\init(), modAdherent\init(), modCategorie\init(), modService\init(), modFournisseur\init(), modProduct\init(), modSociete\init(), and init().
_load_tables ($reldir) protected
Create tables and keys required by module.
Files module.sql and module.key.sql with create table and create keys commands must be stored in directory reldir='/module/sql/' This function is called by this->init
Parameters
string $reldir Relative directory where to scan files
Returns
int <=0 if KO, >0 if OK
Definition at line 1065 of file DolibarrModules.class.php.
References dol_syslog(), and run_sql().
Referenced by modDataPolicy\init(), modApi\init(), modTakePos\init(), modBom\init(), modMyModule\init(), and modResource\loadTables().
_remove ($array_sql, $options = '') protected
Disable function.
Deletes the module constants and boxes from the database.
Parameters
string[] $array_sql SQL requests to be executed when module is disabled
string $options Options when disabling module:
Returns
int 1 if OK, 0 if KO
Definition at line 490 of file DolibarrModules.class.php.
References _unactive(), db, delete_boxes(), delete_const(), delete_cronjobs(), delete_dirs(), delete_menus(), delete_module_parts(), delete_permissions(), delete_tabs(), and dol_syslog().
Referenced by modExternalRss\remove(), modBlockedLog\remove(), modApi\remove(), modSupplierProposal\remove(), modDataPolicy\remove(), modMultiCurrency\remove(), modTakePos\remove(), modEmailCollector\remove(), modDav\remove(), modBom\remove(), modMyModule\remove(), and remove().
_unactive () protected
Module deactivation.
Returns
int Error count (0 if OK)
Definition at line 1034 of file DolibarrModules.class.php.
References db, and dol_syslog().
Referenced by _remove().
create_dirs ()
Creates directories.
Returns
int Error count (0 if OK)
Definition at line 2016 of file DolibarrModules.class.php.
References dol_mkdir(), dol_syslog(), and insert_dirs().
Referenced by _init().
delete_boxes ()
Removes boxes.
Returns
int Error count (0 if OK)
Definition at line 1282 of file DolibarrModules.class.php.
References $resql, db, and dol_syslog().
Referenced by _remove().
delete_const ()
Removes constants tagged 'deleteonunactive'.
Returns
int <0 if KO, 0 if OK
Definition at line 1672 of file DolibarrModules.class.php.
References db, and dol_syslog().
Referenced by _remove().
delete_cronjobs ()
Removes boxes.
Returns
int Error count (0 if OK)
Definition at line 1477 of file DolibarrModules.class.php.
References $resql, db, dol_syslog(), and name.
Referenced by _remove().
delete_dirs ()
Removes directories.
Returns
int Error count (0 if OK)
Definition at line 2120 of file DolibarrModules.class.php.
References db, and dol_syslog().
Referenced by _remove().
delete_menus ()
Removes menu entries.
Returns
int Error count (0 if OK)
Definition at line 1986 of file DolibarrModules.class.php.
References $resql, db, dol_syslog(), and name.
Referenced by _remove().
delete_module_parts ()
Removes generic parts.
Returns
int Error count (0 if OK)
Definition at line 2223 of file DolibarrModules.class.php.
References db, and dol_syslog().
Referenced by _remove().
delete_permissions ()
Removes access rights.
Returns
int Error count (0 if OK)
Definition at line 1855 of file DolibarrModules.class.php.
References db, dol_syslog(), and name.
Referenced by _remove().
delete_tabs ()
Removes tabs.
Returns
int Error count (0 if OK)
Definition at line 1508 of file DolibarrModules.class.php.
References db, and dol_syslog().
Referenced by _remove().
getChangeLog ()
Gives the changelog.
First check ChangeLog-la_LA.md then ChangeLog.md
Returns
string Content of ChangeLog
Definition at line 738 of file DolibarrModules.class.php.
References dol_buildpath(), dol_is_file(), dolMd2Html(), and name.
getDesc ()
Gives the translated module description if translation exists in admin.lang or the default module description.
Returns
string Translated module description
Definition at line 611 of file DolibarrModules.class.php.
References description, and name.
getDescLong ()
Gives the long description of a module.
First check README-la_LA.md then README.md If no markdown files found, it returns translated value of the key ->descriptionlong.
Returns
string Long description of a module from README.md of from property.
Definition at line 647 of file DolibarrModules.class.php.
References dol_buildpath(), dolMd2Html(), getDescLongReadmeFound(), and name.
getDescLongReadmeFound ()
Return path of file if a README file was found.
Returns
string Path of file if a README file was found.
Definition at line 703 of file DolibarrModules.class.php.
References dol_buildpath(), dol_is_file(), and name.
Referenced by getDescLong().
getExportDatasetLabel ($r)
Gives translated label of an export dataset.
Parameters
int $r Dataset index
Returns
string Translated databaset label
Definition at line 873 of file DolibarrModules.class.php.
getImportDatasetLabel ($r)
Gives translated label of an import dataset.
Parameters
int $r Dataset index
Returns
string Translated dataset label
Definition at line 897 of file DolibarrModules.class.php.
getLangFilesArray ()
Gives module related language files list.
Returns
string[] Language files list
Definition at line 861 of file DolibarrModules.class.php.
getLastActivationDate ()
Gives the last date of activation.
Returns
timestamp|string Date of last activation
Definition at line 920 of file DolibarrModules.class.php.
References $resql, db, and dol_syslog().
getLastActivationInfo ()
Gives the last author of activation.
Returns
array Array array('authorid'=>Id of last activation user, 'lastactivationdate'=>Date of last activation)
Definition at line 953 of file DolibarrModules.class.php.
References $resql, db, and dol_syslog().
getName ()
Gives the translated module name if translation exists in admin.lang or into language files of module.
Otherwise return the module key name.
Returns
string Translated module name
Definition at line 575 of file DolibarrModules.class.php.
References name.
getPublisher ()
Gives the publisher name.
Returns
string Publisher name
Definition at line 783 of file DolibarrModules.class.php.
getPublisherUrl ()
Gives the publisher url.
Returns
string Publisher url
Definition at line 793 of file DolibarrModules.class.php.
getVersion ($translated = 1)
Gives module version (translated if param $translated is on) For 'experimental' modules, gives 'experimental' translation For 'dolibarr' modules, gives Dolibarr version.
Parameters
int $translated 1=Special version keys are translated, 0=Special version keys are not translated
Returns
string Module version
Definition at line 806 of file DolibarrModules.class.php.
init ($options = '')
Function called when module is enabled.
The init function adds tabs, constants, boxes, permissions and menus (defined in constructor) into Dolibarr database. It also creates data directories
Parameters
string $options Options when enabling module ('', 'newboxdefonly', 'noboxes') 'noboxes' = Do not insert boxes 'newboxdefonly' = For boxes, insert def of boxes only and not boxes activation
Returns
int 1 if OK, 0 if KO
Definition at line 2262 of file DolibarrModules.class.php.
References _init().
insert_boxes ($option = '')
Adds boxes.
Parameters
string $option Options when disabling module ('newboxdefonly'=insert only boxes definition)
Returns
int Error count (0 if OK)
Definition at line 1184 of file DolibarrModules.class.php.
References $resql, db, dol_syslog(), and InfoBox\getListOfPagesForBoxes().
Referenced by _init().
insert_const ()
Adds constants.
Returns
int Error count (0 if OK)
Definition at line 1600 of file DolibarrModules.class.php.
References db, dol_syslog(), and if.
Referenced by _init().
insert_cronjobs ()
Adds cronjobs.
Returns
int Error count (0 if OK)
Definition at line 1355 of file DolibarrModules.class.php.
References $resql, db, dol_now(), dol_syslog(), and name.
Referenced by _init().
insert_dirs ($name, $dir)
Adds directories definitions.
Parameters
string $name Name
string $dir Directory
Returns
int Error count (0 if OK)
Definition at line 2079 of file DolibarrModules.class.php.
References db, dol_syslog(), and name.
Referenced by create_dirs().
insert_menus ()
Adds menu entries.
Returns
int Error count (0 if OK)
Definition at line 1881 of file DolibarrModules.class.php.
References db, dol_syslog(), and name.
Referenced by _init().
insert_module_parts ()
Adds generic parts.
Returns
int Error count (0 if OK)
Definition at line 2146 of file DolibarrModules.class.php.
References $resql, db, and dol_syslog().
Referenced by _init().
insert_permissions ($reinitadminperms = 0, $force_entity = null, $notrigger = 0)
Adds access rights.
Parameters
int $reinitadminperms If 1, we also grant them to all admin users
int $force_entity Force current entity
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int Error count (0 if OK)
Definition at line 1711 of file DolibarrModules.class.php.
References $resql, db, dol_print_error(), dol_strlen(), dol_syslog(), and name.
Referenced by _init().
insert_tabs ()
Adds tabs.
Returns
int Error count (0 if ok)
Definition at line 1534 of file DolibarrModules.class.php.
References $resql, db, and dol_syslog().
Referenced by _init().
isCoreOrExternalModule ()
Tells if module is core or external.
Returns
string 'core', 'external' or 'unknown'
Definition at line 838 of file DolibarrModules.class.php.
remove ($options = '')
Function called when module is disabled.
The remove function removes tabs, constants, boxes, permissions and menus from Dolibarr database. Data directories are not deleted
Parameters
string $options Options when enabling module ('', 'noboxes')
Returns
int 1 if OK, 0 if KO
Definition at line 2275 of file DolibarrModules.class.php.
References _remove().
The documentation for this class was generated from the following file:
htdocs/core/modules/DolibarrModules.class.php