Dolibarr: Contracts Class Reference
Contracts Class Reference
Public Member Functions
__construct ()
Constructor.
get ($id)
Get properties of a contract object.
post ($request_data=null)
Create contract object.
getLines ($id)
Get lines of a contract.
postLine ($id, $request_data=null)
Add a line to given contract.
putLine ($id, $lineid, $request_data=null)
Update a line to given contract.
activateLine ($id, $lineid, $datestart, $dateend=null, $comment=null)
Activate a service line of a given contract.
unactivateLine ($id, $lineid, $datestart, $comment=null)
Unactivate a service line of a given contract.
deleteLine ($id, $lineid)
Delete a line to given contract.
put ($id, $request_data=null)
Update contract general fields (won't touch lines of contract)
delete ($id)
Delete contract.
validate ($id, $notrigger=0)
Validate a contract.
close ($id, $notrigger=0)
Close all services of a contract.
Public Member Functions inherited from DolibarrApi
__construct ($db, $cachedir= '', $refreshCache=false)
Constructor.
Protected Member Functions
_cleanObjectDatas ($object)
Clean sensible object datas.
Protected Member Functions inherited from DolibarrApi
_cleanObjectDatas ($object)
Executed method when API is called without parameter.
_checkFilters ($sqlfilters)
Return if a $sqlfilters parameter is valid.
Private Member Functions
_validate ($data)
Validate fields before create or update object.
Additional Inherited Members
Static Protected Member Functions inherited from DolibarrApi
static _checkAccessToResource ($resource, $resource_id=0, $dbtablename= '', $feature2= '', $dbt_keyfield= 'fk_soc', $dbt_select= 'rowid')
Check user access to a resource.
static _forge_criteria_callback ($matches)
Function to forge a SQL criteria.
Detailed Description
Definition at line 30 of file api_contracts.class.php.
Member Function Documentation
_cleanObjectDatas ($object) protected
Clean sensible object datas.
Parameters
object $object Object to clean
Returns
array Array of cleaned object properties
Definition at line 643 of file api_contracts.class.php.
Referenced by activateLine(), get(), getLines(), putLine(), and unactivateLine().
_validate ($data) private
Validate fields before create or update object.
Parameters
array $data Array with data to verify
Returns
array
Exceptions
RestException
Definition at line 670 of file api_contracts.class.php.
Referenced by post().
activateLine ($id, $lineid, $datestart, $dateend = null, $comment = null)
Activate a service line of a given contract.
Parameters
int $id Id of contract to activate
int $lineid Id of line to activate
string $datestart { body} Date start { timestamp}
string $dateend { body} Date end { timestamp}
string $comment { body} Comment
PUT {id}/lines/{lineid}/activate
Returns
array|bool
Definition at line 366 of file api_contracts.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
close ($id, $notrigger = 0)
Close all services of a contract.
Parameters
int $id Contract ID
int $notrigger 1=Does not execute triggers, 0= execute triggers
POST {id}/close
Returns
array FIXME An error 403 is returned if the request has an empty body. Error message: "Forbidden: Content type `text/plain` is not supported." Workaround: send this in the body { "notrigger": 0 }
Definition at line 604 of file api_contracts.class.php.
References DolibarrApi\_checkAccessToResource().
delete ($id)
Delete contract.
Parameters
int $id Contract ID
Returns
array
Definition at line 516 of file api_contracts.class.php.
References DolibarrApi\_checkAccessToResource().
deleteLine ($id, $lineid)
Delete a line to given contract.
Parameters
int $id Id of contract to update
int $lineid Id of line to delete
DELETE {id}/lines/{lineid}
Returns
int
Exceptions
401
404
Definition at line 445 of file api_contracts.class.php.
References DolibarrApi\_checkAccessToResource().
get ($id)
Get properties of a contract object.
Return an array with contract informations
Parameters
int $id ID of contract
Returns
array|mixed data without useless information
Exceptions
RestException
Definition at line 68 of file api_contracts.class.php.
References DolibarrApi\_checkAccessToResource(), DolibarrApi\_checkFilters(), _cleanObjectDatas(), and dol_syslog().
getLines ($id)
Get lines of a contract.
Parameters
int $id Id of contract
GET {id}/lines
Returns
array
Definition at line 221 of file api_contracts.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
post ($request_data = null)
Create contract object.
Parameters
array $request_data Request data
Returns
int ID of contrat
Definition at line 187 of file api_contracts.class.php.
References _validate().
postLine ($id, $request_data = null)
Add a line to given contract.
Parameters
int $id Id of contrat to update
array $request_data Contractline data
POST {id}/lines
Returns
int|bool
Definition at line 253 of file api_contracts.class.php.
References DolibarrApi\_checkAccessToResource().
put ($id, $request_data = null)
Update contract general fields (won't touch lines of contract)
Parameters
int $id Id of contract to update
array $request_data Datas
Returns
int
Definition at line 480 of file api_contracts.class.php.
References DolibarrApi\_checkAccessToResource().
putLine ($id, $lineid, $request_data = null)
Update a line to given contract.
Parameters
int $id Id of contrat to update
int $lineid Id of line to update
array $request_data Contractline data
PUT {id}/lines/{lineid}
Returns
array|bool
Definition at line 306 of file api_contracts.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
unactivateLine ($id, $lineid, $datestart, $comment = null)
Unactivate a service line of a given contract.
Parameters
int $id Id of contract to activate
int $lineid Id of line to activate
string $datestart { body} Date start { timestamp}
string $comment { body} Comment
PUT {id}/lines/{lineid}/unactivate
Returns
array|bool
Definition at line 404 of file api_contracts.class.php.
References DolibarrApi\_checkAccessToResource(), and _cleanObjectDatas().
validate ($id, $notrigger = 0)
Validate a contract.
Parameters
int $id Contract ID
int $notrigger 1=Does not execute triggers, 0= execute triggers
POST {id}/validate
Returns
array FIXME An error 403 is returned if the request has an empty body. Error message: "Forbidden: Content type `text/plain` is not supported." Workaround: send this in the body { "notrigger": 0 }
Definition at line 558 of file api_contracts.class.php.
References DolibarrApi\_checkAccessToResource().
The documentation for this class was generated from the following file:
htdocs/contrat/class/api_contracts.class.php