Dolibarr: htdocs/core/lib/resource.lib.php File Reference
resource.lib.php File Reference
Module resource
This file is library for resource module.
Functions
resource_prepare_head ($object)
Prepare head for tabs.
resource_admin_prepare_head ()
Prepare head for admin tabs.
Detailed Description
This file is library for resource module.
Definition in file resource.lib.php.
Function Documentation
resource_admin_prepare_head ()
Prepare head for admin tabs.
Returns
array Array of head entries
Definition at line 105 of file resource.lib.php.
References complete_head_from_modules().
resource_prepare_head ($object)
Prepare head for tabs.
Parameters
Object $object Object
Returns
array Array of head entries
Definition at line 32 of file resource.lib.php.
References complete_head_from_modules(), dol_buildpath(), dol_dir_list(), and dol_sanitizeFileName().