Dolibarr: Events Class Reference
Events Class Reference
Events class.
Public Member Functions
__construct ($db)
Constructor.
create ($user)
Create in database.
update ($user=null, $notrigger=0)
Update database.
fetch ($id, $user=null)
Load object in memory from database.
delete ($user)
Delete object in database.
initAsSpecimen ()
Initialise an instance with random values.
Detailed Description
Events class.
Definition at line 29 of file events.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 137 of file events.class.php.
References db.
Member Function Documentation
create ($user)
Create in database.
Parameters
User $user User that create
Returns
int <0 if KO, >0 if OK
Definition at line 149 of file events.class.php.
References $resql, db, description, dol_syslog(), dol_trunc(), getUserRemoteIP(), and type.
delete ($user)
Delete object in database.
Parameters
User $user User that delete
Returns
int <0 if KO, >0 if OK
Definition at line 289 of file events.class.php.
References $resql, db, and dol_syslog().
fetch ($id, $user = null)
Load object in memory from database.
Parameters
int $id Id object
User $user User that load
Returns
int <0 if KO, >0 if OK
Definition at line 238 of file events.class.php.
References $resql, db, description, dol_syslog(), and type.
initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
void
Definition at line 313 of file events.class.php.
References description, and type.
update ($user = null, $notrigger = 0)
Update database.
Parameters
User $user User that modify
int $notrigger 0=no, 1=yes (no update trigger)
Returns
int <0 if KO, >0 if OK
Definition at line 203 of file events.class.php.
References $resql, db, description, dol_syslog(), and type.
The documentation for this class was generated from the following file:
htdocs/core/class/events.class.php