Dolibarr: Form Class Reference
Form Class Reference
Class to manage generation of HTML components Only common components must be here.
Public Member Functions
__construct ($db)
Constructor.
editfieldkey ($text, $htmlname, $preselected, $object, $perm, $typeofdata= 'string', $moreparam= '', $fieldrequired=0, $notabletag=0, $paramid= 'id')
Output key field for an editable field.
editfieldval ($text, $htmlname, $value, $object, $perm, $typeofdata= 'string', $editvalue= '', $extObject=null, $custommsg=null, $moreparam= '', $notabletag=0, $formatfunc= '', $paramid= 'id')
Output value of a field for an editable field.
textwithtooltip ($text, $htmltext, $tooltipon=1, $direction=0, $img= '', $extracss= '', $notabs=2, $incbefore= '', $noencodehtmltext=0, $tooltiptrigger= '', $forcenowrap=0)
Show a text and picto with tooltip on text or picto.
textwithpicto ($text, $htmltext, $direction=1, $type= 'help', $extracss= '', $noencodehtmltext=0, $notabs=2, $tooltiptrigger= '', $forcenowrap=0)
Show a text with a picto and a tooltip on picto.
selectMassAction ($selected, $arrayofaction, $alwaysvisible=0)
Generate select HTML to choose massaction.
select_country ($selected= '', $htmlname= 'country_id', $htmloption= '', $maxlength=0, $morecss= 'minwidth300', $usecodeaskey= '', $showempty=1, $disablefavorites=0, $addspecialentries=0)
Return combo list of activated countries, into language of user.
select_incoterms ($selected= '', $location_incoterms= '', $page= '', $htmlname= 'incoterm_id', $htmloption= '', $forcecombo=1, $events=array())
Return select list of incoterms.
select_type_of_lines ($selected= '', $htmlname= 'type', $showempty=0, $hidetext=0, $forceall=0)
Return list of types of lines (product or service) Example: 0=product, 1=service, 9=other (for external module)
load_cache_types_fees ()
Load into cache cache_types_fees, array of types of fees.
select_type_fees ($selected= '', $htmlname= 'type', $showempty=0)
Return list of types of notes.
select_thirdparty ($selected= '', $htmlname= 'socid', $filter= '', $limit=20, $ajaxoptions=array(), $forcecombo=0)
Return HTML code to select a company.
select_company ($selected= '', $htmlname= 'socid', $filter= '', $showempty= '', $showtype=0, $forcecombo=0, $events=array(), $limit=0, $morecss= 'minwidth100', $moreparam= '', $selected_input_value= '', $hidelabel=1, $ajaxoptions=array(), $multiple=false)
Output html form to select a third party.
select_thirdparty_list ($selected= '', $htmlname= 'socid', $filter= '', $showempty= '', $showtype=0, $forcecombo=0, $events=array(), $filterkey= '', $outputmode=0, $limit=0, $morecss= 'minwidth100', $moreparam= '', $multiple=false)
Output html form to select a third party.
select_remises ($selected, $htmlname, $filter, $socid, $maxvalue=0)
Return HTML combo list of absolute discounts.
select_contacts ($socid, $selected= '', $htmlname= 'contactid', $showempty=0, $exclude= '', $limitto= '', $showfunction=0, $moreclass= '', $showsoc=0, $forcecombo=0, $events=array(), $options_only=false, $moreparam= '', $htmlid= '')
Return list of all contacts (for a third party or all)
selectcontacts ($socid, $selected= '', $htmlname= 'contactid', $showempty=0, $exclude= '', $limitto= '', $showfunction=0, $moreclass= '', $options_only=false, $showsoc=0, $forcecombo=0, $events=array(), $moreparam= '', $htmlid= '', $multiple=false)
Return HTML code of the SELECT of list of all contacts (for a third party or all).
select_users ($selected= '', $htmlname= 'userid', $show_empty=0, $exclude=null, $disabled=0, $include= '', $enableonly= '', $force_entity= '0')
Return select list of users.
select_dolusers ($selected= '', $htmlname= 'userid', $show_empty=0, $exclude=null, $disabled=0, $include= '', $enableonly= '', $force_entity= '0', $maxlength=0, $showstatus=0, $morefilter= '', $show_every=0, $enableonlytext= '', $morecss= '', $noactive=0, $outputmode=0, $multiple=false)
Return select list of users.
select_dolusers_forevent ($action= '', $htmlname= 'userid', $show_empty=0, $exclude=null, $disabled=0, $include= '', $enableonly= '', $force_entity= '0', $maxlength=0, $showstatus=0, $morefilter= '', $showproperties=0, $listofuserid=array(), $listofcontactid=array(), $listofotherid=array())
Return select list of users.
select_produits ($selected= '', $htmlname= 'productid', $filtertype= '', $limit=20, $price_level=0, $status=1, $finished=2, $selected_input_value= '', $hidelabel=0, $ajaxoptions=array(), $socid=0, $showempty= '1', $forcecombo=0, $morecss= '', $hidepriceinlabel=0, $warehouseStatus= '', $selected_combinations=array())
Return list of products for customer in Ajax if Ajax activated or go to select_produits_list.
select_produits_list ($selected= '', $htmlname= 'productid', $filtertype= '', $limit=20, $price_level=0, $filterkey= '', $status=1, $finished=2, $outputmode=0, $socid=0, $showempty= '1', $forcecombo=0, $morecss= '', $hidepriceinlabel=0, $warehouseStatus= '')
Return list of products for a customer.
select_produits_fournisseurs ($socid, $selected= '', $htmlname= 'productid', $filtertype= '', $filtre= '', $ajaxoptions=array(), $hidelabel=0, $alsoproductwithnosupplierprice=0, $morecss= '')
Return list of products for customer (in Ajax if Ajax activated or go to select_produits_fournisseurs_list)
select_produits_fournisseurs_list ($socid, $selected= '', $htmlname= 'productid', $filtertype= '', $filtre= '', $filterkey= '', $statut=-1, $outputmode=0, $limit=100, $alsoproductwithnosupplierprice=0, $morecss= '')
Return list of suppliers products.
select_product_fourn_price ($productid, $htmlname= 'productfournpriceid', $selected_supplier= '')
Return list of suppliers prices for a product.
select_address ($selected, $socid, $htmlname= 'address_id', $showempty=0)
Return list of delivery address.
load_cache_conditions_paiements ()
Load into cache list of payment terms.
load_cache_availability ()
Charge dans cache la liste des délais de livraison possibles.
selectAvailabilityDelay ($selected= '', $htmlname= 'availid', $filtertype= '', $addempty=0)
Retourne la liste des types de delais de livraison possibles.
loadCacheInputReason ()
Load into cache cache_demand_reason, array of input reasons.
selectInputReason ($selected= '', $htmlname= 'demandreasonid', $exclude= '', $addempty=0)
Return list of input reason (events that triggered an object creation, like after sending an emailing, making an advert, ...) List found into table c_input_reason loaded by loadCacheInputReason.
load_cache_types_paiements ()
Charge dans cache la liste des types de paiements possibles.
select_conditions_paiements ($selected=0, $htmlname= 'condid', $filtertype=-1, $addempty=0, $noinfoadmin=0, $morecss= '')
Return list of payment modes.
select_types_paiements ($selected= '', $htmlname= 'paiementtype', $filtertype= '', $format=0, $empty=1, $noadmininfo=0, $maxlength=0, $active=1, $morecss= '')
Return list of payment methods.
selectPriceBaseType ($selected= '', $htmlname= 'price_base_type')
Selection HT or TTC.
selectShippingMethod ($selected= '', $htmlname= 'shipping_method_id', $filtre= '', $useempty=0, $moreattrib= '')
Return a HTML select list of shipping mode.
formSelectShippingMethod ($page, $selected= '', $htmlname= 'shipping_method_id', $addempty=0)
Display form to select shipping mode.
selectSituationInvoices ($selected= '', $socid=0)
Creates HTML last in cycle situation invoices selector.
selectUnits ($selected= '', $htmlname= 'units', $showempty=0)
Creates HTML units selector (code => label)
select_comptes ($selected= '', $htmlname= 'accountid', $statut=0, $filtre= '', $useempty=0, $moreattrib= '', $showcurrency=0, $morecss= '')
Return a HTML select list of bank accounts.
selectEstablishments ($selected= '', $htmlname= 'entity', $statut=0, $filtre= '', $useempty=0, $moreattrib= '')
Return a HTML select list of establishment.
formSelectAccount ($page, $selected= '', $htmlname= 'fk_account', $addempty=0)
Display form to select bank account.
select_all_categories ($type, $selected= '', $htmlname="parent", $maxlength=64, $markafterid=0, $outputmode=0, $include=0)
Return list of categories having choosed type.
form_confirm ($page, $title, $question, $action, $formquestion= '', $selectedchoice="", $useajax=0, $height=170, $width=500)
Show a confirmation HTML form or AJAX popup.
formconfirm ($page, $title, $question, $action, $formquestion= '', $selectedchoice= '', $useajax=0, $height=210, $width=500, $disableformtag=0)
Show a confirmation HTML form or AJAX popup.
form_project ($page, $socid, $selected= '', $htmlname= 'projectid', $discard_closed=0, $maxlength=20, $forcefocus=0, $nooutput=0)
Show a form to select a project.
form_conditions_reglement ($page, $selected= '', $htmlname= 'cond_reglement_id', $addempty=0)
Show a form to select payment conditions.
form_availability ($page, $selected= '', $htmlname= 'availability', $addempty=0)
Show a form to select a delivery delay.
formInputReason ($page, $selected= '', $htmlname= 'demandreason', $addempty=0)
Output HTML form to select list of input reason (events that triggered an object creation, like after sending an emailing, making an advert, ...) List found into table c_input_reason loaded by loadCacheInputReason.
form_date ($page, $selected, $htmlname, $displayhour=0, $displaymin=0, $nooutput=0)
Show a form + html select a date.
form_users ($page, $selected= '', $htmlname= 'userid', $exclude= '', $include= '')
Show a select form to choose a user.
form_modes_reglement ($page, $selected= '', $htmlname= 'mode_reglement_id', $filtertype= '', $active=1, $addempty=0)
Show form with payment mode.
form_multicurrency_code ($page, $selected= '', $htmlname= 'multicurrency_code')
Show form with multicurrency code.
form_multicurrency_rate ($page, $rate= '', $htmlname= 'multicurrency_tx', $currency= '')
Show form with multicurrency rate.
form_remise_dispo ($page, $selected, $htmlname, $socid, $amount, $filter= '', $maxvalue=0, $more= '', $hidelist=0, $discount_type=0)
Show a select box with available absolute discounts.
form_contacts ($page, $societe, $selected= '', $htmlname= 'contactid')
Show forms to select a contact.
form_thirdparty ($page, $selected= '', $htmlname= 'socid', $filter= '', $showempty=0, $showtype=0, $forcecombo=0, $events=array(), $nooutput=0)
Output html select to select thirdparty.
select_currency ($selected= '', $htmlname= 'currency_id')
Retourne la liste des devises, dans la langue de l'utilisateur.
selectCurrency ($selected= '', $htmlname= 'currency_id', $mode=0)
Retourne la liste des devises, dans la langue de l'utilisateur.
selectMultiCurrency ($selected= '', $htmlname= 'multicurrency_code', $useempty=0)
Return array of currencies in user language.
load_cache_vatrates ($country_code)
Load into the cache vat rates of a country.
load_tva ($htmlname= 'tauxtva', $selectedrate= '', $societe_vendeuse= '', $societe_acheteuse= '', $idprod=0, $info_bits=0, $type= '', $options_only=false, $mode=0)
Output an HTML select vat rate.
select_date ($set_time= '', $prefix= 're', $h=0, $m=0, $empty=0, $form_name="", $d=1, $addnowlink=0, $nooutput=0, $disabled=0, $fullday= '', $addplusone= '', $adddateof= '')
Show a HTML widget to input a date or combo list for day, month, years and optionaly hours and minutes.
selectDate ($set_time= '', $prefix= 're', $h=0, $m=0, $empty=0, $form_name="", $d=1, $addnowlink=0, $disabled=0, $fullday= '', $addplusone= '', $adddateof= '', $openinghours= '', $stepminutes=1)
Show a HTML widget to input a date or combo list for day, month, years and optionaly hours and minutes.
select_duration ($prefix, $iSecond= '', $disabled=0, $typehour= 'select', $minunderhours=0, $nooutput=0)
Function to show a form to select a duration on a page.
selectForForms ($objectdesc, $htmlname, $preselectedvalue, $showempty= '', $searchkey= '', $placeholder= '', $morecss= '', $moreparams= '', $forcecombo=0)
Generic method to select a component from a combo list.
selectForFormsList ($objecttmp, $htmlname, $preselectedvalue, $showempty= '', $searchkey= '', $placeholder= '', $morecss= '', $moreparams= '', $forcecombo=0, $outputmode=0)
Output html form to select an object.
showCategories ($id, $type, $rendermode=0)
Render list of categories linked to object with id $id and type $type.
showLinkedObjectBlock ($object, $morehtmlright= '', $compatibleImportElementsList=false)
Show linked object block.
showLinkToObjectBlock ($object, $restrictlinksto=array(), $excludelinksto=array())
Show block with links to link to other objects.
selectyesno ($htmlname, $value= '', $option=0, $disabled=false, $useempty=0)
Return an html string with a select combo box to choose yes or no.
select_export_model ($selected= '', $htmlname= 'exportmodelid', $type= '', $useempty=0)
Return list of export templates.
showrefnav ($object, $paramid, $morehtml= '', $shownav=1, $fieldid= 'rowid', $fieldref= 'ref', $morehtmlref= '', $moreparam= '', $nodbprefix=0, $morehtmlleft= '', $morehtmlstatus= '', $morehtmlright= '')
Return a HTML area with the reference of object and a navigation bar for a business object Note: To complete search with a particular filter on select, you can set $object->next_prev_filter set to define SQL criterias.
showbarcode (&$object, $width=100)
Return HTML code to output a barcode.
select_dolgroups ($selected= '', $htmlname= 'groupid', $show_empty=0, $exclude= '', $disabled=0, $include= '', $enableonly= '', $force_entity= '0', $multiple=false)
Return select list of groups.
showFilterButtons ()
Return HTML to show the search and clear seach button.
showCheckAddButtons ($cssclass= 'checkforaction', $calljsfunction=0)
Return HTML to show the search and clear seach button.
showFilterAndCheckAddButtons ($addcheckuncheckall=0, $cssclass= 'checkforaction', $calljsfunction=0)
Return HTML to show the search and clear seach button.
selectExpenseCategories ($selected= '', $htmlname= 'fk_c_exp_tax_cat', $useempty=0, $excludeid=array(), $target= '', $default_selected=0, $params=array())
Return HTML to show the select of expense categories.
selectExpenseRanges ($selected= '', $htmlname= 'fk_range', $useempty=0)
Return HTML to show the select ranges of expense range.
selectExpense ($selected= '', $htmlname= 'fk_c_type_fees', $useempty=0, $allchoice=1, $useid=0)
Return HTML to show a select of expense.
Static Public Member Functions
static selectarray ($htmlname, $array, $id= '', $show_empty=0, $key_in_label=0, $value_as_key=0, $moreparam= '', $translate=0, $maxlen=0, $disabled=0, $sort= '', $morecss= '', $addjscombo=0, $moreparamonempty= '', $disablebademail=0, $nohtmlescape=0)
Return a HTML select string, built from an array of key+value.
static selectArrayAjax ($htmlname, $url, $id= '', $moreparam= '', $moreparamtourl= '', $disabled=0, $minimumInputLength=1, $morecss= '', $callurlonselect=0, $placeholder= '', $acceptdelayedhtml=0)
Return a HTML select string, built from an array of key+value, but content returned into select come from an Ajax call of an URL.
static selectArrayFilter ($htmlname, $array, $id= '', $moreparam= '', $disableFiltering=0, $disabled=0, $minimumInputLength=1, $morecss= '', $callurlonselect=0, $placeholder= '', $acceptdelayedhtml=0)
Return a HTML select string, built from an array of key+value, but content returned into select is defined into $array parameter.
static multiselectarray ($htmlname, $array, $selected=array(), $key_in_label=0, $value_as_key=0, $morecss= '', $translate=0, $width=0, $moreattrib= '', $elemtype= '', $placeholder= '', $addjscombo=-1)
Show a multiselect form from an array.
static multiSelectArrayWithCheckbox ($htmlname, &$array, $varpage)
Show a multiselect dropbox from an array.
static showphoto ($modulepart, $object, $width=100, $height=0, $caneditfield=0, $cssclass= 'photowithmargin', $imagesize= '', $addlinktofullsize=1, $cache=0, $forcecapture= '')
Return HTML code to output a photo.
Protected Member Functions
editInPlace ($object, $value, $htmlname, $condition, $inputType= 'textarea', $editvalue=null, $extObject=null, $custommsg=null)
Output edit in place form.
constructProductListOption (&$objp, &$opt, &$optJson, $price_level, $selected, $hidepriceinlabel=0, $filterkey= '')
constructProductListOption.
Detailed Description
Class to manage generation of HTML components Only common components must be here.
TODO Merge all function load_cache_* and loadCache* (except load_cache_vatrates) into one generic function loadCacheTable
Definition at line 52 of file html.form.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 85 of file html.form.class.php.
References db.
Member Function Documentation
constructProductListOption (& $objp, & $opt, & $optJson, $price_level, $selected, $hidepriceinlabel = 0, $filterkey = '') protected
constructProductListOption.
This define value for &$opt and &$optJson.
Parameters
resource $objp Resultset of fetch
string $opt Option (var used for returned value in string option format)
string $optJson Option (var used for returned value in json format)
int $price_level Price level
string $selected Preselected value
int $hidepriceinlabel Hide price in label
string $filterkey Filter key to highlight
Returns
void
Definition at line 2369 of file html.form.class.php.
References db, dol_print_error(), dol_strlen(), dol_syslog(), if, price(), price2num(), Product\TYPE_PRODUCT, Product\TYPE_SERVICE, and vatrate().
Referenced by select_produits_list().
editfieldkey ($text, $htmlname, $preselected, $object, $perm, $typeofdata = 'string', $moreparam = '', $fieldrequired = 0, $notabletag = 0, $paramid = 'id')
Output key field for an editable field.
Parameters
string $text Text of label or key to translate
string $htmlname Name of select field ('edit' prefix will be added)
string $preselected Value to show/edit (not used in this function)
object $object Object
boolean $perm Permission to allow button to edit parameter. Set it to 0 to have a not edited field.
string $typeofdata Type of data ('string' by default, 'email', 'amount:99', 'numeric:99', 'text' or 'textarea:rows:cols', 'datepicker' ('day' do not work, don't know why), 'ckeditor:dolibarr_zzz:width:height:savemethod:1:rows:cols', 'select;xxx[:class]'...)
string $moreparam More param to add on a href URL.
int $fieldrequired 1 if we want to show field as mandatory using the "fieldrequired" CSS.
int $notabletag 1=Do not output table tags but output a ':', 2=Do not output table tags and no ':', 3=Do not output table tags but output a ' '
string $paramid Key of parameter for id ('id', 'socid')
Returns
string HTML edit field
Definition at line 105 of file html.form.class.php.
References GETPOST(), if, and img_edit().
editfieldval ($text, $htmlname, $value, $object, $perm, $typeofdata = 'string', $editvalue = '', $extObject = null, $custommsg = null, $moreparam = '', $notabletag = 0, $formatfunc = '', $paramid = 'id')
Output value of a field for an editable field.
Parameters
string $text Text of label (not used in this function)
string $htmlname Name of select field
string $value Value to show/edit
object $object Object
boolean $perm Permission to allow button to edit parameter
string $typeofdata Type of data ('string' by default, 'email', 'amount:99', 'numeric:99', 'text' or 'textarea:rows:cols', 'datepicker' ('day' do not work, don't know why), 'dayhour' or 'datepickerhour', 'ckeditor:dolibarr_zzz:width:height:savemethod:toolbarstartexpanded:rows:cols', 'select;xkey:xval,ykey:yval,...')
string $editvalue When in edit mode, use this value as $value instead of value (for example, you can provide here a formated price instead of value). Use '' to use same than $value
object $extObject External object
mixed $custommsg String or Array of custom messages : eg array('success' => 'MyMessage', 'error' => 'MyMessage')
string $moreparam More param to add on the form action href URL
int $notabletag Do no output table tags
string $formatfunc Call a specific function to output field
string $paramid Key of parameter for id ('id', 'socid')
Returns
string HTML edit field
Definition at line 167 of file html.form.class.php.
References dol_htmlentitiesbr(), dol_print_date(), dol_print_email(), dol_string_neverthesehtmltags(), editInPlace(), GETPOST(), if, price(), price2num(), selectarray(), and selectDate().
editInPlace ($object, $value, $htmlname, $condition, $inputType = 'textarea', $editvalue = null, $extObject = null, $custommsg = null) protected
Output edit in place form.
Parameters
object $object Object
string $value Value to show/edit
string $htmlname DIV ID (field name)
int $condition Condition to edit
string $inputType Type of input ('string', 'numeric', 'datepicker' ('day' do not work, don't know why), 'textarea:rows:cols', 'ckeditor:dolibarr_zzz:width:height:?:1:rows:cols', 'select:loadmethod:savemethod:buttononly')
string $editvalue When in edit mode, use this value as $value instead of value
object $extObject External object
mixed $custommsg String or Array of custom messages : eg array('success' => 'MyMessage', 'error' => 'MyMessage')
Returns
string HTML edit in place
Definition at line 310 of file html.form.class.php.
References dol_nl2br(), dol_print_date(), and price().
Referenced by editfieldval().
form_availability ($page, $selected = '', $htmlname = 'availability', $addempty = 0)
Show a form to select a delivery delay.
Parameters
int $page Page
string $selected Id condition pre-selectionne
string $htmlname Name of select html field
int $addempty Ajoute entree vide
Returns
void
Definition at line 4352 of file html.form.class.php.
References load_cache_availability(), print, and selectAvailabilityDelay().
form_conditions_reglement ($page, $selected = '', $htmlname = 'cond_reglement_id', $addempty = 0)
Show a form to select payment conditions.
Parameters
int $page Page
string $selected Id condition pre-selectionne
string $htmlname Name of select html field
int $addempty Add empty entry
Returns
void
Definition at line 4317 of file html.form.class.php.
References load_cache_conditions_paiements(), print, and select_conditions_paiements().
form_confirm ($page, $title, $question, $action, $formquestion = '', $selectedchoice = "", $useajax = 0, $height = 170, $width = 500)
Show a confirmation HTML form or AJAX popup.
Parameters
string $page Url of page to call if confirmation is OK
string $title Title
string $question Question
string $action Action
array $formquestion An array with forms complementary inputs
string $selectedchoice "" or "no" or "yes"
int $useajax 0=No, 1=Yes, 2=Yes but submit page with &confirm=no if choice is No, 'xxx'=preoutput confirm box with div id=dialog-confirm-xxx
int $height Force height of box
int $width Force width of box
Returns
void
Deprecated:
See also
formconfirm()
Definition at line 3950 of file html.form.class.php.
References dol_syslog(), formconfirm(), and print.
form_contacts ($page, $societe, $selected = '', $htmlname = 'contactid')
Show forms to select a contact.
Parameters
string $page Page
Societe $societe Filter on third party
int $selected Id contact pre-selectionne
string $htmlname Name of HTML select. If 'none', we just show contact link.
Returns
void
Definition at line 4717 of file html.form.class.php.
References db, print, and select_contacts().
form_date ($page, $selected, $htmlname, $displayhour = 0, $displaymin = 0, $nooutput = 0)
Show a form + html select a date.
Parameters
string $page Page
string $selected Date preselected
string $htmlname Html name of date input fields or 'none'
int $displayhour Display hour selector
int $displaymin Display minutes selector
int $nooutput 1=No print output, return string
Returns
string
See also
selectDate()
Definition at line 4431 of file html.form.class.php.
References dol_print_date(), print, and selectDate().
form_modes_reglement ($page, $selected = '', $htmlname = 'mode_reglement_id', $filtertype = '', $active = 1, $addempty = 0)
Show form with payment mode.
Parameters
string $page Page
int $selected Id mode pre-selectionne
string $htmlname Name of select html field
string $filtertype To filter on field type in llx_c_paiement (array('code'=>xx,'label'=>zz))
int $active Active or not, -1 = all
int $addempty 1=Add empty entry
Returns
void
Definition at line 4513 of file html.form.class.php.
References load_cache_types_paiements(), print, and select_types_paiements().
form_multicurrency_code ($page, $selected = '', $htmlname = 'multicurrency_code')
Show form with multicurrency code.
Parameters
string $page Page
string $selected code pre-selectionne
string $htmlname Name of select html field
Returns
void
Definition at line 4547 of file html.form.class.php.
References currency_name(), dol_include_once(), print, and selectMultiCurrency().
form_multicurrency_rate ($page, $rate = '', $htmlname = 'multicurrency_tx', $currency = '')
Show form with multicurrency rate.
Parameters
string $page Page
double $rate Current rate
string $htmlname Name of select html field
string $currency Currency code to explain the rate
Returns
void
Definition at line 4577 of file html.form.class.php.
References price(), and print.
form_project ($page, $socid, $selected = '', $htmlname = 'projectid', $discard_closed = 0, $maxlength = 20, $forcefocus = 0, $nooutput = 0)
Show a form to select a project.
Parameters
int $page Page
int $socid Id third party (-1=all, 0=only projects not linked to a third party, id=projects not linked or linked to third party id)
int $selected Id pre-selected project
string $htmlname Name of select field
int $discard_closed Discard closed projects (0=Keep,1=hide completely except $selected,2=Disable)
int $maxlength Max length
int $forcefocus Force focus on field (works with javascript only)
int $nooutput No print is done. String is returned.
Returns
string Return html content
Definition at line 4261 of file html.form.class.php.
References db, and print.
form_remise_dispo ($page, $selected, $htmlname, $socid, $amount, $filter = '', $maxvalue = 0, $more = '', $hidelist = 0, $discount_type = 0)
Show a select box with available absolute discounts.
Parameters
string $page Page URL where form is shown
int $selected Value pre-selected
string $htmlname Name of SELECT component. If 'none', not changeable. Example 'remise_id'.
int $socid Third party id
float $amount Total amount available
string $filter SQL filter on discounts
int $maxvalue Max value for lines that can be selected
string $more More string to add
int $hidelist 1=Hide list
int $discount_type 0 => customer discount, 1 => supplier discount
Returns
void
Definition at line 4626 of file html.form.class.php.
References price(), print, and select_remises().
form_thirdparty ($page, $selected = '', $htmlname = 'socid', $filter = '', $showempty = 0, $showtype = 0, $forcecombo = 0, $events = array(), $nooutput = 0)
Output html select to select thirdparty.
Parameters
string $page Page
string $selected Id preselected
string $htmlname Name of HTML select
string $filter optional filters criteras
int $showempty Add an empty field
int $showtype Show third party type in combolist (customer, prospect or supplier)
int $forcecombo Force to use combo box
array $events Event options. Example: array(array('method'=>'getContacts', 'url'=>dol_buildpath('/core/ajax/contacts.php',1), 'htmlname'=>'contactid', 'params'=>array('add-customer-contact'=>'disabled')))
int $nooutput No print output. Return it only.
Returns
void
Definition at line 4768 of file html.form.class.php.
References db, print, and select_company().
form_users ($page, $selected = '', $htmlname = 'userid', $exclude = '', $include = '')
Show a select form to choose a user.
Parameters
string $page Page
string $selected Id of user preselected
string $htmlname Name of input html field. If 'none', we just output the user link.
array $exclude List of users id to exclude
array $include List of users id to include
Returns
void
Definition at line 4472 of file html.form.class.php.
References db, print, and select_dolusers().
formconfirm ($page, $title, $question, $action, $formquestion = '', $selectedchoice = '', $useajax = 0, $height = 210, $width = 500, $disableformtag = 0)
Show a confirmation HTML form or AJAX popup.
Easiest way to use this is with useajax=1. If you use useajax='xxx', you must also add jquery code to trigger opening of box (with correct parameters) just after calling this method. For example: print '<script type="text/javascript">'."\n"; print 'jQuery(document).ready(function() {'."\n"; print 'jQuery(".xxxlink").click(function(e) { jQuery("#aparamid").val(jQuery(this).attr("rel")); jQuery("#dialog-confirm-xxx").dialog("open"); return false; });'."\n"; print '});'."\n"; print '</script>'."\n";
Parameters
string $page Url of page to call if confirmation is OK. Can contains parameters (param 'action' and 'confirm' will be reformated)
string $title Title
string $question Question
string $action Action
array $formquestion An array with complementary inputs to add into forms: array(array('label'=> ,'type'=> ,)) type can be 'hidden', 'text', 'password', 'checkbox', 'radio', 'date', 'morecss', ...
string $selectedchoice '' or 'no', or 'yes' or '1' or '0'
int $useajax 0=No, 1=Yes, 2=Yes but submit page with &confirm=no if choice is No, 'xxx'=Yes and preoutput confirm box with div id=dialog-confirm-xxx
int $height Force height of box
int $width Force width of box ('999' or '90'). Ignored and forced to 90% on smartphones.
int $disableformtag 1=Disable form tag. Can be used if we are already inside a <form> section.
Returns
string HTML ajax code if a confirm ajax popup is required, Pure HTML code if it's an html form
Definition at line 3981 of file html.form.class.php.
References dol_escape_htmltag(), dol_escape_js(), if, selectDate(), and selectyesno().
Referenced by form_confirm().
formInputReason ($page, $selected = '', $htmlname = 'demandreason', $addempty = 0)
Output HTML form to select list of input reason (events that triggered an object creation, like after sending an emailing, making an advert, ...) List found into table c_input_reason loaded by loadCacheInputReason.
Parameters
string $page Page
string $selected Id condition pre-selectionne
string $htmlname Name of select html field
int $addempty Add empty entry
Returns
void
Definition at line 4387 of file html.form.class.php.
References loadCacheInputReason(), print, and selectInputReason().
formSelectAccount ($page, $selected = '', $htmlname = 'fk_account', $addempty = 0)
Display form to select bank account.
Parameters
string $page Page
int $selected Id of bank account
string $htmlname Name of select html field
int $addempty 1=Add an empty value in list, 2=Add an empty value in list only if there is more than 2 entries.
Returns
void
Definition at line 3816 of file html.form.class.php.
References db, print, and select_comptes().
formSelectShippingMethod ($page, $selected = '', $htmlname = 'shipping_method_id', $addempty = 0)
Display form to select shipping mode.
Parameters
string $page Page
int $selected Id of shipping mode
string $htmlname Name of select html field
int $addempty 1=Add an empty value in list, 2=Add an empty value in list only if there is more than 2 entries.
Returns
void
Definition at line 3537 of file html.form.class.php.
References print, and selectShippingMethod().
load_cache_availability ()
Charge dans cache la liste des délais de livraison possibles.
Returns
int Nb of lines loaded, <0 if KO
Definition at line 3111 of file html.form.class.php.
References $resql, db, dol_print_error(), dol_sort_array(), and dol_syslog().
Referenced by form_availability(), and selectAvailabilityDelay().
load_cache_conditions_paiements ()
Load into cache list of payment terms.
Returns
int Nb of lines loaded, <0 if KO
Definition at line 3062 of file html.form.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
Referenced by form_conditions_reglement(), and select_conditions_paiements().
load_cache_types_fees ()
Load into cache cache_types_fees, array of types of fees.
Returns
int Nb of lines loaded, <0 if KO
Definition at line 942 of file html.form.class.php.
References $resql, db, dol_print_error(), and dol_syslog().
Referenced by select_type_fees().
load_cache_types_paiements ()
Charge dans cache la liste des types de paiements possibles.
Returns
int Nb of lines loaded, <0 if KO
Definition at line 3283 of file html.form.class.php.
References $resql, db, dol_print_error(), dol_sort_array(), and dol_syslog().
Referenced by form_modes_reglement(), and select_types_paiements().
load_cache_vatrates ($country_code)
Load into the cache vat rates of a country.
Parameters
string $country_code Country code with quotes ("'CA'", or "'CA,IN,...'")
Returns
int Nb of loaded lines, 0 if already loaded, <0 if KO
Definition at line 4930 of file html.form.class.php.
References $resql, db, dol_syslog(), and if.
Referenced by load_tva().
load_tva ($htmlname = 'tauxtva', $selectedrate = '', $societe_vendeuse = '', $societe_acheteuse = '', $idprod = 0, $info_bits = 0, $type = '', $options_only = false, $mode = 0)
Output an HTML select vat rate.
The name of this function should be selectVat. We keep bad name for compatibility purpose.
Parameters
string $htmlname Name of HTML select field
float | string $selectedrate Force preselected vat rate. Can be '8.5' or '8.5 (NOO)' for example. Use '' for no forcing.
Societe $societe_vendeuse Thirdparty seller
Societe $societe_acheteuse Thirdparty buyer
int $idprod Id product. O if unknown of NA.
int $info_bits Miscellaneous information on line (1 for NPR)
int | string $type ''=Unknown, 0=Product, 1=Service (Used if idprod not defined) Si vendeur non assujeti a TVA, TVA par defaut=0. Fin de regle. Si le (pays vendeur = pays acheteur) alors la TVA par defaut=TVA du produit vendu. Fin de regle. Si (vendeur et acheteur dans Communaute europeenne) et bien vendu = moyen de transports neuf (auto, bateau, avion), TVA par defaut=0 (La TVA doit etre paye par l'acheteur au centre d'impots de son pays et non au vendeur). Fin de regle. Si vendeur et acheteur dans Communauté européenne et acheteur= particulier alors TVA par défaut=TVA du produit vendu. Fin de règle. Si vendeur et acheteur dans Communauté européenne et acheteur= entreprise alors TVA par défaut=0. Fin de règle. Sinon la TVA proposee par defaut=0. Fin de regle.
bool $options_only Return HTML options lines only (for ajax treatment)
int $mode 0=Use vat rate as key in combo list, 1=Add VAT code after vat rate into key, -1=Use id of vat line as key
Returns
string
Definition at line 5012 of file html.form.class.php.
References db, dol_strlen(), get_default_npr(), get_default_tva(), isInEEC(), load_cache_vatrates(), Product\TYPE_SERVICE, and vatrate().
loadCacheInputReason ()
Load into cache cache_demand_reason, array of input reasons.
Returns
int Nb of lines loaded, <0 if KO
Definition at line 3195 of file html.form.class.php.
References $resql, db, dol_print_error(), and dol_sort_array().
Referenced by formInputReason(), and selectInputReason().
static multiselectarray ($htmlname, $array, $selected = array(), $key_in_label = 0, $value_as_key = 0, $morecss = '', $translate = 0, $width = 0, $moreattrib = '', $elemtype = '', $placeholder = '', $addjscombo = -1) static
Show a multiselect form from an array.
Parameters
string $htmlname Name of select
array $array Array with key+value
array $selected Array with key+value preselected
int $key_in_label 1 pour afficher la key dans la valeur "[key] value"
int $value_as_key 1 to use value as key
string $morecss Add more css style
int $translate Translate and encode value
int $width Force width of select box. May be used only when using jquery couch. Example: 250, 95%
string $moreattrib Add more options on select component. Example: 'disabled'
string $elemtype Type of element we show ('category', ...)
string $placeholder String to use as placeholder
int $addjscombo Add js combo
Returns
string HTML multiselect string
See also
selectarray(), selectArrayAjax(), selectArrayFilter()
Definition at line 6254 of file html.form.class.php.
References name.
Referenced by showCategories().
static multiSelectArrayWithCheckbox ($htmlname, & $array, $varpage) static
Show a multiselect dropbox from an array.
Parameters
string $htmlname Name of HTML field
array $array Array with array of fields we could show. This array may be modified according to setup of user.
string $varpage Id of context for page. Can be set by caller with $varpage=(empty($contextpage)?$_SERVER["PHP_SELF"]:$contextpage);
Returns
string HTML multiselect string
See also
selectarray()
Definition at line 6364 of file html.form.class.php.
References dol_escape_htmltag(), and img_picto().
select_address ($selected, $socid, $htmlname = 'address_id', $showempty = 0)
Return list of delivery address.
Parameters
string $selected Id contact pre-selectionn
int $socid Id of company
string $htmlname Name of HTML field
int $showempty Add an empty field
Returns
integer|null
Definition at line 3012 of file html.form.class.php.
References $resql, db, dol_print_error(), dol_syslog(), and print.
select_all_categories ($type, $selected = '', $htmlname = "parent", $maxlength = 64, $markafterid = 0, $outputmode = 0, $include = 0)
Return list of categories having choosed type.
Parameters
string | int $type Type of category ('customer', 'supplier', 'contact', 'product', 'member'). Old mode (0, 1, 2, ...) is deprecated.
string $selected Id of category preselected or 'auto' (autoselect category if there is only one element)
string $htmlname HTML field name
int $maxlength Maximum length for labels
int | string | array $markafterid Keep only or removed all categories including the leaf $markafterid in category tree (exclude) or Keep only of category is inside the leaf starting with this id. $markafterid can be an :
int (id of category)
string (categories ids seprated by comma)
array (list of categories ids)
int $outputmode 0=HTML select string, 1=Array
int $include [=0] Removed or 1=Keep only
Returns
string
See also
select_categories()
Definition at line 3859 of file html.form.class.php.
References db, dol_print_error(), dol_syslog(), and dol_trunc().
Referenced by showCategories().
select_company ($selected = '', $htmlname = 'socid', $filter = '', $showempty = '', $showtype = 0, $forcecombo = 0, $events = array(), $limit = 0, $morecss = 'minwidth100', $moreparam = '', $selected_input_value = '', $hidelabel = 1, $ajaxoptions = array(), $multiple = false)
Output html form to select a third party.
Parameters
string $selected Preselected type
string $htmlname Name of field in form
string $filter Optional filters criteras. WARNING: To avoid SQL injection, only few chars [.a-z0-9 =<>] are allowed here (example: 's.rowid <> x', 's.client IN (1,3)')
string $showempty Add an empty field (Can be '1' or text key to use on empty line like 'SelectThirdParty')
int $showtype Show third party type in combolist (customer, prospect or supplier)
int $forcecombo Force to load all values and output a standard combobox (with no beautification)
array $events Ajax event options to run on change. Example: array(array('method'=>'getContacts', 'url'=>dol_buildpath('/core/ajax/contacts.php',1), 'htmlname'=>'contactid', 'params'=>array('add-customer-contact'=>'disabled')))
int $limit Maximum number of elements
string $morecss Add more css styles to the SELECT component
string $moreparam Add more parameters onto the select tag. For example 'style="width: 95%"' to avoid select2 component to go over parent container
string $selected_input_value Value of preselected input text (for use with ajax)
int $hidelabel Hide label (0=no, 1=yes, 2=show search icon (before) and placeholder, 3 search icon after)
array $ajaxoptions Options for ajax_autocompleter
bool $multiple add [] in the name of element and add 'multiple' attribut (not working with ajax_autocompleter)
Returns
string HTML string with select box for thirdparty.
Definition at line 1064 of file html.form.class.php.
References ajax_autocompleter(), db, img_picto(), print, and select_thirdparty_list().
Referenced by form_thirdparty().
select_comptes ($selected = '', $htmlname = 'accountid', $statut = 0, $filtre = '', $useempty = 0, $moreattrib = '', $showcurrency = 0, $morecss = '')
Return a HTML select list of bank accounts.
Parameters
string $selected Id account pre-selected
string $htmlname Name of select zone
int $statut Status of searched accounts (0=open, 1=closed, 2=both)
string $filtre To filter list
int $useempty 1=Add an empty value in list, 2=Add an empty value in list only if there is more than 2 entries.
string $moreattrib To add more attribute on select
int $showcurrency Show currency in label
string $morecss More CSS
Returns
int <0 if error, Num of bank account found if OK (0, 1, 2, ...)
Definition at line 3677 of file html.form.class.php.
References db, dol_print_error(), dol_syslog(), and print.
Referenced by formSelectAccount().
select_conditions_paiements ($selected = 0, $htmlname = 'condid', $filtertype = -1, $addempty = 0, $noinfoadmin = 0, $morecss = '')
Return list of payment modes.
Constant MAIN_DEFAULT_PAYMENT_TERM_ID can used to set default value but scope is all application, probably not what you want. See instead to force the default value by the caller.
Parameters
int $selected Id of payment term to preselect by default
string $htmlname Nom de la zone select
int $filtertype Not used
int $addempty Add an empty entry
int $noinfoadmin 0=Add admin info, 1=Disable admin info
string $morecss Add more CSS on select tag
Returns
void
Definition at line 3345 of file html.form.class.php.
References dol_syslog(), if, info_admin(), load_cache_conditions_paiements(), and print.
Referenced by form_conditions_reglement().
select_contacts ($socid, $selected = '', $htmlname = 'contactid', $showempty = 0, $exclude = '', $limitto = '', $showfunction = 0, $moreclass = '', $showsoc = 0, $forcecombo = 0, $events = array(), $options_only = false, $moreparam = '', $htmlid = '')
Return list of all contacts (for a third party or all)
Parameters
int $socid Id ot third party or 0 for all
string $selected Id contact pre-selectionne
string $htmlname Name of HTML field ('none' for a not editable field)
int $showempty 0=no empty value, 1=add an empty value, 2=add line 'Internal' (used by user edit), 3=add an empty value only if more than one record into list
string $exclude List of contacts id to exclude
string $limitto Disable answers that are not id in this array list
integer $showfunction Add function into label
string $moreclass Add more class to class style
integer $showsoc Add company into label
int $forcecombo Force to use combo box
array $events Event options. Example: array(array('method'=>'getContacts', 'url'=>dol_buildpath('/core/ajax/contacts.php',1), 'htmlname'=>'contactid', 'params'=>array('add-customer-contact'=>'disabled')))
bool $options_only Return options only (for ajax treatment)
string $moreparam Add more parameters onto the select tag. For example 'style="width: 95%"' to avoid select2 component to go over parent container
string $htmlid Html id to use instead of htmlname
Returns
int <0 if KO, Nb of contact in list if OK You can use selectcontacts directly (warning order of param was changed)
Definition at line 1389 of file html.form.class.php.
References print, and selectcontacts().
Referenced by form_contacts().
select_country ($selected = '', $htmlname = 'country_id', $htmloption = '', $maxlength = 0, $morecss = 'minwidth300', $usecodeaskey = '', $showempty = 1, $disablefavorites = 0, $addspecialentries = 0)
Return combo list of activated countries, into language of user.
Parameters
string $selected Id or Code or Label of preselected country
string $htmlname Name of html select object
string $htmloption More html options on select object
integer $maxlength Max length for labels (0=no limit)
string $morecss More css class
string $usecodeaskey ''=Use id as key (default), 'code3'=Use code on 3 alpha as key, 'code2"=Use code on 2 alpha as key
int $showempty Show empty choice
int $disablefavorites 1=Disable favorites,
int $addspecialentries 1=Add dedicated entries for group of countries (like 'European Economic Community', ...)
Returns
string HTML string with select
Definition at line 685 of file html.form.class.php.
References $resql, ajax_combobox(), db, dol_print_error(), dol_sort_array(), dol_string_unaccent(), dol_syslog(), and dol_trunc().
select_currency ($selected = '', $htmlname = 'currency_id')
Retourne la liste des devises, dans la langue de l'utilisateur.
Parameters
string $selected preselected currency code
string $htmlname name of HTML select list
Deprecated:
Returns
void
Definition at line 4811 of file html.form.class.php.
References print, and selectCurrency().
select_date ($set_time = '', $prefix = 're', $h = 0, $m = 0, $empty = 0, $form_name = "", $d = 1, $addnowlink = 0, $nooutput = 0, $disabled = 0, $fullday = '', $addplusone = '', $adddateof = '')
Show a HTML widget to input a date or combo list for day, month, years and optionaly hours and minutes.
Fields are preselected with :
set_time date (must be a local PHP server timestamp or string date with format 'YYYY-MM-DD' or 'YYYY-MM-DD HH:MM')
local date in user area, if set_time is '' (so if set_time is '', output may differs when done from two different location)
Empty (fields empty), if set_time is -1 (in this case, parameter empty must also have value 1)
Parameters
integer $set_time Pre-selected date (must be a local PHP server timestamp), -1 to keep date not preselected, '' to use current date with 00:00 hour (Parameter 'empty' must be 0 or 2).
string $prefix Prefix for fields name
int $h 1 or 2=Show also hours (2=hours on a new line), -1 has same effect but hour and minutes are prefilled with 23:59 if date is empty, 3 show hour always empty
int $m 1=Show also minutes, -1 has same effect but hour and minutes are prefilled with 23:59 if date is empty, 3 show minutes always empty
int $empty 0=Fields required, 1=Empty inputs are allowed, 2=Empty inputs are allowed for hours only
string $form_name Not used
int $d 1=Show days, month, years
int $addnowlink Add a link "Now"
int $nooutput Do not output html string but return it
int $disabled Disable input fields
int $fullday When a checkbox with this html name is on, hour and day are set with 00:00 or 23:59
string $addplusone Add a link "+1 hour". Value must be name of another select_date field.
datetime $adddateof Add a link "Date of invoice" using the following date.
Returns
string|void Nothing or string if nooutput is 1
Deprecated:
See also
form_date(), select_month(), select_year(), select_dayofweek()
Definition at line 5212 of file html.form.class.php.
References print, and selectDate().
select_dolgroups ($selected = '', $htmlname = 'groupid', $show_empty = 0, $exclude = '', $disabled = 0, $include = '', $enableonly = '', $force_entity = '0', $multiple = false)
Return select list of groups.
Parameters
string $selected Id group preselected
string $htmlname Field name in form
int $show_empty 0=liste sans valeur nulle, 1=ajoute valeur inconnue
string $exclude Array list of groups id to exclude
int $disabled If select list must be disabled
string $include Array list of groups id to include
int $enableonly Array list of groups id to be enabled. All other must be disabled
string $force_entity '0' or Ids of environment to force
bool $multiple add [] in the name of element and add 'multiple' attribut (not working with ajax_autocompleter)
Returns
string
See also
select_dolusers()
Definition at line 7265 of file html.form.class.php.
References $resql, ajax_combobox(), db, dol_print_error(), and dol_syslog().
select_dolusers ($selected = '', $htmlname = 'userid', $show_empty = 0, $exclude = null, $disabled = 0, $include = '', $enableonly = '', $force_entity = '0', $maxlength = 0, $showstatus = 0, $morefilter = '', $show_every = 0, $enableonlytext = '', $morecss = '', $noactive = 0, $outputmode = 0, $multiple = false)
Return select list of users.
Parameters
string $selected User id or user object of user preselected. If 0 or < -2, we use id of current user. If -1, keep unselected (if empty is allowed)
string $htmlname Field name in form
int $show_empty 0=list with no empty value, 1=add also an empty value into list
array $exclude Array list of users id to exclude
int $disabled If select list must be disabled
array | string $include Array list of users id to include or 'hierarchy' to have only supervised users or 'hierarchyme' to have supervised + me
array $enableonly Array list of users id to be enabled. If defined, it means that others will be disabled
string $force_entity '0' or Ids of environment to force
int $maxlength Maximum length of string into list (0=no limit)
int $showstatus 0=show user status only if status is disabled, 1=always show user status into label, -1=never show user status
string $morefilter Add more filters into sql request (Example: 'employee = 1')
integer $show_every 0=default list, 1=add also a value "Everybody" at beginning of list
string $enableonlytext If option $enableonlytext is set, we use this text to explain into label why record is disabled. Not used if enableonly is empty.
string $morecss More css
int $noactive Show only active users (this will also happened whatever is this option if USER_HIDE_INACTIVE_IN_COMBOBOX is on).
int $outputmode 0=HTML select string, 1=Array
bool $multiple add [] in the name of element and add 'multiple' attribut
Returns
string HTML select string
See also
select_dolgroups()
Definition at line 1596 of file html.form.class.php.
References $resql, ajax_combobox(), db, dol_print_error(), and dol_syslog().
Referenced by form_users(), select_dolusers_forevent(), and select_users().
select_dolusers_forevent ($action = '', $htmlname = 'userid', $show_empty = 0, $exclude = null, $disabled = 0, $include = '', $enableonly = '', $force_entity = '0', $maxlength = 0, $showstatus = 0, $morefilter = '', $showproperties = 0, $listofuserid = array(), $listofcontactid = array(), $listofotherid = array())
Return select list of users.
Selected users are stored into session. List of users are provided into $_SESSION['assignedtouser'].
Parameters
string $action Value for $action
string $htmlname Field name in form
int $show_empty 0=list without the empty value, 1=add empty value
array $exclude Array list of users id to exclude
int $disabled If select list must be disabled
array $include Array list of users id to include or 'hierarchy' to have only supervised users
array $enableonly Array list of users id to be enabled. All other must be disabled
int $force_entity '0' or Ids of environment to force
int $maxlength Maximum length of string into list (0=no limit)
int $showstatus 0=show user status only if status is disabled, 1=always show user status into label, -1=never show user status
string $morefilter Add more filters into sql request
int $showproperties Show properties of each attendees
array $listofuserid Array with properties of each user
array $listofcontactid Array with properties of each contact
array $listofotherid Array with properties of each other contact
Returns
string HTML select string
See also
select_dolgroups()
Definition at line 1804 of file html.form.class.php.
References db, dol_escape_htmltag(), and select_dolusers().
select_duration ($prefix, $iSecond = '', $disabled = 0, $typehour = 'select', $minunderhours = 0, $nooutput = 0)
Function to show a form to select a duration on a page.
Parameters
string $prefix Prefix for input fields
int $iSecond Default preselected duration (number of seconds or '')
int $disabled Disable the combo box
string $typehour If 'select' then input hour and input min is a combo, if 'text' input hour is in text and input min is a text, if 'textselect' input hour is in text and input min is a combo
integer $minunderhours If 1, show minutes selection under the hours
int $nooutput Do not output html string but return it
Returns
string|void
Definition at line 5619 of file html.form.class.php.
select_export_model ($selected = '', $htmlname = 'exportmodelid', $type = '', $useempty = 0)
Return list of export templates.
Parameters
string $selected Id modele pre-selectionne
string $htmlname Name of HTML select
string $type Type of searched templates
int $useempty Affiche valeur vide dans liste
Returns
void
Definition at line 6861 of file html.form.class.php.
References db, dol_print_error(), and print.
select_incoterms ($selected = '', $location_incoterms = '', $page = '', $htmlname = 'incoterm_id', $htmloption = '', $forcecombo = 1, $events = array())
Return select list of incoterms.
Parameters
string $selected Id or Code of preselected incoterm
string $location_incoterms Value of input location
string $page Defined the form action
string $htmlname Name of html select object
string $htmloption Options html on select object
int $forcecombo Force to load all values and output a standard combobox (with no beautification)
array $events Event options to run on change. Example: array(array('method'=>'getContacts', 'url'=>dol_buildpath('/core/ajax/contacts.php',1), 'htmlname'=>'contactid', 'params'=>array('add-customer-contact'=>'disabled')))
Returns
string HTML string with select and input
Definition at line 798 of file html.form.class.php.
References $resql, ajax_combobox(), db, dol_print_error(), and dol_syslog().
select_product_fourn_price ($productid, $htmlname = 'productfournpriceid', $selected_supplier = '')
Return list of suppliers prices for a product.
Parameters
int $productid Id of product
string $htmlname Name of HTML field
int $selected_supplier Pre-selected supplier if more than 1 result
Returns
void
Definition at line 2898 of file html.form.class.php.
References db, dol_print_error(), dol_syslog(), and price().
select_produits ($selected = '', $htmlname = 'productid', $filtertype = '', $limit = 20, $price_level = 0, $status = 1, $finished = 2, $selected_input_value = '', $hidelabel = 0, $ajaxoptions = array(), $socid = 0, $showempty = '1', $forcecombo = 0, $morecss = '', $hidepriceinlabel = 0, $warehouseStatus = '', $selected_combinations = array())
Return list of products for customer in Ajax if Ajax activated or go to select_produits_list.
Parameters
int $selected Preselected products
string $htmlname Name of HTML select field (must be unique in page)
int $filtertype Filter on product type (''=nofilter, 0=product, 1=service)
int $limit Limit on number of returned lines
int $price_level Level of price to show
int $status Sell status -1=Return all products, 0=Products not on sell, 1=Products on sell
int $finished 2=all, 1=finished, 0=raw material
string $selected_input_value Value of preselected input text (for use with ajax)
int $hidelabel Hide label (0=no, 1=yes, 2=show search icon (before) and placeholder, 3 search icon after)
array $ajaxoptions Options for ajax_autocompleter
int $socid Thirdparty Id (to get also price dedicated to this customer)
string $showempty '' to not show empty line. Translation key to show an empty line. '1' show empty line with no text.
int $forcecombo Force to use combo box
string $morecss Add more css on select
int $hidepriceinlabel 1=Hide prices in label
string $warehouseStatus Warehouse status filter to count the quantity in stock. Following comma separated filter options can be used 'warehouseopen' = count products from open warehouses, 'warehouseclosed' = count products from closed warehouses, 'warehouseinternal' = count products from warehouses for internal correct/transfer only
array $selected_combinations Selected combinations. Format: array([attrid] => attrval, [...])
Returns
void
Definition at line 1897 of file html.form.class.php.
References ajax_autocompleter(), db, img_picto(), print, and select_produits_list().
select_produits_fournisseurs ($socid, $selected = '', $htmlname = 'productid', $filtertype = '', $filtre = '', $ajaxoptions = array(), $hidelabel = 0, $alsoproductwithnosupplierprice = 0, $morecss = '')
Return list of products for customer (in Ajax if Ajax activated or go to select_produits_fournisseurs_list)
Parameters
int $socid Id third party
string $selected Preselected product
string $htmlname Name of HTML Select
string $filtertype Filter on product type (''=nofilter, 0=product, 1=service)
string $filtre For a SQL filter
array $ajaxoptions Options for ajax_autocompleter
int $hidelabel Hide label (0=no, 1=yes)
int $alsoproductwithnosupplierprice 1=Add also product without supplier prices
string $morecss More CSS
Returns
void
Definition at line 2619 of file html.form.class.php.
References ajax_autocompleter(), db, print, and select_produits_fournisseurs_list().
select_produits_fournisseurs_list ($socid, $selected = '', $htmlname = 'productid', $filtertype = '', $filtre = '', $filterkey = '', $statut = -1, $outputmode = 0, $limit = 100, $alsoproductwithnosupplierprice = 0, $morecss = '')
Return list of suppliers products.
Parameters
int $socid Id societe fournisseur (0 pour aucun filtre)
int $selected Product price pre-selected (must be 'id' in product_fournisseur_price or 'idprod_IDPROD')
string $htmlname Nom de la zone select
string $filtertype Filter on product type (''=nofilter, 0=product, 1=service)
string $filtre Pour filtre sql
string $filterkey Filtre des produits
int $statut -1=Return all products, 0=Products not on sell, 1=Products on sell (not used here, a filter on tobuy is already hard coded in request)
int $outputmode 0=HTML select string, 1=Array
int $limit Limit of line number
int $alsoproductwithnosupplierprice 1=Add also product without supplier prices
string $morecss Add more CSS
Returns
array Array of keys for json
Definition at line 2665 of file html.form.class.php.
References ajax_combobox(), db, dol_print_error(), dol_strlen(), dol_syslog(), dol_trunc(), if, price(), Product\TYPE_SERVICE, and vatrate().
Referenced by select_produits_fournisseurs().
select_produits_list ($selected = '', $htmlname = 'productid', $filtertype = '', $limit = 20, $price_level = 0, $filterkey = '', $status = 1, $finished = 2, $outputmode = 0, $socid = 0, $showempty = '1', $forcecombo = 0, $morecss = '', $hidepriceinlabel = 0, $warehouseStatus = '')
Return list of products for a customer.
Parameters
int $selected Preselected product
string $htmlname Name of select html
string $filtertype Filter on product type (''=nofilter, 0=product, 1=service)
int $limit Limit on number of returned lines
int $price_level Level of price to show
string $filterkey Filter on product
int $status -1=Return all products, 0=Products not on sell, 1=Products on sell
int $finished Filter on finished field: 2=No filter
int $outputmode 0=HTML select string, 1=Array
int $socid Thirdparty Id (to get also price dedicated to this customer)
string $showempty '' to not show empty line. Translation key to show an empty line. '1' show empty line with no text.
int $forcecombo Force to use combo box
string $morecss Add more css on select
int $hidepriceinlabel 1=Hide prices in label
string $warehouseStatus Warehouse status filter to group/count stock. Following comma separated filter options can be used. 'warehouseopen' = count products from open warehouses, 'warehouseclosed' = count products from closed warehouses, 'warehouseinternal' = count products from warehouses for internal correct/transfer only
Returns
array Array of keys for json
Definition at line 2051 of file html.form.class.php.
References ajax_combobox(), constructProductListOption(), db, dol_print_error(), dol_syslog(), getEntity(), if, price2num(), Entrepot\STATUS_CLOSED, Entrepot\STATUS_OPEN_ALL, and Entrepot\STATUS_OPEN_INTERNAL.
Referenced by select_produits().
select_remises ($selected, $htmlname, $filter, $socid, $maxvalue = 0)
Return HTML combo list of absolute discounts.
Parameters
string $selected Id remise fixe pre-selectionnee
string $htmlname Nom champ formulaire
string $filter Criteres optionnels de filtre
int $socid Id of thirdparty
int $maxvalue Max value for lines that can be selected
Returns
int Return number of qualifed lines in list
Definition at line 1302 of file html.form.class.php.
References $resql, db, dol_print_error(), dol_syslog(), dol_trunc(), price(), and print.
Referenced by form_remise_dispo().
select_thirdparty ($selected = '', $htmlname = 'socid', $filter = '', $limit = 20, $ajaxoptions = array(), $forcecombo = 0)
Return HTML code to select a company.
Parameters
int $selected Preselected products
string $htmlname Name of HTML select field (must be unique in page)
int $filter Filter on thirdparty
int $limit Limit on number of returned lines
array $ajaxoptions Options for ajax_autocompleter
int $forcecombo Force to load all values and output a standard combobox (with no beautification)
Returns
string Return select box for thirdparty.
Deprecated:
3.8 Use select_company instead. For exemple $form->select_thirdparty(GETPOST('socid'),'socid','',0) => $form->select_company(GETPOST('socid'),'socid','',1,0,0,array(),0)
Definition at line 1038 of file html.form.class.php.
References select_thirdparty_list().
select_thirdparty_list ($selected = '', $htmlname = 'socid', $filter = '', $showempty = '', $showtype = 0, $forcecombo = 0, $events = array(), $filterkey = '', $outputmode = 0, $limit = 0, $morecss = 'minwidth100', $moreparam = '', $multiple = false)
Output html form to select a third party.
Note, you must use the select_company to get the component to select a third party. This function must only be called by select_company.
Parameters
string $selected Preselected type
string $htmlname Name of field in form
string $filter Optional filters criteras (example: 's.rowid <> x', 's.client in (1,3)')
string $showempty Add an empty field (Can be '1' or text to use on empty line like 'SelectThirdParty')
int $showtype Show third party type in combolist (customer, prospect or supplier)
int $forcecombo Force to use standard HTML select component without beautification
array $events Event options. Example: array(array('method'=>'getContacts', 'url'=>dol_buildpath('/core/ajax/contacts.php',1), 'htmlname'=>'contactid', 'params'=>array('add-customer-contact'=>'disabled')))
string $filterkey Filter on key value
int $outputmode 0=HTML select string, 1=Array
int $limit Limit number of answers
string $morecss Add more css styles to the SELECT component
string $moreparam Add more parameters onto the select tag. For example 'style="width: 95%"' to avoid select2 component to go over parent container
bool $multiple add [] in the name of element and add 'multiple' attribut
Returns
string HTML string with
Definition at line 1128 of file html.form.class.php.
References $resql, ajax_combobox(), db, dol_print_error(), dol_syslog(), and testSqlAndScriptInject().
Referenced by select_company(), and select_thirdparty().
select_type_fees ($selected = '', $htmlname = 'type', $showempty = 0)
Return list of types of notes.
Parameters
string $selected Preselected type
string $htmlname Name of field in form
int $showempty Add an empty field
Returns
void
Definition at line 994 of file html.form.class.php.
References dol_syslog(), info_admin(), load_cache_types_fees(), and print.
select_type_of_lines ($selected = '', $htmlname = 'type', $showempty = 0, $hidetext = 0, $forceall = 0)
Return list of types of lines (product or service) Example: 0=product, 1=service, 9=other (for external module)
Parameters
string $selected Preselected type
string $htmlname Name of field in html form
int $showempty Add an empty field
int $hidetext Do not show label 'Type' before combo box (used only if there is at least 2 choices to select)
integer $forceall 1=Force to show products and services in combo list, whatever are activated modules, 0=No force, 2=Force to show only Products, 3=Force to show only services, -1=Force none (and set hidden field to 'service')
Returns
void
Definition at line 891 of file html.form.class.php.
References print.
select_types_paiements ($selected = '', $htmlname = 'paiementtype', $filtertype = '', $format = 0, $empty = 1, $noadmininfo = 0, $maxlength = 0, $active = 1, $morecss = '')
Return list of payment methods.
Parameters
string $selected Id du mode de paiement pre-selectionne
string $htmlname Nom de la zone select
string $filtertype To filter on field type in llx_c_paiement ('CRDT' or 'DBIT' or array('code'=>xx,'label'=>zz))
int $format 0=id+libelle, 1=code+code, 2=code+libelle, 3=id+code
int $empty 1=peut etre vide, 0 sinon
int $noadmininfo 0=Add admin info, 1=Disable admin info
int $maxlength Max length of label
int $active Active or not, -1 = all
string $morecss Add more CSS on select tag
Returns
void
Definition at line 3392 of file html.form.class.php.
References dol_syslog(), dol_trunc(), if, info_admin(), load_cache_types_paiements(), and print.
Referenced by form_modes_reglement().
select_users ($selected = '', $htmlname = 'userid', $show_empty = 0, $exclude = null, $disabled = 0, $include = '', $enableonly = '', $force_entity = '0')
Return select list of users.
Parameters
string $selected Id user preselected
string $htmlname Field name in form
int $show_empty 0=liste sans valeur nulle, 1=ajoute valeur inconnue
array $exclude Array list of users id to exclude
int $disabled If select list must be disabled
array $include Array list of users id to include
int $enableonly Array list of users id to be enabled. All other must be disabled
string $force_entity '0' or Ids of environment to force
Returns
void
Deprecated:
Use select_dolusers instead
See also
select_dolusers()
Definition at line 1566 of file html.form.class.php.
References print, and select_dolusers().
static selectarray ($htmlname, $array, $id = '', $show_empty = 0, $key_in_label = 0, $value_as_key = 0, $moreparam = '', $translate = 0, $maxlen = 0, $disabled = 0, $sort = '', $morecss = '', $addjscombo = 0, $moreparamonempty = '', $disablebademail = 0, $nohtmlescape = 0) static
Return a HTML select string, built from an array of key+value.
Note: Do not apply langs->trans function on returned content, content may be entity encoded twice.
Parameters
string $htmlname Name of html select area. Must start with "multi" if this is a multiselect
array $array Array like array(key => value) or array(key=>array('label'=>..., 'data-...'=>...))
string|string[] $id Preselected key or preselected keys for multiselect
int | string $show_empty 0 no empty value allowed, 1 or string to add an empty value into list (key is -1 and value is '' or ' ' if 1, key is -1 and value is text if string), <0 to add an empty value with key that is this value.
int $key_in_label 1 to show key into label with format "[key] value"
int $value_as_key 1 to use value as key
string $moreparam Add more parameters onto the select tag. For example 'style="width: 95%"' to avoid select2 component to go over parent container
int $translate 1=Translate and encode value
int $maxlen Length maximum for labels
int $disabled Html select box is disabled
string $sort 'ASC' or 'DESC' = Sort on label, '' or 'NONE' or 'POS' = Do not sort, we keep original order
string $morecss Add more class to css styles
int $addjscombo Add js combo
string $moreparamonempty Add more param on the empty option line. Not used if show_empty not set
int $disablebademail 1=Check if a not valid email, 2=Check string '—', and if found into value, disable and colorize entry
int $nohtmlescape No html escaping.
Returns
string HTML select string.
See also
multiselectarray(), selectArrayAjax(), selectArrayFilter()
Definition at line 5913 of file html.form.class.php.
Referenced by ActionsCardCommon\assign_values(), editfieldval(), FormCompany\form_prospect_level(), FormMail\get_form(), FormOther\getBoxesArea(), Ticket\printSelectStatus(), FormAccounting\select_account(), BookKeeping\select_account(), FormAccounting\select_auxaccount(), FormAccounting\select_bookkeeping_importkey(), FormAccounting\select_journal(), FormMailing\selectDestinariesStatus(), FormOrder\selectInputMethod(), dolReceiptPrinter\selectProfilePrinter(), FormOrder\selectSupplierOrderStatus(), FormBank\selectTypeOfBankAccount(), dolReceiptPrinter\selectTypePrinter(), and FormAccounting\selectyear_accountancy_bookkepping().
static selectArrayAjax ($htmlname, $url, $id = '', $moreparam = '', $moreparamtourl = '', $disabled = 0, $minimumInputLength = 1, $morecss = '', $callurlonselect = 0, $placeholder = '', $acceptdelayedhtml = 0) static
Return a HTML select string, built from an array of key+value, but content returned into select come from an Ajax call of an URL.
Note: Do not apply langs->trans function on returned content of Ajax service, content may be entity encoded twice.
Parameters
string $htmlname Name of html select area
string $url Url. Must return a json_encode of array(key=>array('text'=>'A text', 'url'=>'An url'), ...)
string $id Preselected key
string $moreparam Add more parameters onto the select tag
string $moreparamtourl Add more parameters onto the Ajax called URL
int $disabled Html select box is disabled
int $minimumInputLength Minimum Input Length
string $morecss Add more class to css styles
int $callurlonselect If set to 1, some code is added so an url return by the ajax is called when value is selected.
string $placeholder String to use as placeholder
integer $acceptdelayedhtml 1 = caller is requesting to have html js content not returned but saved into global $delayedhtmlcontent (so caller can show it at end of page to avoid flash FOUC effect)
Returns
string HTML select string
See also
selectArrayFilter(), ajax_combobox() in ajax.lib.php
Definition at line 6034 of file html.form.class.php.
static selectArrayFilter ($htmlname, $array, $id = '', $moreparam = '', $disableFiltering = 0, $disabled = 0, $minimumInputLength = 1, $morecss = '', $callurlonselect = 0, $placeholder = '', $acceptdelayedhtml = 0) static
Return a HTML select string, built from an array of key+value, but content returned into select is defined into $array parameter.
Note: Do not apply langs->trans function on returned content of Ajax service, content may be entity encoded twice.
Parameters
string $htmlname Name of html select area
string $array Array (key=>array('text'=>'A text', 'url'=>'An url'), ...)
string $id Preselected key
string $moreparam Add more parameters onto the select tag
int $disableFiltering If set to 1, results are not filtered with searched string
int $disabled Html select box is disabled
int $minimumInputLength Minimum Input Length
string $morecss Add more class to css styles
int $callurlonselect If set to 1, some code is added so an url return by the ajax is called when value is selected.
string $placeholder String to use as placeholder
integer $acceptdelayedhtml 1 = caller is requesting to have html js content not returned but saved into global $delayedhtmlcontent (so caller can show it at end of page to avoid flash FOUC effect)
Returns
string HTML select string
See also
selectArrayAjax(), ajax_combobox() in ajax.lib.php
Definition at line 6136 of file html.form.class.php.
References select2arrayoflanguage.
selectAvailabilityDelay ($selected = '', $htmlname = 'availid', $filtertype = '', $addempty = 0)
Retourne la liste des types de delais de livraison possibles.
Parameters
int $selected Id du type de delais pre-selectionne
string $htmlname Nom de la zone select
string $filtertype To add a filter
int $addempty Add empty entry
Returns
void
Definition at line 3163 of file html.form.class.php.
References dol_syslog(), info_admin(), load_cache_availability(), and print.
Referenced by form_availability().
selectcontacts ($socid, $selected = '', $htmlname = 'contactid', $showempty = 0, $exclude = '', $limitto = '', $showfunction = 0, $moreclass = '', $options_only = false, $showsoc = 0, $forcecombo = 0, $events = array(), $moreparam = '', $htmlid = '', $multiple = false)
Return HTML code of the SELECT of list of all contacts (for a third party or all).
This also set the number of contacts found into $this->num
Since
9.0 Add afterSelectContactOptions hook
Parameters
int $socid Id ot third party or 0 for all or -1 for empty list
array | int $selected Array of ID of pre-selected contact id
string $htmlname Name of HTML field ('none' for a not editable field)
int $showempty 0=no empty value, 1=add an empty value, 2=add line 'Internal' (used by user edit), 3=add an empty value only if more than one record into list
string $exclude List of contacts id to exclude
string $limitto Disable answers that are not id in this array list
integer $showfunction Add function into label
string $moreclass Add more class to class style
bool $options_only Return options only (for ajax treatment)
integer $showsoc Add company into label
int $forcecombo Force to use combo box (so no ajax beautify effect)
array $events Event options. Example: array(array('method'=>'getContacts', 'url'=>dol_buildpath('/core/ajax/contacts.php',1), 'htmlname'=>'contactid', 'params'=>array('add-customer-contact'=>'disabled')))
string $moreparam Add more parameters onto the select tag. For example 'style="width: 95%"' to avoid select2 component to go over parent container
string $htmlid Html id to use instead of htmlname
bool $multiple add [] in the name of element and add 'multiple' attribut
Returns
int <0 if KO, Nb of contact in list if OK
Definition at line 1419 of file html.form.class.php.
References $resql, ajax_combobox(), db, dol_print_error(), and dol_syslog().
Referenced by select_contacts().
selectCurrency ($selected = '', $htmlname = 'currency_id', $mode = 0)
Retourne la liste des devises, dans la langue de l'utilisateur.
Parameters
string $selected preselected currency code
string $htmlname name of HTML select list
string $mode 0 = Add currency symbol into label, 1 = Add 3 letter iso code
Returns
string
Definition at line 4825 of file html.form.class.php.
References ajax_combobox(), and info_admin().
Referenced by select_currency().
selectDate ($set_time = '', $prefix = 're', $h = 0, $m = 0, $empty = 0, $form_name = "", $d = 1, $addnowlink = 0, $disabled = 0, $fullday = '', $addplusone = '', $adddateof = '', $openinghours = '', $stepminutes = 1)
Show a HTML widget to input a date or combo list for day, month, years and optionaly hours and minutes.
Fields are preselected with :
set_time date (must be a local PHP server timestamp or string date with format 'YYYY-MM-DD' or 'YYYY-MM-DD HH:MM')
local date in user area, if set_time is '' (so if set_time is '', output may differs when done from two different location)
Empty (fields empty), if set_time is -1 (in this case, parameter empty must also have value 1)
Parameters
integer $set_time Pre-selected date (must be a local PHP server timestamp), -1 to keep date not preselected, '' to use current date with 00:00 hour (Parameter 'empty' must be 0 or 2).
string $prefix Prefix for fields name
int $h 1 or 2=Show also hours (2=hours on a new line), -1 has same effect but hour and minutes are prefilled with 23:59 if date is empty, 3 show hour always empty
int $m 1=Show also minutes, -1 has same effect but hour and minutes are prefilled with 23:59 if date is empty, 3 show minutes always empty
int $empty 0=Fields required, 1=Empty inputs are allowed, 2=Empty inputs are allowed for hours only
string $form_name Not used
int $d 1=Show days, month, years
int $addnowlink Add a link "Now"
int $disabled Disable input fields
int $fullday When a checkbox with this html name is on, hour and day are set with 00:00 or 23:59
string $addplusone Add a link "+1 hour". Value must be name of another selectDate field.
datetime $adddateof Add a link "Date of invoice" using the following date.
string $openinghours Specify hour strat and hour end for the select ex 8,20
int $stepminutes Specify step for minutes between 1 and 30
Returns
string Html for selectDate
See also
form_date(), select_month(), select_year(), select_dayofweek()
Definition at line 5247 of file html.form.class.php.
References dol_now(), dol_print_date(), getServerTimeZoneInt(), and type.
Referenced by editfieldval(), form_date(), formconfirm(), and select_date().
selectEstablishments ($selected = '', $htmlname = 'entity', $statut = 0, $filtre = '', $useempty = 0, $moreattrib = '')
Return a HTML select list of establishment.
Parameters
string $selected Id establishment pre-selected
string $htmlname Name of select zone
int $statut Status of searched establishment (0=open, 1=closed, 2=both)
string $filtre To filter list
int $useempty 1=Add an empty value in list, 2=Add an empty value in list only if there is more than 2 entries.
string $moreattrib To add more attribute on select
Returns
int <0 if error, Num of establishment found if OK (0, 1, 2, ...)
Definition at line 3749 of file html.form.class.php.
References db, dol_print_error(), dol_syslog(), and print.
selectExpense ($selected = '', $htmlname = 'fk_c_type_fees', $useempty = 0, $allchoice = 1, $useid = 0)
Return HTML to show a select of expense.
Parameters
string $selected preselected category
string $htmlname name of HTML select list
integer $useempty 1=Add empty choice
integer $allchoice 1=Add all choice
integer $useid 0=use 'code' as key, 1=use 'id' as key
Returns
string
Definition at line 7569 of file html.form.class.php.
References $resql, and dol_print_error().
selectExpenseCategories ($selected = '', $htmlname = 'fk_c_exp_tax_cat', $useempty = 0, $excludeid = array(), $target = '', $default_selected = 0, $params = array())
Return HTML to show the select of expense categories.
Parameters
string $selected preselected category
string $htmlname name of HTML select list
integer $useempty 1=Add empty line
array $excludeid id to exclude
string $target htmlname of target select to bind event
int $default_selected default category to select if fk_c_type_fees change = EX_KME
array $params param to give
Returns
string
Definition at line 7443 of file html.form.class.php.
References $resql, and dol_print_error().
selectExpenseRanges ($selected = '', $htmlname = 'fk_range', $useempty = 0)
Return HTML to show the select ranges of expense range.
Parameters
string $selected preselected category
string $htmlname name of HTML select list
integer $useempty 1=Add empty line
Returns
string
Definition at line 7532 of file html.form.class.php.
References $resql, dol_print_error(), and price().
selectForForms ($objectdesc, $htmlname, $preselectedvalue, $showempty = '', $searchkey = '', $placeholder = '', $morecss = '', $moreparams = '', $forcecombo = 0)
Generic method to select a component from a combo list.
This is the generic method that will replace all specific existing methods.
Parameters
string $objectdesc Objectclassname:Objectclasspath
string $htmlname Name of HTML select component
int $preselectedvalue Preselected value (ID of element)
string $showempty ''=empty values not allowed, 'string'=value show if we allow empty values (for example 'All', ...)
string $searchkey Search criteria
string $placeholder Place holder
string $morecss More CSS
string $moreparams More params provided to ajax call
int $forcecombo Force to load all values and output a standard combobox (with no beautification)
Returns
string Return HTML string
See also
selectForFormsList() select_thirdparty
Definition at line 5707 of file html.form.class.php.
selectForFormsList ($objecttmp, $htmlname, $preselectedvalue, $showempty = '', $searchkey = '', $placeholder = '', $morecss = '', $moreparams = '', $forcecombo = 0, $outputmode = 0)
Output html form to select an object.
Note, this function is called by selectForForms or by ajax selectobject.php
Parameters
Object $objecttmp Object
string $htmlname Name of HTML select component
int $preselectedvalue Preselected value (ID of element)
string $showempty ''=empty values not allowed, 'string'=value show if we allow empty values (for example 'All', ...)
string $searchkey Search value
string $placeholder Place holder
string $morecss More CSS
string $moreparams More params provided to ajax call
int $forcecombo Force to load all values and output a standard combobox (with no beautification)
int $outputmode 0=HTML select string, 1=Array
Returns
string Return HTML string
See also
selectForForms()
Definition at line 5776 of file html.form.class.php.
selectInputReason ($selected = '', $htmlname = 'demandreasonid', $exclude = '', $addempty = 0)
Return list of input reason (events that triggered an object creation, like after sending an emailing, making an advert, ...) List found into table c_input_reason loaded by loadCacheInputReason.
Parameters
int $selected Id or code of type origin to select by default
string $htmlname Nom de la zone select
string $exclude To exclude a code value (Example: SRC_PROP)
int $addempty Add an empty entry
Returns
void
Definition at line 3249 of file html.form.class.php.
References info_admin(), loadCacheInputReason(), and print.
Referenced by formInputReason().
selectMassAction ($selected, $arrayofaction, $alwaysvisible = 0)
Generate select HTML to choose massaction.
Parameters
string $selected Value auto selected when at least one record is selected. Not a preselected value. Use '0' by default.
int $arrayofaction array('code'=>'label', ...). The code is the key stored into the GETPOST('massaction') when submitting action.
int $alwaysvisible 1=select button always visible
Returns
string Select list
Definition at line 582 of file html.form.class.php.
References ajax_combobox(), and dol_escape_htmltag().
selectMultiCurrency ($selected = '', $htmlname = 'multicurrency_code', $useempty = 0)
Return array of currencies in user language.
Parameters
string $selected preselected currency code
string $htmlname name of HTML select list
integer $useempty 1=Add empty line
Returns
string
Definition at line 4875 of file html.form.class.php.
References $resql, and ajax_combobox().
Referenced by form_multicurrency_code().
selectPriceBaseType ($selected = '', $htmlname = 'price_base_type')
Selection HT or TTC.
Parameters
string $selected Id pre-selectionne
string $htmlname Nom de la zone select
Returns
string Code of HTML select to chose tax or not
Definition at line 3446 of file html.form.class.php.
selectShippingMethod ($selected = '', $htmlname = 'shipping_method_id', $filtre = '', $useempty = 0, $moreattrib = '')
Return a HTML select list of shipping mode.
Parameters
string $selected Id shipping mode pre-selected
string $htmlname Name of select zone
string $filtre To filter list
int $useempty 1=Add an empty value in list, 2=Add an empty value in list only if there is more than 2 entries.
string $moreattrib To add more attribute on select
Returns
void
Definition at line 3484 of file html.form.class.php.
References db, dol_print_error(), dol_syslog(), info_admin(), and print.
Referenced by formSelectShippingMethod().
selectSituationInvoices ($selected = '', $socid = 0)
Creates HTML last in cycle situation invoices selector.
Parameters
string $selected Preselected ID
int $socid Company ID
Returns
string HTML select
Definition at line 3568 of file html.form.class.php.
References $resql, db, and dol_syslog().
selectUnits ($selected = '', $htmlname = 'units', $showempty = 0)
Creates HTML units selector (code => label)
Parameters
string $selected Preselected Unit ID
string $htmlname Select name
int $showempty Add a nempty line
Returns
string HTML select
Definition at line 3625 of file html.form.class.php.
References $resql, and db.
selectyesno ($htmlname, $value = '', $option = 0, $disabled = false, $useempty = 0)
Return an html string with a select combo box to choose yes or no.
Parameters
string $htmlname Name of html select field
string $value Pre-selected value
int $option 0 return yes/no, 1 return 1/0
bool $disabled true or false
int $useempty 1=Add empty line
Returns
string See option
Definition at line 6821 of file html.form.class.php.
Referenced by formconfirm().
showbarcode (& $object, $width = 100)
Return HTML code to output a barcode.
Parameters
Object $object Object containing data to retrieve file name
int $width Width of photo
Returns
string HTML code to output barcode
Definition at line 7069 of file html.form.class.php.
showCategories ($id, $type, $rendermode = 0)
Render list of categories linked to object with id $id and type $type.
Parameters
int $id Id of object
string $type Type of category ('member', 'customer', 'supplier', 'product', 'contact'). Old mode (0, 1, 2, ...) is deprecated.
int $rendermode 0=Default, use multiselect. 1=Emulate multiselect (recommended)
Returns
string String with categories
Definition at line 6451 of file html.form.class.php.
References img_object(), multiselectarray(), and select_all_categories().
showCheckAddButtons ($cssclass = 'checkforaction', $calljsfunction = 0)
Return HTML to show the search and clear seach button.
Parameters
string $cssclass CSS class
int $calljsfunction 0=default. 1=call function initCheckForSelect() after changing status of checkboxes
Returns
string
Definition at line 7382 of file html.form.class.php.
Referenced by showFilterAndCheckAddButtons().
showFilterAndCheckAddButtons ($addcheckuncheckall = 0, $cssclass = 'checkforaction', $calljsfunction = 0)
Return HTML to show the search and clear seach button.
Parameters
int $addcheckuncheckall Add the check all/uncheck all checkbox (use javascript) and code to manage this
string $cssclass CSS class
int $calljsfunction 0=default. 1=call function initCheckForSelect() after changing status of checkboxes
Returns
string
Definition at line 7421 of file html.form.class.php.
References showCheckAddButtons(), and showFilterButtons().
showFilterButtons ()
Return HTML to show the search and clear seach button.
Returns
string
Definition at line 7361 of file html.form.class.php.
Referenced by showFilterAndCheckAddButtons().
showLinkedObjectBlock ($object, $morehtmlright = '', $compatibleImportElementsList = false)
Show linked object block.
Parameters
CommonObject $object Object we want to show links to
string $morehtmlright More html to show on right of title
array $compatibleImportElementsList Array of compatibles elements object for "import from" action
Returns
int <0 if KO, >=0 if OK
Definition at line 6496 of file html.form.class.php.
References dol_buildpath(), load_fiche_titre(), and print.
showLinkToObjectBlock ($object, $restrictlinksto = array(), $excludelinksto = array())
Show block with links to link to other objects.
Parameters
CommonObject $object Object we want to show links to
array $restrictlinksto Restrict links to some elements, for exemple array('order') or array('supplier_order'). null or array() if no restriction.
array $excludelinksto Do not show links of this type, for exemple array('order') or array('supplier_order'). null or array() if no exclusion.
Returns
string <0 if KO, >0 if OK
Definition at line 6645 of file html.form.class.php.
References db, dol_print_error(), getEntity(), price(), and print.
static showphoto ($modulepart, $object, $width = 100, $height = 0, $caneditfield = 0, $cssclass = 'photowithmargin', $imagesize = '', $addlinktofullsize = 1, $cache = 0, $forcecapture = '') static
Return HTML code to output a photo.
Parameters
string $modulepart Key to define module concerned ('societe', 'userphoto', 'memberphoto')
object $object Object containing data to retrieve file name
int $width Width of photo
int $height Height of photo (auto if 0)
int $caneditfield Add edit fields
string $cssclass CSS name to use on img for photo
string $imagesize 'mini', 'small' or '' (original)
int $addlinktofullsize Add link to fullsize image
int $cache 1=Accept to use image in cache
string $forcecapture Force parameter capture on HTML input file element to ask a smartphone to allow to open camera to take photo. Auto if empty.
Returns
string HTML code to output photo
See also
https://gravatar.com/site/implement/images/php/
Definition at line 7106 of file html.form.class.php.
References dol_hash(), dol_print_error(), get_exdir(), getAdvancedPreviewUrl(), and getImageFileNameForSize().
Referenced by Societe\getNomUrl(), Adherent\getNomUrl(), User\getNomUrl(), User\getPhotoUrl(), and top_menu_user().
showrefnav ($object, $paramid, $morehtml = '', $shownav = 1, $fieldid = 'rowid', $fieldref = 'ref', $morehtmlref = '', $moreparam = '', $nodbprefix = 0, $morehtmlleft = '', $morehtmlstatus = '', $morehtmlright = '')
Return a HTML area with the reference of object and a navigation bar for a business object Note: To complete search with a particular filter on select, you can set $object->next_prev_filter set to define SQL criterias.
Parameters
object $object Object to show.
string $paramid Name of parameter to use to name the id into the URL next/previous link.
string $morehtml More html content to output just before the nav bar.
int $shownav Show Condition (navigation is shown if value is 1).
string $fieldid Name of field id into database to use for select next and previous (we make the select max and min on this field compared to $object->ref). Use 'none' to disable next/prev.
string $fieldref Name of field ref of object (object->ref) to show or 'none' to not show ref.
string $morehtmlref More html to show after ref.
string $moreparam More param to add in nav link url. Must start with '&...'.
int $nodbprefix Do not include DB prefix to forge table name.
string $morehtmlleft More html code to show before ref.
string $morehtmlstatus More html code to show under navigation arrows (status place).
string $morehtmlright More html code to show after ref.
Returns
string Portion HTML with ref + navigation buttons
Definition at line 6919 of file html.form.class.php.
References dol_htmlentities().
textwithpicto ($text, $htmltext, $direction = 1, $type = 'help', $extracss = '', $noencodehtmltext = 0, $notabs = 2, $tooltiptrigger = '', $forcenowrap = 0)
Show a text with a picto and a tooltip on picto.
Parameters
string $text Text to show
string $htmltext Content of tooltip
int $direction 1=Icon is after text, -1=Icon is before text, 0=no icon
string $type Type of picto ('info', 'help', 'warning', 'superadmin', 'mypicto', ...) or image filepath or 'none'
string $extracss Add a CSS style to td, div or span tag
int $noencodehtmltext Do not encode into html entity the htmltext
int $notabs 0=Include table and tr tags, 1=Do not include table and tr tags, 2=use div, 3=use span
string $tooltiptrigger ''=Tooltip on hover, 'abc'=Tooltip on click (abc is a unique key, clickable link is on image or on link if param $type='none')
int $forcenowrap Force no wrap between text and picto (works with notabs=2 only)
Returns
string HTML code of text, picto, tooltip
Definition at line 530 of file html.form.class.php.
References img_help(), img_picto(), img_warning(), and textwithtooltip().
textwithtooltip ($text, $htmltext, $tooltipon = 1, $direction = 0, $img = '', $extracss = '', $notabs = 2, $incbefore = '', $noencodehtmltext = 0, $tooltiptrigger = '', $forcenowrap = 0)
Show a text and picto with tooltip on text or picto.
Can be called by an instancied $form->textwithtooltip or by a static call Form::textwithtooltip
Parameters
string $text Text to show
string $htmltext HTML content of tooltip. Must be HTML/UTF8 encoded.
int $tooltipon 1=tooltip on text, 2=tooltip on image, 3=tooltip sur les 2
int $direction -1=image is before, 0=no image, 1=image is after
string $img Html code for image (use img_xxx() function to get it)
string $extracss Add a CSS style to td tags
int $notabs 0=Include table and tr tags, 1=Do not include table and tr tags, 2=use div, 3=use span
string $incbefore Include code before the text
int $noencodehtmltext Do not encode into html entity the htmltext
string $tooltiptrigger ''=Tooltip on hover, 'abc'=Tooltip on click (abc is a unique key)
int $forcenowrap Force no wrap between text and picto (works with notabs=2 only)
Returns
string Code html du tooltip (texte+picto)
See also
textwithpicto() Use thisfunction if you can. TODO Move this as static as soon as everybody use textwithpicto or ::textwithtooltip
Definition at line 445 of file html.form.class.php.
References dol_escape_htmltag(), and if.
Referenced by textwithpicto(), and top_menu().
The documentation for this class was generated from the following file:
htdocs/core/class/html.form.class.php