Dolibarr: BookKeeping Class Reference
BookKeeping Class Reference
Class to manage Ledger (General Ledger and Subledger)
Public Member Functions
__construct (DoliDB $db)
Constructor.
create (User $user, $notrigger=false)
Create object into database.
getNomUrl ($withpicto=0, $option= '', $notooltip=0, $morecss= '', $save_lastsearch_value=-1)
Return a link to the object card (with optionaly the picto)
createStd (User $user, $notrigger=false, $mode= '')
Create object into database.
fetch ($id, $ref=null, $mode= '')
Load object in memory from the database.
fetchAllByAccount ($sortorder= '', $sortfield= '', $limit=0, $offset=0, array $filter=array(), $filtermode= 'AND')
Load object in memory from the database.
fetchAll ($sortorder= '', $sortfield= '', $limit=0, $offset=0, array $filter=array(), $filtermode= 'AND', $showAlreadyExportMovements=1)
Load object in memory from the database.
fetchAllBalance ($sortorder= '', $sortfield= '', $limit=0, $offset=0, array $filter=array(), $filtermode= 'AND')
Load object in memory from the database.
update (User $user, $notrigger=false, $mode= '')
Update object into database.
updateByMvt ($piece_num= '', $field= '', $value= '', $mode= '')
Update movement.
delete (User $user, $notrigger=false, $mode= '')
Delete object in database.
deleteByImportkey ($importkey)
Delete bookkepping by importkey.
deleteByYearAndJournal ($delyear= '', $journal= '', $mode= '')
Delete bookkepping by year.
deleteMvtNum ($piecenum)
Delete bookkepping by piece number.
createFromClone (User $user, $fromid)
Load an object from its id and create a new one in database.
initAsSpecimen ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchPerMvt ($piecenum, $mode= '')
Load an accounting document into memory from database.
getNextNumMvt ($mode= '')
Return next number movement.
fetchAllPerMvt ($piecenum, $mode= '')
Load all informations of accountancy document.
export_bookkeping ($model= 'ebp')
Export bookkeping.
transformTransaction ($direction=0, $piece_num= '')
Transform transaction.
select_account ($selectid, $htmlname= 'account', $showempty=0, $event=array(), $select_in=0, $select_out=0, $aabase= '')
Return list of accounts with label by chart of accounts.
get_compte_racine ($account=null)
Description of a root accounting account.
get_compte_desc ($account=null)
Description of accounting account.
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0)
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source= 'external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source= 'internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source= '', $code= '')
Delete all links between an object $this and all its contacts.
liste_contact ($statut=-1, $source= 'external', $list=0, $code= '')
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source= 'internal', $order= 'position', $option=0, $activeonly=0, $code= '')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contactid into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table= '', $id=null, $format= '', $id_field= '', $fuser=null, $trigkey= '', $fk_user_field= 'fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source= 'external')
Return list of id of contacts of object.
setProject ($projectid)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id)
Change the payments terms.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder= 'ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix= '')
Update note of element.
update_note_public ($note)
Update public note (kept for backward compatibility)
update_price ($exclspec=0, $roundingadjust= 'none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null)
Add objects linked in llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $clause= 'OR', $alsosametype=1, $orderby= 'sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
updateObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '')
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype= '', $targetid=null, $targettype= '', $rowid= '')
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType= '', $trigkey= '')
Set status of an object.
getCanvas ($id=0, $ref= '')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
display_incoterms ()
Return incoterms informations TODO Use a cache for label get.
getIncotermsForPDF ()
Return incoterms informations for pdf display.
setIncoterms ($id_incoterm, $location)
Define incoterms values of current object.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir= '/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir= '/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafieldsline=0, $defaulttpldir= '/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist= '', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist= '', $defaulttpldir= '/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
addThumbs ($file)
Build thumb Move this into files.lib.php.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($trigger_name, $user)
Call trigger based on this instance.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger= '', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update an extra field value for the current object.
showInputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
showOutputField ($val, $key, $value, $moreparam= '', $keysuffix= '', $keyprefix= '', $morecss= '')
Return HTML string to show a field into a page Code very similar with showOutputField of extra fields.
showOptionals ($extrafields, $mode= 'view', $params=null, $keysuffix= '', $keyprefix= '', $onetrtd=0)
Function to show lines of extrafields with output datas.
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere= '')
Load object in memory from the database.
fetchLinesCommon ($morewhere= '')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
Additional Inherited Members
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref= '', $ref_ext= '')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static commonReplaceThirdparty (DoliDB $db, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
Data Fields inherited from CommonObject
$projet
$note
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
isNull ($info)
Function test if type is null.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare the values to insert.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ()
Function to concat keys of fields.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage Ledger (General Ledger and Subledger)
Definition at line 33 of file bookkeeping.class.php.
Constructor & Destructor Documentation
__construct (DoliDB $db)
Constructor.
Parameters
DoliDb $db Database handler
Definition at line 142 of file bookkeeping.class.php.
References db.
Member Function Documentation
create (User $user, $notrigger = false)
Create object into database.
Parameters
User $user User that creates
bool $notrigger false=launch triggers after, true=disable triggers
Returns
int <0 if KO, Id of created object if OK
Definition at line 154 of file bookkeeping.class.php.
References $resql, db, dol_now(), dol_strlen(), dol_syslog(), and getEntity().
createFromClone (User $user, $fromid)
Load an object from its id and create a new one in database.
Parameters
User $user User making the clone
int $fromid Id of object to clone
Returns
int New id of clone
Definition at line 1415 of file bookkeeping.class.php.
References db, and dol_syslog().
createStd (User $user, $notrigger = false, $mode = '')
Create object into database.
Parameters
User $user User that creates
bool $notrigger false=launch triggers after, true=disable triggers
string $mode Mode
Returns
int <0 if KO, Id of created object if OK
Definition at line 470 of file bookkeeping.class.php.
References $resql, db, dol_now(), dol_strlen(), dol_syslog(), and price2num().
delete (User $user, $notrigger = false, $mode = '')
Delete object in database.
Parameters
User $user User that deletes
bool $notrigger false=launch triggers after, true=disable triggers
string $mode Mode
Returns
int <0 if KO, >0 if OK
Definition at line 1262 of file bookkeeping.class.php.
References $resql, db, and dol_syslog().
deleteByImportkey ($importkey)
Delete bookkepping by importkey.
Parameters
string $importkey Import key
Returns
int Result
Definition at line 1310 of file bookkeeping.class.php.
References $resql, db, and dol_syslog().
deleteByYearAndJournal ($delyear = '', $journal = '', $mode = '')
Delete bookkepping by year.
Parameters
string $delyear Year to delete
string $journal Journal to delete
string $mode Mode
Returns
int <0 if KO, >0 if OK
Definition at line 1340 of file bookkeeping.class.php.
References $resql, db, dol_syslog(), and getEntity().
deleteMvtNum ($piecenum)
Delete bookkepping by piece number.
Parameters
int $piecenum Piecenum to delete
Returns
int Result
Definition at line 1380 of file bookkeeping.class.php.
References $resql, db, dol_syslog(), and getEntity().
export_bookkeping ($model = 'ebp')
Export bookkeping.
Parameters
string $model Model
Returns
int Result
Definition at line 1625 of file bookkeeping.class.php.
References $resql, db, dol_syslog(), and getEntity().
fetch ($id, $ref = null, $mode = '')
Load object in memory from the database.
Parameters
int $id Id object
string $ref Ref
string $mode Mode
Returns
int <0 if KO, 0 if not found, >0 if OK
Definition at line 639 of file bookkeeping.class.php.
References $resql, db, dol_syslog(), and getEntity().
fetchAll ($sortorder = '', $sortfield = '', $limit = 0, $offset = 0, array $filter = array(), $filtermode = 'AND', $showAlreadyExportMovements = 1)
Load object in memory from the database.
Parameters
string $sortorder Sort Order
string $sortfield Sort field
int $limit Offset limit
int $offset Offset limit
array $filter Filter array
string $filtermode Filter mode (AND or OR)
int $showAlreadyExportMovements Show movements when field 'date_export' is not empty (0:No / 1:Yes (Default))
Returns
int <0 if KO, >0 if OK
Definition at line 873 of file bookkeeping.class.php.
References $resql, db, dol_syslog(), getEntity(), and natural_search().
fetchAllBalance ($sortorder = '', $sortfield = '', $limit = 0, $offset = 0, array $filter = array(), $filtermode = 'AND')
Load object in memory from the database.
Parameters
string $sortorder Sort Order
string $sortfield Sort field
int $limit offset limit
int $offset offset limit
array $filter filter array
string $filtermode filter mode (AND or OR)
Returns
int <0 if KO, >0 if OK
Definition at line 1010 of file bookkeeping.class.php.
References $resql, db, dol_syslog(), and getEntity().
fetchAllByAccount ($sortorder = '', $sortfield = '', $limit = 0, $offset = 0, array $filter = array(), $filtermode = 'AND')
Load object in memory from the database.
Parameters
string $sortorder Sort Order
string $sortfield Sort field
int $limit offset limit
int $offset offset limit
array $filter filter array
string $filtermode filter mode (AND or OR)
Returns
int <0 if KO, >=0 if OK
Definition at line 737 of file bookkeeping.class.php.
References $resql, db, dol_syslog(), getEntity(), and natural_search().
fetchAllPerMvt ($piecenum, $mode = '')
Load all informations of accountancy document.
Parameters
int $piecenum Id of line to get
string $mode Mode
Returns
int <0 if KO, >0 if OK
Definition at line 1565 of file bookkeeping.class.php.
References db, dol_syslog(), and getEntity().
fetchPerMvt ($piecenum, $mode = '')
Load an accounting document into memory from database.
Parameters
int $piecenum Accounting document to get
string $mode Mode
Returns
int <0 if KO, >0 if OK
Definition at line 1500 of file bookkeeping.class.php.
References db, dol_syslog(), and getEntity().
get_compte_desc ($account = null)
Description of accounting account.
Parameters
string $account Accounting account
Returns
string Account desc
Definition at line 1893 of file bookkeeping.class.php.
References $resql, db, dol_syslog(), and getEntity().
get_compte_racine ($account = null)
Description of a root accounting account.
Parameters
string $account Accounting account
Returns
string Root account
Definition at line 1852 of file bookkeeping.class.php.
References $resql, db, dol_syslog(), and getEntity().
getNextNumMvt ($mode = '')
Return next number movement.
Parameters
string $mode Mode
Returns
string Next numero to use
Definition at line 1536 of file bookkeeping.class.php.
References db, dol_syslog(), and getEntity().
Referenced by transformTransaction().
getNomUrl ($withpicto = 0, $option = '', $notooltip = 0, $morecss = '', $save_lastsearch_value = -1)
Return a link to the object card (with optionaly the picto)
Parameters
int $withpicto Include picto in link (0=No picto, 1=Include picto into link, 2=Only picto)
string $option On what the link point to ('nolink', ...)
int $notooltip 1=Disable tooltip
string $morecss Add more css on link
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
Returns
string String with URL
Definition at line 411 of file bookkeeping.class.php.
References img_object().
initAsSpecimen ()
Initialise object with example values Id must be 0 if object instance is a specimen.
Returns
void
Definition at line 1463 of file bookkeeping.class.php.
References dol_now().
select_account ($selectid, $htmlname = 'account', $showempty = 0, $event = array(), $select_in = 0, $select_out = 0, $aabase = '')
Return list of accounts with label by chart of accounts.
Parameters
string $selectid Preselected chart of accounts
string $htmlname Name of field in html form
int $showempty Add an empty field
array $event Event options
int $select_in Value is a aa.rowid (0 default) or aa.account_number (1)
int $select_out Set value returned by select 0=rowid (default), 1=account_number
int $aabase Set accounting_account base class to display empty=all or from 1 to 8 will display only account beginning by this number
Returns
string String with HTML select
Definition at line 1786 of file bookkeeping.class.php.
References $resql, ajax_combobox(), db, dol_syslog(), getEntity(), length_accountg(), and Form\selectarray().
transformTransaction ($direction = 0, $piece_num = '')
Transform transaction.
Parameters
number $direction If 0 tmp => real, if 1 real => tmp
string $piece_num Piece num
Returns
int int <0 if KO, >0 if OK
Definition at line 1687 of file bookkeeping.class.php.
References $resql, db, dol_now(), dol_syslog(), and getNextNumMvt().
update (User $user, $notrigger = false, $mode = '')
Update object into database.
Parameters
User $user User that modifies
bool $notrigger false=launch triggers after, true=disable triggers
string $mode Mode
Returns
int <0 if KO, >0 if OK
Definition at line 1095 of file bookkeeping.class.php.
References $resql, db, dol_strlen(), dol_syslog(), and price2num().
updateByMvt ($piece_num = '', $field = '', $value = '', $mode = '')
Update movement.
Parameters
string $piece_num Piece num
string $field Field
string $value Value
string $mode Mode
Returns
number <0 if KO, >0 if OK
Definition at line 1227 of file bookkeeping.class.php.
References $resql, db, and dol_syslog().
The documentation for this class was generated from the following file:
htdocs/accountancy/class/bookkeeping.class.php