Dolibarr: htdocs/core/lib/xcal.lib.php File Reference
xcal.lib.php File Reference
Function to manage calendar files (vcal/ical/...)
Functions
build_calfile ($format, $title, $desc, $events_array, $outputfile)
Build a file from an array of events All input params and data must be encoded in $conf->charset_output.
build_rssfile ($format, $title, $desc, $events_array, $outputfile, $filter= '')
Build a file from an array of events.
format_cal ($format, $string)
Encode for cal export.
calEncode ($line)
Cut string after 75 chars.
quotedPrintEncode ($str, $forcal=0)
Encode into vcal format.
quotedPrintDecode ($str)
Decode vcal format.
Detailed Description
Function to manage calendar files (vcal/ical/...)
Definition in file xcal.lib.php.
Function Documentation
build_calfile ($format, $title, $desc, $events_array, $outputfile)
Build a file from an array of events All input params and data must be encoded in $conf->charset_output.
Parameters
string $format 'vcal' or 'ical'
string $title Title of export
string $desc Description of export
array $events_array Array of events ('eid','startdate','duration','enddate','title','summary','category','email','url','desc','author')
string $outputfile Output file
Returns
int <0 if ko, Nb of events in file if ok
Definition at line 35 of file xcal.lib.php.
References convertSecondToTime(), dol_now(), dol_print_date(), dol_string_nohtmltag(), dol_syslog(), dol_time_plus_duree(), and format_cal().
Referenced by ActionComm\build_exportfile().
build_rssfile ($format, $title, $desc, $events_array, $outputfile, $filter = '')
Build a file from an array of events.
All input data must be encoded in $conf->charset_output
Parameters
string $format 'rss'
string $title Title of export
string $desc Description of export
array $events_array Array of events ('uid','startdate','summary','url','desc','author','category')
string $outputfile Output file
string $filter Filter
Returns
int <0 if ko, Nb of events in file if ok
Definition at line 295 of file xcal.lib.php.
References dol_string_nohtmltag(), and dol_syslog().
Referenced by ActionComm\build_exportfile().
calEncode ($line)
Cut string after 75 chars.
Add CRLF+Space. line must be encoded in UTF-8
Parameters
string $line String to convert
Returns
string String converted
Definition at line 428 of file xcal.lib.php.
References dol_strlen().
Referenced by format_cal().
format_cal ($format, $string)
Encode for cal export.
Parameters
string $format vcal or ical
string $string string to encode
Returns
string string encoded
Definition at line 398 of file xcal.lib.php.
References calEncode(), and quotedPrintEncode().
Referenced by build_calfile().
quotedPrintDecode ($str)
Decode vcal format.
Parameters
string $str String to convert
Returns
string String converted
Definition at line 516 of file xcal.lib.php.
Referenced by ICal\parse().
quotedPrintEncode ($str, $forcal = 0)
Encode into vcal format.
Parameters
string $str String to convert
int $forcal 1=For cal
Returns
string String converted
Definition at line 479 of file xcal.lib.php.
Referenced by format_cal().