Dolibarr: FormCompany Class Reference
FormCompany Class Reference
Class to build HTML component for third parties management Only common components are here.
Public Member Functions
__construct ($db)
Constructor.
typent_array ($mode=0, $filter= '')
Return list of labels (translated) of third parties type.
effectif_array ($mode=0, $filter= '')
Renvoie la liste des types d'effectifs possibles (pas de traduction car nombre)
form_prospect_level ($page, $selected= '', $htmlname= 'prospect_level_id', $empty=0)
Affiche formulaire de selection des modes de reglement.
select_departement ($selected= '', $country_codeid=0, $htmlname= 'state_id')
Returns the drop-down list of departments/provinces/cantons for all countries or for a given country.
select_state ($selected=0, $country_codeid=0, $htmlname= 'state_id')
Returns the drop-down list of departments/provinces/cantons for all countries or for a given country.
select_region ($selected= '', $htmlname= 'region_id')
Retourne la liste deroulante des regions actives dont le pays est actif La cle de la liste est le code (il peut y avoir plusieurs entree pour un code donnee mais dans ce cas, le champ pays et lang differe).
select_civility ($selected= '', $htmlname= 'civility_id', $morecss= 'maxwidth100')
Return combo list with people title.
select_forme_juridique ($selected= '', $country_codeid=0, $filter= '')
Retourne la liste deroulante des formes juridiques tous pays confondus ou pour un pays donne.
select_juridicalstatus ($selected= '', $country_codeid=0, $filter= '', $htmlname= 'forme_juridique_code')
Retourne la liste deroulante des formes juridiques tous pays confondus ou pour un pays donne.
selectCompaniesForNewContact ($object, $var_id, $selected= '', $htmlname= 'newcompany', $limitto= '', $forceid=0, $moreparam= '', $morecss= '')
Output list of third parties.
selectTypeContact ($object, $selected, $htmlname= 'type', $source= 'internal', $sortorder= 'position', $showempty=0, $morecss= '')
Return a select list with types of contacts.
select_ziptown ($selected= '', $htmlname= 'zipcode', $fields= '', $fieldsize=0, $disableautocomplete=0, $moreattrib= '', $morecss= '')
Return a select list with zip codes and their town.
get_input_id_prof ($idprof, $htmlname, $preselected, $country_code, $morecss= 'maxwidth100onsmartphone quatrevingtpercent')
Return HTML string to use as input of professional id into a HTML page (siren, siret, etc...)
select_localtax ($local, $selected, $htmlname)
Return a HTML select with localtax values for thirdparties.
selectProspectCustomerType ($selected, $htmlname= 'client', $htmlidname= 'customerprospect', $typeinput= 'form', $morecss= '')
Return a HTML select for thirdparty type.
Detailed Description
Class to build HTML component for third parties management Only common components are here.
Definition at line 32 of file html.formcompany.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 49 of file html.formcompany.class.php.
References db.
Member Function Documentation
effectif_array ($mode = 0, $filter = '')
Renvoie la liste des types d'effectifs possibles (pas de traduction car nombre)
Parameters
int $mode 0=renvoi id+libelle, 1=renvoi code+libelle
string $filter Add a SQL filter to select
Returns
array Array of types d'effectifs
Definition at line 106 of file html.formcompany.class.php.
References $resql, db, and dol_syslog().
form_prospect_level ($page, $selected = '', $htmlname = 'prospect_level_id', $empty = 0)
Affiche formulaire de selection des modes de reglement.
Parameters
int $page Page
int $selected Id or code preselected
string $htmlname Nom du formulaire select
int $empty Add empty value in list
Returns
void
Definition at line 148 of file html.formcompany.class.php.
References $resql, db, dol_print_error(), dol_syslog(), print, and Form\selectarray().
get_input_id_prof ($idprof, $htmlname, $preselected, $country_code, $morecss = 'maxwidth100onsmartphone quatrevingtpercent')
Return HTML string to use as input of professional id into a HTML page (siren, siret, etc...)
Parameters
int $idprof 1,2,3,4 (Example: 1=siren,2=siret,3=naf,4=rcs/rm)
string $htmlname Name of HTML select
string $preselected Default value to show
string $country_code FR, IT, ...
string $morecss More css
Returns
string HTML string with prof id
Definition at line 810 of file html.formcompany.class.php.
select_civility ($selected = '', $htmlname = 'civility_id', $morecss = 'maxwidth100')
Return combo list with people title.
Parameters
string $selected Civility/Title code preselected
string $htmlname Name of HTML select combo field
string $morecss Add more css on SELECT element
Returns
string String with HTML select
Definition at line 399 of file html.formcompany.class.php.
References $resql, db, dol_print_error(), dol_syslog(), and info_admin().
select_departement ($selected = '', $country_codeid = 0, $htmlname = 'state_id')
Returns the drop-down list of departments/provinces/cantons for all countries or for a given country.
In the case of an all-country list, the display breaks on the country. The key of the list is the code (there can be several entries for a given code but in this case, the country field differs). Thus the links with the departments are done on a department independently of its name.
Parameters
string $selected Code state preselected
int $country_codeid 0=list for all countries, otherwise country code or country rowid to show
string $htmlname Id of department
Returns
void
Definition at line 201 of file html.formcompany.class.php.
References print, and select_state().
select_forme_juridique ($selected = '', $country_codeid = 0, $filter = '')
Retourne la liste deroulante des formes juridiques tous pays confondus ou pour un pays donne.
Dans le cas d'une liste tous pays confondu, on affiche une rupture sur le pays.
Parameters
string $selected Code forme juridique a pre-selectionne
mixed $country_codeid 0=liste tous pays confondus, sinon code du pays a afficher
string $filter Add a SQL filter on list
Returns
void
Deprecated:
Use print xxx->select_juridicalstatus instead
See also
select_juridicalstatus()
Definition at line 460 of file html.formcompany.class.php.
References print, and select_juridicalstatus().
select_juridicalstatus ($selected = '', $country_codeid = 0, $filter = '', $htmlname = 'forme_juridique_code')
Retourne la liste deroulante des formes juridiques tous pays confondus ou pour un pays donne.
Dans le cas d'une liste tous pays confondu, on affiche une rupture sur le pays
Parameters
string $selected Preselected code of juridical type
int $country_codeid 0=list for all countries, otherwise list only country requested
string $filter Add a SQL filter on list
string $htmlname HTML name of select
Returns
string String with HTML select
Definition at line 477 of file html.formcompany.class.php.
References $resql, ajax_combobox(), db, dol_print_error(), dol_sort_array(), and dol_syslog().
Referenced by select_forme_juridique().
select_localtax ($local, $selected, $htmlname)
Return a HTML select with localtax values for thirdparties.
Parameters
int $local LocalTax
int $selected Preselected value
string $htmlname HTML select name
Returns
void
Definition at line 860 of file html.formcompany.class.php.
References db, get_localtax_by_third(), and print.
select_region ($selected = '', $htmlname = 'region_id')
Retourne la liste deroulante des regions actives dont le pays est actif La cle de la liste est le code (il peut y avoir plusieurs entree pour un code donnee mais dans ce cas, le champ pays et lang differe).
Ainsi les liens avec les regions se font sur une region independemment de son name.
Parameters
string $selected Preselected value
string $htmlname Name of HTML select field
Returns
void
Definition at line 333 of file html.formcompany.class.php.
References $resql, db, dol_print_error(), dol_syslog(), and print.
select_state ($selected = 0, $country_codeid = 0, $htmlname = 'state_id')
Returns the drop-down list of departments/provinces/cantons for all countries or for a given country.
In the case of an all-country list, the display breaks on the country. The key of the list is the code (there can be several entries for a given code but in this case, the country field differs). Thus the links with the departments are done on a department independently of its name.
Parameters
int $selected Code state preselected (mus be state id)
integer $country_codeid Country code or id: 0=list for all countries, otherwise country code or country rowid to show
string $htmlname Id of department. If '', we want only the string with <option>
Returns
string String with HTML select
See also
select_country()
Definition at line 220 of file html.formcompany.class.php.
References ajax_combobox(), db, dol_print_error(), dol_syslog(), and if.
Referenced by select_departement().
select_ziptown ($selected = '', $htmlname = 'zipcode', $fields = '', $fieldsize = 0, $disableautocomplete = 0, $moreattrib = '', $morecss = '')
Return a select list with zip codes and their town.
Parameters
string $selected Preselected value
string $htmlname HTML select name
string $fields Fields
int $fieldsize Field size
int $disableautocomplete 1 To disable ajax autocomplete features (browser autocomplete may still occurs)
string $moreattrib Add more attribute on HTML input field
string $morecss More css
Returns
string
Definition at line 779 of file html.formcompany.class.php.
References ajax_multiautocompleter().
selectCompaniesForNewContact ($object, $var_id, $selected = '', $htmlname = 'newcompany', $limitto = '', $forceid = 0, $moreparam = '', $morecss = '')
Output list of third parties.
Parameters
object $object Object we try to find contacts
string $var_id Name of id field
string $selected Pre-selected third party
string $htmlname Name of HTML form
array $limitto Disable answers that are not id in this array list
int $forceid This is to force another object id than object->id
string $moreparam String with more param to add into url when noajax search is used.
string $morecss More CSS on select component
Returns
int The selected third party ID
Definition at line 582 of file html.formcompany.class.php.
References $resql, ajax_autocompleter(), ajax_combobox(), db, dol_buildpath(), dol_print_error(), if, and print.
selectProspectCustomerType ($selected, $htmlname = 'client', $htmlidname = 'customerprospect', $typeinput = 'form', $morecss = '')
Return a HTML select for thirdparty type.
Parameters
int $selected selected value
string $htmlname HTML select name
string $htmlidname HTML select id
string $typeinput HTML output
string $morecss More css
Returns
string HTML string
Definition at line 904 of file html.formcompany.class.php.
selectTypeContact ($object, $selected, $htmlname = 'type', $source = 'internal', $sortorder = 'position', $showempty = 0, $morecss = '')
Return a select list with types of contacts.
Parameters
object $object Object to use to find type of contact
string $selected Default selected value
string $htmlname HTML select name
string $source Source ('internal' or 'external')
string $sortorder Sort criteria ('position', 'code', ...)
int $showempty 1=Add en empty line
string $morecss Add more css to select component
Returns
void
Definition at line 742 of file html.formcompany.class.php.
References ajax_combobox(), if, and print.
typent_array ($mode = 0, $filter = '')
Return list of labels (translated) of third parties type.
Parameters
int $mode 0=Return id+label, 1=Return code+label
string $filter Add a SQL filter to select
Returns
array Array of types
Definition at line 63 of file html.formcompany.class.php.
References $resql, db, and dol_syslog().
The documentation for this class was generated from the following file:
htdocs/core/class/html.formcompany.class.php