Dolibarr: mailing_contacts1 Class Reference
mailing_contacts1 Class Reference
Class to offer a selector of emailing targets from contacts.
Public Member Functions
__construct ($db)
Constructor.
getSqlArrayForStats ()
On the main mailing area, there is a box with statistics.
getNbOfRecipients ($sql= '')
Return here number of distinct emails returned by your selector.
formFilter ()
Affiche formulaire de filtre qui apparait dans page de selection des destinataires de mailings.
url ($id)
Renvoie url lien vers fiche de la source du destinataire du mailing.
add_to_target ($mailing_id)
Ajoute destinataires dans table des cibles.
Public Member Functions inherited from MailingTargets
__construct ($db)
Constructor.
getDesc ()
Return description of email selector.
getNbOfRecords ()
Return number of records for email selector.
getNbOfRecipients ($sql)
Retourne nombre de destinataires.
formFilter ()
Affiche formulaire de filtre qui apparait dans page de selection des destinataires de mailings.
update_nb ($mailing_id)
Met a jour nombre de destinataires.
add_to_target ($mailing_id, $cibles)
Ajoute destinataires dans table des cibles.
clear_target ($mailing_id)
Supprime tous les destinataires de la table des cibles.
Detailed Description
Class to offer a selector of emailing targets from contacts.
Definition at line 33 of file contacts1.modules.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 53 of file contacts1.modules.php.
References db.
Member Function Documentation
add_to_target ($mailing_id)
Ajoute destinataires dans table des cibles.
Parameters
int $mailing_id Id of emailing
Returns
int <0 si erreur, nb ajout si ok
Definition at line 336 of file contacts1.modules.php.
References $resql, db, dol_print_error(), dol_syslog(), GETPOST(), and url().
formFilter ()
Affiche formulaire de filtre qui apparait dans page de selection des destinataires de mailings.
Returns
string Retourne zone select
Definition at line 116 of file contacts1.modules.php.
References $resql, db, dol_escape_htmltag(), and dol_print_error().
getNbOfRecipients ($sql = '')
Return here number of distinct emails returned by your selector.
For example if this selector is used to extract 500 different emails from a text file, this function must return 500.
Parameters
string $sql Requete sql de comptage
Returns
int
Definition at line 94 of file contacts1.modules.php.
getSqlArrayForStats ()
On the main mailing area, there is a box with statistics.
If you want to add a line in this report you must provide an array of SQL request that returns two field: One called "label", One called "nb".
Returns
string[] Array with SQL requests
Definition at line 67 of file contacts1.modules.php.
url ($id)
Renvoie url lien vers fiche de la source du destinataire du mailing.
Parameters
int $id ID
Returns
string Url lien
Definition at line 323 of file contacts1.modules.php.
References img_object().
Referenced by add_to_target().
The documentation for this class was generated from the following file:
htdocs/core/modules/mailings/contacts1.modules.php