Dolibarr: CommonDocGenerator Class Reference
CommonDocGenerator Class Reference
Parent class for documents generators.
Public Member Functions
__construct ($db)
Constructor.
get_substitutionarray_user ($user, $outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_mysoc ($mysoc, $outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_thirdparty ($object, $outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_contact ($object, $outputlangs, $array_key= 'object')
Define array with couple subtitution key => subtitution value.
get_substitutionarray_other ($outputlangs)
Define array with couple subtitution key => subtitution value.
get_substitutionarray_object ($object, $outputlangs, $array_key= 'object')
Define array with couple substitution key => substitution value.
get_substitutionarray_lines ($line, $outputlangs)
Define array with couple substitution key => substitution value.
get_substitutionarray_shipment ($object, $outputlangs, $array_key= 'object')
Define array with couple substitution key => substitution value.
get_substitutionarray_shipment_lines ($line, $outputlangs)
Define array with couple substitution key => substitution value.
get_substitutionarray_each_var_object (&$object, $outputlangs, $recursive=true)
Define array with couple subtitution key => subtitution value.
fill_substitutionarray_with_extrafields ($object, $array_to_fill, $extrafields, $array_key, $outputlangs)
Fill array with couple extrafield key => extrafield value.
printRect ($pdf, $x, $y, $l, $h, $hidetop=0, $hidebottom=0)
Rect pdf.
columnSort ($a, $b)
uasort callback function to Sort colums fields
prepareArrayColumnField ($object, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0)
Prepare Array Column Field.
getColumnContentWidth ($colKey)
get column content width from column key
getColumnContentXStart ($colKey)
get column content X (abscissa) left position from column key
getColumnRank ($colKey)
get column position rank from column key
insertNewColumnDef ($newColKey, $defArray, $targetCol=false, $insertAfterTarget=false)
get column position rank from column key
printStdColumnContent ($pdf, &$curY, $colKey, $columnText= '')
print standard column content
getColumnStatus ($colKey)
get column status from column key
pdfTabTitles (&$pdf, $tab_top, $tab_height, $outputlangs, $hidetop=0)
Print standard column content.
Detailed Description
Parent class for documents generators.
Definition at line 35 of file commondocgenerator.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 58 of file commondocgenerator.class.php.
References db.
Member Function Documentation
columnSort ($a, $b)
uasort callback function to Sort colums fields
Parameters
array $a PDF lines array fields configs
array $b PDF lines array fields configs
Returns
int Return compare result
Definition at line 859 of file commondocgenerator.class.php.
fill_substitutionarray_with_extrafields ($object, $array_to_fill, $extrafields, $array_key, $outputlangs)
Fill array with couple extrafield key => extrafield value.
Parameters
Object $object Object with extrafields (must have $object->array_options filled)
array $array_to_fill Substitution array
Extrafields $extrafields Extrafields object
string $array_key Prefix for name of the keys into returned array
Translate $outputlangs Lang object to use for output
Returns
array Substitution array
Definition at line 756 of file commondocgenerator.class.php.
References db, dol_include_once(), dol_print_date(), price(), and price2num().
Referenced by get_substitutionarray_lines(), doc_generic_project_odt\get_substitutionarray_object(), doc_generic_task_odt\get_substitutionarray_object(), get_substitutionarray_object(), get_substitutionarray_shipment(), get_substitutionarray_shipment_lines(), and doc_generic_project_odt\get_substitutionarray_tasks().
get_substitutionarray_contact ($object, $outputlangs, $array_key = 'object')
Define array with couple subtitution key => subtitution value.
Parameters
Contact $object contact
Translate $outputlangs object for output
array $array_key Name of the key for return array
Returns
array Array of substitution key->code
Definition at line 252 of file commondocgenerator.class.php.
References db, getState(), and price().
Referenced by doc_generic_odt\write_file(), doc_generic_contract_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_order_odt\write_file(), doc_generic_shipment_odt\write_file(), doc_generic_user_odt\write_file(), doc_generic_product_odt\write_file(), doc_generic_stock_odt\write_file(), doc_generic_usergroup_odt\write_file(), doc_generic_proposal_odt\write_file(), and doc_generic_project_odt\write_file().
get_substitutionarray_each_var_object (& $object, $outputlangs, $recursive = true)
Define array with couple subtitution key => subtitution value.
Parameters
Object $object Dolibarr Object
Translate $outputlangs Language object for output
boolean $recursive Want to fetch child array or child object
Returns
array Array of substitution key->code
Definition at line 725 of file commondocgenerator.class.php.
Referenced by doc_generic_contract_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_order_odt\write_file(), doc_generic_stock_odt\write_file(), doc_generic_product_odt\write_file(), doc_generic_usergroup_odt\write_file(), doc_generic_proposal_odt\write_file(), doc_generic_task_odt\write_file(), and doc_generic_project_odt\write_file().
get_substitutionarray_lines ($line, $outputlangs)
Define array with couple substitution key => substitution value.
Parameters
Object $line Object line
Translate $outputlangs Lang object to use for output
Returns
array Return a substitution array
Definition at line 529 of file commondocgenerator.class.php.
References db, doc_getlinedesc(), dol_print_date(), fill_substitutionarray_with_extrafields(), price(), price2num(), and vatrate().
Referenced by doc_generic_contract_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_order_odt\write_file(), doc_generic_proposal_odt\write_file(), and doc_generic_supplier_proposal_odt\write_file().
get_substitutionarray_mysoc ($mysoc, $outputlangs)
Define array with couple subtitution key => subtitution value.
Parameters
Societe $mysoc Object thirdparty
Translate $outputlangs Language object for output
Returns
array Array of substitution key->code
Definition at line 110 of file commondocgenerator.class.php.
References getFormeJuridiqueLabel(), and getState().
Referenced by doc_generic_odt\write_file(), doc_generic_contract_odt\write_file(), doc_generic_reception_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_order_odt\write_file(), doc_generic_shipment_odt\write_file(), doc_generic_user_odt\write_file(), doc_generic_stock_odt\write_file(), doc_generic_product_odt\write_file(), doc_generic_usergroup_odt\write_file(), doc_generic_proposal_odt\write_file(), doc_generic_supplier_proposal_odt\write_file(), doc_generic_task_odt\write_file(), and doc_generic_project_odt\write_file().
get_substitutionarray_object ($object, $outputlangs, $array_key = 'object')
Define array with couple substitution key => substitution value.
Parameters
Object $object Main object to use as data source
Translate $outputlangs Lang object to use for output
string $array_key Name of the key for return array
Returns
array Array of substitution
Definition at line 364 of file commondocgenerator.class.php.
References db, dol_print_date(), fill_substitutionarray_with_extrafields(), price(), price2num(), and vatrate().
Referenced by doc_generic_contract_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_order_odt\write_file(), doc_generic_proposal_odt\write_file(), and doc_generic_supplier_proposal_odt\write_file().
get_substitutionarray_other ($outputlangs)
Define array with couple subtitution key => subtitution value.
Parameters
Translate $outputlangs Language object for output
Returns
array Array of substitution key->code
Definition at line 324 of file commondocgenerator.class.php.
References dol_now(), and dol_print_date().
Referenced by doc_generic_odt\write_file(), doc_generic_contract_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_order_odt\write_file(), doc_generic_user_odt\write_file(), doc_generic_stock_odt\write_file(), doc_generic_product_odt\write_file(), doc_generic_usergroup_odt\write_file(), doc_generic_proposal_odt\write_file(), doc_generic_supplier_proposal_odt\write_file(), doc_generic_task_odt\write_file(), and doc_generic_project_odt\write_file().
get_substitutionarray_shipment ($object, $outputlangs, $array_key = 'object')
Define array with couple substitution key => substitution value.
Parameters
Expedition $object Main object to use as data source
Translate $outputlangs Lang object to use for output
array $array_key Name of the key for return array
Returns
array Array of substitution
Definition at line 613 of file commondocgenerator.class.php.
References db, dol_include_once(), dol_print_date(), fill_substitutionarray_with_extrafields(), measuring_units_string(), and price().
Referenced by doc_generic_shipment_odt\write_file().
get_substitutionarray_shipment_lines ($line, $outputlangs)
Define array with couple substitution key => substitution value.
Parameters
ExpeditionLigne $line Object line
Translate $outputlangs Lang object to use for output
Returns
array Substitution array
Definition at line 675 of file commondocgenerator.class.php.
References db, doc_getlinedesc(), dol_include_once(), fill_substitutionarray_with_extrafields(), measuring_units_string(), price(), and vatrate().
Referenced by doc_generic_shipment_odt\write_file().
get_substitutionarray_thirdparty ($object, $outputlangs)
Define array with couple subtitution key => subtitution value.
Parameters
Object $object Object
Translate $outputlangs Language object for output
Returns
array Array of substitution key->code
Definition at line 170 of file commondocgenerator.class.php.
References db, getState(), and price().
Referenced by doc_generic_odt\write_file(), doc_generic_contract_odt\write_file(), doc_generic_reception_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_order_odt\write_file(), doc_generic_shipment_odt\write_file(), doc_generic_user_odt\write_file(), doc_generic_stock_odt\write_file(), doc_generic_product_odt\write_file(), doc_generic_usergroup_odt\write_file(), doc_generic_proposal_odt\write_file(), doc_generic_supplier_proposal_odt\write_file(), doc_generic_task_odt\write_file(), and doc_generic_project_odt\write_file().
get_substitutionarray_user ($user, $outputlangs)
Define array with couple subtitution key => subtitution value.
Parameters
User $user User
Translate $outputlangs Language object for output
Returns
array Array of substitution key->code
Definition at line 72 of file commondocgenerator.class.php.
References get_exdir().
Referenced by doc_generic_odt\write_file(), doc_generic_contract_odt\write_file(), doc_generic_reception_odt\write_file(), doc_generic_invoice_odt\write_file(), doc_generic_order_odt\write_file(), doc_generic_shipment_odt\write_file(), doc_generic_user_odt\write_file(), doc_generic_stock_odt\write_file(), doc_generic_product_odt\write_file(), doc_generic_usergroup_odt\write_file(), doc_generic_proposal_odt\write_file(), doc_generic_supplier_proposal_odt\write_file(), doc_generic_task_odt\write_file(), and doc_generic_project_odt\write_file().
getColumnContentWidth ($colKey)
get column content width from column key
Parameters
string $colKey the column key
Returns
float width in mm
Definition at line 955 of file commondocgenerator.class.php.
Referenced by printStdColumnContent(), pdf_espadon\write_file(), pdf_cyan\write_file(), pdf_eratosthene\write_file(), and pdf_sponge\write_file().
getColumnContentXStart ($colKey)
get column content X (abscissa) left position from column key
Parameters
string $colKey the column key
Returns
float X position in mm
Definition at line 968 of file commondocgenerator.class.php.
Referenced by printStdColumnContent(), pdf_espadon\write_file(), pdf_cyan\write_file(), pdf_eratosthene\write_file(), and pdf_sponge\write_file().
getColumnRank ($colKey)
get column position rank from column key
Parameters
string $colKey the column key
Returns
int rank on success and -1 on error
Definition at line 980 of file commondocgenerator.class.php.
Referenced by insertNewColumnDef().
getColumnStatus ($colKey)
get column status from column key
Parameters
string $colKey the column key
Returns
float width in mm
Definition at line 1065 of file commondocgenerator.class.php.
Referenced by pdf_espadon\_tableau_tot(), pdfTabTitles(), prepareArrayColumnField(), pdf_espadon\write_file(), pdf_cyan\write_file(), pdf_eratosthene\write_file(), and pdf_sponge\write_file().
insertNewColumnDef ($newColKey, $defArray, $targetCol = false, $insertAfterTarget = false)
get column position rank from column key
Parameters
string $newColKey the new column key
array $defArray a single column definition array
string $targetCol target column used to place the new column beside
bool $insertAfterTarget insert before or after target column ?
Returns
int new rank on success and -1 on error
Definition at line 995 of file commondocgenerator.class.php.
References getColumnRank().
pdfTabTitles (& $pdf, $tab_top, $tab_height, $outputlangs, $hidetop = 0)
Print standard column content.
Parameters
PDF $pdf Pdf object
float $tab_top Tab top position
float $tab_height Default tab height
Translate $outputlangs Output language
int $hidetop Hide top
Returns
float Height of col tab titles
Definition at line 1083 of file commondocgenerator.class.php.
References getColumnStatus(), and setEventMessages().
Referenced by pdf_espadon\_tableau(), pdf_eratosthene\_tableau(), pdf_cyan\_tableau(), pdf_sponge\_tableau(), pdf_espadon\write_file(), pdf_cyan\write_file(), pdf_eratosthene\write_file(), and pdf_sponge\write_file().
prepareArrayColumnField ($object, $outputlangs, $hidedetails = 0, $hidedesc = 0, $hideref = 0)
Prepare Array Column Field.
Parameters
object $object common object
Translate $outputlangs langs
int $hidedetails Do not show line details
int $hidedesc Do not show desc
int $hideref Do not show ref
Returns
null
Definition at line 879 of file commondocgenerator.class.php.
References getColumnStatus().
Referenced by pdf_espadon\write_file(), pdf_cyan\write_file(), pdf_eratosthene\write_file(), and pdf_sponge\write_file().
printRect ($pdf, $x, $y, $l, $h, $hidetop = 0, $hidebottom = 0)
Rect pdf.
Parameters
TCPDF $pdf Object PDF
float $x Abscissa of first point
float $y Ordinate of first point
float $l ??
float $h ??
int $hidetop 1=Hide top bar of array and title, 0=Hide nothing, -1=Hide only title
int $hidebottom Hide bottom
Returns
void
Definition at line 843 of file commondocgenerator.class.php.
Referenced by pdf_soleil\_tableau(), pdf_strato\_tableau(), pdf_standard\_tableau(), pdf_typhon\_tableau(), pdf_squille\_tableau(), pdf_espadon\_tableau(), pdf_rouget\_tableau(), pdf_canelle\_tableau(), pdf_muscadet\_tableau(), pdf_cornas\_tableau(), pdf_einstein\_tableau(), pdf_aurore\_tableau(), pdf_eratosthene\_tableau(), pdf_azur\_tableau(), pdf_cyan\_tableau(), pdf_crabe\_tableau(), and pdf_sponge\_tableau().
printStdColumnContent ($pdf, & $curY, $colKey, $columnText = '')
print standard column content
Parameters
PDF $pdf pdf object
float $curY curent Y position
string $colKey the column key
string $columnText column text
Returns
int new rank on success and -1 on error
Definition at line 1038 of file commondocgenerator.class.php.
References getColumnContentWidth(), getColumnContentXStart(), and setEventMessages().
Referenced by pdf_espadon\_tableau_tot(), pdf_espadon\write_file(), pdf_cyan\write_file(), pdf_eratosthene\write_file(), and pdf_sponge\write_file().
The documentation for this class was generated from the following file:
htdocs/core/class/commondocgenerator.class.php