Dolibarr: mod_commande_marbre Class Reference
mod_commande_marbre Class Reference
Class to manage customer order numbering rules Marbre.
Public Member Functions
info ()
Return description of numbering module.
getExample ()
Renvoi un exemple de numerotation.
canBeActivated ()
Test si les numeros deje en vigueur dans la base ne provoquent pas de de conflits qui empechera cette numerotation de fonctionner.
getNextValue ($objsoc, $object)
Return next free value.
commande_get_num ($objsoc, $objforref)
Return next free value.
Public Member Functions inherited from ModeleNumRefCommandes
isEnabled ()
Return if a module can be used or not.
info ()
Renvoie la description par defaut du modele de numerotation.
getExample ()
Renvoie un exemple de numerotation.
canBeActivated ()
Test si les numeros deja en vigueur dans la base ne provoquent pas de conflits qui empecheraient cette numerotation de fonctionner.
getNextValue ($objsoc, $object)
Renvoie prochaine valeur attribuee.
getVersion ()
Renvoie version du module numerotation.
Detailed Description
Class to manage customer order numbering rules Marbre.
Definition at line 30 of file mod_commande_marbre.php.
Member Function Documentation
canBeActivated ()
Test si les numeros deje en vigueur dans la base ne provoquent pas de de conflits qui empechera cette numerotation de fonctionner.
Returns
boolean false si conflit, true si ok
Definition at line 80 of file mod_commande_marbre.php.
References $resql.
commande_get_num ($objsoc, $objforref)
Return next free value.
Parameters
Societe $objsoc Object third party
string $objforref Object for number to search
Returns
string Next free value
Definition at line 159 of file mod_commande_marbre.php.
References getNextValue().
getExample ()
Renvoi un exemple de numerotation.
Returns
string Example
Definition at line 68 of file mod_commande_marbre.php.
getNextValue ($objsoc, $object)
Return next free value.
Parameters
Societe $objsoc Object thirdparty
Object $object Object we need next value for
Returns
string Value if KO, <0 if KO
Definition at line 115 of file mod_commande_marbre.php.
References $resql, and dol_syslog().
Referenced by commande_get_num().
info ()
Return description of numbering module.
Returns
string Text with description
Definition at line 56 of file mod_commande_marbre.php.
The documentation for this class was generated from the following file:
htdocs/core/modules/commande/mod_commande_marbre.php