Dolibarr: Setup Class Reference
Setup Class Reference
Public Member Functions
__construct ()
Constructor.
getPaymentTypes ($sortfield="code", $sortorder= 'ASC', $limit=100, $page=0, $active=1, $sqlfilters= '')
Get the list of payments types.
getListOfCountries ($sortfield="code", $sortorder= 'ASC', $limit=100, $page=0, $filter= '', $lang= '', $sqlfilters= '')
Get the list of countries.
getCountryByID ($id, $lang= '')
Get country by ID.
getAvailability ($sortfield="code", $sortorder= 'ASC', $limit=100, $page=0, $active=1, $sqlfilters= '')
Get the list of delivery times.
getListOfEventTypes ($sortfield="code", $sortorder= 'ASC', $limit=100, $page=0, $type= '', $module= '', $active=1, $sqlfilters= '')
Get the list of events types.
getListOfCivilities ($sortfield="code", $sortorder= 'ASC', $limit=100, $page=0, $module= '', $active=1, $sqlfilters= '')
Get the list of civilities.
getListOfCurrencies ($multicurrency=0, $sortfield="code_iso", $sortorder= 'ASC', $limit=100, $page=0, $active=1, $sqlfilters= '')
Get the list of currencies.
getListOfExtrafields ($sortfield="t.pos", $sortorder= 'ASC', $type= '', $sqlfilters= '')
Get the list of extra fields.
getListOfTowns ($sortfield="zip,town", $sortorder= 'ASC', $limit=100, $page=0, $zipcode= '', $town= '', $active=1, $sqlfilters= '')
Get the list of towns.
getPaymentTerms ($sortfield="sortorder", $sortorder= 'ASC', $limit=100, $page=0, $active=1, $sqlfilters= '')
Get the list of payments terms.
getShippingModes ($limit=100, $page=0, $active=1, $sqlfilters= '')
Get the list of shipping methods.
getListOfMeasuringUnits ($sortfield="rowid", $sortorder= 'ASC', $limit=100, $page=0, $active=1, $sqlfilters= '')
Get the list of measuring units.
getTicketsCategories ($sortfield="code", $sortorder= 'ASC', $limit=100, $page=0, $active=1, $sqlfilters= '')
Get the list of tickets categories.
getTicketsSeverities ($sortfield="code", $sortorder= 'ASC', $limit=100, $page=0, $active=1, $sqlfilters= '')
Get the list of tickets severity.
getTicketsTypes ($sortfield="code", $sortorder= 'ASC', $limit=100, $page=0, $active=1, $sqlfilters= '')
Get the list of tickets types.
getCheckIntegrity ($target)
Do a test of integrity for files and setup.
Public Member Functions inherited from DolibarrApi
__construct ($db, $cachedir= '', $refreshCache=false)
Constructor.
Protected Member Functions
_cleanObjectDatas ($object)
Clean sensible object datas.
Protected Member Functions inherited from DolibarrApi
_cleanObjectDatas ($object)
Executed method when API is called without parameter.
_checkFilters ($sqlfilters)
Return if a $sqlfilters parameter is valid.
Private Member Functions
translateLabel ($country, $lang)
Translate the name of the country to the given language.
Additional Inherited Members
Static Protected Member Functions inherited from DolibarrApi
static _checkAccessToResource ($resource, $resource_id=0, $dbtablename= '', $feature2= '', $dbt_keyfield= 'fk_soc', $dbt_select= 'rowid')
Check user access to a resource.
static _forge_criteria_callback ($matches)
Function to forge a SQL criteria.
Detailed Description
Definition at line 35 of file api_setup.class.php.
Member Function Documentation
_cleanObjectDatas ($object) protected
Clean sensible object datas.
Parameters
object $object Object to clean
Returns
array Array of cleaned object properties
Definition at line 284 of file api_setup.class.php.
Referenced by getCountryByID(), and getListOfCountries().
getAvailability ($sortfield = "code", $sortorder = 'ASC', $limit = 100, $page = 0, $active = 1, $sqlfilters = '')
Get the list of delivery times.
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Number of items per page
int $page Page number { 0}
int $active Delivery times is active or not { 0} { 1}
string $sqlfilters SQL criteria to filter with.
GET dictionary/availability
Returns
array [List of availability]
Exceptions
400 RestException
200 OK
Definition at line 232 of file api_setup.class.php.
References DolibarrApi\_checkFilters(), and db.
getCheckIntegrity ($target)
Do a test of integrity for files and setup.
Parameters
string $target Can be 'local' or 'default' or Url of the signatures file to use for the test. Must be reachable by the tested Dolibarr.
Returns
Result of file and setup integrity check
GET checkintegrity
Exceptions
RestException
Definition at line 1035 of file api_setup.class.php.
References dol_dir_list(), dol_filemtime(), dol_filesize(), dol_is_file(), dol_sort_array(), getFilesUpdated(), GETPOST(), getURLContent(), if, and load_fiche_titre().
getCountryByID ($id, $lang = '')
Get country by ID.
Parameters
int $id ID of country
string $lang Code of the language the name of the country must be translated to
Returns
array Array of cleaned object properties
GET dictionary/countries/{id}
Exceptions
RestException
Definition at line 199 of file api_setup.class.php.
References _cleanObjectDatas(), db, and translateLabel().
getListOfCivilities ($sortfield = "code", $sortorder = 'ASC', $limit = 100, $page = 0, $module = '', $active = 1, $sqlfilters = '')
Get the list of civilities.
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Number of items per page
int $page Page number (starting from zero)
string $module To filter on module events
int $active Payment term is active or not { 0} { 1}
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.code:like:'A%') and (t.active:>=:0)"
Returns
List of events types
GET dictionary/civilities
Exceptions
RestException
Definition at line 403 of file api_setup.class.php.
References DolibarrApi\_checkFilters(), and db.
getListOfCountries ($sortfield = "code", $sortorder = 'ASC', $limit = 100, $page = 0, $filter = '', $lang = '', $sqlfilters = '')
Get the list of countries.
The names of the countries will be translated to the given language if the $lang parameter is provided. The value of $lang must be a language code supported by Dolibarr, for example 'en_US' or 'fr_FR'. The returned list is sorted by country ID.
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Number of items per page
int $page Page number (starting from zero)
string $filter To filter the countries by name
string $lang Code of the language the label of the countries must be translated to
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.code:like:'A%') and (t.active:>=:0)"
Returns
array List of countries
GET dictionary/countries
Exceptions
RestException
Definition at line 132 of file api_setup.class.php.
References DolibarrApi\_checkFilters(), _cleanObjectDatas(), db, and translateLabel().
getListOfCurrencies ($multicurrency = 0, $sortfield = "code_iso", $sortorder = 'ASC', $limit = 100, $page = 0, $active = 1, $sqlfilters = '')
Get the list of currencies.
Parameters
int $multicurrency Multicurrency rates (0: no multicurrency, 1: last rate, 2: all rates) { 0} { 2}
string $sortfield Sort field
string $sortorder Sort order
int $limit Number of items per page
int $page Page number (starting from zero)
int $active Payment term is active or not { 0} { 1}
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.code:like:'A%') and (t.active:>=:0)"
Returns
List of events types
GET dictionary/currencies
Exceptions
RestException
Definition at line 465 of file api_setup.class.php.
References DolibarrApi\_checkFilters(), and db.
getListOfEventTypes ($sortfield = "code", $sortorder = 'ASC', $limit = 100, $page = 0, $type = '', $module = '', $active = 1, $sqlfilters = '')
Get the list of events types.
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Number of items per page
int $page Page number (starting from zero)
string $type To filter on type of event
string $module To filter on module events
int $active Payment term is active or not { 0} { 1}
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.code:like:'A%') and (t.active:>=:0)"
Returns
List of events types
GET dictionary/event_types
Exceptions
RestException
Definition at line 340 of file api_setup.class.php.
References DolibarrApi\_checkFilters(), and db.
getListOfExtrafields ($sortfield = "t.pos", $sortorder = 'ASC', $type = '', $sqlfilters = '')
Get the list of extra fields.
Parameters
string $sortfield Sort field
string $sortorder Sort order
string $type Type of element ('adherent', 'commande', 'thirdparty', 'facture', 'propal', 'product', ...)
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.label:like:'SO-%')"
Returns
List of extra fields
GET extrafields
Exceptions
RestException
Definition at line 532 of file api_setup.class.php.
References $resql, DolibarrApi\_checkFilters(), and db.
getListOfMeasuringUnits ($sortfield = "rowid", $sortorder = 'ASC', $limit = 100, $page = 0, $active = 1, $sqlfilters = '')
Get the list of measuring units.
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Number of items per page
int $page Page number (starting from zero)
int $active Payment term is active or not { 0} { 1}
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.code:like:'A%') and (t.active:>=:0)"
Returns
List of events types
GET dictionary/units
Exceptions
RestException
Definition at line 797 of file api_setup.class.php.
References DolibarrApi\_checkFilters(), and db.
getListOfTowns ($sortfield = "zip,town", $sortorder = 'ASC', $limit = 100, $page = 0, $zipcode = '', $town = '', $active = 1, $sqlfilters = '')
Get the list of towns.
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Number of items per page
int $page Page number (starting from zero)
string $zipcode To filter on zipcode
string $town To filter on city name
int $active Payment term is active or not { 0} { 1}
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.code:like:'A%') and (t.active:>=:0)"
Returns
List of towns
GET dictionary/towns
Exceptions
RestException
Definition at line 611 of file api_setup.class.php.
References DolibarrApi\_checkFilters(), and db.
getPaymentTerms ($sortfield = "sortorder", $sortorder = 'ASC', $limit = 100, $page = 0, $active = 1, $sqlfilters = '')
Get the list of payments terms.
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Number of items per page
int $page Page number { 0}
int $active Payment term is active or not { 0} { 1}
string $sqlfilters SQL criteria to filter. Syntax example "(t.code:=:'CHQ')"
GET dictionary/payment_terms
Returns
array List of payment terms
Exceptions
400 RestException
200 OK
Definition at line 675 of file api_setup.class.php.
References DolibarrApi\_checkFilters(), and db.
getPaymentTypes ($sortfield = "code", $sortorder = 'ASC', $limit = 100, $page = 0, $active = 1, $sqlfilters = '')
Get the list of payments types.
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Number of items per page
int $page Page number { 0}
int $active Payment type is active or not { 0} { 1}
string $sqlfilters SQL criteria to filter with. Syntax example "(t.code:=:'CHQ')"
GET dictionary/payment_types
Returns
array [List of payment types]
Exceptions
400 RestException
200 OK
Definition at line 65 of file api_setup.class.php.
References DolibarrApi\_checkFilters(), and db.
getShippingModes ($limit = 100, $page = 0, $active = 1, $sqlfilters = '')
Get the list of shipping methods.
Parameters
int $limit Number of items per page
int $page Page number { 0}
int $active Shipping methodsm is active or not { 0} { 1}
string $sqlfilters SQL criteria to filter. Syntax example "(t.code:=:'CHQ')"
GET dictionary/shipping_methods
Returns
array List of shipping methods
Exceptions
400 RestException
200 OK
Definition at line 736 of file api_setup.class.php.
References DolibarrApi\_checkFilters(), and db.
getTicketsCategories ($sortfield = "code", $sortorder = 'ASC', $limit = 100, $page = 0, $active = 1, $sqlfilters = '')
Get the list of tickets categories.
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Number of items per page
int $page Page number (starting from zero)
int $active Payment term is active or not { 0} { 1}
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.code:like:'A%') and (t.active:>=:0)"
Returns
List of events types
GET dictionary/ticket_categories
Exceptions
RestException
Definition at line 857 of file api_setup.class.php.
References DolibarrApi\_checkFilters(), and db.
getTicketsSeverities ($sortfield = "code", $sortorder = 'ASC', $limit = 100, $page = 0, $active = 1, $sqlfilters = '')
Get the list of tickets severity.
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Number of items per page
int $page Page number (starting from zero)
int $active Payment term is active or not { 0} { 1}
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.code:like:'A%') and (t.active:>=:0)"
Returns
List of events types
GET dictionary/ticket_severities
Exceptions
RestException
Definition at line 917 of file api_setup.class.php.
References DolibarrApi\_checkFilters(), and db.
getTicketsTypes ($sortfield = "code", $sortorder = 'ASC', $limit = 100, $page = 0, $active = 1, $sqlfilters = '')
Get the list of tickets types.
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Number of items per page
int $page Page number (starting from zero)
int $active Payment term is active or not { 0} { 1}
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.code:like:'A%') and (t.active:>=:0)"
Returns
List of events types
GET dictionary/ticket_types
Exceptions
RestException
Definition at line 977 of file api_setup.class.php.
References DolibarrApi\_checkFilters(), and db.
translateLabel ($country, $lang) private
Translate the name of the country to the given language.
Parameters
Ccountry $country Country
string $lang Code of the language the name of the country must be translated to
Returns
void
Definition at line 303 of file api_setup.class.php.
Referenced by getCountryByID(), and getListOfCountries().
The documentation for this class was generated from the following file:
htdocs/api/class/api_setup.class.php