Dolibarr: BankAccounts Class Reference
BankAccounts Class Reference
Public Member Functions
__construct ()
Constructor.
index ($sortfield="t.rowid", $sortorder= 'ASC', $limit=100, $page=0, $sqlfilters= '')
Get the list of accounts.
get ($id)
Get account by ID.
post ($request_data=null)
Create account object.
transfer ($bankaccount_from_id=0, $bankaccount_to_id=0, $date=null, $description="", $amount=0.0, $amount_to=0.0)
Create an internal wire transfer between two bank accounts.
put ($id, $request_data=null)
Update account.
delete ($id)
Delete account.
getLines ($id)
Get the list of lines of the account.
addLine ($id, $date, $type, $label, $amount, $category=0, $cheque_number= '', $cheque_writer= '', $cheque_bank= '')
Add a line to an account.
addLink ($id, $line_id, $url_id, $url, $label, $type)
Add a link to an account line.
Public Member Functions inherited from DolibarrApi
__construct ($db, $cachedir= '', $refreshCache=false)
Constructor.
Static Public Attributes
static $FIELDS
array $FIELDS Mandatory fields, checked when creating an object
Protected Member Functions
_cleanObjectDatas ($object)
Clean sensible object datas.
Protected Member Functions inherited from DolibarrApi
_cleanObjectDatas ($object)
Executed method when API is called without parameter.
_checkFilters ($sqlfilters)
Return if a $sqlfilters parameter is valid.
Private Member Functions
_validate ($data)
Validate fields before creating an object.
Additional Inherited Members
Static Protected Member Functions inherited from DolibarrApi
static _checkAccessToResource ($resource, $resource_id=0, $dbtablename= '', $feature2= '', $dbt_keyfield= 'fk_soc', $dbt_select= 'rowid')
Check user access to a resource.
static _forge_criteria_callback ($matches)
Function to forge a SQL criteria.
Detailed Description
Definition at line 30 of file api_bankaccounts.class.php.
Member Function Documentation
_cleanObjectDatas ($object) protected
Clean sensible object datas.
Parameters
object $object Object to clean
Returns
array Array of cleaned object properties
Definition at line 395 of file api_bankaccounts.class.php.
Referenced by get(), getLines(), and index().
_validate ($data) private
Validate fields before creating an object.
Parameters
array | null $data Data to validate
Returns
array
Exceptions
RestException
Definition at line 377 of file api_bankaccounts.class.php.
References $FIELDS.
Referenced by post().
addLine ($id, $date, $type, $label, $amount, $category = 0, $cheque_number = '', $cheque_writer = '', $cheque_bank = '')
Add a line to an account.
Parameters
int $id ID of account
int $date Payment date (timestamp) { body} { timestamp}
string $type Payment mode (TYP,VIR,PRE,LIQ,VAD,CB,CHQ...) { body}
string $label Label { body}
float $amount Amount (may be 0) { body}
int $category Category
string $cheque_number Cheque numberl { body}
string $cheque_writer Name of cheque writer { body}
string $cheque_bank Bank of cheque writer { body}
Returns
int ID of line
POST {id}/lines
Definition at line 467 of file api_bankaccounts.class.php.
References db.
addLink ($id, $line_id, $url_id, $url, $label, $type)
Add a link to an account line.
Parameters
int $id ID of account
int $line_id ID of account line
int $url_id ID to set in the URL { body}
string $url URL of the link { body}
string $label Label { body}
string $type Type of link ('payment', 'company', 'member', ...) { body}
Returns
int ID of link
POST {id}/lines/{line_id}/links
Definition at line 508 of file api_bankaccounts.class.php.
References db.
delete ($id)
Delete account.
Parameters
int $id ID of account
Returns
array
Definition at line 346 of file api_bankaccounts.class.php.
References db.
get ($id)
Get account by ID.
Parameters
int $id ID of account
Returns
array Account object
Exceptions
RestException
Definition at line 125 of file api_bankaccounts.class.php.
References _cleanObjectDatas(), and db.
getLines ($id)
Get the list of lines of the account.
Parameters
int $id ID of account
Returns
array Array of AccountLine objects
Exceptions
RestException GET {id}/lines
Definition at line 415 of file api_bankaccounts.class.php.
References _cleanObjectDatas(), and db.
index ($sortfield = "t.rowid", $sortorder = 'ASC', $limit = 100, $page = 0, $sqlfilters = '')
Get the list of accounts.
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Limit for list
int $page Page number
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.ref:like:'SO-%') and (t.import_key:<:'20160101')"
Returns
array List of account objects
Exceptions
RestException
Definition at line 65 of file api_bankaccounts.class.php.
References DolibarrApi\_checkFilters(), _cleanObjectDatas(), db, and dol_syslog().
post ($request_data = null)
Create account object.
Parameters
array $request_data Request data
Returns
int ID of account
Definition at line 146 of file api_bankaccounts.class.php.
References _validate(), and db.
put ($id, $request_data = null)
Update account.
Parameters
int $id ID of account
array $request_data data
Returns
int
Definition at line 313 of file api_bankaccounts.class.php.
References db.
transfer ($bankaccount_from_id = 0, $bankaccount_to_id = 0, $date = null, $description = "", $amount = 0.0, $amount_to = 0.0)
Create an internal wire transfer between two bank accounts.
Parameters
int $bankaccount_from_id BankAccount ID to use as the source of the internal wire transfer { body}{ true}
int $bankaccount_to_id BankAccount ID to use as the destination of the internal wire transfer { body}{ true}
string $date Date of the internal wire transfer (UNIX timestamp) { body}{ true}{ timestamp}
string $description Description of the internal wire transfer { body}{ true}
float $amount Amount to transfer from the source to the destination BankAccount { body}{ true}
float $amount_to Amount to transfer to the destination BankAccount (only when accounts does not share the same currency) { body}{ false}
POST /transfer
Returns
array
201
Exceptions
401 Unauthorized: User does not have permission to configure bank accounts
404 Not Found: Either the source or the destination bankaccount for the provided id does not exist
422 Unprocessable Entity: Refer to detailed exception message for the cause
500 Internal Server Error: Error(s) returned by the RDBMS
Creating bank line records
Creating links between bank line record and its source
Definition at line 191 of file api_bankaccounts.class.php.
References db, price2num(), and Account\TYPE_CASH.
The documentation for this class was generated from the following file:
htdocs/compta/bank/class/api_bankaccounts.class.php