Dolibarr: FormProduct Class Reference
FormProduct Class Reference
Class with static methods for building HTML components related to products Only components common to products and services must be here.
Public Member Functions
__construct ($db)
Constructor.
loadWarehouses ($fk_product=0, $batch= '', $status= '', $sumStock=true, $exclude= '')
Load in cache array list of warehouses If fk_product is not 0, we do not use cache.
selectWarehouses ($selected= '', $htmlname= 'idwarehouse', $filterstatus= '', $empty=0, $disabled=0, $fk_product=0, $empty_label= '', $showstock=0, $forcecombo=0, $events=array(), $morecss= 'minwidth200', $exclude= '', $showfullpath=1)
Return list of warehouses.
formSelectWarehouses ($page, $selected= '', $htmlname= 'warehouse_id', $addempty=0)
Display form to select warehouse.
select_measuring_units ($name= 'measuring_units', $measuring_style= '', $default= '0', $adddefault=0, $mode=0)
Output a combo box with list of units pour l'instant on ne definit pas les unites dans la base.
selectMeasuringUnits ($name= 'measuring_units', $measuring_style= '', $default= '0', $adddefault=0, $mode=0)
Return a combo box with list of units For the moment, units labels are defined in measuring_units_string.
selectLotStock ($selected= '', $htmlname= 'batch_id', $filterstatus= '', $empty=0, $disabled=0, $fk_product=0, $fk_entrepot=0, $objectLines=array(), $empty_label= '', $forcecombo=0, $events=array(), $morecss= 'minwidth200')
Return list of lot numbers (stock from product_batch) with stock location and stock qty.
Private Member Functions
get_parent_path ($tab, $final_label= '')
Return full path to current warehouse in $tab (recursive function)
loadLotStock ($productIdArray=array())
Load in cache array list of lot available in stock from a given list of products.
Detailed Description
Class with static methods for building HTML components related to products Only components common to products and services must be here.
Definition at line 30 of file html.formproduct.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 52 of file html.formproduct.class.php.
References db.
Member Function Documentation
formSelectWarehouses ($page, $selected = '', $htmlname = 'warehouse_id', $addempty = 0)
Display form to select warehouse.
Parameters
string $page Page
int $selected Id of warehouse
string $htmlname Name of select html field
int $addempty 1=Add an empty value in list, 2=Add an empty value in list only if there is more than 2 entries.
Returns
void
Definition at line 258 of file html.formproduct.class.php.
References db, print, and selectWarehouses().
get_parent_path ($tab, $final_label = '') private
Return full path to current warehouse in $tab (recursive function)
Parameters
array $tab warehouse data in $this->cache_warehouses line
String $final_label full label with all parents, separated by ' >> ' (completed on each call)
Returns
String full label with all parents, separated by ' >> '
Definition at line 176 of file html.formproduct.class.php.
Referenced by loadWarehouses().
loadLotStock ($productIdArray = array()) private
Load in cache array list of lot available in stock from a given list of products.
Parameters
array $productIdArray array of product id's from who to get lot numbers. A
Returns
int Nb of loaded lines, 0 if nothing loaded, <0 if KO
Definition at line 451 of file html.formproduct.class.php.
References $resql, db, dol_print_error(), dol_syslog(), and getEntity().
Referenced by selectLotStock().
loadWarehouses ($fk_product = 0, $batch = '', $status = '', $sumStock = true, $exclude = '')
Load in cache array list of warehouses If fk_product is not 0, we do not use cache.
Parameters
int $fk_product Add quantity of stock in label for product with id fk_product. Nothing if 0.
string $batch Add quantity of batch stock in label for product with batch name batch, batch name precedes batch_id. Nothing if ''.
string $status warehouse status filter, following comma separated filter options can be used 'warehouseopen' = select products from open warehouses, 'warehouseclosed' = select products from closed warehouses, 'warehouseinternal' = select products from warehouses for internal correct/transfer only
boolean $sumStock sum total stock of a warehouse, default true
array $exclude warehouses ids to exclude
Returns
int Nb of loaded lines, 0 if already loaded, <0 if KO
Definition at line 72 of file html.formproduct.class.php.
References $resql, db, dol_print_error(), dol_syslog(), get_parent_path(), price2num(), Entrepot\STATUS_CLOSED, Entrepot\STATUS_OPEN_ALL, and Entrepot\STATUS_OPEN_INTERNAL.
Referenced by selectWarehouses().
select_measuring_units ($name = 'measuring_units', $measuring_style = '', $default = '0', $adddefault = 0, $mode = 0)
Output a combo box with list of units pour l'instant on ne definit pas les unites dans la base.
Parameters
string $name Name of HTML field
string $measuring_style Unit to show: weight, size, surface, volume, time
string $default Preselected value
int $adddefault Add empty unit called "Default"
int $mode 1=Use short label as value, 0=Use rowid
Returns
void
Deprecated:
Definition at line 296 of file html.formproduct.class.php.
References print, and selectMeasuringUnits().
selectLotStock ($selected = '', $htmlname = 'batch_id', $filterstatus = '', $empty = 0, $disabled = 0, $fk_product = 0, $fk_entrepot = 0, $objectLines = array(), $empty_label = '', $forcecombo = 0, $events = array(), $morecss = 'minwidth200')
Return list of lot numbers (stock from product_batch) with stock location and stock qty.
Parameters
int $selected Id of preselected lot stock id ('' for no value, 'ifone'=select value if one value otherwise no value)
string $htmlname Name of html select html
string $filterstatus lot status filter, following comma separated filter options can be used
int $empty 1=Can be empty, 0 if not
int $disabled 1=Select is disabled
int $fk_product show lot numbers of product with id fk_product. All from objectLines if 0.
int $fk_entrepot filter lot numbers for warehouse with id fk_entrepot. All if 0.
array $objectLines Only cache lot numbers for products in lines of object. If no lines only for fk_product. If no fk_product, all.
string $empty_label Empty label if needed (only if $empty=1)
int $forcecombo 1=Force combo iso ajax select2
array $events Events to add to select2
string $morecss Add more css classes to HTML select
Returns
string HTML select
Definition at line 380 of file html.formproduct.class.php.
References ajax_combobox(), dol_syslog(), and loadLotStock().
selectMeasuringUnits ($name = 'measuring_units', $measuring_style = '', $default = '0', $adddefault = 0, $mode = 0)
Return a combo box with list of units For the moment, units labels are defined in measuring_units_string.
Parameters
string $name Name of HTML field
string $measuring_style Unit to show: weight, size, surface, volume, time
string $default Preselected value
int $adddefault Add empty unit called "Default"
int $mode 1=Use short label as value, 0=Use rowid
Returns
string
Definition at line 313 of file html.formproduct.class.php.
References dol_print_error().
Referenced by select_measuring_units().
selectWarehouses ($selected = '', $htmlname = 'idwarehouse', $filterstatus = '', $empty = 0, $disabled = 0, $fk_product = 0, $empty_label = '', $showstock = 0, $forcecombo = 0, $events = array(), $morecss = 'minwidth200', $exclude = '', $showfullpath = 1)
Return list of warehouses.
Parameters
int $selected Id of preselected warehouse ('' for no value, 'ifone'=select value if one value otherwise no value)
string $htmlname Name of html select html
string $filterstatus warehouse status filter, following comma separated filter options can be used 'warehouseopen' = select products from open warehouses, 'warehouseclosed' = select products from closed warehouses, 'warehouseinternal' = select products from warehouses for internal correct/transfer only
int $empty 1=Can be empty, 0 if not
int $disabled 1=Select is disabled
int $fk_product Add quantity of stock in label for product with id fk_product. Nothing if 0.
string $empty_label Empty label if needed (only if $empty=1)
int $showstock 1=Show stock count
int $forcecombo 1=Force combo iso ajax select2
array $events Events to add to select2
string $morecss Add more css classes to HTML select
array $exclude Warehouses ids to exclude
int $showfullpath 1=Show full path of name (parent ref into label), 0=Show only ref of current warehouse
Returns
string HTML select
Definition at line 213 of file html.formproduct.class.php.
References ajax_combobox(), dol_syslog(), if, and loadWarehouses().
Referenced by formSelectWarehouses().
The documentation for this class was generated from the following file:
htdocs/product/class/html.formproduct.class.php