Dolibarr: MenuManager Class Reference
MenuManager Class Reference
Class to manage menu Auguria.
Public Member Functions
__construct ($db, $type_user)
Constructor.
loadMenu ($forcemainmenu= '', $forceleftmenu= '')
Load this->tabMenu.
showmenu ($mode, $moredata=null)
Show menu.
__construct ($db, $type_user)
Constructor.
loadMenu ($forcemainmenu= '', $forceleftmenu= '')
Load this->tabMenu.
showmenu ($mode, $moredata=null)
Show menu.
__construct ($db, $type_user)
Constructor.
loadMenu ()
Load this->tabMenu.
showmenu ($mode, $moredata=null)
Show menu.
Detailed Description
Class to manage menu Auguria.
Class to manage empty menu.
Class to manage menu Eldy.
Definition at line 29 of file auguria_menu.php.
Constructor & Destructor Documentation
__construct ($db, $type_user)
Constructor.
Parameters
DoliDB $db Database handler
int $type_user Type of user
Definition at line 52 of file auguria_menu.php.
References db.
__construct ($db, $type_user)
Constructor.
Parameters
DoliDB $db Database handler
int $type_user Type of user
Definition at line 51 of file eldy_menu.php.
References db.
__construct ($db, $type_user)
Constructor.
Parameters
DoliDB $db Database handler
int $type_user Type of user
Definition at line 46 of file empty.php.
References db.
Member Function Documentation
loadMenu ()
Load this->tabMenu.
Returns
void
Definition at line 58 of file empty.php.
loadMenu ($forcemainmenu = '', $forceleftmenu = '')
Load this->tabMenu.
Parameters
string $forcemainmenu To force mainmenu to load
string $forceleftmenu To force leftmenu to load
Returns
void
Definition at line 65 of file eldy_menu.php.
References db.
loadMenu ($forcemainmenu = '', $forceleftmenu = '')
Load this->tabMenu.
Parameters
string $forcemainmenu To force mainmenu to load
string $forceleftmenu To force leftmenu to load
Returns
void
Definition at line 66 of file auguria_menu.php.
References db.
Referenced by analyseVarsForSqlAndScriptsInjection().
showmenu ($mode, $moredata = null)
Show menu.
Parameters
string $mode 'top', 'left', 'jmobile'
array $moredata An array with more data to output
Returns
int 0 or nb of top menu entries if $mode = 'topnb'
Definition at line 70 of file empty.php.
References dol_buildpath(), dol_sort_array(), make_substitutions(), print, print_end_menu_array_empty(), print_end_menu_entry_empty(), print_start_menu_array_empty(), print_start_menu_entry_empty(), and print_text_menu_entry_empty().
showmenu ($mode, $moredata = null)
Show menu.
Parameters
string $mode 'top', 'left', 'jmobile' (used to get full xml ul/li menu)
array $moredata An array with more data to output
Returns
int 0 or nb of top menu entries if $mode = 'topnb'
Definition at line 126 of file auguria_menu.php.
References db, dol_buildpath(), make_substitutions(), print, print_auguria_menu(), and print_left_auguria_menu().
showmenu ($mode, $moredata = null)
Show menu.
Module defined in sql tables were stored into $this->tabMenu BEFORE this is called.
Parameters
string $mode 'top', 'topnb', 'left', 'jmobile' (used to get full xml ul/li menu)
array $moredata An array with more data to output
Returns
int 0 or nb of top menu entries if $mode = 'topnb'
Definition at line 126 of file eldy_menu.php.
References db, dol_buildpath(), make_substitutions(), print, print_eldy_menu(), and print_left_eldy_menu().
The documentation for this class was generated from the following files:
htdocs/core/menus/standard/auguria_menu.php
htdocs/core/menus/standard/eldy_menu.php
htdocs/core/menus/standard/empty.php