Dolibarr: pdf_paiement Class Reference
pdf_paiement Class Reference
Classe permettant de generer les rapports de paiement.
Public Member Functions
__construct ($db)
Constructor.
write_file ($_dir, $month, $year, $outputlangs)
Fonction generant la rapport sur le disque.
Body (&$pdf, $page, $lines, $outputlangs)
Output body.
Protected Member Functions
_pagehead (&$pdf, $page, $showaddress, $outputlangs)
Show top header of page.
Detailed Description
Classe permettant de generer les rapports de paiement.
Definition at line 33 of file pdf_paiement.class.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDb $db Database handler
Definition at line 40 of file pdf_paiement.class.php.
References db, description, pdf_getFormat(), and type.
Member Function Documentation
_pagehead (& $pdf, $page, $showaddress, $outputlangs) protected
Show top header of page.
Parameters
PDF $pdf Object PDF
int $page Object to show
int $showaddress 0=no, 1=yes
Translate $outputlangs Object lang for output
Returns
void
Definition at line 353 of file pdf_paiement.class.php.
References dol_mktime(), dol_print_date(), and pdf_getPDFFontSize().
Referenced by Body(), and write_file().
Body (& $pdf, $page, $lines, $outputlangs)
Output body.
Parameters
PDF $pdf PDF object
string $page Page
array $lines Array of lines
Translate $outputlangs Object langs
Returns
void
Definition at line 427 of file pdf_paiement.class.php.
References _pagehead(), pdf_getPDFFontSize(), and price().
Referenced by write_file().
write_file ($_dir, $month, $year, $outputlangs)
Fonction generant la rapport sur le disque.
Parameters
string $_dir repertoire
int $month mois du rapport
int $year annee du rapport
string $outputlangs Lang output object
Returns
int <0 if KO, >0 if OK
Definition at line 96 of file pdf_paiement.class.php.
References _pagehead(), Body(), db, dol_get_first_day(), dol_get_last_day(), dol_mkdir(), dol_print_date(), dol_print_error(), dol_syslog(), pdf_getInstance(), pdf_getPDFFont(), pdf_getPDFFontSize(), and price().
The documentation for this class was generated from the following file:
htdocs/core/modules/rapport/pdf_paiement.class.php