Dolibarr: htdocs/core/lib/treeview.lib.php File Reference
treeview.lib.php File Reference
Libraries for tree views.
Functions
tree_showpad (&$fulltree, $key, $silent=0)
Show indent and picto of a tree line.
tree_recur ($tab, $pere, $rang, $iddivjstree= 'iddivjstree', $donoresetalreadyloaded=0, $showfk=0)
Recursive function to output a tree.
Detailed Description
Libraries for tree views.
Definition in file treeview.lib.php.
Function Documentation
tree_recur ($tab, $pere, $rang, $iddivjstree = 'iddivjstree', $donoresetalreadyloaded = 0, $showfk = 0)
Recursive function to output a tree.
...
It is also used for the tree of categories. Note: To have this function working, check you have loaded the js and css for treeview. $arrayofjs=array('/includes/jquery/plugins/jquerytreeview/jquery.treeview.js', '/includes/jquery/plugins/jquerytreeview/lib/jquery.cookie.js'); $arrayofcss=array('/includes/jquery/plugins/jquerytreeview/jquery.treeview.css'); TODO Replace with jstree plugin instead of treeview plugin.
Parameters
array $tab Array of all elements
array $pere Array with parent ids ('rowid'=>,'mainmenu'=>,'leftmenu'=>,'fk_mainmenu=>,'fk_leftmenu=>)
int $rang Level of element
string $iddivjstree Id to use for parent ul element
int $donoresetalreadyloaded Do not reset global array $donoresetalreadyloaded used to avoid to go down on an aleady processed record
int $showfk 1=show fk_links to parent into label (used by menu editor only)
Returns
void
Definition at line 116 of file treeview.lib.php.
References dol_syslog(), and print.
tree_showpad (& $fulltree, $key, $silent = 0)
Show indent and picto of a tree line.
Return array with information of line.
Parameters
array $fulltree Array of entries in correct order
string $key Key of entry into fulltree to show picto
int $silent Do not output indent and picto, returns only value
Returns
integer[] array(0 or 1 if at least one of this level after, 0 or 1 if at least one of higher level after, nbofdirinsub, nbofdocinsub)
Definition at line 36 of file treeview.lib.php.
References img_picto_common(), and print.
Referenced by treeOutputForAbsoluteDir().