Dolibarr: mod_syslog_file Class Reference
mod_syslog_file Class Reference
Class to manage logging to a file.
Public Member Functions
getName ()
Return name of logger.
getVersion ()
Version of the module ('x.y.z' or 'dolibarr' or 'experimental' or 'development')
getInfo ()
Content of the info tooltip.
isActive ()
Is the module active ?
configure ()
Return array of configuration data.
checkConfiguration ()
Return if configuration is valid.
export ($content, $suffixinfilename= '')
Export the message.
Public Member Functions inherited from LogHandler
getInfo ()
Content of the info tooltip.
getWarning ()
Return warning if something is wrong with logger.
getVersion ()
Version of the module ('x.y.z' or 'dolibarr' or 'experimental' or 'development')
isActive ()
Is the module active ?
configure ()
Configuration variables of the module.
checkConfiguration ()
Function that checks if the configuration is valid.
setIdent ($ident)
Set current ident.
Public Member Functions inherited from LogHandlerInterface
getWarning ()
Return warning if something is wrong with logger.
export ($content)
Output log content.
Private Member Functions
getFilename ($suffixinfilename= '')
Return the parsed logfile path.
Detailed Description
Class to manage logging to a file.
Definition at line 8 of file mod_syslog_file.php.
Member Function Documentation
checkConfiguration ()
Return if configuration is valid.
Returns
array Array of errors. Empty array if ok.
Implements LogHandlerInterface.
Definition at line 82 of file mod_syslog_file.php.
References dol_syslog(), and getFilename().
configure ()
Return array of configuration data.
Returns
array Return array of configuration data
Implements LogHandlerInterface.
Definition at line 63 of file mod_syslog_file.php.
export ($content, $suffixinfilename = '')
Export the message.
Parameters
array $content Array containing the info about the message
string $suffixinfilename When output is a file, append this suffix into default log filename.
Returns
void
Definition at line 134 of file mod_syslog_file.php.
References getFilename(), and print.
getFilename ($suffixinfilename = '') private
Return the parsed logfile path.
Parameters
string $suffixinfilename When output is a file, append this suffix into default log filename.
Returns
string
Definition at line 105 of file mod_syslog_file.php.
Referenced by checkConfiguration(), and export().
getInfo ()
Content of the info tooltip.
Returns
false|string
Implements LogHandlerInterface.
Definition at line 40 of file mod_syslog_file.php.
getName ()
Return name of logger.
Returns
string Name of logger
Implements LogHandlerInterface.
Definition at line 18 of file mod_syslog_file.php.
getVersion ()
Version of the module ('x.y.z' or 'dolibarr' or 'experimental' or 'development')
Returns
string
Implements LogHandlerInterface.
Definition at line 30 of file mod_syslog_file.php.
isActive ()
Is the module active ?
Returns
int
Implements LogHandlerInterface.
Definition at line 52 of file mod_syslog_file.php.
The documentation for this class was generated from the following file:
htdocs/core/modules/syslog/mod_syslog_file.php