Dolibarr: AccountancyExport Class Reference
AccountancyExport Class Reference
Manage the different format accountancy export.
Public Member Functions
__construct (DoliDB &$db)
Constructor.
export (&$TData)
Function who chose which export to use with the default config, and make the export into a file.
exportCegid ($objectLines)
Export format : CEGID.
exportCogilog ($objectLines)
Export format : COGILOG.
exportCoala ($objectLines)
Export format : COALA.
exportBob50 ($objectLines)
Export format : BOB50.
exportCiel (&$TData)
Export format : CIEL.
exportQuadratus (&$TData)
Export format : Quadratus.
exportEbp ($objectLines)
Export format : EBP.
exportAgiris ($objectLines)
Export format : Agiris Isacompta.
exportOpenConcerto ($objectLines)
Export format : OpenConcerto.
exportConfigurable ($objectLines)
Export format : Configurable CSV.
exportFEC ($objectLines)
Export format : FEC.
exportSAGE50SWISS ($objectLines)
Export format : SAGE50SWISS.
exportLDCompta ($objectLines)
Export format : LD Compta version 9 & higher http://www.ldsysteme.fr/fileadmin/telechargement/np/ldcompta/Documentation/IntCptW10.pdf.
exportCharlemagne ($objectLines)
Export format : Charlemagne.
Static Public Member Functions
static getType ()
Array with all export type available (key + label)
static getTypeConfig ()
Array with all export type available (key + label) and parameters for config.
static trunc ($str, $size)
trunc
static toAnsi ($str, $size=-1)
toAnsi
Static Private Member Functions
static getFormatCode ($type)
Return string to summarize the format (Used to generated export filename)
Detailed Description
Manage the different format accountancy export.
Definition at line 39 of file accountancyexport.class.php.
Constructor & Destructor Documentation
__construct (DoliDB & $db)
Constructor.
Parameters
DoliDb $db Database handler
Definition at line 80 of file accountancyexport.class.php.
References db.
Member Function Documentation
export (& $TData)
Function who chose which export to use with the default config, and make the export into a file.
Parameters
array $TData data
Returns
void
Definition at line 230 of file accountancyexport.class.php.
References exportAgiris(), exportBob50(), exportCegid(), exportCharlemagne(), exportCiel(), exportCoala(), exportCogilog(), exportConfigurable(), exportEbp(), exportFEC(), exportLDCompta(), exportOpenConcerto(), exportQuadratus(), and exportSAGE50SWISS().
exportAgiris ($objectLines)
Export format : Agiris Isacompta.
Parameters
array $objectLines data
Returns
void
Definition at line 580 of file accountancyexport.class.php.
References dol_print_date(), length_accounta(), length_accountg(), price(), and print.
Referenced by export().
exportBob50 ($objectLines)
Export format : BOB50.
Parameters
array $objectLines data
Returns
void
Definition at line 383 of file accountancyexport.class.php.
References dol_print_date(), dol_trunc(), length_accounta(), length_accountg(), price(), and print.
Referenced by export().
exportCegid ($objectLines)
Export format : CEGID.
Parameters
array $objectLines data
Returns
void
Definition at line 298 of file accountancyexport.class.php.
References dol_print_date(), length_accounta(), length_accountg(), price(), and print.
Referenced by export().
exportCharlemagne ($objectLines)
Export format : Charlemagne.
Parameters
array $objectLines data
Returns
void
Definition at line 1021 of file accountancyexport.class.php.
References dol_print_date(), price(), and print.
Referenced by export().
exportCiel (& $TData)
Export format : CIEL.
Parameters
array $TData data
Returns
void
Definition at line 421 of file accountancyexport.class.php.
References dol_now(), dol_print_date(), dol_string_unaccent(), and print.
Referenced by export().
exportCoala ($objectLines)
Export format : COALA.
Parameters
array $objectLines data
Returns
void
Definition at line 356 of file accountancyexport.class.php.
References dol_print_date(), length_accountg(), price(), and print.
Referenced by export().
exportCogilog ($objectLines)
Export format : COGILOG.
Parameters
array $objectLines data
Returns
void
Definition at line 323 of file accountancyexport.class.php.
References dol_print_date(), length_accountg(), price(), and print.
Referenced by export().
exportConfigurable ($objectLines)
Export format : Configurable CSV.
Parameters
array $objectLines data
Returns
void
Definition at line 652 of file accountancyexport.class.php.
References dol_print_date(), length_accounta(), length_accountg(), price2num(), and print.
Referenced by export().
exportEbp ($objectLines)
Export format : EBP.
Parameters
array $objectLines data
Returns
void
Definition at line 544 of file accountancyexport.class.php.
References dol_print_date(), price2num(), and print.
Referenced by export().
exportFEC ($objectLines)
Export format : FEC.
Parameters
array $objectLines data
Returns
void
Definition at line 683 of file accountancyexport.class.php.
References dol_print_date(), price2num(), and print.
Referenced by export().
exportLDCompta ($objectLines)
Export format : LD Compta version 9 & higher http://www.ldsysteme.fr/fileadmin/telechargement/np/ldcompta/Documentation/IntCptW10.pdf.
Parameters
array $objectLines data
Returns
void
Definition at line 929 of file accountancyexport.class.php.
References dol_print_date(), length_accounta(), length_accountg(), price(), and print.
Referenced by export().
exportOpenConcerto ($objectLines)
Export format : OpenConcerto.
Parameters
array $objectLines data
Returns
void
Definition at line 620 of file accountancyexport.class.php.
References dol_print_date(), length_accounta(), length_accountg(), price(), and print.
Referenced by export().
exportQuadratus (& $TData)
Export format : Quadratus.
Parameters
array $TData data
Returns
void
Definition at line 461 of file accountancyexport.class.php.
References dol_print_date(), dol_string_unaccent(), and print.
Referenced by export().
exportSAGE50SWISS ($objectLines)
Export format : SAGE50SWISS.
https://onlinehelp.sageschweiz.ch/default.aspx?tabid=19984 http://media.topal.ch/Public/Schnittstellen/TAF/Specification/Sage50-TAF-format.pdf
Parameters
array $objectLines data
Returns
void
Definition at line 781 of file accountancyexport.class.php.
References dol_print_date(), length_accounta(), length_accountg(), and print.
Referenced by export().
static getFormatCode ($type) static private
Return string to summarize the format (Used to generated export filename)
Parameters
int $type Format id
Returns
string Format code
Definition at line 126 of file accountancyexport.class.php.
static getType () static
Array with all export type available (key + label)
Returns
array of type
Definition at line 94 of file accountancyexport.class.php.
static getTypeConfig () static
Array with all export type available (key + label) and parameters for config.
Returns
array of type
Definition at line 152 of file accountancyexport.class.php.
static toAnsi ($str, $size = -1) static
toAnsi
Parameters
string $str Original string to encode and optionaly truncate
integer $size Truncate string after $size characters
Returns
string String encoded in Windows-1251 charset
Definition at line 1094 of file accountancyexport.class.php.
References dol_string_nohtmltag().
static trunc ($str, $size) static
trunc
Parameters
string $str String
integer $size Data to trunc
Returns
string
Definition at line 1082 of file accountancyexport.class.php.
References dol_trunc().
The documentation for this class was generated from the following file:
htdocs/accountancy/class/accountancyexport.class.php