Dolibarr: modGeneratePassPerso Class Reference
modGeneratePassPerso Class Reference
Class to generate a password according to personal rules.
Public Member Functions
__construct ($db, $conf, $langs, $user)
Constructor.
getDescription ()
Return description of module.
getExample ()
Return an example of password generated by this module.
getNewGeneratedPassword ()
Build new password.
validatePassword ($password)
Validate a password.
consecutiveInterationSameCharacter ($password)
consecutive iterations of the same character
Public Member Functions inherited from ModeleGenPassword
isEnabled ()
Return if a module can be used or not.
getDescription ()
Return description of module.
getExample ()
Return an example of password generated by this module.
getNewGeneratedPassword ()
Build new password.
validatePassword ($password)
Validate a password.
Detailed Description
Class to generate a password according to personal rules.
Definition at line 34 of file modGeneratePassPerso.class.php.
Constructor & Destructor Documentation
__construct ($db, $conf, $langs, $user)
Constructor.
Parameters
DoliDB $db Database handler
Conf $conf Handler de conf
Translate $langs Handler de langue
User $user Handler du user connecte
Definition at line 73 of file modGeneratePassPerso.class.php.
References conf(), db, dolibarr_set_const(), and user.
Member Function Documentation
consecutiveInterationSameCharacter ($password)
consecutive iterations of the same character
Parameters
string $password Password to check
Returns
int 0 if KO, >0 if OK
Definition at line 214 of file modGeneratePassPerso.class.php.
Referenced by validatePassword().
getDescription ()
Return description of module.
Returns
string Description of text
Definition at line 123 of file modGeneratePassPerso.class.php.
getExample ()
Return an example of password generated by this module.
Returns
string Example of password
Definition at line 134 of file modGeneratePassPerso.class.php.
References getNewGeneratedPassword().
getNewGeneratedPassword ()
Build new password.
Returns
string Return a new generated password
Definition at line 144 of file modGeneratePassPerso.class.php.
References validatePassword().
Referenced by getExample().
validatePassword ($password)
Validate a password.
Parameters
string $password Password to check
Returns
int 0 if KO, >0 if OK
Definition at line 182 of file modGeneratePassPerso.class.php.
References consecutiveInterationSameCharacter().
Referenced by getNewGeneratedPassword().
The documentation for this class was generated from the following file:
htdocs/core/modules/security/generate/modGeneratePassPerso.class.php