Dolibarr: printing_printipp Class Reference
printing_printipp Class Reference
Class to provide printing with PrintIPP.
Public Member Functions
__construct ($db)
Constructor.
printFile ($file, $module, $subdir= '')
Print selected file.
listAvailablePrinters ()
Return list of available printers.
getlistAvailablePrinters ()
Return list of available printers.
listJobs ($module)
List jobs print.
Public Member Functions inherited from PrintingDriver
__construct ($db)
Constructor.
getDesc ()
Return description of Printing Module.
Private Member Functions
getPrinterDetail ($uri)
Get printer detail.
Additional Inherited Members
Static Public Member Functions inherited from PrintingDriver
static listDrivers ($db, $maxfilenamelength=0)
Return list of printing driver.
Detailed Description
Class to provide printing with PrintIPP.
Definition at line 31 of file printipp.modules.php.
Constructor & Destructor Documentation
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 65 of file printipp.modules.php.
References conf(), db, and user.
Member Function Documentation
getlistAvailablePrinters ()
Return list of available printers.
Returns
array list of printers
Definition at line 207 of file printipp.modules.php.
References user.
Referenced by listAvailablePrinters().
getPrinterDetail ($uri) private
Get printer detail.
Parameters
string $uri URI
Returns
array List of attributes
Definition at line 229 of file printipp.modules.php.
References user.
Referenced by listAvailablePrinters().
listAvailablePrinters ()
Return list of available printers.
Returns
int 0 if OK, >0 if KO
Definition at line 155 of file printipp.modules.php.
References getlistAvailablePrinters(), getPrinterDetail(), and img_picto().
listJobs ($module)
List jobs print.
Parameters
string $module module
Returns
int 0 if OK, >0 if KO
Definition at line 254 of file printipp.modules.php.
References db, and user.
printFile ($file, $module, $subdir = '')
Print selected file.
Parameters
string $file file
string $module module
string $subdir subdirectory of document like for expedition subdir is sendings
Returns
int 0 if OK, >0 if KO
Definition at line 90 of file printipp.modules.php.
References db, dol_print_error(), dol_syslog(), and user.
The documentation for this class was generated from the following file:
htdocs/core/modules/printing/printipp.modules.php