Dolibarr: LignePrelevement Class Reference
LignePrelevement Class Reference
Class to manage withdrawals.
Public Member Functions
__construct ($db, $user)
Constructor.
fetch ($rowid)
Recupere l'objet prelevement.
getLibStatut ($mode=0)
Return status label of object.
LibStatut ($statut, $mode=0)
Return status label for a status.
Static Public Member Functions
static replaceThirdparty (DoliDB $db, $origin_id, $dest_id)
Function used to replace a thirdparty id with another one.
Detailed Description
Class to manage withdrawals.
Definition at line 32 of file ligneprelevement.class.php.
Constructor & Destructor Documentation
__construct ($db, $user)
Constructor.
Parameters
DoliDb $db Database handler
User $user Objet user
Definition at line 53 of file ligneprelevement.class.php.
References db, and user.
Member Function Documentation
fetch ($rowid)
Recupere l'objet prelevement.
Parameters
int $rowid id de la facture a recuperer
Returns
integer
Definition at line 74 of file ligneprelevement.class.php.
References $resql, db, and dol_syslog().
getLibStatut ($mode = 0)
Return status label of object.
Parameters
int $mode 0=Label, 1=Picto + label, 2=Picto, 3=Label + Picto
Returns
string Label
Definition at line 126 of file ligneprelevement.class.php.
References LibStatut().
LibStatut ($statut, $mode = 0)
Return status label for a status.
Parameters
int $statut id statut
int $mode 0=Label, 1=Picto + label, 2=Picto, 3=Label + Picto
Returns
string Label
Definition at line 139 of file ligneprelevement.class.php.
References img_picto().
Referenced by getLibStatut().
static replaceThirdparty (DoliDB $db, $origin_id, $dest_id) static
Function used to replace a thirdparty id with another one.
Parameters
DoliDB $db Database handler
int $origin_id Old thirdparty id
int $dest_id New thirdparty id
Returns
bool
Definition at line 176 of file ligneprelevement.class.php.
References CommonObject\commonReplaceThirdparty().
The documentation for this class was generated from the following file:
htdocs/compta/prelevement/class/ligneprelevement.class.php