Dolibarr: htdocs/document.php File Reference
document.php File Reference
Wrapper to download data files.
Functions
if(isset($_GET["hashp"])&&!defined("NOLOGIN")) if((isset($_GET["modulepart"])&&$_GET["modulepart"]== 'medias')) llxHeader ()
Header empty.
llxFooter ()
Footer empty.
Detailed Description
Wrapper to download data files.
Remarks
Call of this wrapper is made with URL: DOL_URL_ROOT.'/document.php?modulepart=repfichierconcerne&file=relativepathoffile' DOL_URL_ROOT.'/document.php?modulepart=logs&file=dolibarr.log' DOL_URL_ROOT.'/document.php?hashp=sharekey'
Definition in file document.php.
Function Documentation
llxFooter ()
Footer empty.
Returns
void
Definition at line 70 of file document.php.
References $resql, accessforbidden(), dol_check_secure_access_document(), dol_filesize(), dol_mimetype(), dol_osencode(), dol_syslog(), GETPOST(), print, and top_httphead().
if (isset($_GET["hashp"])&&!defined("NOLOGIN")) if ((isset($_GET["modulepart"])&&$_GET["modulepart"]== 'medias')) llxHeader ()
Header empty.
Returns
void
Definition at line 61 of file document.php.