Dolibarr: htdocs/core/lib/files.lib.php File Reference
files.lib.php File Reference
Library for file managing functions.
Functions
dol_basename ($pathfile)
Make a basename working with all page code (default PHP basenamed fails with cyrillic).
dol_dir_list ($path, $types="all", $recursive=0, $filter="", $excludefilter=null, $sortcriteria="name", $sortorder=SORT_ASC, $mode=0, $nohook=0, $relativename="", $donotfollowsymlinks=0)
Scan a directory and return a list of files/directories.
dol_dir_list_in_database ($path, $filter="", $excludefilter=null, $sortcriteria="name", $sortorder=SORT_ASC, $mode=0)
Scan a directory and return a list of files/directories.
completeFileArrayWithDatabaseInfo (&$filearray, $relativedir)
Complete $filearray with data from database.
dol_compare_file ($a, $b)
Fast compare of 2 files identified by their properties ->name, ->date and ->size.
dol_is_dir ($folder)
Test if filename is a directory.
dol_is_dir_empty ($dir)
Return if path is empty.
dol_is_file ($pathoffile)
Return if path is a file.
dol_is_link ($pathoffile)
Return if path is a symbolic link.
dol_is_url ($url)
Return if path is an URL.
dol_dir_is_emtpy ($folder)
Test if a folder is empty.
dol_count_nb_of_line ($file)
Count number of lines in a file.
dol_filesize ($pathoffile)
Return size of a file.
dol_filemtime ($pathoffile)
Return time of a file.
dolReplaceInFile ($srcfile, $arrayreplacement, $destfile= '', $newmask=0, $indexdatabase=0, $arrayreplacementisregex=0)
Make replacement of strings into a file.
dol_copy ($srcfile, $destfile, $newmask=0, $overwriteifexists=1)
Copy a file to another file.
dolCopyDir ($srcfile, $destfile, $newmask, $overwriteifexists, $arrayreplacement=null)
Copy a dir to another dir.
dol_move ($srcfile, $destfile, $newmask=0, $overwriteifexists=1, $testvirus=0, $indexdatabase=1)
Move a file into another name.
dol_unescapefile ($filename)
Unescape a file submitted by upload.
dolCheckVirus ($src_file)
Check virus into a file.
dol_move_uploaded_file ($src_file, $dest_file, $allowoverwrite, $disablevirusscan=0, $uploaderrorcode=0, $nohook=0, $varfiles= 'addedfile')
Make control on an uploaded file from an GUI page and move it to final destination.
dol_delete_file ($file, $disableglob=0, $nophperrors=0, $nohook=0, $object=null, $allowdotdot=false, $indexdatabase=1)
Remove a file or several files with a mask.
dol_delete_dir ($dir, $nophperrors=0)
Remove a directory (not recursive, so content must be empty).
dol_delete_dir_recursive ($dir, $count=0, $nophperrors=0, $onlysub=0, &$countdeleted=0)
Remove a directory $dir and its subdirectories (or only files and subdirectories)
dol_delete_preview ($object)
Delete all preview files linked to object instance.
dol_meta_create ($object)
Create a meta file with document file into same directory.
dol_init_file_process ($pathtoscan= '', $trackid= '')
Scan a directory and init $_SESSION to manage uploaded files with list of all found files.
dol_add_file_process ($upload_dir, $allowoverwrite=0, $donotupdatesession=0, $varfiles= 'addedfile', $savingdocmask= '', $link=null, $trackid= '', $generatethumbs=1)
Get and save an upload file (for example after submitting a new file a mail form).
dol_remove_file_process ($filenb, $donotupdatesession=0, $donotdeletefile=1, $trackid= '')
Remove an uploaded file (for example after submitting a new file a mail form).
addFileIntoDatabaseIndex ($dir, $file, $fullpathorig= '', $mode= 'uploaded', $setsharekey=0)
Add a file into database index.
deleteFilesIntoDatabaseIndex ($dir, $file, $mode= 'uploaded')
Delete files into database index using search criterias.
dol_convert_file ($fileinput, $ext= 'png', $fileoutput= '', $page= '')
Convert an image file into another format.
dol_uncompress ($inputfile, $outputdir)
Uncompress a file.
dol_most_recent_file ($dir, $regexfilter= '', $excludefilter=array('(\.meta|_preview.*\.png)$','^\.'), $nohook=false, $mode= '')
Return file(s) into a directory (by default most recent)
dol_check_secure_access_document ($modulepart, $original_file, $entity, $fuser= '', $refname= '', $mode= 'read')
Security check when accessing to a document (used by document.php, viewimage.php and webservices)
dol_filecache ($directory, $filename, $object)
Store object in file.
dol_cache_refresh ($directory, $filename, $cachetime)
Test if Refresh needed.
dol_readcachefile ($directory, $filename)
Read object from cachefile.
getFilesUpdated (&$file_list, SimpleXMLElement $dir, $path= '', $pathref= '', &$checksumconcat=array())
Function to get list of updated or modified files.
Detailed Description
Library for file managing functions.
Definition in file files.lib.php.
Function Documentation
addFileIntoDatabaseIndex ($dir, $file, $fullpathorig = '', $mode = 'uploaded', $setsharekey = 0)
Add a file into database index.
Called by dol_add_file_process when uploading a file and on other cases. See also commonGenerateDocument that also add/update database index when a file is generated.
Parameters
string $dir Directory name (full real path without ending /)
string $file File name
string $fullpathorig Full path of origin for file (can be '')
string $mode How file was created ('uploaded', 'generated', ...)
int $setsharekey Set also the share key
Returns
int <0 if KO, 0 if nothing done, >0 if OK
Definition at line 1726 of file files.lib.php.
References dol_osencode(), dol_syslog(), and getRandomPassword().
Referenced by dol_add_file_process().
completeFileArrayWithDatabaseInfo (& $filearray, $relativedir)
Complete $filearray with data from database.
This will call doldir_list_indatabase to complate filearray.
Parameters
array $filearray Array of files get using dol_dir_list
string $relativedir Relative dir from DOL_DATA_ROOT
Returns
void
Definition at line 299 of file files.lib.php.
References dol_dir_list_in_database(), dol_osencode(), dol_syslog(), and setEventMessages().
Referenced by FormFile\list_of_documents().
deleteFilesIntoDatabaseIndex ($dir, $file, $mode = 'uploaded')
Delete files into database index using search criterias.
Parameters
string $dir Directory name (full real path without ending /)
string $file File name
string $mode How file was created ('uploaded', 'generated', ...)
Returns
int <0 if KO, 0 if nothing done, >0 if OK
Definition at line 1774 of file files.lib.php.
References $resql, and dol_syslog().
dol_add_file_process ($upload_dir, $allowoverwrite = 0, $donotupdatesession = 0, $varfiles = 'addedfile', $savingdocmask = '', $link = null, $trackid = '', $generatethumbs = 1)
Get and save an upload file (for example after submitting a new file a mail form).
Database index of file is also updated if donotupdatesession is set. All information used are in db, conf, langs, user and _FILES. Note: This function can be used only into a HTML page context.
Parameters
string $upload_dir Directory where to store uploaded file (note: used to forge $destpath = $upload_dir + filename)
int $allowoverwrite 1=Allow overwrite existing file
int $donotupdatesession 1=Do no edit _SESSION variable but update database index. 0=Update _SESSION and not database index. -1=Do not update SESSION neither db.
string $varfiles _FILES var name
string $savingdocmask Mask to use to define output filename. For example 'XXXXX-__YYYYMMDD__-__file__'
string $link Link to add (to add a link instead of a file)
string $trackid Track id (used to prefix name of session vars to avoid conflict)
int $generatethumbs 1=Generate also thumbs for uploaded image files
Returns
int <=0 if KO, >0 if OK
Definition at line 1524 of file files.lib.php.
References addFileIntoDatabaseIndex(), dol_mkdir(), dol_move_uploaded_file(), dol_sanitizeFileName(), dol_string_nohtmltag(), dol_syslog(), GETPOST(), image_format_supported(), setEventMessages(), and vignette().
dol_basename ($pathfile)
Make a basename working with all page code (default PHP basenamed fails with cyrillic).
We supose dir separator for input is '/'.
Parameters
string $pathfile String to find basename.
Returns
string Basename of input
Definition at line 36 of file files.lib.php.
Referenced by Documents\getDocumentsListByElement().
dol_cache_refresh ($directory, $filename, $cachetime)
Test if Refresh needed.
Parameters
string $directory Directory of cache
string $filename Name of filecache
int $cachetime Cachetime delay
Returns
boolean 0 no refresh 1 if refresh needed
Definition at line 3002 of file files.lib.php.
References dol_filemtime(), and dol_now().
Referenced by box_activity\loadBox(), and ModeleBoxes\showBox().
dol_check_secure_access_document ($modulepart, $original_file, $entity, $fuser = '', $refname = '', $mode = 'read')
Security check when accessing to a document (used by document.php, viewimage.php and webservices)
Parameters
string $modulepart Module of document ('module', 'module_user_temp', 'module_user' or 'module_temp')
string $original_file Relative path with filename, relative to modulepart.
string $entity Restrict onto entity (0=no restriction)
User $fuser User object (forced)
string $refname Ref of object to check permission for external users (autodetect if not provided)
string $mode Check permission for 'read' or 'write'
Returns
mixed Array with access information : 'accessallowed' & 'sqlprotectagainstexternals' & 'original_file' (as a full path name)
See also
restrictedArea()
Definition at line 2186 of file files.lib.php.
References dol_mimetype(), dol_print_error(), dol_syslog(), getEntity(), and GETPOST().
Referenced by Documents\builddoc(), getDocument(), Documents\getDocumentsListByElement(), Documents\index(), and llxFooter().
dol_compare_file ($a, $b)
Fast compare of 2 files identified by their properties ->name, ->date and ->size.
Parameters
string $a File 1
string $b File 2
Returns
int 1, 0, 1
Definition at line 399 of file files.lib.php.
dol_convert_file ($fileinput, $ext = 'png', $fileoutput = '', $page = '')
Convert an image file into another format.
This need Imagick php extension.
Parameters
string $fileinput Input file name
string $ext Format of target file (It is also extension added to file if fileoutput is not provided).
string $fileoutput Output filename
string $page Page number if we convert a PDF into png
Returns
int <0 if KO, 0=Nothing done, >0 if OK
Definition at line 1831 of file files.lib.php.
References dol_is_file(), dol_osencode(), and dol_syslog().
Referenced by dol_banner_tab().
dol_copy ($srcfile, $destfile, $newmask = 0, $overwriteifexists = 1)
Copy a file to another file.
Parameters
string $srcfile Source file (can't be a directory)
string $destfile Destination file (can't be a directory)
int $newmask Mask for new file (0 by default means $conf->global->MAIN_UMASK). Example: '0666'
int $overwriteifexists Overwrite file if exists (1 by default)
Returns
int <0 if error, 0 if nothing done (dest file already exists and overwriteifexists=0), >0 if OK
See also
dol_delete_file() dolCopyDir()
Definition at line 670 of file files.lib.php.
References dol_is_file(), dol_osencode(), and dol_syslog().
Referenced by Project\createFromClone(), Task\createFromClone(), dolCopyDir(), Utils\generateDoc(), modWebsite\init(), modSupplierProposal\init(), modContrat\init(), modReception\init(), modPropale\init(), modCommande\init(), modProjet\init(), modExpedition\init(), modStock\init(), modFacture\init(), modSociete\init(), migrate_user_photospath(), and InterfaceActionsAuto\runTrigger().
dol_count_nb_of_line ($file)
Count number of lines in a file.
Parameters
string $file Filename
Returns
int <0 if KO, Number of lines in files if OK
See also
dol_nboflines()
Definition at line 527 of file files.lib.php.
References dol_osencode().
Referenced by ImportCsv\import_get_nb_of_lines().
dol_delete_dir ($dir, $nophperrors = 0)
Remove a directory (not recursive, so content must be empty).
If directory is not empty, return false
Parameters
string $dir Directory to delete
int $nophperrors Disable all PHP output errors
Returns
boolean True if success, false if error
See also
dol_delete_file() dolCopyDir()
Definition at line 1254 of file files.lib.php.
References dol_osencode(), and dol_syslog().
Referenced by EcmDirectory\delete(), Livraison\delete(), and dol_delete_dir_recursive().
dol_delete_dir_recursive ($dir, $count = 0, $nophperrors = 0, $onlysub = 0, & $countdeleted = 0)
Remove a directory $dir and its subdirectories (or only files and subdirectories)
Parameters
string $dir Dir to delete
int $count Counter to count nb of elements found to delete
int $nophperrors Disable all PHP output errors
int $onlysub Delete only files and subdir, not main directory
int $countdeleted Counter to count nb of elements found really deleted
Returns
int Number of files and directory we try to remove. NB really removed is returned into var by reference $countdeleted.
Definition at line 1278 of file files.lib.php.
References dol_delete_dir(), dol_delete_file(), dol_is_dir(), dol_osencode(), dol_syslog(), and utf8_check().
Referenced by FormMail\clear_attached_files(), FormTicket\clear_attached_files(), Website\createFromClone(), EcmDirectory\delete(), Dolresource\delete(), Task\delete(), Website\delete(), Project\delete(), Reception\delete(), Fichinter\delete(), FactureFournisseur\delete(), Product\delete(), Contrat\delete(), Expedition\delete(), Societe\delete(), CommandeFournisseur\delete(), Facture\delete(), SupplierProposal\delete(), Propal\delete(), Commande\delete(), Website\exportWebSite(), Website\importWebSite(), migrate_delete_old_dir(), and Utils\purgeFiles().
dol_delete_file ($file, $disableglob = 0, $nophperrors = 0, $nohook = 0, $object = null, $allowdotdot = false, $indexdatabase = 1)
Remove a file or several files with a mask.
This delete file physically but also database indexes.
Parameters
string $file File to delete or mask of files to delete
int $disableglob Disable usage of glob like * so function is an exact delete function that will return error if no file found
int $nophperrors Disable all PHP output errors
int $nohook Disable all hooks
object $object Current object in use
boolean $allowdotdot Allow to delete file path with .. inside. Never use this, it is reserved for migration purpose.
int $indexdatabase Try to remove also index entries.
Returns
boolean True if no error (file is deleted or if glob is used and there's nothing to delete), False if error
See also
dol_delete_dir()
Definition at line 1144 of file files.lib.php.
References dol_osencode(), dol_syslog(), and setEventMessages().
Referenced by ActionComm\build_exportfile(), Utils\compressSyslogs(), Website\createFromClone(), WebsitePage\delete(), Livraison\delete(), Reception\delete(), Fichinter\delete(), FactureFournisseur\delete(), Expedition\delete(), CommandeFournisseur\delete(), Facture\delete(), SupplierProposal\delete(), Propal\delete(), Commande\delete(), Categorie\delete_photo(), Product\delete_photo(), dol_delete_dir_recursive(), dol_delete_preview(), dol_move(), dol_remove_file_process(), dolReplaceInFile(), dolSaveIndexPage(), dolSaveMasterFile(), dolSavePageContent(), Utils\dumpDatabase(), Website\exportWebSite(), Documents\getDocumentsListByElement(), migrate_delete_old_files(), and Utils\purgeFiles().
dol_delete_preview ($object)
Delete all preview files linked to object instance.
Note that preview image of PDF files is generated when required, by dol_banner_tab() for example.
Parameters
object $object Object to clean
Returns
int 0 if error, 1 if OK
See also
dol_convert_file()
Definition at line 1329 of file files.lib.php.
References dol_delete_file(), and dol_sanitizeFileName().
Referenced by Fichinter\delete(), Facture\delete(), SupplierProposal\delete(), Propal\delete(), Commande\delete(), fichinter_create(), Don\generateDocument(), and ModeleAction\liste_modeles().
dol_dir_is_emtpy ($folder)
Test if a folder is empty.
Parameters
string $folder Name of folder
Returns
boolean True if dir is empty or non-existing, False if it contains files
Definition at line 498 of file files.lib.php.
References dol_osencode().
dol_dir_list ($path, $types = "all", $recursive = 0, $filter = "", $excludefilter = null, $sortcriteria = "name", $sortorder = SORT_ASC, $mode = 0, $nohook = 0, $relativename = "", $donotfollowsymlinks = 0)
Scan a directory and return a list of files/directories.
Content for string is UTF8 and dir separator is "/".
Parameters
string $path Starting path from which to search. This is a full path.
string $types Can be "directories", "files", or "all"
int $recursive Determines whether subdirectories are searched
string $filter Regex filter to restrict list. This regex value must be escaped for '/' by doing preg_quote($var,'/'), since this char is used for preg_match function, but must not contains the start and end '/'. Filter is checked into basename only.
array $excludefilter Array of Regex for exclude filter (example: array('(.meta|_preview.*.png)$','^.')). Exclude is checked both into fullpath and into basename (So '^xxx' may exclude 'xxx/dirscanned/...' and dirscanned/xxx').
string $sortcriteria Sort criteria ('','fullname','relativename','name','date','size')
string $sortorder Sort order (SORT_ASC, SORT_DESC)
int $mode 0=Return array minimum keys loaded (faster), 1=Force all keys like date and size to be loaded (slower), 2=Force load of date only, 3=Force load of size only
int $nohook Disable all hooks
string $relativename For recursive purpose only. Must be "" at first call.
string $donotfollowsymlinks Do not follow symbolic links
Returns
array Array of array('name'=>'xxx','fullname'=>'/abc/xxx','date'=>'yyy','size'=>99,'type'=>'dir|file',...)
See also
dol_dir_list_in_database()
Definition at line 60 of file files.lib.php.
References dol_filemtime(), dol_filesize(), dol_osencode(), dol_sort_array(), dol_syslog(), and utf8_check().
Referenced by actions_prepare_head(), asset_prepare_head(), bank_prepare_head(), bomPrepareHead(), commande_prepare_head(), complete_substitutions_array(), Utils\compressSyslogs(), contact_prepare_head(), contract_prepare_head(), Project\createFromClone(), Task\createFromClone(), dol_init_file_process(), dol_most_recent_file(), donation_prepare_head(), Utils\dumpDatabase(), expensereport_prepare_head(), facture_prepare_head(), facturefourn_prepare_head(), fichinter_prepare_head(), Utils\generateDoc(), Setup\getCheckIntegrity(), FormFile\getDocumentsLink(), Documents\getDocumentsListByElement(), getListOfModels(), holiday_prepare_head(), doc_generic_odt\info(), doc_generic_reception_odt\info(), doc_generic_user_odt\info(), doc_generic_proposal_odt\info(), doc_generic_product_odt\info(), doc_generic_stock_odt\info(), doc_generic_supplier_proposal_odt\info(), doc_generic_usergroup_odt\info(), doc_generic_contract_odt\info(), doc_generic_order_odt\info(), doc_generic_invoice_odt\info(), doc_generic_shipment_odt\info(), doc_generic_task_odt\info(), doc_generic_project_odt\info(), modWebsite\init(), PrintingDriver\listDrivers(), loan_prepare_head(), member_prepare_head(), myobjectPrepareHead(), ordersupplier_prepare_head(), product_prepare_head(), productlot_prepare_head(), project_prepare_head(), propal_prepare_head(), Utils\purgeFiles(), EcmDirectory\refreshcachenboffile(), resource_prepare_head(), FormEcm\selectAllSections(), FormWebsite\selectSampleOfContainer(), Fichinter\setValid(), ExpenseReport\setValidate(), shipping_prepare_head(), FormFile\showdocuments(), societe_prepare_head(), task_prepare_head(), tax_prepare_head(), ticket_prepare_head(), user_prepare_head(), Commande\valid(), Livraison\valid(), Reception\valid(), CommandeFournisseur\valid(), BOM\valid(), Expedition\valid(), SupplierProposal\valid(), Propal\valid(), Contrat\validate(), FactureFournisseur\validate(), Facture\validate(), various_payment_prepare_head(), vat_prepare_head(), doc_generic_task_odt\write_file(), and doc_generic_project_odt\write_file().
dol_dir_list_in_database ($path, $filter = "", $excludefilter = null, $sortcriteria = "name", $sortorder = SORT_ASC, $mode = 0)
Scan a directory and return a list of files/directories.
Content for string is UTF8 and dir separator is "/".
Parameters
string $path Starting path from which to search. Example: 'produit/MYPROD'
string $filter Regex filter to restrict list. This regex value must be escaped for '/', since this char is used for preg_match function
array | null $excludefilter Array of Regex for exclude filter (example: array('(.meta|_preview.*.png)$','^.'))
string $sortcriteria Sort criteria ("","fullname","name","date","size")
string $sortorder Sort order (SORT_ASC, SORT_DESC)
int $mode 0=Return array minimum keys loaded (faster), 1=Force all keys like description
Returns
array Array of array('name'=>'xxx','fullname'=>'/abc/xxx','type'=>'dir|file',...)
See also
dol_dir_list()
Definition at line 224 of file files.lib.php.
References $resql, and dol_print_error().
Referenced by completeFileArrayWithDatabaseInfo().
dol_filecache ($directory, $filename, $object)
Store object in file.
Parameters
string $directory Directory of cache
string $filename Name of filecache
mixed $object Object to store in cachefile
Returns
void
Definition at line 2986 of file files.lib.php.
References dol_is_dir(), and dol_mkdir().
Referenced by box_activity\loadBox(), and ModeleBoxes\showBox().
dol_filemtime ($pathoffile)
Return time of a file.
Parameters
string $pathoffile Path of file
Returns
int Time of file
Definition at line 572 of file files.lib.php.
References dol_osencode().
Referenced by ActionComm\build_exportfile(), dol_cache_refresh(), dol_dir_list(), Stats\getAllByProductEntry(), Stats\getAmountByMonthWithPrevYear(), Setup\getCheckIntegrity(), Stats\getNbByMonthWithPrevYear(), ProjectStats\getTransformRateByMonthWithPrevYear(), ProjectStats\getWeightedAmountByMonthWithPrevYear(), RssParser\parser(), and FormFile\showdocuments().
dol_filesize ($pathoffile)
Return size of a file.
Parameters
string $pathoffile Path of file
Returns
integer File size
See also
dol_print_size()
Definition at line 560 of file files.lib.php.
References dol_osencode().
Referenced by Utils\compressSyslogs(), dol_dir_list(), Setup\getCheckIntegrity(), llxFooter(), FormFile\showdocuments(), and showWebsiteTemplates().
dol_init_file_process ($pathtoscan = '', $trackid = '')
Scan a directory and init $_SESSION to manage uploaded files with list of all found files.
Note: Only email module seems to use this. Other feature initialize the $_SESSION doing $formmail->clear_attached_files(); $formmail->add_attached_files()
Parameters
string $pathtoscan Path to scan
string $trackid Track id (used to prefix name of session vars to avoid conflict)
Returns
void
Definition at line 1486 of file files.lib.php.
References dol_dir_list(), and dol_mimetype().
dol_is_dir ($folder)
Test if filename is a directory.
Parameters
string $folder Name of folder
Returns
boolean True if it's a directory, False if not found
Definition at line 433 of file files.lib.php.
References dol_osencode().
Referenced by complete_substitutions_array(), Ticket\copyFilesForTicket(), Societe\delete(), dol_delete_dir_recursive(), dol_filecache(), dol_uncompress(), dolCopyDir(), Utils\generateDoc(), Stats\getAllByProductEntry(), Stats\getAmountByMonthWithPrevYear(), Documents\getDocumentsListByElement(), Stats\getNbByMonthWithPrevYear(), ProjectStats\getTransformRateByMonthWithPrevYear(), ProjectStats\getWeightedAmountByMonthWithPrevYear(), migrate_user_photospath(), RssParser\parser(), and treeOutputForAbsoluteDir().
dol_is_dir_empty ($dir)
Return if path is empty.
Parameters
string $dir Path of Directory
Returns
boolean True or false
Definition at line 446 of file files.lib.php.
dol_is_file ($pathoffile)
Return if path is a file.
Parameters
string $pathoffile Path of file
Returns
boolean True or false
Definition at line 458 of file files.lib.php.
References dol_osencode().
Referenced by Utils\compressSyslogs(), dol_convert_file(), dol_copy(), dol_move(), dolReplaceInFile(), DolibarrModules\getChangeLog(), Setup\getCheckIntegrity(), DolibarrModules\getDescLongReadmeFound(), Documents\getDocumentsListByElement(), Ticket\is_photo_available(), Product\is_photo_available(), FormFile\list_of_documents(), Categorie\liste_photos(), Product\liste_photos(), llxFooter(), migrate_user_photospath(), rebuild_merge_pdf(), and Notify\send().
dol_is_link ($pathoffile)
Return if path is a symbolic link.
Parameters
string $pathoffile Path of file
Returns
boolean True or false
Definition at line 470 of file files.lib.php.
References dol_osencode().
dol_is_url ($url)
Return if path is an URL.
Parameters
string $url Url
Returns
boolean True or false
Definition at line 482 of file files.lib.php.
Referenced by RssParser\parser().
dol_meta_create ($object)
Create a meta file with document file into same directory.
This make "grep" search possible. This feature to generate the meta file is enabled only if option MAIN_DOC_CREATE_METAFILE is set.
Parameters
CommonObject $object Object
Returns
int 0 if do nothing, >0 if we update meta file too, <0 if KO
Definition at line 1407 of file files.lib.php.
References dol_mkdir(), dol_print_date(), dol_sanitizeFileName(), and dol_syslog().
dol_most_recent_file ($dir, $regexfilter = '', $excludefilter = array('(\.meta|_preview.*\.png)$','^\.'), $nohook = false, $mode = '')
Return file(s) into a directory (by default most recent)
Parameters
string $dir Directory to scan
string $regexfilter Regex filter to restrict list. This regex value must be escaped for '/', since this char is used for preg_match function
array $excludefilter Array of Regex for exclude filter (example: array('(.meta|_preview.*.png)$','^.')). This regex value must be escaped for '/', since this char is used for preg_match function
int $nohook Disable all hooks
int $mode 0=Return array minimum keys loaded (faster), 1=Force all keys like date and size to be loaded (slower), 2=Force load of date only, 3=Force load of size only
Returns
string Full path to most recent file
Definition at line 2168 of file files.lib.php.
References dol_dir_list().
dol_move ($srcfile, $destfile, $newmask = 0, $overwriteifexists = 1, $testvirus = 0, $indexdatabase = 1)
Move a file into another name.
Note:
This function differs from dol_move_uploaded_file, because it can be called in any context.
Database indexes for files are updated.
Test on antivirus is done only if param testvirus is provided and an antivirus was set.
Parameters
string $srcfile Source file (can't be a directory. use native php () to move a directory)
string $destfile Destination file (can't be a directory. use native php () to move a directory)
integer $newmask Mask in octal string for new file (0 by default means $conf->global->MAIN_UMASK)
int $overwriteifexists Overwrite file if exists (1 by default)
int $testvirus Do an antivirus test. Move is canceled if a virus is found.
int $indexdatabase Index new file into database.
Returns
boolean True if OK, false if KO
See also
dol_move_uploaded_file()
Definition at line 818 of file files.lib.php.
References dol_delete_file(), dol_is_file(), dol_osencode(), dol_syslog(), dolCheckVirus(), and setEventMessages().
Referenced by ActionComm\build_exportfile(), Utils\compressSyslogs(), Ticket\copyFilesForTicket(), dolReplaceInFile(), Documents\getDocumentsListByElement(), Website\importWebSite(), and Task\update().
dol_move_uploaded_file ($src_file, $dest_file, $allowoverwrite, $disablevirusscan = 0, $uploaderrorcode = 0, $nohook = 0, $varfiles = 'addedfile')
Make control on an uploaded file from an GUI page and move it to final destination.
If there is errors (virus found, antivir in error, bad filename), file is not moved. Note:
This function can be used only into a HTML page context. Use dol_move if you are outside.
Test on antivirus is always done (if antivirus set).
Database of files is NOT updated (this is done by dol_add_file_process() that calls this function).
Extension .noexe may be added if file is executable and MAIN_DOCUMENT_IS_OUTSIDE_WEBROOT_SO_NOEXE_NOT_REQUIRED is not set.
Parameters
string $src_file Source full path filename ($_FILES['field']['tmp_name'])
string $dest_file Target full path filename ($_FILES['field']['name'])
int $allowoverwrite 1=Overwrite target file if it already exists
int $disablevirusscan 1=Disable virus scan
integer $uploaderrorcode Value of PHP upload error code ($_FILES['field']['error'])
int $nohook Disable all hooks
string $varfiles _FILES var name
Returns
int >0 if OK, <0 or string if KO
See also
dol_move()
Definition at line 1001 of file files.lib.php.
References dol_osencode(), dol_syslog(), dolCheckVirus(), and isAFileWithExecutableContent().
Referenced by Categorie\add_photo(), Product\add_photo(), mailing_xinputfile\add_to_target(), dol_add_file_process(), and FileUpload\handleFileUpload().
dol_readcachefile ($directory, $filename)
Read object from cachefile.
Parameters
string $directory Directory of cache
string $filename Name of filecache
Returns
mixed Unserialise from file
Definition at line 3017 of file files.lib.php.
Referenced by box_activity\loadBox(), and ModeleBoxes\showBox().
dol_remove_file_process ($filenb, $donotupdatesession = 0, $donotdeletefile = 1, $trackid = '')
Remove an uploaded file (for example after submitting a new file a mail form).
All information used are in db, conf, langs, user and _FILES.
Parameters
int $filenb File nb to delete
int $donotupdatesession -1 or 1 = Do not update _SESSION variable
int $donotdeletefile 1=Do not delete physically file
string $trackid Track id (used to prefix name of session vars to avoid conflict)
Returns
void
Definition at line 1674 of file files.lib.php.
References dol_delete_file(), and setEventMessages().
dol_uncompress ($inputfile, $outputdir)
Uncompress a file.
Parameters
string $inputfile File to uncompress
string $outputdir Target dir name
Returns
array array('error'=>'Error code') or array() if no error
Definition at line 2007 of file files.lib.php.
References dol_is_dir(), and dol_syslog().
Referenced by Website\importWebSite().
dol_unescapefile ($filename)
Unescape a file submitted by upload.
PHP escape char " (%22) or char ' (%27) into $FILES.
Parameters
string $filename Filename
Returns
string Filename sanitized
Definition at line 946 of file files.lib.php.
dolCheckVirus ($src_file)
Check virus into a file.
Parameters
string $src_file Source file to check
Returns
array Array of errors or empty array if not virus found
Definition at line 961 of file files.lib.php.
Referenced by dol_move(), and dol_move_uploaded_file().
dolCopyDir ($srcfile, $destfile, $newmask, $overwriteifexists, $arrayreplacement = null)
Copy a dir to another dir.
This include recursive subdirectories.
Parameters
string $srcfile Source file (a directory)
string $destfile Destination file (a directory)
int $newmask Mask for new file (0 by default means $conf->global->MAIN_UMASK). Example: '0666'
int $overwriteifexists Overwrite file if exists (1 by default)
array $arrayreplacement Array to use to replace filenames with another one during the copy (works only on file names, not on directory names).
Returns
int <0 if error, 0 if nothing done (all files already exists and overwriteifexists=0), >0 if OK
See also
dol_copy()
Definition at line 726 of file files.lib.php.
References dol_copy(), dol_is_dir(), dol_mkdir(), dol_osencode(), and dol_syslog().
Referenced by Website\createFromClone(), Website\exportWebSite(), Website\importWebSite(), and modWebsite\init().
dolReplaceInFile ($srcfile, $arrayreplacement, $destfile = '', $newmask = 0, $indexdatabase = 0, $arrayreplacementisregex = 0)
Make replacement of strings into a file.
Parameters
string $srcfile Source file (can't be a directory)
array $arrayreplacement Array with strings to replace. Example: array('valuebefore'=>'valueafter', ...)
string $destfile Destination file (can't be a directory). If empty, will be same than source file.
int $newmask Mask for new file (0 by default means $conf->global->MAIN_UMASK). Example: '0666'
int $indexdatabase 1=index new file into database.
int $arrayreplacementisregex 1=Array of replacement is regex
Returns
int <0 if error, 0 if nothing done (dest file already exists), >0 if OK
See also
dol_copy()
Definition at line 590 of file files.lib.php.
References dol_delete_file(), dol_is_file(), dol_move(), dol_osencode(), dol_syslog(), and make_substitutions().
Referenced by Website\exportWebSite(), Utils\generateDoc(), and Website\importWebSite().
getFilesUpdated (& $file_list, SimpleXMLElement $dir, $path = '', $pathref = '', & $checksumconcat = array())
Function to get list of updated or modified files.
$file_list is used as global variable
Parameters
array $file_list Array for response
SimpleXMLElement $dir SimpleXMLElement of files to test
string $path Path of files relative to $pathref. We start with ''. Used by recursive calls.
string $pathref Path ref (DOL_DOCUMENT_ROOT)
array $checksumconcat Array of checksum
Returns
array Array of filenames
Definition at line 3036 of file files.lib.php.
Referenced by Setup\getCheckIntegrity().